{
  "hash": "cf8687cfd18f0c189e84b00715fc7a2c",
  "result": {
    "engine": "knitr",
    "markdown": "---\ntitle: \"Lab 12: Advanced Logistic Regression\"\n---\n\n\n\n\n## Goals\n\n::: {.callout-note}\n## What You'll Learn in This Lab\n- Fit and interpret interactions in logistic regression\n- Conduct Wald tests and likelihood ratio (LR) tests for logistic models\n- Assess goodness-of-fit using the Pearson chi-square test\n- Compute predicted probabilities at specific covariate values\n- **Lecture Notes Reference:** Chapter 10: *Multiple Logistic Regression* and Chapter 11: *Logistic Diagnostics*\n:::\n\n::: {.callout-tip}\n## Stata → R Translation\n| Stata | R | Notes |\n|:------|:--|:------|\n| `logit ... i.female#c.age` | `glm(... ~ female * age)` | Interaction in logistic |\n| `testparm female` | `car::Anova(type = \"III\")` | Wald test for predictor |\n| `lrtest model1 model2` | `anova(m1, m2, test = \"LRT\")` | Likelihood ratio test |\n| `estat gof, table` | Manual Pearson chi-square | Goodness-of-fit test |\n| `margins female, at(age = 45)` | `marginaleffects::predictions()` | Predicted probabilities |\n:::\n\n**Dataset:** `titanic` from the `regdatasets` package\n\nWelcome to the final lab of BER 640. We have come a long way --- from simple regression lines in Lab 1 to the full machinery of logistic regression. In this lab we bring it all together: interactions, hypothesis tests, goodness-of-fit, and predicted probabilities. By the end, you will have every tool you need to build, test, and communicate a logistic regression analysis from start to finish.\n\n\n## Setup\n\n\n::: {.cell}\n\n```{.r .cell-code}\nlibrary(regdatasets)\ndata(titanic)\n\n# Rename sex to female (already coded 0 = male, 1 = female)\ntitanic <- titanic |>\n  rename(female = sex) |>\n  mutate(pclass_f = factor(pclass, labels = c(\"1st\", \"2nd\", \"3rd\")))\n\nglimpse(titanic)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nRows: 1,309\nColumns: 7\n$ pclass   <int> 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1…\n$ survived <int> 1, 1, 0, 0, 0, 1, 1, 0, 1, 0, 0, 1, 1, 1, 1, 0, 0, 1, 1, 0, 1…\n$ age      <dbl> 29.0000, 0.9167, 2.0000, 30.0000, 25.0000, 48.0000, 63.0000, …\n$ fare     <dbl> 211.3375, 151.5500, 151.5500, 151.5500, 151.5500, 26.5500, 77…\n$ embarked <chr> \"S\", \"S\", \"S\", \"S\", \"S\", \"S\", \"S\", \"S\", \"C\", \"C\", \"C\", \"C\", \"…\n$ female   <int> 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 0, 1, 1, 1, 0, 0, 0, 1, 1, 0, 0…\n$ pclass_f <fct> 1st, 1st, 1st, 1st, 1st, 1st, 1st, 1st, 1st, 1st, 1st, 1st, 1…\n```\n\n\n:::\n:::\n\n\n\n## Part 1: Multiple Logistic Regression\n\nBefore we tackle interactions, let's fit a clean multiple logistic regression and make sure we can interpret every piece of it.\n\n### Step 1: Fit the Model\n\n\n::: {.cell}\n\n```{.r .cell-code}\nmodel1 <- glm(survived ~ female + age, data = titanic, family = binomial)\n```\n:::\n\n\n:::: {.panel-tabset}\n\n#### Simple\n\n\n::: {.cell}\n\n```{.r .cell-code}\nsummary(model1)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\nCall:\nglm(formula = survived ~ female + age, family = binomial, data = titanic)\n\nCoefficients:\n             Estimate Std. Error z value Pr(>|z|)    \n(Intercept) -1.225275   0.183985  -6.660 2.74e-11 ***\nfemale       2.460689   0.152315  16.155  < 2e-16 ***\nage         -0.004254   0.005207  -0.817    0.414    \n---\nSignif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1\n\n(Dispersion parameter for binomial family taken to be 1)\n\n    Null deviance: 1414.6  on 1045  degrees of freedom\nResidual deviance: 1101.3  on 1043  degrees of freedom\n  (263 observations deleted due to missingness)\nAIC: 1107.3\n\nNumber of Fisher Scoring iterations: 4\n```\n\n\n:::\n:::\n\n\n#### Advanced\n\n\n::: {.cell}\n\n```{.r .cell-code}\nmodel1 |>\n  tbl_regression(exponentiate = TRUE) |>\n  bold_labels() |>\n  bold_p(t = 0.05)\n```\n\n::: {.cell-output-display}\n\n```{=html}\n<div id=\"oprdvkwuzb\" style=\"padding-left:0px;padding-right:0px;padding-top:10px;padding-bottom:10px;overflow-x:auto;overflow-y:auto;width:auto;height:auto;\">\n<style>#oprdvkwuzb table {\n  font-family: system-ui, 'Segoe UI', Roboto, Helvetica, Arial, sans-serif, 'Apple Color Emoji', 'Segoe UI Emoji', 'Segoe UI Symbol', 'Noto Color Emoji';\n  -webkit-font-smoothing: antialiased;\n  -moz-osx-font-smoothing: grayscale;\n}\n\n#oprdvkwuzb thead, #oprdvkwuzb tbody, #oprdvkwuzb tfoot, #oprdvkwuzb tr, #oprdvkwuzb td, #oprdvkwuzb th {\n  border-style: none;\n}\n\n#oprdvkwuzb p {\n  margin: 0;\n  padding: 0;\n}\n\n#oprdvkwuzb .gt_table {\n  display: table;\n  border-collapse: collapse;\n  line-height: normal;\n  margin-left: auto;\n  margin-right: auto;\n  color: #333333;\n  font-size: 16px;\n  font-weight: normal;\n  font-style: normal;\n  background-color: #FFFFFF;\n  width: auto;\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #A8A8A8;\n  border-right-style: none;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #A8A8A8;\n  border-left-style: none;\n  border-left-width: 2px;\n  border-left-color: #D3D3D3;\n}\n\n#oprdvkwuzb .gt_caption {\n  padding-top: 4px;\n  padding-bottom: 4px;\n}\n\n#oprdvkwuzb .gt_title {\n  color: #333333;\n  font-size: 125%;\n  font-weight: initial;\n  padding-top: 4px;\n  padding-bottom: 4px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-bottom-color: #FFFFFF;\n  border-bottom-width: 0;\n}\n\n#oprdvkwuzb .gt_subtitle {\n  color: #333333;\n  font-size: 85%;\n  font-weight: initial;\n  padding-top: 3px;\n  padding-bottom: 5px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-top-color: #FFFFFF;\n  border-top-width: 0;\n}\n\n#oprdvkwuzb .gt_heading {\n  background-color: #FFFFFF;\n  text-align: center;\n  border-bottom-color: #FFFFFF;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n}\n\n#oprdvkwuzb .gt_bottom_border {\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n}\n\n#oprdvkwuzb .gt_col_headings {\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n}\n\n#oprdvkwuzb .gt_col_heading {\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: normal;\n  text-transform: inherit;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n  vertical-align: bottom;\n  padding-top: 5px;\n  padding-bottom: 6px;\n  padding-left: 5px;\n  padding-right: 5px;\n  overflow-x: hidden;\n}\n\n#oprdvkwuzb .gt_column_spanner_outer {\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: normal;\n  text-transform: inherit;\n  padding-top: 0;\n  padding-bottom: 0;\n  padding-left: 4px;\n  padding-right: 4px;\n}\n\n#oprdvkwuzb .gt_column_spanner_outer:first-child {\n  padding-left: 0;\n}\n\n#oprdvkwuzb .gt_column_spanner_outer:last-child {\n  padding-right: 0;\n}\n\n#oprdvkwuzb .gt_column_spanner {\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  vertical-align: bottom;\n  padding-top: 5px;\n  padding-bottom: 5px;\n  overflow-x: hidden;\n  display: inline-block;\n  width: 100%;\n}\n\n#oprdvkwuzb .gt_spanner_row {\n  border-bottom-style: hidden;\n}\n\n#oprdvkwuzb .gt_group_heading {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: initial;\n  text-transform: inherit;\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n  vertical-align: middle;\n  text-align: left;\n}\n\n#oprdvkwuzb .gt_empty_group_heading {\n  padding: 0.5px;\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: initial;\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  vertical-align: middle;\n}\n\n#oprdvkwuzb .gt_from_md > :first-child {\n  margin-top: 0;\n}\n\n#oprdvkwuzb .gt_from_md > :last-child {\n  margin-bottom: 0;\n}\n\n#oprdvkwuzb .gt_row {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  margin: 10px;\n  border-top-style: solid;\n  border-top-width: 1px;\n  border-top-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n  vertical-align: middle;\n  overflow-x: hidden;\n}\n\n#oprdvkwuzb .gt_stub {\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: initial;\n  text-transform: inherit;\n  border-right-style: solid;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#oprdvkwuzb .gt_stub_row_group {\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: initial;\n  text-transform: inherit;\n  border-right-style: solid;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n  padding-left: 5px;\n  padding-right: 5px;\n  vertical-align: top;\n}\n\n#oprdvkwuzb .gt_row_group_first td {\n  border-top-width: 2px;\n}\n\n#oprdvkwuzb .gt_row_group_first th {\n  border-top-width: 2px;\n}\n\n#oprdvkwuzb .gt_summary_row {\n  color: #333333;\n  background-color: #FFFFFF;\n  text-transform: inherit;\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#oprdvkwuzb .gt_first_summary_row {\n  border-top-style: solid;\n  border-top-color: #D3D3D3;\n}\n\n#oprdvkwuzb .gt_first_summary_row.thick {\n  border-top-width: 2px;\n}\n\n#oprdvkwuzb .gt_last_summary_row {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n}\n\n#oprdvkwuzb .gt_grand_summary_row {\n  color: #333333;\n  background-color: #FFFFFF;\n  text-transform: inherit;\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#oprdvkwuzb .gt_first_grand_summary_row {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-top-style: double;\n  border-top-width: 6px;\n  border-top-color: #D3D3D3;\n}\n\n#oprdvkwuzb .gt_last_grand_summary_row_top {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-bottom-style: double;\n  border-bottom-width: 6px;\n  border-bottom-color: #D3D3D3;\n}\n\n#oprdvkwuzb .gt_striped {\n  background-color: rgba(128, 128, 128, 0.05);\n}\n\n#oprdvkwuzb .gt_table_body {\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n}\n\n#oprdvkwuzb .gt_footnotes {\n  color: #333333;\n  background-color: #FFFFFF;\n  border-bottom-style: none;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 2px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n}\n\n#oprdvkwuzb .gt_footnote {\n  margin: 0px;\n  font-size: 90%;\n  padding-top: 4px;\n  padding-bottom: 4px;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#oprdvkwuzb .gt_sourcenotes {\n  color: #333333;\n  background-color: #FFFFFF;\n  border-bottom-style: none;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 2px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n}\n\n#oprdvkwuzb .gt_sourcenote {\n  font-size: 90%;\n  padding-top: 4px;\n  padding-bottom: 4px;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#oprdvkwuzb .gt_left {\n  text-align: left;\n}\n\n#oprdvkwuzb .gt_center {\n  text-align: center;\n}\n\n#oprdvkwuzb .gt_right {\n  text-align: right;\n  font-variant-numeric: tabular-nums;\n}\n\n#oprdvkwuzb .gt_font_normal {\n  font-weight: normal;\n}\n\n#oprdvkwuzb .gt_font_bold {\n  font-weight: bold;\n}\n\n#oprdvkwuzb .gt_font_italic {\n  font-style: italic;\n}\n\n#oprdvkwuzb .gt_super {\n  font-size: 65%;\n}\n\n#oprdvkwuzb .gt_footnote_marks {\n  font-size: 75%;\n  vertical-align: 0.4em;\n  position: initial;\n}\n\n#oprdvkwuzb .gt_asterisk {\n  font-size: 100%;\n  vertical-align: 0;\n}\n\n#oprdvkwuzb .gt_indent_1 {\n  text-indent: 5px;\n}\n\n#oprdvkwuzb .gt_indent_2 {\n  text-indent: 10px;\n}\n\n#oprdvkwuzb .gt_indent_3 {\n  text-indent: 15px;\n}\n\n#oprdvkwuzb .gt_indent_4 {\n  text-indent: 20px;\n}\n\n#oprdvkwuzb .gt_indent_5 {\n  text-indent: 25px;\n}\n\n#oprdvkwuzb .katex-display {\n  display: inline-flex !important;\n  margin-bottom: 0.75em !important;\n}\n\n#oprdvkwuzb div.Reactable > div.rt-table > div.rt-thead > div.rt-tr.rt-tr-group-header > div.rt-th-group:after {\n  height: 0px !important;\n}\n</style>\n<table class=\"gt_table\" data-quarto-disable-processing=\"false\" data-quarto-bootstrap=\"false\">\n  <thead>\n    <tr class=\"gt_col_headings\">\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_left\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"label\"><span data-qmd-base64=\"KipDaGFyYWN0ZXJpc3RpYyoq\"><span class='gt_from_md'><strong>Characteristic</strong></span></span></th>\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_center\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"estimate\"><span data-qmd-base64=\"KipPUioq\"><span class='gt_from_md'><strong>OR</strong></span></span></th>\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_center\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"conf.low\"><span data-qmd-base64=\"Kio5NSUgQ0kqKg==\"><span class='gt_from_md'><strong>95% CI</strong></span></span></th>\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_center\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"p.value\"><span data-qmd-base64=\"KipwLXZhbHVlKio=\"><span class='gt_from_md'><strong>p-value</strong></span></span></th>\n    </tr>\n  </thead>\n  <tbody class=\"gt_table_body\">\n    <tr><td headers=\"label\" class=\"gt_row gt_left\" style=\"font-weight: bold;\">female</td>\n<td headers=\"estimate\" class=\"gt_row gt_center\">11.7</td>\n<td headers=\"conf.low\" class=\"gt_row gt_center\">8.72, 15.9</td>\n<td headers=\"p.value\" class=\"gt_row gt_center\" style=\"font-weight: bold;\"><0.001</td></tr>\n    <tr><td headers=\"label\" class=\"gt_row gt_left\" style=\"font-weight: bold;\">age in years</td>\n<td headers=\"estimate\" class=\"gt_row gt_center\">1.00</td>\n<td headers=\"conf.low\" class=\"gt_row gt_center\">0.99, 1.01</td>\n<td headers=\"p.value\" class=\"gt_row gt_center\">0.4</td></tr>\n  </tbody>\n  <tfoot class=\"gt_sourcenotes\">\n    <tr>\n      <td class=\"gt_sourcenote\" colspan=\"4\"><span data-qmd-base64=\"QWJicmV2aWF0aW9uczogQ0kgPSBDb25maWRlbmNlIEludGVydmFsLCBPUiA9IE9kZHMgUmF0aW8=\"><span class='gt_from_md'>Abbreviations: CI = Confidence Interval, OR = Odds Ratio</span></span></td>\n    </tr>\n  </tfoot>\n  \n</table>\n</div>\n```\n\n:::\n:::\n\n\n::::\n\n### Step 2: Odds Ratios and Confidence Intervals\n\n\n::: {.cell}\n\n```{.r .cell-code}\nexp(coef(model1))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n(Intercept)      female         age \n  0.2936769  11.7128810   0.9957548 \n```\n\n\n:::\n\n```{.r .cell-code}\nexp(confint(model1))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n                2.5 %     97.5 %\n(Intercept) 0.2037794  0.4194266\nfemale      8.7239838 15.8549675\nage         0.9855965  1.0059398\n```\n\n\n:::\n:::\n\n\n> Let's interpret each predictor:\n>\n> - **female:** Controlling for age, females had about 11.7 times the odds of survival compared to males. The 95% CI is well above 1, confirming this is a large and significant effect.\n> - **age:** Each additional year of age is associated with an OR of about 0.996. That is, older passengers had slightly lower odds of survival, holding gender constant.\n\n::: {.callout-tip}\n## The \"Controlling For\" Logic\nIn this model, the OR for `female` compares a female and male passenger **of the same age**. The OR for `age` describes the effect of aging one year for passengers **of the same gender**. This \"all else equal\" interpretation is the power of multiple regression.\n:::\n\n### Step 3: Predicted Probability Curves by Gender\n\nThis is the plot that makes logistic regression click for most audiences. We show how the predicted probability of survival changes with age, separately for males and females.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nnew_data <- expand.grid(\n  age    = seq(1, 70, length.out = 200),\n  female = c(0, 1)\n)\n\npreds <- predict(model1, newdata = new_data, type = \"link\", se.fit = TRUE)\n\nnew_data <- new_data |>\n  mutate(\n    prob    = plogis(preds$fit),\n    ci_low  = plogis(preds$fit - 1.96 * preds$se.fit),\n    ci_high = plogis(preds$fit + 1.96 * preds$se.fit),\n    gender_label = if_else(female == 1, \"Female\", \"Male\")\n  )\n\nggplot(new_data, aes(x = age, y = prob, color = gender_label, fill = gender_label)) +\n  geom_ribbon(aes(ymin = ci_low, ymax = ci_high), alpha = 0.15, color = NA) +\n  geom_line(linewidth = 1.2) +\n  scale_color_manual(values = c(\"Female\" = ber640_colors[\"secondary\"],\n                                \"Male\"   = ber640_colors[\"accent\"])) +\n  scale_fill_manual(values = c(\"Female\" = ber640_colors[\"secondary\"],\n                               \"Male\"   = ber640_colors[\"accent\"])) +\n  labs(x = \"Age\", y = \"Predicted P(Survived)\",\n       color = \"Gender\", fill = \"Gender\",\n       title = \"Survival Probability by Age and Gender\",\n       subtitle = \"No interaction: curves are parallel on the log-odds scale\") +\n  scale_y_continuous(limits = c(0, 1), labels = scales::percent)\n```\n\n::: {.cell-output-display}\n![Predicted probability of survival by age and gender (no interaction)](lab12-logistic-advanced_files/figure-html/pred-curves-gender-1.png){fig-alt='Two S-shaped predicted probability curves for females and males showing survival decreasing with age, with females consistently higher and the curves parallel on the log-odds scale' width=2400}\n:::\n:::\n\n\n> Notice that the two curves never cross and maintain a roughly constant vertical gap. That is because, without an interaction term, the **log-odds** difference between males and females is the same at every age. The curves look parallel on the log-odds scale (though not exactly parallel on the probability scale due to the logistic transformation). Is that assumption realistic? Let's find out.\n\n\n## Part 2: Interactions in Logistic Regression\n\nIn linear regression (Lab 6), we learned that an interaction means the slope of one predictor depends on the level of another. The same idea applies in logistic regression, but now the interaction operates on the **log-odds** scale.\n\n### Step 1: Fit the Interaction Model\n\n\n::: {.cell}\n\n```{.r .cell-code}\nmodel2 <- glm(survived ~ female * age, data = titanic, family = binomial)\n```\n:::\n\n\n:::: {.panel-tabset}\n\n#### Simple\n\n\n::: {.cell}\n\n```{.r .cell-code}\nsummary(model2)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\nCall:\nglm(formula = survived ~ female * age, family = binomial, data = titanic)\n\nCoefficients:\n             Estimate Std. Error z value Pr(>|z|)    \n(Intercept) -0.660758   0.224807  -2.939 0.003290 ** \nfemale       1.154139   0.339337   3.401 0.000671 ***\nage         -0.023760   0.007276  -3.266 0.001092 ** \nfemale:age   0.046276   0.011216   4.126 3.69e-05 ***\n---\nSignif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1\n\n(Dispersion parameter for binomial family taken to be 1)\n\n    Null deviance: 1414.6  on 1045  degrees of freedom\nResidual deviance: 1083.4  on 1042  degrees of freedom\n  (263 observations deleted due to missingness)\nAIC: 1091.4\n\nNumber of Fisher Scoring iterations: 4\n```\n\n\n:::\n:::\n\n\n#### Advanced\n\n\n::: {.cell}\n\n```{.r .cell-code}\nmodel2 |>\n  tbl_regression(exponentiate = TRUE) |>\n  bold_labels() |>\n  bold_p(t = 0.05)\n```\n\n::: {.cell-output-display}\n\n```{=html}\n<div id=\"fqfeyzarts\" style=\"padding-left:0px;padding-right:0px;padding-top:10px;padding-bottom:10px;overflow-x:auto;overflow-y:auto;width:auto;height:auto;\">\n<style>#fqfeyzarts table {\n  font-family: system-ui, 'Segoe UI', Roboto, Helvetica, Arial, sans-serif, 'Apple Color Emoji', 'Segoe UI Emoji', 'Segoe UI Symbol', 'Noto Color Emoji';\n  -webkit-font-smoothing: antialiased;\n  -moz-osx-font-smoothing: grayscale;\n}\n\n#fqfeyzarts thead, #fqfeyzarts tbody, #fqfeyzarts tfoot, #fqfeyzarts tr, #fqfeyzarts td, #fqfeyzarts th {\n  border-style: none;\n}\n\n#fqfeyzarts p {\n  margin: 0;\n  padding: 0;\n}\n\n#fqfeyzarts .gt_table {\n  display: table;\n  border-collapse: collapse;\n  line-height: normal;\n  margin-left: auto;\n  margin-right: auto;\n  color: #333333;\n  font-size: 16px;\n  font-weight: normal;\n  font-style: normal;\n  background-color: #FFFFFF;\n  width: auto;\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #A8A8A8;\n  border-right-style: none;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #A8A8A8;\n  border-left-style: none;\n  border-left-width: 2px;\n  border-left-color: #D3D3D3;\n}\n\n#fqfeyzarts .gt_caption {\n  padding-top: 4px;\n  padding-bottom: 4px;\n}\n\n#fqfeyzarts .gt_title {\n  color: #333333;\n  font-size: 125%;\n  font-weight: initial;\n  padding-top: 4px;\n  padding-bottom: 4px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-bottom-color: #FFFFFF;\n  border-bottom-width: 0;\n}\n\n#fqfeyzarts .gt_subtitle {\n  color: #333333;\n  font-size: 85%;\n  font-weight: initial;\n  padding-top: 3px;\n  padding-bottom: 5px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-top-color: #FFFFFF;\n  border-top-width: 0;\n}\n\n#fqfeyzarts .gt_heading {\n  background-color: #FFFFFF;\n  text-align: center;\n  border-bottom-color: #FFFFFF;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n}\n\n#fqfeyzarts .gt_bottom_border {\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n}\n\n#fqfeyzarts .gt_col_headings {\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n}\n\n#fqfeyzarts .gt_col_heading {\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: normal;\n  text-transform: inherit;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n  vertical-align: bottom;\n  padding-top: 5px;\n  padding-bottom: 6px;\n  padding-left: 5px;\n  padding-right: 5px;\n  overflow-x: hidden;\n}\n\n#fqfeyzarts .gt_column_spanner_outer {\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: normal;\n  text-transform: inherit;\n  padding-top: 0;\n  padding-bottom: 0;\n  padding-left: 4px;\n  padding-right: 4px;\n}\n\n#fqfeyzarts .gt_column_spanner_outer:first-child {\n  padding-left: 0;\n}\n\n#fqfeyzarts .gt_column_spanner_outer:last-child {\n  padding-right: 0;\n}\n\n#fqfeyzarts .gt_column_spanner {\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  vertical-align: bottom;\n  padding-top: 5px;\n  padding-bottom: 5px;\n  overflow-x: hidden;\n  display: inline-block;\n  width: 100%;\n}\n\n#fqfeyzarts .gt_spanner_row {\n  border-bottom-style: hidden;\n}\n\n#fqfeyzarts .gt_group_heading {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: initial;\n  text-transform: inherit;\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n  vertical-align: middle;\n  text-align: left;\n}\n\n#fqfeyzarts .gt_empty_group_heading {\n  padding: 0.5px;\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: initial;\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  vertical-align: middle;\n}\n\n#fqfeyzarts .gt_from_md > :first-child {\n  margin-top: 0;\n}\n\n#fqfeyzarts .gt_from_md > :last-child {\n  margin-bottom: 0;\n}\n\n#fqfeyzarts .gt_row {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  margin: 10px;\n  border-top-style: solid;\n  border-top-width: 1px;\n  border-top-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n  vertical-align: middle;\n  overflow-x: hidden;\n}\n\n#fqfeyzarts .gt_stub {\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: initial;\n  text-transform: inherit;\n  border-right-style: solid;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#fqfeyzarts .gt_stub_row_group {\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: initial;\n  text-transform: inherit;\n  border-right-style: solid;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n  padding-left: 5px;\n  padding-right: 5px;\n  vertical-align: top;\n}\n\n#fqfeyzarts .gt_row_group_first td {\n  border-top-width: 2px;\n}\n\n#fqfeyzarts .gt_row_group_first th {\n  border-top-width: 2px;\n}\n\n#fqfeyzarts .gt_summary_row {\n  color: #333333;\n  background-color: #FFFFFF;\n  text-transform: inherit;\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#fqfeyzarts .gt_first_summary_row {\n  border-top-style: solid;\n  border-top-color: #D3D3D3;\n}\n\n#fqfeyzarts .gt_first_summary_row.thick {\n  border-top-width: 2px;\n}\n\n#fqfeyzarts .gt_last_summary_row {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n}\n\n#fqfeyzarts .gt_grand_summary_row {\n  color: #333333;\n  background-color: #FFFFFF;\n  text-transform: inherit;\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#fqfeyzarts .gt_first_grand_summary_row {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-top-style: double;\n  border-top-width: 6px;\n  border-top-color: #D3D3D3;\n}\n\n#fqfeyzarts .gt_last_grand_summary_row_top {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-bottom-style: double;\n  border-bottom-width: 6px;\n  border-bottom-color: #D3D3D3;\n}\n\n#fqfeyzarts .gt_striped {\n  background-color: rgba(128, 128, 128, 0.05);\n}\n\n#fqfeyzarts .gt_table_body {\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n}\n\n#fqfeyzarts .gt_footnotes {\n  color: #333333;\n  background-color: #FFFFFF;\n  border-bottom-style: none;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 2px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n}\n\n#fqfeyzarts .gt_footnote {\n  margin: 0px;\n  font-size: 90%;\n  padding-top: 4px;\n  padding-bottom: 4px;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#fqfeyzarts .gt_sourcenotes {\n  color: #333333;\n  background-color: #FFFFFF;\n  border-bottom-style: none;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 2px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n}\n\n#fqfeyzarts .gt_sourcenote {\n  font-size: 90%;\n  padding-top: 4px;\n  padding-bottom: 4px;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#fqfeyzarts .gt_left {\n  text-align: left;\n}\n\n#fqfeyzarts .gt_center {\n  text-align: center;\n}\n\n#fqfeyzarts .gt_right {\n  text-align: right;\n  font-variant-numeric: tabular-nums;\n}\n\n#fqfeyzarts .gt_font_normal {\n  font-weight: normal;\n}\n\n#fqfeyzarts .gt_font_bold {\n  font-weight: bold;\n}\n\n#fqfeyzarts .gt_font_italic {\n  font-style: italic;\n}\n\n#fqfeyzarts .gt_super {\n  font-size: 65%;\n}\n\n#fqfeyzarts .gt_footnote_marks {\n  font-size: 75%;\n  vertical-align: 0.4em;\n  position: initial;\n}\n\n#fqfeyzarts .gt_asterisk {\n  font-size: 100%;\n  vertical-align: 0;\n}\n\n#fqfeyzarts .gt_indent_1 {\n  text-indent: 5px;\n}\n\n#fqfeyzarts .gt_indent_2 {\n  text-indent: 10px;\n}\n\n#fqfeyzarts .gt_indent_3 {\n  text-indent: 15px;\n}\n\n#fqfeyzarts .gt_indent_4 {\n  text-indent: 20px;\n}\n\n#fqfeyzarts .gt_indent_5 {\n  text-indent: 25px;\n}\n\n#fqfeyzarts .katex-display {\n  display: inline-flex !important;\n  margin-bottom: 0.75em !important;\n}\n\n#fqfeyzarts div.Reactable > div.rt-table > div.rt-thead > div.rt-tr.rt-tr-group-header > div.rt-th-group:after {\n  height: 0px !important;\n}\n</style>\n<table class=\"gt_table\" data-quarto-disable-processing=\"false\" data-quarto-bootstrap=\"false\">\n  <thead>\n    <tr class=\"gt_col_headings\">\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_left\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"label\"><span data-qmd-base64=\"KipDaGFyYWN0ZXJpc3RpYyoq\"><span class='gt_from_md'><strong>Characteristic</strong></span></span></th>\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_center\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"estimate\"><span data-qmd-base64=\"KipPUioq\"><span class='gt_from_md'><strong>OR</strong></span></span></th>\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_center\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"conf.low\"><span data-qmd-base64=\"Kio5NSUgQ0kqKg==\"><span class='gt_from_md'><strong>95% CI</strong></span></span></th>\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_center\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"p.value\"><span data-qmd-base64=\"KipwLXZhbHVlKio=\"><span class='gt_from_md'><strong>p-value</strong></span></span></th>\n    </tr>\n  </thead>\n  <tbody class=\"gt_table_body\">\n    <tr><td headers=\"label\" class=\"gt_row gt_left\" style=\"font-weight: bold;\">female</td>\n<td headers=\"estimate\" class=\"gt_row gt_center\">3.17</td>\n<td headers=\"conf.low\" class=\"gt_row gt_center\">1.63, 6.19</td>\n<td headers=\"p.value\" class=\"gt_row gt_center\" style=\"font-weight: bold;\"><0.001</td></tr>\n    <tr><td headers=\"label\" class=\"gt_row gt_left\" style=\"font-weight: bold;\">age in years</td>\n<td headers=\"estimate\" class=\"gt_row gt_center\">0.98</td>\n<td headers=\"conf.low\" class=\"gt_row gt_center\">0.96, 0.99</td>\n<td headers=\"p.value\" class=\"gt_row gt_center\" style=\"font-weight: bold;\">0.001</td></tr>\n    <tr><td headers=\"label\" class=\"gt_row gt_left\" style=\"font-weight: bold;\">female * age in years</td>\n<td headers=\"estimate\" class=\"gt_row gt_center\">1.05</td>\n<td headers=\"conf.low\" class=\"gt_row gt_center\">1.02, 1.07</td>\n<td headers=\"p.value\" class=\"gt_row gt_center\" style=\"font-weight: bold;\"><0.001</td></tr>\n  </tbody>\n  <tfoot class=\"gt_sourcenotes\">\n    <tr>\n      <td class=\"gt_sourcenote\" colspan=\"4\"><span data-qmd-base64=\"QWJicmV2aWF0aW9uczogQ0kgPSBDb25maWRlbmNlIEludGVydmFsLCBPUiA9IE9kZHMgUmF0aW8=\"><span class='gt_from_md'>Abbreviations: CI = Confidence Interval, OR = Odds Ratio</span></span></td>\n    </tr>\n  </tfoot>\n  \n</table>\n</div>\n```\n\n:::\n:::\n\n\n::::\n\n### Step 2: Interpret the Interaction\n\n\n::: {.cell}\n\n```{.r .cell-code}\nround(coef(model2), 4)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n(Intercept)      female         age  female:age \n    -0.6608      1.1541     -0.0238      0.0463 \n```\n\n\n:::\n:::\n\n\n> In the model `survived ~ female * age`, R creates four terms:\n>\n> - `(Intercept)`: log-odds of survival for a male (female = 0) at age = 0\n> - `female`: the **difference** in log-odds between female and male **at age = 0**\n> - `age`: the effect of age **for males** (female = 0)\n> - `female:age`: how much the age effect **changes** for females compared to males\n\nThe interaction term `female:age` tells us whether the age-survival relationship differs by gender. If it is non-zero, the OR of being female is not constant --- it depends on age.\n\n### Step 3: Compute the OR of Female at Specific Ages\n\nBecause of the interaction, we cannot report a single OR for `female`. Instead, the OR depends on age:\n$$\\text{OR}_{\\text{female at age} = a} = \\exp\\!\\bigl(b_{\\text{female}} + b_{\\text{female:age}} \\times a\\bigr)$$\n\n\n::: {.cell}\n\n```{.r .cell-code}\nb <- coef(model2)\n\nages <- c(5, 20, 40, 60)\n\nor_female <- tibble(\n  Age = ages,\n  log_OR = b[\"female\"] + b[\"female:age\"] * ages,\n  OR     = exp(log_OR)\n) |>\n  mutate(across(where(is.numeric), \\(x) round(x, 3)))\n\nknitr::kable(or_female, col.names = c(\"Age\", \"Log OR\", \"OR of Female vs. Male\"))\n```\n\n::: {.cell-output-display}\n\n\n| Age| Log OR| OR of Female vs. Male|\n|---:|------:|---------------------:|\n|   5|  1.386|                 3.997|\n|  20|  2.080|                 8.002|\n|  40|  3.005|                20.189|\n|  60|  3.931|                50.941|\n\n\n:::\n:::\n\n\n> The OR of being female **decreases** with age. For a 5-year-old, the female advantage is enormous. For a 60-year-old, it is smaller (though still substantial). This makes historical sense --- \"women and children first\" meant young women and girls had the highest survival advantage.\n\n### Step 4: Predicted Probability Curves with Interaction\n\n\n::: {.cell}\n\n```{.r .cell-code}\nnew_data2 <- expand.grid(\n  age    = seq(1, 70, length.out = 200),\n  female = c(0, 1)\n)\n\npreds2 <- predict(model2, newdata = new_data2, type = \"link\", se.fit = TRUE)\n\nnew_data2 <- new_data2 |>\n  mutate(\n    prob    = plogis(preds2$fit),\n    ci_low  = plogis(preds2$fit - 1.96 * preds2$se.fit),\n    ci_high = plogis(preds2$fit + 1.96 * preds2$se.fit),\n    gender_label = if_else(female == 1, \"Female\", \"Male\")\n  )\n\nggplot(new_data2, aes(x = age, y = prob, color = gender_label, fill = gender_label)) +\n  geom_ribbon(aes(ymin = ci_low, ymax = ci_high), alpha = 0.15, color = NA) +\n  geom_line(linewidth = 1.2) +\n  scale_color_manual(values = c(\"Female\" = ber640_colors[\"secondary\"],\n                                \"Male\"   = ber640_colors[\"accent\"])) +\n  scale_fill_manual(values = c(\"Female\" = ber640_colors[\"secondary\"],\n                               \"Male\"   = ber640_colors[\"accent\"])) +\n  labs(x = \"Age\", y = \"Predicted P(Survived)\",\n       color = \"Gender\", fill = \"Gender\",\n       title = \"Survival Probability by Age and Gender (with Interaction)\",\n       subtitle = \"The gender gap narrows with age\") +\n  scale_y_continuous(limits = c(0, 1), labels = scales::percent)\n```\n\n::: {.cell-output-display}\n![Predicted probability with interaction: non-parallel curves](lab12-logistic-advanced_files/figure-html/interaction-curves-1.png){fig-alt='Two predicted probability curves for females and males showing non-parallel patterns where the gender gap in survival narrows with increasing age, reflecting the interaction effect' width=2400}\n:::\n:::\n\n\n> Compare this to the no-interaction plot from Part 1. Now the curves are **not parallel** --- the gap between males and females is wider for younger passengers and narrower for older ones. That is the interaction in action: the effect of gender depends on age.\n\n### Step 5: Predicted Comparisons at Specific Ages\n\nThe `marginaleffects` package can compute the female-vs-male comparison at any age we choose:\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Predicted probability difference (female - male) at specific ages\ncomparisons_age <- comparisons(\n  model2,\n  variables = \"female\",\n  newdata = datagrid(age = c(10, 20, 40, 60))\n)\n\ncomparisons_age |>\n  as.data.frame() |>\n  select(age, estimate, std.error, p.value, conf.low, conf.high) |>\n  mutate(across(where(is.numeric), \\(x) round(x, 4))) |>\n  knitr::kable()\n```\n\n::: {.cell-output-display}\n\n\n| age| estimate| std.error| p.value| conf.low| conf.high|\n|---:|--------:|---------:|-------:|--------:|---------:|\n|  10|   0.3829|    0.0524|       0|   0.2803|    0.4855|\n|  20|   0.4768|    0.0335|       0|   0.4111|    0.5425|\n|  40|   0.6348|    0.0322|       0|   0.5717|    0.6979|\n|  60|   0.7530|    0.0443|       0|   0.6662|    0.8399|\n\n\n:::\n:::\n\n\n> These are the **marginal effects** of being female (vs. male) on the probability scale at each age. The effect is largest for young passengers and shrinks as age increases. This is a clean way to communicate how an interaction plays out in practice.\n\n\n## Part 3: Hypothesis Testing\n\nWe have two main tools for testing predictors in logistic regression: the **Wald test** and the **likelihood ratio (LR) test**. Both ask the same question --- does this predictor matter? --- but they go about it differently.\n\n### Wald Test\n\nThe Wald test uses the estimated coefficients and their standard errors. It is the default test reported in `summary()`. For testing **sets** of predictors (e.g., all terms involving `female`), we use `car::Anova()`:\n\n\n::: {.cell}\n\n```{.r .cell-code}\ncar::Anova(model2, type = \"III\")\n```\n\n::: {.cell-output-display}\n<div class=\"kable-table\">\n\n|           | LR Chisq| Df| Pr(>Chisq)|\n|:----------|--------:|--:|----------:|\n|female     | 11.68851|  1|  0.0006289|\n|age        | 11.29006|  1|  0.0007792|\n|female:age | 17.90320|  1|  0.0000232|\n\n</div>\n:::\n:::\n\n\n> Type III sums of squares test each predictor **adjusting for all others**. The `female` row tests whether the main effect of female is significant (at age = 0, which is extrapolation --- be cautious). The `female:age` row tests whether the interaction is significant.\n\n::: {.callout-tip}\n## Wald Test vs. z-Test in summary()\nThe z-tests in `summary(model2)` and the Wald chi-square tests in `car::Anova()` are closely related. For a single-coefficient predictor, $\\chi^2 = z^2$. The advantage of `car::Anova()` is that it can test multi-degree-of-freedom predictors (like a 3-level factor) with a single test.\n:::\n\n### Likelihood Ratio Test\n\n::: {.callout-warning}\n## Same Sample Required for Likelihood Ratio Tests\nWhen comparing two nested models with a likelihood ratio test, both models **must be fit on exactly the same observations**. If one model drops observations due to missing values that the other retains, the test is invalid. Always filter to complete cases first, then fit both models on that filtered dataset.\n:::\n\nThe LR test compares the fit of two nested models: one with the predictor and one without. It is generally considered more reliable than the Wald test, especially in small samples.\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# IMPORTANT: Both models must use the same observations!\n# First, identify complete cases for the full model\ntitanic_cc <- titanic |>\n  filter(complete.cases(survived, female, age))\n\n# Fit both models on the SAME data\nmodel_full    <- glm(survived ~ female * age, data = titanic_cc, family = binomial)\nmodel_reduced <- glm(survived ~ female + age, data = titanic_cc, family = binomial)\n\nnobs(model_full)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 1046\n```\n\n\n:::\n\n```{.r .cell-code}\nnobs(model_reduced)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 1046\n```\n\n\n:::\n:::\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nanova(model_reduced, model_full, test = \"LRT\")\n```\n\n::: {.cell-output-display}\n<div class=\"kable-table\">\n\n| Resid. Df| Resid. Dev| Df| Deviance| Pr(>Chi)|\n|---------:|----------:|--:|--------:|--------:|\n|      1043|   1101.339| NA|       NA|       NA|\n|      1042|   1083.436|  1|  17.9032| 2.32e-05|\n\n</div>\n:::\n:::\n\n\n> The LR test compares the deviance of the reduced model (no interaction) to the full model (with interaction). A significant p-value means the interaction term improves model fit.\n\n::: {.callout-important}\n## The Same-Sample Trap\nBoth models in a likelihood ratio test **must** be fit on identical observations. If the reduced model uses a different sample (e.g., because it has fewer missing values), the deviances are not comparable. Always filter to complete cases first. Here is what can go wrong:\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# BAD: different samples if 'age' has missing values\nmodel_wrong <- glm(survived ~ female, data = titanic, family = binomial)\n\ncat(\"Full model N: \", nobs(model_full), \"\\n\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nFull model N:  1046 \n```\n\n\n:::\n\n```{.r .cell-code}\ncat(\"Wrong reduced model N:\", nobs(model_wrong), \"\\n\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nWrong reduced model N: 1309 \n```\n\n\n:::\n:::\n\n\nIf these Ns differ, `anova()` may give you a misleading result. Always check.\n:::\n\n### Testing a Set of Predictors\n\nWe can also use LR tests to ask broader questions, like \"does gender matter at all?\" (testing both the main effect and the interaction together):\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Remove ALL terms involving female\nmodel_age_only <- glm(survived ~ age, data = titanic_cc, family = binomial)\n\nanova(model_age_only, model_full, test = \"LRT\")\n```\n\n::: {.cell-output-display}\n<div class=\"kable-table\">\n\n| Resid. Df| Resid. Dev| Df| Deviance| Pr(>Chi)|\n|---------:|----------:|--:|--------:|--------:|\n|      1044|   1411.383| NA|       NA|       NA|\n|      1042|   1083.436|  2| 327.9469|        0|\n\n</div>\n:::\n:::\n\n\n> This tests 2 degrees of freedom (the main effect of `female` and the `female:age` interaction jointly). The highly significant result confirms that gender matters for survival, even after accounting for age.\n\n\n## Part 4: Goodness-of-Fit\n\nHow do we know our logistic model fits the data adequately? For models with only categorical predictors (or a small number of covariate patterns), we can use the **Pearson chi-square** goodness-of-fit test.\n\n### Step 1: A Model with Categorical Predictors Only\n\n\n::: {.cell}\n\n```{.r .cell-code}\nmodel_gof <- glm(survived ~ female + pclass_f, data = titanic, family = binomial)\nsummary(model_gof)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\nCall:\nglm(formula = survived ~ female + pclass_f, family = binomial, \n    data = titanic)\n\nCoefficients:\n            Estimate Std. Error z value Pr(>|z|)    \n(Intercept)  -0.4059     0.1374  -2.954  0.00313 ** \nfemale        2.5150     0.1467  17.145  < 2e-16 ***\npclass_f2nd  -0.8808     0.1977  -4.456 8.34e-06 ***\npclass_f3rd  -1.7231     0.1715 -10.047  < 2e-16 ***\n---\nSignif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1\n\n(Dispersion parameter for binomial family taken to be 1)\n\n    Null deviance: 1741.0  on 1308  degrees of freedom\nResidual deviance: 1257.2  on 1305  degrees of freedom\nAIC: 1265.2\n\nNumber of Fisher Scoring iterations: 4\n```\n\n\n:::\n:::\n\n\n> With only `female` (binary) and `pclass_f` (3 levels), there are $2 \\times 3 = 6$ unique covariate patterns. The Pearson chi-square test compares observed and expected frequencies within each pattern.\n\n### Step 2: Manual Pearson Chi-Square Test\n\nThis follows the same approach used in the Homework Solutions book:\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Step 1: Get per-row predicted probabilities using augment()\ntitanic_augmented <- broom::augment(model_gof, type.predict = \"response\")\n\n# Step 2: Aggregate by covariate pattern (unique predictor combinations)\ngof_table <- titanic_augmented |>\n  group_by(female, pclass_f) |>\n  summarise(\n    n = n(),\n    obs_1 = sum(survived),\n    pred_prob = first(.fitted),  # same for all rows in the pattern\n    .groups = \"drop\"\n  ) |>\n  mutate(\n    exp_1 = n * pred_prob,\n    exp_0 = n * (1 - pred_prob),\n    obs_0 = n - obs_1\n  )\n\ngof_table |>\n  mutate(across(where(is.numeric), \\(x) round(x, 3))) |>\n  knitr::kable()\n```\n\n::: {.cell-output-display}\n\n\n| female|pclass_f |   n| obs_1| pred_prob|   exp_1|   exp_0| obs_0|\n|------:|:--------|---:|-----:|---------:|-------:|-------:|-----:|\n|      0|1st      | 179|    61|     0.400|  71.583| 107.417|   118|\n|      0|2nd      | 171|    25|     0.216|  37.007| 133.993|   146|\n|      0|3rd      | 493|    75|     0.106|  52.411| 440.589|   418|\n|      1|1st      | 144|   139|     0.892| 128.417|  15.583|     5|\n|      1|2nd      | 106|    94|     0.774|  81.993|  24.007|    12|\n|      1|3rd      | 216|   106|     0.595| 128.589|  87.411|   110|\n\n\n:::\n:::\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Grouped Pearson chi-square\nn_patterns <- nrow(gof_table)\nn_params <- length(coef(model_gof))\ndf_gof <- n_patterns - n_params\n\npearson_chisq <- sum(\n  (gof_table$obs_1 - gof_table$exp_1)^2 / gof_table$exp_1 +\n  (gof_table$obs_0 - gof_table$exp_0)^2 / gof_table$exp_0\n)\np_gof <- pchisq(pearson_chisq, df = df_gof, lower.tail = FALSE)\n\ncat(\"Number of covariate patterns:\", n_patterns, \"\\n\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nNumber of covariate patterns: 6 \n```\n\n\n:::\n\n```{.r .cell-code}\ncat(\"Number of parameters:\", n_params, \"\\n\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nNumber of parameters: 4 \n```\n\n\n:::\n\n```{.r .cell-code}\ncat(\"Pearson chi2(\", df_gof, \") =\", round(pearson_chisq, 2), \"\\n\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nPearson chi2( 2 ) = 44.1 \n```\n\n\n:::\n\n```{.r .cell-code}\ncat(\"p-value =\", round(p_gof, 4), \"\\n\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\np-value = 0 \n```\n\n\n:::\n:::\n\n\n> A **non-significant** p-value means we fail to reject the null hypothesis that the model fits adequately. That is good news --- it means our model's predicted probabilities are consistent with the observed data.\n\n::: {.callout-note}\n## What Would Lack of Fit Mean?\nIf the Pearson test were significant, it would suggest our model is missing something important. The most common culprit is a **missing interaction**. For example, if the effect of gender on survival differs across passenger classes, we would need to add a `female:pclass_f` interaction. A significant goodness-of-fit test is a signal to reconsider the model specification.\n:::\n\n::: {.callout-tip}\n## When to Use the Pearson Test\nThe Pearson chi-square goodness-of-fit test works best when there are few unique covariate patterns (i.e., categorical predictors only or a small number of grouped continuous predictors). When you have continuous predictors that create many unique patterns, alternative approaches like the Hosmer-Lemeshow test (which groups observations by predicted probability) are more appropriate.\n:::\n\n\n## Part 5: Predicted Probabilities at Specific Values\n\nFor your final report or presentation, you often want to present a clean table of predicted probabilities at substantively meaningful covariate values. The `marginaleffects` package makes this straightforward.\n\n### Step 1: Predictions at a Grid of Values\n\n\n::: {.cell}\n\n```{.r .cell-code}\nmodel_final <- glm(survived ~ female + age + pclass_f, data = titanic, family = binomial)\n\npred_table <- predictions(\n  model_final,\n  newdata = datagrid(\n    female   = c(0, 1),\n    age      = c(10, 25, 40, 60),\n    pclass_f = c(\"1st\", \"2nd\", \"3rd\")\n  )\n)\n\npred_table |>\n  select(female, age, pclass_f, estimate, conf.low, conf.high) |>\n  mutate(\n    Gender = if_else(female == 1, \"Female\", \"Male\"),\n    across(c(estimate, conf.low, conf.high), \\(x) round(x, 3))\n  ) |>\n  select(Gender, Age = age, Class = pclass_f,\n         `P(Survived)` = estimate,\n         `95% CI Lower` = conf.low,\n         `95% CI Upper` = conf.high) |>\n  knitr::kable()\n```\n\n::: {.cell-output-display}\n\n\n|Gender | Age|Class | P(Survived)| 95% CI Lower| 95% CI Upper|\n|:------|---:|:-----|-----------:|------------:|------------:|\n|Male   |  10|1st   |       0.664|        0.550|        0.761|\n|Male   |  10|2nd   |       0.354|        0.270|        0.448|\n|Male   |  10|3rd   |       0.167|        0.126|        0.217|\n|Male   |  25|1st   |       0.541|        0.453|        0.627|\n|Male   |  25|2nd   |       0.247|        0.191|        0.312|\n|Male   |  25|3rd   |       0.107|        0.082|        0.138|\n|Male   |  40|1st   |       0.413|        0.343|        0.487|\n|Male   |  40|2nd   |       0.164|        0.120|        0.218|\n|Male   |  40|3rd   |       0.067|        0.047|        0.093|\n|Male   |  60|1st   |       0.261|        0.194|        0.343|\n|Male   |  60|2nd   |       0.089|        0.056|        0.141|\n|Male   |  60|3rd   |       0.035|        0.020|        0.059|\n|Female |  10|1st   |       0.960|        0.933|        0.976|\n|Female |  10|2nd   |       0.870|        0.812|        0.911|\n|Female |  10|3rd   |       0.709|        0.635|        0.772|\n|Female |  25|1st   |       0.935|        0.903|        0.957|\n|Female |  25|2nd   |       0.799|        0.735|        0.851|\n|Female |  25|3rd   |       0.592|        0.522|        0.659|\n|Female |  40|1st   |       0.895|        0.855|        0.926|\n|Female |  40|2nd   |       0.704|        0.620|        0.776|\n|Female |  40|3rd   |       0.464|        0.379|        0.551|\n|Female |  60|1st   |       0.811|        0.735|        0.869|\n|Female |  60|2nd   |       0.544|        0.416|        0.667|\n|Female |  60|3rd   |       0.303|        0.204|        0.426|\n\n\n:::\n:::\n\n\n> This table tells a vivid story. A 10-year-old girl in 1st class had a very high predicted probability of survival. An older male in 3rd class had a very low one. These specific numbers bring the model to life in a way that a single odds ratio never could.\n\n### Step 2: An Alternative with emmeans\n\nIf you prefer `emmeans`, you can get predicted probabilities at specific covariate values using the `at` argument:\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Using emmeans with specific covariate values\n# Note: emmeans works best with factor predictors;\n# for continuous covariates, use cov.reduce = list(age = c(25, 50))\nem_pred <- emmeans(\n  model_gof,\n  ~ female | pclass_f,\n  type = \"response\"\n)\n\nas.data.frame(em_pred) |>\n  mutate(\n    Gender = if_else(female == 1, \"Female\", \"Male\"),\n    across(c(prob, asymp.LCL, asymp.UCL), \\(x) round(x, 3))\n  ) |>\n  select(Gender, Class = pclass_f,\n         `P(Survived)` = prob,\n         `95% CI Lower` = asymp.LCL,\n         `95% CI Upper` = asymp.UCL) |>\n  knitr::kable()\n```\n\n::: {.cell-output-display}\n\n\n|Gender |Class | P(Survived)| 95% CI Lower| 95% CI Upper|\n|:------|:-----|-----------:|------------:|------------:|\n|Male   |1st   |       0.400|        0.337|        0.466|\n|Female |1st   |       0.892|        0.855|        0.920|\n|Male   |2nd   |       0.216|        0.169|        0.273|\n|Female |2nd   |       0.774|        0.710|        0.827|\n|Male   |3rd   |       0.106|        0.085|        0.132|\n|Female |3rd   |       0.595|        0.537|        0.651|\n\n\n:::\n:::\n\n\n> Note that `predictions()` above uses `model_final` (which includes `age`), while `emmeans()` here uses `model_gof` (which does not include `age`). The predicted probabilities will differ because the models are different. Both approaches are valid --- just be sure to use the model that matches your research question.\n\n\n## Key Takeaways\n\n::: {.callout-note}\n## What We Learned\n\n1. **Interactions in logistic regression** mean the odds ratio of one predictor depends on the value of another. With `female * age`, the female survival advantage was larger for younger passengers than older ones.\n\n2. **Wald tests** (`car::Anova(type = \"III\")`) use the estimated coefficients and SEs to test predictors. They are convenient but can be unreliable in small samples.\n\n3. **Likelihood ratio tests** (`anova(reduced, full, test = \"LRT\")`) compare the deviance of nested models. They are generally preferred over Wald tests. **Critical rule:** both models must be fit on the exact same observations.\n\n4. **Goodness-of-fit** via the Pearson chi-square test tells you whether the model's predictions match the observed data. A non-significant result is reassuring. A significant result suggests a missing predictor or interaction.\n\n5. **Always report OR + CI + p-value** for each predictor. For interactions, report the OR at meaningful values of the moderator rather than a single \"overall\" OR.\n\n6. **Predicted probability tables** at specific covariate values are the clearest way to communicate your results to a non-statistical audience.\n:::\n\n::: {.callout-important}\n## Congratulations\nYou have now completed all 12 labs in the BER 640 R Lab Manual. You can fit and interpret linear and logistic regression models, check assumptions, handle interactions, test hypotheses, and communicate results through tables and plots. These are the core skills of applied regression analysis --- and they will serve you well in any research context that involves quantitative data.\n:::\n",
    "supporting": [
      "lab12-logistic-advanced_files"
    ],
    "filters": [
      "rmarkdown/pagebreak.lua"
    ],
    "includes": {},
    "engineDependencies": {},
    "preserve": {},
    "postProcess": true
  }
}