{
  "hash": "50a0e7249e324e1a9a14136b53349c22",
  "result": {
    "engine": "knitr",
    "markdown": "---\ntitle: \"Homework 4: Multiple Dummies and One-Way ANOVA\"\n---\n\n\n\n\n## Overview\n\n::: {.callout-note}\n## Learning Objectives\n- Use multiple dummy variables to represent a multi-category predictor\n- Understand the equivalence of regression with dummies and one-way ANOVA\n- Perform and interpret the overall $F$-test for group differences\n- Conduct pairwise comparisons with Sidak correction for multiple testing\n- **Related:** Chapter 3: *One-Way ANOVA* (in Lecture Notes)\n:::\n\n::: {.callout-tip}\n## Stata-to-R Translation\n| Stata Command | R Equivalent | Used In |\n|:---|:---|:---|\n| `regress wleread uk germany` | `lm(wleread ~ uk + germany, data = pisa_3)` | Problem 1 |\n| `anova wleread country` | `aov(wleread ~ country_f)` + `summary()` | Problem 2a |\n| `oneway wleread country, sidak` | `emmeans(model, pairwise ~ country_f, adjust = \"sidak\")` | Problem 2c |\n:::\n\n**Dataset:** `pisa2000` from the `regdatasets` package (USA, UK, Germany; $N = 4{,}528$)\n\n## Setup\n\n\n::: {.cell}\n\n```{.r .cell-code  code-fold=\"true\" code-summary=\"Show R Code\"}\n# Load emmeans for pairwise comparisons (Sidak correction)\npacman::p_load(emmeans)\n\ndata(pisa2000)\n\n# Filter to three countries and create a factor variable\n# USA is the reference level (first in levels)\npisa_3 <- pisa2000 |>\n  filter(usa == 1 | uk == 1 | germany == 1) |>\n  mutate(country_f = factor(\n    case_when(usa == 1 ~ \"USA\", uk == 1 ~ \"UK\", germany == 1 ~ \"Germany\"),\n    levels = c(\"USA\", \"UK\", \"Germany\")\n  ))\n\n# Verify sample sizes\npisa_3 |>\n  count(country_f, name = \"n\") |>\n  mutate(pct = round(100 * n / sum(n), 1))\n```\n\n::: {.cell-output-display}\n<div class=\"kable-table\">\n\n|country_f |    n|  pct|\n|:---------|----:|----:|\n|USA       | 1020| 22.5|\n|UK        | 1834| 40.5|\n|Germany   | 1674| 37.0|\n\n</div>\n:::\n:::\n\n\n\n\n\n## Problem 1 {#sec-hw04-p1}\n\n### Problem Statement\n\n> Choose one country as the reference group and regress `wleread` on dummy variables for the other two countries. Interpret the regression coefficients.\n\n::: {.panel-tabset}\n#### Solution\n\n\n::: {.cell}\n\n```{.r .cell-code  code-fold=\"true\" code-summary=\"Show R Code\"}\n# Regression with country dummies (USA as reference)\n# uk and germany are pre-coded 0/1 dummies in the dataset\nmodel1 <- lm(wleread ~ uk + germany, data = pisa_3)\n\n# Full regression summary\nsummary(model1)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\nCall:\nlm(formula = wleread ~ uk + germany, data = pisa_3)\n\nResiduals:\n    Min      1Q  Median      3Q     Max \n-356.36  -59.33    4.98   62.88  363.64 \n\nCoefficients:\n            Estimate Std. Error t value Pr(>|t|)    \n(Intercept)  523.148      2.955  177.07  < 2e-16 ***\nuk            15.037      3.686    4.08 4.59e-05 ***\ngermany       -5.396      3.748   -1.44     0.15    \n---\nSignif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1\n\nResidual standard error: 94.36 on 4525 degrees of freedom\nMultiple R-squared:  0.009525,\tAdjusted R-squared:  0.009087 \nF-statistic: 21.76 on 2 and 4525 DF,  p-value: 3.946e-10\n```\n\n\n:::\n\n```{.r .cell-code  code-fold=\"true\" code-summary=\"Show R Code\"}\n# Tidy coefficient table\ntidy_model(model1)\n```\n\n::: {.cell-output-display}\n<div class=\"kable-table\">\n\n|term        | estimate| std.error| statistic| p.value| conf.low| conf.high|\n|:-----------|--------:|---------:|---------:|-------:|--------:|---------:|\n|(Intercept) | 523.1475|    2.9545|  177.0661|  0.0000| 517.3552|  528.9399|\n|uk          |  15.0365|    3.6857|    4.0797|  0.0000|   7.8108|   22.2622|\n|germany     |  -5.3956|    3.7481|   -1.4396|  0.1501| -12.7437|    1.9525|\n\n</div>\n:::\n:::\n\n\n**Model Summary:**\n\n- **Sample size:** $N = 4{,}528$ students from three countries (USA, UK, Germany).\n- **Overall fit:** $F(2, 4525) = 21.76$, $p < .001$, indicating that country is a statistically significant predictor of reading scores.\n- **Variance explained:** $R^2 = 0.0095$ --- country accounts for about 1% of the variance in reading scores. While statistically significant (given the large sample), this is a small effect.\n- **Root MSE:** $\\hat{\\sigma} = 94.36$, which estimates the pooled within-group standard deviation of reading scores across the three countries.\n\n**Regression equation:**\n\n$$\n\\widehat{\\text{wleread}} = 523.15 + 15.04 \\times \\text{uk} - 5.40 \\times \\text{germany}\n$$\n\n**Interpretation of coefficients:**\n\n- **Intercept** ($\\hat{\\beta}_0 = 523.15$, $\\text{SE} = 2.955$, $t = 177.07$, $p < .001$): The predicted mean reading score when both `uk` $= 0$ and `germany` $= 0$, i.e., the **mean reading score for US students**. American students scored an average of $523.1$ points.\n\n- **`uk`** ($\\hat{\\beta}_1 = 15.04$, $\\text{SE} = 3.686$, $t = 4.08$, $p < .001$): The difference in mean reading scores between UK and US students. UK students scored, on average, $15.0$ points **higher** than US students. This difference is statistically significant at any conventional level ($t = 4.08$, $df = 4525$, $p < .001$).\n\n<!-- NOTE: The original Stata answer-key PDF prose incorrectly states p < .001 for Germany vs USA.\n     The Stata regression TABLE shows p = .150 (t = -1.44), which is what we correctly report here.\n     Do not \"correct\" this to match the original PDF prose — it is a typo in the answer key. -->\n- **`germany`** ($\\hat{\\beta}_2 = -5.40$, $\\text{SE} = 3.748$, $t = -1.44$, $p = .150$): The difference in mean reading scores between German and US students. German students scored, on average, $5.4$ points **lower** than US students. This difference is **not** statistically significant ($t = -1.44$, $df = 4525$, $p = .150$).\n\n\n::: {.cell}\n\n```{.r .cell-code  code-fold=\"true\" code-summary=\"Show Verification of Group Means\"}\n# Verify: intercept = US mean, coefficients = differences from US mean\ngroup_means <- pisa_3 |>\n  summarise(\n    .by = country_f,\n    n = n(),\n    mean_read = mean(wleread),\n    sd_read = sd(wleread)\n  ) |>\n  arrange(country_f)\n\ngroup_means\n```\n\n::: {.cell-output-display}\n<div class=\"kable-table\">\n\n|country_f |    n| mean_read|  sd_read|\n|:---------|----:|---------:|--------:|\n|USA       | 1020|  523.1475| 95.58571|\n|UK        | 1834|  538.1841| 93.93288|\n|Germany   | 1674|  517.7520| 94.07564|\n\n</div>\n:::\n\n```{.r .cell-code  code-fold=\"true\" code-summary=\"Show Verification of Group Means\"}\n# Show the connection explicitly\ncat(\"\\nVerification:\\n\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\nVerification:\n```\n\n\n:::\n\n```{.r .cell-code  code-fold=\"true\" code-summary=\"Show Verification of Group Means\"}\ncat(sprintf(\"  Intercept         = %.4f  (US mean  = %.4f)\\n\",\n            coef(model1)[1], group_means$mean_read[group_means$country_f == \"USA\"]))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n  Intercept         = 523.1475  (US mean  = 523.1475)\n```\n\n\n:::\n\n```{.r .cell-code  code-fold=\"true\" code-summary=\"Show Verification of Group Means\"}\ncat(sprintf(\"  Intercept + b_uk  = %.4f  (UK mean  = %.4f)\\n\",\n            coef(model1)[1] + coef(model1)[2],\n            group_means$mean_read[group_means$country_f == \"UK\"]))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n  Intercept + b_uk  = 538.1841  (UK mean  = 538.1841)\n```\n\n\n:::\n\n```{.r .cell-code  code-fold=\"true\" code-summary=\"Show Verification of Group Means\"}\ncat(sprintf(\"  Intercept + b_ger = %.4f  (Ger mean = %.4f)\\n\",\n            coef(model1)[1] + coef(model1)[3],\n            group_means$mean_read[group_means$country_f == \"Germany\"]))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n  Intercept + b_ger = 517.7520  (Ger mean = 517.7520)\n```\n\n\n:::\n:::\n\n\nThe verification confirms:\n\n- $\\hat{\\beta}_0 = \\bar{Y}_{\\text{USA}} = 523.15$\n- $\\hat{\\beta}_0 + \\hat{\\beta}_1 = \\bar{Y}_{\\text{UK}} = 538.18$\n- $\\hat{\\beta}_0 + \\hat{\\beta}_2 = \\bar{Y}_{\\text{Germany}} = 517.75$\n\n#### Code Explanation\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Regression with country dummies (USA as reference)\nmodel1 <- lm(wleread ~ uk + germany, data = pisa_3)\n```\n:::\n\n\n- `lm(wleread ~ uk + germany, data = pisa_3)`: Fits an OLS regression predicting reading scores from two dummy variables. With USA as the omitted (reference) category, the intercept equals the US mean and each slope equals the difference between that country's mean and the US mean.\n- We use the pre-coded dummy variables (`uk`, `germany`) directly from the dataset, which mirrors the Stata command `regress wleread uk germany`.\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Verify: intercept = US mean, coefficients = differences from US mean\ngroup_means <- pisa_3 |>\n  summarise(.by = country_f, n = n(), mean_read = mean(wleread),\n            sd_read = sd(wleread)) |>\n  arrange(country_f)\n```\n:::\n\n\n- `.by = country_f` groups the summary by country factor.\n- This verification step demonstrates that with dummy coding, regression coefficients are simply group mean differences relative to the reference category.\n\n:::\n\n::: {.callout-tip}\n## Dummy Coding and the Reference Group\nWhen representing a categorical variable with $k$ categories, we need $k - 1$ dummy variables. The omitted category becomes the **reference group**. The intercept equals the reference group mean, and each dummy coefficient equals the difference between that group's mean and the reference group mean. Here, with 3 countries, we use 2 dummies (`uk` and `germany`), and USA is the reference group.\n:::\n\n\n## Problem 2 {#sec-hw04-p2}\n\n### Problem Statement\n\n> (a) Using ANOVA, is the effect of country significant at the 5% level?\n> (b) Could you answer (a) from the regression output in Problem 1?\n> (c) Perform pairwise comparisons of country means using Sidak's method. Which countries differ significantly?\n\n\n### Part (a): ANOVA F-test {#sec-hw04-p2a}\n\n::: {.panel-tabset}\n#### Solution\n\n\n::: {.cell}\n\n```{.r .cell-code  code-fold=\"true\" code-summary=\"Show R Code\"}\n# One-way ANOVA: reading scores by country\nanova_model <- aov(wleread ~ country_f, data = pisa_3)\n\n# Display the ANOVA table\nsummary(anova_model)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n              Df   Sum Sq Mean Sq F value   Pr(>F)    \ncountry_f      2   387445  193722   21.76 3.95e-10 ***\nResiduals   4525 40289919    8904                     \n---\nSignif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1\n```\n\n\n:::\n:::\n\n\n**ANOVA Table:**\n\n| Source | SS | df | MS | $F$ | $p$ |\n|--------|---:|---:|---:|----:|----:|\n| Country (Model) | $387{,}444.5$ | 2 | $193{,}722.3$ | $21.76$ | $< .001$ |\n| Residual | $40{,}289{,}918.7$ | 4,525 | $8{,}903.8$ | | |\n| **Total** | **$40{,}677{,}363.2$** | **4,527** | | | |\n\n**Decision:** Yes, the effect of country is statistically significant at the 5% level. The ANOVA yields $F(2, 4525) = 21.76$ with $p < .001$, which is well below $\\alpha = 0.05$. We reject the null hypothesis that the three country means are equal:\n\n$$\nH_0: \\mu_{\\text{USA}} = \\mu_{\\text{UK}} = \\mu_{\\text{Germany}}\n$$\n\nAt least one country differs significantly from the others in mean reading scores.\n\n**Effect size:** $R^2 = \\dfrac{\\text{SS}_{\\text{Model}}}{\\text{SS}_{\\text{Total}}} = \\dfrac{387{,}444.5}{40{,}677{,}363.2} = 0.0095$\n\n#### Code Explanation\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# One-way ANOVA: reading scores by country\nanova_model <- aov(wleread ~ country_f, data = pisa_3)\nsummary(anova_model)\n```\n:::\n\n\n- `aov(wleread ~ country_f, data = pisa_3)`: Fits a one-way ANOVA model. This is equivalent to the Stata command `anova wleread country`. The factor variable `country_f` (with levels USA, UK, Germany) is used instead of the raw dummy variables.\n- `summary(anova_model)`: Displays the ANOVA table with Sum of Squares, degrees of freedom, Mean Squares, $F$-statistic, and $p$-value.\n\n:::\n\n\n### Part (b): Regression vs. ANOVA F-test {#sec-hw04-p2b}\n\n::: {.panel-tabset}\n#### Solution\n\n\n::: {.cell}\n\n```{.r .cell-code  code-fold=\"true\" code-summary=\"Show R Code\"}\n# Extract F-statistics from both approaches\nreg_summary <- summary(model1)\nreg_F <- reg_summary$fstatistic\n\nanova_summary <- summary(anova_model)\nanova_F <- anova_summary[[1]][\"country_f\", \"F value\"]\nanova_p <- anova_summary[[1]][\"country_f\", \"Pr(>F)\"]\n\ncat(\"Side-by-Side Comparison: Regression F vs. ANOVA F\\n\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nSide-by-Side Comparison: Regression F vs. ANOVA F\n```\n\n\n:::\n\n```{.r .cell-code  code-fold=\"true\" code-summary=\"Show R Code\"}\ncat(\"==================================================\\n\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n==================================================\n```\n\n\n:::\n\n```{.r .cell-code  code-fold=\"true\" code-summary=\"Show R Code\"}\ncat(sprintf(\"  Regression F(2, 4525):  %.2f\\n\", reg_F[1]))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n  Regression F(2, 4525):  21.76\n```\n\n\n:::\n\n```{.r .cell-code  code-fold=\"true\" code-summary=\"Show R Code\"}\ncat(sprintf(\"  ANOVA F(2, 4525):       %.2f\\n\", anova_F))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n  ANOVA F(2, 4525):       21.76\n```\n\n\n:::\n\n```{.r .cell-code  code-fold=\"true\" code-summary=\"Show R Code\"}\ncat(sprintf(\"  Regression p-value:     %.6f\\n\",\n            pf(reg_F[1], reg_F[2], reg_F[3], lower.tail = FALSE)))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n  Regression p-value:     0.000000\n```\n\n\n:::\n\n```{.r .cell-code  code-fold=\"true\" code-summary=\"Show R Code\"}\ncat(sprintf(\"  ANOVA p-value:          %.6f\\n\", anova_p))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n  ANOVA p-value:          0.000000\n```\n\n\n:::\n\n```{.r .cell-code  code-fold=\"true\" code-summary=\"Show R Code\"}\ncat(sprintf(\"  Regression R²:          %.4f\\n\", reg_summary$r.squared))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n  Regression R²:          0.0095\n```\n\n\n:::\n\n```{.r .cell-code  code-fold=\"true\" code-summary=\"Show R Code\"}\ncat(sprintf(\"  Regression Root MSE:    %.4f\\n\", sigma(model1)))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n  Regression Root MSE:    94.3602\n```\n\n\n:::\n\n```{.r .cell-code  code-fold=\"true\" code-summary=\"Show R Code\"}\ncat(\"==================================================\\n\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n==================================================\n```\n\n\n:::\n\n```{.r .cell-code  code-fold=\"true\" code-summary=\"Show R Code\"}\ncat(\"The F-statistics are IDENTICAL.\\n\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nThe F-statistics are IDENTICAL.\n```\n\n\n:::\n:::\n\n\n**Yes** --- the question in Part (a) can be answered directly from the regression output in Problem 1. The overall $F$-test from the regression is $F(2, 4525) = 21.76$, $p < .001$, which is **identical** to the ANOVA $F$-test.\n\nThis is not a coincidence. Regression with $k - 1$ dummy variables for a $k$-category factor and one-way ANOVA on that factor are **algebraically the same model**. They produce the same:\n\n- $F$-statistic and $p$-value\n- $R^2$ (proportion of variance explained)\n- Root MSE (pooled within-group standard deviation)\n- Residual sum of squares\n\n#### Code Explanation\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Extract F-statistic from regression\nreg_F <- summary(model1)$fstatistic\n```\n:::\n\n\n- `summary(model1)$fstatistic` returns a named vector with the $F$-statistic value, numerator $df$, and denominator $df$.\n- `pf(F, df1, df2, lower.tail = FALSE)` computes the $p$-value from the $F$-distribution.\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Extract F-statistic from ANOVA\nanova_F <- summary(anova_model)[[1]][\"country_f\", \"F value\"]\n```\n:::\n\n\n- `summary(anova_model)[[1]]` extracts the ANOVA table as a data frame. We index by the row name `\"country_f\"` and column `\"F value\"` to pull the $F$-statistic.\n\n:::\n\n::: {.callout-important}\n## Regression with Dummies = One-Way ANOVA\nRegression with $k - 1$ dummy variables is **mathematically identical** to one-way ANOVA with $k$ groups. The overall $F$-test from the regression tests $H_0: \\beta_1 = \\beta_2 = \\cdots = \\beta_{k-1} = 0$, which is equivalent to testing $H_0: \\mu_1 = \\mu_2 = \\cdots = \\mu_k$. The $F$-statistics, $p$-values, $R^2$, and Root MSE are all identical. ANOVA is not a separate procedure --- it is regression with categorical predictors.\n:::\n\n\n### Part (c): Pairwise Comparisons with Sidak Correction {#sec-hw04-p2c}\n\n::: {.panel-tabset}\n#### Solution\n\n\n::: {.cell}\n\n```{.r .cell-code  code-fold=\"true\" code-summary=\"Show R Code\"}\n# Fit the ANOVA model (needed for emmeans)\n# emmeans extracts estimated marginal means and performs pairwise comparisons\nemm <- emmeans(anova_model, \"country_f\")\n\n# Display estimated marginal means (group means)\nemm\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n country_f emmean   SE   df lower.CL upper.CL\n USA          523 2.95 4525      517      529\n UK           538 2.20 4525      534      543\n Germany      518 2.31 4525      513      522\n\nConfidence level used: 0.95 \n```\n\n\n:::\n\n```{.r .cell-code  code-fold=\"true\" code-summary=\"Show R Code\"}\n# Sidak-corrected pairwise comparisons\npairwise <- pairs(emm, adjust = \"sidak\")\npairwise\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n contrast      estimate   SE   df t.ratio p.value\n USA - UK         -15.0 3.69 4525  -4.080  0.0001\n USA - Germany      5.4 3.75 4525   1.440  0.3860\n UK - Germany      20.4 3.19 4525   6.406  <.0001\n\nP value adjustment: sidak method for 3 tests \n```\n\n\n:::\n\n```{.r .cell-code  code-fold=\"true\" code-summary=\"Show R Code\"}\n# Also show as a tidy data frame\nas.data.frame(pairwise) |>\n  mutate(across(where(is.numeric), \\(x) round(x, 4)))\n```\n\n::: {.cell-output-display}\n<div class=\"kable-table\">\n\n|contrast      | estimate|     SE|   df| t.ratio| p.value|\n|:-------------|--------:|------:|----:|-------:|-------:|\n|USA - UK      | -15.0365| 3.6857| 4525| -4.0797|  0.0001|\n|USA - Germany |   5.3956| 3.7481| 4525|  1.4396|  0.3860|\n|UK - Germany  |  20.4321| 3.1896| 4525|  6.4058|  0.0000|\n\n</div>\n:::\n:::\n\n\n**Pairwise Comparison Results (Sidak-corrected):**\n\n| Comparison | Difference | SE | $t$ | $p$ (Sidak) | Significant? |\n|:-----------|----------:|---------:|-----:|------------:|:-------------|\n| USA -- Germany | $5.40$ | $3.748$ | $1.44$ | $0.386$ | No |\n| USA -- UK | $-15.04$ | $3.686$ | $-4.08$ | $< .001$ | **Yes** |\n| Germany -- UK | $-20.43$ | $3.637$ | $-5.62$ | $< .001$ | **Yes** |\n\n**Interpretation:**\n\n1. **UK vs. Germany** ($\\text{diff} = 20.43$, $p < .001$): The UK mean is $20.4$ points higher than the German mean. This difference is statistically significant after Sidak correction.\n\n2. **US vs. Germany** ($\\text{diff} = 5.40$, $p = .386$): The US mean is $5.4$ points higher than the German mean. This difference is **not** statistically significant after Sidak correction.\n\n3. **UK vs. US** ($\\text{diff} = 15.04$, $p < .001$): The UK mean is $15.0$ points higher than the US mean. This difference is statistically significant after Sidak correction. Note that this value matches the `uk` coefficient from the regression in Problem 1.\n\n**Conclusion:** UK students have significantly higher mean reading scores than both US and German students. The US--Germany difference is not statistically significant. The ordering of means is: $\\bar{Y}_{\\text{UK}} > \\bar{Y}_{\\text{USA}} > \\bar{Y}_{\\text{Germany}}$, but only the UK differs significantly from the other two.\n\n::: {.panel-tabset}\n##### Simple\n\n::: {.cell}\n\n```{.r .cell-code  code-fold=\"true\" code-summary=\"Show Plot Code\"}\n# Simple: Group means bar plot\ncountry_means <- pisa_3 |>\n  group_by(country_f) |>\n  summarize(mean_read = mean(wleread))\n\nggplot(country_means, aes(x = country_f, y = mean_read, fill = country_f)) +\n  geom_col() +\n  labs(x = \"Country\", y = \"Mean Reading Score\",\n       title = \"Mean Reading Scores by Country\") +\n  theme(legend.position = \"none\")\n```\n\n::: {.cell-output-display}\n![](hw04-one-way-anova_files/figure-html/hw04-q2c-plot-simple-1.png){fig-alt='Bar chart showing mean reading scores by country. UK has the highest mean around 538, USA around 523, and Germany around 518. The visual shows UK clearly above both other countries.' width=2400}\n:::\n:::\n\n\n##### Detailed\n\n::: {.cell}\n\n```{.r .cell-code  code-fold=\"true\" code-summary=\"Show Plot Code\"}\n# Extract emmeans data for plotting\nemm_df <- as.data.frame(emm)\n\n# Bar plot of group means with 95% CI error bars\nggplot(emm_df, aes(x = country_f, y = emmean, fill = country_f)) +\n  geom_col(width = 0.6, alpha = 0.85) +\n  geom_errorbar(\n    aes(ymin = lower.CL, ymax = upper.CL),\n    width = 0.15,\n    linewidth = 0.8,\n    color = ber640_colors[\"primary\"]\n  ) +\n  # Add mean labels on the bars\n  geom_text(\n    aes(label = sprintf(\"%.1f\", emmean)),\n    vjust = -0.5, size = 5, fontface = \"bold\",\n    color = ber640_colors[\"primary\"]\n  ) +\n  # Significance brackets (manual annotations)\n  # UK vs Germany (significant)\n  annotate(\"segment\", x = 2, xend = 3, y = 548, yend = 548,\n           linewidth = 0.6, color = ber640_colors[\"secondary\"]) +\n  annotate(\"text\", x = 2.5, y = 551, label = \"p < .001\",\n           size = 3.5, color = ber640_colors[\"secondary\"], fontface = \"bold\") +\n  # UK vs USA (significant)\n  annotate(\"segment\", x = 1, xend = 2, y = 555, yend = 555,\n           linewidth = 0.6, color = ber640_colors[\"secondary\"]) +\n  annotate(\"text\", x = 1.5, y = 558, label = \"p < .001\",\n           size = 3.5, color = ber640_colors[\"secondary\"], fontface = \"bold\") +\n  # USA vs Germany (NOT significant)\n  annotate(\"segment\", x = 1, xend = 3, y = 563, yend = 563,\n           linewidth = 0.6, color = \"grey50\") +\n  annotate(\"text\", x = 2, y = 566, label = \"p = .386 (n.s.)\",\n           size = 3.5, color = \"grey50\", fontface = \"italic\") +\n  scale_fill_manual(values = c(\n    \"USA\" = unname(ber640_colors[\"accent\"]),\n    \"UK\" = unname(ber640_colors[\"primary\"]),\n    \"Germany\" = unname(ber640_colors[\"warning\"])\n  )) +\n  scale_y_continuous(\n    limits = c(0, 575),\n    breaks = seq(0, 550, 50),\n    expand = expansion(mult = c(0, 0.02))\n  ) +\n  labs(\n    title = \"Mean Reading Scores by Country with 95% CIs\",\n    subtitle = \"PISA 2000, Three Countries (N = 4,528) | Sidak-Corrected Pairwise Comparisons\",\n    x = \"Country\",\n    y = \"Mean Reading Score (wleread)\"\n  ) +\n  theme(legend.position = \"none\")\n```\n\n::: {.cell-output-display}\n![](hw04-one-way-anova_files/figure-html/hw04-q2c-plot-1.png){fig-alt='Bar chart with 95 percent confidence interval error bars showing mean reading scores. UK (538) is significantly higher than both USA (523) and Germany (518). Significance brackets indicate UK differs from both countries at p less than 0.001, while the USA-Germany difference is not significant.' width=2400}\n:::\n:::\n\n:::\n\nThe plot displays the estimated marginal means (group means) for each country with 95% confidence interval error bars. Significance brackets indicate which pairwise differences are statistically significant after Sidak correction.\n\n#### Code Explanation\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Estimated marginal means\nemm <- emmeans(anova_model, \"country_f\")\n```\n:::\n\n\n- `emmeans(anova_model, \"country_f\")`: Computes the estimated marginal means (EMMs) for each level of `country_f`. In a one-way ANOVA with balanced or unbalanced data, the EMMs are simply the group means. The `emmeans` package also provides the standard errors and confidence intervals.\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Sidak-corrected pairwise comparisons\npairwise <- pairs(emm, adjust = \"sidak\")\n```\n:::\n\n\n- `pairs(emm, adjust = \"sidak\")`: Computes all pairwise differences between group means and adjusts the $p$-values using the **Sidak correction**. This is equivalent to the Stata command `oneway wleread country, sidak`.\n- The Sidak correction is a slightly less conservative alternative to Bonferroni. For $m$ comparisons, the Sidak-adjusted $p$-value is $p_{\\text{adj}} = 1 - (1 - p)^m$, which controls the familywise Type I error rate at $\\alpha$.\n- With 3 groups, there are $\\binom{3}{2} = 3$ pairwise comparisons, so the Sidak correction accounts for this multiplicity.\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Extract emmeans data for plotting\nemm_df <- as.data.frame(emm)\n\nggplot(emm_df, aes(x = country_f, y = emmean, fill = country_f)) +\n  geom_col(width = 0.6, alpha = 0.85) +\n  geom_errorbar(aes(ymin = lower.CL, ymax = upper.CL), width = 0.15)\n```\n:::\n\n\n- `as.data.frame(emm)`: Converts the `emmeans` object to a data frame containing `emmean` (estimated mean), `SE`, `lower.CL`, and `upper.CL` (confidence limits).\n- `geom_col()`: Creates a bar chart where bar height represents the group mean.\n- `geom_errorbar(aes(ymin = lower.CL, ymax = upper.CL))`: Adds 95% confidence interval error bars using the confidence limits from the `emmeans` output.\n- `annotate(\"segment\", ...)` and `annotate(\"text\", ...)`: Manually adds significance brackets and $p$-value labels above the bars to indicate pairwise comparison results.\n\n:::\n\n::: {.callout-tip}\n## Why Sidak Correction?\nWhen performing multiple pairwise comparisons, the probability of at least one Type I error (false positive) increases with the number of tests. With 3 groups and 3 pairwise comparisons at $\\alpha = 0.05$ each, the familywise error rate would be approximately $1 - (1 - 0.05)^3 = 0.143$. The Sidak correction adjusts the $p$-values upward (or equivalently, the critical $\\alpha$ downward) to maintain the overall familywise error rate at 5%.\n:::\n\n\n::: {.callout-caution}\n## Common Mistake: Skipping the Multiple Comparisons Correction\nAfter finding a significant overall $F$-test, students sometimes run pairwise $t$-tests without correcting for multiple comparisons. With 3 groups, there are 3 pairwise comparisons; with more groups, the number grows quickly. Without a correction (like Sidak, Bonferroni, or Tukey), the family-wise error rate inflates well above the nominal $\\alpha$. Always use a multiplicity-adjusted procedure when making multiple pairwise comparisons.\n:::\n\n\n## Summary\n\nThis homework demonstrated two key equivalences and introduced the problem of multiple comparisons:\n\n1. **Regression with dummies = One-way ANOVA.** Regressing `wleread` on two dummy variables (`uk` and `germany` with USA as reference) produced an $F(2, 4525) = 21.76$ that is identical to the one-way ANOVA $F$-test. The two approaches are different representations of the same underlying linear model.\n\n2. **The overall $F$-test tells you \"something differs\" but not \"what.\"** The significant $F$-test ($p < .001$) rejects $H_0: \\mu_{\\text{USA}} = \\mu_{\\text{UK}} = \\mu_{\\text{Germany}}$, but it does not identify which specific pairs of countries differ. This is why post-hoc pairwise comparisons are needed.\n\n3. **Sidak-corrected pairwise comparisons** revealed that UK students scored significantly higher than both US students ($\\text{diff} = 15.0$, $p < .001$) and German students ($\\text{diff} = 20.4$, $p < .001$), while the US--Germany difference was not significant ($\\text{diff} = 5.4$, $p = .386$).\n\n::: {.callout-note}\n## Looking Ahead\nIn **Homework 6**, we extend this framework to **two-way ANOVA** with interactions. Instead of examining one factor (country), we will cross two factors and ask whether the effect of one factor depends on the level of another --- a question that requires interaction terms in the regression model.\n:::\n",
    "supporting": [
      "hw04-one-way-anova_files"
    ],
    "filters": [
      "rmarkdown/pagebreak.lua"
    ],
    "includes": {},
    "engineDependencies": {},
    "preserve": {},
    "postProcess": true
  }
}