{
  "hash": "a07af9f0677c9074f3b5b85ff7b4b6c0",
  "result": {
    "engine": "knitr",
    "markdown": "---\ntitle: \"Homework 8: Logistic Regression and Simpson's Paradox\"\n---\n\n\n\n\n## Overview\n\n::: {.callout-note}\n## Learning Objectives\n- Build three-way and collapsed frequency tables from binary data\n- Compute and interpret a crude odds ratio\n- Fit a multiple logistic regression with categorical predictors\n- Compare crude and adjusted odds ratios to explain Simpson's paradox\n- Conduct a Wald test for one logistic-regression coefficient\n- Compute a grouped Pearson goodness-of-fit test for categorical predictor patterns\n- **Related notes:** [Chapter 10: *Multiple Logistic Regression*](../../notes/chapters/10-multiple-logistic-regression.html) and [Chapter 11: *Logistic Regression Diagnostics*](../../notes/chapters/11-logistic-diagnostics.html)\n- **Related labs:** [Lab 10: *Multiple Logistic Regression*](../../labs/labs/lab10-logistic-extended.html) and [Lab 11: *Logistic Diagnostics and Classification*](../../labs/labs/lab11-logistic-diagnostics.html)\n:::\n\n::: {.callout-tip}\n## Stata-to-R Translation\n| Stata command | R equivalent | Used in |\n|:---|:---|:---|\n| `table admitted female, contents(freq) by(departme)` | `count(department, admitted, female)` | Problem 1 |\n| `cs admitted female, or` | `glm(admitted ~ female, family = binomial)` or a manual odds ratio | Problem 2 |\n| `logit admitted female i.departme, or` | `glm(admitted ~ female + factor(department), family = binomial)` | Problem 3 |\n| `testparm female` | the Wald $z$ test in `model_params()` | Problem 5 |\n| `estat gof, table` | grouped observed/expected counts by covariate pattern | Problem 6 |\n:::\n\n**Dataset:** `berkeley` from the `regdatasets` package, based on the UC Berkeley graduate-admissions data discussed by @bickel1975.\n\nThe Stata reference uses the variable name `departme`; the R dataset uses `department`. They refer to the same five Berkeley graduate departments.\n\n**Variables:**\n\n- `department`: department code, 1--5\n- `female`: applicant gender, where $0 =$ male and $1 =$ female\n- `admitted`: admission outcome, where $0 =$ not admitted and $1 =$ admitted\n\nThe Berkeley admissions data are a classic example of **Simpson's paradox**: an aggregate association changes after conditioning on a confounding variable.\n\n\n## Setup\n\n\n::: {.cell}\n\n```{.r .cell-code}\ndata(berkeley)\n\nberk <- berkeley |>\n  mutate(\n    department_f = factor(department, levels = 1:5, labels = paste(\"Dept\", 1:5)),\n    female_f = factor(female, levels = c(0, 1), labels = c(\"Male\", \"Female\")),\n    admitted_f = factor(\n      admitted,\n      levels = c(0, 1),\n      labels = c(\"Not admitted\", \"Admitted\")\n    )\n  )\n\nberk |>\n  summarise(\n    n = n(),\n    departments = n_distinct(department),\n    female_applicants = sum(female),\n    admitted_applicants = sum(admitted),\n    admission_rate = mean(admitted)\n  ) |>\n  round_numeric(digits = 4)\n```\n\n::: {.cell-output-display}\n<div class=\"kable-table\">\n\n|    n| departments| female_applicants| admitted_applicants| admission_rate|\n|----:|-----------:|-----------------:|-------------------:|--------------:|\n| 3593|           5|              1727|                1154|         0.3212|\n\n</div>\n:::\n:::\n\n\n\n\n\n## Problem 1\n\n### Problem Statement\n\n> Read the data and form a three-way table of frequencies: admitted by gender, separately for each department.\n\n### Solution\n\n\n::: {.cell}\n\n```{.r .cell-code}\ndept_counts <- berk |>\n  count(department, admitted_f, female_f, name = \"n\") |>\n  tidyr::pivot_wider(\n    names_from = female_f,\n    values_from = n\n  ) |>\n  arrange(department, admitted_f)\n\ndept_counts\n```\n\n::: {.cell-output-display}\n<div class=\"kable-table\">\n\n| department|admitted_f   | Male| Female|\n|----------:|:------------|----:|------:|\n|          1|Not admitted |  207|      8|\n|          1|Admitted     |  353|     17|\n|          2|Not admitted |  205|    391|\n|          2|Admitted     |  120|    202|\n|          3|Not admitted |  279|    244|\n|          3|Admitted     |  138|    131|\n|          4|Not admitted |  138|    299|\n|          4|Admitted     |   53|     94|\n|          5|Not admitted |  351|    317|\n|          5|Admitted     |   22|     24|\n\n</div>\n:::\n:::\n\n\nThe same table can be summarized as admission rates within each department-by-gender cell:\n\n\n::: {.cell}\n\n```{.r .cell-code}\ndept_rates <- berk |>\n  group_by(department_f, female_f) |>\n  summarise(\n    n = n(),\n    admitted = sum(admitted),\n    not_admitted = n - admitted,\n    admission_rate = admitted / n,\n    odds = admission_rate / (1 - admission_rate),\n    .groups = \"drop\"\n  )\n\ndept_rates |>\n  gt::gt() |>\n  gt::cols_label(\n    department_f = \"Department\",\n    female_f = \"Gender\",\n    n = \"N\",\n    admitted = \"Admitted\",\n    not_admitted = \"Not admitted\",\n    admission_rate = \"Admission rate\",\n    odds = \"Odds\"\n  ) |>\n  gt::fmt_number(columns = c(n, admitted, not_admitted), decimals = 0, use_seps = FALSE) |>\n  gt::fmt_number(columns = c(admission_rate, odds), decimals = 4) |>\n  gt::cols_align(\"left\", columns = c(department_f, female_f)) |>\n  gt::cols_align(\"right\", columns = c(n, admitted, not_admitted, admission_rate, odds)) |>\n  gt::cols_width(\n    department_f ~ gt::pct(17),\n    female_f ~ gt::pct(14),\n    n ~ gt::pct(8),\n    admitted ~ gt::pct(14),\n    not_admitted ~ gt::pct(16),\n    admission_rate ~ gt::pct(18),\n    odds ~ gt::pct(13)\n  ) |>\n  gt::tab_options(table.width = gt::pct(100))\n```\n\n::: {.cell-output-display}\n\n```{=html}\n<div id=\"okgoawrfzu\" style=\"padding-left:0px;padding-right:0px;padding-top:10px;padding-bottom:10px;overflow-x:auto;overflow-y:auto;width:auto;height:auto;\">\n<style>#okgoawrfzu table {\n  font-family: system-ui, 'Segoe UI', Roboto, Helvetica, Arial, sans-serif, 'Apple Color Emoji', 'Segoe UI Emoji', 'Segoe UI Symbol', 'Noto Color Emoji';\n  -webkit-font-smoothing: antialiased;\n  -moz-osx-font-smoothing: grayscale;\n}\n\n#okgoawrfzu thead, #okgoawrfzu tbody, #okgoawrfzu tfoot, #okgoawrfzu tr, #okgoawrfzu td, #okgoawrfzu th {\n  border-style: none;\n}\n\n#okgoawrfzu p {\n  margin: 0;\n  padding: 0;\n}\n\n#okgoawrfzu .gt_table {\n  display: table;\n  border-collapse: collapse;\n  line-height: normal;\n  margin-left: auto;\n  margin-right: auto;\n  color: #333333;\n  font-size: 16px;\n  font-weight: normal;\n  font-style: normal;\n  background-color: #FFFFFF;\n  width: 100%;\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #A8A8A8;\n  border-right-style: none;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #A8A8A8;\n  border-left-style: none;\n  border-left-width: 2px;\n  border-left-color: #D3D3D3;\n}\n\n#okgoawrfzu .gt_caption {\n  padding-top: 4px;\n  padding-bottom: 4px;\n}\n\n#okgoawrfzu .gt_title {\n  color: #333333;\n  font-size: 125%;\n  font-weight: initial;\n  padding-top: 4px;\n  padding-bottom: 4px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-bottom-color: #FFFFFF;\n  border-bottom-width: 0;\n}\n\n#okgoawrfzu .gt_subtitle {\n  color: #333333;\n  font-size: 85%;\n  font-weight: initial;\n  padding-top: 3px;\n  padding-bottom: 5px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-top-color: #FFFFFF;\n  border-top-width: 0;\n}\n\n#okgoawrfzu .gt_heading {\n  background-color: #FFFFFF;\n  text-align: center;\n  border-bottom-color: #FFFFFF;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n}\n\n#okgoawrfzu .gt_bottom_border {\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n}\n\n#okgoawrfzu .gt_col_headings {\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n}\n\n#okgoawrfzu .gt_col_heading {\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: normal;\n  text-transform: inherit;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n  vertical-align: bottom;\n  padding-top: 5px;\n  padding-bottom: 6px;\n  padding-left: 5px;\n  padding-right: 5px;\n  overflow-x: hidden;\n}\n\n#okgoawrfzu .gt_column_spanner_outer {\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: normal;\n  text-transform: inherit;\n  padding-top: 0;\n  padding-bottom: 0;\n  padding-left: 4px;\n  padding-right: 4px;\n}\n\n#okgoawrfzu .gt_column_spanner_outer:first-child {\n  padding-left: 0;\n}\n\n#okgoawrfzu .gt_column_spanner_outer:last-child {\n  padding-right: 0;\n}\n\n#okgoawrfzu .gt_column_spanner {\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  vertical-align: bottom;\n  padding-top: 5px;\n  padding-bottom: 5px;\n  overflow-x: hidden;\n  display: inline-block;\n  width: 100%;\n}\n\n#okgoawrfzu .gt_spanner_row {\n  border-bottom-style: hidden;\n}\n\n#okgoawrfzu .gt_group_heading {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: initial;\n  text-transform: inherit;\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n  vertical-align: middle;\n  text-align: left;\n}\n\n#okgoawrfzu .gt_empty_group_heading {\n  padding: 0.5px;\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: initial;\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  vertical-align: middle;\n}\n\n#okgoawrfzu .gt_from_md > :first-child {\n  margin-top: 0;\n}\n\n#okgoawrfzu .gt_from_md > :last-child {\n  margin-bottom: 0;\n}\n\n#okgoawrfzu .gt_row {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  margin: 10px;\n  border-top-style: solid;\n  border-top-width: 1px;\n  border-top-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n  vertical-align: middle;\n  overflow-x: hidden;\n}\n\n#okgoawrfzu .gt_stub {\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: initial;\n  text-transform: inherit;\n  border-right-style: solid;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#okgoawrfzu .gt_stub_row_group {\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: initial;\n  text-transform: inherit;\n  border-right-style: solid;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n  padding-left: 5px;\n  padding-right: 5px;\n  vertical-align: top;\n}\n\n#okgoawrfzu .gt_row_group_first td {\n  border-top-width: 2px;\n}\n\n#okgoawrfzu .gt_row_group_first th {\n  border-top-width: 2px;\n}\n\n#okgoawrfzu .gt_summary_row {\n  color: #333333;\n  background-color: #FFFFFF;\n  text-transform: inherit;\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#okgoawrfzu .gt_first_summary_row {\n  border-top-style: solid;\n  border-top-color: #D3D3D3;\n}\n\n#okgoawrfzu .gt_first_summary_row.thick {\n  border-top-width: 2px;\n}\n\n#okgoawrfzu .gt_last_summary_row {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n}\n\n#okgoawrfzu .gt_grand_summary_row {\n  color: #333333;\n  background-color: #FFFFFF;\n  text-transform: inherit;\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#okgoawrfzu .gt_first_grand_summary_row {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-top-style: double;\n  border-top-width: 6px;\n  border-top-color: #D3D3D3;\n}\n\n#okgoawrfzu .gt_last_grand_summary_row_top {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-bottom-style: double;\n  border-bottom-width: 6px;\n  border-bottom-color: #D3D3D3;\n}\n\n#okgoawrfzu .gt_striped {\n  background-color: rgba(128, 128, 128, 0.05);\n}\n\n#okgoawrfzu .gt_table_body {\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n}\n\n#okgoawrfzu .gt_footnotes {\n  color: #333333;\n  background-color: #FFFFFF;\n  border-bottom-style: none;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 2px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n}\n\n#okgoawrfzu .gt_footnote {\n  margin: 0px;\n  font-size: 90%;\n  padding-top: 4px;\n  padding-bottom: 4px;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#okgoawrfzu .gt_sourcenotes {\n  color: #333333;\n  background-color: #FFFFFF;\n  border-bottom-style: none;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 2px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n}\n\n#okgoawrfzu .gt_sourcenote {\n  font-size: 90%;\n  padding-top: 4px;\n  padding-bottom: 4px;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#okgoawrfzu .gt_left {\n  text-align: left;\n}\n\n#okgoawrfzu .gt_center {\n  text-align: center;\n}\n\n#okgoawrfzu .gt_right {\n  text-align: right;\n  font-variant-numeric: tabular-nums;\n}\n\n#okgoawrfzu .gt_font_normal {\n  font-weight: normal;\n}\n\n#okgoawrfzu .gt_font_bold {\n  font-weight: bold;\n}\n\n#okgoawrfzu .gt_font_italic {\n  font-style: italic;\n}\n\n#okgoawrfzu .gt_super {\n  font-size: 65%;\n}\n\n#okgoawrfzu .gt_footnote_marks {\n  font-size: 75%;\n  vertical-align: 0.4em;\n  position: initial;\n}\n\n#okgoawrfzu .gt_asterisk {\n  font-size: 100%;\n  vertical-align: 0;\n}\n\n#okgoawrfzu .gt_indent_1 {\n  text-indent: 5px;\n}\n\n#okgoawrfzu .gt_indent_2 {\n  text-indent: 10px;\n}\n\n#okgoawrfzu .gt_indent_3 {\n  text-indent: 15px;\n}\n\n#okgoawrfzu .gt_indent_4 {\n  text-indent: 20px;\n}\n\n#okgoawrfzu .gt_indent_5 {\n  text-indent: 25px;\n}\n\n#okgoawrfzu .katex-display {\n  display: inline-flex !important;\n  margin-bottom: 0.75em !important;\n}\n\n#okgoawrfzu div.Reactable > div.rt-table > div.rt-thead > div.rt-tr.rt-tr-group-header > div.rt-th-group:after {\n  height: 0px !important;\n}\n</style>\n<table class=\"gt_table\" style=\"table-layout:fixed;width:100%;\" data-quarto-disable-processing=\"false\" data-quarto-bootstrap=\"false\">\n  <colgroup>\n    <col style=\"width:17%;\"/>\n    <col style=\"width:14%;\"/>\n    <col style=\"width:8%;\"/>\n    <col style=\"width:14%;\"/>\n    <col style=\"width:16%;\"/>\n    <col style=\"width:18%;\"/>\n    <col style=\"width:13%;\"/>\n  </colgroup>\n  <thead>\n    <tr class=\"gt_col_headings\">\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_left\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"department_f\">Department</th>\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_left\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"female_f\">Gender</th>\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_right\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"n\">N</th>\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_right\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"admitted\">Admitted</th>\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_right\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"not_admitted\">Not admitted</th>\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_right\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"admission_rate\">Admission rate</th>\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_right\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"odds\">Odds</th>\n    </tr>\n  </thead>\n  <tbody class=\"gt_table_body\">\n    <tr><td headers=\"department_f\" class=\"gt_row gt_left\">Dept 1</td>\n<td headers=\"female_f\" class=\"gt_row gt_left\">Male</td>\n<td headers=\"n\" class=\"gt_row gt_right\">560</td>\n<td headers=\"admitted\" class=\"gt_row gt_right\">353</td>\n<td headers=\"not_admitted\" class=\"gt_row gt_right\">207</td>\n<td headers=\"admission_rate\" class=\"gt_row gt_right\">0.6304</td>\n<td headers=\"odds\" class=\"gt_row gt_right\">1.7053</td></tr>\n    <tr><td headers=\"department_f\" class=\"gt_row gt_left\">Dept 1</td>\n<td headers=\"female_f\" class=\"gt_row gt_left\">Female</td>\n<td headers=\"n\" class=\"gt_row gt_right\">25</td>\n<td headers=\"admitted\" class=\"gt_row gt_right\">17</td>\n<td headers=\"not_admitted\" class=\"gt_row gt_right\">8</td>\n<td headers=\"admission_rate\" class=\"gt_row gt_right\">0.6800</td>\n<td headers=\"odds\" class=\"gt_row gt_right\">2.1250</td></tr>\n    <tr><td headers=\"department_f\" class=\"gt_row gt_left\">Dept 2</td>\n<td headers=\"female_f\" class=\"gt_row gt_left\">Male</td>\n<td headers=\"n\" class=\"gt_row gt_right\">325</td>\n<td headers=\"admitted\" class=\"gt_row gt_right\">120</td>\n<td headers=\"not_admitted\" class=\"gt_row gt_right\">205</td>\n<td headers=\"admission_rate\" class=\"gt_row gt_right\">0.3692</td>\n<td headers=\"odds\" class=\"gt_row gt_right\">0.5854</td></tr>\n    <tr><td headers=\"department_f\" class=\"gt_row gt_left\">Dept 2</td>\n<td headers=\"female_f\" class=\"gt_row gt_left\">Female</td>\n<td headers=\"n\" class=\"gt_row gt_right\">593</td>\n<td headers=\"admitted\" class=\"gt_row gt_right\">202</td>\n<td headers=\"not_admitted\" class=\"gt_row gt_right\">391</td>\n<td headers=\"admission_rate\" class=\"gt_row gt_right\">0.3406</td>\n<td headers=\"odds\" class=\"gt_row gt_right\">0.5166</td></tr>\n    <tr><td headers=\"department_f\" class=\"gt_row gt_left\">Dept 3</td>\n<td headers=\"female_f\" class=\"gt_row gt_left\">Male</td>\n<td headers=\"n\" class=\"gt_row gt_right\">417</td>\n<td headers=\"admitted\" class=\"gt_row gt_right\">138</td>\n<td headers=\"not_admitted\" class=\"gt_row gt_right\">279</td>\n<td headers=\"admission_rate\" class=\"gt_row gt_right\">0.3309</td>\n<td headers=\"odds\" class=\"gt_row gt_right\">0.4946</td></tr>\n    <tr><td headers=\"department_f\" class=\"gt_row gt_left\">Dept 3</td>\n<td headers=\"female_f\" class=\"gt_row gt_left\">Female</td>\n<td headers=\"n\" class=\"gt_row gt_right\">375</td>\n<td headers=\"admitted\" class=\"gt_row gt_right\">131</td>\n<td headers=\"not_admitted\" class=\"gt_row gt_right\">244</td>\n<td headers=\"admission_rate\" class=\"gt_row gt_right\">0.3493</td>\n<td headers=\"odds\" class=\"gt_row gt_right\">0.5369</td></tr>\n    <tr><td headers=\"department_f\" class=\"gt_row gt_left\">Dept 4</td>\n<td headers=\"female_f\" class=\"gt_row gt_left\">Male</td>\n<td headers=\"n\" class=\"gt_row gt_right\">191</td>\n<td headers=\"admitted\" class=\"gt_row gt_right\">53</td>\n<td headers=\"not_admitted\" class=\"gt_row gt_right\">138</td>\n<td headers=\"admission_rate\" class=\"gt_row gt_right\">0.2775</td>\n<td headers=\"odds\" class=\"gt_row gt_right\">0.3841</td></tr>\n    <tr><td headers=\"department_f\" class=\"gt_row gt_left\">Dept 4</td>\n<td headers=\"female_f\" class=\"gt_row gt_left\">Female</td>\n<td headers=\"n\" class=\"gt_row gt_right\">393</td>\n<td headers=\"admitted\" class=\"gt_row gt_right\">94</td>\n<td headers=\"not_admitted\" class=\"gt_row gt_right\">299</td>\n<td headers=\"admission_rate\" class=\"gt_row gt_right\">0.2392</td>\n<td headers=\"odds\" class=\"gt_row gt_right\">0.3144</td></tr>\n    <tr><td headers=\"department_f\" class=\"gt_row gt_left\">Dept 5</td>\n<td headers=\"female_f\" class=\"gt_row gt_left\">Male</td>\n<td headers=\"n\" class=\"gt_row gt_right\">373</td>\n<td headers=\"admitted\" class=\"gt_row gt_right\">22</td>\n<td headers=\"not_admitted\" class=\"gt_row gt_right\">351</td>\n<td headers=\"admission_rate\" class=\"gt_row gt_right\">0.0590</td>\n<td headers=\"odds\" class=\"gt_row gt_right\">0.0627</td></tr>\n    <tr><td headers=\"department_f\" class=\"gt_row gt_left\">Dept 5</td>\n<td headers=\"female_f\" class=\"gt_row gt_left\">Female</td>\n<td headers=\"n\" class=\"gt_row gt_right\">341</td>\n<td headers=\"admitted\" class=\"gt_row gt_right\">24</td>\n<td headers=\"not_admitted\" class=\"gt_row gt_right\">317</td>\n<td headers=\"admission_rate\" class=\"gt_row gt_right\">0.0704</td>\n<td headers=\"odds\" class=\"gt_row gt_right\">0.0757</td></tr>\n  </tbody>\n  \n</table>\n</div>\n```\n\n:::\n:::\n\n\nDepartment matters for two reasons. First, departments differ sharply in admission rates. Second, the gender composition of applicant pools differs across departments. That is exactly the setup in which a collapsed gender comparison can be misleading.\n\n\n\n\n## Problem 2\n\n### Problem Statement\n\n> Form a two-way table collapsing over departments. Calculate the odds ratio and interpret it.\n\n### Solution\n\n\n::: {.cell}\n\n```{.r .cell-code}\naggregate_by_gender <- berk |>\n  group_by(female_f) |>\n  summarise(\n    n = n(),\n    admitted = sum(admitted),\n    not_admitted = n - admitted,\n    admission_rate = admitted / n,\n    odds = admitted / not_admitted,\n    .groups = \"drop\"\n  )\n\naggregate_by_gender |>\n  round_numeric(digits = 4)\n```\n\n::: {.cell-output-display}\n<div class=\"kable-table\">\n\n|female_f |    n| admitted| not_admitted| admission_rate|   odds|\n|:--------|----:|--------:|------------:|--------------:|------:|\n|Male     | 1866|      686|         1180|         0.3676| 0.5814|\n|Female   | 1727|      468|         1259|         0.2710| 0.3717|\n\n</div>\n:::\n:::\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nodds_female <- aggregate_by_gender$odds[aggregate_by_gender$female_f == \"Female\"]\nodds_male <- aggregate_by_gender$odds[aggregate_by_gender$female_f == \"Male\"]\ncrude_or <- odds_female / odds_male\n\ntibble(\n  comparison = \"Female vs male, ignoring department\",\n  odds_female = odds_female,\n  odds_male = odds_male,\n  odds_ratio = crude_or,\n  percent_change_in_odds = 100 * (crude_or - 1)\n) |>\n  round_numeric(digits = 4)\n```\n\n::: {.cell-output-display}\n<div class=\"kable-table\">\n\n|comparison                          | odds_female| odds_male| odds_ratio| percent_change_in_odds|\n|:-----------------------------------|-----------:|---------:|----------:|----------------------:|\n|Female vs male, ignoring department |      0.3717|    0.5814|     0.6394|               -36.0592|\n\n</div>\n:::\n:::\n\n\nThe crude odds ratio is:\n\n$$\n\\widehat{\\text{OR}}_{\\text{crude}}\n= \\frac{468 / 1259}{686 / 1180}\n= 0.64.\n$$\n\nIgnoring department, female applicants have estimated admission odds about 36% lower than male applicants. This is the aggregate comparison; it has not adjusted for the department to which applicants applied.\n\n::: {.callout-warning}\n## Why This Is Only a First Look\nThe crude odds ratio compares all female applicants to all male applicants after pooling departments together. If department is associated with both gender and admission, this pooled comparison mixes the gender comparison with department composition.\n:::\n\n\n\n\n## Problem 3\n\n### Problem Statement\n\n> Fit a logistic regression of `admitted` on `female` and `department` as a categorical variable. Report the odds ratios and interpret the coefficient of `female`.\n\n### Solution\n\nDepartment is a set of labels, not a numeric scale. In R, use `factor(department)` so the model creates dummy variables for departments 2--5, with department 1 as the reference group.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nmodel_adjusted <- glm(\n  admitted ~ female + factor(department),\n  data = berk,\n  family = binomial\n)\n\nadjusted_or_table <- model_params(\n  model_adjusted,\n  exponentiate = TRUE,\n  ci_method = \"wald\"\n) |>\n  as_tibble() |>\n  mutate(\n    Parameter = dplyr::recode(\n      Parameter,\n      `(Intercept)` = \"Baseline odds: Dept 1 male\",\n      female = \"Female vs male\",\n      `factor(department)2` = \"Dept 2 vs Dept 1\",\n      `factor(department)3` = \"Dept 3 vs Dept 1\",\n      `factor(department)4` = \"Dept 4 vs Dept 1\",\n      `factor(department)5` = \"Dept 5 vs Dept 1\"\n    ),\n    p = format_p(p)\n  ) |>\n  rename(Odds_ratio = Coefficient) |>\n  select(Parameter, Odds_ratio, SE, CI_low, CI_high, z, p)\n\nadjusted_or_table |>\n  round_numeric(digits = 4) |>\n  rename(`Baseline odds or odds ratio` = Odds_ratio) |>\n  knitr::kable(\n    col.names = c(\n      \"Term\",\n      \"Baseline odds or odds ratio\",\n      \"Log-odds SE\",\n      \"CI lower\",\n      \"CI upper\",\n      \"z\",\n      \"p\"\n    ),\n    align = c(\"l\", \"r\", \"r\", \"r\", \"r\", \"r\", \"r\"),\n    caption = \"Adjusted logistic regression odds ratios by gender and department.\"\n  )\n```\n\n::: {.cell-output-display}\n\n\nTable: Adjusted logistic regression odds ratios by gender and department.\n\n|Term                       | Baseline odds or odds ratio| Log-odds SE| CI lower| CI upper|        z|      p|\n|:--------------------------|---------------------------:|-----------:|--------:|--------:|--------:|------:|\n|Baseline odds: Dept 1 male |                      1.7232|      0.1479|   1.4564|   2.0389|   6.3398| < .001|\n|Female vs male             |                      0.9698|      0.0841|   0.8181|   1.1495|  -0.3538|  0.724|\n|Dept 2 vs Dept 1           |                      0.3198|      0.0390|   0.2518|   0.4061|  -9.3541| < .001|\n|Dept 3 vs Dept 1           |                      0.3028|      0.0363|   0.2394|   0.3830|  -9.9677| < .001|\n|Dept 4 vs Dept 1           |                      0.1993|      0.0278|   0.1517|   0.2618| -11.5812| < .001|\n|Dept 5 vs Dept 1           |                      0.0405|      0.0072|   0.0286|   0.0576| -17.9269| < .001|\n\n\n:::\n:::\n\n\nThe table above is built from `model_params()` so we can relabel terms and match the Stata-style answer key. For a report-ready regression table, `gtsummary::tbl_regression()` can format the same adjusted model in one short call:\n\n\n::: {.cell}\n\n```{.r .cell-code}\ngtsummary::tbl_regression(\n  model_adjusted,\n  exponentiate = TRUE,\n  label = list(female ~ \"Female vs male\")\n) |>\n  gtsummary::bold_labels()\n```\n\n::: {.cell-output-display}\n\n```{=html}\n<div id=\"fvgksbodci\" style=\"padding-left:0px;padding-right:0px;padding-top:10px;padding-bottom:10px;overflow-x:auto;overflow-y:auto;width:auto;height:auto;\">\n<style>#fvgksbodci table {\n  font-family: system-ui, 'Segoe UI', Roboto, Helvetica, Arial, sans-serif, 'Apple Color Emoji', 'Segoe UI Emoji', 'Segoe UI Symbol', 'Noto Color Emoji';\n  -webkit-font-smoothing: antialiased;\n  -moz-osx-font-smoothing: grayscale;\n}\n\n#fvgksbodci thead, #fvgksbodci tbody, #fvgksbodci tfoot, #fvgksbodci tr, #fvgksbodci td, #fvgksbodci th {\n  border-style: none;\n}\n\n#fvgksbodci p {\n  margin: 0;\n  padding: 0;\n}\n\n#fvgksbodci .gt_table {\n  display: table;\n  border-collapse: collapse;\n  line-height: normal;\n  margin-left: auto;\n  margin-right: auto;\n  color: #333333;\n  font-size: 16px;\n  font-weight: normal;\n  font-style: normal;\n  background-color: #FFFFFF;\n  width: auto;\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #A8A8A8;\n  border-right-style: none;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #A8A8A8;\n  border-left-style: none;\n  border-left-width: 2px;\n  border-left-color: #D3D3D3;\n}\n\n#fvgksbodci .gt_caption {\n  padding-top: 4px;\n  padding-bottom: 4px;\n}\n\n#fvgksbodci .gt_title {\n  color: #333333;\n  font-size: 125%;\n  font-weight: initial;\n  padding-top: 4px;\n  padding-bottom: 4px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-bottom-color: #FFFFFF;\n  border-bottom-width: 0;\n}\n\n#fvgksbodci .gt_subtitle {\n  color: #333333;\n  font-size: 85%;\n  font-weight: initial;\n  padding-top: 3px;\n  padding-bottom: 5px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-top-color: #FFFFFF;\n  border-top-width: 0;\n}\n\n#fvgksbodci .gt_heading {\n  background-color: #FFFFFF;\n  text-align: center;\n  border-bottom-color: #FFFFFF;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n}\n\n#fvgksbodci .gt_bottom_border {\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n}\n\n#fvgksbodci .gt_col_headings {\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n}\n\n#fvgksbodci .gt_col_heading {\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: normal;\n  text-transform: inherit;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n  vertical-align: bottom;\n  padding-top: 5px;\n  padding-bottom: 6px;\n  padding-left: 5px;\n  padding-right: 5px;\n  overflow-x: hidden;\n}\n\n#fvgksbodci .gt_column_spanner_outer {\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: normal;\n  text-transform: inherit;\n  padding-top: 0;\n  padding-bottom: 0;\n  padding-left: 4px;\n  padding-right: 4px;\n}\n\n#fvgksbodci .gt_column_spanner_outer:first-child {\n  padding-left: 0;\n}\n\n#fvgksbodci .gt_column_spanner_outer:last-child {\n  padding-right: 0;\n}\n\n#fvgksbodci .gt_column_spanner {\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  vertical-align: bottom;\n  padding-top: 5px;\n  padding-bottom: 5px;\n  overflow-x: hidden;\n  display: inline-block;\n  width: 100%;\n}\n\n#fvgksbodci .gt_spanner_row {\n  border-bottom-style: hidden;\n}\n\n#fvgksbodci .gt_group_heading {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: initial;\n  text-transform: inherit;\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n  vertical-align: middle;\n  text-align: left;\n}\n\n#fvgksbodci .gt_empty_group_heading {\n  padding: 0.5px;\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: initial;\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  vertical-align: middle;\n}\n\n#fvgksbodci .gt_from_md > :first-child {\n  margin-top: 0;\n}\n\n#fvgksbodci .gt_from_md > :last-child {\n  margin-bottom: 0;\n}\n\n#fvgksbodci .gt_row {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  margin: 10px;\n  border-top-style: solid;\n  border-top-width: 1px;\n  border-top-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n  vertical-align: middle;\n  overflow-x: hidden;\n}\n\n#fvgksbodci .gt_stub {\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: initial;\n  text-transform: inherit;\n  border-right-style: solid;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#fvgksbodci .gt_stub_row_group {\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: initial;\n  text-transform: inherit;\n  border-right-style: solid;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n  padding-left: 5px;\n  padding-right: 5px;\n  vertical-align: top;\n}\n\n#fvgksbodci .gt_row_group_first td {\n  border-top-width: 2px;\n}\n\n#fvgksbodci .gt_row_group_first th {\n  border-top-width: 2px;\n}\n\n#fvgksbodci .gt_summary_row {\n  color: #333333;\n  background-color: #FFFFFF;\n  text-transform: inherit;\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#fvgksbodci .gt_first_summary_row {\n  border-top-style: solid;\n  border-top-color: #D3D3D3;\n}\n\n#fvgksbodci .gt_first_summary_row.thick {\n  border-top-width: 2px;\n}\n\n#fvgksbodci .gt_last_summary_row {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n}\n\n#fvgksbodci .gt_grand_summary_row {\n  color: #333333;\n  background-color: #FFFFFF;\n  text-transform: inherit;\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#fvgksbodci .gt_first_grand_summary_row {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-top-style: double;\n  border-top-width: 6px;\n  border-top-color: #D3D3D3;\n}\n\n#fvgksbodci .gt_last_grand_summary_row_top {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-bottom-style: double;\n  border-bottom-width: 6px;\n  border-bottom-color: #D3D3D3;\n}\n\n#fvgksbodci .gt_striped {\n  background-color: rgba(128, 128, 128, 0.05);\n}\n\n#fvgksbodci .gt_table_body {\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n}\n\n#fvgksbodci .gt_footnotes {\n  color: #333333;\n  background-color: #FFFFFF;\n  border-bottom-style: none;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 2px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n}\n\n#fvgksbodci .gt_footnote {\n  margin: 0px;\n  font-size: 90%;\n  padding-top: 4px;\n  padding-bottom: 4px;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#fvgksbodci .gt_sourcenotes {\n  color: #333333;\n  background-color: #FFFFFF;\n  border-bottom-style: none;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 2px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n}\n\n#fvgksbodci .gt_sourcenote {\n  font-size: 90%;\n  padding-top: 4px;\n  padding-bottom: 4px;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#fvgksbodci .gt_left {\n  text-align: left;\n}\n\n#fvgksbodci .gt_center {\n  text-align: center;\n}\n\n#fvgksbodci .gt_right {\n  text-align: right;\n  font-variant-numeric: tabular-nums;\n}\n\n#fvgksbodci .gt_font_normal {\n  font-weight: normal;\n}\n\n#fvgksbodci .gt_font_bold {\n  font-weight: bold;\n}\n\n#fvgksbodci .gt_font_italic {\n  font-style: italic;\n}\n\n#fvgksbodci .gt_super {\n  font-size: 65%;\n}\n\n#fvgksbodci .gt_footnote_marks {\n  font-size: 75%;\n  vertical-align: 0.4em;\n  position: initial;\n}\n\n#fvgksbodci .gt_asterisk {\n  font-size: 100%;\n  vertical-align: 0;\n}\n\n#fvgksbodci .gt_indent_1 {\n  text-indent: 5px;\n}\n\n#fvgksbodci .gt_indent_2 {\n  text-indent: 10px;\n}\n\n#fvgksbodci .gt_indent_3 {\n  text-indent: 15px;\n}\n\n#fvgksbodci .gt_indent_4 {\n  text-indent: 20px;\n}\n\n#fvgksbodci .gt_indent_5 {\n  text-indent: 25px;\n}\n\n#fvgksbodci .katex-display {\n  display: inline-flex !important;\n  margin-bottom: 0.75em !important;\n}\n\n#fvgksbodci div.Reactable > div.rt-table > div.rt-thead > div.rt-tr.rt-tr-group-header > div.rt-th-group:after {\n  height: 0px !important;\n}\n</style>\n<table class=\"gt_table\" data-quarto-disable-processing=\"false\" data-quarto-bootstrap=\"false\">\n  <thead>\n    <tr class=\"gt_col_headings\">\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_left\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"label\"><span data-qmd-base64=\"KipDaGFyYWN0ZXJpc3RpYyoq\"><span class='gt_from_md'><strong>Characteristic</strong></span></span></th>\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_center\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"estimate\"><span data-qmd-base64=\"KipPUioq\"><span class='gt_from_md'><strong>OR</strong></span></span></th>\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_center\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"conf.low\"><span data-qmd-base64=\"Kio5NSUgQ0kqKg==\"><span class='gt_from_md'><strong>95% CI</strong></span></span></th>\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_center\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"p.value\"><span data-qmd-base64=\"KipwLXZhbHVlKio=\"><span class='gt_from_md'><strong>p-value</strong></span></span></th>\n    </tr>\n  </thead>\n  <tbody class=\"gt_table_body\">\n    <tr><td headers=\"label\" class=\"gt_row gt_left\" style=\"font-weight: bold;\">Female vs male</td>\n<td headers=\"estimate\" class=\"gt_row gt_center\">0.97</td>\n<td headers=\"conf.low\" class=\"gt_row gt_center\">0.82, 1.15</td>\n<td headers=\"p.value\" class=\"gt_row gt_center\">0.7</td></tr>\n    <tr><td headers=\"label\" class=\"gt_row gt_left\" style=\"font-weight: bold;\">factor(department)</td>\n<td headers=\"estimate\" class=\"gt_row gt_center\"><br /></td>\n<td headers=\"conf.low\" class=\"gt_row gt_center\"><br /></td>\n<td headers=\"p.value\" class=\"gt_row gt_center\"><br /></td></tr>\n    <tr><td headers=\"label\" class=\"gt_row gt_left\">    1</td>\n<td headers=\"estimate\" class=\"gt_row gt_center\">—</td>\n<td headers=\"conf.low\" class=\"gt_row gt_center\">—</td>\n<td headers=\"p.value\" class=\"gt_row gt_center\"><br /></td></tr>\n    <tr><td headers=\"label\" class=\"gt_row gt_left\">    2</td>\n<td headers=\"estimate\" class=\"gt_row gt_center\">0.32</td>\n<td headers=\"conf.low\" class=\"gt_row gt_center\">0.25, 0.41</td>\n<td headers=\"p.value\" class=\"gt_row gt_center\"><0.001</td></tr>\n    <tr><td headers=\"label\" class=\"gt_row gt_left\">    3</td>\n<td headers=\"estimate\" class=\"gt_row gt_center\">0.30</td>\n<td headers=\"conf.low\" class=\"gt_row gt_center\">0.24, 0.38</td>\n<td headers=\"p.value\" class=\"gt_row gt_center\"><0.001</td></tr>\n    <tr><td headers=\"label\" class=\"gt_row gt_left\">    4</td>\n<td headers=\"estimate\" class=\"gt_row gt_center\">0.20</td>\n<td headers=\"conf.low\" class=\"gt_row gt_center\">0.15, 0.26</td>\n<td headers=\"p.value\" class=\"gt_row gt_center\"><0.001</td></tr>\n    <tr><td headers=\"label\" class=\"gt_row gt_left\">    5</td>\n<td headers=\"estimate\" class=\"gt_row gt_center\">0.04</td>\n<td headers=\"conf.low\" class=\"gt_row gt_center\">0.03, 0.06</td>\n<td headers=\"p.value\" class=\"gt_row gt_center\"><0.001</td></tr>\n  </tbody>\n  <tfoot>\n    <tr class=\"gt_sourcenotes\">\n      <td class=\"gt_sourcenote\" colspan=\"4\"><span data-qmd-base64=\"QWJicmV2aWF0aW9uczogQ0kgPSBDb25maWRlbmNlIEludGVydmFsLCBPUiA9IE9kZHMgUmF0aW8=\"><span class='gt_from_md'>Abbreviations: CI = Confidence Interval, OR = Odds Ratio</span></span></td>\n    </tr>\n  </tfoot>\n</table>\n</div>\n```\n\n:::\n:::\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nmodel_null <- glm(admitted ~ 1, data = berk, family = binomial)\nlr_chisq <- as.numeric(deviance(model_null) - deviance(model_adjusted))\nlr_df <- attr(logLik(model_adjusted), \"df\") - attr(logLik(model_null), \"df\")\n\nadjusted_fit <- tibble(\n  n = nobs(model_adjusted),\n  log_likelihood = as.numeric(logLik(model_adjusted)),\n  lr_chisq = lr_chisq,\n  df = lr_df,\n  p = format_p(pchisq(lr_chisq, df = lr_df, lower.tail = FALSE)),\n  pseudo_r2 = 1 - as.numeric(logLik(model_adjusted) / logLik(model_null))\n)\n\nadjusted_fit |>\n  round_numeric(digits = 4)\n```\n\n::: {.cell-output-display}\n<div class=\"kable-table\">\n\n|    n| log_likelihood| lr_chisq| df|p      | pseudo_r2|\n|----:|--------------:|--------:|--:|:------|---------:|\n| 3593|      -1987.076| 536.9016|  5|< .001 |     0.119|\n\n</div>\n:::\n:::\n\n\nThe adjusted odds ratio for `female` is:\n\n$$\n\\widehat{\\text{OR}}_{\\text{female} \\mid \\text{department}} = 0.97,\n\\qquad\n95\\% \\ \\text{CI} = [0.82, 1.15],\n\\qquad\np = 0.724.\n$$\n\nHolding department constant, the estimated odds of admission for female applicants are about 0.97 times the odds for male applicants. This is very close to 1, and the confidence interval includes 1. The adjusted model therefore does not provide evidence that female and male applicants had different admission odds after accounting for department.\n\n::: {.callout-warning}\n## Do Not Treat Department as Continuous\nThe values 1, 2, 3, 4, and 5 are department codes. A model with `+ department` would assume a constant log-odds change from department 1 to 2, 2 to 3, and so on. That is not meaningful for nominal department labels.\n:::\n\n\n\n\n## Problem 4\n\n### Problem Statement\n\n> Contrast the odds ratio from Problem 3 with the odds ratio from Problem 2 and explain why they differ so much.\n\n### Solution\n\n\n::: {.cell}\n\n```{.r .cell-code}\nmodel_unadjusted <- glm(admitted ~ female, data = berk, family = binomial)\n\ncrude_model_or <- model_params(\n  model_unadjusted,\n  exponentiate = TRUE,\n  ci_method = \"wald\"\n) |>\n  as_tibble() |>\n  filter(Parameter == \"female\") |>\n  transmute(\n    model = \"Crude: female only\",\n    odds_ratio = Coefficient,\n    CI_low,\n    CI_high,\n    p = format_p(p)\n  )\n\nadjusted_female_or <- adjusted_or_table |>\n  filter(Parameter == \"Female vs male\") |>\n  transmute(\n    model = \"Adjusted: female + department\",\n    odds_ratio = Odds_ratio,\n    CI_low,\n    CI_high,\n    p\n  )\n\nor_comparison <- bind_rows(crude_model_or, adjusted_female_or)\n\nor_comparison |>\n  round_numeric(digits = 4)\n```\n\n::: {.cell-output-display}\n<div class=\"kable-table\">\n\n|model                         | odds_ratio| CI_low| CI_high|p      |\n|:-----------------------------|----------:|------:|-------:|:------|\n|Crude: female only            |     0.6394| 0.5549|  0.7368|< .001 |\n|Adjusted: female + department |     0.9698| 0.8181|  1.1495|0.724  |\n\n</div>\n:::\n:::\n\n\nFor a compact side-by-side report table, `modelsummary::modelsummary()` can show the crude and adjusted female odds ratios with one model list:\n\n\n```{.r .cell-code}\nmodelsummary::modelsummary(\n  list(\"Crude\" = model_unadjusted, \"Adjusted\" = model_adjusted),\n  exponentiate = TRUE,\n  coef_map = c(\"female\" = \"Female vs male\"),\n  statistic = \"conf.int\",\n  fmt = 3,\n  gof_omit = \"AIC|BIC|Log.Lik|RMSE|F|R2\",\n  output = \"markdown\"\n)\n```\n\n\n+----------------+----------------+----------------+\n|                | Crude          | Adjusted       |\n+================+================+================+\n| Female vs male | 0.639          | 0.970          |\n+----------------+----------------+----------------+\n|                | [0.555, 0.737] | [0.818, 1.150] |\n+----------------+----------------+----------------+\n| Num.Obs.       | 3593           | 3593           |\n+----------------+----------------+----------------+\n\n\n::: {.cell}\n::: {.cell-output-display}\n![Crude and department-adjusted odds ratios for female applicants. The crude odds ratio is below 1, while the adjusted odds ratio is close to 1.](hw08-simpsons-paradox_files/figure-html/fig-hw08-crude-adjusted-or-1.png){#fig-hw08-crude-adjusted-or fig-alt='Forest plot comparing two odds ratios for female applicants. The crude female odds ratio is about 0.64, below the null line at 1. The department-adjusted odds ratio is about 0.97 and its confidence interval crosses 1.' width=2100}\n:::\n:::\n\n\nThe crude OR is about 0.64, suggesting lower admission odds for female applicants when departments are ignored. The adjusted OR is about 0.97, suggesting nearly equal admission odds after conditioning on department.\n\nThis difference is Simpson's paradox. Department is a confounder because it is associated with both:\n\n- **gender composition:** department 1 has a very small female share, while departments 2 and 4 have much larger female shares;\n- **admission probability:** department 1 has a high admission rate, while departments 4 and 5 have low admission rates.\n\nWhen departments are collapsed, applicant gender is partly standing in for department choice. The adjusted model separates the gender comparison from department differences.\n\n\n::: {.cell}\n\n```{.r .cell-code}\ndepartment_summary <- berk |>\n  group_by(department_f) |>\n  summarise(\n    n = n(),\n    percent_female = 100 * mean(female),\n    admit_rate_male = 100 * mean(admitted[female == 0]),\n    admit_rate_female = 100 * mean(admitted[female == 1]),\n    admit_rate_overall = 100 * mean(admitted),\n    .groups = \"drop\"\n  )\n\ndepartment_summary |>\n  round_numeric(digits = 1)\n```\n\n::: {.cell-output-display}\n<div class=\"kable-table\">\n\n|department_f |   n| percent_female| admit_rate_male| admit_rate_female| admit_rate_overall|\n|:------------|---:|--------------:|---------------:|-----------------:|------------------:|\n|Dept 1       | 585|            4.3|            63.0|              68.0|               63.2|\n|Dept 2       | 918|           64.6|            36.9|              34.1|               35.1|\n|Dept 3       | 792|           47.3|            33.1|              34.9|               34.0|\n|Dept 4       | 584|           67.3|            27.7|              23.9|               25.2|\n|Dept 5       | 714|           47.8|             5.9|               7.0|                6.4|\n\n</div>\n:::\n:::\n\n\n\n\n\n## Problem 5\n\n### Problem Statement\n\n> Conduct a Wald test for the coefficient of `female`. Interpret.\n\n### Solution\n\nThe Wald test for a single coefficient tests:\n\n$$\nH_0: \\beta_{\\text{female}} = 0.\n$$\n\nFor one coefficient, the Wald test can be reported as a $z$ test or as a one-degree-of-freedom chi-square test:\n\n$$\nX^2(1) = z^2.\n$$\n\n\n::: {.cell}\n\n```{.r .cell-code}\nfemale_logit <- model_params(\n  model_adjusted,\n  exponentiate = FALSE,\n  ci_method = \"wald\"\n) |>\n  as_tibble() |>\n  filter(Parameter == \"female\")\n\nwald_female <- female_logit |>\n  transmute(\n    term = \"female\",\n    log_odds_coefficient = Coefficient,\n    SE,\n    z,\n    chi_square = z^2,\n    df = 1,\n    p = format_p(p)\n  )\n\nwald_female |>\n  round_numeric(digits = 4)\n```\n\n::: {.cell-output-display}\n<div class=\"kable-table\">\n\n|term   | log_odds_coefficient|     SE|       z| chi_square| df|p     |\n|:------|--------------------:|------:|-------:|----------:|--:|:-----|\n|female |              -0.0307| 0.0868| -0.3538|     0.1251|  1|0.724 |\n\n</div>\n:::\n:::\n\n\nThe Wald test gives:\n\n$$\nz = -0.35,\n\\qquad\nX^2(1) = 0.12,\n\\qquad\np = 0.724.\n$$\n\nWe do not reject the null hypothesis that the adjusted log-odds coefficient for `female` is zero. This is the hypothesis-test version of the odds-ratio interpretation from Problem 3.\n\n\n\n\n## Problem 6\n\n### Problem Statement\n\n> Test the goodness of fit of the model. Interpret.\n\n### Solution\n\nBecause both predictors are categorical, the data have 10 covariate patterns: 5 departments crossed with 2 gender groups. Stata's `estat gof, table` computes observed and expected admissions within those 10 patterns.\n\nWithin each gender-department pattern, every applicant has the same fitted probability because the adjusted model includes only `female` and `factor(department)`. The code below therefore uses `first(predicted_probability)` to keep one fitted probability per pattern.\n\n\n::: {.cell}\n\n```{.r .cell-code}\ngof_table <- berk |>\n  mutate(predicted_probability = fitted(model_adjusted)) |>\n  group_by(female, department) |>\n  summarise(\n    predicted_probability = first(predicted_probability),\n    observed_admitted = sum(admitted),\n    observed_not_admitted = sum(1 - admitted),\n    total = n(),\n    .groups = \"drop\"\n  ) |>\n  mutate(\n    expected_admitted = total * predicted_probability,\n    expected_not_admitted = total * (1 - predicted_probability),\n    pearson_component =\n      (observed_admitted - expected_admitted)^2 / expected_admitted +\n      (observed_not_admitted - expected_not_admitted)^2 / expected_not_admitted\n  ) |>\n  arrange(predicted_probability) |>\n  mutate(group = row_number(), .before = 1)\n\ngof_table |>\n  mutate(\n    gender = if_else(female == 1, \"Female\", \"Male\"),\n    department_label = paste(\"Dept\", department)\n  ) |>\n  select(\n    group,\n    department_label,\n    gender,\n    predicted_probability,\n    observed_admitted,\n    expected_admitted,\n    observed_not_admitted,\n    expected_not_admitted,\n    total\n  ) |>\n  round_numeric(digits = 4) |>\n  gt::gt() |>\n  gt::cols_label(\n    group = \"Group\",\n    department_label = \"Dept.\",\n    gender = \"Gender\",\n    predicted_probability = gt::md(\"Predicted<br>prob.\"),\n    observed_admitted = \"Observed\",\n    expected_admitted = \"Expected\",\n    observed_not_admitted = \"Observed\",\n    expected_not_admitted = \"Expected\",\n    total = \"Total\"\n  ) |>\n  gt::tab_spanner(\"Admitted\", columns = c(observed_admitted, expected_admitted)) |>\n  gt::tab_spanner(\"Not admitted\", columns = c(observed_not_admitted, expected_not_admitted)) |>\n  gt::fmt_number(columns = c(group, observed_admitted, observed_not_admitted, total), decimals = 0, use_seps = FALSE) |>\n  gt::fmt_number(columns = c(predicted_probability, expected_admitted, expected_not_admitted), decimals = 4) |>\n  gt::cols_align(\"left\", columns = c(department_label, gender)) |>\n  gt::cols_align(\n    \"right\",\n    columns = c(\n      group,\n      predicted_probability,\n      observed_admitted,\n      expected_admitted,\n      observed_not_admitted,\n      expected_not_admitted,\n      total\n    )\n  ) |>\n  gt::cols_width(\n    group ~ gt::pct(7),\n    department_label ~ gt::pct(10),\n    gender ~ gt::pct(10),\n    predicted_probability ~ gt::pct(15),\n    observed_admitted ~ gt::pct(11),\n    expected_admitted ~ gt::pct(12),\n    observed_not_admitted ~ gt::pct(12),\n    expected_not_admitted ~ gt::pct(13),\n    total ~ gt::pct(8)\n  ) |>\n  gt::tab_options(table.width = gt::pct(100)) |>\n  gt::tab_caption(\"Observed and expected admissions by gender-department pattern.\")\n```\n\n::: {.cell-output-display}\n\n```{=html}\n<div id=\"lggmhkwpxg\" style=\"padding-left:0px;padding-right:0px;padding-top:10px;padding-bottom:10px;overflow-x:auto;overflow-y:auto;width:auto;height:auto;\">\n<style>#lggmhkwpxg table {\n  font-family: system-ui, 'Segoe UI', Roboto, Helvetica, Arial, sans-serif, 'Apple Color Emoji', 'Segoe UI Emoji', 'Segoe UI Symbol', 'Noto Color Emoji';\n  -webkit-font-smoothing: antialiased;\n  -moz-osx-font-smoothing: grayscale;\n}\n\n#lggmhkwpxg thead, #lggmhkwpxg tbody, #lggmhkwpxg tfoot, #lggmhkwpxg tr, #lggmhkwpxg td, #lggmhkwpxg th {\n  border-style: none;\n}\n\n#lggmhkwpxg p {\n  margin: 0;\n  padding: 0;\n}\n\n#lggmhkwpxg .gt_table {\n  display: table;\n  border-collapse: collapse;\n  line-height: normal;\n  margin-left: auto;\n  margin-right: auto;\n  color: #333333;\n  font-size: 16px;\n  font-weight: normal;\n  font-style: normal;\n  background-color: #FFFFFF;\n  width: 100%;\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #A8A8A8;\n  border-right-style: none;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #A8A8A8;\n  border-left-style: none;\n  border-left-width: 2px;\n  border-left-color: #D3D3D3;\n}\n\n#lggmhkwpxg .gt_caption {\n  padding-top: 4px;\n  padding-bottom: 4px;\n}\n\n#lggmhkwpxg .gt_title {\n  color: #333333;\n  font-size: 125%;\n  font-weight: initial;\n  padding-top: 4px;\n  padding-bottom: 4px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-bottom-color: #FFFFFF;\n  border-bottom-width: 0;\n}\n\n#lggmhkwpxg .gt_subtitle {\n  color: #333333;\n  font-size: 85%;\n  font-weight: initial;\n  padding-top: 3px;\n  padding-bottom: 5px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-top-color: #FFFFFF;\n  border-top-width: 0;\n}\n\n#lggmhkwpxg .gt_heading {\n  background-color: #FFFFFF;\n  text-align: center;\n  border-bottom-color: #FFFFFF;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n}\n\n#lggmhkwpxg .gt_bottom_border {\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n}\n\n#lggmhkwpxg .gt_col_headings {\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n}\n\n#lggmhkwpxg .gt_col_heading {\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: normal;\n  text-transform: inherit;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n  vertical-align: bottom;\n  padding-top: 5px;\n  padding-bottom: 6px;\n  padding-left: 5px;\n  padding-right: 5px;\n  overflow-x: hidden;\n}\n\n#lggmhkwpxg .gt_column_spanner_outer {\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: normal;\n  text-transform: inherit;\n  padding-top: 0;\n  padding-bottom: 0;\n  padding-left: 4px;\n  padding-right: 4px;\n}\n\n#lggmhkwpxg .gt_column_spanner_outer:first-child {\n  padding-left: 0;\n}\n\n#lggmhkwpxg .gt_column_spanner_outer:last-child {\n  padding-right: 0;\n}\n\n#lggmhkwpxg .gt_column_spanner {\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  vertical-align: bottom;\n  padding-top: 5px;\n  padding-bottom: 5px;\n  overflow-x: hidden;\n  display: inline-block;\n  width: 100%;\n}\n\n#lggmhkwpxg .gt_spanner_row {\n  border-bottom-style: hidden;\n}\n\n#lggmhkwpxg .gt_group_heading {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: initial;\n  text-transform: inherit;\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n  vertical-align: middle;\n  text-align: left;\n}\n\n#lggmhkwpxg .gt_empty_group_heading {\n  padding: 0.5px;\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: initial;\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  vertical-align: middle;\n}\n\n#lggmhkwpxg .gt_from_md > :first-child {\n  margin-top: 0;\n}\n\n#lggmhkwpxg .gt_from_md > :last-child {\n  margin-bottom: 0;\n}\n\n#lggmhkwpxg .gt_row {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  margin: 10px;\n  border-top-style: solid;\n  border-top-width: 1px;\n  border-top-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n  vertical-align: middle;\n  overflow-x: hidden;\n}\n\n#lggmhkwpxg .gt_stub {\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: initial;\n  text-transform: inherit;\n  border-right-style: solid;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#lggmhkwpxg .gt_stub_row_group {\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: initial;\n  text-transform: inherit;\n  border-right-style: solid;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n  padding-left: 5px;\n  padding-right: 5px;\n  vertical-align: top;\n}\n\n#lggmhkwpxg .gt_row_group_first td {\n  border-top-width: 2px;\n}\n\n#lggmhkwpxg .gt_row_group_first th {\n  border-top-width: 2px;\n}\n\n#lggmhkwpxg .gt_summary_row {\n  color: #333333;\n  background-color: #FFFFFF;\n  text-transform: inherit;\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#lggmhkwpxg .gt_first_summary_row {\n  border-top-style: solid;\n  border-top-color: #D3D3D3;\n}\n\n#lggmhkwpxg .gt_first_summary_row.thick {\n  border-top-width: 2px;\n}\n\n#lggmhkwpxg .gt_last_summary_row {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n}\n\n#lggmhkwpxg .gt_grand_summary_row {\n  color: #333333;\n  background-color: #FFFFFF;\n  text-transform: inherit;\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#lggmhkwpxg .gt_first_grand_summary_row {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-top-style: double;\n  border-top-width: 6px;\n  border-top-color: #D3D3D3;\n}\n\n#lggmhkwpxg .gt_last_grand_summary_row_top {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-bottom-style: double;\n  border-bottom-width: 6px;\n  border-bottom-color: #D3D3D3;\n}\n\n#lggmhkwpxg .gt_striped {\n  background-color: rgba(128, 128, 128, 0.05);\n}\n\n#lggmhkwpxg .gt_table_body {\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n}\n\n#lggmhkwpxg .gt_footnotes {\n  color: #333333;\n  background-color: #FFFFFF;\n  border-bottom-style: none;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 2px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n}\n\n#lggmhkwpxg .gt_footnote {\n  margin: 0px;\n  font-size: 90%;\n  padding-top: 4px;\n  padding-bottom: 4px;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#lggmhkwpxg .gt_sourcenotes {\n  color: #333333;\n  background-color: #FFFFFF;\n  border-bottom-style: none;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 2px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n}\n\n#lggmhkwpxg .gt_sourcenote {\n  font-size: 90%;\n  padding-top: 4px;\n  padding-bottom: 4px;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#lggmhkwpxg .gt_left {\n  text-align: left;\n}\n\n#lggmhkwpxg .gt_center {\n  text-align: center;\n}\n\n#lggmhkwpxg .gt_right {\n  text-align: right;\n  font-variant-numeric: tabular-nums;\n}\n\n#lggmhkwpxg .gt_font_normal {\n  font-weight: normal;\n}\n\n#lggmhkwpxg .gt_font_bold {\n  font-weight: bold;\n}\n\n#lggmhkwpxg .gt_font_italic {\n  font-style: italic;\n}\n\n#lggmhkwpxg .gt_super {\n  font-size: 65%;\n}\n\n#lggmhkwpxg .gt_footnote_marks {\n  font-size: 75%;\n  vertical-align: 0.4em;\n  position: initial;\n}\n\n#lggmhkwpxg .gt_asterisk {\n  font-size: 100%;\n  vertical-align: 0;\n}\n\n#lggmhkwpxg .gt_indent_1 {\n  text-indent: 5px;\n}\n\n#lggmhkwpxg .gt_indent_2 {\n  text-indent: 10px;\n}\n\n#lggmhkwpxg .gt_indent_3 {\n  text-indent: 15px;\n}\n\n#lggmhkwpxg .gt_indent_4 {\n  text-indent: 20px;\n}\n\n#lggmhkwpxg .gt_indent_5 {\n  text-indent: 25px;\n}\n\n#lggmhkwpxg .katex-display {\n  display: inline-flex !important;\n  margin-bottom: 0.75em !important;\n}\n\n#lggmhkwpxg div.Reactable > div.rt-table > div.rt-thead > div.rt-tr.rt-tr-group-header > div.rt-th-group:after {\n  height: 0px !important;\n}\n</style>\n<table class=\"gt_table\" style=\"table-layout:fixed;width:100%;\" data-quarto-disable-processing=\"false\" data-quarto-bootstrap=\"false\">\n  <caption>Observed and expected admissions by gender-department pattern.</caption>\n  <colgroup>\n    <col style=\"width:7%;\"/>\n    <col style=\"width:10%;\"/>\n    <col style=\"width:10%;\"/>\n    <col style=\"width:15%;\"/>\n    <col style=\"width:11%;\"/>\n    <col style=\"width:12%;\"/>\n    <col style=\"width:12%;\"/>\n    <col style=\"width:13%;\"/>\n    <col style=\"width:8%;\"/>\n  </colgroup>\n  <thead>\n    <tr class=\"gt_col_headings gt_spanner_row\">\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_right\" rowspan=\"2\" colspan=\"1\" scope=\"col\" id=\"group\">Group</th>\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_left\" rowspan=\"2\" colspan=\"1\" scope=\"col\" id=\"department_label\">Dept.</th>\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_left\" rowspan=\"2\" colspan=\"1\" scope=\"col\" id=\"gender\">Gender</th>\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_right\" rowspan=\"2\" colspan=\"1\" scope=\"col\" id=\"predicted_probability\"><span data-qmd-base64=\"UHJlZGljdGVkPGJyPnByb2Iu\"><span class='gt_from_md'>Predicted<br>prob.</span></span></th>\n      <th class=\"gt_center gt_columns_top_border gt_column_spanner_outer\" rowspan=\"1\" colspan=\"2\" scope=\"colgroup\" id=\"Admitted\">\n        <div class=\"gt_column_spanner\">Admitted</div>\n      </th>\n      <th class=\"gt_center gt_columns_top_border gt_column_spanner_outer\" rowspan=\"1\" colspan=\"2\" scope=\"colgroup\" id=\"Not admitted\">\n        <div class=\"gt_column_spanner\">Not admitted</div>\n      </th>\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_right\" rowspan=\"2\" colspan=\"1\" scope=\"col\" id=\"total\">Total</th>\n    </tr>\n    <tr class=\"gt_col_headings\">\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_right\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"observed_admitted\">Observed</th>\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_right\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"expected_admitted\">Expected</th>\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_right\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"observed_not_admitted\">Observed</th>\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_right\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"expected_not_admitted\">Expected</th>\n    </tr>\n  </thead>\n  <tbody class=\"gt_table_body\">\n    <tr><td headers=\"group\" class=\"gt_row gt_right\">1</td>\n<td headers=\"department_label\" class=\"gt_row gt_left\">Dept 5</td>\n<td headers=\"gender\" class=\"gt_row gt_left\">Female</td>\n<td headers=\"predicted_probability\" class=\"gt_row gt_right\">0.0635</td>\n<td headers=\"observed_admitted\" class=\"gt_row gt_right\">24</td>\n<td headers=\"expected_admitted\" class=\"gt_row gt_right\">21.6399</td>\n<td headers=\"observed_not_admitted\" class=\"gt_row gt_right\">317</td>\n<td headers=\"expected_not_admitted\" class=\"gt_row gt_right\">319.3601</td>\n<td headers=\"total\" class=\"gt_row gt_right\">341</td></tr>\n    <tr><td headers=\"group\" class=\"gt_row gt_right\">2</td>\n<td headers=\"department_label\" class=\"gt_row gt_left\">Dept 5</td>\n<td headers=\"gender\" class=\"gt_row gt_left\">Male</td>\n<td headers=\"predicted_probability\" class=\"gt_row gt_right\">0.0653</td>\n<td headers=\"observed_admitted\" class=\"gt_row gt_right\">22</td>\n<td headers=\"expected_admitted\" class=\"gt_row gt_right\">24.3601</td>\n<td headers=\"observed_not_admitted\" class=\"gt_row gt_right\">351</td>\n<td headers=\"expected_not_admitted\" class=\"gt_row gt_right\">348.6399</td>\n<td headers=\"total\" class=\"gt_row gt_right\">373</td></tr>\n    <tr><td headers=\"group\" class=\"gt_row gt_right\">3</td>\n<td headers=\"department_label\" class=\"gt_row gt_left\">Dept 4</td>\n<td headers=\"gender\" class=\"gt_row gt_left\">Female</td>\n<td headers=\"predicted_probability\" class=\"gt_row gt_right\">0.2498</td>\n<td headers=\"observed_admitted\" class=\"gt_row gt_right\">94</td>\n<td headers=\"expected_admitted\" class=\"gt_row gt_right\">98.1780</td>\n<td headers=\"observed_not_admitted\" class=\"gt_row gt_right\">299</td>\n<td headers=\"expected_not_admitted\" class=\"gt_row gt_right\">294.8220</td>\n<td headers=\"total\" class=\"gt_row gt_right\">393</td></tr>\n    <tr><td headers=\"group\" class=\"gt_row gt_right\">4</td>\n<td headers=\"department_label\" class=\"gt_row gt_left\">Dept 4</td>\n<td headers=\"gender\" class=\"gt_row gt_left\">Male</td>\n<td headers=\"predicted_probability\" class=\"gt_row gt_right\">0.2556</td>\n<td headers=\"observed_admitted\" class=\"gt_row gt_right\">53</td>\n<td headers=\"expected_admitted\" class=\"gt_row gt_right\">48.8220</td>\n<td headers=\"observed_not_admitted\" class=\"gt_row gt_right\">138</td>\n<td headers=\"expected_not_admitted\" class=\"gt_row gt_right\">142.1780</td>\n<td headers=\"total\" class=\"gt_row gt_right\">191</td></tr>\n    <tr><td headers=\"group\" class=\"gt_row gt_right\">5</td>\n<td headers=\"department_label\" class=\"gt_row gt_left\">Dept 3</td>\n<td headers=\"gender\" class=\"gt_row gt_left\">Female</td>\n<td headers=\"predicted_probability\" class=\"gt_row gt_right\">0.3360</td>\n<td headers=\"observed_admitted\" class=\"gt_row gt_right\">131</td>\n<td headers=\"expected_admitted\" class=\"gt_row gt_right\">126.0087</td>\n<td headers=\"observed_not_admitted\" class=\"gt_row gt_right\">244</td>\n<td headers=\"expected_not_admitted\" class=\"gt_row gt_right\">248.9913</td>\n<td headers=\"total\" class=\"gt_row gt_right\">375</td></tr>\n    <tr><td headers=\"group\" class=\"gt_row gt_right\">6</td>\n<td headers=\"department_label\" class=\"gt_row gt_left\">Dept 3</td>\n<td headers=\"gender\" class=\"gt_row gt_left\">Male</td>\n<td headers=\"predicted_probability\" class=\"gt_row gt_right\">0.3429</td>\n<td headers=\"observed_admitted\" class=\"gt_row gt_right\">138</td>\n<td headers=\"expected_admitted\" class=\"gt_row gt_right\">142.9913</td>\n<td headers=\"observed_not_admitted\" class=\"gt_row gt_right\">279</td>\n<td headers=\"expected_not_admitted\" class=\"gt_row gt_right\">274.0087</td>\n<td headers=\"total\" class=\"gt_row gt_right\">417</td></tr>\n    <tr><td headers=\"group\" class=\"gt_row gt_right\">7</td>\n<td headers=\"department_label\" class=\"gt_row gt_left\">Dept 2</td>\n<td headers=\"gender\" class=\"gt_row gt_left\">Female</td>\n<td headers=\"predicted_probability\" class=\"gt_row gt_right\">0.3483</td>\n<td headers=\"observed_admitted\" class=\"gt_row gt_right\">202</td>\n<td headers=\"expected_admitted\" class=\"gt_row gt_right\">206.5329</td>\n<td headers=\"observed_not_admitted\" class=\"gt_row gt_right\">391</td>\n<td headers=\"expected_not_admitted\" class=\"gt_row gt_right\">386.4671</td>\n<td headers=\"total\" class=\"gt_row gt_right\">593</td></tr>\n    <tr><td headers=\"group\" class=\"gt_row gt_right\">8</td>\n<td headers=\"department_label\" class=\"gt_row gt_left\">Dept 2</td>\n<td headers=\"gender\" class=\"gt_row gt_left\">Male</td>\n<td headers=\"predicted_probability\" class=\"gt_row gt_right\">0.3553</td>\n<td headers=\"observed_admitted\" class=\"gt_row gt_right\">120</td>\n<td headers=\"expected_admitted\" class=\"gt_row gt_right\">115.4671</td>\n<td headers=\"observed_not_admitted\" class=\"gt_row gt_right\">205</td>\n<td headers=\"expected_not_admitted\" class=\"gt_row gt_right\">209.5329</td>\n<td headers=\"total\" class=\"gt_row gt_right\">325</td></tr>\n    <tr><td headers=\"group\" class=\"gt_row gt_right\">9</td>\n<td headers=\"department_label\" class=\"gt_row gt_left\">Dept 1</td>\n<td headers=\"gender\" class=\"gt_row gt_left\">Female</td>\n<td headers=\"predicted_probability\" class=\"gt_row gt_right\">0.6256</td>\n<td headers=\"observed_admitted\" class=\"gt_row gt_right\">17</td>\n<td headers=\"expected_admitted\" class=\"gt_row gt_right\">15.6406</td>\n<td headers=\"observed_not_admitted\" class=\"gt_row gt_right\">8</td>\n<td headers=\"expected_not_admitted\" class=\"gt_row gt_right\">9.3594</td>\n<td headers=\"total\" class=\"gt_row gt_right\">25</td></tr>\n    <tr><td headers=\"group\" class=\"gt_row gt_right\">10</td>\n<td headers=\"department_label\" class=\"gt_row gt_left\">Dept 1</td>\n<td headers=\"gender\" class=\"gt_row gt_left\">Male</td>\n<td headers=\"predicted_probability\" class=\"gt_row gt_right\">0.6328</td>\n<td headers=\"observed_admitted\" class=\"gt_row gt_right\">353</td>\n<td headers=\"expected_admitted\" class=\"gt_row gt_right\">354.3594</td>\n<td headers=\"observed_not_admitted\" class=\"gt_row gt_right\">207</td>\n<td headers=\"expected_not_admitted\" class=\"gt_row gt_right\">205.6406</td>\n<td headers=\"total\" class=\"gt_row gt_right\">560</td></tr>\n  </tbody>\n  \n</table>\n</div>\n```\n\n:::\n:::\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\npearson_chisq <- sum(gof_table$pearson_component)\ndf_gof <- nrow(gof_table) - length(coef(model_adjusted))\np_gof <- pchisq(pearson_chisq, df = df_gof, lower.tail = FALSE)\n\ngof_summary <- tibble(\n  statistic = \"Grouped Pearson X2\",\n  value = pearson_chisq,\n  df = df_gof,\n  p = format_p(p_gof)\n)\n\ngof_summary |>\n  round_numeric(digits = 4)\n```\n\n::: {.cell-output-display}\n<div class=\"kable-table\">\n\n|statistic          |  value| df|p     |\n|:------------------|------:|--:|:-----|\n|Grouped Pearson X2 | 2.5582|  4|0.634 |\n\n</div>\n:::\n:::\n\n\nThe goodness-of-fit result is:\n\n$$\nX^2(4) = 2.56,\n\\qquad\np = 0.634.\n$$\n\nThere is no evidence of lack of fit. In this categorical model, lack of fit would correspond to a gender-by-department interaction. The additive model with `female` plus department is adequate for these data.\n\n::: {.callout-warning}\n## Grouped, Not Individual, Pearson Residuals\nFor this Stata-style goodness-of-fit test, compute observed and expected counts by covariate pattern. Summing individual-level Pearson residuals is not the same test and does not reproduce `estat gof, table`.\n:::\n\n\n\n\n## Summary\n\nThis homework shows Simpson's paradox in a logistic-regression setting:\n\n1. The collapsed table gives a crude female-vs-male odds ratio of about 0.64.\n\n2. After adjusting for department, the female odds ratio is about 0.97, with $p = 0.724$.\n\n3. The difference occurs because department is associated with both applicant gender and admission probability.\n\n4. The Wald test does not provide evidence against equal adjusted admission odds for female and male applicants.\n\n5. The grouped Pearson goodness-of-fit test gives $X^2(4) = 2.56$, $p = 0.634$, so there is no evidence that the additive gender-plus-department model lacks fit.\n\nThe core lesson is practical: always compare crude and adjusted estimates when a confounder is plausible. In this example, the aggregate gender comparison is misleading because it ignores department.\n",
    "supporting": [
      "hw08-simpsons-paradox_files"
    ],
    "filters": [
      "rmarkdown/pagebreak.lua"
    ],
    "includes": {},
    "engineDependencies": {},
    "preserve": {},
    "postProcess": true
  }
}