{
  "hash": "05a81a4747318784b26dff9266490597",
  "result": {
    "engine": "knitr",
    "markdown": "# Logistic Regression Diagnostics {#sec-ch11}\n\n\n\n\n## Introduction {#sec-ch11-intro}\n\nIn @sec-ch8, we developed a comprehensive diagnostic toolkit for linear regression: residuals-vs-fitted plots, Q-Q plots, leverage and Cook's distance, and formal tests for heteroscedasticity and normality. Those tools all rest on the assumption that the response is continuous and the errors are normally distributed --- assumptions that do not hold for logistic regression.\n\nLogistic regression has its own set of diagnostic challenges. Because the outcome is binary (0 or 1), the raw residuals take only two possible values for each fitted probability, making standard residual plots nearly useless. There is no direct analogue of $R^2$ that everyone agrees on. And the very meaning of \"goodness of fit\" depends on whether the predictors are categorical (producing a small number of covariate patterns) or continuous (producing many unique patterns, often one per observation).\n\nThis chapter develops the diagnostic toolkit for logistic regression models. We cover five key areas:\n\n1. **Goodness-of-fit tests** (Pearson $X^2$ and Deviance $G^2$) that assess whether the model adequately reproduces the observed data\n2. **Pseudo $R^2$ measures** that quantify how much the model improves over a null model\n3. **Classification accuracy** using predicted classes and the kappa statistic\n4. **Residual diagnostics** including binned residual plots and calibration plots\n5. **Influence diagnostics** using Cook's distance, DFBETAS, and influence bubble plots\n\n::: {.objectives}\n[Learning Objectives]{.obj-title}\n\nAfter completing this chapter, you will be able to:\n\n1. Explain why standard goodness-of-fit tests require grouped (non-sparse) data and identify when sparseness invalidates $p$-values\n2. Compute and interpret the Pearson $X^2$ and Deviance $G^2$ statistics for logistic regression models\n3. Define and compute at least six pseudo $R^2$ measures and explain why no single measure dominates\n4. Construct a classification table, compute sensitivity, specificity, and Cohen's kappa\n5. Calculate and interpret Pearson and deviance residuals for logistic regression\n6. Construct and interpret binned residual plots and calibration plots for models with continuous predictors\n7. Use DFBETAS, Cook's distance, and influence bubble plots to detect influential observations\n8. Recognize the Wald-vs-LR test discrepancy as an indicator of sparse data\n9. Map each OLS diagnostic from @sec-ch8 to its logistic regression analogue\n:::\n\n::: {.callout-important}\n## Connection to OLS Diagnostics (@sec-ch8)\nThe diagnostic logic from @sec-ch8 carries forward: check model specification, identify influential observations, and assess robustness of conclusions. The key differences for logistic regression are:\n\n| OLS Diagnostic (@sec-ch8) | Logistic Analogue (this chapter) |\n|:---|:---|\n| Raw residuals $e_i = y_i - \\hat{y}_i$ | Pearson / deviance residuals |\n| $R^2$ (proportion of variance explained) | Pseudo $R^2$ (multiple definitions) |\n| $F$-test for overall model | Likelihood ratio test, $X^2$/$G^2$ |\n| Q-Q plot for normality | Not applicable (binary outcome) |\n| Residual vs. fitted plot | Binned residual plot (continuous predictors) |\n| Cook's distance, leverage, DFBETAS | Same tools, adapted for GLM hat matrix |\n\n: Mapping between OLS and logistic regression diagnostics. {#tbl-ch11-ols-comparison}\n\nThe fundamental mindset is the same: no single diagnostic is definitive. Use multiple tools and triangulate.\n:::\n\n\n## Motivating Example: Death Penalty Data {#sec-ch11-example}\n\nWe use the `penalty` dataset from `regdatasets`, which contains 674 murder cases from a classic study of racial bias in death penalty sentencing. The variables are:\n\n- `death_pe`: Whether the death penalty was imposed (1 = yes, 0 = no)\n- `def_bl`: Defendant's race (1 = Black, 0 = White)\n- `vic_bl`: Victim's race (1 = Black, 0 = White)\n\nBecause both predictors are binary, the data collapse into a $2 \\times 2 \\times 2$ contingency table with only four covariate patterns. This makes the data a compact, easy-to-read example for demonstrating goodness-of-fit tests. Note, however, that the death-sentence outcome is rare, so in one covariate pattern the *expected* number of death sentences is only about 0.18 --- far below the conventional threshold of 5. The $X^2$/$G^2$ chi-square approximation here is therefore illustrative and somewhat fragile rather than ideal. Later, we return to the `titanic` data from @sec-ch9 to illustrate diagnostics when continuous predictors create sparse tables.\n\n### Loading and Summarizing the Data\n\n::: {.panel-tabset}\n### Output\n\n::: {.cell}\n\n```{.r .cell-code  code-fold=\"true\" code-summary=\"Show R Code\"}\n# Load the death penalty data\ndata(penalty)\n\n# Cross-tabulation: observed counts\npenalty_table <- penalty |>\n  count(def_bl, vic_bl, death_pe) |>\n  pivot_wider(names_from = death_pe, values_from = n, values_fill = 0) |>\n  rename(no_death = `0`, death = `1`) |>\n  mutate(total = no_death + death,\n         prop_death = death / total)\n\npenalty_table |>\n  kable(digits = 3,\n        col.names = c(\"Defendant Black\", \"Victim Black\",\n                       \"No Death\", \"Death\", \"Total\", \"P(Death)\"))\n```\n\n::: {.cell-output-display}\n\n\n| Defendant Black| Victim Black| No Death| Death| Total| P(Death)|\n|---------------:|------------:|--------:|-----:|-----:|--------:|\n|               0|            0|      414|    53|   467|    0.113|\n|               0|            1|       16|     0|    16|    0.000|\n|               1|            0|       37|    11|    48|    0.229|\n|               1|            1|      139|     4|   143|    0.028|\n\n\n:::\n:::\n\n\n### Output Interpretation\n\n\n::: {.cell}\n::: {.cell-output-display}\n\n\n| Defendant Black| Victim Black| No Death| Death| Total| P(Death)|\n|---------------:|------------:|--------:|-----:|-----:|--------:|\n|               0|            0|      414|    53|   467|    0.113|\n|               0|            1|       16|     0|    16|    0.000|\n|               1|            0|       37|    11|    48|    0.229|\n|               1|            1|      139|     4|   143|    0.028|\n\n\n:::\n:::\n\nThe table reveals that the death penalty rate varies across the four groups. Cases with White victims have higher death penalty rates, regardless of the defendant's race. This is the pattern a logistic regression model should capture.\n\n### Code Explanation\n\n::: {.cell}\n\n```{.r .cell-code}\n# Load the death penalty data\ndata(penalty)\n\n# Cross-tabulation: observed counts\npenalty_table <- penalty |>\n  count(def_bl, vic_bl, death_pe) |>\n  pivot_wider(names_from = death_pe, values_from = n, values_fill = 0) |>\n  rename(no_death = `0`, death = `1`) |>\n  mutate(total = no_death + death,\n         prop_death = death / total)\n\npenalty_table |>\n  kable(digits = 3,\n        col.names = c(\"Defendant Black\", \"Victim Black\",\n                       \"No Death\", \"Death\", \"Total\", \"P(Death)\"))\n```\n\n::: {.cell-output-display}\n\n\n| Defendant Black| Victim Black| No Death| Death| Total| P(Death)|\n|---------------:|------------:|--------:|-----:|-----:|--------:|\n|               0|            0|      414|    53|   467|    0.113|\n|               0|            1|       16|     0|    16|    0.000|\n|               1|            0|       37|    11|    48|    0.229|\n|               1|            1|      139|     4|   143|    0.028|\n\n\n:::\n:::\n\n- `count()` tallies the number of cases for each combination of defendant race, victim race, and sentencing outcome\n- `pivot_wider()` reshapes so that each row is a unique covariate pattern\n- `prop_death` is the observed proportion receiving the death penalty within each group\n- Although the total count per covariate pattern is moderate, the *expected* number of death sentences in one pattern (`def_bl` = 0, `vic_bl` = 1) is only about 0.18 --- well below 5 --- so this cell is sparse and the grouped-test $p$-values should be read as approximate\n\n\n:::\n\n\n### Fitting the Model\n\n::: {.panel-tabset}\n### Output\n\n::: {.cell}\n\n```{.r .cell-code  code-fold=\"true\" code-summary=\"Show R Code\"}\n# Fit logistic regression: death penalty ~ defendant race + victim race\npenalty_model <- glm(death_pe ~ def_bl + vic_bl,\n                     family = binomial, data = penalty)\n\nmodel_parameters(penalty_model, exponentiate = TRUE) |> print_md()\n```\n\n::: {.cell-output-display}\n\n\n|Parameter   | Odds Ratio |   SE |       95% CI |      z |      p |\n|:-----------|:----------:|:----:|:------------:|:------:|:------:|\n|(Intercept) |       0.13 | 0.02 | (0.09, 0.17) | -14.12 | < .001 |\n|def bl      |       2.38 | 0.87 | (1.12, 4.77) |   2.36 | 0.018  |\n|vic bl      |       0.09 | 0.05 | (0.02, 0.27) |  -4.00 | < .001 |\n\n\n:::\n:::\n\n\n### Output Interpretation\n\n\n::: {.cell}\n::: {.cell-output-display}\n\n\n|Parameter   | Odds Ratio |   SE |       95% CI |      z |      p |\n|:-----------|:----------:|:----:|:------------:|:------:|:------:|\n|(Intercept) |       0.13 | 0.02 | (0.09, 0.17) | -14.12 | < .001 |\n|def bl      |       2.38 | 0.87 | (1.12, 4.77) |   2.36 | 0.018  |\n|vic bl      |       0.09 | 0.05 | (0.02, 0.27) |  -4.00 | < .001 |\n\n\n:::\n:::\n\nExamine the odds ratios. The effect of victim race on death penalty sentencing is the key substantive finding. We now turn to assessing whether this model fits the data adequately.\n\n### Code Explanation\n\n::: {.cell}\n\n```{.r .cell-code}\n# Fit logistic regression: death penalty ~ defendant race + victim race\npenalty_model <- glm(death_pe ~ def_bl + vic_bl,\n                     family = binomial, data = penalty)\n\nmodel_parameters(penalty_model, exponentiate = TRUE) |> print_md()\n```\n\n::: {.cell-output-display}\n\n\n|Parameter   | Odds Ratio |   SE |       95% CI |      z |      p |\n|:-----------|:----------:|:----:|:------------:|:------:|:------:|\n|(Intercept) |       0.13 | 0.02 | (0.09, 0.17) | -14.12 | < .001 |\n|def bl      |       2.38 | 0.87 | (1.12, 4.77) |   2.36 | 0.018  |\n|vic bl      |       0.09 | 0.05 | (0.02, 0.27) |  -4.00 | < .001 |\n\n\n:::\n:::\n\n- `glm()` with `family = binomial` fits the logistic regression model\n- `exponentiate = TRUE` shows odds ratios instead of log-odds\n- The model includes main effects of defendant and victim race (no interaction)\n\n\n:::\n\n\n## Goodness of Fit Tests {#sec-ch11-gof}\n\nIn linear regression, the $F$-test tells us whether the model as a whole explains significant variance. In logistic regression, goodness-of-fit tests ask a different question: **does the model adequately reproduce the observed frequencies?** Two classic tests compare observed and expected counts across covariate patterns.\n\n### Covariate Patterns and Grouped Data\n\nA **covariate pattern** is a unique combination of predictor values. For the `penalty` model with two binary predictors, there are $2 \\times 2 = 4$ covariate patterns. If we let $J$ denote the number of covariate patterns, $n_j$ the number of observations with pattern $j$, and $y_j$ the number of \"successes\" (death penalties) in that group, then the observed proportion is $\\hat{p}_j = y_j / n_j$ and the model-predicted proportion is $\\hat{\\pi}_j$.\n\n### Pearson Chi-Square ($X^2$) {#sec-ch11-pearson-x2}\n\nThe Pearson goodness-of-fit statistic compares observed and expected counts:\n\n$$\nX^2 = \\sum_{j=1}^{J} \\frac{(y_j - n_j \\hat{\\pi}_j)^2}{n_j \\hat{\\pi}_j (1 - \\hat{\\pi}_j)}\n$$ {#eq-ch11-pearson-x2}\n\nUnder the null hypothesis that the model is correctly specified, $X^2 \\sim \\chi^2_{J - p}$ where $p$ is the number of estimated parameters (including the intercept). A large $X^2$ (small $p$-value) indicates that the model does **not** fit the data well.\n\n### Deviance ($G^2$) {#sec-ch11-deviance-g2}\n\nThe deviance (or likelihood ratio) goodness-of-fit statistic compares the fitted model to the **saturated model** --- the model that perfectly reproduces all observed proportions:\n\n$$\nG^2 = 2 \\sum_{j=1}^{J} \\left[ y_j \\ln\\!\\left(\\frac{y_j}{n_j \\hat{\\pi}_j}\\right) + (n_j - y_j) \\ln\\!\\left(\\frac{n_j - y_j}{n_j(1 - \\hat{\\pi}_j)}\\right) \\right]\n$$ {#eq-ch11-deviance-g2}\n\nUnder the null hypothesis, $G^2 \\sim \\chi^2_{J - p}$, with the same degrees of freedom as $X^2$.\n\n### Computing $X^2$ and $G^2$\n\n::: {.panel-tabset}\n### Output\n\n::: {.cell}\n\n```{.r .cell-code  code-fold=\"true\" code-summary=\"Show R Code\"}\n# Get fitted probabilities for each covariate pattern\npenalty_gof <- penalty |>\n  mutate(pi_hat = fitted(penalty_model)) |>\n  group_by(def_bl, vic_bl) |>\n  summarise(\n    n_j     = n(),\n    y_j     = sum(death_pe),\n    pi_hat  = first(pi_hat),\n    .groups = \"drop\"\n  ) |>\n  mutate(\n    expected = n_j * pi_hat,\n    # Pearson components\n    pearson_comp = (y_j - expected)^2 / (expected * (1 - pi_hat)),\n    # Deviance components (handling zero cells carefully)\n    dev_comp = 2 * (\n      ifelse(y_j > 0, y_j * log(y_j / expected), 0) +\n      ifelse(n_j - y_j > 0,\n             (n_j - y_j) * log((n_j - y_j) / (n_j * (1 - pi_hat))), 0)\n    )\n  )\n\n# Display the grouped table\npenalty_gof |>\n  select(def_bl, vic_bl, n_j, y_j, expected, pearson_comp, dev_comp) |>\n  kable(digits = 3,\n        col.names = c(\"Def Black\", \"Vic Black\", \"n\", \"Observed\",\n                       \"Expected\", \"Pearson Comp\", \"Deviance Comp\"))\n```\n\n::: {.cell-output-display}\n\n\n| Def Black| Vic Black|   n| Observed| Expected| Pearson Comp| Deviance Comp|\n|---------:|---------:|---:|--------:|--------:|------------:|-------------:|\n|         0|         0| 467|       53|   52.818|        0.001|         0.001|\n|         0|         1|  16|        0|    0.182|        0.184|         0.366|\n|         1|         0|  48|       11|   11.182|        0.004|         0.004|\n|         1|         1| 143|        4|    3.818|        0.009|         0.009|\n\n\n:::\n\n```{.r .cell-code  code-fold=\"true\" code-summary=\"Show R Code\"}\n# Compute test statistics\nX2 <- sum(penalty_gof$pearson_comp)\nG2 <- sum(penalty_gof$dev_comp)\nJ <- nrow(penalty_gof)\np_params <- length(coef(penalty_model))\ndf_gof <- J - p_params\n\ntibble(\n  Statistic = c(\"Pearson X²\", \"Deviance G²\"),\n  Value     = round(c(X2, G2), 4),\n  df        = df_gof,\n  p_value   = round(1 - pchisq(c(X2, G2), df_gof), 4)\n) |>\n  kable(col.names = c(\"Statistic\", \"Value\", \"df\", \"p-value\"))\n```\n\n::: {.cell-output-display}\n\n\n|Statistic   |  Value| df| p-value|\n|:-----------|------:|--:|-------:|\n|Pearson X²  | 0.1978|  1|  0.6565|\n|Deviance G² | 0.3798|  1|  0.5377|\n\n\n:::\n:::\n\n\n### Output Interpretation\n\n\n::: {.cell}\n::: {.cell-output-display}\n\n\n| Def Black| Vic Black|   n| Observed| Expected| Pearson Comp| Deviance Comp|\n|---------:|---------:|---:|--------:|--------:|------------:|-------------:|\n|         0|         0| 467|       53|   52.818|        0.001|         0.001|\n|         0|         1|  16|        0|    0.182|        0.184|         0.366|\n|         1|         0|  48|       11|   11.182|        0.004|         0.004|\n|         1|         1| 143|        4|    3.818|        0.009|         0.009|\n\n\n:::\n\n::: {.cell-output-display}\n\n\n|Statistic   |  Value| df| p-value|\n|:-----------|------:|--:|-------:|\n|Pearson X²  | 0.1978|  1|  0.6565|\n|Deviance G² | 0.3798|  1|  0.5377|\n\n\n:::\n:::\n\nWith only 1 degree of freedom, the test has limited power. A non-significant result does **not** prove good fit: with $df = 1$, one expected count near 0.18, and low power, the chi-square approximation is fragile. It means we do not find *evidence* of lack of fit, not that the interaction between defendant and victim race is definitely unneeded. If the $p$-value were small, we would conclude the model fails to capture the observed pattern and should consider adding the interaction term.\n\n### Code Explanation\n\n::: {.cell}\n\n```{.r .cell-code}\n# Get fitted probabilities for each covariate pattern\npenalty_gof <- penalty |>\n  mutate(pi_hat = fitted(penalty_model)) |>\n  group_by(def_bl, vic_bl) |>\n  summarise(\n    n_j     = n(),\n    y_j     = sum(death_pe),\n    pi_hat  = first(pi_hat),\n    .groups = \"drop\"\n  ) |>\n  mutate(\n    expected = n_j * pi_hat,\n    # Pearson components\n    pearson_comp = (y_j - expected)^2 / (expected * (1 - pi_hat)),\n    # Deviance components (handling zero cells carefully)\n    dev_comp = 2 * (\n      ifelse(y_j > 0, y_j * log(y_j / expected), 0) +\n      ifelse(n_j - y_j > 0,\n             (n_j - y_j) * log((n_j - y_j) / (n_j * (1 - pi_hat))), 0)\n    )\n  )\n\n# Display the grouped table\npenalty_gof |>\n  select(def_bl, vic_bl, n_j, y_j, expected, pearson_comp, dev_comp) |>\n  kable(digits = 3,\n        col.names = c(\"Def Black\", \"Vic Black\", \"n\", \"Observed\",\n                       \"Expected\", \"Pearson Comp\", \"Deviance Comp\"))\n```\n\n::: {.cell-output-display}\n\n\n| Def Black| Vic Black|   n| Observed| Expected| Pearson Comp| Deviance Comp|\n|---------:|---------:|---:|--------:|--------:|------------:|-------------:|\n|         0|         0| 467|       53|   52.818|        0.001|         0.001|\n|         0|         1|  16|        0|    0.182|        0.184|         0.366|\n|         1|         0|  48|       11|   11.182|        0.004|         0.004|\n|         1|         1| 143|        4|    3.818|        0.009|         0.009|\n\n\n:::\n\n```{.r .cell-code}\n# Compute test statistics\nX2 <- sum(penalty_gof$pearson_comp)\nG2 <- sum(penalty_gof$dev_comp)\nJ <- nrow(penalty_gof)\np_params <- length(coef(penalty_model))\ndf_gof <- J - p_params\n\ntibble(\n  Statistic = c(\"Pearson X²\", \"Deviance G²\"),\n  Value     = round(c(X2, G2), 4),\n  df        = df_gof,\n  p_value   = round(1 - pchisq(c(X2, G2), df_gof), 4)\n) |>\n  kable(col.names = c(\"Statistic\", \"Value\", \"df\", \"p-value\"))\n```\n\n::: {.cell-output-display}\n\n\n|Statistic   |  Value| df| p-value|\n|:-----------|------:|--:|-------:|\n|Pearson X²  | 0.1978|  1|  0.6565|\n|Deviance G² | 0.3798|  1|  0.5377|\n\n\n:::\n:::\n\n- We group observations by covariate pattern and compute observed ($y_j$) and expected ($n_j \\hat{\\pi}_j$) counts\n- The Pearson and deviance components are summed across all $J = 4$ patterns\n- Degrees of freedom = $J - p = 4 - 3 = 1$ (4 patterns minus 3 parameters)\n- The `ifelse` guards handle the case where $y_j = 0$ to avoid $\\log(0)$\n\n\n:::\n\n::: {.callout-warning}\n## The Sparseness Problem\nThe $\\chi^2$ approximation for both $X^2$ and $G^2$ requires adequate cell sizes in the grouped table --- typically $n_j \\hat{\\pi}_j \\geq 5$ and $n_j(1 - \\hat{\\pi}_j) \\geq 5$ for all covariate patterns. When predictors are continuous (e.g., age, fare), the number of covariate patterns $J$ approaches $n$, most cells have $n_j = 1$, and the $\\chi^2$ approximation completely fails. In that situation:\n\n- The $X^2$ and $G^2$ statistics do **not** follow a $\\chi^2$ distribution\n- Their $p$-values are meaningless\n- The Hosmer-Lemeshow test (which groups observations into deciles of predicted risk) was designed as a workaround, though it has its own limitations\n\n**Rule of thumb**: Use $X^2$ and $G^2$ only when the number of covariate patterns $J$ is small relative to $n$ and all expected counts exceed 5. With continuous predictors, skip these tests entirely.\n:::\n\n\n## When the MLE Doesn't Exist: Separation {#sec-ch11-separation}\n\nLogistic regression estimates are obtained by maximum likelihood, but the MLE does not always exist. **Complete separation** occurs when some linear combination of the predictors perfectly splits the two outcome classes; **quasi-complete separation** is the milder case where the split is perfect for at least one covariate pattern (ties are allowed). In either case the likelihood has no finite maximum --- the corresponding coefficient is pushed toward $\\pm\\infty$ and the MLE diverges. The `penalty` data contain a built-in example: in the covariate pattern $\\texttt{def\\_bl}=0,\\ \\texttt{vic\\_bl}=1$ there are 16 cases and **zero** death sentences, so that combination perfectly predicts \"no death\" and creates quasi-complete separation.\n\n::: {.panel-tabset}\n### Output\n\n::: {.cell}\n\n```{.r .cell-code  code-fold=\"true\" code-summary=\"Show R Code\"}\n# Build an indicator for the perfectly-predicting covariate pattern\npenalty <- penalty |>\n  mutate(sep_ind = as.integer(def_bl == 0 & vic_bl == 1))\n\n# Ordinary glm: the MLE for sep_ind does not exist\nm_sep <- glm(death_pe ~ sep_ind + def_bl,\n             family = binomial, data = penalty)\nmodel_parameters(m_sep) |> print_md()\n```\n\n::: {.cell-output-display}\n\n\n|Parameter   | Log-Odds |     SE |         95% CI |      z |      p |\n|:-----------|:--------:|:------:|:--------------:|:------:|:------:|\n|(Intercept) |    -2.06 |   0.15 | (-2.35, -1.78) | -14.09 | < .001 |\n|sep ind     |   -14.51 | 599.89 |      (, 23.54) |  -0.02 | 0.981  |\n|def bl      |    -0.41 |   0.31 |  (-1.04, 0.17) |  -1.33 | 0.184  |\n\n\n:::\n\n```{.r .cell-code  code-fold=\"true\" code-summary=\"Show R Code\"}\n# Remedy: weakly-informative Bayesian prior (arm::bayesglm)\nm_firth <- arm::bayesglm(death_pe ~ sep_ind + def_bl,\n                         family = binomial, data = penalty)\nmodel_parameters(m_firth) |> print_md()\n```\n\n::: {.cell-output-display}\n\n\n|Parameter   | Log-Odds |   SE |         95% CI | Statistic |  df |      p |\n|:-----------|:--------:|:----:|:--------------:|:---------:|:---:|:------:|\n|(Intercept) |    -2.06 | 0.15 | (-2.35, -1.78) |    -14.17 | 671 | < .001 |\n|sep ind     |    -1.84 | 1.45 |  (-4.69, 1.00) |     -1.27 | 671 | 0.203  |\n|def bl      |    -0.39 | 0.30 |  (-0.98, 0.20) |     -1.29 | 671 | 0.196  |\n\n\n:::\n:::\n\n\n### Output Interpretation\n\n\n::: {.cell}\n::: {.cell-output-display}\n\n\n|Parameter   | Log-Odds |     SE |         95% CI |      z |      p |\n|:-----------|:--------:|:------:|:--------------:|:------:|:------:|\n|(Intercept) |    -2.06 |   0.15 | (-2.35, -1.78) | -14.09 | < .001 |\n|sep ind     |   -14.51 | 599.89 |      (, 23.54) |  -0.02 | 0.981  |\n|def bl      |    -0.41 |   0.31 |  (-1.04, 0.17) |  -1.33 | 0.184  |\n\n\n:::\n\n::: {.cell-output-display}\n\n\n|Parameter   | Log-Odds |   SE |         95% CI | Statistic |  df |      p |\n|:-----------|:--------:|:----:|:--------------:|:---------:|:---:|:------:|\n|(Intercept) |    -2.06 | 0.15 | (-2.35, -1.78) |    -14.17 | 671 | < .001 |\n|sep ind     |    -1.84 | 1.45 |  (-4.69, 1.00) |     -1.27 | 671 | 0.203  |\n|def bl      |    -0.39 | 0.30 |  (-0.98, 0.20) |     -1.29 | 671 | 0.196  |\n\n\n:::\n:::\n\nThe ordinary `glm()` fit shows the classic signature of separation. R emits the warning *\"fitted probabilities numerically 0 or 1 occurred\"* (suppressed in this chapter's rendering), and the `sep_ind` coefficient blows up to roughly $-14.5$ with a standard error of about $600$. The resulting Wald $z$ is essentially $0$ and the $p$-value is near $1$ ($\\approx 0.98$) --- a *meaningless* result, since the estimate is really $-\\infty$ in disguise and the odds ratio ($e^{-14.5}\\approx 0$) is wildly unstable. By contrast, `arm::bayesglm()` places a weakly-informative prior on the coefficients, which guarantees a finite estimate: `sep_ind` settles to a stable $\\approx -1.84$ with a usable SE of about $1.45$.\n\nThe practical remedies for separation are: (1) **penalized likelihood** --- Firth's bias-reduced estimator (the `logistf` package) is the standard choice and also yields finite estimates; (2) the **weakly-informative Bayesian prior** of `arm::bayesglm()` shown here; (3) **collapsing or combining** the sparse categories that cause the perfect split; and (4) **collecting more data** so the offending cell is no longer empty. Always inspect the data when a coefficient and its SE both explode --- separation, not a real effect, is usually the culprit.\n\n### Code Explanation\n\n::: {.cell}\n\n```{.r .cell-code}\n# Build an indicator for the perfectly-predicting covariate pattern\npenalty <- penalty |>\n  mutate(sep_ind = as.integer(def_bl == 0 & vic_bl == 1))\n\n# Ordinary glm: the MLE for sep_ind does not exist\nm_sep <- glm(death_pe ~ sep_ind + def_bl,\n             family = binomial, data = penalty)\nmodel_parameters(m_sep) |> print_md()\n```\n\n::: {.cell-output-display}\n\n\n|Parameter   | Log-Odds |     SE |         95% CI |      z |      p |\n|:-----------|:--------:|:------:|:--------------:|:------:|:------:|\n|(Intercept) |    -2.06 |   0.15 | (-2.35, -1.78) | -14.09 | < .001 |\n|sep ind     |   -14.51 | 599.89 |      (, 23.54) |  -0.02 | 0.981  |\n|def bl      |    -0.41 |   0.31 |  (-1.04, 0.17) |  -1.33 | 0.184  |\n\n\n:::\n\n```{.r .cell-code}\n# Remedy: weakly-informative Bayesian prior (arm::bayesglm)\nm_firth <- arm::bayesglm(death_pe ~ sep_ind + def_bl,\n                         family = binomial, data = penalty)\nmodel_parameters(m_firth) |> print_md()\n```\n\n::: {.cell-output-display}\n\n\n|Parameter   | Log-Odds |   SE |         95% CI | Statistic |  df |      p |\n|:-----------|:--------:|:----:|:--------------:|:---------:|:---:|:------:|\n|(Intercept) |    -2.06 | 0.15 | (-2.35, -1.78) |    -14.17 | 671 | < .001 |\n|sep ind     |    -1.84 | 1.45 |  (-4.69, 1.00) |     -1.27 | 671 | 0.203  |\n|def bl      |    -0.39 | 0.30 |  (-0.98, 0.20) |     -1.29 | 671 | 0.196  |\n\n\n:::\n:::\n\n- `sep_ind` flags the single covariate pattern (`def_bl = 0`, `vic_bl = 1`) in which no death sentences occur, manufacturing quasi-complete separation\n- The ordinary `glm()` cannot find a finite MLE for `sep_ind`; the optimizer halts at a huge negative value with an enormous SE\n- `arm::bayesglm()` is a drop-in replacement for `glm()` that adds a default Cauchy prior, regularizing the estimate so it stays finite\n- Firth's method (`logistf`) is an equally valid penalized alternative; it is mentioned here for completeness but not run, since the package is not installed in this environment\n\n\n:::\n\n\n## Pseudo R-squared Measures {#sec-ch11-pseudo-r2}\n\nIn linear regression, $R^2$ has a clear interpretation: the proportion of variance explained. Logistic regression has no exact analogue, but several **pseudo $R^2$** measures have been proposed. Each captures a different aspect of model performance, and none has the elegant properties of the linear $R^2$.\n\n### Why Multiple Definitions?\n\nThe linear $R^2$ simultaneously satisfies many desirable properties: it equals the squared correlation between $y$ and $\\hat{y}$, the proportion of variance explained, the proportional reduction in the residual sum of squares, and a function of the $F$-statistic. In logistic regression, no single measure satisfies all of these at once. Different pseudo $R^2$ measures emphasize different aspects.\n\n### Six Common Pseudo $R^2$ Measures\n\nLet $L_0$ be the likelihood of the **null model** (intercept only) and $L_1$ the likelihood of the **fitted model**. Equivalently, let $D_0 = -2\\ln L_0$ and $D_1 = -2\\ln L_1$ be the null and residual deviances.\n\n1. **McFadden's $R^2$** (likelihood ratio index):\n\n$$\nR^2_{\\text{McF}} = 1 - \\frac{\\ln L_1}{\\ln L_0} = \\frac{D_0 - D_1}{D_0}\n$$ {#eq-ch11-mcfadden}\n\nInterpretation: the proportional reduction in the deviance (analogous to the proportional reduction in RSS for linear regression). Values between 0.2 and 0.4 are considered excellent.\n\n2. **Cox-Snell $R^2$**:\n\n$$\nR^2_{\\text{CS}} = 1 - \\left(\\frac{L_0}{L_1}\\right)^{2/n}\n$$ {#eq-ch11-cox-snell}\n\nBased on the likelihood ratio, but its maximum is less than 1, which is a conceptual nuisance.\n\n3. **Nagelkerke $R^2$** (adjusted Cox-Snell):\n\n$$\nR^2_{\\text{N}} = \\frac{R^2_{\\text{CS}}}{1 - L_0^{2/n}}\n$$ {#eq-ch11-nagelkerke}\n\nRescales Cox-Snell so the theoretical maximum is 1. The most commonly reported pseudo $R^2$ in social science software.\n\n4. **Tjur's $R^2$** (coefficient of discrimination):\n\n$$\nR^2_{\\text{Tjur}} = \\bar{\\hat{\\pi}}_1 - \\bar{\\hat{\\pi}}_0\n$$ {#eq-ch11-tjur}\n\nSimply the difference in mean predicted probabilities between the $y = 1$ and $y = 0$ groups. Typically between 0 and 1 (larger = better separation); in principle it can be negative if a model assigns higher predicted probabilities to the $y = 0$ group than the $y = 1$ group. It has an intuitive interpretation: how well does the model separate the two groups?\n\n5. **Count $R^2$**: The proportion of correctly classified cases (see @sec-ch11-classification).\n\n6. **Adjusted Count $R^2$**: Improvement in classification over always predicting the modal category.\n\n::: {.callout-tip}\n## Which Pseudo $R^2$ Should I Report?\nReport **McFadden's $R^2$** and **Tjur's $R^2$** as a default pair. McFadden's is directly tied to the likelihood ratio test and has a clear \"proportional reduction in deviance\" interpretation. Tjur's is intuitive and does not depend on the likelihood. Always report the measure's name --- a bare \"$R^2 = 0.15$\" is ambiguous for logistic regression.\n:::\n\n### Computing Pseudo $R^2$ in R\n\n::: {.panel-tabset}\n### Output\n\n::: {.cell}\n\n```{.r .cell-code  code-fold=\"true\" code-summary=\"Show R Code\"}\n# Method 1: performance package (easystats)\nr2_values <- r2(penalty_model)\nr2_values\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# R2 for Logistic Regression\n  Tjur's R2: 0.029\n```\n\n\n:::\n\n```{.r .cell-code  code-fold=\"true\" code-summary=\"Show R Code\"}\n# Method 2: Manual computation of McFadden's R²\nnull_model <- glm(death_pe ~ 1, family = binomial, data = penalty)\nD0 <- deviance(null_model)  # null deviance = -2 log L0\nD1 <- deviance(penalty_model)  # residual deviance = -2 log L1\n\nmcfadden_manual <- (D0 - D1) / D0\n\ntibble(\n  Measure              = c(\"Null deviance (D0)\", \"Residual deviance (D1)\",\n                           \"Reduction in deviance\", \"McFadden R²\"),\n  Value                = round(c(D0, D1, D0 - D1, mcfadden_manual), 4)\n) |>\n  kable()\n```\n\n::: {.cell-output-display}\n\n\n|Measure                |    Value|\n|:----------------------|--------:|\n|Null deviance (D0)     | 440.8426|\n|Residual deviance (D1) | 418.9565|\n|Reduction in deviance  |  21.8861|\n|McFadden R²            |   0.0496|\n\n\n:::\n\n```{.r .cell-code  code-fold=\"true\" code-summary=\"Show R Code\"}\n# Method 3: Tjur's R²\npenalty <- penalty |>\n  mutate(pi_hat = fitted(penalty_model))\n\ntjur <- penalty |>\n  group_by(death_pe) |>\n  summarise(mean_pi = mean(pi_hat), .groups = \"drop\")\n\ntjur |>\n  bind_rows(tibble(death_pe = NA_real_,\n                   mean_pi = diff(tjur$mean_pi))) |>\n  mutate(Label = c(\"Mean P(death) | y=0\", \"Mean P(death) | y=1\", \"Tjur's R²\")) |>\n  select(Label, Value = mean_pi) |>\n  kable(digits = 4)\n```\n\n::: {.cell-output-display}\n\n\n|Label                    |  Value|\n|:------------------------|------:|\n|Mean P(death) &#124; y=0 | 0.0979|\n|Mean P(death) &#124; y=1 | 0.1274|\n|Tjur's R²                | 0.0295|\n\n\n:::\n:::\n\n\n### Output Interpretation\n\n\n::: {.cell}\n::: {.cell-output .cell-output-stdout}\n\n```\n# R2 for Logistic Regression\n  Tjur's R2: 0.029\n```\n\n\n:::\n\n::: {.cell-output-display}\n\n\n|Measure                |    Value|\n|:----------------------|--------:|\n|Null deviance (D0)     | 440.8426|\n|Residual deviance (D1) | 418.9565|\n|Reduction in deviance  |  21.8861|\n|McFadden R²            |   0.0496|\n\n\n:::\n\n::: {.cell-output-display}\n\n\n|Label                    |  Value|\n|:------------------------|------:|\n|Mean P(death) &#124; y=0 | 0.0979|\n|Mean P(death) &#124; y=1 | 0.1274|\n|Tjur's R²                | 0.0295|\n\n\n:::\n:::\n\nPseudo $R^2$ values for logistic regression are typically much lower than linear $R^2$ values. A McFadden $R^2$ of 0.05 does not mean the model is useless --- it means defendant and victim race explain a modest proportion of the variation in death penalty sentencing. The primary goal in this study is inference (testing for racial bias), not prediction.\n\n### Code Explanation\n\n::: {.cell}\n\n```{.r .cell-code}\n# Method 1: performance package (easystats)\nr2_values <- r2(penalty_model)\nr2_values\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# R2 for Logistic Regression\n  Tjur's R2: 0.029\n```\n\n\n:::\n\n```{.r .cell-code}\n# Method 2: Manual computation of McFadden's R²\nnull_model <- glm(death_pe ~ 1, family = binomial, data = penalty)\nD0 <- deviance(null_model)  # null deviance = -2 log L0\nD1 <- deviance(penalty_model)  # residual deviance = -2 log L1\n\nmcfadden_manual <- (D0 - D1) / D0\n\ntibble(\n  Measure              = c(\"Null deviance (D0)\", \"Residual deviance (D1)\",\n                           \"Reduction in deviance\", \"McFadden R²\"),\n  Value                = round(c(D0, D1, D0 - D1, mcfadden_manual), 4)\n) |>\n  kable()\n```\n\n::: {.cell-output-display}\n\n\n|Measure                |    Value|\n|:----------------------|--------:|\n|Null deviance (D0)     | 440.8426|\n|Residual deviance (D1) | 418.9565|\n|Reduction in deviance  |  21.8861|\n|McFadden R²            |   0.0496|\n\n\n:::\n\n```{.r .cell-code}\n# Method 3: Tjur's R²\npenalty <- penalty |>\n  mutate(pi_hat = fitted(penalty_model))\n\ntjur <- penalty |>\n  group_by(death_pe) |>\n  summarise(mean_pi = mean(pi_hat), .groups = \"drop\")\n\ntjur |>\n  bind_rows(tibble(death_pe = NA_real_,\n                   mean_pi = diff(tjur$mean_pi))) |>\n  mutate(Label = c(\"Mean P(death) | y=0\", \"Mean P(death) | y=1\", \"Tjur's R²\")) |>\n  select(Label, Value = mean_pi) |>\n  kable(digits = 4)\n```\n\n::: {.cell-output-display}\n\n\n|Label                    |  Value|\n|:------------------------|------:|\n|Mean P(death) &#124; y=0 | 0.0979|\n|Mean P(death) &#124; y=1 | 0.1274|\n|Tjur's R²                | 0.0295|\n\n\n:::\n:::\n\n- `r2()` from the `performance` package automatically computes Tjur's $R^2$ for logistic models\n- For McFadden's $R^2$, we compare the null and residual deviances\n- Tjur's $R^2$ requires only the mean predicted probability within each outcome group\n- The `deviance()` function extracts $-2\\ln L$ from a fitted `glm` object\n\n\n:::\n\n\n## Classification Accuracy {#sec-ch11-classification}\n\nA natural way to assess a logistic regression model is to see how well it **predicts** the outcome. The basic idea: if $\\hat{\\pi}_i \\ge 0.5$, predict $\\hat{y}_i = 1$; otherwise predict $\\hat{y}_i = 0$. Then cross-tabulate observed outcomes against predictions.\n\n### The Classification Table\n\nThe **classification table** (also called the confusion matrix) is a $2 \\times 2$ cross-tabulation:\n\n|  | Predicted $\\hat{y} = 1$ | Predicted $\\hat{y} = 0$ |\n|:---|:---:|:---:|\n| Observed $y = 1$ | True Positive (TP) | False Negative (FN) |\n| Observed $y = 0$ | False Positive (FP) | True Negative (TN) |\n\n: Classification table for binary outcomes. The rows are actual outcomes; columns are model predictions based on a cutoff, typically 0.5. {#tbl-ch11-classification}\n\nKey metrics derived from this table:\n\n- **Sensitivity** (true positive rate): $\\text{TP} / (\\text{TP} + \\text{FN})$ --- proportion of actual positives correctly identified\n- **Specificity** (true negative rate): $\\text{TN} / (\\text{TN} + \\text{FP})$ --- proportion of actual negatives correctly identified\n- **Overall accuracy**: $(\\text{TP} + \\text{TN}) / n$\n\n### Computing the Classification Table\n\n::: {.panel-tabset}\n### Output\n\n::: {.cell}\n\n```{.r .cell-code  code-fold=\"true\" code-summary=\"Show R Code\"}\n# Classify using the 0.5 cutoff\npenalty <- penalty |>\n  mutate(\n    y_pred = ifelse(pi_hat >= 0.5, 1, 0)\n  )\n\n# Classification table — ensure both levels appear\npenalty$y_pred <- factor(penalty$y_pred, levels = c(0, 1))\npenalty$death_pe_f <- factor(penalty$death_pe, levels = c(0, 1))\n\nconf_matrix <- table(\n  Observed  = penalty$death_pe_f,\n  Predicted = penalty$y_pred\n)\nconf_matrix |> addmargins()\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n        Predicted\nObserved   0   1 Sum\n     0   606   0 606\n     1    68   0  68\n     Sum 674   0 674\n```\n\n\n:::\n\n```{.r .cell-code  code-fold=\"true\" code-summary=\"Show R Code\"}\n# Accuracy metrics using factor-safe indexing\nTP <- conf_matrix[\"1\", \"1\"]\nTN <- conf_matrix[\"0\", \"0\"]\nFP <- conf_matrix[\"0\", \"1\"]\nFN <- conf_matrix[\"1\", \"0\"]\n\nif (sum(conf_matrix[\"1\", ]) == 0) {\n  message(\"Note: Model never predicts y = 1 (all predicted probabilities < 0.5)\")\n}\n\naccuracy <- (TP + TN) / sum(conf_matrix)\nbase_rate <- max(table(penalty$death_pe)) / nrow(penalty)\nsensitivity <- sum(penalty$death_pe == 1 & penalty$y_pred == 1) /\n               sum(penalty$death_pe == 1)\nspecificity <- sum(penalty$death_pe == 0 & penalty$y_pred == 0) /\n               sum(penalty$death_pe == 0)\n\ntibble(\n  Metric      = c(\"Overall accuracy\", \"Base rate (modal class)\",\n                   \"Sensitivity\", \"Specificity\"),\n  Value       = round(c(accuracy, base_rate, sensitivity, specificity), 4)\n) |>\n  kable()\n```\n\n::: {.cell-output-display}\n\n\n|Metric                  |  Value|\n|:-----------------------|------:|\n|Overall accuracy        | 0.8991|\n|Base rate (modal class) | 0.8991|\n|Sensitivity             | 0.0000|\n|Specificity             | 1.0000|\n\n\n:::\n:::\n\n\n### Output Interpretation\n\n\n::: {.cell}\n::: {.cell-output .cell-output-stdout}\n\n```\n        Predicted\nObserved   0   1 Sum\n     0   606   0 606\n     1    68   0  68\n     Sum 674   0 674\n```\n\n\n:::\n\n::: {.cell-output-display}\n\n\n|Metric                  |  Value|\n|:-----------------------|------:|\n|Overall accuracy        | 0.8991|\n|Base rate (modal class) | 0.8991|\n|Sensitivity             | 0.0000|\n|Specificity             | 1.0000|\n\n\n:::\n:::\n\nWhen the event is rare, the 0.5 cutoff produces a model that predicts \"no death penalty\" for everyone --- achieving high accuracy simply by mimicking the base rate. This illustrates a fundamental limitation: **overall accuracy is misleading when classes are imbalanced**. The model may capture real effects (significant odds ratios) while producing poor classification, because classification accuracy and inferential power address different questions.\n\n### Code Explanation\n\n::: {.cell}\n\n```{.r .cell-code}\n# Classify using the 0.5 cutoff\npenalty <- penalty |>\n  mutate(\n    y_pred = ifelse(pi_hat >= 0.5, 1, 0)\n  )\n\n# Classification table — ensure both levels appear\npenalty$y_pred <- factor(penalty$y_pred, levels = c(0, 1))\npenalty$death_pe_f <- factor(penalty$death_pe, levels = c(0, 1))\n\nconf_matrix <- table(\n  Observed  = penalty$death_pe_f,\n  Predicted = penalty$y_pred\n)\nconf_matrix |> addmargins()\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n        Predicted\nObserved   0   1 Sum\n     0   606   0 606\n     1    68   0  68\n     Sum 674   0 674\n```\n\n\n:::\n\n```{.r .cell-code}\n# Accuracy metrics using factor-safe indexing\nTP <- conf_matrix[\"1\", \"1\"]\nTN <- conf_matrix[\"0\", \"0\"]\nFP <- conf_matrix[\"0\", \"1\"]\nFN <- conf_matrix[\"1\", \"0\"]\n\nif (sum(conf_matrix[\"1\", ]) == 0) {\n  message(\"Note: Model never predicts y = 1 (all predicted probabilities < 0.5)\")\n}\n\naccuracy <- (TP + TN) / sum(conf_matrix)\nbase_rate <- max(table(penalty$death_pe)) / nrow(penalty)\nsensitivity <- sum(penalty$death_pe == 1 & penalty$y_pred == 1) /\n               sum(penalty$death_pe == 1)\nspecificity <- sum(penalty$death_pe == 0 & penalty$y_pred == 0) /\n               sum(penalty$death_pe == 0)\n\ntibble(\n  Metric      = c(\"Overall accuracy\", \"Base rate (modal class)\",\n                   \"Sensitivity\", \"Specificity\"),\n  Value       = round(c(accuracy, base_rate, sensitivity, specificity), 4)\n) |>\n  kable()\n```\n\n::: {.cell-output-display}\n\n\n|Metric                  |  Value|\n|:-----------------------|------:|\n|Overall accuracy        | 0.8991|\n|Base rate (modal class) | 0.8991|\n|Sensitivity             | 0.0000|\n|Specificity             | 1.0000|\n\n\n:::\n:::\n\n- `ifelse(pi_hat >= 0.5, 1, 0)` assigns predicted classes based on the 0.5 cutoff\n- When the overall event rate is very low (as in death penalty cases), the model may never predict $\\hat{y} = 1$ because all $\\hat{\\pi}_i < 0.5$\n- The base rate is the accuracy you would get by always predicting the most common category\n- Sensitivity and specificity decompose accuracy into performance on each class\n\n\n:::\n\n### Interactive Exploration: Classification Threshold Explorer {.unnumbered}\n\n::: {.callout-tip}\n## Try It: Adjust the Classification Threshold\n\nMove the **Classification Threshold (c)** slider away from its default 0.5 and watch how the confusion matrix (TP/FP/FN/TN), the sensitivity/specificity/precision/accuracy/F1 readouts, and the moving dot on the ROC curve all respond. Start by dragging it low (near 0.1) to flag almost everyone as positive, then high (near 0.9) to flag almost no one, and notice that sensitivity and specificity trade off against each other while the ROC curve and AUC stay fixed. Use **Reset** to return to $c = 0.50$.\n\nWe simulate the data here because tracing a clean sensitivity-specificity trade-off across every possible cutoff requires a known data-generating model with a controlled signal strength; a single real dataset would fix one operating point and obscure how the whole ROC curve arises from sweeping the threshold.\n:::\n\n```{ojs}\n//| echo: false\nimport { ber640 as thresh_ber640, plotDefaults as thresh_plotDefaults, themeColors as thresh_themeColors, onThemeChange as thresh_onThemeChange, sigmoid as thresh_sigmoid, srSummary as thresh_srSummary, resetControls as thresh_resetControls } from \"../ojs/shared.js\"\n```\n\n```{ojs}\n//| echo: false\nthresh_theme = thresh_themeColors()\n```\n\n```{ojs}\n//| echo: false\nthresh_pill = (label, value, tone = \"\") => html`<span class=\"ojs-readout ${tone ? \"ojs-readout-\" + tone : \"\"}\"><span class=\"ojs-readout-label\">${label}</span><span class=\"ojs-readout-value\">${value}</span></span>`\n```\n\n```{ojs}\n//| echo: false\nviewof thresh_threshold = Inputs.range([0.01, 0.99], {\n  value: 0.50,\n  step: 0.01,\n  label: \"Classification Threshold (c)\"\n})\n```\n\n```{ojs}\n//| echo: false\nthresh_reset = thresh_resetControls([\n  { input: viewof thresh_threshold, value: 0.50 }\n], { label: \"Reset\" })\n```\n\n```{ojs}\n//| echo: false\nthresh_mulberry32 = function(a) {\n  return function() {\n    a |= 0; a = a + 0x6D2B79F5 | 0;\n    var t = Math.imul(a ^ a >>> 15, 1 | a);\n    t = t + Math.imul(t ^ t >>> 7, 61 | t) ^ t;\n    return ((t ^ t >>> 14) >>> 0) / 4294967296;\n  }\n}\n\nthresh_n = 200\n\nthresh_data = {\n  const rng = thresh_mulberry32(12345);\n  const data = [];\n  for (let i = 0; i < thresh_n; i++) {\n    const u1a = rng(), u2a = rng();\n    const x1 = Math.sqrt(-2 * Math.log(u1a)) * Math.cos(2 * Math.PI * u2a);\n    const u1b = rng(), u2b = rng();\n    const x2 = Math.sqrt(-2 * Math.log(u1b)) * Math.cos(2 * Math.PI * u2b);\n    const logit = -1.5 + 1.2 * x1 + 0.8 * x2;\n    const p = thresh_sigmoid(logit);\n    const y = rng() < p ? 1 : 0;\n    data.push({ x1, x2, logit, p, y });\n  }\n  return data;\n}\n\nthresh_confusion = {\n  const c = thresh_threshold;\n  let tp = 0, tn = 0, fp = 0, fn = 0;\n  for (const d of thresh_data) {\n    const pred = d.p >= c ? 1 : 0;\n    if (d.y === 1 && pred === 1) tp++;\n    else if (d.y === 0 && pred === 0) tn++;\n    else if (d.y === 0 && pred === 1) fp++;\n    else fn++;\n  }\n  return { tp, tn, fp, fn };\n}\n\nthresh_metrics = {\n  const { tp, tn, fp, fn } = thresh_confusion;\n  const sensitivity = (tp + fn) > 0 ? tp / (tp + fn) : 0;\n  const specificity = (tn + fp) > 0 ? tn / (tn + fp) : 0;\n  const precision = (tp + fp) > 0 ? tp / (tp + fp) : 0;\n  const accuracy = (tp + tn) / thresh_n;\n  const f1 = (precision + sensitivity) > 0 ? 2 * precision * sensitivity / (precision + sensitivity) : 0;\n  return { sensitivity, specificity, precision, accuracy, f1 };\n}\n\nthresh_rocData = {\n  const thresholds = [];\n  for (let i = 0; i <= 100; i++) thresholds.push(i / 100);\n  const points = thresholds.map(c => {\n    let tp = 0, fn = 0, fp = 0, tn = 0;\n    for (const d of thresh_data) {\n      const pred = d.p >= c ? 1 : 0;\n      if (d.y === 1 && pred === 1) tp++;\n      else if (d.y === 1 && pred === 0) fn++;\n      else if (d.y === 0 && pred === 1) fp++;\n      else tn++;\n    }\n    const tpr = (tp + fn) > 0 ? tp / (tp + fn) : 0;\n    const fpr = (fp + tn) > 0 ? fp / (fp + tn) : 0;\n    return { threshold: c, tpr, fpr };\n  });\n  return points;\n}\n\nthresh_auc = {\n  const sorted = [...thresh_rocData].sort((a, b) => a.fpr - b.fpr);\n  let auc = 0;\n  for (let i = 1; i < sorted.length; i++) {\n    const dx = sorted[i].fpr - sorted[i - 1].fpr;\n    const avgY = (sorted[i].tpr + sorted[i - 1].tpr) / 2;\n    auc += dx * avgY;\n  }\n  return auc;\n}\n\nthresh_currentRocPoint = {\n  const { tp, tn, fp, fn } = thresh_confusion;\n  const tpr = (tp + fn) > 0 ? tp / (tp + fn) : 0;\n  const fpr = (fp + tn) > 0 ? fp / (fp + tn) : 0;\n  return { fpr, tpr };\n}\n\nthresh_rocLabel = {\n  const { fpr, tpr } = thresh_currentRocPoint;\n  const labelRight = fpr <= 0.72;\n  const labelAbove = tpr <= 0.14;\n  return {\n    x: Math.max(0.06, Math.min(0.94, fpr + (labelRight ? 0.07 : -0.07))),\n    y: Math.max(0.08, Math.min(0.92, tpr + (labelAbove ? 0.08 : -0.07))),\n    anchor: labelRight ? \"start\" : \"end\",\n    dy: labelAbove ? 0 : 3\n  };\n}\n```\n\n```{ojs}\n//| echo: false\nthresh_rocPlot = Plot.plot(thresh_plotDefaults({\n  width: 330,\n  height: 320,\n  marginTop: 24,\n  marginLeft: 50,\n  marginBottom: 45,\n  marginRight: 28,\n  style: { color: thresh_theme.text },\n  x: { label: \"False Positive Rate (FPR)\", domain: [0, 1] },\n  y: { label: \"True Positive Rate (TPR)\", domain: [0, 1] },\n  marks: [\n    Plot.line([[0, 0], [1, 1]], { stroke: thresh_theme.muted, strokeDasharray: \"6,4\", strokeWidth: 1.5 }),\n    Plot.line(thresh_rocData, {\n      x: \"fpr\",\n      y: \"tpr\",\n      stroke: thresh_ber640.accent,\n      strokeWidth: 2.5,\n      sort: { channel: \"x\" }\n    }),\n    Plot.dot([thresh_currentRocPoint], {\n      x: \"fpr\",\n      y: \"tpr\",\n      fill: thresh_ber640.secondary,\n      stroke: thresh_theme.bg,\n      strokeWidth: 2,\n      r: 7\n    }),\n    Plot.text([`AUC = ${thresh_auc.toFixed(3)}`], {\n      x: [0.97],\n      y: [0.05],\n      textAnchor: \"end\",\n      fill: thresh_theme.text,\n      fontSize: 13,\n      fontWeight: 600\n    }),\n    Plot.text([`c = ${thresh_threshold.toFixed(2)}`], {\n      x: [thresh_rocLabel.x],\n      y: [thresh_rocLabel.y],\n      textAnchor: thresh_rocLabel.anchor,\n      dy: thresh_rocLabel.dy,\n      fill: thresh_ber640.secondary,\n      fontSize: 12,\n      fontWeight: 600\n    })\n  ]\n}))\n```\n\n```{ojs}\n//| echo: false\nthresh_confusionMatrix = {\n  const { tp, tn, fp, fn } = thresh_confusion;\n  // CSS-var-driven tints so the table repaints on dark-mode toggle (no baked themeColors).\n  const cellStyle = (rgb, color) =>\n    `background:rgba(var(${rgb}), 0.15); color:var(${color}); font-size:1.35rem; font-weight:700; text-align:center; vertical-align:middle; padding:1.1rem 0.5rem; border-radius:6px; width:96px; height:72px;`;\n  const subStyle = `font-size:0.75rem; font-weight:400; color:var(--ojs-text-muted); display:block; margin-top:2px;`;\n  const labelStyle = `font-weight:600; font-size:0.92rem; color:var(--ojs-text); text-align:center; padding:0.4rem;`;\n\n  return html`<div style=\"display:flex; flex-direction:column; align-items:center;\">\n    <div style=\"font-weight:700; font-size:1rem; color:var(--ojs-text); margin-bottom:0.6rem;\">Confusion Matrix</div>\n    <table style=\"border-collapse:separate; border-spacing:6px;\">\n      <tr>\n        <td></td>\n        <td style=\"${labelStyle}\">Predicted 1</td>\n        <td style=\"${labelStyle}\">Predicted 0</td>\n      </tr>\n      <tr>\n        <td style=\"${labelStyle}\">Actual 1</td>\n        <td style=\"${cellStyle(\"--ber-success-rgb\", \"--ber-success\")}\">${tp}<span style=\"${subStyle}\">TP</span></td>\n        <td style=\"${cellStyle(\"--ber-warning-rgb\", \"--ber-warning\")}\">${fn}<span style=\"${subStyle}\">FN</span></td>\n      </tr>\n      <tr>\n        <td style=\"${labelStyle}\">Actual 0</td>\n        <td style=\"${cellStyle(\"--ber-secondary-rgb\", \"--ber-secondary\")}\">${fp}<span style=\"${subStyle}\">FP</span></td>\n        <td style=\"${cellStyle(\"--ber-success-rgb\", \"--ber-success\")}\">${tn}<span style=\"${subStyle}\">TN</span></td>\n      </tr>\n    </table>\n  </div>`;\n}\n```\n\n```{ojs}\n//| echo: false\nthresh_readouts = html`<div class=\"ojs-readouts\">\n  ${thresh_pill(\"Threshold c\", thresh_threshold.toFixed(2), \"info\")}\n  ${thresh_pill(\"Sensitivity (TPR)\", thresh_metrics.sensitivity.toFixed(3), \"good\")}\n  ${thresh_pill(\"Specificity (TNR)\", thresh_metrics.specificity.toFixed(3), \"info\")}\n  ${thresh_pill(\"Precision (PPV)\", thresh_metrics.precision.toFixed(3), \"\")}\n  ${thresh_pill(\"Accuracy\", thresh_metrics.accuracy.toFixed(3), \"good\")}\n  ${thresh_pill(\"F1 Score\", thresh_metrics.f1.toFixed(3), \"warning\")}\n  ${thresh_pill(\"AUC\", thresh_auc.toFixed(3), \"info\")}\n</div>`\n```\n\n```{ojs}\n//| echo: false\nthresh_sr = thresh_srSummary(\"ch11-thresh\",\n  `At classification threshold c = ${thresh_threshold.toFixed(2)}: confusion matrix has ${thresh_confusion.tp} true positives, ${thresh_confusion.fn} false negatives, ${thresh_confusion.fp} false positives, ${thresh_confusion.tn} true negatives. Sensitivity ${thresh_metrics.sensitivity.toFixed(3)}, specificity ${thresh_metrics.specificity.toFixed(3)}, precision ${thresh_metrics.precision.toFixed(3)}, accuracy ${thresh_metrics.accuracy.toFixed(3)}, F1 ${thresh_metrics.f1.toFixed(3)}. The ROC curve has area under the curve (AUC) ${thresh_auc.toFixed(3)}; the operating point sits at false positive rate ${thresh_currentRocPoint.fpr.toFixed(3)} and true positive rate ${thresh_currentRocPoint.tpr.toFixed(3)}.`)\n```\n\n```{ojs}\n//| echo: false\nthresh_app = html`<div class=\"ojs-app\" role=\"group\" aria-label=\"Classification threshold explorer: ROC curve and confusion matrix\">\n  <div class=\"ojs-controls\">${viewof thresh_threshold}<div class=\"ojs-control-group\" style=\"flex:0 0 auto; min-width:5.5rem;\">${thresh_reset}</div></div>\n  ${thresh_readouts}\n  <div style=\"display:flex; flex-wrap:wrap; gap:1rem; align-items:center; justify-content:center;\">\n    <div class=\"ojs-plot\" style=\"flex:0 1 auto;\">${thresh_rocPlot}</div>\n    <div style=\"flex:0 1 auto;\">${thresh_confusionMatrix}</div>\n  </div>\n  ${thresh_sr}\n</div>`\n```\n\n::: {.callout-note}\n## What you should have seen\n\n- **No single cutoff is \"correct.\"** Lowering the threshold raises sensitivity (catches more true positives) but lowers specificity (more false positives); raising it does the reverse. The right cutoff depends on the relative cost of the two error types, not on a default of 0.5.\n- **The ROC curve and AUC do not move when you slide the threshold.** Only the operating-point dot travels along the curve. The curve summarizes the model's *ranking* ability across all cutoffs at once, and AUC condenses that whole curve into one threshold-free number.\n- **Accuracy alone can mislead.** A threshold can post high accuracy while sensitivity collapses, especially with imbalanced classes — which is exactly why sensitivity, specificity, and AUC are reported alongside accuracy here.\n:::\n\n### ROC Curves and AUC {#sec-ch11-roc}\n\nThe **ROC (Receiver Operating Characteristic) curve** plots sensitivity (the true-positive rate) against $1 - \\text{specificity}$ (the false-positive rate) as the classification threshold sweeps from $0$ to $1$. This is exactly the trajectory the slider traces out in the Threshold Explorer above: each threshold $c$ yields one (FPR, TPR) point, and stringing them together gives the curve. A model with no discriminative power produces the $45^\\circ$ diagonal; a better model bows toward the upper-left corner.\n\nThe **AUC (Area Under the Curve)** summarizes the whole ROC curve in a single number. It has a clean probabilistic interpretation: the AUC equals the probability that a randomly chosen event case is assigned a *higher* predicted probability than a randomly chosen non-event case. An AUC of $0.5$ means no discrimination (coin-flip ranking), while $1.0$ means perfect ranking. A common rough guide treats $0.7$--$0.8$ as acceptable and $0.8$--$0.9$ as excellent. The Threshold Explorer above (@sec-ch11-classification) reports the AUC for its simulated model directly on the ROC panel.\n\nTwo cautions are essential. First, AUC measures **discrimination** (how well the model *ranks* cases), not **calibration** (whether the predicted probabilities are numerically correct) --- a model can have high AUC yet badly miscalibrated probabilities. Second, AUC does **not** choose a decision threshold for you; the cutoff should reflect the relative costs of false positives versus false negatives in the application, not a default of $0.5$. Finally, recall the \"predict no death penalty for everyone\" example from @sec-ch11-classification: with imbalanced classes, raw accuracy can look high while the model discriminates poorly. AUC and the confusion-matrix metrics (sensitivity, specificity) are far more informative in that setting.\n\n### Cohen's Kappa {#sec-ch11-kappa}\n\n**Cohen's kappa** ($\\kappa$) measures classification accuracy **adjusted for chance agreement**:\n\n$$\n\\kappa = \\frac{P_o - P_e}{1 - P_e}\n$$ {#eq-ch11-kappa}\n\nwhere $P_o$ is the observed agreement (overall accuracy) and $P_e$ is the expected agreement under independence. A $\\kappa$ of 0 means classification is no better than chance; $\\kappa = 1$ means perfect classification.\n\n::: {.panel-tabset}\n### Output\n\n::: {.cell}\n\n```{.r .cell-code  code-fold=\"true\" code-summary=\"Show R Code\"}\n# Compute Cohen's kappa manually\nn_total <- nrow(penalty)\nP_o <- accuracy\n\n# Expected agreement under independence\nrow_marginals <- rowSums(conf_matrix) / n_total\ncol_marginals <- colSums(conf_matrix) / n_total\nP_e <- sum(row_marginals * col_marginals)\n\nkappa <- (P_o - P_e) / (1 - P_e)\ntibble(\n  Measure = c(\"Observed agreement (P_o)\", \"Expected agreement (P_e)\",\n              \"Cohen's kappa\"),\n  Value   = round(c(P_o, P_e, kappa), 4)\n) |>\n  kable()\n```\n\n::: {.cell-output-display}\n\n\n|Measure                  |  Value|\n|:------------------------|------:|\n|Observed agreement (P_o) | 0.8991|\n|Expected agreement (P_e) | 0.8991|\n|Cohen's kappa            | 0.0000|\n\n\n:::\n:::\n\n\n### Output Interpretation\n\n\n::: {.cell}\n::: {.cell-output-display}\n\n\n|Measure                  |  Value|\n|:------------------------|------:|\n|Observed agreement (P_o) | 0.8991|\n|Expected agreement (P_e) | 0.8991|\n|Cohen's kappa            | 0.0000|\n\n\n:::\n:::\n\nA kappa near 0 confirms that the classification (at the 0.5 threshold) is no better than chance. This does **not** mean the model is useless --- it means the model's strength lies in estimating the effect of race on sentencing, not in predicting individual case outcomes. Models can be inferentially valuable even when their predictive classification is poor.\n\n### Code Explanation\n\n::: {.cell}\n\n```{.r .cell-code}\n# Compute Cohen's kappa manually\nn_total <- nrow(penalty)\nP_o <- accuracy\n\n# Expected agreement under independence\nrow_marginals <- rowSums(conf_matrix) / n_total\ncol_marginals <- colSums(conf_matrix) / n_total\nP_e <- sum(row_marginals * col_marginals)\n\nkappa <- (P_o - P_e) / (1 - P_e)\ntibble(\n  Measure = c(\"Observed agreement (P_o)\", \"Expected agreement (P_e)\",\n              \"Cohen's kappa\"),\n  Value   = round(c(P_o, P_e, kappa), 4)\n) |>\n  kable()\n```\n\n::: {.cell-output-display}\n\n\n|Measure                  |  Value|\n|:------------------------|------:|\n|Observed agreement (P_o) | 0.8991|\n|Expected agreement (P_e) | 0.8991|\n|Cohen's kappa            | 0.0000|\n\n\n:::\n:::\n\n- $P_o$ is simply the overall accuracy (proportion of correct predictions)\n- $P_e$ is computed from the marginal distributions: the probability that the model and reality agree by chance\n- When the model always predicts the same class, $\\kappa = 0$ because the model adds no information beyond the marginal distribution\n\n\n:::\n\n::: {.callout-tip}\n## Classification vs. Inference\nThe classification table is most useful when the research goal is prediction (e.g., identifying high-risk patients). When the goal is inference (e.g., testing whether racial bias exists in sentencing), odds ratios and likelihood ratio tests are more relevant than classification accuracy. Do not dismiss a model solely because its classification accuracy is low.\n:::\n\n\n## Residual Analysis {#sec-ch11-residuals}\n\nIn linear regression, raw residuals $e_i = y_i - \\hat{y}_i$ are the starting point for diagnostics. In logistic regression, raw residuals ($y_i - \\hat{\\pi}_i$) are problematic because $y_i$ is 0 or 1 while $\\hat{\\pi}_i$ is continuous --- the residual is heteroscedastic by construction. Two standardized alternatives are commonly used.\n\n### Pearson Residuals {#sec-ch11-pearson-resid}\n\nThe **Pearson residual** standardizes the raw residual by its expected standard deviation under the binomial model:\n\n$$\nr_i^{(P)} = \\frac{y_i - \\hat{\\pi}_i}{\\sqrt{\\hat{\\pi}_i(1 - \\hat{\\pi}_i)}}\n$$ {#eq-ch11-pearson-resid}\n\nThe denominator is the standard deviation of a Bernoulli variable with success probability $\\hat{\\pi}_i$. For grouped data with $n_j$ observations at covariate pattern $j$:\n\n$$\nr_j^{(P)} = \\frac{y_j - n_j\\hat{\\pi}_j}{\\sqrt{n_j\\hat{\\pi}_j(1 - \\hat{\\pi}_j)}}\n$$\n\nThe sum of squared Pearson residuals equals the Pearson $X^2$ statistic from @eq-ch11-pearson-x2.\n\n### Deviance Residuals\n\nThe **deviance residual** is derived from the contribution of each observation to the overall deviance $G^2$:\n\n$$\nr_i^{(D)} = \\text{sign}(y_i - \\hat{\\pi}_i) \\sqrt{2 \\left[ y_i \\ln\\!\\left(\\frac{y_i}{\\hat{\\pi}_i}\\right) + (1 - y_i)\\ln\\!\\left(\\frac{1 - y_i}{1 - \\hat{\\pi}_i}\\right) \\right]}\n$$ {#eq-ch11-deviance-resid}\n\nAs usual, terms of the form $0\\ln(0/a)$ are defined by continuity to equal 0. The sum of squared deviance residuals equals the residual deviance. Deviance residuals tend to be more symmetrically distributed than Pearson residuals, making them slightly better for diagnostic plots.\n\n### Computing Residuals\n\n::: {.panel-tabset}\n### Output\n\n::: {.cell}\n\n```{.r .cell-code  code-fold=\"true\" code-summary=\"Show R Code\"}\n# Extract residuals from the glm object\npenalty <- penalty |>\n  mutate(\n    resid_pearson  = residuals(penalty_model, type = \"pearson\"),\n    resid_deviance = residuals(penalty_model, type = \"deviance\"),\n    resid_response = residuals(penalty_model, type = \"response\"),  # y - pi_hat\n    linear_pred    = predict(penalty_model, type = \"link\")  # log-odds\n  )\n\n# Summary statistics\npenalty |>\n  select(resid_pearson, resid_deviance, resid_response) |>\n  pivot_longer(everything(), names_to = \"type\", values_to = \"value\") |>\n  group_by(type) |>\n  summarise(\n    Mean = round(mean(value), 4),\n    SD   = round(sd(value), 4),\n    Min  = round(min(value), 2),\n    Max  = round(max(value), 2),\n    .groups = \"drop\"\n  ) |>\n  kable()\n```\n\n::: {.cell-output-display}\n\n\n|type           |    Mean|     SD|   Min|  Max|\n|:--------------|-------:|------:|-----:|----:|\n|resid_deviance | -0.1845| 0.7671| -0.73| 2.69|\n|resid_pearson  | -0.0007| 0.9945| -0.55| 6.04|\n|resid_response |  0.0000| 0.2970| -0.23| 0.97|\n\n\n:::\n:::\n\n\n### Output Interpretation\n\n\n::: {.cell}\n::: {.cell-output-display}\n\n\n|type           |    Mean|     SD|   Min|  Max|\n|:--------------|-------:|------:|-----:|----:|\n|resid_deviance | -0.1845| 0.7671| -0.73| 2.69|\n|resid_pearson  | -0.0007| 0.9945| -0.55| 6.04|\n|resid_response |  0.0000| 0.2970| -0.23| 0.97|\n\n\n:::\n:::\n\nWith binary data, both Pearson and deviance residuals form discrete clusters rather than the smooth cloud you see in linear regression diagnostics. Each covariate pattern produces two residual values (one for $y = 1$ cases and one for $y = 0$ cases), so plots look very different from the continuous case.\n\n### Code Explanation\n\n::: {.cell}\n\n```{.r .cell-code}\n# Extract residuals from the glm object\npenalty <- penalty |>\n  mutate(\n    resid_pearson  = residuals(penalty_model, type = \"pearson\"),\n    resid_deviance = residuals(penalty_model, type = \"deviance\"),\n    resid_response = residuals(penalty_model, type = \"response\"),  # y - pi_hat\n    linear_pred    = predict(penalty_model, type = \"link\")  # log-odds\n  )\n\n# Summary statistics\npenalty |>\n  select(resid_pearson, resid_deviance, resid_response) |>\n  pivot_longer(everything(), names_to = \"type\", values_to = \"value\") |>\n  group_by(type) |>\n  summarise(\n    Mean = round(mean(value), 4),\n    SD   = round(sd(value), 4),\n    Min  = round(min(value), 2),\n    Max  = round(max(value), 2),\n    .groups = \"drop\"\n  ) |>\n  kable()\n```\n\n::: {.cell-output-display}\n\n\n|type           |    Mean|     SD|   Min|  Max|\n|:--------------|-------:|------:|-----:|----:|\n|resid_deviance | -0.1845| 0.7671| -0.73| 2.69|\n|resid_pearson  | -0.0007| 0.9945| -0.55| 6.04|\n|resid_response |  0.0000| 0.2970| -0.23| 0.97|\n\n\n:::\n:::\n\n- `residuals(model, type = \"pearson\")` computes @eq-ch11-pearson-resid\n- `residuals(model, type = \"deviance\")` computes @eq-ch11-deviance-resid (the default for `glm`)\n- `type = \"response\"` gives the raw residual $y_i - \\hat{\\pi}_i$\n- `predict(model, type = \"link\")` gives the linear predictor (log-odds), which is the appropriate x-axis for residual plots\n\n\n:::\n\n### Residual Plots\n\n::: {.panel-tabset}\n### Output\n\n::: {.cell}\n\n```{.r .cell-code  code-fold=\"true\" code-summary=\"Show R Code\"}\nggplot(penalty, aes(x = linear_pred, y = resid_pearson)) +\n  geom_jitter(width = 0.02, height = 0, alpha = 0.3,\n              color = ber640_colors[[\"primary\"]]) +\n  geom_hline(yintercept = 0, linetype = \"dashed\", color = \"grey50\") +\n  geom_hline(yintercept = c(-2, 2), linetype = \"dotted\",\n             color = ber640_colors[[\"secondary\"]]) +\n  labs(\n    title = \"Pearson Residuals vs. Linear Predictor\",\n    x = \"Linear Predictor (log-odds)\",\n    y = \"Pearson Residual\"\n  )\n```\n\n::: {.cell-output-display}\n![Pearson residuals vs. linear predictor (log-odds) for the death penalty model. With only categorical predictors, residuals cluster at four horizontal (log-odds) positions corresponding to the four covariate patterns, and each pattern can split into two residual levels (a high value for the $y = 1$ cases and a low value for the $y = 0$ cases); at the lowest-probability cell the $y = 1$ point may be sparse or off-range, so only one band is visible there.](11-logistic-diagnostics_files/figure-html/fig-ch11-residual-plot-1.png){#fig-ch11-residual-plot fig-alt='Scatter plot of Pearson residuals on the y-axis versus the linear predictor (log-odds) on the x-axis for the death penalty logistic regression model. Because the model contains only categorical predictors, the points cluster at four distinct horizontal positions along the log-odds axis corresponding to the four unique covariate patterns, with each pattern able to split into two residual levels (a higher residual for y equals 1 cases and a lower residual for y equals 0 cases); at the lowest-probability cell the y equals 1 point is sparse or off-range, so only one band shows there. A horizontal dashed line at zero marks the expected residual value, and dotted reference lines at plus and minus 2 indicate approximate significance boundaries. Several covariate patterns produce residuals above the plus-2 line, including values near 6 and near 2.8, because a few y-equals-1 cases fall in low-probability cells; this is expected behaviour for sparse categorical data rather than a sign of a poorly specified model.' width=2400}\n:::\n:::\n\n\n### Output Interpretation\n\n\n::: {.cell}\n::: {.cell-output-display}\n![](11-logistic-diagnostics_files/figure-html/unnamed-chunk-28-1.png){width=2400}\n:::\n:::\n\nThe banded structure is normal for categorical predictors. Here several points sit well above the $+2$ band (one near 6, another near 2.8): these are $y = 1$ cases that land in low-probability cells, where a single success produces a large positive Pearson residual. With sparse cells this is expected and does not by itself indicate misfit. In models with continuous predictors, look for systematic curvature (suggesting a missing nonlinear term) or increasing spread (suggesting overdispersion).\n\n### Code Explanation\n\n::: {.cell}\n\n```{.r .cell-code}\nggplot(penalty, aes(x = linear_pred, y = resid_pearson)) +\n  geom_jitter(width = 0.02, height = 0, alpha = 0.3,\n              color = ber640_colors[[\"primary\"]]) +\n  geom_hline(yintercept = 0, linetype = \"dashed\", color = \"grey50\") +\n  geom_hline(yintercept = c(-2, 2), linetype = \"dotted\",\n             color = ber640_colors[[\"secondary\"]]) +\n  labs(\n    title = \"Pearson Residuals vs. Linear Predictor\",\n    x = \"Linear Predictor (log-odds)\",\n    y = \"Pearson Residual\"\n  )\n```\n\n::: {.cell-output-display}\n![](11-logistic-diagnostics_files/figure-html/unnamed-chunk-29-1.png){width=2400}\n:::\n:::\n\n- The x-axis uses the linear predictor (log-odds scale), not fitted probabilities, to spread observations more evenly\n- Horizontal reference lines at $\\pm 2$ highlight potentially problematic observations\n- `geom_jitter()` adds horizontal noise to reveal overlapping points\n- With purely categorical predictors, the clusters along the log-odds axis correspond to covariate patterns, and each pattern can split into two residual levels ($y = 1$ vs. $y = 0$); at the lowest-probability cell the $y = 1$ point may be too sparse to appear\n\n\n:::\n\n\n### Binned Residual Plot {#sec-ch11-binned-resid}\n\nStandard residual plots are hard to read for binary outcomes because residuals cluster in two bands. A **binned residual plot** solves this by averaging residuals within bins of the fitted values (or a predictor). If the model is well-calibrated, the binned averages should fall within the $\\pm 2\\text{SE}$ bounds.\n\n::: {.panel-tabset}\n### Output\n\n::: {.cell}\n\n```{.r .cell-code  code-fold=\"true\" code-summary=\"Show R Code\"}\n# Fit the Titanic model (needed for this section)\ndata(titanic)\ntitanic_model <- glm(survived ~ sex + age + pclass,\n                     family = binomial, data = titanic)\n\ntitanic_binned <- titanic |>\n  filter(!is.na(age)) |>\n  mutate(\n    pi_hat     = fitted(titanic_model),\n    resid_raw  = survived - pi_hat,\n    linear_pred = predict(titanic_model, type = \"link\")\n  )\n\n# Create bins of the linear predictor\nn_bins <- 40\ntitanic_binned <- titanic_binned |>\n  mutate(bin = ntile(linear_pred, n_bins)) |>\n  group_by(bin) |>\n  summarise(\n    mean_pred  = mean(linear_pred),\n    mean_resid = mean(resid_raw),\n    n_bin      = n(),\n    se_resid   = sqrt(mean(pi_hat) * (1 - mean(pi_hat)) / n()),\n    .groups    = \"drop\"\n  )\n\nggplot(titanic_binned, aes(x = mean_pred, y = mean_resid)) +\n  geom_ribbon(aes(ymin = -2 * se_resid, ymax = 2 * se_resid),\n              fill = \"grey85\", alpha = 0.5) +\n  geom_point(color = ber640_colors[[\"primary\"]], size = 2) +\n  geom_hline(yintercept = 0, linetype = \"dashed\", color = \"grey50\") +\n  labs(\n    title = \"Binned Residual Plot (Titanic Model)\",\n    x = \"Mean Linear Predictor within Bin\",\n    y = \"Mean Residual within Bin\"\n  )\n```\n\n::: {.cell-output-display}\n![Binned residual plot for the Titanic logistic regression model. Residuals are averaged within bins of the fitted linear predictor. Points outside the grey $\\pm 2\\text{SE}$ bands suggest local misfit.](11-logistic-diagnostics_files/figure-html/fig-ch11-binned-resid-1.png){#fig-ch11-binned-resid fig-alt='Binned residual plot for the Titanic logistic regression model with the average residual on the y-axis and the bin midpoint of the fitted linear predictor on the x-axis. Each point represents the mean residual within a bin of observations. Grey shaded bands at plus and minus two standard errors provide reference boundaries. Points falling inside the bands indicate acceptable fit for that region of the predictor space, while any points outside the bands suggest localized areas where the model does not fit the data well.' width=2400}\n:::\n:::\n\n\n### Output Interpretation\n\n\n::: {.cell}\n::: {.cell-output-display}\n![](11-logistic-diagnostics_files/figure-html/unnamed-chunk-30-1.png){width=2400}\n:::\n:::\n\nIf most binned residual points (roughly 95%) fall within the grey $\\pm 2\\text{SE}$ bands, the model fits adequately. Here, however, a sizeable number of bins fall *outside* the envelope --- consistent with the Hosmer--Lemeshow rejection ($p < 0.001$) reported later --- so this plot flags genuine miscalibration of the Titanic model rather than a clean pass. Systematic patterns (e.g., a U-shape) suggest a missing nonlinear term. Bins at the extremes of the linear predictor are worth inspecting closely, since the model is extrapolating in those regions. This plot is the logistic regression analogue of the residual-vs-fitted plot from @sec-ch8, but aggregated to overcome the discrete nature of binary residuals.\n\n### Code Explanation\n\n::: {.cell}\n\n```{.r .cell-code}\n# Fit the Titanic model (needed for this section)\ndata(titanic)\ntitanic_model <- glm(survived ~ sex + age + pclass,\n                     family = binomial, data = titanic)\n\ntitanic_binned <- titanic |>\n  filter(!is.na(age)) |>\n  mutate(\n    pi_hat     = fitted(titanic_model),\n    resid_raw  = survived - pi_hat,\n    linear_pred = predict(titanic_model, type = \"link\")\n  )\n\n# Create bins of the linear predictor\nn_bins <- 40\ntitanic_binned <- titanic_binned |>\n  mutate(bin = ntile(linear_pred, n_bins)) |>\n  group_by(bin) |>\n  summarise(\n    mean_pred  = mean(linear_pred),\n    mean_resid = mean(resid_raw),\n    n_bin      = n(),\n    se_resid   = sqrt(mean(pi_hat) * (1 - mean(pi_hat)) / n()),\n    .groups    = \"drop\"\n  )\n\nggplot(titanic_binned, aes(x = mean_pred, y = mean_resid)) +\n  geom_ribbon(aes(ymin = -2 * se_resid, ymax = 2 * se_resid),\n              fill = \"grey85\", alpha = 0.5) +\n  geom_point(color = ber640_colors[[\"primary\"]], size = 2) +\n  geom_hline(yintercept = 0, linetype = \"dashed\", color = \"grey50\") +\n  labs(\n    title = \"Binned Residual Plot (Titanic Model)\",\n    x = \"Mean Linear Predictor within Bin\",\n    y = \"Mean Residual within Bin\"\n  )\n```\n\n::: {.cell-output-display}\n![](11-logistic-diagnostics_files/figure-html/unnamed-chunk-31-1.png){width=2400}\n:::\n:::\n\n- Here `pclass` enters as a numeric trend for a compact diagnostic illustration, in contrast to @sec-ch10 where passenger class was treated as a factor; this choice changes the meaning of the class coefficient (a single per-level trend here vs. category contrasts there)\n- Observations are sorted by the linear predictor and grouped into `n_bins = 40` bins using `ntile()`\n- Within each bin, the average raw residual ($\\bar{e}_{\\text{bin}} = \\overline{y - \\hat{\\pi}}$) is computed\n- The $\\pm 2\\text{SE}$ envelope uses the binomial standard error: $\\sqrt{\\bar{\\pi}(1-\\bar{\\pi})/n_{\\text{bin}}}$; because `ntile()` makes the bins nearly equal in size, the band's lens shape (wide in the middle, pinched at the ends) tracks $\\bar{\\pi}(1-\\bar{\\pi})$ and so reflects sampling precision per bin, not how forgiving the fit criterion is in that region\n- Points outside the grey band indicate regions where the model systematically over- or under-predicts\n\n\n:::\n\n\n### Influence Diagnostics: DFBETAS and Cook's Distance {#sec-ch11-influence}\n\nJust as in linear regression (see @sec-ch8), individual observations can exert disproportionate influence on logistic regression parameter estimates. The key diagnostic measures carry over with minor modifications.\n\n**Cook's distance** for logistic regression measures how much all parameter estimates change when observation $i$ is deleted:\n\n$$\nD_i = \\frac{r_i^{(P)2} \\cdot h_{ii}}{p \\cdot (1 - h_{ii})^2}\n$$\n\nwhere $h_{ii}$ is the diagonal of the hat matrix and $p$ is the number of parameters.\n\n**DFBETAS** measures the influence of observation $i$ on each individual coefficient $\\hat{\\beta}_k$.\n\n::: {.panel-tabset}\n### Output\n\n::: {.cell}\n\n```{.r .cell-code  code-fold=\"true\" code-summary=\"Show R Code\"}\n# Extract influence diagnostics\npenalty <- penalty |>\n  mutate(\n    cooks_d  = cooks.distance(penalty_model),\n    leverage = hatvalues(penalty_model),\n    obs_id   = row_number()\n  )\n\n# Cook's distance plot\nggplot(penalty, aes(x = obs_id, y = cooks_d)) +\n  geom_point(alpha = 0.4, color = ber640_colors[[\"primary\"]]) +\n  geom_hline(yintercept = 4 / nrow(penalty),\n             linetype = \"dashed\", color = ber640_colors[[\"secondary\"]]) +\n  labs(\n    title = \"Cook's Distance for Death Penalty Model\",\n    x = \"Observation Index\",\n    y = \"Cook's Distance\"\n  ) +\n  annotate(\"text\", x = nrow(penalty) * 0.8,\n           y = 4 / nrow(penalty) * 1.3,\n           label = paste0(\"Threshold = \", round(4 / nrow(penalty), 4)),\n           color = ber640_colors[[\"secondary\"]], size = 4)\n```\n\n::: {.cell-output-display}\n![Cook's distance for the death penalty model. With grouped categorical data, influence is largely shared across observations within each covariate pattern, though a few cells in small groups with unusual outcomes still stand out (here two near $D \\approx 0.08$, far above the rest).](11-logistic-diagnostics_files/figure-html/fig-ch11-influence-1.png){#fig-ch11-influence fig-alt='Index plot of Cook\\'s distance on the y-axis versus observation number on the x-axis for the death penalty logistic regression model. Because the data consist of grouped categorical predictors, Cook\\'s distance values cluster at a few distinct levels corresponding to the covariate patterns rather than showing a unique value for each observation. Most values are small, indicating that influence is largely shared across observations within each group, but two points sit far above the rest near a Cook\\'s distance of 0.08 — individual cells in small groups with unusual outcomes.' width=2400}\n:::\n:::\n\n\n### Output Interpretation\n\n\n::: {.cell}\n::: {.cell-output-display}\n![](11-logistic-diagnostics_files/figure-html/unnamed-chunk-32-1.png){width=2400}\n:::\n:::\n\nObservations that exceed the $4/n$ threshold deserve closer inspection. With purely categorical predictors, extreme Cook's distance values arise from observations in small cells with unusual outcomes. Check whether removing these observations meaningfully changes the odds ratios.\n\n### Code Explanation\n\n::: {.cell}\n\n```{.r .cell-code}\n# Extract influence diagnostics\npenalty <- penalty |>\n  mutate(\n    cooks_d  = cooks.distance(penalty_model),\n    leverage = hatvalues(penalty_model),\n    obs_id   = row_number()\n  )\n\n# Cook's distance plot\nggplot(penalty, aes(x = obs_id, y = cooks_d)) +\n  geom_point(alpha = 0.4, color = ber640_colors[[\"primary\"]]) +\n  geom_hline(yintercept = 4 / nrow(penalty),\n             linetype = \"dashed\", color = ber640_colors[[\"secondary\"]]) +\n  labs(\n    title = \"Cook's Distance for Death Penalty Model\",\n    x = \"Observation Index\",\n    y = \"Cook's Distance\"\n  ) +\n  annotate(\"text\", x = nrow(penalty) * 0.8,\n           y = 4 / nrow(penalty) * 1.3,\n           label = paste0(\"Threshold = \", round(4 / nrow(penalty), 4)),\n           color = ber640_colors[[\"secondary\"]], size = 4)\n```\n\n::: {.cell-output-display}\n![](11-logistic-diagnostics_files/figure-html/unnamed-chunk-33-1.png){width=2400}\n:::\n:::\n\n- `cooks.distance()` and `hatvalues()` work on `glm` objects just as they do on `lm` objects\n- The common threshold $4/n$ flags observations with disproportionate influence\n- For logistic regression with binary data, Cook's distance values tend to be smaller than in the continuous case\n\n\n:::\n\n::: {.panel-tabset}\n### Output\n\n::: {.cell}\n\n```{.r .cell-code  code-fold=\"true\" code-summary=\"Show R Code\"}\n# DFBETAS for each coefficient\ndfb <- dfbetas(penalty_model)\ndfb_df <- as.data.frame(dfb) |>\n  mutate(obs_id = row_number()) |>\n  pivot_longer(-obs_id, names_to = \"coefficient\", values_to = \"dfbeta\")\n\n# Threshold: 2/sqrt(n)\ndfbeta_threshold <- 2 / sqrt(nrow(penalty))\n\n# Count observations exceeding threshold\ndfb_df |>\n  group_by(coefficient) |>\n  summarise(\n    n_influential = sum(abs(dfbeta) > dfbeta_threshold),\n    max_dfbeta = round(max(abs(dfbeta)), 4),\n    .groups = \"drop\"\n  ) |>\n  kable(col.names = c(\"Coefficient\", \"N Influential\", \"Max |DFBETA|\"))\n```\n\n::: {.cell-output-display}\n\n\n|Coefficient | N Influential| Max &#124;DFBETA&#124;|\n|:-----------|-------------:|----------------------:|\n|(Intercept) |            53|                 0.1296|\n|def_bl      |            11|                 0.2429|\n|vic_bl      |            15|                 0.4106|\n\n\n:::\n:::\n\n\n### Output Interpretation\n\n\n::: {.cell}\n::: {.cell-output-display}\n\n\n|Coefficient | N Influential| Max &#124;DFBETA&#124;|\n|:-----------|-------------:|----------------------:|\n|(Intercept) |            53|                 0.1296|\n|def_bl      |            11|                 0.2429|\n|vic_bl      |            15|                 0.4106|\n\n\n:::\n:::\n\nIf the count of influential observations is small, the model estimates are stable. If many observations exceed the threshold for a particular coefficient, consider whether those cases share a common characteristic (e.g., unusual combinations of predictor values).\n\n### Code Explanation\n\n::: {.cell}\n\n```{.r .cell-code}\n# DFBETAS for each coefficient\ndfb <- dfbetas(penalty_model)\ndfb_df <- as.data.frame(dfb) |>\n  mutate(obs_id = row_number()) |>\n  pivot_longer(-obs_id, names_to = \"coefficient\", values_to = \"dfbeta\")\n\n# Threshold: 2/sqrt(n)\ndfbeta_threshold <- 2 / sqrt(nrow(penalty))\n\n# Count observations exceeding threshold\ndfb_df |>\n  group_by(coefficient) |>\n  summarise(\n    n_influential = sum(abs(dfbeta) > dfbeta_threshold),\n    max_dfbeta = round(max(abs(dfbeta)), 4),\n    .groups = \"drop\"\n  ) |>\n  kable(col.names = c(\"Coefficient\", \"N Influential\", \"Max |DFBETA|\"))\n```\n\n::: {.cell-output-display}\n\n\n|Coefficient | N Influential| Max &#124;DFBETA&#124;|\n|:-----------|-------------:|----------------------:|\n|(Intercept) |            53|                 0.1296|\n|def_bl      |            11|                 0.2429|\n|vic_bl      |            15|                 0.4106|\n\n\n:::\n:::\n\n- `dfbetas()` returns a matrix with one column per coefficient and one row per observation\n- The standard threshold $2/\\sqrt{n}$ identifies observations with outsized influence on specific coefficients\n- Observations with large DFBETAS for the `def_bl` or `vic_bl` coefficient are disproportionately shaping the estimated effect of race\n\n\n:::\n\n\n### Titanic Example: Diagnostics with Continuous Predictors {#sec-ch11-titanic}\n\nWhen models include continuous predictors, the number of covariate patterns approaches $n$ and the grouped diagnostics from the previous sections become invalid. We illustrate this with the `titanic` data from @sec-ch9.\n\n::: {.panel-tabset}\n### Output\n\n::: {.cell}\n\n```{.r .cell-code  code-fold=\"true\" code-summary=\"Show R Code\"}\n# Fit a model with continuous and categorical predictors\ndata(titanic)\ntitanic_model <- glm(survived ~ sex + age + pclass,\n                     family = binomial, data = titanic)\n\n# Augment with diagnostics\ntitanic_diag <- titanic |>\n  filter(!is.na(age)) |>\n  mutate(\n    resid_dev = residuals(titanic_model, type = \"deviance\"),\n    cooks_d   = cooks.distance(titanic_model),\n    linear_pred = predict(titanic_model, type = \"link\"),\n    obs_id    = row_number()\n  )\n\n# Two-panel diagnostic plot\np1 <- ggplot(titanic_diag, aes(x = linear_pred, y = resid_dev)) +\n  geom_point(alpha = 0.25, color = ber640_colors[[\"primary\"]]) +\n  geom_hline(yintercept = 0, linetype = \"dashed\", color = \"grey50\") +\n  geom_smooth(method = \"loess\", formula = y ~ x, se = FALSE,\n              color = ber640_colors[[\"secondary\"]], linewidth = 0.8) +\n  labs(title = \"Deviance Residuals\",\n       x = \"Linear Predictor\", y = \"Deviance Residual\")\n\np2 <- ggplot(titanic_diag, aes(x = obs_id, y = cooks_d)) +\n  geom_point(alpha = 0.3, color = ber640_colors[[\"primary\"]]) +\n  geom_hline(yintercept = 4 / nrow(titanic_diag),\n             linetype = \"dashed\", color = ber640_colors[[\"secondary\"]]) +\n  labs(title = \"Cook's Distance\",\n       x = \"Observation Index\", y = \"Cook's Distance\")\n\np1 + p2\n```\n\n::: {.cell-output-display}\n![Diagnostic plots for a logistic regression with continuous predictors (Titanic data). Left: deviance residuals show the characteristic two-band pattern of binary data. Right: Cook's distance reveals a handful of influential passengers.](11-logistic-diagnostics_files/figure-html/fig-ch11-titanic-diagnostics-1.png){#fig-ch11-titanic-diagnostics fig-alt='Two-panel diagnostic plot for the Titanic logistic regression model. Left panel shows deviance residuals on the y-axis versus the linear predictor on the x-axis, displaying the characteristic two-band pattern typical of binary outcome data, with one band of positive residuals for survivors and one band of negative residuals for non-survivors. Right panel shows Cook\\'s distance on the y-axis versus observation index on the x-axis, where most values are near zero but a handful of points have notably larger Cook\\'s distance, identifying influential passengers whose removal would meaningfully change the fitted model.' width=2700}\n:::\n:::\n\n\n### Output Interpretation\n\n\n::: {.cell}\n::: {.cell-output-display}\n![](11-logistic-diagnostics_files/figure-html/unnamed-chunk-36-1.png){width=2400}\n:::\n:::\n\nIf the LOESS smoother departs substantially from zero, this suggests the linear predictor is misspecified --- perhaps a nonlinear term for age is needed. The Cook's distance plot identifies specific passengers whose inclusion substantially affects the estimated coefficients.\n\n### Code Explanation\n\n::: {.cell}\n\n```{.r .cell-code}\n# Fit a model with continuous and categorical predictors\ndata(titanic)\ntitanic_model <- glm(survived ~ sex + age + pclass,\n                     family = binomial, data = titanic)\n\n# Augment with diagnostics\ntitanic_diag <- titanic |>\n  filter(!is.na(age)) |>\n  mutate(\n    resid_dev = residuals(titanic_model, type = \"deviance\"),\n    cooks_d   = cooks.distance(titanic_model),\n    linear_pred = predict(titanic_model, type = \"link\"),\n    obs_id    = row_number()\n  )\n\n# Two-panel diagnostic plot\np1 <- ggplot(titanic_diag, aes(x = linear_pred, y = resid_dev)) +\n  geom_point(alpha = 0.25, color = ber640_colors[[\"primary\"]]) +\n  geom_hline(yintercept = 0, linetype = \"dashed\", color = \"grey50\") +\n  geom_smooth(method = \"loess\", formula = y ~ x, se = FALSE,\n              color = ber640_colors[[\"secondary\"]], linewidth = 0.8) +\n  labs(title = \"Deviance Residuals\",\n       x = \"Linear Predictor\", y = \"Deviance Residual\")\n\np2 <- ggplot(titanic_diag, aes(x = obs_id, y = cooks_d)) +\n  geom_point(alpha = 0.3, color = ber640_colors[[\"primary\"]]) +\n  geom_hline(yintercept = 4 / nrow(titanic_diag),\n             linetype = \"dashed\", color = ber640_colors[[\"secondary\"]]) +\n  labs(title = \"Cook's Distance\",\n       x = \"Observation Index\", y = \"Cook's Distance\")\n\np1 + p2\n```\n\n::: {.cell-output-display}\n![](11-logistic-diagnostics_files/figure-html/unnamed-chunk-37-1.png){width=2400}\n:::\n:::\n\n- The model includes `sex` (binary), `age` (continuous), and `pclass` (treated as numeric)\n- The LOESS smoother on the residual plot should be approximately flat and centered on zero if the model is well-specified\n- With continuous predictors, the residual plot has more spread, but the two-band structure remains because $y$ is binary\n- Influential observations in the Titanic data often correspond to unusual survival patterns (e.g., older passengers in third class who survived)\n\n\n:::\n\n### Calibration Plot {#sec-ch11-calibration}\n\nA **calibration plot** checks whether the predicted probabilities match the observed event rates. If a model predicts 30% risk for a group of observations, roughly 30% of those observations should have the event. Perfect calibration falls on the 45-degree line.\n\n::: {.panel-tabset}\n### Output\n\n::: {.cell}\n\n```{.r .cell-code  code-fold=\"true\" code-summary=\"Show R Code\"}\n# Calibration data: group by deciles of predicted probability\ntitanic_cal <- titanic |>\n  filter(!is.na(age)) |>\n  mutate(pi_hat = fitted(titanic_model)) |>\n  mutate(decile = ntile(pi_hat, 10)) |>\n  group_by(decile) |>\n  summarise(\n    mean_predicted = mean(pi_hat),\n    mean_observed  = mean(survived),\n    n_group        = n(),\n    se_obs         = sqrt(mean_observed * (1 - mean_observed) / n()),\n    .groups        = \"drop\"\n  )\n\nggplot(titanic_cal, aes(x = mean_predicted, y = mean_observed)) +\n  geom_abline(intercept = 0, slope = 1, linetype = \"dashed\", color = \"grey50\") +\n  geom_point(size = 3, color = ber640_colors[[\"accent\"]], alpha = 0.8) +\n  geom_errorbar(aes(ymin = mean_observed - 1.96 * se_obs,\n                    ymax = mean_observed + 1.96 * se_obs),\n                width = 0.02, color = ber640_colors[[\"primary\"]]) +\n  geom_smooth(formula = y ~ x, method = \"loess\", se = FALSE,\n              color = ber640_colors[[\"secondary\"]], linewidth = 0.8) +\n  coord_equal(xlim = c(0, 1), ylim = c(0, 1)) +\n  labs(\n    title = \"Calibration Plot (Titanic Model)\",\n    x = \"Mean Predicted Probability\",\n    y = \"Observed Proportion\"\n  )\n```\n\n::: {.cell-output-display}\n![Calibration plot for the Titanic logistic regression model. Observations are grouped into deciles of predicted probability. A perfectly calibrated model would place all points on the dashed diagonal.](11-logistic-diagnostics_files/figure-html/fig-ch11-calibration-1.png){#fig-ch11-calibration fig-alt='Calibration plot with mean predicted probability on the x-axis and observed proportion of survivors on the y-axis, both ranging from 0 to 1. Ten points represent decile groups of observations sorted by predicted probability. A dashed diagonal line from the origin to the upper-right corner represents perfect calibration. Points falling close to this diagonal indicate that the model\\'s predicted probabilities match the observed event rates well. Deviations from the diagonal reveal where the model over- or under-predicts survival.' width=2400}\n:::\n:::\n\n\n### Output Interpretation\n\n\n::: {.cell}\n::: {.cell-output-display}\n![](11-logistic-diagnostics_files/figure-html/unnamed-chunk-38-1.png){width=2400}\n:::\n:::\n\nPoints close to the 45-degree line indicate good calibration. Deviations reveal where the model is miscalibrated: points above the line mean the model under-predicts (observed rate > predicted), and points below mean it over-predicts. A model can have good discrimination (separating events from non-events) but poor calibration (predicted probabilities are systematically off). Calibration plots complement pseudo $R^2$ and classification metrics.\n\n### Code Explanation\n\n::: {.cell}\n\n```{.r .cell-code}\n# Calibration data: group by deciles of predicted probability\ntitanic_cal <- titanic |>\n  filter(!is.na(age)) |>\n  mutate(pi_hat = fitted(titanic_model)) |>\n  mutate(decile = ntile(pi_hat, 10)) |>\n  group_by(decile) |>\n  summarise(\n    mean_predicted = mean(pi_hat),\n    mean_observed  = mean(survived),\n    n_group        = n(),\n    se_obs         = sqrt(mean_observed * (1 - mean_observed) / n()),\n    .groups        = \"drop\"\n  )\n\nggplot(titanic_cal, aes(x = mean_predicted, y = mean_observed)) +\n  geom_abline(intercept = 0, slope = 1, linetype = \"dashed\", color = \"grey50\") +\n  geom_point(size = 3, color = ber640_colors[[\"accent\"]], alpha = 0.8) +\n  geom_errorbar(aes(ymin = mean_observed - 1.96 * se_obs,\n                    ymax = mean_observed + 1.96 * se_obs),\n                width = 0.02, color = ber640_colors[[\"primary\"]]) +\n  geom_smooth(formula = y ~ x, method = \"loess\", se = FALSE,\n              color = ber640_colors[[\"secondary\"]], linewidth = 0.8) +\n  coord_equal(xlim = c(0, 1), ylim = c(0, 1)) +\n  labs(\n    title = \"Calibration Plot (Titanic Model)\",\n    x = \"Mean Predicted Probability\",\n    y = \"Observed Proportion\"\n  )\n```\n\n::: {.cell-output-display}\n![](11-logistic-diagnostics_files/figure-html/unnamed-chunk-39-1.png){width=2400}\n:::\n:::\n\n- Observations are grouped into deciles based on predicted probability $\\hat{\\pi}_i$\n- Within each decile, the mean predicted probability is plotted against the observed event rate\n- Deciles are constructed to have roughly equal counts (about 104 observations each), so all points are drawn at a single fixed size\n- Error bars show $\\pm 1.96 \\text{SE}$ for the observed proportion (binomial standard error)\n- The LOESS smoother highlights systematic calibration patterns\n\n\n:::\n\n\n### The Hosmer-Lemeshow Test {#sec-ch11-hl}\n\nThe calibration plot above is a *visual* check; the **Hosmer-Lemeshow (HL) test** is its formal counterpart. It groups observations into deciles of predicted risk --- exactly the partition the calibration plot visualizes --- and compares the observed and expected event counts within each group using an approximate chi-square statistic. A small $p$-value flags a discrepancy between predicted and observed rates, i.e. imperfect calibration.\n\n\n::: {.cell}\n\n```{.r .cell-code  code-fold=\"true\" code-summary=\"Show R Code\"}\nperformance::performance_hosmer(titanic_model)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# Hosmer-Lemeshow Goodness-of-Fit Test\n\n  Chi-squared: 39.882\n           df:  8    \n      p-value:  0.000\n```\n\n\n:::\n:::\n\n\nFor the Titanic model the test returns $\\chi^2 \\approx 39.9$ on $df = 8$ with $p < 0.001$, which here signals that the model does not fit the deciles well --- consistent with the departures visible in the calibration plot. That said, the HL test carries well-known caveats: it depends on the *arbitrary* number of groups (the result can change if you use $8$ groups instead of $10$), it tends to **over-reject** in large samples (trivial misfit becomes \"significant\") and has **low power** in small ones, and it is sensitive to how predictors are coded. Read it **alongside** the calibration plot --- as one piece of evidence about calibration --- rather than as a definitive pass/fail verdict.\n\n### Influence Bubble Plot {#sec-ch11-influence-bubble}\n\nAn **influence bubble plot** simultaneously displays three diagnostics: leverage (x-axis), residual magnitude (y-axis), and Cook's distance (bubble size). This provides a compact summary that reveals whether influential observations are also poorly fitted.\n\n::: {.panel-tabset}\n### Output\n\n::: {.cell}\n\n```{.r .cell-code  code-fold=\"true\" code-summary=\"Show R Code\"}\ntitanic_bubble <- titanic |>\n  filter(!is.na(age)) |>\n  mutate(\n    resid_pearson = residuals(titanic_model, type = \"pearson\"),\n    cooks_d       = cooks.distance(titanic_model),\n    leverage      = hatvalues(titanic_model),\n    linear_pred   = predict(titanic_model, type = \"link\"),\n    survived_f    = factor(survived, labels = c(\"Died\", \"Survived\"))\n  )\n\n# Threshold for Cook's D\ncooks_threshold <- 4 / nrow(titanic_bubble)\n\nggplot(titanic_bubble, aes(x = leverage, y = resid_pearson)) +\n  geom_point(aes(size = cooks_d, color = survived_f), alpha = 0.4) +\n  geom_hline(yintercept = 0, linetype = \"dashed\", color = \"grey50\") +\n  geom_hline(yintercept = c(-2, 2), linetype = \"dotted\",\n             color = ber640_colors[[\"secondary\"]]) +\n  scale_size_continuous(name = \"Cook's D\", range = c(0.5, 5)) +\n  scale_color_manual(name = \"Outcome\",\n                     values = c(\"Died\" = ber640_colors[[\"primary\"]],\n                                \"Survived\" = ber640_colors[[\"warning\"]])) +\n  labs(\n    title = \"Influence Bubble Plot (Titanic Model)\",\n    x = \"Leverage (Hat Value)\",\n    y = \"Pearson Residual\"\n  )\n```\n\n::: {.cell-output-display}\n![Influence bubble plot for the Titanic model. Each point represents a passenger; bubble size is proportional to Cook's distance. The largest bubbles occur where the Pearson residual is large in magnitude (here a point near $-5.5$ at low leverage), so the most influential cases are large-residual, modest-leverage observations; the high-leverage points on the right carry only small-to-moderate Cook's distance.](11-logistic-diagnostics_files/figure-html/fig-ch11-influence-bubble-1.png){#fig-ch11-influence-bubble fig-alt='Bubble plot for the Titanic logistic regression model with leverage (hat values) on the x-axis and Pearson residuals on the y-axis. Each bubble represents one passenger, and bubble size is proportional to Cook\\'s distance. Most bubbles are small and clustered in two horizontal bands corresponding to survivors and non-survivors. The largest bubbles sit at large Pearson residuals but only modest leverage (for example a point near minus 5.5 at the far left), so the most influential passengers here are extreme-residual rather than high-leverage cases; the high-leverage points on the right of the plot carry only small Cook\\'s distance.' width=2400}\n:::\n:::\n\n\n### Output Interpretation\n\n\n::: {.cell}\n::: {.cell-output-display}\n![](11-logistic-diagnostics_files/figure-html/unnamed-chunk-40-1.png){width=2400}\n:::\n:::\n\nLook for large bubbles far from the center --- these are the observations that most affect the model. In the Titanic data, influential passengers are typically those with atypical survival outcomes given their demographics (e.g., a first-class male who survived, or a young third-class female who died). If removing such observations changes the substantive conclusions, the model's robustness should be questioned.\n\n### Code Explanation\n\n::: {.cell}\n\n```{.r .cell-code}\ntitanic_bubble <- titanic |>\n  filter(!is.na(age)) |>\n  mutate(\n    resid_pearson = residuals(titanic_model, type = \"pearson\"),\n    cooks_d       = cooks.distance(titanic_model),\n    leverage      = hatvalues(titanic_model),\n    linear_pred   = predict(titanic_model, type = \"link\"),\n    survived_f    = factor(survived, labels = c(\"Died\", \"Survived\"))\n  )\n\n# Threshold for Cook's D\ncooks_threshold <- 4 / nrow(titanic_bubble)\n\nggplot(titanic_bubble, aes(x = leverage, y = resid_pearson)) +\n  geom_point(aes(size = cooks_d, color = survived_f), alpha = 0.4) +\n  geom_hline(yintercept = 0, linetype = \"dashed\", color = \"grey50\") +\n  geom_hline(yintercept = c(-2, 2), linetype = \"dotted\",\n             color = ber640_colors[[\"secondary\"]]) +\n  scale_size_continuous(name = \"Cook's D\", range = c(0.5, 5)) +\n  scale_color_manual(name = \"Outcome\",\n                     values = c(\"Died\" = ber640_colors[[\"primary\"]],\n                                \"Survived\" = ber640_colors[[\"warning\"]])) +\n  labs(\n    title = \"Influence Bubble Plot (Titanic Model)\",\n    x = \"Leverage (Hat Value)\",\n    y = \"Pearson Residual\"\n  )\n```\n\n::: {.cell-output-display}\n![](11-logistic-diagnostics_files/figure-html/unnamed-chunk-41-1.png){width=2400}\n:::\n:::\n\n- The x-axis shows leverage ($h_{ii}$), which measures how unusual the predictor combination is\n- The y-axis shows Pearson residuals, which measure how poorly the observation is fitted\n- Bubble size is proportional to Cook's distance --- the combined effect of leverage and residual magnitude\n- Color distinguishes actual outcomes to reveal whether misfit is concentrated among survivors or non-survivors\n- Large bubbles anywhere off-center flag influential observations; in these data the biggest are large-residual, low-leverage cells (small cells with an unexpected outcome) rather than the high-leverage points on the right\n\n\n:::\n\n\n::: {.callout-tip}\n## When to Worry About Which Diagnostic\n\n| Diagnostic Tool | When to Worry | Action |\n|:---|:---|:---|\n| $X^2$ / $G^2$ goodness-of-fit | $p < 0.05$ with non-sparse data | Add interactions or nonlinear terms |\n| Pseudo $R^2$ | Very low (McFadden < 0.02) | Check if predictors are relevant |\n| Classification accuracy | Below base rate | Consider different threshold or predictors |\n| Binned residual plot | Systematic pattern in bands | Add nonlinear terms or missing predictors |\n| Calibration plot | Deviation from 45-degree line | Recalibrate or respecify the model |\n| Cook's distance | Values > $4/n$ | Inspect observation; refit without it |\n| DFBETAS | Values > $2/\\sqrt{n}$ | Check if conclusions change |\n\n: Summary guide for logistic regression diagnostics. {#tbl-ch11-when-to-worry}\n\nRemember: for inference-focused studies (e.g., testing racial bias), low pseudo $R^2$ and poor classification are not necessarily problems. The model can still provide valid estimates of covariate effects. For prediction-focused studies (e.g., clinical risk scores), calibration and classification matter more.\n:::\n\n\n::: {.callout-warning}\n## Wald vs. LR Test Discrepancy as a Sparseness Indicator\nWhen data are sparse, the **Wald test** and the **likelihood ratio (LR) test** can give very different results for the same coefficient. The Wald test relies on the estimated standard error (which may be inflated or deflated in sparse data), while the LR test compares model deviances (which is more robust). A large discrepancy between the two is a red flag that the data are too sparse for reliable inference. When in doubt, prefer the LR test as the more reliable signal, but also investigate sparse cells and possible separation; in small or separated samples, penalized or exact methods may be more appropriate (see @sec-ch10 for the comparison).\n:::\n\n\n## Summary and Key Takeaways {#sec-ch11-summary}\n\n::: {.callout-note}\n## Chapter 11 Summary\n\n1. **Goodness-of-fit tests** ($X^2$ and $G^2$) assess whether a logistic regression model adequately reproduces observed frequencies. They require **non-sparse grouped data** --- with continuous predictors, these tests are invalid.\n\n2. **Pseudo $R^2$ measures** quantify model improvement over the null model. At least six definitions exist; report the name alongside the value. McFadden $R^2$ values of 0.2--0.4 indicate strong models.\n\n3. **Classification tables** provide an intuitive assessment of predictive accuracy but are misleading with imbalanced outcomes. Cohen's $\\kappa$ adjusts for chance agreement. Classification accuracy and inferential utility are different questions.\n\n4. **Pearson and deviance residuals** standardize the raw residuals from binary data. Plot them against the linear predictor (not fitted probabilities) and look for systematic patterns.\n\n5. **Influence diagnostics** (Cook's distance, DFBETAS, influence bubble plots) extend naturally from linear to logistic regression. The same interpretation applies: large values indicate observations that disproportionately affect parameter estimates.\n\n6. **Binned residual plots** aggregate binary residuals into bins, making patterns visible that are hidden in raw residual plots. This is the logistic analogue of the residual-vs-fitted plot from @sec-ch8.\n\n7. **Calibration plots** check whether predicted probabilities match observed event rates. Good discrimination (separating groups) does not guarantee good calibration (accurate probabilities).\n\n8. **Sparseness** is the central challenge. When expected cell counts are small, $\\chi^2$ tests are invalid, Wald tests become unreliable, and the Wald-LR discrepancy serves as a diagnostic signal.\n\n9. **Connection to linear diagnostics**: The logic of @sec-ch8 carries forward --- check model specification, identify influential observations, assess whether conclusions are robust --- but the tools change because the outcome is binary rather than continuous (see @tbl-ch11-ols-comparison).\n:::\n\n\n## Exercises {#sec-ch11-exercises}\n\n::: {.callout-caution collapse=\"true\"}\n## Exercise 11.1: Goodness of Fit for Death Penalty with Interaction\nAdd the interaction term `def_bl:vic_bl` to the death penalty model. Compute the Pearson $X^2$ and Deviance $G^2$ statistics for this saturated model. What are the degrees of freedom? What happens to the test statistics? Explain why a saturated model always has $X^2 = G^2 = 0$.\n\n*Hint*: With 4 covariate patterns and 4 parameters (intercept + 2 main effects + 1 interaction), think about what happens to the degrees of freedom $J - p$. A saturated model has as many parameters as covariate patterns.\n\n\n::: {.cell}\n\n```{.r .cell-code  code-fold=\"true\" code-summary=\"Show Solution\"}\n# Saturated model (all interactions)\nsat_model <- glm(death_pe ~ def_bl * vic_bl,\n                 family = binomial, data = penalty)\n\n# Deviance of saturated model\ntibble(\n  Measure = c(\"Residual deviance\", \"Degrees of freedom\"),\n  Value   = c(round(deviance(sat_model), 4), sat_model$df.residual)\n) |>\n  kable()\n```\n\n::: {.cell-output-display}\n\n\n|Measure            |    Value|\n|:------------------|--------:|\n|Residual deviance  | 418.5767|\n|Degrees of freedom | 670.0000|\n\n\n:::\n\n```{.r .cell-code  code-fold=\"true\" code-summary=\"Show Solution\"}\n# With J = 4 patterns and p = 4 parameters, df = 0.\n# The saturated model perfectly reproduces all observed proportions,\n# so X² = G² = 0 by definition.\n\n# Compare coefficients\nbind_rows(\n  tidy_model(penalty_model) |> mutate(model = \"Main effects\"),\n  tidy_model(sat_model) |> mutate(model = \"With interaction\")\n) |>\n  select(model, term, estimate, p.value) |>\n  kable(digits = 4)\n```\n\n::: {.cell-output-display}\n\n\n|model            |term          | estimate| p.value|\n|:----------------|:-------------|--------:|-------:|\n|Main effects     |(Intercept)   |  -2.0595|  0.0000|\n|Main effects     |def_bl        |   0.8678|  0.0181|\n|Main effects     |vic_bl        |  -2.4044|  0.0001|\n|With interaction |(Intercept)   |  -2.0556|  0.0000|\n|With interaction |def_bl        |   0.8426|  0.0239|\n|With interaction |vic_bl        | -14.5105|  0.9807|\n|With interaction |def_bl:vic_bl |  12.1753|  0.9838|\n\n\n:::\n:::\n\n:::\n\n::: {.callout-caution collapse=\"true\"}\n## Exercise 11.2: Pseudo $R^2$ Comparison for Titanic Models\nFit three logistic regression models predicting Titanic survival: (a) `sex` only, (b) `sex + pclass`, (c) `sex + pclass + age`. For each model, compute McFadden's $R^2$ and Tjur's $R^2$. Which predictor contributes most to model fit? Do the two measures agree on the ranking?\n\n*Hint*: For McFadden's $R^2$, use the formula $(D_0 - D_1)/D_0$ where `D0 <- m$null.deviance` and `D1 <- m$deviance`. For Tjur's $R^2$, compare `mean(fitted(m)[y == 1])` vs `mean(fitted(m)[y == 0])`. The biggest jump in $R^2$ between consecutive models reveals which predictor matters most.\n\n\n::: {.cell}\n\n```{.r .cell-code  code-fold=\"true\" code-summary=\"Show Solution\"}\ndata(titanic)\n\nm1 <- glm(survived ~ sex, family = binomial, data = titanic)\nm2 <- glm(survived ~ sex + pclass, family = binomial, data = titanic)\nm3 <- glm(survived ~ sex + pclass + age, family = binomial,\n           data = titanic |> filter(!is.na(age)))\n\n# Collect pseudo R² values\nmodels <- list(\"sex only\" = m1, \"sex + pclass\" = m2, \"sex + pclass + age\" = m3)\n\nr2_table <- map_dfr(models, \\(m) {\n  D0 <- m$null.deviance\n  D1 <- m$deviance\n  mcf <- (D0 - D1) / D0\n  pi_hat <- fitted(m)\n  y <- m$y\n  tjur <- mean(pi_hat[y == 1]) - mean(pi_hat[y == 0])\n  tibble(McFadden = mcf, Tjur = tjur)\n}, .id = \"Model\")\n\nr2_table |> kable(digits = 4)\n```\n\n::: {.cell-output-display}\n\n\n|Model              | McFadden|   Tjur|\n|:------------------|--------:|------:|\n|sex only           |   0.2142| 0.2795|\n|sex + pclass       |   0.2779| 0.3449|\n|sex + pclass + age |   0.3051| 0.3763|\n\n\n:::\n:::\n\n:::\n\n::: {.callout-caution collapse=\"true\"}\n## Exercise 11.3: Influence Diagnostics for Titanic\nUsing the model `survived ~ sex + pclass + age`, identify the 5 most influential observations by Cook's distance. Examine their characteristics. Remove them and refit --- how much do the odds ratios change? Are the substantive conclusions affected?\n\n*Hint*: Use `cooks.distance(model)` to extract Cook's D, then `slice_max(cooks_d, n = 5)` to find the top 5. Compare odds ratios by fitting the model with and without these observations. A change of less than 10% in the odds ratios generally suggests robust conclusions.\n\n\n::: {.cell}\n\n```{.r .cell-code  code-fold=\"true\" code-summary=\"Show Solution\"}\ndata(titanic)\ntitanic_complete <- titanic |> filter(!is.na(age))\n\nm_full <- glm(survived ~ sex + pclass + age,\n              family = binomial, data = titanic_complete)\n\n# Find top 5 influential observations\ntitanic_complete <- titanic_complete |>\n  mutate(cooks_d = cooks.distance(m_full),\n         obs_id  = row_number())\n\ntop5 <- titanic_complete |>\n  slice_max(cooks_d, n = 5)\n\ntop5 |>\n  select(obs_id, survived, sex, pclass, age, cooks_d) |>\n  kable(digits = 4, caption = \"Top 5 most influential observations\")\n```\n\n::: {.cell-output-display}\n\n\nTable: Top 5 most influential observations\n\n| obs_id| survived| sex| pclass| age| cooks_d|\n|------:|--------:|---:|------:|---:|-------:|\n|      3|        0|   1|      1|   2|  0.0217|\n|     15|        1|   0|      1|  80|  0.0159|\n|   1011|        1|   1|      3|  63|  0.0111|\n|    390|        1|   0|      2|  62|  0.0105|\n|    682|        1|   0|      3|  45|  0.0095|\n\n\n:::\n\n```{.r .cell-code  code-fold=\"true\" code-summary=\"Show Solution\"}\n# Refit without top 5\nm_reduced <- glm(survived ~ sex + pclass + age,\n                 family = binomial,\n                 data = titanic_complete |> filter(!obs_id %in% top5$obs_id))\n\nbind_rows(\n  tidy_model(m_full, exponentiate = TRUE) |> mutate(model = \"Full data\"),\n  tidy_model(m_reduced, exponentiate = TRUE) |> mutate(model = \"Without top 5\")\n) |>\n  select(model, term, estimate, p.value) |>\n  pivot_wider(names_from = model, values_from = c(estimate, p.value)) |>\n  kable(digits = 4, caption = \"Coefficient comparison (odds ratios)\")\n```\n\n::: {.cell-output-display}\n\n\nTable: Coefficient comparison (odds ratios)\n\n|term        | estimate_Full data| estimate_Without top 5| p.value_Full data| p.value_Without top 5|\n|:-----------|------------------:|----------------------:|-----------------:|---------------------:|\n|(Intercept) |             8.1002|                11.0824|                 0|                     0|\n|sex         |            12.1506|                12.8239|                 0|                     0|\n|pclass      |             0.3220|                 0.2984|                 0|                     0|\n|age         |             0.9667|                 0.9605|                 0|                     0|\n\n\n:::\n:::\n\n:::\n\n::: {.callout-caution collapse=\"true\"}\n## Exercise 11.4: Calibration Assessment\nUsing the Titanic model (`survived ~ sex + pclass + age`), create a calibration plot with 10 groups. Then add `I(age^2)` to the model and create a second calibration plot. Does the quadratic term improve calibration? Compare the two models using both McFadden's $R^2$ and visual calibration.\n\n*Hint*: Group observations into deciles of predicted probability using `ntile(pi_hat, 10)`. Within each decile, compare `mean(pi_hat)` to `mean(survived)`. Plot both models side-by-side using `patchwork`.\n\n\n::: {.cell}\n\n```{.r .cell-code  code-fold=\"true\" code-summary=\"Show Solution\"}\ndata(titanic)\ntitanic_ex4 <- titanic |> filter(!is.na(age))\n\n# Model without quadratic term\nm_linear <- glm(survived ~ sex + pclass + age,\n                family = binomial, data = titanic_ex4)\n\n# Model with quadratic term\nm_quad <- glm(survived ~ sex + pclass + age + I(age^2),\n              family = binomial, data = titanic_ex4)\n\n# Calibration function\nmake_calibration <- function(model, data, model_name) {\n  data |>\n    mutate(pi_hat = fitted(model)) |>\n    mutate(decile = ntile(pi_hat, 10)) |>\n    group_by(decile) |>\n    summarise(\n      mean_pred = mean(pi_hat),\n      mean_obs  = mean(survived),\n      .groups   = \"drop\"\n    ) |>\n    mutate(model = model_name)\n}\n\ncal_data <- bind_rows(\n  make_calibration(m_linear, titanic_ex4, \"Linear age\"),\n  make_calibration(m_quad, titanic_ex4, \"Quadratic age\")\n)\n\nggplot(cal_data, aes(x = mean_pred, y = mean_obs, color = model)) +\n  geom_abline(intercept = 0, slope = 1, linetype = \"dashed\", color = \"grey50\") +\n  geom_point(size = 3) +\n  geom_line() +\n  scale_color_manual(values = c(\"Linear age\" = ber640_colors[[\"primary\"]],\n                                \"Quadratic age\" = ber640_colors[[\"accent\"]])) +\n  coord_equal(xlim = c(0, 1), ylim = c(0, 1)) +\n  labs(\n    title = \"Calibration Comparison: Linear vs. Quadratic Age\",\n    x = \"Mean Predicted Probability\",\n    y = \"Observed Proportion\",\n    color = \"Model\"\n  )\n```\n\n::: {.cell-output-display}\n![](11-logistic-diagnostics_files/figure-html/ch11-ex4-1.png){width=2400}\n:::\n\n```{.r .cell-code  code-fold=\"true\" code-summary=\"Show Solution\"}\n# Compare McFadden R²\ntibble(\n  Model    = c(\"Linear age\", \"Quadratic age\"),\n  McFadden = round(c(\n    (m_linear$null.deviance - m_linear$deviance) / m_linear$null.deviance,\n    (m_quad$null.deviance - m_quad$deviance) / m_quad$null.deviance\n  ), 4)\n) |>\n  kable()\n```\n\n::: {.cell-output-display}\n\n\n|Model         | McFadden|\n|:-------------|--------:|\n|Linear age    |   0.3051|\n|Quadratic age |   0.3064|\n\n\n:::\n:::\n\n:::\n\n::: {.callout-caution collapse=\"true\"}\n## Exercise 11.5: Binned Residuals and Model Specification\nFit two logistic regression models for Titanic survival: (a) `survived ~ age` and (b) `survived ~ age + I(age^2)`. For each model, create a binned residual plot with the x-axis showing `age` (not the linear predictor). Does the linear model show a systematic pattern in the binned residuals that the quadratic model corrects? Connect this to the model specification checks from @sec-ch8.\n\n*Hint*: Instead of binning by the linear predictor, bin by `age` directly. Use `ntile(age, 30)` to create age-based bins. A U-shaped or curved pattern in the binned residuals of the linear model suggests that age has a nonlinear relationship with the log-odds of survival.\n\n\n::: {.cell}\n\n```{.r .cell-code  code-fold=\"true\" code-summary=\"Show Solution\"}\ndata(titanic)\ntitanic_ex5 <- titanic |> filter(!is.na(age))\n\n# Two models\nm_age <- glm(survived ~ age, family = binomial, data = titanic_ex5)\nm_age2 <- glm(survived ~ age + I(age^2), family = binomial, data = titanic_ex5)\n\n# Binned residual function\nbinned_resid_by_age <- function(model, data, model_name) {\n  data |>\n    mutate(resid_raw = survived - fitted(model)) |>\n    mutate(bin = ntile(age, 30)) |>\n    group_by(bin) |>\n    summarise(\n      mean_age   = mean(age),\n      mean_resid = mean(resid_raw),\n      se_resid   = sqrt(mean(fitted(model)) * (1 - mean(fitted(model))) / n()),\n      .groups    = \"drop\"\n    ) |>\n    mutate(model = model_name)\n}\n\nbinned_data <- bind_rows(\n  binned_resid_by_age(m_age, titanic_ex5, \"Linear: age only\"),\n  binned_resid_by_age(m_age2, titanic_ex5, \"Quadratic: age + age²\")\n)\n\nggplot(binned_data, aes(x = mean_age, y = mean_resid)) +\n  geom_ribbon(aes(ymin = -2 * se_resid, ymax = 2 * se_resid),\n              fill = \"grey85\", alpha = 0.4) +\n  geom_point(color = ber640_colors[[\"primary\"]], size = 2) +\n  geom_hline(yintercept = 0, linetype = \"dashed\", color = \"grey50\") +\n  geom_smooth(formula = y ~ x, method = \"loess\", se = FALSE,\n              color = ber640_colors[[\"secondary\"]], linewidth = 0.8) +\n  facet_wrap(~ model, ncol = 1) +\n  labs(\n    title = \"Binned Residuals by Age\",\n    x = \"Mean Age within Bin\",\n    y = \"Mean Residual within Bin\"\n  )\n```\n\n::: {.cell-output-display}\n![](11-logistic-diagnostics_files/figure-html/ch11-ex5-1.png){width=2400}\n:::\n:::\n\n:::\n\n::: {.callout-caution collapse=\"true\"}\n## Exercise 11.6: Why Can't We Use Standard Residual Plots for Logistic Regression?\nIn linear regression, we routinely plot raw residuals ($y_i - \\hat{y}_i$) against fitted values to check model assumptions.\n\na. Explain why raw residuals from a logistic regression model take on only two possible values for any given fitted probability $\\hat{\\pi}_i$. What are those two values?\nb. Given this discrete structure, why does a standard residual-vs-fitted plot look like two curved bands rather than a random scatter? Why is this uninformative for diagnosing model problems?\nc. How does binning residuals (as in a binned residual plot) overcome this limitation? What does a systematic pattern in a binned residual plot tell you that individual residuals cannot?\n\n*Hint*: For part (a), since $y_i \\in \\{0, 1\\}$, the residual is either $1 - \\hat{\\pi}_i$ or $0 - \\hat{\\pi}_i$. For part (b), every observation with the same fitted value produces the same two possible residuals, so no new diagnostic information emerges. Binning averages over many observations, allowing systematic departures from zero to emerge.\n:::\n\n::: {.callout-caution collapse=\"true\"}\n## Exercise 11.7: Interpreting Pseudo $R^2$ Values\nA researcher fits a logistic regression model predicting customer churn and reports McFadden's $R^2 = 0.18$. A colleague responds: \"That's terrible---in my linear regression models, I always get $R^2$ above 0.50.\"\n\na. Why is it misleading to compare McFadden's pseudo $R^2$ directly to the $R^2$ from ordinary linear regression? What does McFadden's $R^2$ actually measure?\nb. Explain why pseudo $R^2$ values in logistic regression are typically much lower than $R^2$ values in linear regression, even for models that predict well. What would McFadden's $R^2 = 1$ require?\nc. If you had to communicate model performance to a non-technical audience, would you use pseudo $R^2$, classification accuracy, AUC, or something else? Justify your choice.\n\n*Hint*: McFadden's $R^2$ measures the proportional reduction in deviance, not variance. Achieving $R^2 = 1$ would require a model with deviance of zero, meaning perfect deterministic separation of outcomes. For part (c), consider which metric is most intuitive and least likely to be misinterpreted.\n:::\n\n::: {.callout-caution collapse=\"true\"}\n## Exercise 11.8: Influential Observations in Logistic Regression\nSuppose you fit a logistic regression predicting loan default from income, and one observation has a very high Cook's distance.\n\na. In linear regression, an influential point can substantially shift the regression line. What does \"influential\" mean in the context of logistic regression---what specifically does the high-influence observation shift?\nb. If you remove this observation and the coefficient for income changes from $-0.03$ to $-0.05$, what does that tell you? Should you automatically remove influential points? Why or why not?\nc. Why are observations with predictor values far from the center of the data (high leverage) especially influential in logistic regression when their outcome goes against the model's prediction? Connect this to the concept of leverage in linear regression.\n\n*Hint*: For part (a), influence affects the estimated coefficients, which in turn shift the entire predicted probability curve. For part (b), removing an observation is an exploratory diagnostic, not a routine data-cleaning step---you need a substantive reason (e.g., data error). For part (c), high-leverage points exert more \"pull\" on the fit, and when their outcome is surprising, that pull is amplified.\n:::\n",
    "supporting": [
      "11-logistic-diagnostics_files"
    ],
    "filters": [
      "rmarkdown/pagebreak.lua"
    ],
    "includes": {},
    "engineDependencies": {},
    "preserve": {},
    "postProcess": true
  }
}