{
  "hash": "828c3a70b945b4e715c7c49d85a87488",
  "result": {
    "engine": "knitr",
    "markdown": "# Logistic Regression Example: Proposal {#sec-logistic-proposal}\n\n\n\n\n::: {.callout-note}\n## About This Chapter\nThis chapter demonstrates **Parts 1--3** of the logistic regression project\nusing the PIAAC Korea dataset. The same data and predictor variables from\nProject 1 are reused, but the outcome changes to a **binary** variable:\nwhether a worker holds a supervisory (managerial) position. Each section\nbegins with a guideline callout, followed by the example text.\n:::\n\n\n## Part 1: Background and Research Question {#sec-logistic-ex-part1}\n\n::: {.callout-important}\n## Guideline Reminder --- Part 1\nProvide a brief paragraph motivating **why** the topic matters, then state\n**one focused research question** involving a binary outcome. Name the modeled\nevent explicitly: which outcome category is $Y = 1$? Do **not** describe the\ndata or variables here --- save that for Part 2. (See @sec-logistic-part1 for\nthe full expectations.)\n:::\n\n### Background\n\nBeyond earnings, career advancement to supervisory positions is another\nimportant labor market outcome. Supervisory roles are often associated with\nhigher wages, greater autonomy, and greater influence over organizational\ndecisions. Understanding which individual characteristics are associated with\nsupervisory status can help us think more carefully about labor-market\nadvancement and inequality.\n\nIn South Korea, where educational attainment is nearly universal at the\ntertiary level, the traditional credential signal may have limited power to\ndifferentiate workers for promotion into supervisory roles. Cognitive skills\nmeasured directly --- such as numeracy --- may provide additional predictive\nvalue beyond years of schooling. Furthermore, a persistent gender gap in\nleadership positions raises the question of whether education and skill\nassociations with supervisory status differ between men and women.\n\nThis project examines how human capital, cognitive skills, occupation, and\ngender relate to supervisory status within the supplied PIAAC Korea teaching\nsubset.\n\n### Research Question\n\n**Research question:** Among Korean full-time workers, how are gender,\neducation, work experience, occupational classification, and numeracy\nassociated with the probability of holding a supervisory position\n(`manager = 1`), including whether the education or numeracy associations\ndiffer by gender?\n\n::: {.callout-tip}\n## Writing Tip\nProject 2 uses **one focused logistic research question**. The planned models\nbelow still build in stages --- baseline model, extended model, interaction\nmodel --- but those stages support the same overarching question rather than\ncreating separate numbered research questions.\n:::\n\n\n## Part 2: Methods --- Subjects and Variables {#sec-logistic-ex-part2}\n\n::: {.callout-important}\n## Guideline Reminder --- Part 2\nDescribe the **data source** and study design, the **subjects** and final\nanalytic sample size, the **missing-data rule**, and provide a table listing\n**every variable** with its name, type, coding, and definition. For the binary\noutcome, identify the event and non-event. For categorical predictors, list all\ncategories and the reference group. (See @sec-logistic-part2 for the full\nexpectations.)\n:::\n\n### Study Design and Data Source\n\nWe use the same data from the **Programme for the International Assessment of\nAdult Competencies** [PIAAC; @oecd2013piaac] described in @sec-linear-ex-part2.\nThe PIAAC provides detailed information on adult skills and labor market\noutcomes, including supervisory responsibilities.\n\n### Subjects\n\nThe supplied analysis file is the same already-filtered Korean PIAAC subset\nused in Project 1. It contains prime working-age adults (35--54) who were\nfull-time employees. After applying the complete-case rule to the planned\nlogistic outcome and predictors, the final analytic sample includes\n**$N$ = 1,357** respondents in the teaching file.\n\nAs in Project 1, this is an unweighted teaching subset. The logistic models do\nnot use PIAAC survey weights, replicate weights, plausible values, or complex\nsample design information, so inference is limited to this teaching analysis\nfile. Interpret odds ratios and predicted probabilities as sample associations\nwith supervisory status in this subset, not as nationally representative\nestimates.\n\n### Variables\n\nBecause this project reuses the same predictor variables from Project 1, we\nfocus on describing the **new outcome variable** and provide a complete\nvariable table for reference.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nanalysis_vars <- c(\n  \"manager\", \"female\", \"schyrs_c\", \"exper_c\",\n  \"exper2_c\", \"occupation\", \"numeracy\"\n)\n\nanalysis_df <- readRDS(here::here(\"data\", \"piaac_kor.rds\")) |>\n  mutate(occupation = fct_relevel(occupation, \"Skilled\")) |>\n  drop_na(all_of(analysis_vars))\n\ntibble(\n  final_n = nrow(analysis_df),\n  modeled_event = sum(analysis_df$manager == 1),\n  non_event = sum(analysis_df$manager == 0),\n  occupation_reference = levels(analysis_df$occupation)[1]\n)\n```\n\n::: {.cell-output-display}\n<div class=\"kable-table\">\n\n| final_n| modeled_event| non_event|occupation_reference |\n|-------:|-------------:|---------:|:--------------------|\n|    1357|           580|       777|Skilled              |\n\n</div>\n:::\n:::\n\n\n::: {.callout-note}\nAs in the linear regression example (@sec-linear-proposal), we set **Skilled** as the reference category for occupation. See Chapter 4 for the rationale.\n:::\n\n**Outcome variable.** The outcome is `manager`, a binary indicator of\nsupervisory status. The modeled event is `manager = 1`: the respondent\nsupervises other employees as part of their job. The non-event is\n`manager = 0`: the respondent does not supervise other employees. This\nvariable is derived from the PIAAC item asking whether the respondent manages\nor supervises other workers at their current job.\n\n@tbl-manager-distribution shows the number and percentage of workers in the\nmodeled event and non-event categories.\n\n\n::: {#tbl-manager-distribution .cell tbl-cap='Distribution of the outcome variable (manager).'}\n\n```{.r .cell-code}\n# Frequency table of the modeled event and non-event\nmanager_freq <- table(analysis_df$manager)\nmanager_pct  <- round(prop.table(manager_freq) * 100, 1)\n\nmanager_tbl <- tibble::tibble(\n  `Supervisory Status` = c(\n    \"Non-manager (0, non-event)\",\n    \"Manager (1, event)\",\n    \"Total\"\n  ),\n  n   = c(manager_freq[1], manager_freq[2], sum(manager_freq)),\n  `%` = c(manager_pct[1], manager_pct[2], 100.0)\n)\n\nkable(manager_tbl, align = \"lrr\")\n```\n\n::: {.cell-output-display}\n\n\n|Supervisory Status         |    n|     %|\n|:--------------------------|----:|-----:|\n|Non-manager (0, non-event) |  777|  57.3|\n|Manager (1, event)         |  580|  42.7|\n|Total                      | 1357| 100.0|\n\n\n:::\n:::\n\n\nThe sample contains **580 managers (42.7%)** and **777 non-managers (57.3%)**.\nThe outcome is not extremely rare, so logistic regression is an appropriate\nmodeling choice with no need for specialized rare-event methods.\n\n**Predictor variables.** All predictor variables are identical to those used in\nProject 1. @tbl-logistic-variables provides the complete variable table.\n\n\n::: {#tbl-logistic-variables .cell tbl-cap='Variables used in the logistic regression analysis of supervisory status in the PIAAC Korea teaching subset.'}\n\n```{.r .cell-code}\nvar_table <- tibble::tribble(\n  ~Variable,      ~Role,        ~Type,                    ~Definition,\n  \"`manager`\",    \"Outcome\",    \"Binary\",                 \"1 = supervises other employees (event), 0 = does not (non-event)\",\n  \"`female`\",     \"Predictor\",  \"Binary\",                 \"1 = female, 0 = male (ref)\",\n  \"`schyrs_c`\",   \"Predictor\",  \"Continuous\",             \"Mean-centered years of education\",\n  \"`exper_c`\",    \"Predictor\",  \"Continuous\",             \"Mean-centered work experience (in decades)\",\n  \"`exper2_c`\",   \"Predictor\",  \"Continuous\",             \"Squared term of mean-centered experience\",\n  \"`occupation`\", \"Predictor\",  \"Categorical (4 levels)\", \"Skilled (ref), Semi-white, Semi-blue, Elementary\",\n  \"`numeracy`\",   \"Predictor\",  \"Continuous\",             \"Z-scored numeracy proficiency (1 unit = 1 SD)\"\n)\n\nkable(var_table, align = \"llll\")\n```\n\n::: {.cell-output-display}\n\n\n|Variable     |Role      |Type                   |Definition                                                       |\n|:------------|:---------|:----------------------|:----------------------------------------------------------------|\n|`manager`    |Outcome   |Binary                 |1 = supervises other employees (event), 0 = does not (non-event) |\n|`female`     |Predictor |Binary                 |1 = female, 0 = male (ref)                                       |\n|`schyrs_c`   |Predictor |Continuous             |Mean-centered years of education                                 |\n|`exper_c`    |Predictor |Continuous             |Mean-centered work experience (in decades)                       |\n|`exper2_c`   |Predictor |Continuous             |Squared term of mean-centered experience                         |\n|`occupation` |Predictor |Categorical (4 levels) |Skilled (ref), Semi-white, Semi-blue, Elementary                 |\n|`numeracy`   |Predictor |Continuous             |Z-scored numeracy proficiency (1 unit = 1 SD)                    |\n\n\n:::\n:::\n\n\n::: {.callout-tip}\n## Writing Tip\nWhen the same predictors are used across projects, you do not need to repeat\nlengthy descriptions of every variable. Instead, reference the earlier project\nand focus your writing on what has changed --- in this case, the outcome\nvariable and the rationale for using logistic regression.\n:::\n\n\n## Part 3: Methods --- Statistical Analysis {#sec-logistic-ex-part3}\n\n::: {.callout-important}\n## Guideline Reminder --- Part 3\nWrite out your logistic regression model(s) using proper notation. If you use a\nmodel comparison strategy (e.g., nested models), describe each model stage and\nexplain how it supports the single research question. State your significance\nlevel. (See @sec-logistic-part3 for the full expectations.)\n:::\n\n### Analytic Strategy\n\nWe estimate a planned sequence of **three nested logistic regression models**\nto build evidence for the single research question. Model 1 estimates a\nbaseline human-capital specification, Model 2 adds cognitive skill and\noccupation, and Model 3 tests whether the education and numeracy associations\ndiffer by gender. All three models use the same complete-case `analysis_df`,\nso model comparisons are based on the same $N = 1{,}357$ rows.\n\nAll analyses are conducted in R (version 4.4+). We set the significance level\nat $\\alpha = 0.05$ for all statistical tests. Results will be presented as\n**odds ratios** with 95% confidence intervals, and we will compute **predicted\nprobabilities** to illustrate practical significance.\n\nLet $Y_i = 1$ if worker $i$ supervises other employees and $Y_i = 0$\notherwise. Let $p_i = P(Y_i = 1)$.\n\n### Model 1: Baseline Human Capital Model {#sec-logistic-ex-model1}\n\nThe first model regresses supervisory status on gender, education, and work\nexperience. The baseline model is shown in @eq-logistic-model1.\n\n$$\n\\begin{aligned}\n\\text{logit}(p_i) ={} & \\beta_0 + \\beta_1 \\, \\text{female}_i\n  + \\beta_2 \\, \\text{schyrs\\_c}_i\n  + \\beta_3 \\, \\text{exper\\_c}_i \\\\\n& + \\beta_4 \\, \\text{exper2\\_c}_i\n\\end{aligned}\n$$ {#eq-logistic-model1}\n\nwhere $\\text{logit}(p) = \\ln\\!\\big(\\frac{p}{1-p}\\big)$.\n\nThis baseline stage estimates the association of gender, education, and\nexperience with the odds of the modeled event, `manager = 1`. The\nexponentiated coefficient $e^{\\beta_2}$ gives the **odds ratio** for a\none-year increase in education, holding all other variables constant. The\nintercept $\\beta_0$ represents the log-odds of being a manager for a male\nworker with average education and average experience because both predictors\nare mean-centered.\n\n### Model 2: Adding Cognitive Skills and Occupation {#sec-logistic-ex-model2}\n\nThe second model extends Model 1 by adding occupational classification and\nnumeracy proficiency. The extended model is shown in @eq-logistic-model2.\n\nFor compact notation, define $D_{SW,i}$, $D_{SB,i}$, and $D_{EL,i}$ as\nindicators for the semi-white, semi-blue, and elementary occupation categories,\nrespectively. Skilled workers are the reference group. In R, we use\n`occupation` as a factor and let R create these contrasts automatically; the\ncourse data also include equivalent 0/1 columns (`semiwhite`, `semiblue`,\n`elementary`) if you want to inspect the coding.\n\n$$\n\\begin{aligned}\n\\text{logit}(p_i) ={} & \\beta_0 + \\beta_1 \\, \\text{female}_i\n  + \\beta_2 \\, \\text{schyrs\\_c}_i\n  + \\beta_3 \\, \\text{exper\\_c}_i\n  + \\beta_4 \\, \\text{exper2\\_c}_i \\\\\n& + \\beta_5 \\, D_{SW,i}\n  + \\beta_6 \\, D_{SB,i}\n  + \\beta_7 \\, D_{EL,i}\n  + \\beta_8 \\, \\text{numeracy}_i\n\\end{aligned}\n$$ {#eq-logistic-model2}\n\nThis stage tests whether occupation and numeracy add evidence about\nsupervisory status beyond the baseline human-capital variables. We compare\nModel 1 and Model 2 using a **likelihood ratio test** (the logistic regression\nanalogue of the incremental $F$-test) to determine whether the additional\npredictors significantly improve model fit.\n\nKey coefficients of interest:\n\n- $e^{\\beta_8}$ (numeracy): the multiplicative change in the odds of being a\n  manager for a one-SD increase in numeracy, holding all other variables\n  constant.\n- $e^{\\beta_5}$, $e^{\\beta_6}$, $e^{\\beta_7}$: the odds of being a manager in\n  each listed occupation category relative to the skilled reference group.\n\n### Model 3: Gender Interactions {#sec-logistic-ex-model3}\n\nThe third model extends Model 2 by adding interaction terms between gender and\ntwo key predictors --- education and numeracy. The interaction model is shown\nin @eq-logistic-model3.\n\n$$\n\\begin{aligned}\n\\text{logit}(p_i) ={} & \\beta_0 + \\beta_1 \\, \\text{female}_i\n  + \\beta_2 \\, \\text{schyrs\\_c}_i\n  + \\beta_3 \\, \\text{exper\\_c}_i\n  + \\beta_4 \\, \\text{exper2\\_c}_i \\\\\n& + \\beta_5 \\, D_{SW,i}\n  + \\beta_6 \\, D_{SB,i}\n  + \\beta_7 \\, D_{EL,i}\n  + \\beta_8 \\, \\text{numeracy}_i \\\\\n& + \\beta_9 \\, (\\text{female}_i \\times \\text{schyrs\\_c}_i)\n  + \\beta_{10} \\, (\\text{female}_i \\times \\text{numeracy}_i)\n\\end{aligned}\n$$ {#eq-logistic-model3}\n\nThis stage tests whether the education and numeracy associations with the\nlog-odds of the modeled event differ between men and women:\n\n- $\\beta_9 > 0$ would indicate that the education log-odds association is\n  larger for women than for men.\n- $\\beta_{10} > 0$ would indicate that the numeracy log-odds association is\n  larger for women than for men.\n\nBecause interaction terms in logistic regression are on the log-odds scale,\nthe probability-scale implications will be interpreted using predicted\nprobabilities in the results chapter.\n\nWe test the significance of the interaction block using a likelihood ratio\ntest comparing Model 2 and Model 3.\n\n### Summary of Model Stages\n\n@tbl-logistic-model-summary summarizes how the planned nested model stages\nsupport the single logistic research question.\n\n| Model | Predictors Added | Purpose for the Single Research Question |\n|-------|------------------|------------------------------------------|\n| Model 1 | `female`, `schyrs_c`, `exper_c`, `exper2_c` | Baseline association of gender, education, and experience with the odds of `manager = 1` |\n| Model 2 | + `occupation` factor contrasts, `numeracy` | Tests whether cognitive skill and occupation add evidence about supervisory status |\n| Model 3 | + `female` $\\times$ `schyrs_c`, `female` $\\times$ `numeracy` | Tests whether education and numeracy associations differ by gender |\n\n: Summary of the planned logistic model stages. {#tbl-logistic-model-summary}\n\n### Model Evaluation\n\nFor logistic regression, we will assess model quality using the following:\n\n1. **Overall model fit:** Model $N$ and log-likelihood from `nobs()` and\n   `logLik()`, plus AIC, BIC, Tjur's $R^2$, and RMSE from `model_fit()`.\n2. **Model comparison:** Likelihood ratio tests comparing the planned nested\n   model stages\n   (analogous to the incremental $F$-test in linear regression).\n3. **Sparse cells and separation:** Outcome-by-category tables, convergence\n   warnings, unusually large standard errors, and fitted probabilities close to\n   0 or 1.\n4. **Categorical predictor block:** An overall likelihood ratio test for the\n   multi-category occupation predictor.\n5. **Linearity in the logit:** A simple check for the continuous predictors\n   before relying on a linear logit specification.\n6. **Multicollinearity:** Variance inflation factors for the full logistic\n   model, using `performance::check_collinearity()`; values above 5 will be\n   flagged for discussion.\n7. **Influence:** Cook's distance or related influence screening, followed by\n   a sensitivity check if influential observations appear to drive conclusions.\n\n::: {.callout-tip}\n## Writing Tip\nLogistic regression does not have the same residual-based assumption checks as\nlinear regression (no normality or homoscedasticity of residuals). Instead,\nfocus on overall model fit statistics, the likelihood ratio test, and\npredicted probabilities. Mentioning your evaluation plan in the proposal\nshows methodological awareness.\n:::\n\n\n### R Setup for the Analysis\n\nThe code below shows the R commands we will use to fit the three models. The\nresults will be reported and interpreted in @sec-logistic-results.\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# --- Model 1: Baseline human capital model ---\nlogit1 <- glm(manager ~ female + schyrs_c + exper_c + exper2_c,\n              data = analysis_df, family = binomial)\n\n# --- Model 2: Add occupation and numeracy ---\nlogit2 <- glm(manager ~ female + schyrs_c + exper_c + exper2_c +\n                occupation + numeracy,\n              data = analysis_df, family = binomial)\n\n# --- Model 3: Add gender interactions ---\nlogit3 <- glm(manager ~ female + schyrs_c + exper_c + exper2_c +\n                occupation + numeracy +\n                female:schyrs_c + female:numeracy,\n              data = analysis_df, family = binomial)\n\n# --- Odds ratios, fit, and planned model comparisons ---\nmodel_params(logit3, exponentiate = TRUE)\nmodel_fit(logit3)\nlogLik(logit3)\nperformance::check_collinearity(logit3)\nanova(logit1, logit2, test = \"Chisq\")   # Occupation + numeracy block\nanova(logit2, logit3, test = \"Chisq\")   # Gender interaction block\n```\n:::\n\n\n::: {.callout-note}\n## What Comes Next\nIn @sec-logistic-results, we will fit these three models, report the odds ratios\nin a combined table, compute predicted probabilities for key comparisons,\ninterpret the results in the context of the single research question, and\nevaluate model fit.\n:::\n",
    "supporting": [],
    "filters": [
      "rmarkdown/pagebreak.lua"
    ],
    "includes": {},
    "engineDependencies": {},
    "preserve": {},
    "postProcess": true
  }
}