{
  "hash": "93778176b01862df471d9638700be38d",
  "result": {
    "engine": "knitr",
    "markdown": "# Logistic Regression Example: Results & Discussion {#sec-logistic-results}\n\n\n\n\n::: {.callout-note}\n## About This Chapter\nThis chapter demonstrates **Parts 4--6** of the logistic regression project\n(Descriptive Statistics, Results, and Discussion). This is the main analysis\nchapter for Project 2. Every code block runs on the PIAAC Korea dataset and\nproduces real output, so you can follow along step by step. The focus is on\n**odds ratios**, **predicted probabilities**, and proper interpretation of\nlogistic regression output.\n:::\n\n\n## Part 4: Descriptive Analysis {#sec-logistic-ex-part4}\n\n::: {.callout-important}\n## Guideline Reminder --- Part 4\nBefore running any regressions, describe your data. For logistic regression\nwith a binary outcome, cross-tabulations and grouped comparisons are\nespecially informative. Report the outcome distribution, present\ncross-tabulations with row/column percentages, and include visualizations\nthat preview the relationships you will model.\n:::\n\n### Sample Overview {#sec-logistic-ex-sample-overview}\n\nWe begin by loading the analysis dataset and confirming the sample size and\nthe distribution of the outcome variable.\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Load the PIAAC Korea analysis dataset\npiaac <- readRDS(here::here(\"data\", \"piaac_kor.rds\"))\n\n# Confirm sample size\ncat(\"Sample size:\", nrow(piaac), \"\\n\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nSample size: 1357 \n```\n\n\n:::\n\n```{.r .cell-code}\ncat(\"Variables:  \", ncol(piaac), \"\\n\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nVariables:   21 \n```\n\n\n:::\n\n```{.r .cell-code}\n# Outcome distribution\ncat(\"\\nSupervisory status:\\n\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\nSupervisory status:\n```\n\n\n:::\n\n```{.r .cell-code}\ntable(piaac$manager) |> addmargins()\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\n   0    1  Sum \n 777  580 1357 \n```\n\n\n:::\n\n```{.r .cell-code}\ncat(\"\\nProportions:\\n\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\nProportions:\n```\n\n\n:::\n\n```{.r .cell-code}\nprop.table(table(piaac$manager)) |> round(3)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\n    0     1 \n0.573 0.427 \n```\n\n\n:::\n:::\n\n\nThe analytic sample contains **N = 1,357** Korean full-time workers aged\n35--54. Among them, **580 (42.7%)** hold supervisory positions and **777\n(57.3%)** do not. This reasonably balanced split is well-suited for standard\nlogistic regression --- no rare-event corrections are needed.\n\n\n### Cross-Tabulation: Manager Status by Gender {#sec-logistic-ex-xtab-gender}\n\nA natural first step is to examine whether supervisory status varies by\ngender. @tbl-xtab-gender presents the cross-tabulation of `manager` by\n`female`, with both row and column percentages.\n\n\n::: {#tbl-xtab-gender .cell tbl-cap='Cross-Tabulation of Supervisory Status by Gender'}\n\n```{.r .cell-code}\n# Cross-tabulation with counts\nxtab_gender <- piaac |>\n  mutate(\n    Gender = factor(female, levels = c(0, 1),\n                    labels = c(\"Male\", \"Female\")),\n    Status = factor(manager, levels = c(0, 1),\n                    labels = c(\"Non-manager\", \"Manager\"))\n  ) |>\n  count(Gender, Status) |>\n  tidyr::pivot_wider(names_from = Status, values_from = n)\n\n# Add row totals\nxtab_gender <- xtab_gender |>\n  mutate(Total = `Non-manager` + Manager)\n\n# Display\nkable(xtab_gender, align = \"lrrr\")\n```\n\n::: {.cell-output-display}\n\n\n|Gender | Non-manager| Manager| Total|\n|:------|-----------:|-------:|-----:|\n|Male   |         362|     452|   814|\n|Female |         415|     128|   543|\n\n\n:::\n:::\n\n\n\n::: {#tbl-xtab-gender-pct .cell tbl-cap='Row Percentages: Supervisory Status by Gender'}\n\n```{.r .cell-code}\n# Row percentages\npiaac |>\n  mutate(\n    Gender = factor(female, levels = c(0, 1),\n                    labels = c(\"Male\", \"Female\")),\n    Status = factor(manager, levels = c(0, 1),\n                    labels = c(\"Non-manager\", \"Manager\"))\n  ) |>\n  count(Gender, Status) |>\n  group_by(Gender) |>\n  mutate(pct = round(n / sum(n) * 100, 1)) |>\n  ungroup() |>\n  select(Gender, Status, pct) |>\n  tidyr::pivot_wider(names_from = Status, values_from = pct) |>\n  kable(align = \"lrr\",\n        col.names = c(\"Gender\", \"Non-manager (%)\", \"Manager (%)\"))\n```\n\n::: {.cell-output-display}\n\n\n|Gender | Non-manager (%)| Manager (%)|\n|:------|---------------:|-----------:|\n|Male   |            44.5|        55.5|\n|Female |            76.4|        23.6|\n\n\n:::\n:::\n\n\nThe cross-tabulation reveals a clear gender difference: approximately half of\nmale workers are managers, compared with roughly one-third of female workers.\nThis raw difference foreshadows the gender gap we will examine in the\nregression analysis.\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Chi-square test: manager x female\nchisq.test(table(piaac$manager, piaac$female))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\n\tPearson's Chi-squared test with Yates' continuity correction\n\ndata:  table(piaac$manager, piaac$female)\nX-squared = 134.61, df = 1, p-value < 2.2e-16\n```\n\n\n:::\n:::\n\n\nThe chi-square test confirms that the association between supervisory status\nand gender is statistically significant ($p < .001$).\n\n\n### Cross-Tabulation: Manager Status by Occupation {#sec-logistic-ex-xtab-occ}\n\n@tbl-xtab-occ presents the cross-tabulation of supervisory status by\noccupational classification.\n\n\n::: {#tbl-xtab-occ .cell tbl-cap='Supervisory Status by Occupational Classification'}\n\n```{.r .cell-code}\npiaac |>\n  mutate(\n    Status = factor(manager, levels = c(0, 1),\n                    labels = c(\"Non-manager\", \"Manager\"))\n  ) |>\n  count(occupation, Status) |>\n  group_by(occupation) |>\n  mutate(pct = round(n / sum(n) * 100, 1)) |>\n  ungroup() |>\n  mutate(label = paste0(n, \" (\", pct, \"%)\")) |>\n  select(occupation, Status, label) |>\n  tidyr::pivot_wider(names_from = Status, values_from = label) |>\n  kable(align = \"lrr\",\n        col.names = c(\"Occupation\", \"Non-manager\", \"Manager\"))\n```\n\n::: {.cell-output-display}\n\n\n|Occupation | Non-manager|     Manager|\n|:----------|-----------:|-----------:|\n|Skilled    | 176 (40.2%)| 262 (59.8%)|\n|Semi-white | 264 (54.2%)| 223 (45.8%)|\n|Semi-blue  | 207 (71.4%)|  83 (28.6%)|\n|Elementary | 130 (91.5%)|   12 (8.5%)|\n\n\n:::\n:::\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Chi-square test: manager x occupation\nchisq.test(table(piaac$manager, piaac$occupation))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\n\tPearson's Chi-squared test\n\ndata:  table(piaac$manager, piaac$occupation)\nX-squared = 145.89, df = 3, p-value < 2.2e-16\n```\n\n\n:::\n:::\n\n\nThere is a strong association between occupation and supervisory status\n($p < .001$). Skilled and semi-white-collar workers have the highest rates of\nholding managerial positions, while elementary occupation workers have the\nlowest rate. This makes intuitive sense: managerial responsibilities tend to\nbe concentrated in higher-status occupational categories.\n\n\n### Continuous Predictors by Manager Status {#sec-logistic-ex-continuous}\n\n@tbl-logistic-desc-continuous presents the means of key continuous variables\n(years of education, work experience, and numeracy) separately for managers\nand non-managers.\n\n\n::: {#tbl-logistic-desc-continuous .cell tbl-cap='Continuous Variables by Supervisory Status'}\n\n```{.r .cell-code}\npiaac |>\n  mutate(\n    Status = factor(manager, levels = c(0, 1),\n                    labels = c(\"Non-manager\", \"Manager\"))\n  ) |>\n  select(Status, schyrs, exper, numeracy) |>\n  tbl_summary(\n    by = Status,\n    type = everything() ~ \"continuous\",\n    statistic = all_continuous() ~ \"{mean} ({sd})\",\n    label = list(\n      schyrs   ~ \"Years of education\",\n      exper    ~ \"Work experience (years)\",\n      numeracy ~ \"Numeracy (z-score)\"\n    ),\n    digits = everything() ~ 2\n  ) |>\n  add_overall() |>\n  add_p() |>\n  bold_labels() |>\n  bold_p(t = 0.05)\n```\n\n::: {.cell-output-display}\n\n```{=html}\n<div id=\"vrjnxtivwk\" style=\"padding-left:0px;padding-right:0px;padding-top:10px;padding-bottom:10px;overflow-x:auto;overflow-y:auto;width:auto;height:auto;\">\n<style>#vrjnxtivwk table {\n  font-family: system-ui, 'Segoe UI', Roboto, Helvetica, Arial, sans-serif, 'Apple Color Emoji', 'Segoe UI Emoji', 'Segoe UI Symbol', 'Noto Color Emoji';\n  -webkit-font-smoothing: antialiased;\n  -moz-osx-font-smoothing: grayscale;\n}\n\n#vrjnxtivwk thead, #vrjnxtivwk tbody, #vrjnxtivwk tfoot, #vrjnxtivwk tr, #vrjnxtivwk td, #vrjnxtivwk th {\n  border-style: none;\n}\n\n#vrjnxtivwk p {\n  margin: 0;\n  padding: 0;\n}\n\n#vrjnxtivwk .gt_table {\n  display: table;\n  border-collapse: collapse;\n  line-height: normal;\n  margin-left: auto;\n  margin-right: auto;\n  color: #333333;\n  font-size: 16px;\n  font-weight: normal;\n  font-style: normal;\n  background-color: #FFFFFF;\n  width: auto;\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #A8A8A8;\n  border-right-style: none;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #A8A8A8;\n  border-left-style: none;\n  border-left-width: 2px;\n  border-left-color: #D3D3D3;\n}\n\n#vrjnxtivwk .gt_caption {\n  padding-top: 4px;\n  padding-bottom: 4px;\n}\n\n#vrjnxtivwk .gt_title {\n  color: #333333;\n  font-size: 125%;\n  font-weight: initial;\n  padding-top: 4px;\n  padding-bottom: 4px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-bottom-color: #FFFFFF;\n  border-bottom-width: 0;\n}\n\n#vrjnxtivwk .gt_subtitle {\n  color: #333333;\n  font-size: 85%;\n  font-weight: initial;\n  padding-top: 3px;\n  padding-bottom: 5px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-top-color: #FFFFFF;\n  border-top-width: 0;\n}\n\n#vrjnxtivwk .gt_heading {\n  background-color: #FFFFFF;\n  text-align: center;\n  border-bottom-color: #FFFFFF;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n}\n\n#vrjnxtivwk .gt_bottom_border {\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n}\n\n#vrjnxtivwk .gt_col_headings {\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n}\n\n#vrjnxtivwk .gt_col_heading {\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: normal;\n  text-transform: inherit;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n  vertical-align: bottom;\n  padding-top: 5px;\n  padding-bottom: 6px;\n  padding-left: 5px;\n  padding-right: 5px;\n  overflow-x: hidden;\n}\n\n#vrjnxtivwk .gt_column_spanner_outer {\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: normal;\n  text-transform: inherit;\n  padding-top: 0;\n  padding-bottom: 0;\n  padding-left: 4px;\n  padding-right: 4px;\n}\n\n#vrjnxtivwk .gt_column_spanner_outer:first-child {\n  padding-left: 0;\n}\n\n#vrjnxtivwk .gt_column_spanner_outer:last-child {\n  padding-right: 0;\n}\n\n#vrjnxtivwk .gt_column_spanner {\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  vertical-align: bottom;\n  padding-top: 5px;\n  padding-bottom: 5px;\n  overflow-x: hidden;\n  display: inline-block;\n  width: 100%;\n}\n\n#vrjnxtivwk .gt_spanner_row {\n  border-bottom-style: hidden;\n}\n\n#vrjnxtivwk .gt_group_heading {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: initial;\n  text-transform: inherit;\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n  vertical-align: middle;\n  text-align: left;\n}\n\n#vrjnxtivwk .gt_empty_group_heading {\n  padding: 0.5px;\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: initial;\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  vertical-align: middle;\n}\n\n#vrjnxtivwk .gt_from_md > :first-child {\n  margin-top: 0;\n}\n\n#vrjnxtivwk .gt_from_md > :last-child {\n  margin-bottom: 0;\n}\n\n#vrjnxtivwk .gt_row {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  margin: 10px;\n  border-top-style: solid;\n  border-top-width: 1px;\n  border-top-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n  vertical-align: middle;\n  overflow-x: hidden;\n}\n\n#vrjnxtivwk .gt_stub {\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: initial;\n  text-transform: inherit;\n  border-right-style: solid;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#vrjnxtivwk .gt_stub_row_group {\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: initial;\n  text-transform: inherit;\n  border-right-style: solid;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n  padding-left: 5px;\n  padding-right: 5px;\n  vertical-align: top;\n}\n\n#vrjnxtivwk .gt_row_group_first td {\n  border-top-width: 2px;\n}\n\n#vrjnxtivwk .gt_row_group_first th {\n  border-top-width: 2px;\n}\n\n#vrjnxtivwk .gt_summary_row {\n  color: #333333;\n  background-color: #FFFFFF;\n  text-transform: inherit;\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#vrjnxtivwk .gt_first_summary_row {\n  border-top-style: solid;\n  border-top-color: #D3D3D3;\n}\n\n#vrjnxtivwk .gt_first_summary_row.thick {\n  border-top-width: 2px;\n}\n\n#vrjnxtivwk .gt_last_summary_row {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n}\n\n#vrjnxtivwk .gt_grand_summary_row {\n  color: #333333;\n  background-color: #FFFFFF;\n  text-transform: inherit;\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#vrjnxtivwk .gt_first_grand_summary_row {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-top-style: double;\n  border-top-width: 6px;\n  border-top-color: #D3D3D3;\n}\n\n#vrjnxtivwk .gt_last_grand_summary_row_top {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-bottom-style: double;\n  border-bottom-width: 6px;\n  border-bottom-color: #D3D3D3;\n}\n\n#vrjnxtivwk .gt_striped {\n  background-color: rgba(128, 128, 128, 0.05);\n}\n\n#vrjnxtivwk .gt_table_body {\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n}\n\n#vrjnxtivwk .gt_footnotes {\n  color: #333333;\n  background-color: #FFFFFF;\n  border-bottom-style: none;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 2px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n}\n\n#vrjnxtivwk .gt_footnote {\n  margin: 0px;\n  font-size: 90%;\n  padding-top: 4px;\n  padding-bottom: 4px;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#vrjnxtivwk .gt_sourcenotes {\n  color: #333333;\n  background-color: #FFFFFF;\n  border-bottom-style: none;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 2px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n}\n\n#vrjnxtivwk .gt_sourcenote {\n  font-size: 90%;\n  padding-top: 4px;\n  padding-bottom: 4px;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#vrjnxtivwk .gt_left {\n  text-align: left;\n}\n\n#vrjnxtivwk .gt_center {\n  text-align: center;\n}\n\n#vrjnxtivwk .gt_right {\n  text-align: right;\n  font-variant-numeric: tabular-nums;\n}\n\n#vrjnxtivwk .gt_font_normal {\n  font-weight: normal;\n}\n\n#vrjnxtivwk .gt_font_bold {\n  font-weight: bold;\n}\n\n#vrjnxtivwk .gt_font_italic {\n  font-style: italic;\n}\n\n#vrjnxtivwk .gt_super {\n  font-size: 65%;\n}\n\n#vrjnxtivwk .gt_footnote_marks {\n  font-size: 75%;\n  vertical-align: 0.4em;\n  position: initial;\n}\n\n#vrjnxtivwk .gt_asterisk {\n  font-size: 100%;\n  vertical-align: 0;\n}\n\n#vrjnxtivwk .gt_indent_1 {\n  text-indent: 5px;\n}\n\n#vrjnxtivwk .gt_indent_2 {\n  text-indent: 10px;\n}\n\n#vrjnxtivwk .gt_indent_3 {\n  text-indent: 15px;\n}\n\n#vrjnxtivwk .gt_indent_4 {\n  text-indent: 20px;\n}\n\n#vrjnxtivwk .gt_indent_5 {\n  text-indent: 25px;\n}\n\n#vrjnxtivwk .katex-display {\n  display: inline-flex !important;\n  margin-bottom: 0.75em !important;\n}\n\n#vrjnxtivwk div.Reactable > div.rt-table > div.rt-thead > div.rt-tr.rt-tr-group-header > div.rt-th-group:after {\n  height: 0px !important;\n}\n</style>\n<table class=\"gt_table\" data-quarto-disable-processing=\"false\" data-quarto-bootstrap=\"false\">\n  <thead>\n    <tr class=\"gt_col_headings\">\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_left\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"label\"><span data-qmd-base64=\"KipDaGFyYWN0ZXJpc3RpYyoq\"><span class='gt_from_md'><strong>Characteristic</strong></span></span></th>\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_center\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"stat_0\"><span data-qmd-base64=\"KipPdmVyYWxsKiogIApOID0gMSwzNTc=\"><span class='gt_from_md'><strong>Overall</strong><br />\nN = 1,357</span></span><span class=\"gt_footnote_marks\" style=\"white-space:nowrap;font-style:italic;font-weight:normal;line-height:0;\"><sup>1</sup></span></th>\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_center\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"stat_1\"><span data-qmd-base64=\"KipOb24tbWFuYWdlcioqICAKTiA9IDc3Nw==\"><span class='gt_from_md'><strong>Non-manager</strong><br />\nN = 777</span></span><span class=\"gt_footnote_marks\" style=\"white-space:nowrap;font-style:italic;font-weight:normal;line-height:0;\"><sup>1</sup></span></th>\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_center\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"stat_2\"><span data-qmd-base64=\"KipNYW5hZ2VyKiogIApOID0gNTgw\"><span class='gt_from_md'><strong>Manager</strong><br />\nN = 580</span></span><span class=\"gt_footnote_marks\" style=\"white-space:nowrap;font-style:italic;font-weight:normal;line-height:0;\"><sup>1</sup></span></th>\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_center\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"p.value\"><span data-qmd-base64=\"KipwLXZhbHVlKio=\"><span class='gt_from_md'><strong>p-value</strong></span></span><span class=\"gt_footnote_marks\" style=\"white-space:nowrap;font-style:italic;font-weight:normal;line-height:0;\"><sup>2</sup></span></th>\n    </tr>\n  </thead>\n  <tbody class=\"gt_table_body\">\n    <tr><td headers=\"label\" class=\"gt_row gt_left\" style=\"font-weight: bold;\">Years of education</td>\n<td headers=\"stat_0\" class=\"gt_row gt_center\">13.65 (2.94)</td>\n<td headers=\"stat_1\" class=\"gt_row gt_center\">12.86 (2.97)</td>\n<td headers=\"stat_2\" class=\"gt_row gt_center\">14.71 (2.53)</td>\n<td headers=\"p.value\" class=\"gt_row gt_center\" style=\"font-weight: bold;\"><0.001</td></tr>\n    <tr><td headers=\"label\" class=\"gt_row gt_left\" style=\"font-weight: bold;\">Work experience (years)</td>\n<td headers=\"stat_0\" class=\"gt_row gt_center\">16.46 (7.73)</td>\n<td headers=\"stat_1\" class=\"gt_row gt_center\">15.43 (8.11)</td>\n<td headers=\"stat_2\" class=\"gt_row gt_center\">17.83 (6.95)</td>\n<td headers=\"p.value\" class=\"gt_row gt_center\" style=\"font-weight: bold;\"><0.001</td></tr>\n    <tr><td headers=\"label\" class=\"gt_row gt_left\" style=\"font-weight: bold;\">Numeracy (z-score)</td>\n<td headers=\"stat_0\" class=\"gt_row gt_center\">0.00 (1.00)</td>\n<td headers=\"stat_1\" class=\"gt_row gt_center\">-0.20 (1.03)</td>\n<td headers=\"stat_2\" class=\"gt_row gt_center\">0.27 (0.90)</td>\n<td headers=\"p.value\" class=\"gt_row gt_center\" style=\"font-weight: bold;\"><0.001</td></tr>\n  </tbody>\n  \n  <tfoot class=\"gt_footnotes\">\n    <tr>\n      <td class=\"gt_footnote\" colspan=\"5\"><span class=\"gt_footnote_marks\" style=\"white-space:nowrap;font-style:italic;font-weight:normal;line-height:0;\"><sup>1</sup></span> <span data-qmd-base64=\"TWVhbiAoU0Qp\"><span class='gt_from_md'>Mean (SD)</span></span></td>\n    </tr>\n    <tr>\n      <td class=\"gt_footnote\" colspan=\"5\"><span class=\"gt_footnote_marks\" style=\"white-space:nowrap;font-style:italic;font-weight:normal;line-height:0;\"><sup>2</sup></span> <span data-qmd-base64=\"V2lsY294b24gcmFuayBzdW0gdGVzdA==\"><span class='gt_from_md'>Wilcoxon rank sum test</span></span></td>\n    </tr>\n  </tfoot>\n</table>\n</div>\n```\n\n:::\n:::\n\n\nManagers have slightly more education, more work experience, and somewhat\nhigher numeracy scores than non-managers. However, the differences in\neducation and numeracy are relatively modest. The descriptive statistics\nsuggest that occupation and gender may be more important differentiators\nthan continuous human capital variables --- a hypothesis we will test in the\nregression analysis.\n\n\n### Visualizations {#sec-logistic-ex-visualizations}\n\n#### Bar Chart: Manager Status by Gender\n\n@fig-logistic-bar-gender shows the proportion of managers and non-managers\nwithin each gender group.\n\n\n::: {.cell}\n\n```{.r .cell-code}\npiaac |>\n  mutate(\n    Gender = factor(female, levels = c(0, 1),\n                    labels = c(\"Male\", \"Female\")),\n    Status = factor(manager, levels = c(0, 1),\n                    labels = c(\"Non-manager\", \"Manager\"))\n  ) |>\n  count(Gender, Status) |>\n  group_by(Gender) |>\n  mutate(prop = n / sum(n)) |>\n  ggplot(aes(x = Gender, y = prop, fill = Status)) +\n  geom_col(position = \"dodge\", alpha = 0.85) +\n  scale_fill_manual(values = c(ber640_colors[\"primary\"],\n                               ber640_colors[\"accent\"])) +\n  scale_y_continuous(labels = scales::percent) +\n  labs(\n    x = \"Gender\",\n    y = \"Proportion\",\n    fill = \"Status\",\n    title = \"Supervisory Status by Gender\",\n    subtitle = \"PIAAC Korea sample (N = 1,357)\"\n  )\n```\n\n::: {.cell-output-display}\n![Supervisory Status by Gender](ch07-logistic-results_files/figure-html/fig-logistic-bar-gender-1.png){#fig-logistic-bar-gender fig-alt='Grouped bar chart showing the proportion of managers and non-managers by gender. About half of male workers are managers compared with roughly one-third of female workers, revealing a substantial gender gap in supervisory status.' width=2100}\n:::\n:::\n\n\nThe bar chart clearly shows the gender gap in supervisory status: male\nworkers are more likely to be managers than female workers.\n\n#### Boxplots: Continuous Predictors by Manager Status\n\n@fig-logistic-boxplots presents the distributions of years of education,\nwork experience, and numeracy by supervisory status.\n\n\n::: {.cell}\n\n```{.r .cell-code}\np_edu <- piaac |>\n  mutate(Status = factor(manager, levels = c(0, 1),\n                         labels = c(\"Non-manager\", \"Manager\"))) |>\n  ggplot(aes(x = Status, y = schyrs, fill = Status)) +\n  geom_boxplot(alpha = 0.7, show.legend = FALSE) +\n  scale_fill_manual(values = c(ber640_colors[\"primary\"],\n                               ber640_colors[\"accent\"])) +\n  labs(x = NULL, y = \"Years of education\", title = \"Education\")\n\np_exp <- piaac |>\n  mutate(Status = factor(manager, levels = c(0, 1),\n                         labels = c(\"Non-manager\", \"Manager\"))) |>\n  ggplot(aes(x = Status, y = exper, fill = Status)) +\n  geom_boxplot(alpha = 0.7, show.legend = FALSE) +\n  scale_fill_manual(values = c(ber640_colors[\"primary\"],\n                               ber640_colors[\"accent\"])) +\n  labs(x = NULL, y = \"Experience (years)\", title = \"Experience\")\n\np_num <- piaac |>\n  mutate(Status = factor(manager, levels = c(0, 1),\n                         labels = c(\"Non-manager\", \"Manager\"))) |>\n  ggplot(aes(x = Status, y = numeracy, fill = Status)) +\n  geom_boxplot(alpha = 0.7, show.legend = FALSE) +\n  scale_fill_manual(values = c(ber640_colors[\"primary\"],\n                               ber640_colors[\"accent\"])) +\n  labs(x = NULL, y = \"Numeracy (z-score)\", title = \"Numeracy\")\n\np_edu + p_exp + p_num\n```\n\n::: {.cell-output-display}\n![Distribution of Continuous Predictors by Supervisory Status](ch07-logistic-results_files/figure-html/fig-logistic-boxplots-1.png){#fig-logistic-boxplots fig-alt='Three-panel boxplot comparing managers and non-managers on education, experience, and numeracy. Managers have slightly higher median education and noticeably more work experience than non-managers. Numeracy distributions are similar for both groups with only a modest advantage for managers.' width=2100}\n:::\n:::\n\n\nKey observations from the boxplots:\n\n- **Education:** Managers have slightly more years of education on average,\n  but the distributions overlap substantially.\n- **Experience:** Managers tend to have more work experience, which is\n  consistent with the expectation that supervisory roles require seniority.\n- **Numeracy:** The distributions are similar for managers and non-managers,\n  with only a modest advantage for managers.\n\n::: {.callout-tip}\n## Writing Tip\nFor a binary outcome, bar charts (for categorical predictors) and boxplots\n(for continuous predictors) are the most informative exploratory\nvisualizations. They help you preview which predictors are likely to be\nimportant before fitting the logistic regression.\n:::\n\n\n## Part 5: Regression Analysis {#sec-logistic-ex-part5}\n\n::: {.callout-important}\n## Guideline Reminder --- Part 5\nFit your planned logistic regression models, present the results as **odds\nratios** in a publication-style table, interpret every coefficient\nsubstantively, and compare nested models using **likelihood ratio tests**.\nLink each model back to the research question it addresses. For logistic\nregression, the key deliverable is a **predicted probability graph**.\n:::\n\n### Model 1: Baseline Human Capital Model (RQ1) {#sec-logistic-ex-results-m1}\n\nWe begin by fitting Model 1, which regresses supervisory status on gender,\nyears of education (mean-centered), work experience (mean-centered, in\ndecades), and the squared experience term.\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# --- Model 1: Baseline human capital model ---\nlogit1 <- glm(manager ~ female + schyrs_c + exper_c + exper2_c,\n              data = piaac, family = binomial)\n\nsummary(logit1)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\nCall:\nglm(formula = manager ~ female + schyrs_c + exper_c + exper2_c, \n    family = binomial, data = piaac)\n\nCoefficients:\n            Estimate Std. Error z value Pr(>|z|)    \n(Intercept)  0.19347    0.09035   2.141   0.0322 *  \nfemale      -1.12960    0.13310  -8.487  < 2e-16 ***\nschyrs_c     0.23390    0.02397   9.757  < 2e-16 ***\nexper_c      0.43447    0.09044   4.804 1.55e-06 ***\nexper2_c    -0.23465    0.09183  -2.555   0.0106 *  \n---\nSignif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1\n\n(Dispersion parameter for binomial family taken to be 1)\n\n    Null deviance: 1852.5  on 1356  degrees of freedom\nResidual deviance: 1576.7  on 1352  degrees of freedom\nAIC: 1586.7\n\nNumber of Fisher Scoring iterations: 4\n```\n\n\n:::\n:::\n\n\n#### Odds Ratios for Model 1\n\nTo interpret logistic regression coefficients substantively, we exponentiate\nthem to obtain **odds ratios** (ORs).\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Odds ratios with 95% CI\nexp(cbind(OR = coef(logit1), confint(logit1))) |>\n  round(3)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n               OR 2.5 % 97.5 %\n(Intercept) 1.213 1.017  1.449\nfemale      0.323 0.248  0.419\nschyrs_c    1.264 1.206  1.325\nexper_c     1.544 1.296  1.847\nexper2_c    0.791 0.659  0.945\n```\n\n\n:::\n:::\n\n\n**Interpretation of Model 1:**\n\n- **Intercept (OR):** The baseline odds of being a manager for a *male*\n  worker with *average* education and *average* experience. Because the\n  intercept is on the log-odds scale, the exponentiated value gives the\n  odds (not probability) at the reference point.\n- **Female (OR $\\approx$ 0.32, $p < .001$):** Women have approximately 68%\n  lower odds of holding a supervisory position compared with men who have the\n  same education and experience. This is a substantial gender gap:\n  $100 \\times (1 - 0.32) = 68\\%$ reduction in odds.\n- **Education (OR $\\approx$ 1.26, $p < .001$):** Each additional year of\n  education is associated with a 26% increase in the odds of being a\n  manager, holding gender and experience constant.\n- **Experience (OR $> 1$):** Work experience in decades is associated with\n  higher odds of being a manager, consistent with seniority-based promotion\n  patterns.\n- **Experience squared:** The negative coefficient (OR $< 1$) on the squared\n  term indicates diminishing returns --- the promotion advantage of\n  experience levels off at higher tenure.\n\n\n### Model 2: Adding Occupation and Numeracy (RQ2) {#sec-logistic-ex-results-m2}\n\nModel 2 extends Model 1 by adding three occupation dummy variables (with\nskilled occupations as the reference category) and numeracy proficiency.\n\n::: {.callout-tip}\n## Two Ways to Include Categorical Predictors\nIn the proposal (@sec-logistic-proposal), we used `occupation` (a factor) and let R create the dummy variables automatically. Here we include the pre-computed dummies (`semiwhite`, `semiblue`, `elementary`) explicitly. Both approaches produce the same fitted values and overall model fit, but the coefficient table depends on which category is chosen as the reference. The explicit dummy version makes it easier to see exactly which coefficients appear in the output and ensures the reference category is unambiguous.\n:::\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# --- Model 2: + Occupation and numeracy ---\nlogit2 <- glm(manager ~ female + schyrs_c + exper_c + exper2_c +\n                semiwhite + semiblue + elementary + numeracy,\n              data = piaac, family = binomial)\n\nsummary(logit2)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\nCall:\nglm(formula = manager ~ female + schyrs_c + exper_c + exper2_c + \n    semiwhite + semiblue + elementary + numeracy, family = binomial, \n    data = piaac)\n\nCoefficients:\n            Estimate Std. Error z value Pr(>|z|)    \n(Intercept)  0.84629    0.14953   5.660 1.52e-08 ***\nfemale      -1.46225    0.14579 -10.030  < 2e-16 ***\nschyrs_c     0.10861    0.02991   3.631 0.000282 ***\nexper_c      0.44008    0.09508   4.629 3.68e-06 ***\nexper2_c    -0.22221    0.09562  -2.324 0.020134 *  \nsemiwhite   -0.14639    0.15726  -0.931 0.351901    \nsemiblue    -1.43097    0.20212  -7.080 1.44e-12 ***\nelementary  -2.16526    0.35273  -6.139 8.32e-10 ***\nnumeracy     0.04584    0.07682   0.597 0.550740    \n---\nSignif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1\n\n(Dispersion parameter for binomial family taken to be 1)\n\n    Null deviance: 1852.5  on 1356  degrees of freedom\nResidual deviance: 1481.6  on 1348  degrees of freedom\nAIC: 1499.6\n\nNumber of Fisher Scoring iterations: 5\n```\n\n\n:::\n:::\n\n\n#### Odds Ratios for Model 2\n\n\n::: {.cell}\n\n```{.r .cell-code}\nexp(cbind(OR = coef(logit2), confint(logit2))) |>\n  round(3)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n               OR 2.5 % 97.5 %\n(Intercept) 2.331 1.743  3.135\nfemale      0.232 0.174  0.308\nschyrs_c    1.115 1.052  1.183\nexper_c     1.553 1.291  1.875\nexper2_c    0.801 0.663  0.964\nsemiwhite   0.864 0.635  1.176\nsemiblue    0.239 0.160  0.354\nelementary  0.115 0.055  0.222\nnumeracy    1.047 0.901  1.217\n```\n\n\n:::\n:::\n\n\n**Interpretation of Model 2:**\n\n- **Occupation effects** (all relative to **Skilled** occupations, the\n  reference category):\n  - Semi-white-collar workers have about 14% lower odds of being managers\n    compared with skilled workers (OR $\\approx$ 0.86).\n  - Semi-blue-collar workers have about 76% lower odds compared with\n    skilled workers (OR $\\approx$ 0.24).\n  - Elementary workers have about 89% lower odds compared with skilled\n    workers (OR $\\approx$ 0.12). Equivalently, skilled workers have about\n    8.7 times the odds of elementary workers.\n  - This clear occupational gradient confirms that the type of work one does\n    is a major determinant of whether one supervises others.\n- **Numeracy (OR $\\approx$ 1, not significant):** Numeracy proficiency is\n  **not** a significant predictor of supervisory status after controlling for\n  education, experience, and occupation. This is an important contrast with\n  the linear regression results, where numeracy was highly significant for\n  predicting earnings.\n- **Female:** The gender odds ratio remains substantial (women still have\n  much lower odds of being managers) even after controlling for occupation\n  and cognitive skills.\n- **Education:** The education OR decreases somewhat after controlling for\n  occupation, suggesting that part of the education effect in Model 1\n  operated through occupational sorting.\n\n::: {.callout-tip}\n## Key Contrast with Linear Regression\nIn the earnings analysis (Project 1), numeracy was a significant predictor:\nwhat workers *know* mattered for how much they *earn*. Here, numeracy is\n**not** significant for managerial status. This suggests that cognitive\nskills contribute to earnings but do not independently drive promotion to\nsupervisory roles --- occupational classification is far more important.\n:::\n\n\n### Model 3: Gender Interactions (RQ3) {#sec-logistic-ex-results-m3}\n\nModel 3 extends Model 2 by adding interaction terms between gender and two\nkey predictors: education and numeracy. These interactions test whether the\npathways to managerial status differ between men and women.\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# --- Model 3: + Gender interactions ---\nlogit3 <- glm(manager ~ female + schyrs_c + exper_c + exper2_c +\n                semiwhite + semiblue + elementary + numeracy +\n                fem_schyrs_c + fem_numeracy,\n              data = piaac, family = binomial)\n\nsummary(logit3)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\nCall:\nglm(formula = manager ~ female + schyrs_c + exper_c + exper2_c + \n    semiwhite + semiblue + elementary + numeracy + fem_schyrs_c + \n    fem_numeracy, family = binomial, data = piaac)\n\nCoefficients:\n             Estimate Std. Error z value Pr(>|z|)    \n(Intercept)   0.85231    0.14999   5.682 1.33e-08 ***\nfemale       -1.48281    0.15011  -9.878  < 2e-16 ***\nschyrs_c      0.09031    0.03749   2.409   0.0160 *  \nexper_c       0.43480    0.09595   4.531 5.86e-06 ***\nexper2_c     -0.22461    0.09559  -2.350   0.0188 *  \nsemiwhite    -0.13702    0.15806  -0.867   0.3860    \nsemiblue     -1.44394    0.20367  -7.090 1.34e-12 ***\nelementary   -2.15937    0.35369  -6.105 1.03e-09 ***\nnumeracy      0.07670    0.09489   0.808   0.4189    \nfem_schyrs_c  0.04547    0.05674   0.801   0.4229    \nfem_numeracy -0.07855    0.16101  -0.488   0.6257    \n---\nSignif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1\n\n(Dispersion parameter for binomial family taken to be 1)\n\n    Null deviance: 1852.5  on 1356  degrees of freedom\nResidual deviance: 1480.9  on 1346  degrees of freedom\nAIC: 1502.9\n\nNumber of Fisher Scoring iterations: 5\n```\n\n\n:::\n:::\n\n\n#### Odds Ratios for Model 3\n\n\n::: {.cell}\n\n```{.r .cell-code}\nexp(cbind(OR = coef(logit3), confint(logit3))) |>\n  round(3)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n                OR 2.5 % 97.5 %\n(Intercept)  2.345 1.752  3.156\nfemale       0.227 0.169  0.304\nschyrs_c     1.095 1.017  1.179\nexper_c      1.545 1.282  1.868\nexper2_c     0.799 0.661  0.962\nsemiwhite    0.872 0.640  1.189\nsemiblue     0.236 0.158  0.351\nelementary   0.115 0.055  0.224\nnumeracy     1.080 0.897  1.301\nfem_schyrs_c 1.047 0.937  1.171\nfem_numeracy 0.924 0.674  1.268\n```\n\n\n:::\n:::\n\n\n**Interpretation of the interaction terms:**\n\n- **Female $\\times$ Education:** The interaction is not statistically\n  significant. There is no evidence that the association between education and the\n  odds of being a manager differs between men and women.\n- **Female $\\times$ Numeracy:** This interaction is also not significant.\n  The (already weak) association between numeracy and supervisory status does not vary\n  by gender.\n\nThese null interaction results indicate that the gender gap in managerial\nstatus operates primarily as a **level difference** (the main effect of\n`female`) rather than through differential returns to education or cognitive\nskills.\n\n\n### Publication-Style Odds Ratio Table {#sec-logistic-ex-or-table}\n\n@tbl-logistic-models presents all three models side by side in a\npublication-ready format with exponentiated coefficients (odds ratios).\n\n\n::: {#tbl-logistic-models .cell tbl-cap='Nested Logistic Regression Models Predicting Supervisory Status (Odds Ratios)'}\n\n```{.r .cell-code}\n# Create individual tbl_regression objects with odds ratios\nt1 <- tbl_regression(\n  logit1,\n  exponentiate = TRUE,\n  label = list(\n    female   ~ \"Female\",\n    schyrs_c ~ \"Education (years, centered)\",\n    exper_c  ~ \"Experience (decades, centered)\",\n    exper2_c ~ \"Experience squared\"\n  )\n) |> bold_p(t = 0.05)\n\nt2 <- tbl_regression(\n  logit2,\n  exponentiate = TRUE,\n  label = list(\n    female     ~ \"Female\",\n    schyrs_c   ~ \"Education (years, centered)\",\n    exper_c    ~ \"Experience (decades, centered)\",\n    exper2_c   ~ \"Experience squared\",\n    semiwhite  ~ \"Semi-white-collar\",\n    semiblue   ~ \"Semi-blue-collar\",\n    elementary ~ \"Elementary\",\n    numeracy   ~ \"Numeracy (z-score)\"\n  )\n) |> bold_p(t = 0.05)\n\nt3 <- tbl_regression(\n  logit3,\n  exponentiate = TRUE,\n  label = list(\n    female       ~ \"Female\",\n    schyrs_c     ~ \"Education (years, centered)\",\n    exper_c      ~ \"Experience (decades, centered)\",\n    exper2_c     ~ \"Experience squared\",\n    semiwhite    ~ \"Semi-white-collar\",\n    semiblue     ~ \"Semi-blue-collar\",\n    elementary   ~ \"Elementary\",\n    numeracy     ~ \"Numeracy (z-score)\",\n    fem_schyrs_c ~ \"Female x Education\",\n    fem_numeracy ~ \"Female x Numeracy\"\n  )\n) |> bold_p(t = 0.05)\n\n# Merge into one table\ntbl_merge(\n  tbls = list(t1, t2, t3),\n  tab_spanner = c(\"**Model 1**\", \"**Model 2**\", \"**Model 3**\")\n)\n```\n\n::: {.cell-output-display}\n\n```{=html}\n<div id=\"iosgnvcpxs\" style=\"padding-left:0px;padding-right:0px;padding-top:10px;padding-bottom:10px;overflow-x:auto;overflow-y:auto;width:auto;height:auto;\">\n<style>#iosgnvcpxs table {\n  font-family: system-ui, 'Segoe UI', Roboto, Helvetica, Arial, sans-serif, 'Apple Color Emoji', 'Segoe UI Emoji', 'Segoe UI Symbol', 'Noto Color Emoji';\n  -webkit-font-smoothing: antialiased;\n  -moz-osx-font-smoothing: grayscale;\n}\n\n#iosgnvcpxs thead, #iosgnvcpxs tbody, #iosgnvcpxs tfoot, #iosgnvcpxs tr, #iosgnvcpxs td, #iosgnvcpxs th {\n  border-style: none;\n}\n\n#iosgnvcpxs p {\n  margin: 0;\n  padding: 0;\n}\n\n#iosgnvcpxs .gt_table {\n  display: table;\n  border-collapse: collapse;\n  line-height: normal;\n  margin-left: auto;\n  margin-right: auto;\n  color: #333333;\n  font-size: 16px;\n  font-weight: normal;\n  font-style: normal;\n  background-color: #FFFFFF;\n  width: auto;\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #A8A8A8;\n  border-right-style: none;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #A8A8A8;\n  border-left-style: none;\n  border-left-width: 2px;\n  border-left-color: #D3D3D3;\n}\n\n#iosgnvcpxs .gt_caption {\n  padding-top: 4px;\n  padding-bottom: 4px;\n}\n\n#iosgnvcpxs .gt_title {\n  color: #333333;\n  font-size: 125%;\n  font-weight: initial;\n  padding-top: 4px;\n  padding-bottom: 4px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-bottom-color: #FFFFFF;\n  border-bottom-width: 0;\n}\n\n#iosgnvcpxs .gt_subtitle {\n  color: #333333;\n  font-size: 85%;\n  font-weight: initial;\n  padding-top: 3px;\n  padding-bottom: 5px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-top-color: #FFFFFF;\n  border-top-width: 0;\n}\n\n#iosgnvcpxs .gt_heading {\n  background-color: #FFFFFF;\n  text-align: center;\n  border-bottom-color: #FFFFFF;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n}\n\n#iosgnvcpxs .gt_bottom_border {\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n}\n\n#iosgnvcpxs .gt_col_headings {\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n}\n\n#iosgnvcpxs .gt_col_heading {\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: normal;\n  text-transform: inherit;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n  vertical-align: bottom;\n  padding-top: 5px;\n  padding-bottom: 6px;\n  padding-left: 5px;\n  padding-right: 5px;\n  overflow-x: hidden;\n}\n\n#iosgnvcpxs .gt_column_spanner_outer {\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: normal;\n  text-transform: inherit;\n  padding-top: 0;\n  padding-bottom: 0;\n  padding-left: 4px;\n  padding-right: 4px;\n}\n\n#iosgnvcpxs .gt_column_spanner_outer:first-child {\n  padding-left: 0;\n}\n\n#iosgnvcpxs .gt_column_spanner_outer:last-child {\n  padding-right: 0;\n}\n\n#iosgnvcpxs .gt_column_spanner {\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  vertical-align: bottom;\n  padding-top: 5px;\n  padding-bottom: 5px;\n  overflow-x: hidden;\n  display: inline-block;\n  width: 100%;\n}\n\n#iosgnvcpxs .gt_spanner_row {\n  border-bottom-style: hidden;\n}\n\n#iosgnvcpxs .gt_group_heading {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: initial;\n  text-transform: inherit;\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n  vertical-align: middle;\n  text-align: left;\n}\n\n#iosgnvcpxs .gt_empty_group_heading {\n  padding: 0.5px;\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: initial;\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  vertical-align: middle;\n}\n\n#iosgnvcpxs .gt_from_md > :first-child {\n  margin-top: 0;\n}\n\n#iosgnvcpxs .gt_from_md > :last-child {\n  margin-bottom: 0;\n}\n\n#iosgnvcpxs .gt_row {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  margin: 10px;\n  border-top-style: solid;\n  border-top-width: 1px;\n  border-top-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n  vertical-align: middle;\n  overflow-x: hidden;\n}\n\n#iosgnvcpxs .gt_stub {\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: initial;\n  text-transform: inherit;\n  border-right-style: solid;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#iosgnvcpxs .gt_stub_row_group {\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: initial;\n  text-transform: inherit;\n  border-right-style: solid;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n  padding-left: 5px;\n  padding-right: 5px;\n  vertical-align: top;\n}\n\n#iosgnvcpxs .gt_row_group_first td {\n  border-top-width: 2px;\n}\n\n#iosgnvcpxs .gt_row_group_first th {\n  border-top-width: 2px;\n}\n\n#iosgnvcpxs .gt_summary_row {\n  color: #333333;\n  background-color: #FFFFFF;\n  text-transform: inherit;\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#iosgnvcpxs .gt_first_summary_row {\n  border-top-style: solid;\n  border-top-color: #D3D3D3;\n}\n\n#iosgnvcpxs .gt_first_summary_row.thick {\n  border-top-width: 2px;\n}\n\n#iosgnvcpxs .gt_last_summary_row {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n}\n\n#iosgnvcpxs .gt_grand_summary_row {\n  color: #333333;\n  background-color: #FFFFFF;\n  text-transform: inherit;\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#iosgnvcpxs .gt_first_grand_summary_row {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-top-style: double;\n  border-top-width: 6px;\n  border-top-color: #D3D3D3;\n}\n\n#iosgnvcpxs .gt_last_grand_summary_row_top {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-bottom-style: double;\n  border-bottom-width: 6px;\n  border-bottom-color: #D3D3D3;\n}\n\n#iosgnvcpxs .gt_striped {\n  background-color: rgba(128, 128, 128, 0.05);\n}\n\n#iosgnvcpxs .gt_table_body {\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n}\n\n#iosgnvcpxs .gt_footnotes {\n  color: #333333;\n  background-color: #FFFFFF;\n  border-bottom-style: none;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 2px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n}\n\n#iosgnvcpxs .gt_footnote {\n  margin: 0px;\n  font-size: 90%;\n  padding-top: 4px;\n  padding-bottom: 4px;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#iosgnvcpxs .gt_sourcenotes {\n  color: #333333;\n  background-color: #FFFFFF;\n  border-bottom-style: none;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 2px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n}\n\n#iosgnvcpxs .gt_sourcenote {\n  font-size: 90%;\n  padding-top: 4px;\n  padding-bottom: 4px;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#iosgnvcpxs .gt_left {\n  text-align: left;\n}\n\n#iosgnvcpxs .gt_center {\n  text-align: center;\n}\n\n#iosgnvcpxs .gt_right {\n  text-align: right;\n  font-variant-numeric: tabular-nums;\n}\n\n#iosgnvcpxs .gt_font_normal {\n  font-weight: normal;\n}\n\n#iosgnvcpxs .gt_font_bold {\n  font-weight: bold;\n}\n\n#iosgnvcpxs .gt_font_italic {\n  font-style: italic;\n}\n\n#iosgnvcpxs .gt_super {\n  font-size: 65%;\n}\n\n#iosgnvcpxs .gt_footnote_marks {\n  font-size: 75%;\n  vertical-align: 0.4em;\n  position: initial;\n}\n\n#iosgnvcpxs .gt_asterisk {\n  font-size: 100%;\n  vertical-align: 0;\n}\n\n#iosgnvcpxs .gt_indent_1 {\n  text-indent: 5px;\n}\n\n#iosgnvcpxs .gt_indent_2 {\n  text-indent: 10px;\n}\n\n#iosgnvcpxs .gt_indent_3 {\n  text-indent: 15px;\n}\n\n#iosgnvcpxs .gt_indent_4 {\n  text-indent: 20px;\n}\n\n#iosgnvcpxs .gt_indent_5 {\n  text-indent: 25px;\n}\n\n#iosgnvcpxs .katex-display {\n  display: inline-flex !important;\n  margin-bottom: 0.75em !important;\n}\n\n#iosgnvcpxs div.Reactable > div.rt-table > div.rt-thead > div.rt-tr.rt-tr-group-header > div.rt-th-group:after {\n  height: 0px !important;\n}\n</style>\n<table class=\"gt_table\" data-quarto-disable-processing=\"false\" data-quarto-bootstrap=\"false\">\n  <thead>\n    <tr class=\"gt_col_headings gt_spanner_row\">\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_left\" rowspan=\"2\" colspan=\"1\" scope=\"col\" id=\"label\"><span data-qmd-base64=\"KipDaGFyYWN0ZXJpc3RpYyoq\"><span class='gt_from_md'><strong>Characteristic</strong></span></span></th>\n      <th class=\"gt_center gt_columns_top_border gt_column_spanner_outer\" rowspan=\"1\" colspan=\"3\" scope=\"colgroup\" id=\"level 1; estimate_1\">\n        <div class=\"gt_column_spanner\"><span data-qmd-base64=\"KipNb2RlbCAxKio=\"><span class='gt_from_md'><strong>Model 1</strong></span></span></div>\n      </th>\n      <th class=\"gt_center gt_columns_top_border gt_column_spanner_outer\" rowspan=\"1\" colspan=\"3\" scope=\"colgroup\" id=\"level 1; estimate_2\">\n        <div class=\"gt_column_spanner\"><span data-qmd-base64=\"KipNb2RlbCAyKio=\"><span class='gt_from_md'><strong>Model 2</strong></span></span></div>\n      </th>\n      <th class=\"gt_center gt_columns_top_border gt_column_spanner_outer\" rowspan=\"1\" colspan=\"3\" scope=\"colgroup\" id=\"level 1; estimate_3\">\n        <div class=\"gt_column_spanner\"><span data-qmd-base64=\"KipNb2RlbCAzKio=\"><span class='gt_from_md'><strong>Model 3</strong></span></span></div>\n      </th>\n    </tr>\n    <tr class=\"gt_col_headings\">\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_center\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"estimate_1\"><span data-qmd-base64=\"KipPUioq\"><span class='gt_from_md'><strong>OR</strong></span></span></th>\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_center\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"conf.low_1\"><span data-qmd-base64=\"Kio5NSUgQ0kqKg==\"><span class='gt_from_md'><strong>95% CI</strong></span></span></th>\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_center\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"p.value_1\"><span data-qmd-base64=\"KipwLXZhbHVlKio=\"><span class='gt_from_md'><strong>p-value</strong></span></span></th>\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_center\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"estimate_2\"><span data-qmd-base64=\"KipPUioq\"><span class='gt_from_md'><strong>OR</strong></span></span></th>\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_center\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"conf.low_2\"><span data-qmd-base64=\"Kio5NSUgQ0kqKg==\"><span class='gt_from_md'><strong>95% CI</strong></span></span></th>\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_center\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"p.value_2\"><span data-qmd-base64=\"KipwLXZhbHVlKio=\"><span class='gt_from_md'><strong>p-value</strong></span></span></th>\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_center\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"estimate_3\"><span data-qmd-base64=\"KipPUioq\"><span class='gt_from_md'><strong>OR</strong></span></span></th>\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_center\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"conf.low_3\"><span data-qmd-base64=\"Kio5NSUgQ0kqKg==\"><span class='gt_from_md'><strong>95% CI</strong></span></span></th>\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_center\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"p.value_3\"><span data-qmd-base64=\"KipwLXZhbHVlKio=\"><span class='gt_from_md'><strong>p-value</strong></span></span></th>\n    </tr>\n  </thead>\n  <tbody class=\"gt_table_body\">\n    <tr><td headers=\"label\" class=\"gt_row gt_left\">Female</td>\n<td headers=\"estimate_1\" class=\"gt_row gt_center\">0.32</td>\n<td headers=\"conf.low_1\" class=\"gt_row gt_center\">0.25, 0.42</td>\n<td headers=\"p.value_1\" class=\"gt_row gt_center\" style=\"font-weight: bold;\"><0.001</td>\n<td headers=\"estimate_2\" class=\"gt_row gt_center\">0.23</td>\n<td headers=\"conf.low_2\" class=\"gt_row gt_center\">0.17, 0.31</td>\n<td headers=\"p.value_2\" class=\"gt_row gt_center\" style=\"font-weight: bold;\"><0.001</td>\n<td headers=\"estimate_3\" class=\"gt_row gt_center\">0.23</td>\n<td headers=\"conf.low_3\" class=\"gt_row gt_center\">0.17, 0.30</td>\n<td headers=\"p.value_3\" class=\"gt_row gt_center\" style=\"font-weight: bold;\"><0.001</td></tr>\n    <tr><td headers=\"label\" class=\"gt_row gt_left\">Education (years, centered)</td>\n<td headers=\"estimate_1\" class=\"gt_row gt_center\">1.26</td>\n<td headers=\"conf.low_1\" class=\"gt_row gt_center\">1.21, 1.33</td>\n<td headers=\"p.value_1\" class=\"gt_row gt_center\" style=\"font-weight: bold;\"><0.001</td>\n<td headers=\"estimate_2\" class=\"gt_row gt_center\">1.11</td>\n<td headers=\"conf.low_2\" class=\"gt_row gt_center\">1.05, 1.18</td>\n<td headers=\"p.value_2\" class=\"gt_row gt_center\" style=\"font-weight: bold;\"><0.001</td>\n<td headers=\"estimate_3\" class=\"gt_row gt_center\">1.09</td>\n<td headers=\"conf.low_3\" class=\"gt_row gt_center\">1.02, 1.18</td>\n<td headers=\"p.value_3\" class=\"gt_row gt_center\" style=\"font-weight: bold;\">0.016</td></tr>\n    <tr><td headers=\"label\" class=\"gt_row gt_left\">Experience (decades, centered)</td>\n<td headers=\"estimate_1\" class=\"gt_row gt_center\">1.54</td>\n<td headers=\"conf.low_1\" class=\"gt_row gt_center\">1.30, 1.85</td>\n<td headers=\"p.value_1\" class=\"gt_row gt_center\" style=\"font-weight: bold;\"><0.001</td>\n<td headers=\"estimate_2\" class=\"gt_row gt_center\">1.55</td>\n<td headers=\"conf.low_2\" class=\"gt_row gt_center\">1.29, 1.87</td>\n<td headers=\"p.value_2\" class=\"gt_row gt_center\" style=\"font-weight: bold;\"><0.001</td>\n<td headers=\"estimate_3\" class=\"gt_row gt_center\">1.54</td>\n<td headers=\"conf.low_3\" class=\"gt_row gt_center\">1.28, 1.87</td>\n<td headers=\"p.value_3\" class=\"gt_row gt_center\" style=\"font-weight: bold;\"><0.001</td></tr>\n    <tr><td headers=\"label\" class=\"gt_row gt_left\">Experience squared</td>\n<td headers=\"estimate_1\" class=\"gt_row gt_center\">0.79</td>\n<td headers=\"conf.low_1\" class=\"gt_row gt_center\">0.66, 0.95</td>\n<td headers=\"p.value_1\" class=\"gt_row gt_center\" style=\"font-weight: bold;\">0.011</td>\n<td headers=\"estimate_2\" class=\"gt_row gt_center\">0.80</td>\n<td headers=\"conf.low_2\" class=\"gt_row gt_center\">0.66, 0.96</td>\n<td headers=\"p.value_2\" class=\"gt_row gt_center\" style=\"font-weight: bold;\">0.020</td>\n<td headers=\"estimate_3\" class=\"gt_row gt_center\">0.80</td>\n<td headers=\"conf.low_3\" class=\"gt_row gt_center\">0.66, 0.96</td>\n<td headers=\"p.value_3\" class=\"gt_row gt_center\" style=\"font-weight: bold;\">0.019</td></tr>\n    <tr><td headers=\"label\" class=\"gt_row gt_left\">Semi-white-collar</td>\n<td headers=\"estimate_1\" class=\"gt_row gt_center\"><br /></td>\n<td headers=\"conf.low_1\" class=\"gt_row gt_center\"><br /></td>\n<td headers=\"p.value_1\" class=\"gt_row gt_center\"><br /></td>\n<td headers=\"estimate_2\" class=\"gt_row gt_center\">0.86</td>\n<td headers=\"conf.low_2\" class=\"gt_row gt_center\">0.63, 1.18</td>\n<td headers=\"p.value_2\" class=\"gt_row gt_center\">0.4</td>\n<td headers=\"estimate_3\" class=\"gt_row gt_center\">0.87</td>\n<td headers=\"conf.low_3\" class=\"gt_row gt_center\">0.64, 1.19</td>\n<td headers=\"p.value_3\" class=\"gt_row gt_center\">0.4</td></tr>\n    <tr><td headers=\"label\" class=\"gt_row gt_left\">Semi-blue-collar</td>\n<td headers=\"estimate_1\" class=\"gt_row gt_center\"><br /></td>\n<td headers=\"conf.low_1\" class=\"gt_row gt_center\"><br /></td>\n<td headers=\"p.value_1\" class=\"gt_row gt_center\"><br /></td>\n<td headers=\"estimate_2\" class=\"gt_row gt_center\">0.24</td>\n<td headers=\"conf.low_2\" class=\"gt_row gt_center\">0.16, 0.35</td>\n<td headers=\"p.value_2\" class=\"gt_row gt_center\" style=\"font-weight: bold;\"><0.001</td>\n<td headers=\"estimate_3\" class=\"gt_row gt_center\">0.24</td>\n<td headers=\"conf.low_3\" class=\"gt_row gt_center\">0.16, 0.35</td>\n<td headers=\"p.value_3\" class=\"gt_row gt_center\" style=\"font-weight: bold;\"><0.001</td></tr>\n    <tr><td headers=\"label\" class=\"gt_row gt_left\">Elementary</td>\n<td headers=\"estimate_1\" class=\"gt_row gt_center\"><br /></td>\n<td headers=\"conf.low_1\" class=\"gt_row gt_center\"><br /></td>\n<td headers=\"p.value_1\" class=\"gt_row gt_center\"><br /></td>\n<td headers=\"estimate_2\" class=\"gt_row gt_center\">0.11</td>\n<td headers=\"conf.low_2\" class=\"gt_row gt_center\">0.06, 0.22</td>\n<td headers=\"p.value_2\" class=\"gt_row gt_center\" style=\"font-weight: bold;\"><0.001</td>\n<td headers=\"estimate_3\" class=\"gt_row gt_center\">0.12</td>\n<td headers=\"conf.low_3\" class=\"gt_row gt_center\">0.06, 0.22</td>\n<td headers=\"p.value_3\" class=\"gt_row gt_center\" style=\"font-weight: bold;\"><0.001</td></tr>\n    <tr><td headers=\"label\" class=\"gt_row gt_left\">Numeracy (z-score)</td>\n<td headers=\"estimate_1\" class=\"gt_row gt_center\"><br /></td>\n<td headers=\"conf.low_1\" class=\"gt_row gt_center\"><br /></td>\n<td headers=\"p.value_1\" class=\"gt_row gt_center\"><br /></td>\n<td headers=\"estimate_2\" class=\"gt_row gt_center\">1.05</td>\n<td headers=\"conf.low_2\" class=\"gt_row gt_center\">0.90, 1.22</td>\n<td headers=\"p.value_2\" class=\"gt_row gt_center\">0.6</td>\n<td headers=\"estimate_3\" class=\"gt_row gt_center\">1.08</td>\n<td headers=\"conf.low_3\" class=\"gt_row gt_center\">0.90, 1.30</td>\n<td headers=\"p.value_3\" class=\"gt_row gt_center\">0.4</td></tr>\n    <tr><td headers=\"label\" class=\"gt_row gt_left\">Female x Education</td>\n<td headers=\"estimate_1\" class=\"gt_row gt_center\"><br /></td>\n<td headers=\"conf.low_1\" class=\"gt_row gt_center\"><br /></td>\n<td headers=\"p.value_1\" class=\"gt_row gt_center\"><br /></td>\n<td headers=\"estimate_2\" class=\"gt_row gt_center\"><br /></td>\n<td headers=\"conf.low_2\" class=\"gt_row gt_center\"><br /></td>\n<td headers=\"p.value_2\" class=\"gt_row gt_center\"><br /></td>\n<td headers=\"estimate_3\" class=\"gt_row gt_center\">1.05</td>\n<td headers=\"conf.low_3\" class=\"gt_row gt_center\">0.94, 1.17</td>\n<td headers=\"p.value_3\" class=\"gt_row gt_center\">0.4</td></tr>\n    <tr><td headers=\"label\" class=\"gt_row gt_left\">Female x Numeracy</td>\n<td headers=\"estimate_1\" class=\"gt_row gt_center\"><br /></td>\n<td headers=\"conf.low_1\" class=\"gt_row gt_center\"><br /></td>\n<td headers=\"p.value_1\" class=\"gt_row gt_center\"><br /></td>\n<td headers=\"estimate_2\" class=\"gt_row gt_center\"><br /></td>\n<td headers=\"conf.low_2\" class=\"gt_row gt_center\"><br /></td>\n<td headers=\"p.value_2\" class=\"gt_row gt_center\"><br /></td>\n<td headers=\"estimate_3\" class=\"gt_row gt_center\">0.92</td>\n<td headers=\"conf.low_3\" class=\"gt_row gt_center\">0.67, 1.27</td>\n<td headers=\"p.value_3\" class=\"gt_row gt_center\">0.6</td></tr>\n  </tbody>\n  <tfoot class=\"gt_sourcenotes\">\n    <tr>\n      <td class=\"gt_sourcenote\" colspan=\"10\"><span data-qmd-base64=\"QWJicmV2aWF0aW9uczogQ0kgPSBDb25maWRlbmNlIEludGVydmFsLCBPUiA9IE9kZHMgUmF0aW8=\"><span class='gt_from_md'>Abbreviations: CI = Confidence Interval, OR = Odds Ratio</span></span></td>\n    </tr>\n  </tfoot>\n  \n</table>\n</div>\n```\n\n:::\n:::\n\n\n::: {.callout-tip}\n## Writing Tip\nFor logistic regression, always present **odds ratios** (not raw log-odds\ncoefficients) in the publication table. Set `exponentiate = TRUE` in\n`tbl_regression()`. The confidence intervals are also exponentiated, so they\nare on the OR scale. An OR whose 95% CI includes 1.00 is not significant at\n$\\alpha = .05$.\n:::\n\n\n### Likelihood Ratio Tests {#sec-logistic-ex-lr-tests}\n\nWe compare nested models using **likelihood ratio (LR) tests**, the logistic\nregression analogue of the incremental $F$-test used in linear regression.\n\n#### LR Test: Model 1 vs. Model 2\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# LR test: Does adding occupation + numeracy improve fit?\nanova(logit1, logit2, test = \"Chisq\")\n```\n\n::: {.cell-output-display}\n<div class=\"kable-table\">\n\n| Resid. Df| Resid. Dev| Df| Deviance| Pr(>Chi)|\n|---------:|----------:|--:|--------:|--------:|\n|      1352|   1576.653| NA|       NA|       NA|\n|      1348|   1481.565|  4|  95.0876|        0|\n\n</div>\n:::\n:::\n\n\nThe likelihood ratio test is highly significant ($p < .001$), confirming\nthat occupation and numeracy jointly add significant predictive power beyond\nthe baseline human capital variables. This answers **RQ2** in the\naffirmative: occupational classification is a strong predictor of\nsupervisory status.\n\n#### LR Test: Model 2 vs. Model 3\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# LR test: Do gender interactions improve fit?\nanova(logit2, logit3, test = \"Chisq\")\n```\n\n::: {.cell-output-display}\n<div class=\"kable-table\">\n\n| Resid. Df| Resid. Dev| Df|  Deviance|  Pr(>Chi)|\n|---------:|----------:|--:|---------:|---------:|\n|      1348|   1481.565| NA|        NA|        NA|\n|      1346|   1480.891|  2| 0.6747079| 0.7136562|\n\n</div>\n:::\n:::\n\n\nThe likelihood ratio test for the two interaction terms is **not\nsignificant** ($p > .05$), indicating that the gender interaction block does\nnot meaningfully improve model fit. This answers **RQ3**: the associations of\neducation and numeracy with supervisory status do **not** differ significantly\nby gender.\n\n\n### Collinearity Diagnostics {#sec-logistic-ex-vif}\n\nWe check for multicollinearity by computing variance inflation factors\n(VIFs) for the full model.\n\n\n::: {#tbl-logistic-vif .cell tbl-cap='Variance Inflation Factors for Logistic Model 3'}\n\n```{.r .cell-code}\ncar::vif(logit3) |>\n  as.data.frame() |>\n  setNames(\"VIF\") |>\n  knitr::kable(digits = 2)\n```\n\n::: {.cell-output-display}\n\n\n|             |  VIF|\n|:------------|----:|\n|female       | 1.27|\n|schyrs_c     | 2.52|\n|exper_c      | 1.22|\n|exper2_c     | 1.10|\n|semiwhite    | 1.47|\n|semiblue     | 1.79|\n|elementary   | 1.22|\n|numeracy     | 2.03|\n|fem_schyrs_c | 2.02|\n|fem_numeracy | 1.81|\n\n\n:::\n:::\n\n\nAll VIF values are well below 5, indicating that multicollinearity is not a\nconcern. The interaction terms (`fem_schyrs_c`, `fem_numeracy`) have modest\nVIFs because we used mean-centered predictors to construct them.\n\n::: {.callout-note}\n## VIF Guidelines\n- VIF < 5: No concern\n- VIF 5--10: Moderate concern; consider centering or combining predictors\n- VIF > 10: Serious multicollinearity; affected coefficients may be unstable\n:::\n\n\n### Predicted Probabilities {#sec-logistic-ex-predicted}\n\nThe **predicted probability graph** is the key deliverable for the logistic\nregression project. Unlike odds ratios, predicted probabilities are on an\nintuitive 0--1 scale that communicates practical significance directly.\n\n#### Predicted Probability Graph: Education by Gender\n\n@fig-logistic-predicted shows the predicted probability of holding a\nsupervisory position as a function of years of education (centered),\nseparately for men and women.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nplot_predictions(logit2,\n                 condition = list(\"schyrs_c\", \"female\"),\n                 type = \"response\") +\n  labs(\n    x = \"Years of Education (centered)\",\n    y = \"Predicted P(Manager)\",\n    color = \"Gender\",\n    fill = \"Gender\",\n    title = \"Predicted Probability of Supervisory Status\",\n    subtitle = \"By education level and gender (Model 2)\"\n  ) +\n  scale_color_manual(\n    values = c(ber640_colors[\"primary\"], ber640_colors[\"secondary\"]),\n    labels = c(\"Male\", \"Female\")\n  ) +\n  scale_fill_manual(\n    values = c(ber640_colors[\"primary\"], ber640_colors[\"secondary\"]),\n    labels = c(\"Male\", \"Female\")\n  )\n```\n\n::: {.cell-output-display}\n![Predicted Probability of Being a Manager by Education and Gender](ch07-logistic-results_files/figure-html/fig-logistic-predicted-1.png){#fig-logistic-predicted fig-alt='Predicted probability curves showing the probability of being a manager increases with years of education for both genders, following an S-shaped logistic curve. Males have a consistently higher predicted probability than females at every education level, with a gap of approximately 25 to 30 percentage points.' width=2100}\n:::\n:::\n\n\nThe predicted probability graph reveals two important patterns:\n\n1. **Gender gap:** At every level of education, men have a substantially\n   higher predicted probability of being a manager than women. The gap is\n   consistent across the education range.\n2. **Education gradient:** Higher education is associated with a higher\n   probability of being a manager for both genders. The S-shaped logistic\n   curve means that the marginal effect of education varies depending on\n   where a worker starts on the probability scale.\n\n#### Predicted Probability Graph: Education by Occupation\n\n@fig-logistic-predicted-occ shows predicted probabilities across education\nlevels for each occupational category.\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Create an occupation factor for plotting\npiaac <- piaac |>\n  mutate(\n    occ_label = case_when(\n      semiwhite == 0 & semiblue == 0 & elementary == 0 ~ \"Skilled\",\n      semiwhite == 1 ~ \"Semi-white\",\n      semiblue == 1  ~ \"Semi-blue\",\n      elementary == 1 ~ \"Elementary\"\n    ),\n    occ_label = factor(occ_label,\n                       levels = c(\"Skilled\", \"Semi-white\",\n                                  \"Semi-blue\", \"Elementary\"))\n  )\n\n# Refit Model 2 with occ_label for cleaner plotting\nlogit2_plot <- glm(manager ~ female + schyrs_c + exper_c + exper2_c +\n                     occ_label + numeracy,\n                   data = piaac, family = binomial)\n\nplot_predictions(logit2_plot,\n                 condition = list(\"schyrs_c\", \"occ_label\"),\n                 type = \"response\") +\n  labs(\n    x = \"Years of Education (centered)\",\n    y = \"Predicted P(Manager)\",\n    color = \"Occupation\",\n    fill = \"Occupation\",\n    title = \"Predicted Probability of Supervisory Status\",\n    subtitle = \"By education level and occupation (Model 2)\"\n  ) +\n  scale_color_manual(values = unname(ber640_colors[1:4])) +\n  scale_fill_manual(values = unname(ber640_colors[1:4]))\n```\n\n::: {.cell-output-display}\n![Predicted Probability of Being a Manager by Education and Occupation](ch07-logistic-results_files/figure-html/fig-logistic-predicted-occ-1.png){#fig-logistic-predicted-occ fig-alt='Predicted probability curves for four occupational categories showing the probability of being a manager as a function of education. Skilled workers have the highest predicted probability at every education level, followed by semi-white-collar, semi-blue-collar, and elementary workers. The occupational gap is much larger than the education gradient.' width=2100}\n:::\n:::\n\n\nThe occupational gradient in predicted probabilities is striking: skilled\nworkers have the highest predicted probability of being managers at every\neducation level, while elementary workers have the lowest. The gap between\noccupational categories is much larger than the gap between education levels,\nhighlighting the dominant role of occupation.\n\n#### Table of Predicted Probabilities at Key Values\n\n@tbl-logistic-pred-table presents predicted probabilities at specific\ncombinations of predictor values to facilitate interpretation.\n\n\n::: {#tbl-logistic-pred-table .cell tbl-cap='Predicted Probabilities of Supervisory Status at Selected Values'}\n\n```{.r .cell-code}\n# Create a prediction grid\npred_grid <- predictions(\n  logit2,\n  newdata = datagrid(\n    female   = c(0, 1),\n    schyrs_c = c(-4, 0, 4),\n    exper_c  = 0,\n    exper2_c = 0,\n    semiwhite = 0,\n    semiblue  = 0,\n    elementary = 0,\n    numeracy  = 0\n  ),\n  type = \"response\"\n)\n\npred_grid |>\n  as.data.frame() |>\n  mutate(\n    Gender = ifelse(female == 0, \"Male\", \"Female\"),\n    Education = case_when(\n      schyrs_c == -4 ~ \"Mean - 4 yrs\",\n      schyrs_c ==  0 ~ \"Mean\",\n      schyrs_c ==  4 ~ \"Mean + 4 yrs\"\n    ),\n    `P(Manager)` = round(estimate, 3),\n    `95% CI` = paste0(\"[\", round(conf.low, 3), \", \",\n                      round(conf.high, 3), \"]\")\n  ) |>\n  select(Gender, Education, `P(Manager)`, `95% CI`) |>\n  kable(align = \"llrr\")\n```\n\n::: {.cell-output-display}\n\n\n|Gender |Education    | P(Manager)|         95% CI|\n|:------|:------------|----------:|--------------:|\n|Male   |Mean - 4 yrs |      0.602| [0.496, 0.707]|\n|Male   |Mean         |      0.700| [0.638, 0.761]|\n|Male   |Mean + 4 yrs |      0.783| [0.732, 0.833]|\n|Female |Mean - 4 yrs |      0.259|  [0.178, 0.34]|\n|Female |Mean         |      0.351| [0.284, 0.417]|\n|Female |Mean + 4 yrs |      0.455| [0.375, 0.535]|\n\n\n:::\n:::\n\n\nThe predicted probability table makes the gender gap concrete. For example,\na male skilled worker with average education, average experience, and\naverage numeracy has a predicted probability of about 0.55--0.60 of being a\nmanager, while a comparable female worker has a predicted probability of\nonly about 0.25--0.30. This is a 25--30 percentage-point gap in the\nprobability of holding a supervisory position.\n\n::: {.callout-tip}\n## Writing Tip\nPredicted probability tables are extremely useful for communicating logistic\nregression results to non-technical audiences. By plugging in specific,\nmeaningful values for the predictors, you translate abstract odds ratios\ninto concrete probabilities that readers can immediately grasp.\n:::\n\n\n### Model Fit Summary {#sec-logistic-ex-fit}\n\nWe summarize the overall fit of each model using AIC, BIC, and McFadden's\npseudo-$R^2$.\n\n\n::: {#tbl-logistic-fit .cell tbl-cap='Model Fit Statistics for the Three Logistic Regression Models'}\n\n```{.r .cell-code}\n# Null model for pseudo-R2 calculation\nlogit_null <- glm(manager ~ 1, data = piaac, family = binomial)\nll_null <- logLik(logit_null)\n\nfit_table <- tibble::tibble(\n  Model = c(\"Model 1\", \"Model 2\", \"Model 3\"),\n  AIC = c(AIC(logit1), AIC(logit2), AIC(logit3)),\n  BIC = c(BIC(logit1), BIC(logit2), BIC(logit3)),\n  `Log-Lik` = c(as.numeric(logLik(logit1)),\n                as.numeric(logLik(logit2)),\n                as.numeric(logLik(logit3))),\n  `McFadden R2` = c(\n    1 - as.numeric(logLik(logit1)) / as.numeric(ll_null),\n    1 - as.numeric(logLik(logit2)) / as.numeric(ll_null),\n    1 - as.numeric(logLik(logit3)) / as.numeric(ll_null)\n  )\n) |>\n  mutate(across(AIC:BIC, ~ round(.x, 1)),\n         `Log-Lik` = round(`Log-Lik`, 1),\n         `McFadden R2` = round(`McFadden R2`, 3))\n\nkable(fit_table, align = \"lrrrr\")\n```\n\n::: {.cell-output-display}\n\n\n|Model   |    AIC|    BIC| Log-Lik| McFadden R2|\n|:-------|------:|------:|-------:|-----------:|\n|Model 1 | 1586.7| 1612.7|  -788.3|       0.149|\n|Model 2 | 1499.6| 1546.5|  -740.8|       0.200|\n|Model 3 | 1502.9| 1560.2|  -740.4|       0.201|\n\n\n:::\n:::\n\n\nModel 2 shows a substantial improvement over Model 1 (lower AIC and BIC,\nhigher pseudo-$R^2$), confirming the importance of occupational\nclassification. Model 3 adds only a negligible improvement over Model 2,\nconsistent with the nonsignificant interaction terms.\n\n\n## Part 6: Discussion {#sec-logistic-ex-part6}\n\n::: {.callout-important}\n## Guideline Reminder --- Part 6\nSummarize your key findings, answer each research question directly, discuss\nat least 2--3 limitations, and note implications. This is where you show\nthat you understand what the numbers mean.\n:::\n\n### Summary of Key Findings {#sec-logistic-ex-findings}\n\nThis study examined the determinants of supervisory status among Korean\nfull-time workers using a series of nested logistic regression models\napplied to PIAAC Korea data ($N = 1{,}357$). The results yield three main\nfindings.\n\n**RQ1: Education and experience predict supervisory status.** Both years of\neducation and work experience are significant predictors of the likelihood\nof holding a managerial position. Each additional year of education is\nassociated with approximately a 26% increase in the odds of being a manager\nin the baseline model (Model 1). Work experience shows the expected\nconcave pattern: the odds of being a manager increase with experience but\nat a diminishing rate. These results are consistent with human capital\ntheory --- more educated and experienced workers are more likely to be\npromoted to supervisory roles.\n\n**RQ2: Occupation is a dominant predictor; numeracy is not.** Occupational\nclassification and numeracy were added as a block in Model 2. The\nlikelihood ratio test confirmed that this block significantly improves model\nfit ($p < .001$). However, the improvement is driven almost entirely by\n**occupation**, not numeracy. Relative to **Skilled** workers (the reference\ncategory), semi-blue-collar workers have about 76% lower odds and elementary\nworkers have about 89% lower odds of being managers. In contrast, numeracy\nproficiency is **not** a significant predictor of supervisory status after\ncontrolling for education, experience, and occupation. This is an important\nfinding: cognitive skills predict *earnings* (as shown in Project 1) but\ndo not independently predict *career advancement* to managerial positions.\n\n**RQ3: Gender interactions are not significant.** The interaction terms\nbetween gender and education ($p > .05$) and gender and numeracy ($p > .05$)\nare both nonsignificant. The likelihood ratio test comparing Model 2 and\nModel 3 also fails to reject the null hypothesis. The returns to education\nand numeracy do not differ between men and women in predicting supervisory\nstatus.\n\n### The Persistent Gender Gap {#sec-logistic-ex-gender-gap}\n\nOne of the most striking findings is the large and persistent gender gap in\nsupervisory status. Across all three models, women have approximately **68%\nlower odds** of being managers compared with men who have the same\neducation, experience, occupation, and cognitive skills. Translated into\npredicted probabilities, this means that a woman with identical\nqualifications to a male counterpart has a 25--30 percentage-point lower\nprobability of holding a supervisory position.\n\nThis finding parallels the large gender earnings gap documented in Project 1\nand is consistent with the well-documented underrepresentation of women in\nleadership positions in South Korea. The fact that the gap persists after\ncontrolling for human capital, occupation, and cognitive skills suggests\nthat it reflects structural factors --- such as organizational culture,\npromotion practices, and work-family constraints --- that our model cannot\ncapture.\n\n### Key Contrast: Linear vs. Logistic Regression Findings {#sec-logistic-ex-contrast}\n\nComparing the results across the two projects yields an important\nsubstantive insight:\n\n| Finding | Project 1 (Earnings) | Project 2 (Manager Status) |\n|---------|---------------------|---------------------------|\n| Education | Significant | Significant |\n| Experience | Significant (concave) | Significant (concave) |\n| Occupation | Strong earnings gradient | Strong managerial gradient |\n| **Numeracy** | **Significant** ($p < .001$) | **Not significant** |\n| Gender gap | ~33% lower earnings | ~68% lower odds |\n| Gender interactions | Marginally nonsignificant | Not significant |\n\n: Comparison of linear and logistic regression findings. {#tbl-project-comparison}\n\nThe most notable contrast is that **cognitive skills (numeracy) matter for\nearnings but not for career advancement**. This suggests that the labor\nmarket rewards cognitive skills through higher wages but that the promotion\nprocess to supervisory roles depends more on occupational context and other\nfactors (seniority, organizational fit, network ties) than on measured\ncognitive ability.\n\n### Limitations {#sec-logistic-ex-limitations}\n\nSeveral limitations should be noted when interpreting these results.\n\n1. **Cross-sectional design.** Because PIAAC is a cross-sectional survey,\n   we cannot determine whether education and experience *cause* promotion\n   to supervisory roles. The observed associations may reflect selection\n   effects (e.g., workers who seek managerial positions may also invest more\n   in education).\n\n2. **Single-country sample.** Our analysis focuses on South Korea, which\n   has distinctive labor market institutions, a strong seniority system, and\n   specific cultural norms about gender and leadership. The findings may not\n   generalize to other countries.\n\n3. **Binary simplification.** The `manager` variable is a simple binary\n   indicator of supervisory responsibility. It does not capture the *level*\n   of management (e.g., front-line supervisor vs. senior executive) or the\n   *number* of subordinates, which would provide a more nuanced picture.\n\n4. **Omitted variables.** Important predictors such as tenure at the\n   current firm, industry, firm size, and personality traits are not\n   available in the PIAAC data. These factors likely influence promotion\n   decisions and could confound our estimates.\n\n### Implications {#sec-logistic-ex-implications}\n\nDespite these limitations, the findings have practical implications:\n\n- The **nonsignificance of numeracy** for supervisory status suggests that\n  improving workers' cognitive skills alone will not increase their chances\n  of promotion. Organizational factors and social capital may be more\n  relevant for career advancement.\n- The **dominant role of occupation** highlights the importance of initial\n  occupational placement. Workers who enter skilled occupations have much\n  higher odds of eventually becoming managers, regardless of their education\n  or cognitive skills. Career counseling and vocational training may be\n  important levers.\n- The **persistent gender gap** in managerial status, even after extensive\n  controls, points to the need for structural interventions such as\n  mentoring programs, leadership development initiatives for women, and\n  organizational policies that address implicit bias in promotion decisions.\n\n\n## Submission Checklist {#sec-logistic-ex-checklist}\n\n::: {.callout-important}\n## Project 2 Submission Checklist\nBefore submitting your Logistic Regression Results & Discussion, confirm\nthat you have completed all of the following:\n\n- [ ] **Cross-tabulations** of the outcome with key categorical predictors,\n  with row/column percentages and chi-square tests\n- [ ] **Descriptive statistics** for continuous variables by outcome group,\n  with significance tests\n- [ ] **Exploratory visualizations** (bar charts, boxplots) with written\n  interpretations\n- [ ] **Logistic regression models** fitted and summarized with `summary()`\n  output\n- [ ] **Odds ratio table** using `tbl_regression(exponentiate = TRUE)` for\n  all models, merged into a single publication-style table\n- [ ] **Odds ratio interpretation** for every predictor --- direction,\n  magnitude, significance, and substantive meaning\n- [ ] **Likelihood ratio tests** comparing nested models to evaluate\n  incremental contributions\n- [ ] **Predicted probability graph** (the key deliverable) showing the\n  relationship between a key predictor and the probability of the outcome,\n  stratified by at least one grouping variable\n- [ ] **Predicted probability table** at selected predictor values for\n  concrete interpretation\n- [ ] **VIF check** for multicollinearity\n- [ ] **Model fit summary** (AIC, BIC, pseudo-$R^2$)\n- [ ] **Discussion** that answers each research question, compares findings\n  with the linear regression project, notes limitations, and discusses\n  implications\n- [ ] All code runs without errors (`eval: true` for all code chunks)\n- [ ] All figures and tables are labeled, captioned, and cross-referenced\n:::\n",
    "supporting": [
      "ch07-logistic-results_files"
    ],
    "filters": [
      "rmarkdown/pagebreak.lua"
    ],
    "includes": {},
    "engineDependencies": {},
    "preserve": {},
    "postProcess": true
  }
}