{
  "hash": "00a39a8ff6a3c025a0a03c405f12588a",
  "result": {
    "engine": "knitr",
    "markdown": "---\ntitle: \"Homework 2: Simple Regression with a Dummy Variable\"\n---\n\n\n\n\n## Overview\n\n::: {.callout-note}\n## Learning Objectives\n- Estimate and interpret regression with a single dummy predictor\n- Understand the equivalence of regression t-test and independent samples t-test\n- Identify Root MSE as the pooled within-group standard deviation\n- **Related:** Chapter 1: *Simple Linear Regression* and Chapter 2: *ANCOVA* (in Lecture Notes)\n:::\n\n::: {.callout-tip}\n## Stata-to-R Translation\n| Stata Command | R Equivalent | Used In |\n|:---|:---|:---|\n| `regress wleread female if usa==1` | `lm(wleread ~ female, data = pisa_us)` | Problem 1 |\n| `twoway lfit wleread female` | `ggplot() + geom_smooth(method = \"lm\")` | Problem 3 |\n| `ttest wleread, by(female)` | `t.test(wleread ~ female, var.equal = TRUE)` | Problem 5 |\n:::\n\n**Dataset:** `pisa2000` from the `regdatasets` package (US subset, N = 1,020)\n\n## Setup\n\n\n::: {.cell}\n\n```{.r .cell-code  code-fold=\"true\" code-summary=\"Show R Code\"}\ndata(pisa2000)\npisa_us <- pisa2000 |> filter(usa == 1)\n```\n:::\n\n\n## Problem 1\n\n### Problem Statement\n\n> Run the regression of `wleread` on `female` for American students.\n\n::: {.panel-tabset}\n#### Solution\n\n\n::: {.cell}\n\n```{.r .cell-code  code-fold=\"true\" code-summary=\"Show R Code\"}\n# Fit simple regression: reading score on female dummy\nmodel1 <- lm(wleread ~ female, data = pisa_us)\n\n# Display full regression summary\nsummary(model1)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\nCall:\nlm(formula = wleread ~ female, data = pisa_us)\n\nResiduals:\n     Min       1Q   Median       3Q      Max \n-312.178  -57.358    4.921   63.381  252.242 \n\nCoefficients:\n            Estimate Std. Error t value Pr(>|t|)    \n(Intercept)  507.859      4.427 114.725  < 2e-16 ***\nfemale        27.699      5.958   4.649 3.78e-06 ***\n---\nSignif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1\n\nResidual standard error: 94.63 on 1018 degrees of freedom\nMultiple R-squared:  0.02079,\tAdjusted R-squared:  0.01982 \nF-statistic: 21.61 on 1 and 1018 DF,  p-value: 3.78e-06\n```\n\n\n:::\n\n```{.r .cell-code  code-fold=\"true\" code-summary=\"Show R Code\"}\n# Tidy coefficient table with confidence intervals\ntidy_model(model1)\n```\n\n::: {.cell-output-display}\n<div class=\"kable-table\">\n\n|term        | estimate| std.error| statistic| p.value| conf.low| conf.high|\n|:-----------|--------:|---------:|---------:|-------:|--------:|---------:|\n|(Intercept) | 507.8590|    4.4268|  114.7246|       0| 499.1724|  516.5456|\n|female      |  27.6986|    5.9584|    4.6486|       0|  16.0064|   39.3908|\n\n</div>\n:::\n:::\n\n\n- **Sample size:** $N = 1{,}020$ US students from the PISA 2000 dataset.\n- **Model fit:** $F(1, 1018) = 21.61$, $p < .001$, indicating that `female` is a statistically significant predictor of reading scores.\n- **Variance explained:** $R^2 = 0.0208$ --- the `female` dummy variable accounts for approximately 2.1% of the variance in reading scores. While statistically significant, this is a small effect.\n- **Root MSE:** $\\hat{\\sigma} = 94.633$, which estimates the standard deviation of reading scores within each gender group (assuming equal variances).\n- **Regression equation:**\n\n$$\\widehat{\\text{wleread}} = 507.86 + 27.70 \\times \\text{female}$$\n\n#### Code Explanation\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Fit simple regression: reading score on female dummy\nmodel1 <- lm(wleread ~ female, data = pisa_us)\n\n# Display full regression summary\nsummary(model1)\n\n# Tidy coefficient table with confidence intervals\ntidy_model(model1)\n```\n:::\n\n\n- `lm(wleread ~ female, data = pisa_us)`: Fits an OLS regression predicting reading scores (`wleread`) from the dummy variable `female` (coded 0 = male, 1 = female). With a single dummy predictor, this is equivalent to comparing two group means.\n- `summary(model1)`: Produces the full regression output including coefficients, standard errors, $t$-statistics, $p$-values, $R^2$, adjusted $R^2$, $F$-statistic, and residual standard error (Root MSE).\n- `tidy_model(model1)`: A helper function (defined in `_common.R`) that calls `broom::tidy()` with confidence intervals and rounds numeric values to 4 decimal places for clean display.\n\n:::\n\n::: {.callout-tip}\n## Key Takeaway\nWhen the predictor is a dummy variable (0/1), the regression intercept equals the mean of the reference group (males), and the slope equals the difference in means between the two groups. This makes dummy variable regression equivalent to a two-sample comparison of means.\n:::\n\n## Problem 2\n\n### Problem Statement\n\n> Report and interpret the estimated regression coefficients and their standard errors.\n\n::: {.panel-tabset}\n#### Solution\n\n\n::: {.cell}\n\n```{.r .cell-code  code-fold=\"true\" code-summary=\"Show R Code\"}\n# Extract coefficients and standard errors\ncoefs <- tidy_model(model1)\ncoefs\n```\n\n::: {.cell-output-display}\n<div class=\"kable-table\">\n\n|term        | estimate| std.error| statistic| p.value| conf.low| conf.high|\n|:-----------|--------:|---------:|---------:|-------:|--------:|---------:|\n|(Intercept) | 507.8590|    4.4268|  114.7246|       0| 499.1724|  516.5456|\n|female      |  27.6986|    5.9584|    4.6486|       0|  16.0064|   39.3908|\n\n</div>\n:::\n\n```{.r .cell-code  code-fold=\"true\" code-summary=\"Show R Code\"}\n# Verify: intercept = male mean, slope = female - male difference\npisa_us |>\n  group_by(female) |>\n  summarise(\n    n = n(),\n    mean_read = mean(wleread),\n    sd_read = sd(wleread),\n    .groups = \"drop\"\n  )\n```\n\n::: {.cell-output-display}\n<div class=\"kable-table\">\n\n| female|   n| mean_read|  sd_read|\n|------:|---:|---------:|--------:|\n|      0| 457|  507.8590| 99.19631|\n|      1| 563|  535.5576| 90.76287|\n\n</div>\n:::\n:::\n\n\n**Intercept** ($\\hat{\\beta}_0 = 507.86$, $\\text{SE} = 4.43$):\n\n- The intercept is the predicted reading score when `female` $= 0$, i.e., the **mean reading score for male students**.\n- Male US students scored an average of $507.9$ points on the PISA reading assessment.\n- The standard error of $4.43$ is the standard deviation of $\\hat{\\beta}_0$ across hypothetical repeated samples. It quantifies the precision of our estimate of the male mean.\n\n**Slope** ($\\hat{\\beta}_1 = 27.70$, $\\text{SE} = 5.96$):\n\n- The slope is the **difference in mean reading scores** between female and male students: $\\bar{Y}_{\\text{female}} - \\bar{Y}_{\\text{male}} = 27.7$ points.\n- Female US students scored, on average, $27.7$ points higher than male students on the PISA reading assessment.\n- The standard error of $5.96$ is the standard deviation of $\\hat{\\beta}_1$ across hypothetical repeated samples. It reflects how precisely we have estimated the gender gap in reading scores.\n\n**What standard errors represent:**\n\n- Standard errors are the **standard deviations of the sampling distributions** of the estimated coefficients.\n- If we could draw many independent random samples of $N = 1{,}020$ US students and fit this regression each time, the standard errors tell us how much $\\hat{\\beta}_0$ and $\\hat{\\beta}_1$ would vary from sample to sample.\n- Smaller standard errors indicate more precise estimates; larger standard errors indicate greater uncertainty.\n\n#### Code Explanation\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Extract coefficients and standard errors\ncoefs <- tidy_model(model1)\ncoefs\n\n# Verify: intercept = male mean, slope = female - male difference\npisa_us |>\n  group_by(female) |>\n  summarise(\n    n = n(),\n    mean_read = mean(wleread),\n    sd_read = sd(wleread),\n    .groups = \"drop\"\n  )\n```\n:::\n\n\n- `tidy_model(model1)`: Extracts the coefficient table with estimates, standard errors, test statistics, $p$-values, and 95% confidence intervals in a tidy data frame.\n- `group_by(female) |> summarise(...)`: Computes descriptive statistics by gender group to verify that the regression intercept matches the male mean and the slope matches the difference in means.\n- `mean(wleread)`: Computes the group mean of reading scores, which should match $\\hat{\\beta}_0$ for males and $\\hat{\\beta}_0 + \\hat{\\beta}_1$ for females.\n- `sd(wleread)`: Computes the within-group standard deviation, which is related to (but not identical to) the Root MSE from the regression.\n\n:::\n\n::: {.callout-tip}\n## Key Takeaway\nIn a regression with a single dummy predictor, the standard errors have a direct interpretation: $\\text{SE}(\\hat{\\beta}_0)$ measures uncertainty about the reference group mean, and $\\text{SE}(\\hat{\\beta}_1)$ measures uncertainty about the difference between groups. These are the standard deviations of the estimates if we could repeat the study many times.\n:::\n\n## Problem 3\n\n### Problem Statement\n\n> Graph the regression relationship.\n\n::: {.panel-tabset}\n#### Simple Version\n\n\n::: {.cell}\n\n```{.r .cell-code  code-fold=\"true\" code-summary=\"Show R Code\"}\n# Simple version: fitted line plot\nggplot(pisa_us, aes(x = female, y = wleread)) +\n  geom_jitter(alpha = 0.1, width = 0.1) +\n  geom_smooth(method = \"lm\", se = FALSE, color = \"blue\") +\n  scale_x_continuous(breaks = c(0, 1), labels = c(\"Male\", \"Female\")) +\n  labs(x = \"Gender\", y = \"Reading Score\",\n       title = \"Regression of Reading Score on Gender\")\n```\n\n::: {.cell-output-display}\n![Regression of reading score on gender with jittered data points.](hw02-dummy-regression_files/figure-html/hw02-q3-plot-simple-1.png){fig-alt='Scatter plot with jittered points showing reading scores for males (x equals 0) and females (x equals 1). A blue regression line connects the two group means, rising from about 508 for males to about 536 for females, indicating a 28-point gender gap.' width=2400}\n:::\n:::\n\n\n#### Detailed Version\n\n\n::: {.cell}\n\n```{.r .cell-code  code-fold=\"true\" code-summary=\"Show R Code\"}\n# Extract fitted values for plotting\nb0 <- coef(model1)[1]  # intercept (male mean)\nb1 <- coef(model1)[2]  # slope (female - male difference)\n\n# Create data frame for the two group means\nfitted_points <- tibble(\n  female = c(0, 1),\n  fitted = c(b0, b0 + b1),\n  label = c(\n    paste0(\"Males: \", round(b0, 1)),\n    paste0(\"Females: \", round(b0 + b1, 1))\n  )\n)\n\n# Plot the fitted regression line with group means\nggplot(fitted_points, aes(x = female, y = fitted)) +\n  # Regression line connecting the two means\n  geom_line(\n    color = ber640_colors[\"accent\"],\n    linewidth = 1.2\n  ) +\n  # Points at each group mean\n  geom_point(\n    size = 5,\n    color = ber640_colors[\"primary\"]\n  ) +\n  # Labels for each point\n  geom_label(\n    aes(label = label),\n    vjust = -1.2,\n    size = 4.5,\n    fontface = \"bold\",\n    color = ber640_colors[\"primary\"],\n    fill = \"white\",\n    label.padding = unit(0.4, \"lines\")\n  ) +\n  # Annotate the slope (difference)\n  annotate(\n    \"segment\",\n    x = 0.5, xend = 0.5,\n    y = b0, yend = b0 + b1,\n    color = ber640_colors[\"secondary\"],\n    linewidth = 0.8,\n    linetype = \"dashed\"\n  ) +\n  annotate(\n    \"text\",\n    x = 0.55, y = b0 + b1 / 2,\n    label = paste0(\"Difference = \", round(b1, 1)),\n    hjust = 0, size = 4,\n    color = ber640_colors[\"secondary\"],\n    fontface = \"italic\"\n  ) +\n  # Axis formatting\n  scale_x_continuous(\n    breaks = c(0, 1),\n    labels = c(\"0\\n(Male)\", \"1\\n(Female)\"),\n    limits = c(-0.3, 1.5)\n  ) +\n  scale_y_continuous(\n    limits = c(480, 560)\n  ) +\n  labs(\n    title = \"Regression of Reading Score on Gender\",\n    subtitle = \"PISA 2000, US Students (N = 1,020)\",\n    x = \"Female (Dummy Variable)\",\n    y = \"Predicted Reading Score (wleread)\"\n  )\n```\n\n::: {.cell-output-display}\n![Regression of reading score on gender with annotated group means.](hw02-dummy-regression_files/figure-html/hw02-q3-plot-1.png){fig-alt='Two large points connected by a blue line showing male mean reading score of 507.9 at x equals 0 and female mean of 535.6 at x equals 1. A dashed red vertical segment at x equals 0.5 indicates the 27.7-point difference between groups.' width=2400}\n:::\n:::\n\n\n:::\n\n- **The plot displays the fitted regression line** connecting the predicted mean reading score for males ($x = 0$, $\\hat{Y} = 507.9$) to the predicted mean for females ($x = 1$, $\\hat{Y} = 535.6$).\n- **The slope of the line** represents the estimated gender gap: female students scored $27.7$ points higher on average.\n- **With a dummy predictor, the \"regression line\" is simply two points** --- the means of the two groups connected by a straight line. This highlights that dummy variable regression is fundamentally a comparison of group means.\n\n::: {.callout-tip}\n## Key Takeaway\nWith a dummy variable predictor, the regression \"line\" is just two points connected by a segment. The plot makes the regression equation tangible: the intercept is the left point (reference group mean) and the slope is the vertical rise to the right point (comparison group mean). This visual reinforces why dummy variable regression is simply a comparison of two group means expressed as a linear model.\n:::\n\n## Problem 4\n\n### Problem Statement\n\n> Test the null hypothesis that `female` has no effect on `wleread` at the 1% significance level.\n\n::: {.panel-tabset}\n#### Solution\n\n\n::: {.cell}\n\n```{.r .cell-code  code-fold=\"true\" code-summary=\"Show R Code\"}\n# Extract coefficient table from the regression model\ncoef_table <- summary(model1)$coefficients\n\n# Pull out the t-statistic and p-value for the female coefficient\nt_stat <- coef_table[\"female\", \"t value\"]\np_value <- coef_table[\"female\", \"Pr(>|t|)\"]\ndf_error <- model1$df.residual\n\n# Display the test results\ncat(\"Hypothesis Test for the Effect of Female on Reading Score\\n\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nHypothesis Test for the Effect of Female on Reading Score\n```\n\n\n:::\n\n```{.r .cell-code  code-fold=\"true\" code-summary=\"Show R Code\"}\ncat(\"=========================================================\\n\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n=========================================================\n```\n\n\n:::\n\n```{.r .cell-code  code-fold=\"true\" code-summary=\"Show R Code\"}\ncat(sprintf(\"  t-statistic : %.2f\\n\", t_stat))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n  t-statistic : 4.65\n```\n\n\n:::\n\n```{.r .cell-code  code-fold=\"true\" code-summary=\"Show R Code\"}\ncat(sprintf(\"  df          : %d\\n\", df_error))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n  df          : 1018\n```\n\n\n:::\n\n```{.r .cell-code  code-fold=\"true\" code-summary=\"Show R Code\"}\ncat(sprintf(\"  p-value     : %.6f\\n\", p_value))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n  p-value     : 0.000004\n```\n\n\n:::\n\n```{.r .cell-code  code-fold=\"true\" code-summary=\"Show R Code\"}\ncat(sprintf(\"  alpha       : 0.01\\n\"))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n  alpha       : 0.01\n```\n\n\n:::\n\n```{.r .cell-code  code-fold=\"true\" code-summary=\"Show R Code\"}\ncat(\"=========================================================\\n\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n=========================================================\n```\n\n\n:::\n\n```{.r .cell-code  code-fold=\"true\" code-summary=\"Show R Code\"}\n# Critical value for two-tailed test at 1% level\nt_crit <- qt(0.995, df = df_error)\ncat(sprintf(\"  Critical value (two-tailed): +/- %.3f\\n\", t_crit))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n  Critical value (two-tailed): +/- 2.581\n```\n\n\n:::\n\n```{.r .cell-code  code-fold=\"true\" code-summary=\"Show R Code\"}\ncat(sprintf(\"  |t| = %.2f > %.3f = t_crit => Reject H0\\n\", abs(t_stat), t_crit))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n  |t| = 4.65 > 2.581 = t_crit => Reject H0\n```\n\n\n:::\n:::\n\n\n**Formal hypothesis test:**\n\n1. **Hypotheses:**\n   - $H_0: \\beta_1 = 0$ (no difference in mean reading scores between female and male students)\n   - $H_a: \\beta_1 \\neq 0$ (there is a difference)\n\n2. **Test statistic:** $t = \\dfrac{\\hat{\\beta}_1}{\\text{SE}(\\hat{\\beta}_1)} = 4.65$ with $df = 1018$\n\n3. **Decision rule:** At $\\alpha = 0.01$ (two-tailed), reject $H_0$ if $|t| > t_{0.005,\\, 1018}$\n\n4. **Conclusion:** Since $p < 0.001 < 0.01 = \\alpha$, we **reject $H_0$** at the 1% significance level. There is statistically significant evidence that mean reading scores differ between female and male US students in PISA 2000.\n\n#### Code Explanation\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Extract coefficient table from the regression model\ncoef_table <- summary(model1)$coefficients\n```\n:::\n\n\n- `summary(model1)$coefficients` returns the matrix of estimates, standard errors, $t$-values, and $p$-values for all coefficients.\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Pull out the t-statistic and p-value for the female coefficient\nt_stat <- coef_table[\"female\", \"t value\"]\np_value <- coef_table[\"female\", \"Pr(>|t|)\"]\ndf_error <- model1$df.residual\n```\n:::\n\n\n- We index the coefficient matrix by row name `\"female\"` and column name to extract the specific values.\n- `model1$df.residual` gives the error degrees of freedom: $n - k - 1 = 1020 - 1 - 1 = 1018$.\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Critical value for two-tailed test at 1% level\nt_crit <- qt(0.995, df = df_error)\n```\n:::\n\n\n- `qt(0.995, df)` returns the 99.5th percentile of the $t$-distribution, which is the upper critical value for a two-tailed test at $\\alpha = 0.01$.\n\n:::\n\n::: {.callout-tip}\n## Key Takeaway\nThe regression $t$-test for $\\beta_1$ is equivalent to testing whether the dummy variable's group means differ. A significant $\\beta_1$ means the two groups have different population means. The $p$-value from the regression output can be directly used for hypothesis testing at any significance level.\n:::\n\n::: {.callout-note}\n## Association, Not Causation\nBecause PISA 2000 is an observational study, we describe the relationship between gender and reading scores as an **association** or **mean difference**, not a causal **effect**. The hypothesis test asks whether the observed difference is statistically distinguishable from zero --- it does not tell us whether gender *causes* the difference. The original homework uses \"effect\" as Stata/statistics shorthand, but in research writing, \"association\" is safer language for observational data.\n:::\n\n\n## Problem 5\n\n### Problem Statement\n\n> Test the same null hypothesis using an independent samples t-test. Compare with the regression result.\n\n::: {.panel-tabset}\n#### Solution\n\n\n::: {.cell}\n\n```{.r .cell-code  code-fold=\"true\" code-summary=\"Show R Code\"}\n# Compute descriptive statistics by group\ngroup_stats <- pisa_us |>\n  summarize(\n    .by = female,\n    n    = n(),\n    mean = mean(wleread),\n    sd   = sd(wleread)\n  ) |>\n  arrange(female)\n\n# Combined statistics\ncombined_stats <- pisa_us |>\n  summarize(\n    n    = n(),\n    mean = mean(wleread),\n    sd   = sd(wleread)\n  )\n\ncat(\"Descriptive Statistics\\n\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nDescriptive Statistics\n```\n\n\n:::\n\n```{.r .cell-code  code-fold=\"true\" code-summary=\"Show R Code\"}\ncat(\"======================\\n\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n======================\n```\n\n\n:::\n\n```{.r .cell-code  code-fold=\"true\" code-summary=\"Show R Code\"}\ncat(sprintf(\"  Male   (female=0): N = %d, Mean = %.3f, SD = %.5f\\n\",\n            group_stats$n[1], group_stats$mean[1], group_stats$sd[1]))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n  Male   (female=0): N = 457, Mean = 507.859, SD = 99.19631\n```\n\n\n:::\n\n```{.r .cell-code  code-fold=\"true\" code-summary=\"Show R Code\"}\ncat(sprintf(\"  Female (female=1): N = %d, Mean = %.4f, SD = %.5f\\n\",\n            group_stats$n[2], group_stats$mean[2], group_stats$sd[2]))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n  Female (female=1): N = 563, Mean = 535.5576, SD = 90.76287\n```\n\n\n:::\n\n```{.r .cell-code  code-fold=\"true\" code-summary=\"Show R Code\"}\ncat(sprintf(\"  Combined         : N = %d, Mean = %.4f, SD = %.5f\\n\",\n            combined_stats$n, combined_stats$mean, combined_stats$sd))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n  Combined         : N = 1020, Mean = 523.1475, SD = 95.58571\n```\n\n\n:::\n\n```{.r .cell-code  code-fold=\"true\" code-summary=\"Show R Code\"}\ncat(\"\\n\")\n```\n\n```{.r .cell-code  code-fold=\"true\" code-summary=\"Show R Code\"}\n# Independent samples t-test (equal variance assumed)\nt_result <- t.test(wleread ~ female, data = pisa_us, var.equal = TRUE)\nprint(t_result)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\n\tTwo Sample t-test\n\ndata:  wleread by female\nt = -4.6486, df = 1018, p-value = 3.78e-06\nalternative hypothesis: true difference in means between group 0 and group 1 is not equal to 0\n95 percent confidence interval:\n -39.39082 -16.00636\nsample estimates:\nmean in group 0 mean in group 1 \n       507.8590        535.5576 \n```\n\n\n:::\n:::\n\n\n**Comparing the t-test with regression:**\n\n\n::: {.cell}\n\n```{.r .cell-code  code-fold=\"true\" code-summary=\"Show Comparison Code\"}\n# Extract values from both approaches\nreg_t <- summary(model1)$coefficients[\"female\", \"t value\"]\nreg_p <- summary(model1)$coefficients[\"female\", \"Pr(>|t|)\"]\n\nttest_t <- t_result$statistic\nttest_p <- t_result$p.value\nttest_diff <- diff(t_result$estimate)  # female mean - male mean\n\ncat(\"Side-by-Side Comparison\\n\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nSide-by-Side Comparison\n```\n\n\n:::\n\n```{.r .cell-code  code-fold=\"true\" code-summary=\"Show Comparison Code\"}\ncat(\"============================================\\n\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n============================================\n```\n\n\n:::\n\n```{.r .cell-code  code-fold=\"true\" code-summary=\"Show Comparison Code\"}\ncat(sprintf(\"  Regression t-statistic :  %.2f\\n\", reg_t))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n  Regression t-statistic :  4.65\n```\n\n\n:::\n\n```{.r .cell-code  code-fold=\"true\" code-summary=\"Show Comparison Code\"}\ncat(sprintf(\"  t-test t-statistic     : %.4f\\n\", ttest_t))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n  t-test t-statistic     : -4.6486\n```\n\n\n:::\n\n```{.r .cell-code  code-fold=\"true\" code-summary=\"Show Comparison Code\"}\ncat(sprintf(\"  Regression p-value     :  %.6f\\n\", reg_p))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n  Regression p-value     :  0.000004\n```\n\n\n:::\n\n```{.r .cell-code  code-fold=\"true\" code-summary=\"Show Comparison Code\"}\ncat(sprintf(\"  t-test p-value         :  %.6f\\n\", ttest_p))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n  t-test p-value         :  0.000004\n```\n\n\n:::\n\n```{.r .cell-code  code-fold=\"true\" code-summary=\"Show Comparison Code\"}\ncat(\"============================================\\n\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n============================================\n```\n\n\n:::\n\n```{.r .cell-code  code-fold=\"true\" code-summary=\"Show Comparison Code\"}\ncat(sprintf(\"  Mean difference (t-test): %.5f\\n\", ttest_diff))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n  Mean difference (t-test): 27.69859\n```\n\n\n:::\n\n```{.r .cell-code  code-fold=\"true\" code-summary=\"Show Comparison Code\"}\ncat(sprintf(\"  Regression slope (b1)  :  %.5f\\n\", coef(model1)[\"female\"]))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n  Regression slope (b1)  :  27.69859\n```\n\n\n:::\n\n```{.r .cell-code  code-fold=\"true\" code-summary=\"Show Comparison Code\"}\ncat(\"============================================\\n\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n============================================\n```\n\n\n:::\n\n```{.r .cell-code  code-fold=\"true\" code-summary=\"Show Comparison Code\"}\ncat(\"\\nThe t-statistics have the SAME absolute value but OPPOSITE signs.\\n\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\nThe t-statistics have the SAME absolute value but OPPOSITE signs.\n```\n\n\n:::\n\n```{.r .cell-code  code-fold=\"true\" code-summary=\"Show Comparison Code\"}\ncat(\"The p-values are identical.\\n\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nThe p-values are identical.\n```\n\n\n:::\n:::\n\n\n- The $t$-test yields $t = -4.6486$ while the regression yields $t = 4.65$.\n- The **absolute values are identical**; the sign difference arises because:\n  - The $t$-test computes: $\\bar{Y}_{\\text{male}} - \\bar{Y}_{\\text{female}}$ (group 0 minus group 1)\n  - The regression computes: $\\hat{\\beta}_1 = \\bar{Y}_{\\text{female}} - \\bar{Y}_{\\text{male}}$ (group 1 minus group 0)\n- The **$p$-values are identical** ($p < 0.001$), so both approaches lead to the same conclusion: reject $H_0$ at the 1% level.\n\n#### Code Explanation\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Compute descriptive statistics by group\ngroup_stats <- pisa_us |>\n  summarize(\n    .by = female,\n    n    = n(),\n    mean = mean(wleread),\n    sd   = sd(wleread)\n  ) |>\n  arrange(female)\n```\n:::\n\n\n- `.by = female` groups the summary by the dummy variable without using `group_by()`.\n- We compute the sample size, mean, and standard deviation for each group.\n- `arrange(female)` ensures male (0) appears first.\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Independent samples t-test (equal variance assumed)\nt_result <- t.test(wleread ~ female, data = pisa_us, var.equal = TRUE)\n```\n:::\n\n\n- `wleread ~ female` specifies the formula: outcome by grouping variable.\n- `var.equal = TRUE` requests the **pooled-variance** $t$-test, which assumes equal population variances. This is the version that is algebraically equivalent to the regression $t$-test.\n- Without `var.equal = TRUE`, R defaults to Welch's $t$-test (unequal variances), which would give different $df$ and a slightly different $t$-statistic.\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Extract values from both approaches\nttest_diff <- diff(t_result$estimate)  # female mean - male mean\n```\n:::\n\n\n- `t_result$estimate` contains the two group means; `diff()` computes female minus male.\n- This equals the regression slope $\\hat{\\beta}_1$.\n\n:::\n\n::: {.callout-important}\n## Regression = t-test (with Equal Variances)\nWhen the predictor is a single dummy variable, the regression $t$-test for $\\beta_1$ is **algebraically identical** to the pooled-variance independent samples $t$-test. The test statistics have the same absolute value, the degrees of freedom are the same ($n - 2$), and the $p$-values are identical. The only difference is the sign convention.\n:::\n\n\n## Problem 6\n\n### Problem Statement\n\n> Where is the pooled within-group standard deviation in the regression output? Explain the connection between Root MSE and the pooled standard deviation.\n\n::: {.panel-tabset}\n#### Solution\n\n**Step 1: Extract Root MSE from the regression**\n\n\n::: {.cell}\n\n```{.r .cell-code  code-fold=\"true\" code-summary=\"Show R Code\"}\n# Root MSE from the regression\nroot_mse <- sigma(model1)\ncat(sprintf(\"Root MSE (from regression): %.3f\\n\\n\", root_mse))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nRoot MSE (from regression): 94.633\n```\n\n\n:::\n\n```{.r .cell-code  code-fold=\"true\" code-summary=\"Show R Code\"}\n# Manually compute the pooled within-group SD\nn1 <- group_stats$n[1]  # male\nn2 <- group_stats$n[2]  # female\ns1 <- group_stats$sd[1]  # male SD\ns2 <- group_stats$sd[2]  # female SD\n\npooled_var <- ((n1 - 1) * s1^2 + (n2 - 1) * s2^2) / (n1 + n2 - 2)\npooled_sd  <- sqrt(pooled_var)\n\ncat(sprintf(\"Pooled within-group SD (manual calculation): %.3f\\n\\n\", pooled_sd))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nPooled within-group SD (manual calculation): 94.633\n```\n\n\n:::\n\n```{.r .cell-code  code-fold=\"true\" code-summary=\"Show R Code\"}\ncat(sprintf(\"Are they equal? %s\\n\", all.equal(root_mse, pooled_sd)))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nAre they equal? TRUE\n```\n\n\n:::\n:::\n\n\n**Step 2: Verify using ANOVA table**\n\n\n::: {.cell}\n\n```{.r .cell-code  code-fold=\"true\" code-summary=\"Show ANOVA Verification\"}\n# ANOVA table\nanova_table <- anova(model1)\nprint(anova_table)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nAnalysis of Variance Table\n\nResponse: wleread\n            Df  Sum Sq Mean Sq F value   Pr(>F)    \nfemale       1  193526  193526   21.61 3.78e-06 ***\nResiduals 1018 9116698    8955                     \n---\nSignif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1\n```\n\n\n:::\n\n```{.r .cell-code  code-fold=\"true\" code-summary=\"Show ANOVA Verification\"}\ncat(\"\\n\")\n```\n\n```{.r .cell-code  code-fold=\"true\" code-summary=\"Show ANOVA Verification\"}\nmse <- anova_table[\"Residuals\", \"Mean Sq\"]\ncat(sprintf(\"MSE from ANOVA table: %.3f\\n\", mse))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nMSE from ANOVA table: 8955.499\n```\n\n\n:::\n\n```{.r .cell-code  code-fold=\"true\" code-summary=\"Show ANOVA Verification\"}\ncat(sprintf(\"sqrt(MSE) = %.3f\\n\", sqrt(mse)))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nsqrt(MSE) = 94.633\n```\n\n\n:::\n\n```{.r .cell-code  code-fold=\"true\" code-summary=\"Show ANOVA Verification\"}\ncat(sprintf(\"Root MSE   = %.3f\\n\", root_mse))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nRoot MSE   = 94.633\n```\n\n\n:::\n:::\n\n\n**Step 3: Mathematical proof that $s_p = \\sqrt{\\text{MSE}}$**\n\nThe pooled within-group variance is defined as:\n\n$$\ns_p^2 = \\frac{(n_1 - 1)\\, s_1^2 + (n_2 - 1)\\, s_2^2}{n_1 + n_2 - 2}\n$$\n\nRecall that the sample variance for group $j$ is:\n\n$$\ns_j^2 = \\frac{\\sum_{i=1}^{n_j} (Y_{ij} - \\bar{Y}_j)^2}{n_j - 1} = \\frac{\\text{SS}_j}{n_j - 1}\n$$\n\nSubstituting into the pooled variance formula:\n\n$$\ns_p^2 = \\frac{(n_1 - 1) \\cdot \\dfrac{\\text{SS}_1}{n_1 - 1} + (n_2 - 1) \\cdot \\dfrac{\\text{SS}_2}{n_2 - 1}}{n_1 + n_2 - 2}\n$$\n\nThe $(n_j - 1)$ terms cancel:\n\n$$\ns_p^2 = \\frac{\\text{SS}_1 + \\text{SS}_2}{n_1 + n_2 - 2} = \\frac{\\text{SSE}}{df_{\\text{error}}} = \\text{MSE}\n$$\n\nwhere $\\text{SS}_1 + \\text{SS}_2 = \\text{SSE}$ (the sum of squared residuals) because in a dummy variable regression, the residual for each observation is $e_i = Y_i - \\bar{Y}_{j(i)}$, i.e., the deviation from its own group mean.\n\nTherefore:\n\n$$\n\\boxed{s_p = \\sqrt{s_p^2} = \\sqrt{\\text{MSE}} = \\text{Root MSE} = 94.633}\n$$\n\n#### Code Explanation\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Root MSE from the regression\nroot_mse <- sigma(model1)\n```\n:::\n\n\n- `sigma()` extracts the residual standard error (Root MSE) from an `lm` object. This is $\\sqrt{\\text{MSE}} = \\sqrt{\\text{SSE}/df_{\\text{error}}}$.\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Manually compute the pooled within-group SD\nn1 <- group_stats$n[1]  # male\nn2 <- group_stats$n[2]  # female\ns1 <- group_stats$sd[1]  # male SD\ns2 <- group_stats$sd[2]  # female SD\n\npooled_var <- ((n1 - 1) * s1^2 + (n2 - 1) * s2^2) / (n1 + n2 - 2)\npooled_sd  <- sqrt(pooled_var)\n```\n:::\n\n\n- This implements the textbook formula for the pooled variance: a weighted average of the two group variances, where the weights are $(n_j - 1)$.\n- The denominator $n_1 + n_2 - 2 = 1018$ equals the error degrees of freedom in the regression.\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Verify using ANOVA table\nanova_table <- anova(model1)\nmse <- anova_table[\"Residuals\", \"Mean Sq\"]\n```\n:::\n\n\n- `anova()` produces the ANOVA decomposition of the regression.\n- The \"Residuals\" row's \"Mean Sq\" column is $\\text{MSE} = \\text{SSE}/df_{\\text{error}}$.\n- We verify that $\\sqrt{\\text{MSE}}$ equals both Root MSE and the pooled SD.\n\n:::\n\n::: {.callout-warning}\n## Combined SD is NOT the Pooled SD\nThe \"combined\" standard deviation from descriptive statistics ($\\text{SD} = 95.586$ for all 1,020 students) is **not** the pooled within-group standard deviation (94.633). The combined SD ignores group membership and includes between-group variation in its calculation. The pooled SD averages only the **within-group** variation, which is exactly what the regression's Root MSE captures.\n:::\n\n::: {.callout-tip}\n## Key Takeaway\nRoot MSE in a dummy variable regression is the pooled within-group standard deviation. This is not a coincidence --- it follows directly from the algebra. In a regression with a single dummy predictor, the fitted values are the group means, so the residuals are deviations from group means, and MSE is the pooled within-group variance. This insight generalizes: in any ANOVA model, Root MSE equals the pooled within-group SD.\n:::\n\n\n::: {.callout-caution}\n## Common Mistake: Dismissing a Small $R^2$ as \"No Relationship\"\nWith $R^2 = 0.0208$, it is tempting to conclude that gender \"doesn't matter.\" But $R^2$ measures the proportion of variance explained, not the importance or significance of the predictor. A 27.7-point gender gap is highly significant ($p < .001$) and may be substantively meaningful in an educational context, even though it explains only 2% of the total variance in reading scores. Always evaluate both statistical significance and practical significance.\n:::\n\n\n## Summary\n\nThis homework demonstrated three fundamental equivalences that connect simple regression with a dummy variable to classical two-group comparisons:\n\n1. **Regression coefficients = group means.** The intercept $\\hat{\\beta}_0$ equals the reference group mean, and the slope $\\hat{\\beta}_1$ equals the difference in group means. Regression with a dummy predictor is simply a way of comparing two groups.\n\n2. **Regression $t$-test = independent samples $t$-test.** The $t$-statistic for $\\hat{\\beta}_1$ has the same absolute value, the same degrees of freedom ($n - 2$), and the same $p$-value as the pooled-variance $t$-test. The sign depends only on the coding convention (which group is subtracted from which).\n\n3. **Root MSE = pooled within-group SD.** This follows algebraically from the fact that $s_p^2 = \\text{SSE}/df_{\\text{error}} = \\text{MSE}$. The combined (overall) SD is a different quantity that conflates within- and between-group variation.\n\n::: {.callout-note}\n## Looking Ahead\nThese equivalences generalize beyond two groups. In **Homework 4**, we will see that regression with multiple dummy variables is equivalent to one-way ANOVA, and the $F$-test from the regression is identical to the ANOVA $F$-test. The Root MSE will again equal the pooled within-group SD, but now pooled across more than two groups.\n:::\n",
    "supporting": [
      "hw02-dummy-regression_files"
    ],
    "filters": [
      "rmarkdown/pagebreak.lua"
    ],
    "includes": {},
    "engineDependencies": {},
    "preserve": {},
    "postProcess": true
  }
}