{
  "hash": "deb33007b5ef6733a82cc5d5d74238e4",
  "result": {
    "engine": "knitr",
    "markdown": "# ANCOVA {#sec-ch2}\n\n\n\n\n## Introduction {#sec-ch2-intro}\n\nIn @sec-ch1, we modeled the relationship between a single predictor and a continuous outcome. But in education research, we rarely have just one variable of interest. Consider our GCSE example: Chelsea school has higher mean GCSE scores than Battersea. But Chelsea also has students with higher LRT scores at intake. Is the difference in GCSE scores a genuine \"school effect,\" or is it simply explained by the pre-existing differences in student ability?\n\nThis question --- **how to make a more comparable group contrast by statistically controlling for other variables** --- motivates the Analysis of Covariance (ANCOVA) model. ANCOVA extends simple regression by including both a categorical predictor (e.g., school) and a continuous covariate (e.g., LRT), allowing us to estimate the \"adjusted\" difference between groups.\n\nMore broadly, this chapter introduces the **multiple linear regression** model, which can include any number of predictors --- both continuous and categorical. Along the way, we encounter some of the most important concepts in applied statistics: omitted variable bias, confounding, and collinearity.\n\n::: {.objectives}\n[Learning Objectives]{.obj-title}\n\nAfter completing this chapter, you will be able to:\n\n1. Specify and interpret an ANCOVA model with a continuous covariate and a categorical factor\n2. Distinguish between unadjusted and adjusted group means\n3. Compute and interpret $R^2$ and the multiple correlation in multiple regression\n4. Conduct sequential and partial $F$-tests (Type I vs Type III SS)\n5. Explain omitted variable bias (OVB) and identify confounders\n6. Recognize the consequences of collinearity for regression estimates\n:::\n\n\n## Motivating Example: Controlling for Prior Achievement {#sec-ch2-example}\n\nLet us continue with the GCSE data from @sec-ch1. Recall that we have data from two London schools --- Battersea and Chelsea --- with both GCSE scores (outcome, age 16) and LRT scores (covariate, age 11).\n\n::: {.panel-tabset}\n### Output\n\n::: {.cell}\n\n```{.r .cell-code  code-fold=\"true\" code-summary=\"Show R Code\"}\n# Subset to two schools\ntwo_schools <- gcse |>\n  filter(school %in% c(15, 6)) |>\n  mutate(school_name = factor(ifelse(school == 15, \"Battersea\", \"Chelsea\")))\n\n# Compare raw means\ntwo_schools |>\n  group_by(school_name) |>\n  summarise(\n    n = n(),\n    mean_gcse = mean(gcse, na.rm = TRUE),\n    mean_lrt  = mean(lrt, na.rm = TRUE),\n    .groups = \"drop\"\n  ) |>\n  kable(digits = 2, col.names = c(\"School\", \"n\", \"Mean GCSE\", \"Mean LRT\"))\n```\n\n::: {.cell-output-display}\n\n\n|School    |  n| Mean GCSE| Mean LRT|\n|:---------|--:|---------:|--------:|\n|Battersea | 91|     -0.41|     2.70|\n|Chelsea   | 80|      9.45|     6.38|\n\n\n:::\n:::\n\n\n### Output Interpretation\n\n\n::: {.cell}\n::: {.cell-output-display}\n\n\n|School    |  n| Mean GCSE| Mean LRT|\n|:---------|--:|---------:|--------:|\n|Battersea | 91|     -0.41|     2.70|\n|Chelsea   | 80|      9.45|     6.38|\n\n\n:::\n:::\n\n- **Mean GCSE**: The raw (unadjusted) average GCSE score for each school. Any difference here may reflect genuine school effects, pre-existing ability differences, or both\n- **Mean LRT**: The average intake ability for each school. If this differs between schools, the raw GCSE comparison is confounded --- Chelsea students may score higher simply because they started with higher ability\n- The gap in Mean LRT motivates the need for ANCOVA: we need to \"adjust\" the school comparison for pre-existing ability differences (see @sec-ch2-estimation)\n\n### Code Explanation\n\n::: {.cell}\n\n```{.r .cell-code}\n# Subset to two schools\ntwo_schools <- gcse |>\n  filter(school %in% c(15, 6)) |>\n  mutate(school_name = factor(ifelse(school == 15, \"Battersea\", \"Chelsea\")))\n\n# Compare raw means\ntwo_schools |>\n  group_by(school_name) |>\n  summarise(\n    n = n(),\n    mean_gcse = mean(gcse, na.rm = TRUE),\n    mean_lrt  = mean(lrt, na.rm = TRUE),\n    .groups = \"drop\"\n  ) |>\n  kable(digits = 2, col.names = c(\"School\", \"n\", \"Mean GCSE\", \"Mean LRT\"))\n```\n\n::: {.cell-output-display}\n\n\n|School    |  n| Mean GCSE| Mean LRT|\n|:---------|--:|---------:|--------:|\n|Battersea | 91|     -0.41|     2.70|\n|Chelsea   | 80|      9.45|     6.38|\n\n\n:::\n:::\n\n- We filter to schools 15 (Battersea) and 6 (Chelsea) and create a factor for the school name\n- The table reveals that Chelsea has a higher mean GCSE score **and** a higher mean LRT score\n- This raises the question: is the GCSE difference due to the school, or due to pre-existing differences in student ability?\n\n\n:::\n\n::: {.panel-tabset}\n### Output\n\n::: {.cell}\n\n```{.r .cell-code  code-fold=\"true\" code-summary=\"Show R Code\"}\nggplot(two_schools, aes(x = lrt, y = gcse, color = school_name)) +\n  geom_point(alpha = 0.4) +\n  geom_smooth(method = \"lm\", formula = y ~ x, se = FALSE, linewidth = 1) +\n  scale_color_manual(values = c(ber640_colors[[\"primary\"]], ber640_colors[[\"secondary\"]])) +\n  labs(\n    title = \"GCSE vs LRT by School\",\n    subtitle = \"Are the regression lines parallel?\",\n    x = \"LRT Score (age 11)\",\n    y = \"GCSE Score (age 16)\",\n    color = \"School\"\n  )\n```\n\n::: {.cell-output-display}\n![Regression of GCSE on LRT for Battersea and Chelsea schools. Separate regression lines suggest similar slopes but different intercepts, motivating the ANCOVA (parallel lines) model.](02-ancova_files/figure-html/fig-ch2-parallel-1.png){#fig-ch2-parallel fig-alt='Scatter plot with LRT on the horizontal axis and GCSE on the vertical axis, with points colored by school. Battersea and Chelsea each have a separate regression line. The two lines have similar positive slopes but different intercepts, with Chelsea shifted higher, motivating the parallel lines ANCOVA model that estimates a constant group difference after adjusting for LRT.' width=2400}\n:::\n:::\n\n\n### Output Interpretation\n\n\n::: {.cell}\n::: {.cell-output-display}\n![](02-ancova_files/figure-html/unnamed-chunk-3-1.png){width=2400}\n:::\n:::\n\n- The two regression lines appear **roughly parallel**, supporting the ANCOVA assumption of equal slopes across schools\n- Chelsea's regression line sits **above** Battersea's, suggesting Chelsea has higher GCSE scores even at the same LRT level\n- The vertical gap between the lines is the **adjusted school difference** --- the quantity ANCOVA estimates\n- Note the overlap in LRT ranges: both schools have students with similar intake scores, which allows meaningful comparison at common LRT values\n\n### Code Explanation\n\n::: {.cell}\n\n```{.r .cell-code}\nggplot(two_schools, aes(x = lrt, y = gcse, color = school_name)) +\n  geom_point(alpha = 0.4) +\n  geom_smooth(method = \"lm\", formula = y ~ x, se = FALSE, linewidth = 1) +\n  scale_color_manual(values = c(ber640_colors[[\"primary\"]], ber640_colors[[\"secondary\"]])) +\n  labs(\n    title = \"GCSE vs LRT by School\",\n    subtitle = \"Are the regression lines parallel?\",\n    x = \"LRT Score (age 11)\",\n    y = \"GCSE Score (age 16)\",\n    color = \"School\"\n  )\n```\n\n::: {.cell-output-display}\n![](02-ancova_files/figure-html/unnamed-chunk-4-1.png){width=2400}\n:::\n:::\n\n- `geom_smooth(method = \"lm\")` fits separate regression lines for each school\n- If the slopes are similar (lines are roughly parallel), the ANCOVA model is appropriate\n- The vertical distance between the two parallel lines is the **LRT-adjusted** school difference\n\n\n:::\n\n\n## The ANCOVA Model {#sec-ch2-model}\n\nThe ANCOVA model includes both a continuous covariate ($x_i$ = LRT) and a dummy variable ($d_{Ci}$ = Chelsea indicator):\n\n$$\ny_i = \\alpha + \\beta_1 x_i + \\beta_2 d_{Ci} + \\epsilon_i\n$$ {#eq-ch2-ancova}\n\nFor students in **Battersea** ($d_{Ci} = 0$):\n\n$$\n\\text{E}(y_i \\mid x_i, d_{Ci} = 0) = \\alpha + \\beta_1 x_i\n$$\n\nFor students in **Chelsea** ($d_{Ci} = 1$):\n\n$$\n\\text{E}(y_i \\mid x_i, d_{Ci} = 1) = (\\alpha + \\beta_2) + \\beta_1 x_i\n$$\n\nThe key parameter is $\\beta_2$: the adjusted difference between Chelsea and Battersea, **holding LRT constant**:\n\n$$\n\\underbrace{(\\alpha + \\beta_1 x_i + \\beta_2)}_{\\text{Chelsea}} - \\underbrace{(\\alpha + \\beta_1 x_i)}_{\\text{Battersea}} = \\beta_2\n$$\n\n::: {.callout-tip}\n## Interpreting ANCOVA Coefficients\n- $\\alpha$: Expected GCSE score for a Battersea student with LRT = 0\n- $\\beta_1$: Expected change in GCSE per one-unit increase in LRT, **controlling for school**\n- $\\beta_2$: Expected difference in GCSE between Chelsea and Battersea, **controlling for LRT**\n\nThis \"controlling for\" language is the hallmark of multiple regression. Each coefficient is interpreted *holding all other variables constant*.\n:::\n\n::: {.callout-tip}\n## Concept Check: What Does \"Controlling For\" Actually Mean?\nConsider two students --- one from Battersea, one from Chelsea --- **both with LRT = 5**. The ANCOVA model predicts their GCSE scores differ by exactly $\\hat{\\beta}_2$, regardless of which LRT value we choose (as long as it is the same for both).\n\nThis is what \"holding LRT constant\" means: we compare groups *at the same level* of the covariate. It is a *statistical* operation, not a physical one --- we did not assign students to schools. Statistical control is therefore not the same as causal control: the adjusted difference is a *descriptive*, covariate-adjusted contrast, and it equals a **causal** school effect only if LRT captures *all* common causes of school attended and GCSE (the strong-ignorability assumption). In observational data this is rarely guaranteed, so throughout this chapter read \"adjusted school difference\" as model-adjusted, not as a verified causal effect (see @sec-ch2-ovb and @sec-ch2-confounding).\n:::\n\n### The General Multiple Regression Model\n\nMore generally, with $k$ predictors:\n\n$$\ny_i = \\alpha + \\beta_1 x_{1i} + \\beta_2 x_{2i} + \\cdots + \\beta_k x_{ki} + \\epsilon_i\n$$ {#eq-ch2-mlr}\n\nEach $\\beta_j$ represents the change in $\\text{E}(y)$ per one-unit increase in $x_j$, **holding all other predictors constant**. The error term $\\epsilon_i$ has the same assumptions as in simple regression: mean zero, constant variance $\\sigma^2$, independence, and (for inference) normality.\n\n\n## Estimation and Interpretation {#sec-ch2-estimation}\n\n### Fitting the ANCOVA Model\n\n::: {.panel-tabset}\n### Output\n\n::: {.cell}\n\n```{.r .cell-code  code-fold=\"true\" code-summary=\"Show R Code\"}\n# ANCOVA model: GCSE predicted by LRT and School\nmodel_ancova <- lm(gcse ~ lrt + school_name, data = two_schools)\n\n# Parameters with easystats\nmodel_parameters(model_ancova) |> print_md()\n```\n\n::: {.cell-output-display}\n\n\n|Parameter             | Coefficient |   SE |         95% CI | t(168) |      p |\n|:---------------------|:-----------:|:----:|:--------------:|:------:|:------:|\n|(Intercept)           |       -2.13 | 0.79 | (-3.69, -0.56) |  -2.68 | 0.008  |\n|lrt                   |        0.64 | 0.07 |   (0.50, 0.77) |   9.29 | < .001 |\n|school name (Chelsea) |        7.51 | 1.16 |   (5.23, 9.80) |   6.49 | < .001 |\n\n\n:::\n:::\n\n\n### Output Interpretation\n\n\n::: {.cell}\n::: {.cell-output-display}\n\n\n|Parameter             | Coefficient |   SE |         95% CI | t(168) |      p |\n|:---------------------|:-----------:|:----:|:--------------:|:------:|:------:|\n|(Intercept)           |       -2.13 | 0.79 | (-3.69, -0.56) |  -2.68 | 0.008  |\n|lrt                   |        0.64 | 0.07 |   (0.50, 0.77) |   9.29 | < .001 |\n|school name (Chelsea) |        7.51 | 1.16 |   (5.23, 9.80) |   6.49 | < .001 |\n\n\n:::\n:::\n\n- **Intercept** ($a$): Expected GCSE for a Battersea student with LRT = 0. Since LRT is standardized around 0, this is roughly the expected GCSE for an average-ability Battersea student\n- **lrt** ($b_1$): Each additional LRT point is associated with a $b_1$-point increase in GCSE, controlling for school. This is the common slope shared by both schools under the parallel lines assumption\n- **school_nameChelsea** ($b_2$): Comparing two students with the **same** LRT score, a Chelsea student is expected to score $b_2$ points higher (or lower, if negative) on GCSE than a Battersea student. This is the key ANCOVA quantity --- the \"adjusted\" school difference\n- **SE and 95% CI**: The standard error and confidence interval for each coefficient. Narrower intervals indicate more precisely estimated effects\n- Compare the Chelsea coefficient here to the unadjusted difference (next section) to see how controlling for LRT changes the model-adjusted school difference\n\n### Code Explanation\n\n::: {.cell}\n\n```{.r .cell-code}\n# ANCOVA model: GCSE predicted by LRT and School\nmodel_ancova <- lm(gcse ~ lrt + school_name, data = two_schools)\n\n# Parameters with easystats\nmodel_parameters(model_ancova) |> print_md()\n```\n\n::: {.cell-output-display}\n\n\n|Parameter             | Coefficient |   SE |         95% CI | t(168) |      p |\n|:---------------------|:-----------:|:----:|:--------------:|:------:|:------:|\n|(Intercept)           |       -2.13 | 0.79 | (-3.69, -0.56) |  -2.68 | 0.008  |\n|lrt                   |        0.64 | 0.07 |   (0.50, 0.77) |   9.29 | < .001 |\n|school name (Chelsea) |        7.51 | 1.16 |   (5.23, 9.80) |   6.49 | < .001 |\n\n\n:::\n:::\n\n- `lm(gcse ~ lrt + school_name)`: Fits the ANCOVA model with LRT (continuous) and school (categorical) as predictors\n- R automatically creates a dummy variable for `school_name`, with Battersea as the reference group\n- The `school_nameChelsea` coefficient is $\\hat{\\beta}_2$: the LRT-adjusted school difference\n- `print_md()` formats the output as a clean markdown table\n\n\n:::\n\n### Checking the Parallel Slopes Assumption\n\nBefore fitting the ANCOVA model, we should verify that the effect of LRT on GCSE is similar for both schools --- the **parallel slopes** assumption. We test this by fitting an interaction model and checking whether the interaction term is significant:\n\n::: {.panel-tabset}\n### Output\n\n::: {.cell}\n\n```{.r .cell-code  code-fold=\"true\" code-summary=\"Show R Code\"}\n# Interaction model: allows different slopes per school\nmodel_interact <- lm(gcse ~ lrt * school_name, data = two_schools)\n\n# Compare ANCOVA (parallel) vs interaction (non-parallel) model\nanova(model_ancova, model_interact)\n```\n\n::: {.cell-output-display}\n<div class=\"kable-table\">\n\n| Res.Df|      RSS| Df| Sum of Sq|        F|   Pr(>F)|\n|------:|--------:|--:|---------:|--------:|--------:|\n|    168| 9128.752| NA|        NA|       NA|       NA|\n|    167| 9013.457|  1|  115.2955| 2.136178| 0.145739|\n\n</div>\n:::\n:::\n\n\n### Output Interpretation\n\n\n::: {.cell}\n::: {.cell-output-display}\n<div class=\"kable-table\">\n\n| Res.Df|      RSS| Df| Sum of Sq|        F|   Pr(>F)|\n|------:|--------:|--:|---------:|--------:|--------:|\n|    168| 9128.752| NA|        NA|       NA|       NA|\n|    167| 9013.457|  1|  115.2955| 2.136178| 0.145739|\n\n</div>\n:::\n:::\n\n- **F-statistic and p-value**: Here $F \\approx 2.14$ with $p \\approx .15$, so we fail to reject the null that the slopes are equal. This means we find *no evidence* that the slopes differ --- it does not prove the slopes are exactly equal (the test may have limited power). The parallel-slopes ANCOVA is therefore a reasonable working model\n- This is consistent with the visual evidence in @fig-ch2-parallel, where the two school regression lines appear roughly parallel\n- If the interaction were significant, we would need a model that lets the school difference vary with LRT, such as the interaction model from @sec-ch5\n\n### Code Explanation\n\n::: {.cell}\n\n```{.r .cell-code}\n# Interaction model: allows different slopes per school\nmodel_interact <- lm(gcse ~ lrt * school_name, data = two_schools)\n\n# Compare ANCOVA (parallel) vs interaction (non-parallel) model\nanova(model_ancova, model_interact)\n```\n\n::: {.cell-output-display}\n<div class=\"kable-table\">\n\n| Res.Df|      RSS| Df| Sum of Sq|        F|   Pr(>F)|\n|------:|--------:|--:|---------:|--------:|--------:|\n|    168| 9128.752| NA|        NA|       NA|       NA|\n|    167| 9013.457|  1|  115.2955| 2.136178| 0.145739|\n\n</div>\n:::\n:::\n\n- `lrt * school_name` creates both main effects and the LRT $\\times$ School interaction\n- The interaction term ($\\beta_3$) represents the **difference in slopes** between Chelsea and Battersea\n- `anova()` performs an $F$-test comparing the restricted (parallel) and unrestricted (interaction) models\n- A **non-significant** $F$-test supports the simpler parallel-slopes ANCOVA model\n\n\n:::\n\n### Comparing Unadjusted vs Adjusted Differences\n\n::: {.panel-tabset}\n### Output\n\n::: {.cell}\n\n```{.r .cell-code  code-fold=\"true\" code-summary=\"Show R Code\"}\n# Unadjusted model (school only)\nmodel_unadj <- lm(gcse ~ school_name, data = two_schools)\n\n# Compare coefficients side by side\nbind_rows(\n  tidy_model(model_unadj) |> mutate(model = \"Unadjusted\"),\n  tidy_model(model_ancova) |> mutate(model = \"Adjusted (ANCOVA)\")\n) |>\n  filter(term == \"school_nameChelsea\") |>\n  select(model, estimate, std.error, statistic, p.value) |>\n  kable(digits = 3, col.names = c(\"Model\", \"Estimate\", \"SE\", \"t\", \"p-value\"))\n```\n\n::: {.cell-output-display}\n\n\n|Model             | Estimate|    SE|     t| p-value|\n|:-----------------|--------:|-----:|-----:|-------:|\n|Unadjusted        |    9.852| 1.386| 7.109|       0|\n|Adjusted (ANCOVA) |    7.514| 1.157| 6.492|       0|\n\n\n:::\n:::\n\n\n### Output Interpretation\n\n\n::: {.cell}\n::: {.cell-output-display}\n\n\n|Model             | Estimate|    SE|     t| p-value|\n|:-----------------|--------:|-----:|-----:|-------:|\n|Unadjusted        |    9.852| 1.386| 7.109|       0|\n|Adjusted (ANCOVA) |    7.514| 1.157| 6.492|       0|\n\n\n:::\n:::\n\n- **Unadjusted estimate**: The raw difference in mean GCSE between Chelsea and Battersea, ignoring LRT. This conflates any school difference with intake ability differences\n- **Adjusted estimate**: The school difference after controlling for LRT. This is the ANCOVA estimate --- a more comparable (covariate-adjusted) contrast of schools, as if both had the same average intake ability. It is the difference predicted for students with the same LRT; whether it equals a causal school effect requires the further assumptions discussed in @sec-ch2-ovb\n- The reduction from unadjusted to adjusted illustrates omitted variable bias in action (see @sec-ch2-ovb). The unadjusted comparison attributes to the school part of what is associated with differences in student intake ability; adjusting for LRT moves the estimate toward --- though not necessarily all the way to --- a causal school effect\n\n### Code Explanation\n\n::: {.cell}\n\n```{.r .cell-code}\n# Unadjusted model (school only)\nmodel_unadj <- lm(gcse ~ school_name, data = two_schools)\n\n# Compare coefficients side by side\nbind_rows(\n  tidy_model(model_unadj) |> mutate(model = \"Unadjusted\"),\n  tidy_model(model_ancova) |> mutate(model = \"Adjusted (ANCOVA)\")\n) |>\n  filter(term == \"school_nameChelsea\") |>\n  select(model, estimate, std.error, statistic, p.value) |>\n  kable(digits = 3, col.names = c(\"Model\", \"Estimate\", \"SE\", \"t\", \"p-value\"))\n```\n\n::: {.cell-output-display}\n\n\n|Model             | Estimate|    SE|     t| p-value|\n|:-----------------|--------:|-----:|-----:|-------:|\n|Unadjusted        |    9.852| 1.386| 7.109|       0|\n|Adjusted (ANCOVA) |    7.514| 1.157| 6.492|       0|\n\n\n:::\n:::\n\n- `tidy_model()` extracts coefficient estimates from each model in a tidy format\n- The unadjusted difference (from a model with only `school_name`) is larger than the adjusted difference (from the ANCOVA model with both `school_name` and `lrt`)\n- The reduction occurs because part of the school difference is \"explained\" by differences in LRT scores at intake\n\n\n:::\n\n### Adjusted Group Means\n\nThe LRT-adjusted mean GCSE score for each school is the predicted GCSE score at the overall mean LRT:\n\n::: {.panel-tabset}\n### Output\n\n::: {.cell}\n\n```{.r .cell-code  code-fold=\"true\" code-summary=\"Show R Code\"}\n# Adjusted means: predicted GCSE at the grand mean of LRT for each school\npredictions(\n  model_ancova,\n  newdata = datagrid(\n    school_name = unique(two_schools$school_name),\n    lrt = mean(two_schools$lrt, na.rm = TRUE)\n  )\n) |>\n  as.data.frame() |>\n  select(school_name, estimate, std.error, conf.low, conf.high) |>\n  kable(digits = 2, col.names = c(\"School\", \"Adjusted Mean\", \"SE\", \"CI Lower\", \"CI Upper\"))\n```\n\n::: {.cell-output-display}\n\n\n|School    | Adjusted Mean|   SE| CI Lower| CI Upper|\n|:---------|-------------:|----:|--------:|--------:|\n|Battersea |          0.69| 0.78|    -0.84|     2.22|\n|Chelsea   |          8.20| 0.83|     6.57|     9.84|\n\n\n:::\n:::\n\n\n### Output Interpretation\n\n\n::: {.cell}\n::: {.cell-output-display}\n\n\n|School    | Adjusted Mean|   SE| CI Lower| CI Upper|\n|:---------|-------------:|----:|--------:|--------:|\n|Battersea |          0.69| 0.78|    -0.84|     2.22|\n|Chelsea   |          8.20| 0.83|     6.57|     9.84|\n\n\n:::\n:::\n\n- **Estimate**: The LRT-adjusted (predicted) mean GCSE for each school. These give a more comparable contrast because both schools are evaluated at the same intake (LRT) level\n- **Std. Error and 95% CI**: The precision of the adjusted mean estimates. Narrower intervals indicate more precisely estimated adjusted means\n- The difference between the two adjusted means equals the `school_nameChelsea` coefficient from the ANCOVA model\n- Compare these adjusted means to the raw means from the earlier table to see how controlling for LRT changes the picture\n\n### Code Explanation\n\n::: {.cell}\n\n```{.r .cell-code}\n# Adjusted means: predicted GCSE at the grand mean of LRT for each school\npredictions(\n  model_ancova,\n  newdata = datagrid(\n    school_name = unique(two_schools$school_name),\n    lrt = mean(two_schools$lrt, na.rm = TRUE)\n  )\n) |>\n  as.data.frame() |>\n  select(school_name, estimate, std.error, conf.low, conf.high) |>\n  kable(digits = 2, col.names = c(\"School\", \"Adjusted Mean\", \"SE\", \"CI Lower\", \"CI Upper\"))\n```\n\n::: {.cell-output-display}\n\n\n|School    | Adjusted Mean|   SE| CI Lower| CI Upper|\n|:---------|-------------:|----:|--------:|--------:|\n|Battersea |          0.69| 0.78|    -0.84|     2.22|\n|Chelsea   |          8.20| 0.83|     6.57|     9.84|\n\n\n:::\n:::\n\n- `predictions()` with `datagrid()` from `marginaleffects` computes the model-predicted mean GCSE for each school, evaluated at the **grand mean** of LRT (the same LRT value for both schools)\n- These are the \"adjusted means\" --- what each school's model-predicted GCSE would be at the same representative LRT value\n\n\n:::\n\n::: {.callout-tip}\n## How Adjusted Means Are Computed\nThe adjusted mean for school $g$ is the predicted GCSE at the **grand mean** of LRT:\n\n$$\\hat{\\mu}_g^{\\text{adj}} = \\hat{\\alpha} + \\hat{\\beta}_1 \\bar{x}_{\\cdot} + \\hat{\\beta}_2 \\cdot \\mathbf{1}[g = \\text{Chelsea}]$$\n\nBoth schools are evaluated at the same LRT value --- this is the source of the added comparability in the adjusted comparison (a causal interpretation still requires that LRT captures all relevant intake differences).\n:::\n\n::: {.panel-tabset}\n### Output\n\n::: {.cell}\n\n```{.r .cell-code  code-fold=\"true\" code-summary=\"Show R Code\"}\nraw_means <- two_schools |>\n  group_by(school_name) |>\n  summarise(estimate = mean(gcse, na.rm = TRUE), .groups = \"drop\") |>\n  mutate(type = \"Unadjusted (raw)\")\n\nadj_means <- predictions(\n  model_ancova,\n  newdata = datagrid(\n    school_name = unique(two_schools$school_name),\n    lrt = mean(two_schools$lrt, na.rm = TRUE)\n  )\n) |>\n  as.data.frame() |>\n  select(school_name, estimate) |>\n  mutate(type = \"Adjusted (ANCOVA)\")\n\nmeans_df <- bind_rows(raw_means, adj_means) |>\n  mutate(type = factor(type, levels = c(\"Unadjusted (raw)\", \"Adjusted (ANCOVA)\")))\n\nggplot(means_df, aes(x = type, y = estimate, color = school_name, group = school_name)) +\n  geom_line(linetype = \"dashed\", linewidth = 0.7, alpha = 0.6) +\n  geom_point(size = 5) +\n  geom_text(aes(label = round(estimate, 1)), vjust = -1, size = 3.8,\n            fontface = \"bold\", show.legend = FALSE) +\n  scale_color_manual(values = c(ber640_colors[[\"primary\"]], ber640_colors[[\"secondary\"]])) +\n  scale_y_continuous(expand = expansion(mult = c(0.1, 0.15))) +\n  labs(title = \"How ANCOVA Adjusts the School Comparison\",\n       subtitle = \"Controlling for LRT reduces the estimated Chelsea advantage\",\n       x = NULL, y = \"Mean GCSE Score\", color = \"School\")\n```\n\n::: {.cell-output-display}\n![Unadjusted (raw) and LRT-adjusted mean GCSE scores. Dashed connectors show how adjusting for intake ability changes the estimated school difference.](02-ancova_files/figure-html/fig-ch2-adjusted-means-1.png){#fig-ch2-adjusted-means fig-alt='Dot plot comparing unadjusted and LRT-adjusted mean GCSE scores for Battersea and Chelsea schools. Dashed connectors join each school\\'s raw mean to its adjusted mean, showing how controlling for LRT intake ability shifts the estimated group means. The gap between schools changes after adjustment, illustrating that the unadjusted difference partly reflects pre-existing differences in intake scores rather than a pure school effect.' width=2100}\n:::\n:::\n\n\n### Output Interpretation\n\n\n::: {.cell}\n::: {.cell-output-display}\n![](02-ancova_files/figure-html/unnamed-chunk-13-1.png){width=2100}\n:::\n:::\n\n- The **unadjusted** means reflect the raw school difference, which confounds the school effect with intake ability differences\n- The **adjusted** means show the ANCOVA-estimated school difference after controlling for LRT\n- The convergence of the two points (lines moving closer together) illustrates that part of the raw school difference was due to LRT differences, not the school itself\n- The remaining gap between adjusted means equals the `school_nameChelsea` coefficient from the ANCOVA model\n\n### Code Explanation\n\n::: {.cell}\n\n```{.r .cell-code}\nraw_means <- two_schools |>\n  group_by(school_name) |>\n  summarise(estimate = mean(gcse, na.rm = TRUE), .groups = \"drop\") |>\n  mutate(type = \"Unadjusted (raw)\")\n\nadj_means <- predictions(\n  model_ancova,\n  newdata = datagrid(\n    school_name = unique(two_schools$school_name),\n    lrt = mean(two_schools$lrt, na.rm = TRUE)\n  )\n) |>\n  as.data.frame() |>\n  select(school_name, estimate) |>\n  mutate(type = \"Adjusted (ANCOVA)\")\n\nmeans_df <- bind_rows(raw_means, adj_means) |>\n  mutate(type = factor(type, levels = c(\"Unadjusted (raw)\", \"Adjusted (ANCOVA)\")))\n\nggplot(means_df, aes(x = type, y = estimate, color = school_name, group = school_name)) +\n  geom_line(linetype = \"dashed\", linewidth = 0.7, alpha = 0.6) +\n  geom_point(size = 5) +\n  geom_text(aes(label = round(estimate, 1)), vjust = -1, size = 3.8,\n            fontface = \"bold\", show.legend = FALSE) +\n  scale_color_manual(values = c(ber640_colors[[\"primary\"]], ber640_colors[[\"secondary\"]])) +\n  scale_y_continuous(expand = expansion(mult = c(0.1, 0.15))) +\n  labs(title = \"How ANCOVA Adjusts the School Comparison\",\n       subtitle = \"Controlling for LRT reduces the estimated Chelsea advantage\",\n       x = NULL, y = \"Mean GCSE Score\", color = \"School\")\n```\n\n::: {.cell-output-display}\n![](02-ancova_files/figure-html/unnamed-chunk-14-1.png){width=2100}\n:::\n:::\n\n- `raw_means` computes simple group averages (ignoring LRT); `adj_means` uses `predictions()` at the grand mean of LRT from the ANCOVA model\n- The dashed lines connecting each school's raw and adjusted mean show how the estimates shift after controlling for LRT\n- `scale_color_manual()` applies the course color palette for consistency\n\n\n:::\n\n### Interactive Exploration: Adjusted vs. Unadjusted Means {.unnumbered}\n\n::: {.callout-tip}\n## Try It: How Covariates Confound Group Comparisons\n\nThis app has two sliders --- **Confounding strength** (how strongly the covariate X separates the two groups) and **True group effect** (the genuine causal gap the model targets) --- plus a **Reset** button. Start by pushing **Confounding strength** up from its default while leaving **True group effect** fixed: watch the unadjusted difference drift away from the true effect while the ANCOVA-adjusted difference stays much nearer to it. Then vary **True group effect** to see that adjustment targets the truth you set, while the displayed recovery error reminds you that any single finite sample can still miss the true value. We simulate the data here because demonstrating that adjustment removes bias requires a *known* true effect and *controlled* confounding strength to compare against --- quantities a single real dataset cannot supply, since its true effect is unknown and its confounding is fixed.\n:::\n\n```{ojs}\n//| echo: false\nimport { ber640 as ancova_ber640, withAlpha as ancova_withAlpha,\n         themeColors as ancova_themeColors, plotDefaults as ancova_plotDefaults,\n         normalRandom as ancova_normalRandom, seq as ancova_seq,\n         formatCoef as ancova_formatCoef, srSummary as ancova_srSummary,\n         resetControls as ancova_resetControls, onThemeChange as ancova_onThemeChange } from \"../ojs/shared.js\"\n```\n\n```{ojs}\n//| echo: false\nancova_theme = ancova_themeColors()\n```\n\n```{ojs}\n//| echo: false\nancova_pill = (label, value, tone = \"\") => html`<span class=\"ojs-readout ${tone ? \"ojs-readout-\" + tone : \"\"}\"><span class=\"ojs-readout-label\">${label}</span><span class=\"ojs-readout-value\">${value}</span></span>`\n```\n\n```{ojs}\n//| echo: false\nviewof ancova_confounding = Inputs.range([0, 0.9], {\n  value: 0.5, step: 0.05, label: \"Confounding strength\"\n})\n```\n\n```{ojs}\n//| echo: false\nviewof ancova_trueEffect = Inputs.range([-2, 2], {\n  value: 0.5, step: 0.1, label: \"True group effect\"\n})\n```\n\n```{ojs}\n//| echo: false\nancova_nPerGroup = 100\nancova_betaX = 0.8\nancova_confoundShift = ancova_confounding * 3\n\nancova_xA = ancova_normalRandom(ancova_nPerGroup, 0, 1, 42)\nancova_xB = ancova_normalRandom(ancova_nPerGroup, ancova_confoundShift, 1, 99)\nancova_errA = {\n  const e = ancova_normalRandom(ancova_nPerGroup, 0, 1, 123);\n  const ebar = d3.mean(e);            // frozen ~+0.12 offset from this fixed seed\n  return e.map(v => v - ebar);        // center so realized residuals have mean 0\n}\nancova_errB = {\n  const e = ancova_normalRandom(ancova_nPerGroup, 0, 1, 456);\n  const ebar = d3.mean(e);            // frozen ~-0.13 offset from this fixed seed\n  return e.map(v => v - ebar);        // center so realized residuals have mean 0\n}\n\nancova_yA = ancova_xA.map((x, i) => ancova_trueEffect * 0 + ancova_betaX * x + ancova_errA[i])\nancova_yB = ancova_xB.map((x, i) => ancova_trueEffect * 1 + ancova_betaX * x + ancova_errB[i])\n\nancova_data = {\n  const rows = [];\n  for (let i = 0; i < ancova_nPerGroup; i++) {\n    rows.push({ group: \"Group A\", x: ancova_xA[i], y: ancova_yA[i] });\n  }\n  for (let i = 0; i < ancova_nPerGroup; i++) {\n    rows.push({ group: \"Group B\", x: ancova_xB[i], y: ancova_yB[i] });\n  }\n  return rows;\n}\n```\n\n```{ojs}\n//| echo: false\nancova_meanYA = d3.mean(ancova_yA)\nancova_meanYB = d3.mean(ancova_yB)\nancova_meanXA = d3.mean(ancova_xA)\nancova_meanXB = d3.mean(ancova_xB)\nancova_meanXGrand = d3.mean([...ancova_xA, ...ancova_xB])\n\nancova_bWithin = {\n  let ssxy = 0, ssxx = 0;\n  for (let i = 0; i < ancova_nPerGroup; i++) {\n    ssxy += (ancova_xA[i] - ancova_meanXA) * (ancova_yA[i] - ancova_meanYA);\n    ssxx += (ancova_xA[i] - ancova_meanXA) ** 2;\n  }\n  for (let i = 0; i < ancova_nPerGroup; i++) {\n    ssxy += (ancova_xB[i] - ancova_meanXB) * (ancova_yB[i] - ancova_meanYB);\n    ssxx += (ancova_xB[i] - ancova_meanXB) ** 2;\n  }\n  return ssxy / ssxx;\n}\n\nancova_adjMeanA = ancova_meanYA - ancova_bWithin * (ancova_meanXA - ancova_meanXGrand)\nancova_adjMeanB = ancova_meanYB - ancova_bWithin * (ancova_meanXB - ancova_meanXGrand)\nancova_unadjDiff = ancova_meanYB - ancova_meanYA\nancova_adjDiff = ancova_adjMeanB - ancova_adjMeanA\nancova_bias = ancova_unadjDiff - ancova_adjDiff\nancova_recoveryErr = ancova_adjDiff - ancova_trueEffect\n```\n\n```{ojs}\n//| echo: false\nancova_scatterPlot = {\n  const xAll = [...ancova_xA, ...ancova_xB];\n  const yAll = [...ancova_yA, ...ancova_yB];\n  const xMin = d3.min(xAll) - 0.5;\n  const xMax = d3.max(xAll) + 0.5;\n  const xLine = ancova_seq(xMin, xMax, 50);\n\n  const interceptA = ancova_meanYA - ancova_bWithin * ancova_meanXA;\n  const interceptB = ancova_meanYB - ancova_bWithin * ancova_meanXB;\n\n  const lineA = xLine.map(x => ({ x, y: interceptA + ancova_bWithin * x, group: \"Group A\" }));\n  const lineB = xLine.map(x => ({ x, y: interceptB + ancova_bWithin * x, group: \"Group B\" }));\n\n  return Plot.plot(ancova_plotDefaults({\n    width: 320,\n    height: 320,\n    marginTop: 24, marginBottom: 40, marginLeft: 48, marginRight: 16,\n    style: { color: ancova_theme.text },\n    color: { domain: [\"Group A\", \"Group B\"], range: [ancova_ber640.accent, ancova_ber640.secondary] },\n    x: { label: \"Covariate (X)\", domain: [xMin, xMax], grid: true },\n    y: { label: \"Outcome (Y)\", grid: true },\n    marks: [\n      Plot.dot(ancova_data, {\n        x: \"x\", y: \"y\", fill: \"group\",\n        fillOpacity: 0.45, r: 3, stroke: \"none\"\n      }),\n      Plot.line(lineA, { x: \"x\", y: \"y\", stroke: ancova_ber640.accent, strokeWidth: 2.5 }),\n      Plot.line(lineB, { x: \"x\", y: \"y\", stroke: ancova_ber640.secondary, strokeWidth: 2.5, strokeDasharray: \"6 4\" }),\n      Plot.ruleX([ancova_meanXGrand], {\n        stroke: ancova_theme.muted, strokeDasharray: \"2 2\", strokeOpacity: 0.6\n      }),\n      Plot.text([{ x: ancova_meanXGrand, y: d3.max(yAll) + 0.3 }], {\n        x: \"x\", y: \"y\", text: [\"X̄ grand\"], fontSize: 10,\n        fill: ancova_theme.text, textAnchor: \"middle\"\n      })\n    ]\n  }));\n}\n\nancova_barData = [\n  { type: \"Unadjusted\", group: \"Group A\", mean: ancova_meanYA },\n  { type: \"Unadjusted\", group: \"Group B\", mean: ancova_meanYB },\n  { type: \"Adjusted\", group: \"Group A\", mean: ancova_adjMeanA },\n  { type: \"Adjusted\", group: \"Group B\", mean: ancova_adjMeanB }\n]\n\nancova_barPlot = {\n  return Plot.plot(ancova_plotDefaults({\n    width: 320,\n    height: 320,\n    marginTop: 24, marginBottom: 40, marginLeft: 48, marginRight: 16,\n    style: { color: ancova_theme.text },\n    x: { label: null, padding: 0.2 },\n    y: { label: \"Mean Outcome (Y)\", grid: true },\n    fx: { label: null, padding: 0.15 },\n    color: { domain: [\"Group A\", \"Group B\"], range: [ancova_ber640.accent, ancova_ber640.secondary], legend: true },\n    marks: [\n      Plot.barY(ancova_barData, {\n        fx: \"type\", x: \"group\", y: \"mean\", fill: \"group\", fillOpacity: 0.8\n      }),\n      Plot.ruleY([0], { stroke: ancova_theme.muted }),\n      Plot.text(ancova_barData, {\n        fx: \"type\", x: \"group\",\n        y: d => d.mean >= 0 ? d.mean + 0.12 : d.mean - 0.12,\n        text: d => ancova_formatCoef(d.mean, 2),\n        fontSize: 11, fill: ancova_theme.text, textAnchor: \"middle\"\n      })\n    ]\n  }));\n}\n```\n\n```{ojs}\n//| echo: false\nancova_readouts = html`<div class=\"ojs-readouts\">\n  ${ancova_pill(\"True effect τ\", ancova_formatCoef(ancova_trueEffect, 2), \"good\")}\n  ${ancova_pill(\"Unadjusted Ȳ_B−Ȳ_A\", ancova_formatCoef(ancova_unadjDiff, 2))}\n  ${ancova_pill(\"Adjusted (ANCOVA)\", ancova_formatCoef(ancova_adjDiff, 2), \"info\")}\n  ${ancova_pill(\"Bias\", ancova_formatCoef(ancova_bias, 2), Math.abs(ancova_bias) > 0.3 ? \"warning\" : \"good\")}\n  ${ancova_pill(\"Recovery err\", ancova_formatCoef(ancova_recoveryErr, 2), Math.abs(ancova_recoveryErr) > 0.3 ? \"warning\" : \"good\")}\n  ${ancova_pill(\"Within slope b_w\", ancova_formatCoef(ancova_bWithin, 2))}\n</div>`\n```\n\n```{ojs}\n//| echo: false\nancova_reset = ancova_resetControls([\n  { input: viewof ancova_confounding, value: 0.5 },\n  { input: viewof ancova_trueEffect,  value: 0.5 }\n], { label: \"Reset\" })\n```\n\n```{ojs}\n//| echo: false\nancova_sr = ancova_srSummary(\"ch02-ancova\",\n  `True effect ${ancova_formatCoef(ancova_trueEffect, 2)}. Unadjusted difference ${ancova_formatCoef(ancova_unadjDiff, 2)}, adjusted (ANCOVA) difference ${ancova_formatCoef(ancova_adjDiff, 2)}. Bias ${ancova_formatCoef(ancova_bias, 2)}, recovery error ${ancova_formatCoef(ancova_recoveryErr, 2)}, pooled within-group slope ${ancova_formatCoef(ancova_bWithin, 2)}.`)\n```\n\n```{ojs}\n//| echo: false\nancova_app = html`<div class=\"ojs-app\" role=\"group\" aria-label=\"Adjusted vs unadjusted group means under a confounding covariate\">\n  <div class=\"ojs-controls\">${viewof ancova_confounding}${viewof ancova_trueEffect}<div class=\"ojs-control-group\" style=\"flex:0 0 auto;\">${ancova_reset}</div></div>\n  ${ancova_readouts}\n  <div style=\"display:flex; flex-wrap:wrap; gap:16px; align-items:flex-start; justify-content:center;\">\n    <div>\n      <div style=\"text-align:center; font-weight:600; margin-bottom:4px; color:${ancova_theme.text};\">Scatter with Regression Lines</div>\n      ${ancova_scatterPlot}\n    </div>\n    <div>\n      <div style=\"text-align:center; font-weight:600; margin-bottom:4px; color:${ancova_theme.text};\">Unadjusted vs. Adjusted Means</div>\n      ${ancova_barPlot}\n    </div>\n  </div>\n  ${ancova_sr}\n</div>`\n```\n\n::: {.callout-note}\n## What you should have seen\n- The **unadjusted** group difference moves with confounding strength even though the true effect never changed --- a covariate correlated with group membership biases the raw comparison.\n- The **ANCOVA-adjusted** difference stays much closer to the true effect across confounding levels, because it compares groups at the same covariate value (the grand mean of X); the remaining recovery error is ordinary finite-sample noise.\n- The gap between the unadjusted and adjusted bars *is* the omitted-variable bias; it shrinks to zero only when the groups do not differ on the covariate.\n:::\n\n### Visualizing the ANCOVA Model\n\n::: {.panel-tabset}\n### Output\n\n::: {.cell}\n\n```{.r .cell-code  code-fold=\"true\" code-summary=\"Show R Code\"}\nplot_predictions(model_ancova, condition = c(\"lrt\", \"school_name\")) +\n  scale_color_manual(values = c(ber640_colors[[\"primary\"]], ber640_colors[[\"secondary\"]])) +\n  scale_fill_manual(values = c(ber640_colors[[\"primary\"]], ber640_colors[[\"secondary\"]])) +\n  labs(\n    title = \"ANCOVA: Parallel Regression Lines\",\n    subtitle = \"Vertical gap = adjusted school difference, controlling for LRT\",\n    x = \"LRT Score\",\n    y = \"Predicted GCSE Score\",\n    color = \"School\",\n    fill = \"School\"\n  )\n```\n\n::: {.cell-output-display}\n![ANCOVA model: parallel regression lines for Battersea and Chelsea. Shaded bands are 95% confidence intervals for the predicted mean GCSE at each LRT value; the vertical distance between the lines represents the LRT-adjusted school difference.](02-ancova_files/figure-html/fig-ch2-ancova-plot-1.png){#fig-ch2-ancova-plot fig-alt='Line plot of predicted GCSE versus LRT with two parallel regression lines, one for Battersea and one for Chelsea. The lines share a common slope but differ in intercept, and the constant vertical gap between them is the LRT-adjusted school difference. Shaded confidence bands surround each line, showing the 95% confidence interval for the predicted mean GCSE at each LRT value.' width=2400}\n:::\n:::\n\n\n### Output Interpretation\n\n\n::: {.cell}\n::: {.cell-output-display}\n![](02-ancova_files/figure-html/unnamed-chunk-27-1.png){width=2400}\n:::\n:::\n\n- The two **parallel lines** confirm the ANCOVA model structure: same slope, different intercepts\n- The **shaded ribbon** around each line shows the 95% confidence interval for the predicted mean at each LRT value\n- The **vertical gap** between the lines is constant across all LRT values and equals the `school_nameChelsea` coefficient ($\\hat{\\beta}_2$)\n- This visualization makes clear that ANCOVA answers: \"At any given LRT score, how much do the schools differ in expected GCSE?\"\n\n### Code Explanation\n\n::: {.cell}\n\n```{.r .cell-code}\nplot_predictions(model_ancova, condition = c(\"lrt\", \"school_name\")) +\n  scale_color_manual(values = c(ber640_colors[[\"primary\"]], ber640_colors[[\"secondary\"]])) +\n  scale_fill_manual(values = c(ber640_colors[[\"primary\"]], ber640_colors[[\"secondary\"]])) +\n  labs(\n    title = \"ANCOVA: Parallel Regression Lines\",\n    subtitle = \"Vertical gap = adjusted school difference, controlling for LRT\",\n    x = \"LRT Score\",\n    y = \"Predicted GCSE Score\",\n    color = \"School\",\n    fill = \"School\"\n  )\n```\n\n::: {.cell-output-display}\n![](02-ancova_files/figure-html/unnamed-chunk-28-1.png){width=2400}\n:::\n:::\n\n- `plot_predictions()` from `marginaleffects` visualizes the model predictions\n- `condition = c(\"lrt\", \"school_name\")` shows how predicted GCSE varies across LRT values, separately for each school\n- The parallel lines reflect the ANCOVA assumption: the LRT slope is the same for both schools\n\n\n:::\n\n\n## R-squared and Multiple Correlation {#sec-ch2-r2}\n\nThe coefficient of determination generalizes straightforwardly to multiple regression. With $k$ predictors:\n\n$$\nR^2 = \\frac{\\text{MSS}}{\\text{TSS}} = 1 - \\frac{\\text{SSE}}{\\text{TSS}}\n$$\n\nThe **multiple correlation** $R$ is the Pearson correlation between observed $y_i$ and predicted $\\hat{y}_i$. The squared multiple correlation equals $R^2$.\n\n::: {.panel-tabset}\n### Output\n\n::: {.cell}\n\n```{.r .cell-code  code-fold=\"true\" code-summary=\"Show R Code\"}\n# Compare R-squared across nested models\nm0 <- lm(gcse ~ 1, data = two_schools)            # Intercept only\nm1 <- lm(gcse ~ school_name, data = two_schools)   # School only\nm2 <- lm(gcse ~ lrt, data = two_schools)            # LRT only\nm3 <- model_ancova                                   # Both\n\n# Names appear in output: m0 = intercept, m1 = school, m2 = LRT, m3 = ANCOVA\ncompare_performance(m0, m1, m2, m3) |> print_md()\n```\n\n::: {.cell-output-display}\n\n\nTable: Comparison of Model Performance Indices\n\n|Name | Model |  AIC (weights) | AICc (weights) |  BIC (weights) |   R2 | R2 (adj.) |  RMSE | Sigma |\n|:----|:-----:|:--------------:|:--------------:|:--------------:|:----:|:---------:|:-----:|:-----:|\n|m0   |    lm | 1285.1 (<.001) | 1285.1 (<.001) | 1291.3 (<.001) | 0.00 |      0.00 | 10.25 | 10.28 |\n|m1   |    lm | 1242.3 (<.001) | 1242.5 (<.001) | 1251.7 (<.001) | 0.23 |      0.23 |  8.99 |  9.04 |\n|m2   |    lm | 1209.7 (<.001) | 1209.9 (<.001) | 1219.1 (<.001) | 0.36 |      0.36 |  8.17 |  8.22 |\n|m3   |    lm | 1173.4 (>.999) | 1173.7 (>.999) | 1186.0 (>.999) | 0.49 |      0.49 |  7.31 |  7.37 |\n\n\n:::\n:::\n\n\n### Output Interpretation\n\n\n::: {.cell}\n::: {.cell-output-display}\n\n\nTable: Comparison of Model Performance Indices\n\n|Name | Model |  AIC (weights) | AICc (weights) |  BIC (weights) |   R2 | R2 (adj.) |  RMSE | Sigma |\n|:----|:-----:|:--------------:|:--------------:|:--------------:|:----:|:---------:|:-----:|:-----:|\n|m0   |    lm | 1285.1 (<.001) | 1285.1 (<.001) | 1291.3 (<.001) | 0.00 |      0.00 | 10.25 | 10.28 |\n|m1   |    lm | 1242.3 (<.001) | 1242.5 (<.001) | 1251.7 (<.001) | 0.23 |      0.23 |  8.99 |  9.04 |\n|m2   |    lm | 1209.7 (<.001) | 1209.9 (<.001) | 1219.1 (<.001) | 0.36 |      0.36 |  8.17 |  8.22 |\n|m3   |    lm | 1173.4 (>.999) | 1173.7 (>.999) | 1186.0 (>.999) | 0.49 |      0.49 |  7.31 |  7.37 |\n\n\n:::\n:::\n\n- **$R^2$ progression**: As we add predictors, $R^2$ increases (or stays the same). The intercept-only model explains 0% of variance; adding school or LRT alone explains some; the ANCOVA model with both explains the most\n- **AIC/BIC**: Lower values indicate better model fit, balancing complexity against explanatory power. Here the ANCOVA model has the lowest AIC and BIC, confirming that both predictors earn their place in the model\n- **Why $R^2$ and AIC/BIC can disagree**: Adding a predictor can never decrease $R^2$, so $R^2$ always favors the larger model --- even when the extra predictor contributes little. AIC and BIC instead penalize each extra parameter, so they can *increase* (worsen) when a predictor does not earn its keep. This is why $R^2$ alone should not be used to choose between nested models\n- **RMSE**: The root mean squared error decreases as the model improves --- predictions become more accurate\n- The improvement from the school-only model to the ANCOVA model shows the value of controlling for LRT\n\n### Code Explanation\n\n::: {.cell}\n\n```{.r .cell-code}\n# Compare R-squared across nested models\nm0 <- lm(gcse ~ 1, data = two_schools)            # Intercept only\nm1 <- lm(gcse ~ school_name, data = two_schools)   # School only\nm2 <- lm(gcse ~ lrt, data = two_schools)            # LRT only\nm3 <- model_ancova                                   # Both\n\n# Names appear in output: m0 = intercept, m1 = school, m2 = LRT, m3 = ANCOVA\ncompare_performance(m0, m1, m2, m3) |> print_md()\n```\n\n::: {.cell-output-display}\n\n\nTable: Comparison of Model Performance Indices\n\n|Name | Model |  AIC (weights) | AICc (weights) |  BIC (weights) |   R2 | R2 (adj.) |  RMSE | Sigma |\n|:----|:-----:|:--------------:|:--------------:|:--------------:|:----:|:---------:|:-----:|:-----:|\n|m0   |    lm | 1285.1 (<.001) | 1285.1 (<.001) | 1291.3 (<.001) | 0.00 |      0.00 | 10.25 | 10.28 |\n|m1   |    lm | 1242.3 (<.001) | 1242.5 (<.001) | 1251.7 (<.001) | 0.23 |      0.23 |  8.99 |  9.04 |\n|m2   |    lm | 1209.7 (<.001) | 1209.9 (<.001) | 1219.1 (<.001) | 0.36 |      0.36 |  8.17 |  8.22 |\n|m3   |    lm | 1173.4 (>.999) | 1173.7 (>.999) | 1186.0 (>.999) | 0.49 |      0.49 |  7.31 |  7.37 |\n\n\n:::\n:::\n\n- `compare_performance()` from `easystats` provides a side-by-side comparison of model fit statistics\n- We can see how much each predictor (and their combination) contributes to explaining variance in GCSE\n- $R^2$ for the ANCOVA model (both predictors) is greater than for either predictor alone\n\n\n:::\n\n\n## Sequential and Partial Tests {#sec-ch2-tests}\n\nWhen we have multiple predictors, there are different ways to partition the Model Sum of Squares. The two main approaches are:\n\n### Type I (Sequential) Sums of Squares\n\nPredictors are added one at a time in the order specified. The SS for each predictor represents its **additional** contribution given the predictors already in the model.\n\n### Type III (Unique/Partial) Sums of Squares\n\nEach predictor's SS represents its **unique** contribution, controlling for all other predictors. This is typically what we want for hypothesis testing in observational studies.\n\n::: {.panel-tabset}\n### Output\n\n::: {.cell}\n\n```{.r .cell-code  code-fold=\"true\" code-summary=\"Show R Code\"}\n# Type I (Sequential) SS - order matters!\nanova(model_ancova)\n```\n\n::: {.cell-output-display}\n<div class=\"kable-table\">\n\n|            |  Df|   Sum Sq|    Mean Sq|   F value| Pr(>F)|\n|:-----------|---:|--------:|----------:|---------:|------:|\n|lrt         |   1| 6530.485| 6530.48515| 120.18308|      0|\n|school_name |   1| 2290.182| 2290.18159|  42.14711|      0|\n|Residuals   | 168| 9128.752|   54.33781|        NA|     NA|\n\n</div>\n:::\n:::\n\n\n\n::: {.cell}\n\n```{.r .cell-code  code-fold=\"true\" code-summary=\"Show R Code\"}\n# Type III (Unique/Partial) SS - each predictor controlling for the other.\n# Refit a LOCAL copy with sum-to-zero contrasts so the Type III tests are\n# correctly specified (textbook convention); model_ancova is left untouched.\nmodel_typeiii <- update(model_ancova, contrasts = list(school_name = contr.sum))\n\n# car is installed; we namespace car::Anova (no library(car) needed)\ncar::Anova(model_typeiii, type = 3)\n```\n\n::: {.cell-output-display}\n<div class=\"kable-table\">\n\n|            |   Sum Sq|  Df|   F value|    Pr(>F)|\n|:-----------|--------:|---:|---------:|---------:|\n|(Intercept) |  347.715|   1|  6.399135| 0.0123378|\n|lrt         | 4688.637|   1| 86.286817| 0.0000000|\n|school_name | 2290.182|   1| 42.147109| 0.0000000|\n|Residuals   | 9128.752| 168|        NA|        NA|\n\n</div>\n:::\n:::\n\n\n### Output Interpretation\n\n\n::: {.cell}\n::: {.cell-output-display}\n<div class=\"kable-table\">\n\n|            |  Df|   Sum Sq|    Mean Sq|   F value| Pr(>F)|\n|:-----------|---:|--------:|----------:|---------:|------:|\n|lrt         |   1| 6530.485| 6530.48515| 120.18308|      0|\n|school_name |   1| 2290.182| 2290.18159|  42.14711|      0|\n|Residuals   | 168| 9128.752|   54.33781|        NA|     NA|\n\n</div>\n:::\n:::\n\n- **Type I SS**: The SS for `lrt` is tested first (its total contribution), then `school_name` is tested for its *additional* contribution beyond LRT. Reversing the order would change the individual SS values\n- **Type III SS**: Each predictor's SS reflects its *unique* contribution after controlling for the other. The results are the same regardless of the order in which variables are listed in the model formula\n- **$F$-statistics and $p$-values**: In both types, these test whether each predictor significantly improves the model. In the Type III table above, `school_name` is significant ($F \\approx 42.15$, $p < .001$), confirming that the two schools differ in GCSE even after controlling for LRT; `lrt` is likewise significant ($F \\approx 86.29$, $p < .001$) after controlling for school. (Note `lrt`'s Type III $F \\approx 86.29$ is a bit *smaller* than its Type I $F \\approx 120.18$: entered first, Type I credits LRT with the variance it shares with school, whereas Type III counts only LRT's unique contribution.)\n\n### Code Explanation\n\n::: {.cell}\n\n```{.r .cell-code}\n# Type I (Sequential) SS - order matters!\nanova(model_ancova)\n```\n\n::: {.cell-output-display}\n<div class=\"kable-table\">\n\n|            |  Df|   Sum Sq|    Mean Sq|   F value| Pr(>F)|\n|:-----------|---:|--------:|----------:|---------:|------:|\n|lrt         |   1| 6530.485| 6530.48515| 120.18308|      0|\n|school_name |   1| 2290.182| 2290.18159|  42.14711|      0|\n|Residuals   | 168| 9128.752|   54.33781|        NA|     NA|\n\n</div>\n:::\n:::\n\n- `anova()` produces **Type I** (sequential) SS: each predictor is tested after adding it to all preceding predictors\n- `car::Anova(..., type = 3)` produces **Type III** (unique) SS: each predictor is tested controlling for all others\n- In balanced designs, Types I and III give the same results. In unbalanced designs (common in observational research), they can differ\n\n\n:::\n\n::: {.callout-note}\n## Type I vs Type III Sums of Squares\n| Feature | Type I (Sequential) | Type III (Unique) |\n|:--------|:-------------------|:-----------------|\n| Depends on order? | Yes | No |\n| Tests for... | Additional contribution | Unique contribution |\n| Best for... | Hierarchical model building | Hypothesis testing |\n| Default in R | `anova()` | `car::Anova(type = 3)` |\n\n**Rule of thumb**: Use Type III for testing individual predictors in observational studies, where there is no natural ordering of variables.\n:::\n\n::: {.callout-warning}\n## Caveat: Type III SS and Contrast Coding\nType III sums of squares require care with **contrast coding** for categorical predictors. With the usual treatment (dummy) coding, the Type III test of a *main effect* that is also involved in an **interaction** is not the hypothesis most people intend; the standard fix is to use orthogonal, sum-to-zero contrasts (e.g. `contr.sum`) --- which is why the chunk above refits a local copy with `contrasts = list(school_name = contr.sum)`.\n\nThis ANCOVA has **no interaction**, so the term-level Type III tests are *contrast-invariant*: the $F$-values for `lrt` and `school_name` are identical under treatment or sum-to-zero coding, and they coincide with the Type II tests. In fact, for `school_name` all three of the following give exactly the same $F \\approx 42.15$ ($p < .001$):\n\n- the Type III (and Type II) test from `car::Anova()` above;\n- the nested-model comparison `anova(lm(gcse ~ lrt, data = two_schools), model_ancova)`;\n- the $t$-test of the `school_nameChelsea` coefficient in the model summary, since $t^2 = F$ exactly (the coefficient has $t \\approx 6.49$, and the Type III $F \\approx 42.15$).\n\nThe equivalence breaks down only once the model contains an interaction, where the choice of contrasts genuinely changes what the Type III main-effect rows test.\n:::\n\n::: {.panel-tabset}\n### Output\n\n::: {.cell}\n\n```{.r .cell-code  code-fold=\"true\" code-summary=\"Show R Code\"}\nss_lrt_only <- summary(lm(gcse ~ lrt, data = two_schools))$r.squared\nss_school_only <- summary(lm(gcse ~ school_name, data = two_schools))$r.squared\nss_both <- summary(model_ancova)$r.squared\n\nunique_lrt <- ss_both - ss_school_only\nunique_school <- ss_both - ss_lrt_only\nshared_r2 <- ss_lrt_only + ss_school_only - ss_both\n\n# Draw Venn with annotated circles\ntheta <- seq(0, 2 * pi, length.out = 100)\ncircle_lrt <- tibble(x = -0.55 + 1.3 * cos(theta), y = 1.3 * sin(theta), group = \"LRT\")\ncircle_sch <- tibble(x = 0.55 + 1.3 * cos(theta), y = 1.3 * sin(theta), group = \"School\")\n\nggplot() +\n  geom_polygon(data = circle_lrt, aes(x, y), fill = ber640_colors[[\"primary\"]], alpha = 0.2) +\n  geom_polygon(data = circle_sch, aes(x, y), fill = ber640_colors[[\"secondary\"]], alpha = 0.2) +\n  annotate(\"text\", x = -1.3, y = 0, label = paste0(\"LRT unique\\n\", round(unique_lrt * 100, 1), \"%\"),\n           color = ber640_colors[[\"primary\"]], size = 4.5, fontface = \"bold\") +\n  annotate(\"text\", x = 0, y = 0, label = paste0(\"Shared\\n\", round(shared_r2 * 100, 1), \"%\"),\n           color = ber640_colors[[\"success\"]], size = 4.5, fontface = \"bold\") +\n  annotate(\"text\", x = 1.3, y = 0, label = paste0(\"School unique\\n\", round(unique_school * 100, 1), \"%\"),\n           color = ber640_colors[[\"secondary\"]], size = 4.5, fontface = \"bold\") +\n  annotate(\"text\", x = 0, y = -2, hjust = 0.5, size = 3.8, color = \"grey30\", fontface = \"italic\",\n           label = \"Type I: shared → first predictor entered\\nType III: only unique portions tested\") +\n  coord_equal(xlim = c(-2.5, 2.5), ylim = c(-2.5, 2)) +\n  labs(title = \"Type I vs Type III: Who Gets Credit for Shared Variance?\",\n       subtitle = paste0(\"Total R² = \", round(ss_both * 100, 1), \"%\")) +\n  theme_void(base_size = 14) +\n  theme(plot.title = element_text(face = \"bold\", size = 15, hjust = 0.5),\n        plot.subtitle = element_text(color = \"grey40\", hjust = 0.5))\n```\n\n::: {.cell-output-display}\n![Variance partitioning in ANCOVA. Type I SS assigns shared variance to the first predictor entered; Type III SS tests only the unique portions. The diagram is schematic and not drawn to scale --- circle sizes and overlap are fixed, so the areas are not proportional to the variance (only the labelled percentages are exact).](02-ancova_files/figure-html/fig-ch2-ss-venn-1.png){#fig-ch2-ss-venn fig-alt='Venn diagram with two overlapping circles representing the variance explained by school and LRT. The overlap represents shared variance. Annotations contrast Type I sums of squares, which assign the shared portion to whichever predictor is entered first, with Type III sums of squares, which test only each predictor\\'s unique contribution. The diagram clarifies why predictor order matters for Type I but not Type III tests. It is schematic and not drawn to scale: the circle sizes and overlap are fixed and are not proportional to the variance, so only the labelled percentages are exact.' width=2400}\n:::\n:::\n\n\n### Output Interpretation\n\n\n::: {.cell}\n::: {.cell-output-display}\n![](02-ancova_files/figure-html/unnamed-chunk-33-1.png){width=2400}\n:::\n:::\n\n- **LRT unique**: Variance in GCSE explained only by LRT (not school). This is the same regardless of Type I or Type III\n- **School unique**: Variance in GCSE explained only by school (not LRT). Also the same for both SS types\n- **Shared**: Variance that both LRT and school could explain. Type I assigns this to whichever predictor is entered first; Type III does not assign the shared variance to either predictor, instead testing each predictor's unique increment after controlling for the other\n- The total $R^2$ is the union of all three regions. The unexplained variance ($1 - R^2$) lies outside both circles\n\n### Code Explanation\n\n::: {.cell}\n\n```{.r .cell-code}\nss_lrt_only <- summary(lm(gcse ~ lrt, data = two_schools))$r.squared\nss_school_only <- summary(lm(gcse ~ school_name, data = two_schools))$r.squared\nss_both <- summary(model_ancova)$r.squared\n\nunique_lrt <- ss_both - ss_school_only\nunique_school <- ss_both - ss_lrt_only\nshared_r2 <- ss_lrt_only + ss_school_only - ss_both\n\n# Draw Venn with annotated circles\ntheta <- seq(0, 2 * pi, length.out = 100)\ncircle_lrt <- tibble(x = -0.55 + 1.3 * cos(theta), y = 1.3 * sin(theta), group = \"LRT\")\ncircle_sch <- tibble(x = 0.55 + 1.3 * cos(theta), y = 1.3 * sin(theta), group = \"School\")\n\nggplot() +\n  geom_polygon(data = circle_lrt, aes(x, y), fill = ber640_colors[[\"primary\"]], alpha = 0.2) +\n  geom_polygon(data = circle_sch, aes(x, y), fill = ber640_colors[[\"secondary\"]], alpha = 0.2) +\n  annotate(\"text\", x = -1.3, y = 0, label = paste0(\"LRT unique\\n\", round(unique_lrt * 100, 1), \"%\"),\n           color = ber640_colors[[\"primary\"]], size = 4.5, fontface = \"bold\") +\n  annotate(\"text\", x = 0, y = 0, label = paste0(\"Shared\\n\", round(shared_r2 * 100, 1), \"%\"),\n           color = ber640_colors[[\"success\"]], size = 4.5, fontface = \"bold\") +\n  annotate(\"text\", x = 1.3, y = 0, label = paste0(\"School unique\\n\", round(unique_school * 100, 1), \"%\"),\n           color = ber640_colors[[\"secondary\"]], size = 4.5, fontface = \"bold\") +\n  annotate(\"text\", x = 0, y = -2, hjust = 0.5, size = 3.8, color = \"grey30\", fontface = \"italic\",\n           label = \"Type I: shared → first predictor entered\\nType III: only unique portions tested\") +\n  coord_equal(xlim = c(-2.5, 2.5), ylim = c(-2.5, 2)) +\n  labs(title = \"Type I vs Type III: Who Gets Credit for Shared Variance?\",\n       subtitle = paste0(\"Total R² = \", round(ss_both * 100, 1), \"%\")) +\n  theme_void(base_size = 14) +\n  theme(plot.title = element_text(face = \"bold\", size = 15, hjust = 0.5),\n        plot.subtitle = element_text(color = \"grey40\", hjust = 0.5))\n```\n\n::: {.cell-output-display}\n![](02-ancova_files/figure-html/unnamed-chunk-34-1.png){width=2400}\n:::\n:::\n\n- We compute $R^2$ from three models (LRT-only, school-only, both) to partition variance into unique and shared components\n- `unique_lrt` = total $R^2$ minus school-only $R^2$: the variance explained by LRT that school cannot explain\n- `unique_school` = total $R^2$ minus LRT-only $R^2$: the variance explained by school that LRT cannot explain\n- `shared_r2` = the overlap where both predictors compete for credit\n- The Venn diagram uses `geom_polygon()` with parametric circles to visualize these regions\n\n\n:::\n\n\n## Omitted Variable Bias {#sec-ch2-ovb}\n\nOne of the most important concepts in applied statistics is **omitted variable bias (OVB)**. When a relevant variable is left out of the model, the estimated coefficients for the included variables may be biased.\n\n### The OVB Formula\n\nSuppose the true model is:\n\n$$\ny_i = \\alpha + \\beta_1 x_{1i} + \\beta_2 x_{2i} + \\epsilon_i\n$$\n\nBut we estimate the misspecified model that omits $x_2$:\n\n$$\ny_i = \\alpha^* + \\beta_1^* x_{1i} + \\epsilon_i^*\n$$\n\nThe expected value of $b_1^*$ is:\n\n$$\n\\text{E}(b_1^*) = \\beta_1 + r_{21} \\frac{s_2}{s_1} \\beta_2 \\neq \\beta_1\n$$ {#eq-ch2-ovb}\n\nwhere $r_{21}$ is the correlation between $x_1$ and $x_2$, and $s_1, s_2$ are their standard deviations. In this formula $x_1$ is the **included** predictor (school) and $x_2$ is the **omitted** one (LRT), so the $\\beta_2$ appearing here is LRT's coefficient --- distinct from the $\\beta_2$ in the ANCOVA model above, which denotes the school coefficient.\n\n::: {.callout-important}\n## When Does OVB Occur?\nOmitted variable bias requires **both**:\n\n1. The omitted variable $x_2$ affects $y$ (i.e., $\\beta_2 \\neq 0$)\n2. The omitted variable $x_2$ is correlated with the included variable $x_1$ (i.e., $r_{21} \\neq 0$)\n\nIf either condition fails, the bias is zero. Randomization can eliminate condition (2), which is why randomized experiments are the gold standard for causal inference.\n:::\n\n::: {.callout-tip}\n## Predicting the Direction of OVB Bias\nThe sign of the bias term $r_{21} \\cdot (s_2/s_1) \\cdot \\beta_2$ tells you whether omitting $x_2$ will make $b_1^*$ too large or too small:\n\n| Sign of $r_{21}$ | Sign of $\\beta_2$ | Direction of bias |\n|:------------------|:-------------------|:-----------------|\n| Positive | Positive | Upward (overestimate) |\n| Positive | Negative | Downward (underestimate) |\n| Negative | Positive | Downward (underestimate) |\n| Negative | Negative | Upward (overestimate) |\n:::\n\n### OVB Mechanism\n\n::: {.panel-tabset}\n### Output\n\n::: {.cell}\n\n```{.r .cell-code  code-fold=\"true\" code-summary=\"Show R Code\"}\np_a <- ggplot(two_schools, aes(x = school_name, y = lrt, fill = school_name)) +\n  geom_violin(alpha = 0.35, color = NA) +\n  geom_boxplot(width = 0.25, outlier.shape = NA, alpha = 0.7) +\n  scale_fill_manual(values = c(ber640_colors[[\"primary\"]], ber640_colors[[\"secondary\"]])) +\n  labs(title = \"A: Condition 2\", subtitle = \"School correlated with LRT\",\n       x = NULL, y = \"LRT Score\") +\n  theme(legend.position = \"none\")\n\np_b <- ggplot(two_schools, aes(x = lrt, y = gcse)) +\n  geom_point(alpha = 0.25, color = ber640_colors[[\"primary\"]]) +\n  geom_smooth(method = \"lm\", formula = y ~ x, se = TRUE,\n              color = ber640_colors[[\"secondary\"]], fill = ber640_colors[[\"secondary\"]], alpha = 0.15) +\n  labs(title = \"B: Condition 1\", subtitle = \"LRT predicts GCSE\",\n       x = \"LRT Score\", y = \"GCSE Score\")\n\nschool_means <- two_schools |> group_by(school_name) |>\n  summarise(mean_gcse = mean(gcse, na.rm = TRUE), .groups = \"drop\")\n\np_c <- ggplot(two_schools, aes(x = school_name, y = gcse, fill = school_name)) +\n  geom_violin(alpha = 0.3, color = NA) +\n  geom_boxplot(width = 0.25, outlier.shape = NA, alpha = 0.7) +\n  geom_point(data = school_means, aes(y = mean_gcse), shape = 23, size = 4,\n             color = \"grey20\", fill = \"white\", stroke = 0.8) +\n  scale_fill_manual(values = c(ber640_colors[[\"primary\"]], ber640_colors[[\"secondary\"]])) +\n  labs(title = \"C: Biased Result\", subtitle = \"Raw school gap (confounded)\",\n       x = NULL, y = \"GCSE Score\") +\n  theme(legend.position = \"none\")\n\np_a | p_b | p_c\n```\n\n::: {.cell-output-display}\n![The two conditions for OVB, plus the resulting bias. (A) School correlates with LRT (condition 2). (B) LRT predicts GCSE (condition 1). (C) The raw, confounded school gap in GCSE that results when both conditions hold and LRT is omitted.](02-ancova_files/figure-html/fig-ch2-ovb-mechanism-1.png){#fig-ch2-ovb-mechanism fig-alt='Three-panel figure illustrating the conditions for omitted variable bias and its consequence. Panel A shows violin and box plots demonstrating that school is correlated with LRT intake scores, satisfying the second OVB condition. Panel B shows a scatter with a fitted line confirming that LRT is a significant predictor of GCSE, satisfying the first condition. Panel C shows violin and box plots of GCSE by school with the group means marked, displaying the raw confounded school gap that results because both conditions hold and LRT is omitted from a regression of GCSE on school.' width=3600}\n:::\n:::\n\n\n### Output Interpretation\n\n\n::: {.cell}\n::: {.cell-output-display}\n![](02-ancova_files/figure-html/unnamed-chunk-35-1.png){width=3600}\n:::\n:::\n\n- **Panel A**: The LRT distributions clearly differ between schools. Chelsea students enter with higher prior achievement, confirming that school and LRT are correlated ($r_{21} \\neq 0$)\n- **Panel B**: The strong positive slope confirms that LRT is a meaningful predictor of GCSE ($\\beta_2 \\neq 0$). Both OVB conditions are satisfied\n- **Panel C**: The raw school gap (white diamonds) is larger than the LRT-adjusted school difference because it includes the confounding influence of LRT. In this demonstration we treat the two-predictor model as the data-generating model, so the larger bivariate gap overstates the adjusted coefficient --- exactly what the OVB formula (@eq-ch2-ovb) predicts. (In the real GCSE data, this removes bias only with respect to LRT, not other unmeasured confounders; see @sec-ch2-confounding.)\n\n### Code Explanation\n\n::: {.cell}\n\n```{.r .cell-code}\np_a <- ggplot(two_schools, aes(x = school_name, y = lrt, fill = school_name)) +\n  geom_violin(alpha = 0.35, color = NA) +\n  geom_boxplot(width = 0.25, outlier.shape = NA, alpha = 0.7) +\n  scale_fill_manual(values = c(ber640_colors[[\"primary\"]], ber640_colors[[\"secondary\"]])) +\n  labs(title = \"A: Condition 2\", subtitle = \"School correlated with LRT\",\n       x = NULL, y = \"LRT Score\") +\n  theme(legend.position = \"none\")\n\np_b <- ggplot(two_schools, aes(x = lrt, y = gcse)) +\n  geom_point(alpha = 0.25, color = ber640_colors[[\"primary\"]]) +\n  geom_smooth(method = \"lm\", formula = y ~ x, se = TRUE,\n              color = ber640_colors[[\"secondary\"]], fill = ber640_colors[[\"secondary\"]], alpha = 0.15) +\n  labs(title = \"B: Condition 1\", subtitle = \"LRT predicts GCSE\",\n       x = \"LRT Score\", y = \"GCSE Score\")\n\nschool_means <- two_schools |> group_by(school_name) |>\n  summarise(mean_gcse = mean(gcse, na.rm = TRUE), .groups = \"drop\")\n\np_c <- ggplot(two_schools, aes(x = school_name, y = gcse, fill = school_name)) +\n  geom_violin(alpha = 0.3, color = NA) +\n  geom_boxplot(width = 0.25, outlier.shape = NA, alpha = 0.7) +\n  geom_point(data = school_means, aes(y = mean_gcse), shape = 23, size = 4,\n             color = \"grey20\", fill = \"white\", stroke = 0.8) +\n  scale_fill_manual(values = c(ber640_colors[[\"primary\"]], ber640_colors[[\"secondary\"]])) +\n  labs(title = \"C: Biased Result\", subtitle = \"Raw school gap (confounded)\",\n       x = NULL, y = \"GCSE Score\") +\n  theme(legend.position = \"none\")\n\np_a | p_b | p_c\n```\n\n::: {.cell-output-display}\n![](02-ancova_files/figure-html/unnamed-chunk-36-1.png){width=3600}\n:::\n:::\n\n- **Panel A** (Condition 2): A violin + boxplot showing that Chelsea students have higher LRT scores at intake than Battersea students. This establishes that school assignment is correlated with the omitted variable (LRT)\n- **Panel B** (Condition 1): A scatterplot confirming that LRT strongly predicts GCSE scores. This establishes that the omitted variable affects the outcome\n- **Panel C** (Biased Result): The raw GCSE distributions by school, with diamond markers at the group means. The apparent school gap is confounded --- it mixes the LRT-adjusted school difference with pre-existing ability differences\n- Both conditions are met, so omitting LRT from the model biases the school coefficient upward\n\n\n:::\n\n### OVB Demonstration\n\n::: {.panel-tabset}\n### Output\n\n::: {.cell}\n\n```{.r .cell-code  code-fold=\"true\" code-summary=\"Show R Code\"}\n# Demonstrate OVB: compare bivariate vs ANCOVA estimate for school effect\nmodel_bivariate <- lm(gcse ~ school_name, data = two_schools)\nmodel_adjusted  <- lm(gcse ~ school_name + lrt, data = two_schools)\n\nbind_rows(\n  tidy_model(model_bivariate) |> mutate(model = \"Bivariate (omits LRT)\"),\n  tidy_model(model_adjusted)  |> mutate(model = \"Adjusted (includes LRT)\")\n) |>\n  filter(term != \"(Intercept)\") |>\n  select(model, term, estimate, std.error) |>\n  kable(digits = 3)\n```\n\n::: {.cell-output-display}\n\n\n|model                   |term               | estimate| std.error|\n|:-----------------------|:------------------|--------:|---------:|\n|Bivariate (omits LRT)   |school_nameChelsea |    9.852|     1.386|\n|Adjusted (includes LRT) |school_nameChelsea |    7.514|     1.157|\n|Adjusted (includes LRT) |lrt                |    0.636|     0.068|\n\n\n:::\n:::\n\n\n### Output Interpretation\n\n\n::: {.cell}\n::: {.cell-output-display}\n\n\n|model                   |term               | estimate| std.error|\n|:-----------------------|:------------------|--------:|---------:|\n|Bivariate (omits LRT)   |school_nameChelsea |    9.852|     1.386|\n|Adjusted (includes LRT) |school_nameChelsea |    7.514|     1.157|\n|Adjusted (includes LRT) |lrt                |    0.636|     0.068|\n\n\n:::\n:::\n\n- **Bivariate estimate**: The raw school difference ignoring LRT. This is larger than the LRT-adjusted school difference because it includes the confounding influence of pre-existing ability differences\n- **Adjusted estimate**: The school difference controlling for LRT. This is smaller, reflecting the removal of the confounding bias\n- **The reduction** between the two estimates is the **omitted variable bias** --- the amount by which ignoring LRT distorts the school effect estimate\n- Use the OVB formula (@eq-ch2-ovb) to verify: the predicted bias should match the observed difference between the two estimates\n\n### Code Explanation\n\n::: {.cell}\n\n```{.r .cell-code}\n# Demonstrate OVB: compare bivariate vs ANCOVA estimate for school effect\nmodel_bivariate <- lm(gcse ~ school_name, data = two_schools)\nmodel_adjusted  <- lm(gcse ~ school_name + lrt, data = two_schools)\n\nbind_rows(\n  tidy_model(model_bivariate) |> mutate(model = \"Bivariate (omits LRT)\"),\n  tidy_model(model_adjusted)  |> mutate(model = \"Adjusted (includes LRT)\")\n) |>\n  filter(term != \"(Intercept)\") |>\n  select(model, term, estimate, std.error) |>\n  kable(digits = 3)\n```\n\n::: {.cell-output-display}\n\n\n|model                   |term               | estimate| std.error|\n|:-----------------------|:------------------|--------:|---------:|\n|Bivariate (omits LRT)   |school_nameChelsea |    9.852|     1.386|\n|Adjusted (includes LRT) |school_nameChelsea |    7.514|     1.157|\n|Adjusted (includes LRT) |lrt                |    0.636|     0.068|\n\n\n:::\n:::\n\n- The bivariate coefficient is larger than the adjusted coefficient because it confounds the school difference with pre-existing LRT differences; treating the two-predictor model as the data-generating model here, the bivariate estimate overstates the adjusted coefficient\n- In the adjusted model, the school coefficient is smaller, reflecting the LRT-adjusted school difference after accounting for intake ability (adjusted only with respect to LRT, not other unmeasured confounders; see @sec-ch2-confounding)\n- This is OVB in action: LRT is a confounder (it affects GCSE and is correlated with school)\n\n\n:::\n\n### OVB Numerical Verification\n\n::: {.panel-tabset}\n### Output\n\n::: {.cell}\n\n```{.r .cell-code  code-fold=\"true\" code-summary=\"Show R Code\"}\n# Verify the OVB formula numerically\nd_chelsea <- as.numeric(two_schools$school_name == \"Chelsea\")\nr21 <- cor(d_chelsea, two_schools$lrt, use = \"complete.obs\")\ns1  <- sd(d_chelsea)\ns2  <- sd(two_schools$lrt, na.rm = TRUE)\nb_lrt <- coef(model_adjusted)[\"lrt\"]\n\npredicted_bias <- r21 * (s2 / s1) * b_lrt\nobserved_bias  <- coef(model_bivariate)[\"school_nameChelsea\"] -\n                  coef(model_adjusted)[\"school_nameChelsea\"]\n\ncat(\"Predicted bias (from OVB formula):\", round(predicted_bias, 3), \"\\n\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nPredicted bias (from OVB formula): 2.338 \n```\n\n\n:::\n\n```{.r .cell-code  code-fold=\"true\" code-summary=\"Show R Code\"}\ncat(\"Observed bias (actual difference): \", round(observed_bias,  3), \"\\n\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nObserved bias (actual difference):  2.338 \n```\n\n\n:::\n:::\n\n\n### Output Interpretation\n\n\n::: {.cell}\n::: {.cell-output .cell-output-stdout}\n\n```\nPredicted bias (from OVB formula): 2.338 \n```\n\n\n:::\n\n::: {.cell-output .cell-output-stdout}\n\n```\nObserved bias (actual difference):  2.338 \n```\n\n\n:::\n:::\n\n- The predicted bias from the OVB formula exactly matches the observed difference between the bivariate and adjusted estimates. This confirms that the formula is not an approximation --- it is an algebraic identity in OLS regression. The match is exact because the verification plugs in **sample** quantities (the sample $r_{21}$, $s_1$, $s_2$, and $\\beta_2$): it is the finite-sample (Frisch--Waugh--Lovell) identity, so no expectation is required for the equality to hold exactly\n- The positive bias means the bivariate coefficient is **larger** than the LRT-adjusted coefficient, consistent with the OVB direction table: $r_{21} > 0$ (Chelsea students have higher LRT) and $\\beta_2 > 0$ (higher LRT predicts higher GCSE), so the bias is upward\n- This numerical verification makes the abstract OVB formula concrete and verifiable\n\n### Code Explanation\n\n::: {.cell}\n\n```{.r .cell-code}\n# Verify the OVB formula numerically\nd_chelsea <- as.numeric(two_schools$school_name == \"Chelsea\")\nr21 <- cor(d_chelsea, two_schools$lrt, use = \"complete.obs\")\ns1  <- sd(d_chelsea)\ns2  <- sd(two_schools$lrt, na.rm = TRUE)\nb_lrt <- coef(model_adjusted)[\"lrt\"]\n\npredicted_bias <- r21 * (s2 / s1) * b_lrt\nobserved_bias  <- coef(model_bivariate)[\"school_nameChelsea\"] -\n                  coef(model_adjusted)[\"school_nameChelsea\"]\n\ncat(\"Predicted bias (from OVB formula):\", round(predicted_bias, 3), \"\\n\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nPredicted bias (from OVB formula): 2.338 \n```\n\n\n:::\n\n```{.r .cell-code}\ncat(\"Observed bias (actual difference): \", round(observed_bias,  3), \"\\n\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nObserved bias (actual difference):  2.338 \n```\n\n\n:::\n:::\n\n- We compute each component of the OVB formula: the correlation between the school dummy and LRT ($r_{21}$), the standard deviations ($s_1, s_2$), and the LRT coefficient ($\\beta_2$)\n- `predicted_bias` applies the formula: $r_{21} \\cdot (s_2/s_1) \\cdot \\beta_2$\n- `observed_bias` is the actual difference between the bivariate and adjusted school coefficients\n- If the formula is correct, these two values should be identical (up to rounding)\n\n\n:::\n\n\n## Confounding and Endogeneity {#sec-ch2-confounding}\n\nThe residual $\\epsilon_i$ represents the combined effects of all omitted variables plus measurement error. When a confounder $x_2$ is omitted:\n\n$$\n\\epsilon_i^* = \\beta_2 x_{2i} + \\epsilon_i\n$$\n\nSince $x_2$ is correlated with $x_1$ (and $x_2$ is now part of the error term), $\\epsilon_i^*$ becomes correlated with $x_1$. In econometrics, a variable correlated with the error term is called **endogenous**, and its coefficient will be biased.\n\n::: {.callout-warning}\n## Confounders vs Mediators\nNot every omitted variable is a confounder. A **mediator** is a variable on the causal pathway between $x$ and $y$:\n\n$$\n\\text{Father's education} \\rightarrow \\text{Son's education} \\rightarrow \\text{Son's income}\n$$\n\nIf we control for the mediator (son's education), we would remove the very effect we want to measure. **Never control for mediators** if the goal is to estimate the total effect of the predictor.\n\nKey rule: Only control for variables that are **common causes** of both the predictor and the outcome (confounders), not variables that are **consequences** of the predictor (mediators).\n:::\n\n::: {.panel-tabset}\n### Output\n\n::: {.cell}\n\n```{.r .cell-code  code-fold=\"true\" code-summary=\"Show R Code\"}\ndag_theme <- theme_void(base_size = 13) +\n  theme(plot.title = element_text(face = \"bold\", size = 14, hjust = 0.5),\n        plot.subtitle = element_text(color = \"grey40\", hjust = 0.5, size = 11))\n\np_conf <- ggplot() +\n  annotate(\"label\", x = 0.5, y = 0.85, label = \"LRT\\n(Confounder)\",\n           fill = ber640_colors[[\"warning\"]], color = \"white\", size = 4, fontface = \"bold\", label.size = 0) +\n  annotate(\"label\", x = 0.1, y = 0.2, label = \"School\",\n           fill = ber640_colors[[\"primary\"]], color = \"white\", size = 4, fontface = \"bold\", label.size = 0) +\n  annotate(\"label\", x = 0.9, y = 0.2, label = \"GCSE\",\n           fill = ber640_colors[[\"accent\"]], color = \"white\", size = 4, fontface = \"bold\", label.size = 0) +\n  annotate(\"segment\", x = 0.42, xend = 0.18, y = 0.75, yend = 0.33,\n           arrow = arrow(length = unit(0.25, \"cm\"), type = \"closed\"),\n           color = ber640_colors[[\"warning\"]], linewidth = 1) +\n  annotate(\"segment\", x = 0.58, xend = 0.82, y = 0.75, yend = 0.33,\n           arrow = arrow(length = unit(0.25, \"cm\"), type = \"closed\"),\n           color = ber640_colors[[\"warning\"]], linewidth = 1) +\n  annotate(\"segment\", x = 0.22, xend = 0.78, y = 0.2, yend = 0.2,\n           arrow = arrow(length = unit(0.25, \"cm\"), type = \"closed\"),\n           color = ber640_colors[[\"primary\"]], linewidth = 1.2) +\n  annotate(\"text\", x = 0.5, y = 0.05, label = \"Control for LRT (yes)\",\n           color = ber640_colors[[\"success\"]], size = 3.5, fontface = \"italic\") +\n  xlim(0, 1) + ylim(0, 1) +\n  labs(title = \"A: Confounder (control for it)\") + dag_theme\n\np_med <- ggplot() +\n  annotate(\"label\", x = 0.1, y = 0.5, label = \"School\",\n           fill = ber640_colors[[\"primary\"]], color = \"white\", size = 4, fontface = \"bold\", label.size = 0) +\n  annotate(\"label\", x = 0.5, y = 0.5, label = \"Teaching\\nQuality\",\n           fill = ber640_colors[[\"warning\"]], color = \"white\", size = 4, fontface = \"bold\", label.size = 0) +\n  annotate(\"label\", x = 0.9, y = 0.5, label = \"GCSE\",\n           fill = ber640_colors[[\"accent\"]], color = \"white\", size = 4, fontface = \"bold\", label.size = 0) +\n  annotate(\"segment\", x = 0.22, xend = 0.38, y = 0.5, yend = 0.5,\n           arrow = arrow(length = unit(0.25, \"cm\"), type = \"closed\"),\n           color = ber640_colors[[\"primary\"]], linewidth = 1.2) +\n  annotate(\"segment\", x = 0.62, xend = 0.78, y = 0.5, yend = 0.5,\n           arrow = arrow(length = unit(0.25, \"cm\"), type = \"closed\"),\n           color = ber640_colors[[\"warning\"]], linewidth = 1.2) +\n  annotate(\"text\", x = 0.5, y = 0.25, label = \"Do NOT control for mediator (no)\",\n           color = ber640_colors[[\"secondary\"]], size = 3.5, fontface = \"italic\") +\n  xlim(0, 1) + ylim(0, 1) +\n  labs(title = \"B: Mediator (do NOT control)\") + dag_theme\n\np_conf | p_med\n```\n\n::: {.cell-output-display}\n![Confounder vs mediator. (A) LRT is a common cause (confounder) — control for it. (B) Teaching quality is on the causal pathway (mediator) — do NOT control for it.](02-ancova_files/figure-html/fig-ch2-dag-1.png){#fig-ch2-dag fig-alt='Two directed acyclic graph panels contrasting confounders and mediators. Panel A shows LRT as a common cause of both school assignment and GCSE scores, making it a confounder that should be controlled for. Panel B shows teaching quality as a variable on the causal pathway from school to GCSE, making it a mediator that should not be controlled for. The diagrams illustrate when statistical adjustment is appropriate versus when it blocks the causal effect of interest.' width=3000}\n:::\n:::\n\n\n### Output Interpretation\n\n\n::: {.cell}\n::: {.cell-output-display}\n![](02-ancova_files/figure-html/unnamed-chunk-41-1.png){width=3000}\n:::\n:::\n\n- **Panel A**: LRT is a pre-treatment measure of prior achievement that is associated with school attended (higher-ability students tend to attend Chelsea) and predictive of GCSE; it therefore plays the role of a measured confounder (a proxy for intake differences). Controlling for LRT removes the part of the association it accounts for, yielding a contrast closer to the school's own contribution --- causal only insofar as LRT (plus any other adjusted variables) captures all common causes\n- **Panel B**: Teaching quality is a mediator --- it is one of the *mechanisms* through which a school affects GCSE scores. If the goal is the **total** school effect, controlling for teaching quality would remove part of that effect, underestimating it. (If the goal were instead a school's **direct** effect net of teaching quality, adjusting for it could be intended --- the right choice depends on which estimand you want.)\n- The key distinction: confounders create **spurious** associations (control for them); mediators transmit **genuine** effects (do not control for them)\n\n### Code Explanation\n\n::: {.cell}\n\n```{.r .cell-code}\ndag_theme <- theme_void(base_size = 13) +\n  theme(plot.title = element_text(face = \"bold\", size = 14, hjust = 0.5),\n        plot.subtitle = element_text(color = \"grey40\", hjust = 0.5, size = 11))\n\np_conf <- ggplot() +\n  annotate(\"label\", x = 0.5, y = 0.85, label = \"LRT\\n(Confounder)\",\n           fill = ber640_colors[[\"warning\"]], color = \"white\", size = 4, fontface = \"bold\", label.size = 0) +\n  annotate(\"label\", x = 0.1, y = 0.2, label = \"School\",\n           fill = ber640_colors[[\"primary\"]], color = \"white\", size = 4, fontface = \"bold\", label.size = 0) +\n  annotate(\"label\", x = 0.9, y = 0.2, label = \"GCSE\",\n           fill = ber640_colors[[\"accent\"]], color = \"white\", size = 4, fontface = \"bold\", label.size = 0) +\n  annotate(\"segment\", x = 0.42, xend = 0.18, y = 0.75, yend = 0.33,\n           arrow = arrow(length = unit(0.25, \"cm\"), type = \"closed\"),\n           color = ber640_colors[[\"warning\"]], linewidth = 1) +\n  annotate(\"segment\", x = 0.58, xend = 0.82, y = 0.75, yend = 0.33,\n           arrow = arrow(length = unit(0.25, \"cm\"), type = \"closed\"),\n           color = ber640_colors[[\"warning\"]], linewidth = 1) +\n  annotate(\"segment\", x = 0.22, xend = 0.78, y = 0.2, yend = 0.2,\n           arrow = arrow(length = unit(0.25, \"cm\"), type = \"closed\"),\n           color = ber640_colors[[\"primary\"]], linewidth = 1.2) +\n  annotate(\"text\", x = 0.5, y = 0.05, label = \"Control for LRT (yes)\",\n           color = ber640_colors[[\"success\"]], size = 3.5, fontface = \"italic\") +\n  xlim(0, 1) + ylim(0, 1) +\n  labs(title = \"A: Confounder (control for it)\") + dag_theme\n\np_med <- ggplot() +\n  annotate(\"label\", x = 0.1, y = 0.5, label = \"School\",\n           fill = ber640_colors[[\"primary\"]], color = \"white\", size = 4, fontface = \"bold\", label.size = 0) +\n  annotate(\"label\", x = 0.5, y = 0.5, label = \"Teaching\\nQuality\",\n           fill = ber640_colors[[\"warning\"]], color = \"white\", size = 4, fontface = \"bold\", label.size = 0) +\n  annotate(\"label\", x = 0.9, y = 0.5, label = \"GCSE\",\n           fill = ber640_colors[[\"accent\"]], color = \"white\", size = 4, fontface = \"bold\", label.size = 0) +\n  annotate(\"segment\", x = 0.22, xend = 0.38, y = 0.5, yend = 0.5,\n           arrow = arrow(length = unit(0.25, \"cm\"), type = \"closed\"),\n           color = ber640_colors[[\"primary\"]], linewidth = 1.2) +\n  annotate(\"segment\", x = 0.62, xend = 0.78, y = 0.5, yend = 0.5,\n           arrow = arrow(length = unit(0.25, \"cm\"), type = \"closed\"),\n           color = ber640_colors[[\"warning\"]], linewidth = 1.2) +\n  annotate(\"text\", x = 0.5, y = 0.25, label = \"Do NOT control for mediator (no)\",\n           color = ber640_colors[[\"secondary\"]], size = 3.5, fontface = \"italic\") +\n  xlim(0, 1) + ylim(0, 1) +\n  labs(title = \"B: Mediator (do NOT control)\") + dag_theme\n\np_conf | p_med\n```\n\n::: {.cell-output-display}\n![](02-ancova_files/figure-html/unnamed-chunk-42-1.png){width=3000}\n:::\n:::\n\n- We use `annotate(\"label\")` and `annotate(\"segment\")` to draw DAG-style diagrams without external packages\n- **Panel A** (Confounder): LRT sits above School and GCSE with arrows pointing down to both, forming a \"fork\" structure. This is the classic confounder pattern --- LRT is a common cause\n- **Panel B** (Mediator): Teaching Quality sits between School and GCSE on the causal pathway. Controlling for it would block the very effect we want to measure\n- `arrow()` creates directional edges; `label.size = 0` removes the border around node labels\n\n\n:::\n\n::: {.callout-warning}\n## Statistical Control Is Not Causal Control\nANCOVA adjusts for **measured** confounders. But if Chelsea also enrolls students who differ on parental SES, neighborhood resources, prior school quality, language background, or other factors driving selection into schools --- and these *pre-treatment* variables are not in the model --- the adjusted school difference still mixes school effects with unmeasured confounders. (Note that variables such as teacher experience or teaching quality are better viewed as *mechanisms* through which a school operates --- mediators of the school effect --- rather than as pre-treatment confounders, so they should not simply be lumped in with SES or neighborhood here; see @fig-ch2-dag.)\n\nThe ANCOVA estimate is causal only under the **strong ignorability assumption**: that the model includes *all* common causes of school selection and GCSE outcomes. In observational education data, this is rarely guaranteed. This is why randomized experiments are preferred for causal claims.\n:::\n\n\n## Collinearity {#sec-ch2-collinearity}\n\nWhen two predictors are highly correlated, they contain overlapping information about $y$. This creates **collinearity**, which inflates the standard errors of the regression coefficients.\n\n### The Effect of Collinearity\n\n::: {.panel-tabset}\n### Output\n\n::: {.cell}\n\n```{.r .cell-code  code-fold=\"true\" code-summary=\"Show R Code\"}\n# Check collinearity with VIF\ncheck_collinearity(model_ancova)\n```\n\n::: {.cell-output-display}\n<div class=\"kable-table\">\n\n|Term        |      VIF| VIF_CI_low| VIF_CI_high| SE_factor| Tolerance| Tolerance_CI_low| Tolerance_CI_high|\n|:-----------|--------:|----------:|-----------:|---------:|---------:|----------------:|-----------------:|\n|lrt         | 1.049616|   1.001993|    2.235509|  1.024507| 0.9527297|        0.4473253|         0.9980115|\n|school_name | 1.049616|   1.001993|    2.235509|  1.024507| 0.9527297|        0.4473253|         0.9980115|\n\n</div>\n:::\n:::\n\n\n### Output Interpretation\n\n\n::: {.cell}\n::: {.cell-output-display}\n<div class=\"kable-table\">\n\n|Term        |      VIF| VIF_CI_low| VIF_CI_high| SE_factor| Tolerance| Tolerance_CI_low| Tolerance_CI_high|\n|:-----------|--------:|----------:|-----------:|---------:|---------:|----------------:|-----------------:|\n|lrt         | 1.049616|   1.001993|    2.235509|  1.024507| 0.9527297|        0.4473253|         0.9980115|\n|school_name | 1.049616|   1.001993|    2.235509|  1.024507| 0.9527297|        0.4473253|         0.9980115|\n\n</div>\n:::\n:::\n\n- **VIF**: A VIF of 1 means no collinearity; higher values indicate more overlap between predictors. For example, VIF = 2 means the standard error is $\\sqrt{2} \\approx 1.41$ times larger than it would be without collinearity\n- **Tolerance**: The reciprocal of VIF ($1/\\text{VIF}$). Values below 0.2 signal concern\n- In our ANCOVA model, the VIF values should be low because LRT (continuous) and school (categorical) capture different types of information. High VIF would suggest that the two predictors are so correlated that their individual effects are hard to disentangle\n\n### Code Explanation\n\n::: {.cell}\n\n```{.r .cell-code}\n# Check collinearity with VIF\ncheck_collinearity(model_ancova)\n```\n\n::: {.cell-output-display}\n<div class=\"kable-table\">\n\n|Term        |      VIF| VIF_CI_low| VIF_CI_high| SE_factor| Tolerance| Tolerance_CI_low| Tolerance_CI_high|\n|:-----------|--------:|----------:|-----------:|---------:|---------:|----------------:|-----------------:|\n|lrt         | 1.049616|   1.001993|    2.235509|  1.024507| 0.9527297|        0.4473253|         0.9980115|\n|school_name | 1.049616|   1.001993|    2.235509|  1.024507| 0.9527297|        0.4473253|         0.9980115|\n\n</div>\n:::\n:::\n\n- `check_collinearity()` from `performance` computes the **Variance Inflation Factor (VIF)** for each predictor\n- VIF measures how much the variance of a coefficient is inflated due to correlation with other predictors\n- **Rule of thumb**: VIF > 5 suggests moderate collinearity; VIF > 10 suggests serious collinearity\n\n\n:::\n\n::: {.panel-tabset}\n### Output\n\n::: {.cell}\n\n```{.r .cell-code  code-fold=\"true\" code-summary=\"Show R Code\"}\nr_seq <- seq(0, 0.99, by = 0.005)\nvif_seq <- 1 / (1 - r_seq^2)\nr_actual <- abs(cor(two_schools$lrt, as.numeric(two_schools$school_name) - 1, use = \"complete.obs\"))\nvif_actual <- 1 / (1 - r_actual^2)\n\ncol_df <- tibble(r = r_seq, vif = vif_seq, se_mult = sqrt(vif_seq))\n\np1 <- ggplot(col_df, aes(x = r, y = vif)) +\n  geom_line(color = ber640_colors[[\"secondary\"]], linewidth = 1.2) +\n  geom_vline(xintercept = r_actual, linetype = \"dashed\", color = ber640_colors[[\"primary\"]]) +\n  geom_point(aes(x = r_actual, y = vif_actual), color = ber640_colors[[\"primary\"]], size = 4) +\n  annotate(\"text\", x = r_actual + 0.05, y = vif_actual + 1,\n           label = paste0(\"Our model\\nVIF = \", round(vif_actual, 2)),\n           color = ber640_colors[[\"primary\"]], size = 3.5, hjust = 0) +\n  coord_cartesian(ylim = c(1, 15)) +\n  labs(title = \"A: VIF grows with predictor correlation\",\n       x = \"|r| between predictors\", y = \"VIF\")\n\np2 <- ggplot(col_df, aes(x = r, y = se_mult)) +\n  geom_line(color = ber640_colors[[\"accent\"]], linewidth = 1.2) +\n  geom_hline(yintercept = 1, linetype = \"dotted\", color = \"grey50\") +\n  geom_vline(xintercept = r_actual, linetype = \"dashed\", color = ber640_colors[[\"primary\"]]) +\n  geom_point(aes(x = r_actual, y = sqrt(vif_actual)), color = ber640_colors[[\"primary\"]], size = 4) +\n  coord_cartesian(ylim = c(1, 4)) +\n  labs(title = \"B: SE inflation (\\u221AVIF)\",\n       x = \"|r| between predictors\", y = \"SE multiplier\")\n\np1 | p2\n```\n\n::: {.cell-output-display}\n![Collinearity inflates standard errors. As predictor correlation increases, VIF grows and the standard error multiplier (√VIF) shows how much less precise our estimates become.](02-ancova_files/figure-html/fig-ch2-collinearity-1.png){#fig-ch2-collinearity fig-alt='Two side-by-side line-plot panels, each with predictor correlation on the horizontal axis. Panel A plots the variance inflation factor (VIF), which rises sharply as the correlation between predictors increases toward one. Panel B plots the standard error multiplier (the square root of VIF) on its own vertical axis. A marked point on each panel shows where our ANCOVA model falls. Together the panels demonstrate that even moderate collinearity noticeably inflates standard errors, and high collinearity makes coefficient estimates very imprecise.' width=3000}\n:::\n:::\n\n\n### Output Interpretation\n\n\n::: {.cell}\n::: {.cell-output-display}\n![](02-ancova_files/figure-html/unnamed-chunk-45-1.png){width=3000}\n:::\n:::\n\n- **Panel A**: Our ANCOVA model (marked point) has low VIF, confirming that LRT and school are not highly collinear. The curve shows how dramatically VIF increases beyond $|r| = 0.8$\n- **Panel B**: The SE multiplier for our model is close to 1, meaning collinearity has minimal impact on our standard errors. At $|r| = 0.9$, the SE would be more than doubled\n- These plots illustrate why VIF > 10 (corresponding to $|r| > 0.95$) is considered problematic: standard errors become so inflated that coefficients are essentially uninterpretable\n\n### Code Explanation\n\n::: {.cell}\n\n```{.r .cell-code}\nr_seq <- seq(0, 0.99, by = 0.005)\nvif_seq <- 1 / (1 - r_seq^2)\nr_actual <- abs(cor(two_schools$lrt, as.numeric(two_schools$school_name) - 1, use = \"complete.obs\"))\nvif_actual <- 1 / (1 - r_actual^2)\n\ncol_df <- tibble(r = r_seq, vif = vif_seq, se_mult = sqrt(vif_seq))\n\np1 <- ggplot(col_df, aes(x = r, y = vif)) +\n  geom_line(color = ber640_colors[[\"secondary\"]], linewidth = 1.2) +\n  geom_vline(xintercept = r_actual, linetype = \"dashed\", color = ber640_colors[[\"primary\"]]) +\n  geom_point(aes(x = r_actual, y = vif_actual), color = ber640_colors[[\"primary\"]], size = 4) +\n  annotate(\"text\", x = r_actual + 0.05, y = vif_actual + 1,\n           label = paste0(\"Our model\\nVIF = \", round(vif_actual, 2)),\n           color = ber640_colors[[\"primary\"]], size = 3.5, hjust = 0) +\n  coord_cartesian(ylim = c(1, 15)) +\n  labs(title = \"A: VIF grows with predictor correlation\",\n       x = \"|r| between predictors\", y = \"VIF\")\n\np2 <- ggplot(col_df, aes(x = r, y = se_mult)) +\n  geom_line(color = ber640_colors[[\"accent\"]], linewidth = 1.2) +\n  geom_hline(yintercept = 1, linetype = \"dotted\", color = \"grey50\") +\n  geom_vline(xintercept = r_actual, linetype = \"dashed\", color = ber640_colors[[\"primary\"]]) +\n  geom_point(aes(x = r_actual, y = sqrt(vif_actual)), color = ber640_colors[[\"primary\"]], size = 4) +\n  coord_cartesian(ylim = c(1, 4)) +\n  labs(title = \"B: SE inflation (\\u221AVIF)\",\n       x = \"|r| between predictors\", y = \"SE multiplier\")\n\np1 | p2\n```\n\n::: {.cell-output-display}\n![](02-ancova_files/figure-html/unnamed-chunk-46-1.png){width=3000}\n:::\n:::\n\n- We compute VIF = $1/(1-r^2)$ across a range of correlations from 0 to 0.99\n- **Panel A** shows VIF on the y-axis: it grows slowly at first, then explodes as $|r|$ approaches 1\n- **Panel B** shows the SE multiplier ($\\sqrt{\\text{VIF}}$): this is how much wider the confidence interval becomes due to collinearity\n- The dashed vertical line and point mark where our ANCOVA model falls on the curve\n\n\n:::\n\n::: {.callout-note}\n## The Bias-Variance Tradeoff\nCollinearity illustrates a fundamental tradeoff in regression:\n\n- **Including relevant pre-treatment confounders**: Reduces omitted-variable bias but can increase variance (larger standard errors). Including **irrelevant** predictors does not reduce bias --- it only adds variance --- and including **mediators or colliders** (post-treatment variables) can *introduce* bias\n- **Excluding relevant confounders**: Reduces variance (smaller standard errors) but introduces omitted-variable bias\n\nThe best approach depends on the research question. For causal inference, bias is usually a bigger concern than variance, so we prefer to include important confounders even if they create some collinearity.\n:::\n\n### Interactive Exploration: Collinearity Explorer {.unnumbered}\n\n::: {.callout-tip collapse=\"false\"}\n## Try It: How Correlated Predictors Inflate Uncertainty\n\nDrag the **Predictor correlation r(X₁, X₂)** slider --- the app's single control --- to see how multicollinearity between two predictors inflates standard errors and widens confidence intervals. Under correct specification the coefficient *estimates* remain **unbiased in expectation** --- collinearity does not create bias --- but in **any single sample** high collinearity makes them **unstable and possibly far from the truth**, because the inflated standard errors leave the model unable to pin down each predictor's unique contribution. We simulate the data because demonstrating this requires a *known* true coefficient (1.0 for both predictors) and a *dial* that sets the target predictor correlation --- a known truth and counterfactual control over r that a single fixed real dataset cannot provide.\n:::\n\n```{ojs}\n//| echo: false\n\nimport { ber640 as collin_ber640,\n         themeColors as collin_themeColors, plotDefaults as collin_plotDefaults,\n         onThemeChange as collin_onThemeChange,\n         normalRandom as collin_normalRandom,\n         formatCoef as collin_formatCoef,\n         srSummary as collin_srSummary,\n         resetControls as collin_resetControls } from \"../ojs/shared.js\"\n```\n\n```{ojs}\n//| echo: false\ncollin_theme = collin_themeColors()\n```\n\n```{ojs}\n//| echo: false\ncollin_pill = (label, value, tone = \"\") => html`<span class=\"ojs-readout ${tone ? \"ojs-readout-\" + tone : \"\"}\"><span class=\"ojs-readout-label\">${label}</span><span class=\"ojs-readout-value\">${value}</span></span>`\n```\n\n```{ojs}\n//| echo: false\n\nviewof collin_r = Inputs.range([0, 0.99], {\n  value: 0.3,\n  step: 0.01,\n  label: \"Predictor correlation r(X₁, X₂)\",\n  width: 400\n})\n```\n\n```{ojs}\n//| echo: false\n\n// --- Data generation (n = 100, all seeded) ---\ncollin_n = 100\n\ncollin_x1_raw = collin_normalRandom(collin_n, 0, 1, 42)\ncollin_eps = collin_normalRandom(collin_n, 0, 1, 43)\ncollin_ey = collin_normalRandom(collin_n, 0, 1, 44)\n\n// X₂ = r * X₁ + sqrt(1 - r²) * ε\ncollin_x2 = {\n  const r = collin_r;\n  const s = Math.sqrt(1 - r * r);\n  return collin_x1_raw.map((x1, i) => r * x1 + s * collin_eps[i]);\n}\n\n// Y = 1.0 * X₁ + 1.0 * X₂ + ε_y\ncollin_y = collin_x1_raw.map((x1, i) => 1.0 * x1 + 1.0 * collin_x2[i] + collin_ey[i])\n```\n\n```{ojs}\n//| echo: false\n\n// --- Multiple regression via normal equations (3×3 system) ---\ncollin_reg = {\n  const n = collin_n;\n  const x1 = collin_x1_raw;\n  const x2 = collin_x2;\n  const y = collin_y;\n  const mean = arr => arr.reduce((a, b) => a + b, 0) / arr.length;\n  const mx1 = mean(x1);\n  const mx2 = mean(x2);\n  let cov12 = 0, ss1 = 0, ss2 = 0;\n  for (let i = 0; i < n; i++) {\n    cov12 += (x1[i] - mx1) * (x2[i] - mx2);\n    ss1 += (x1[i] - mx1) ** 2;\n    ss2 += (x2[i] - mx2) ** 2;\n  }\n  const sampleR = cov12 / Math.sqrt(ss1 * ss2);\n\n  // X'X elements (3×3: intercept, x1, x2)\n  let s1 = 0, s2 = 0, s11 = 0, s22 = 0, s12 = 0;\n  let sy = 0, s1y = 0, s2y = 0;\n\n  for (let i = 0; i < n; i++) {\n    s1 += x1[i]; s2 += x2[i];\n    s11 += x1[i] * x1[i]; s22 += x2[i] * x2[i]; s12 += x1[i] * x2[i];\n    sy += y[i]; s1y += x1[i] * y[i]; s2y += x2[i] * y[i];\n  }\n\n  // X'X matrix (row-major 3×3)\n  const XtX = [\n    n,   s1,  s2,\n    s1,  s11, s12,\n    s2,  s12, s22\n  ];\n\n  // X'Y vector\n  const XtY = [sy, s1y, s2y];\n\n  // Invert 3×3 via cofactors\n  function inv3(m) {\n    const [a,b,c, d,e,f, g,h,k] = m;\n    const det = a*(e*k - f*h) - b*(d*k - f*g) + c*(d*h - e*g);\n    if (Math.abs(det) < 1e-15) return null;\n    const invDet = 1 / det;\n    return [\n      (e*k - f*h)*invDet, (c*h - b*k)*invDet, (b*f - c*e)*invDet,\n      (f*g - d*k)*invDet, (a*k - c*g)*invDet, (c*d - a*f)*invDet,\n      (d*h - e*g)*invDet, (b*g - a*h)*invDet, (a*e - b*d)*invDet\n    ];\n  }\n\n  const XtXinv = inv3(XtX);\n  if (!XtXinv) return { b0: NaN, b1: NaN, b2: NaN, se1: NaN, se2: NaN, vif: NaN };\n\n  // Coefficients: (X'X)⁻¹ X'Y\n  const b0 = XtXinv[0]*XtY[0] + XtXinv[1]*XtY[1] + XtXinv[2]*XtY[2];\n  const b1 = XtXinv[3]*XtY[0] + XtXinv[4]*XtY[1] + XtXinv[5]*XtY[2];\n  const b2 = XtXinv[6]*XtY[0] + XtXinv[7]*XtY[1] + XtXinv[8]*XtY[2];\n\n  // Residual variance: σ² = SSE / (n - 3)\n  let sse = 0;\n  for (let i = 0; i < n; i++) {\n    const resid = y[i] - (b0 + b1 * x1[i] + b2 * x2[i]);\n    sse += resid * resid;\n  }\n  const sigma2 = sse / (n - 3);\n\n  // SE from diagonal of (X'X)⁻¹ * σ²\n  const se1 = Math.sqrt(XtXinv[4] * sigma2);\n  const se2 = Math.sqrt(XtXinv[8] * sigma2);\n\n  // VIF uses the realized sample correlation because the fitted model sees\n  // this sample, not the slider's population target exactly.\n  const vif = 1 / (1 - sampleR * sampleR);\n\n  return { b0, b1, b2, se1, se2, vif, sigma2, sampleR, targetR: collin_r };\n}\n```\n\n```{ojs}\n//| echo: false\n\n// --- Derived display helpers (tones/labels mirror the original VIF colour bands) ---\ncollin_vifTone  = collin_reg.vif < 5 ? \"good\" : collin_reg.vif < 10 ? \"warning\" : \"bad\"\ncollin_vifLabel = collin_reg.vif < 5 ? \"Low concern\" : collin_reg.vif < 10 ? \"Moderate concern\" : \"Severe collinearity\"\ncollin_vifColor = collin_reg.vif < 5 ? collin_ber640.success : collin_reg.vif < 10 ? collin_ber640.warning : collin_ber640.secondary\n```\n\n```{ojs}\n//| echo: false\n\n// --- Readout pills (CSS-var driven via the shared pill helper → theme-reactive) ---\ncollin_readouts = {\n  const reg = collin_reg;\n  const ci1Width = 2 * 1.96 * reg.se1;\n  const ci2Width = 2 * 1.96 * reg.se2;\n  return html`<div class=\"ojs-readouts\">\n    ${collin_pill(\"β̂₁\", `${collin_formatCoef(reg.b1, 3)} ± ${collin_formatCoef(reg.se1, 3)} (w ${collin_formatCoef(ci1Width, 2)})`)}\n    ${collin_pill(\"β̂₂\", `${collin_formatCoef(reg.b2, 3)} ± ${collin_formatCoef(reg.se2, 3)} (w ${collin_formatCoef(ci2Width, 2)})`)}\n    ${collin_pill(\"VIF (sample)\", `${collin_formatCoef(reg.vif, reg.vif < 10 ? 2 : 1)} · ${collin_vifLabel}`, collin_vifTone)}\n    ${collin_pill(\"Target r\", collin_formatCoef(reg.targetR, 2), \"info\")}\n    ${collin_pill(\"Sample r\", collin_formatCoef(reg.sampleR, 2), \"info\")}\n  </div>`;\n}\n```\n\n```{ojs}\n//| echo: false\n\n// --- Coefficient plot: β̂₁ and β̂₂ with approximate 95% intervals (reads `collin_theme` so it repaints on toggle) ---\ncollin_coefPlot = {\n  const t = collin_theme;\n  const reg = collin_reg;\n\n  const coefData = [\n    {\n      label: \"β̂₁\",\n      estimate: reg.b1,\n      lo: reg.b1 - 1.96 * reg.se1,\n      hi: reg.b1 + 1.96 * reg.se1,\n      se: reg.se1,\n      trueVal: 1.0,\n      color: collin_ber640.accent,\n      y: 1\n    },\n    {\n      label: \"β̂₂\",\n      estimate: reg.b2,\n      lo: reg.b2 - 1.96 * reg.se2,\n      hi: reg.b2 + 1.96 * reg.se2,\n      se: reg.se2,\n      trueVal: 1.0,\n      color: collin_ber640.secondary,\n      y: 0\n    }\n  ];\n\n  // Compute dynamic x-axis range\n  const allVals = coefData.flatMap(d => [d.lo, d.hi, d.trueVal]);\n  const xMin = Math.min(...allVals) - 0.3;\n  const xMax = Math.max(...allVals) + 0.3;\n\n  return Plot.plot(collin_plotDefaults({\n    width: 640,\n    height: 340,\n    marginLeft: 65,\n    marginTop: 28,\n    marginBottom: 40,\n    marginRight: 16,\n    style: { color: t.text },\n    x: {\n      label: \"Coefficient value\",\n      domain: [xMin, xMax],\n      grid: true\n    },\n    y: {\n      domain: [-0.5, 1.5],\n      axis: null\n    },\n    marks: [\n      // True value reference line (non-color channel: dashed rule + label)\n      Plot.ruleX([1.0], {\n        stroke: t.muted,\n        strokeWidth: 2,\n        strokeDasharray: \"6,4\"\n      }),\n\n      // True value label\n      Plot.text([{ x: 1.0, y: 1.5 }], {\n        x: \"x\", y: \"y\",\n        text: d => \"True β = 1.0\",\n        fill: t.muted,\n        fontSize: 11,\n        dy: -5\n      }),\n\n      // CI bars\n      Plot.link(coefData, {\n        x1: \"lo\",\n        x2: \"hi\",\n        y1: \"y\",\n        y2: \"y\",\n        stroke: \"color\",\n        strokeWidth: 4,\n        strokeLinecap: \"round\"\n      }),\n\n      // Point estimates\n      Plot.dot(coefData, {\n        x: \"estimate\",\n        y: \"y\",\n        r: 7,\n        fill: \"color\",\n        stroke: t.bg,\n        strokeWidth: 2\n      }),\n\n      // Labels on left\n      Plot.text(coefData, {\n        x: d => xMin + 0.05,\n        y: \"y\",\n        text: \"label\",\n        fill: \"color\",\n        fontWeight: 700,\n        fontSize: 14,\n        textAnchor: \"start\",\n        dx: 5\n      })\n    ]\n  }));\n}\n```\n\n```{ojs}\n//| echo: false\n\n// --- Dynamic narrative (state line; reads `collin_theme` so it repaints on toggle) ---\ncollin_narrative = {\n  const t = collin_theme;\n  const r = collin_r;\n  const reg = collin_reg;\n\n  let msg;\n  const vif = reg.vif;\n  const vifFmt = collin_formatCoef(vif, vif < 10 ? 2 : 1);\n  if (vif < 5) {\n    msg = `At target r = ${collin_formatCoef(r, 2)} (realized sample r = ${collin_formatCoef(reg.sampleR, 2)}), the sample VIF of ${vifFmt} signals low collinearity: the two predictors carry mostly distinct information. Standard errors are only modestly inflated (by a factor of about ${collin_formatCoef(Math.sqrt(vif), 2)} relative to the zero-correlation baseline), so the confidence intervals stay fairly tight. OLS is unbiased on average, and in this sample the estimates sit close to the true value of 1.0 — though even here they are not exactly 1.0, since each sample lands somewhere in the sampling distribution.`;\n  } else if (vif < 10) {\n    msg = `At target r = ${collin_formatCoef(r, 2)} (realized sample r = ${collin_formatCoef(reg.sampleR, 2)}), the sample VIF of ${vifFmt} indicates moderate collinearity: standard errors are inflated by roughly ${collin_formatCoef(Math.sqrt(vif), 2)}× and the confidence intervals are visibly wider. OLS remains unbiased on average, but watch this single sample's point estimates: as r rises they drift away from 1.0 (one coefficient pulled above it, the other below) while their standard errors keep inflating. Unbiasedness is a property of the long-run average, not a guarantee for any one sample.`;\n  } else {\n    msg = `At target r = ${collin_formatCoef(r, 2)} (realized sample r = ${collin_formatCoef(reg.sampleR, 2)}), the sample VIF of ${vifFmt} marks severe collinearity: standard errors are inflated by about ${collin_formatCoef(Math.sqrt(vif), 1)}× and the confidence intervals span an enormous range, making each coefficient hard to interpret on its own. The model can barely separate the near-identical effects of X₁ and X₂. OLS is still unbiased in expectation, yet in this fixed-seed sample the estimates have drifted markedly from 1.0 — a vivid reminder that no-bias-on-average does not pin down the estimate in a single highly collinear sample.`;\n  }\n\n  return html`<div class=\"ojs-equation\" style=\"\n    display:block;\n    text-align:left;\n    font-size: 0.9rem;\n    line-height: 1.55;\n    color: ${t.text};\n    padding: 0.6rem 0.8rem;\n    background: ${t.isDark ? 'rgba(255,255,255,0.04)' : 'rgba(0,0,0,0.02)'};\n    border-left: 3px solid ${collin_vifColor};\n    border-radius: 0 6px 6px 0;\n  \">${msg}</div>`;\n}\n```\n\n```{ojs}\n//| echo: false\ncollin_sr = collin_srSummary(\"ch02-collin\",\n  `Target predictor correlation r = ${collin_formatCoef(collin_reg.targetR, 2)}, realized sample r = ${collin_formatCoef(collin_reg.sampleR, 2)}. β̂₁ = ${collin_formatCoef(collin_reg.b1, 3)} ± ${collin_formatCoef(collin_reg.se1, 3)} (approximate 95% interval width ${collin_formatCoef(2 * 1.96 * collin_reg.se1, 2)}); β̂₂ = ${collin_formatCoef(collin_reg.b2, 3)} ± ${collin_formatCoef(collin_reg.se2, 3)} (approximate 95% interval width ${collin_formatCoef(2 * 1.96 * collin_reg.se2, 2)}); true value 1.0 for both. Sample VIF = ${collin_formatCoef(collin_reg.vif, collin_reg.vif < 10 ? 2 : 1)} (${collin_vifLabel}), standard errors inflated by about ${collin_formatCoef(Math.sqrt(collin_reg.vif), 2)}× relative to the zero-correlation baseline.`)\n```\n\n```{ojs}\n//| echo: false\ncollin_reset = collin_resetControls([\n  { input: viewof collin_r, value: 0.3 }\n], { label: \"Reset\" })\n```\n\n```{ojs}\n//| echo: false\ncollin_app = html`<div class=\"ojs-app\" role=\"group\" aria-label=\"Collinearity explorer: how correlated predictors inflate standard errors\">\n  <div class=\"ojs-controls\">${viewof collin_r}<div class=\"ojs-control-group\" style=\"flex:0 0 auto;\">${collin_reset}</div></div>\n  ${collin_readouts}\n  <div class=\"ojs-plot\">${collin_coefPlot}</div>\n  ${collin_narrative}\n  ${collin_sr}\n</div>`\n```\n\n::: {.callout-note}\n## What you should have seen\n- As the target **r** rises, both coefficient confidence intervals widen dramatically while the point estimates stay (on average) near the true value of 1.0 --- collinearity inflates *variance*, not bias.\n- The displayed **VIF** is based on the realized sample correlation, which can differ slightly from the slider's target r; standard errors inflate by about $\\sqrt{\\text{VIF}}$, and at high r the model can barely separate the near-identical contributions of X₁ and X₂.\n- In this single fixed-seed sample the estimates can drift noticeably from 1.0 at high r --- a concrete reminder that unbiased-on-average is not a guarantee for any one collinear sample.\n:::\n\n### Output\n\n::: {.cell}\n\n```{.r .cell-code  code-fold=\"true\" code-summary=\"Show R Code\"}\nset.seed(42)\nalpha_true <- coef(model_ancova)[\"(Intercept)\"]\nb_lrt <- coef(model_ancova)[\"lrt\"]\nb_school <- coef(model_ancova)[\"school_nameChelsea\"]\nsigma_true <- sigma(model_ancova)\nn <- nrow(two_schools)\n\nsim_results <- replicate(500, {\n  y_sim <- alpha_true + b_lrt * two_schools$lrt +\n    b_school * (as.numeric(two_schools$school_name) - 1) + rnorm(n, 0, sigma_true)\n  df_sim <- two_schools |> mutate(gcse_sim = y_sim)\n  c(biased = unname(coef(lm(gcse_sim ~ school_name, data = df_sim))[\"school_nameChelsea\"]),\n    unbiased = unname(coef(lm(gcse_sim ~ school_name + lrt, data = df_sim))[\"school_nameChelsea\"]))\n}, simplify = TRUE) |> t() |> as_tibble()\n\nsim_long <- sim_results |>\n  pivot_longer(everything(), names_to = \"estimator\", values_to = \"estimate\") |>\n  mutate(estimator = factor(estimator,\n    levels = c(\"biased\", \"unbiased\"),\n    labels = c(\"Biased (omits LRT)\", \"Unbiased (ANCOVA)\")))\n\np_dist <- ggplot(sim_long, aes(x = estimate, fill = estimator, color = estimator)) +\n  geom_density(alpha = 0.35, linewidth = 0.8) +\n  geom_vline(xintercept = b_school, linewidth = 1, color = \"grey20\") +\n  annotate(\"text\", x = b_school + 0.3, y = Inf, label = paste0(\"True~beta[2]=='\", round(b_school, 2), \"'\"),\n           parse = TRUE, vjust = 1.5, color = \"grey20\", fontface = \"bold\", size = 3.5) +\n  scale_fill_manual(values = c(ber640_colors[[\"secondary\"]], ber640_colors[[\"accent\"]])) +\n  scale_color_manual(values = c(ber640_colors[[\"secondary\"]], ber640_colors[[\"accent\"]])) +\n  labs(title = \"A: Sampling Distributions (500 sims)\",\n       x = \"Estimated School Coefficient\", y = \"Density\", fill = NULL, color = NULL)\n\nsim_summary <- sim_long |>\n  group_by(estimator) |>\n  summarise(bias2 = (mean(estimate) - b_school)^2, variance = var(estimate), .groups = \"drop\") |>\n  pivot_longer(c(bias2, variance), names_to = \"component\", values_to = \"value\") |>\n  mutate(component = factor(component, levels = c(\"variance\", \"bias2\"), labels = c(\"Variance\", \"Bias\\u00b2\")))\n\np_mse <- ggplot(sim_summary, aes(x = estimator, y = value, fill = component)) +\n  geom_col(width = 0.5) +\n  scale_fill_manual(values = c(\"Bias\\u00b2\" = ber640_colors[[\"secondary\"]], \"Variance\" = ber640_colors[[\"warning\"]])) +\n  labs(title = \"B: MSE = Bias\\u00b2 + Variance\", x = NULL, y = \"MSE\", fill = NULL)\n\np_dist | p_mse\n```\n\n::: {.cell-output-display}\n![Bias-variance tradeoff via simulation. Left: the biased estimator (omitting LRT) consistently overestimates; the unbiased ANCOVA estimator is centered on truth but wider. Right: MSE = Bias² + Variance shows ANCOVA wins in total error.](02-ancova_files/figure-html/fig-ch2-bias-variance-1.png){#fig-ch2-bias-variance fig-alt='Two-panel simulation figure illustrating the bias-variance tradeoff. The left panel shows overlapping density curves for two estimators: the biased estimator that omits LRT is narrow but shifted away from the true value, while the unbiased ANCOVA estimator is centered on the truth but wider. The right panel displays a stacked bar chart decomposing mean squared error into bias squared and variance components for each estimator, showing that ANCOVA achieves lower total MSE despite its greater variance.' width=3000}\n:::\n:::\n\n\n### Output Interpretation\n\n\n::: {.cell}\n::: {.cell-output-display}\n![](02-ancova_files/figure-html/unnamed-chunk-60-1.png){width=3000}\n:::\n:::\n\n- **Panel A**: The biased estimator (red) is shifted to the right of the true value --- it consistently overestimates the school effect because it absorbs the LRT confounding. The unbiased ANCOVA estimator (blue) is centered on the truth\n- **Panel B**: Although the unbiased estimator has slightly more variance (it estimates an additional parameter), its total MSE is much smaller because it has near-zero bias. The biased estimator's large Bias² component dominates its MSE\n- This demonstrates why controlling for confounders is usually worth the small increase in variance: bias reduction outweighs the variance cost\n\n### Code Explanation\n\n::: {.cell}\n\n```{.r .cell-code}\nset.seed(42)\nalpha_true <- coef(model_ancova)[\"(Intercept)\"]\nb_lrt <- coef(model_ancova)[\"lrt\"]\nb_school <- coef(model_ancova)[\"school_nameChelsea\"]\nsigma_true <- sigma(model_ancova)\nn <- nrow(two_schools)\n\nsim_results <- replicate(500, {\n  y_sim <- alpha_true + b_lrt * two_schools$lrt +\n    b_school * (as.numeric(two_schools$school_name) - 1) + rnorm(n, 0, sigma_true)\n  df_sim <- two_schools |> mutate(gcse_sim = y_sim)\n  c(biased = unname(coef(lm(gcse_sim ~ school_name, data = df_sim))[\"school_nameChelsea\"]),\n    unbiased = unname(coef(lm(gcse_sim ~ school_name + lrt, data = df_sim))[\"school_nameChelsea\"]))\n}, simplify = TRUE) |> t() |> as_tibble()\n\nsim_long <- sim_results |>\n  pivot_longer(everything(), names_to = \"estimator\", values_to = \"estimate\") |>\n  mutate(estimator = factor(estimator,\n    levels = c(\"biased\", \"unbiased\"),\n    labels = c(\"Biased (omits LRT)\", \"Unbiased (ANCOVA)\")))\n\np_dist <- ggplot(sim_long, aes(x = estimate, fill = estimator, color = estimator)) +\n  geom_density(alpha = 0.35, linewidth = 0.8) +\n  geom_vline(xintercept = b_school, linewidth = 1, color = \"grey20\") +\n  annotate(\"text\", x = b_school + 0.3, y = Inf, label = paste0(\"True~beta[2]=='\", round(b_school, 2), \"'\"),\n           parse = TRUE, vjust = 1.5, color = \"grey20\", fontface = \"bold\", size = 3.5) +\n  scale_fill_manual(values = c(ber640_colors[[\"secondary\"]], ber640_colors[[\"accent\"]])) +\n  scale_color_manual(values = c(ber640_colors[[\"secondary\"]], ber640_colors[[\"accent\"]])) +\n  labs(title = \"A: Sampling Distributions (500 sims)\",\n       x = \"Estimated School Coefficient\", y = \"Density\", fill = NULL, color = NULL)\n\nsim_summary <- sim_long |>\n  group_by(estimator) |>\n  summarise(bias2 = (mean(estimate) - b_school)^2, variance = var(estimate), .groups = \"drop\") |>\n  pivot_longer(c(bias2, variance), names_to = \"component\", values_to = \"value\") |>\n  mutate(component = factor(component, levels = c(\"variance\", \"bias2\"), labels = c(\"Variance\", \"Bias\\u00b2\")))\n\np_mse <- ggplot(sim_summary, aes(x = estimator, y = value, fill = component)) +\n  geom_col(width = 0.5) +\n  scale_fill_manual(values = c(\"Bias\\u00b2\" = ber640_colors[[\"secondary\"]], \"Variance\" = ber640_colors[[\"warning\"]])) +\n  labs(title = \"B: MSE = Bias\\u00b2 + Variance\", x = NULL, y = \"MSE\", fill = NULL)\n\np_dist | p_mse\n```\n\n::: {.cell-output-display}\n![](02-ancova_files/figure-html/unnamed-chunk-61-1.png){width=3000}\n:::\n:::\n\n- We simulate 500 datasets from the true ANCOVA model (using estimated parameters as \"truth\") and fit both the biased (school-only) and unbiased (ANCOVA) models to each\n- **Panel A**: Density plots of the 500 estimated school coefficients. The biased estimator is centered away from the true value; the unbiased estimator is centered on truth but has wider spread\n- **Panel B**: Stacked bar chart decomposing MSE into Bias² and Variance for each estimator\n- `as_tibble()` and `pivot_longer()` reshape the simulation results for plotting\n\n\n## Summary and Key Takeaways {#sec-ch2-summary}\n\n::: {.callout-important}\n## Key Takeaways\n\n1. **ANCOVA** combines a categorical factor and a continuous covariate in a single regression model, allowing adjusted group comparisons\n2. **Adjusted means** are **model-implied** outcomes evaluated at a common covariate value (e.g., the grand mean of LRT). They make group comparisons **more comparable** (covariate-adjusted) rather than literally \"fair\": the contrast is causal only under strong ignorability (@sec-ch2-confounding)\n3. **Type III (unique) SS** tests each predictor controlling for all others. It is **one convention** (not the only valid one) and should be used with care --- be deliberate about contrast coding and the hypotheses it implies; it is a common default for hypothesis testing in observational studies\n4. **Omitted variable bias** occurs when a relevant confounder is left out of the model. The bias depends on both the confounder's effect on $y$ and its correlation with the included predictor\n5. Whether to adjust for a variable depends on the **estimand**: to estimate a **total effect**, control for **pre-treatment confounders** but **not mediators** (conditioning on a mediator removes part of the effect you want to measure)\n6. **Collinearity** inflates standard errors and causes finite-sample instability but does not by itself bias coefficients under the standard assumptions --- it reflects the difficulty of separating the effects of correlated predictors\n7. Every regression coefficient in multiple regression has a \"controlling for\" interpretation: $\\beta_j$ is the effect of $x_j$ holding all other predictors constant\n\n:::\n\n::: {.callout-note}\n## ANCOVA in Education Research Practice\nANCOVA appears throughout education research:\n\n- **Randomized experiments with pre-tests**: Including a pre-test score as a covariate reduces residual variance and increases statistical power, even when randomization ensures balance\n- **Value-added models (VAMs)**: School accountability systems use ANCOVA-style models to estimate school \"effects\" adjusted for student intake characteristics\n- **Program evaluation**: Quasi-experimental studies use covariate adjustment to approximate the comparisons that randomization would provide\n\nUnderstanding the assumptions and limitations of ANCOVA --- particularly around unmeasured confounders (@sec-ch2-confounding) --- is essential for critically evaluating these research designs.\n:::\n\n\n## Exercises {#sec-ch2-exercises}\n\n::: {.callout-caution collapse=\"true\"}\n## Exercise 2.1: Full ANCOVA with All Schools\nUsing the full `gcse` dataset (all schools), fit an ANCOVA model with `lrt` and `school` as predictors. How many dummy variables does R create? What is $R^2$ compared to the LRT-only model?\n\n**Hint**: `lm(gcse ~ lrt + factor(school), data = gcse)`. Check `nlevels(factor(gcse$school))` to see how many schools (and therefore dummies) there are.\n:::\n\n::: {.callout-caution collapse=\"true\"}\n## Exercise 2.2: Predicting the Direction of OVB\nIn the `gcse` data, suppose the true model includes both `lrt` and `gender`. If you omit `gender`, in which direction would you expect the coefficient of `lrt` to be biased? Use the OVB formula in @eq-ch2-ovb to reason through this.\n\n**Hint**: Since `gender` is categorical, compute the point-biserial correlation: `cor(gcse$lrt, as.numeric(factor(gcse$gender)))`. Then fit `lm(gcse ~ lrt + gender, data = gcse)` to get $\\hat{\\beta}_{\\text{gender}}$. Multiply the signs together using the OVB direction table.\n:::\n\n::: {.callout-caution collapse=\"true\"}\n## Exercise 2.3: Sequential vs Partial SS\nFit the ANCOVA model with `lrt` + `school_name` and then again with `school_name` + `lrt` (reversed order). Compare the Type I SS from `anova()`. Then use `car::Anova(type = 3)` for both. What do you notice?\n\n**Hint**: The Type I SS will differ because they are sequential, but Type III SS will be identical.\n:::\n\n::: {.callout-caution collapse=\"true\"}\n## Exercise 2.4: When Does ANCOVA Fail?\nA researcher evaluates a new reading program by comparing the post-test scores of students who volunteered for the program versus those who did not, controlling for pre-test scores using ANCOVA. The researcher concludes the program is effective because the adjusted mean for participants is significantly higher.\n\n(a) What is the key assumption the researcher is making about confounders?\n(b) List two plausible unmeasured confounders that could explain the result.\n(c) Would a randomized experiment solve both problems? Why or why not?\n\n**Hint**: Review @sec-ch2-confounding and think about what drives students to *volunteer* for programs.\n:::\n\n::: {.callout-caution collapse=\"true\"}\n## Exercise 2.5: Why Does Adding a Covariate Change the Group Coefficient?\nIn a simple regression comparing two schools, School B's coefficient is $\\hat{\\beta} = 5.2$ (i.e., School B students score 5.2 points higher on average). After adding prior achievement (LRT score) as a covariate in an ANCOVA model, School B's coefficient drops to $\\hat{\\beta} = 1.8$. Explain in plain language why controlling for prior achievement reduced the estimated school difference. What does this tell you about the relationship between school assignment and prior achievement in this dataset?\n\n**Hint**: Think about omitted variable bias. If School B tends to enroll students with higher prior achievement, part of the raw school difference reflects pre-existing ability rather than a school effect. Adding the covariate removes this confounding.\n:::\n\n::: {.callout-caution collapse=\"true\"}\n## Exercise 2.6: Interpreting Parallel Slopes\nThe ANCOVA model assumes parallel regression lines (equal slopes across groups). A colleague argues this is unrealistic because \"obviously different schools benefit differently from prior knowledge.\" Explain what the parallel slopes assumption actually means in statistical terms. Describe a specific pattern in the data that would indicate the assumption is violated, and how you would detect it both graphically and with a formal test.\n\n**Hint**: The parallel slopes assumption means no interaction between the group factor and the covariate. You could detect a violation by plotting separate regression lines and looking for crossing or diverging lines, or by adding an interaction term to the model and testing whether it is significant.\n:::\n\n::: {.callout-caution collapse=\"true\"}\n## Exercise 2.7: Adjusted Means and Extrapolation\nIn an ANCOVA comparing three treatment groups, the adjusted (least-squares) means are computed at the grand mean of the covariate. Group C has very few observations near the grand mean of the covariate---most of its students scored much higher on the pre-test. Should you be concerned about the adjusted mean for Group C? Explain why extrapolation is a risk here and how you would assess whether the adjusted mean for Group C is trustworthy.\n\n**Hint**: Adjusted means rely on the fitted regression line being accurate at the evaluation point. If Group C has little data near the grand mean of the covariate, the adjusted mean depends on extrapolating the within-group regression line into a region with sparse data. Check the overlap in covariate distributions across groups.\n:::\n",
    "supporting": [
      "02-ancova_files"
    ],
    "filters": [
      "rmarkdown/pagebreak.lua"
    ],
    "includes": {},
    "engineDependencies": {},
    "preserve": {},
    "postProcess": true
  }
}