{
  "hash": "d0d44d90128d7dcd9a1e9718098975cb",
  "result": {
    "engine": "knitr",
    "markdown": "# Simple Logistic Regression {#sec-ch9}\n\n\n\n\n\n## Introduction {#sec-ch9-intro}\n\nThroughout Chapters 1--8, every outcome variable we modeled was continuous: GCSE exam scores, mathematics achievement, faculty salaries, crime rates. The regression models we built --- simple linear regression, ANCOVA, ANOVA, multiple regression with interactions and nonlinear terms --- all shared a common structure: the conditional mean of $y$ given $x$ was modeled as a linear function of the predictors, and the residuals were assumed to be normally distributed with constant variance.\n\nBut many of the most important questions in education and the social sciences involve **binary outcomes** --- variables that take only two values:\n\n- Did the student **graduate** or not?\n- Did the respondent **agree** with the statement or not?\n- Did the passenger **survive** or not?\n- Was the student **sent to the office** for a disciplinary infraction?\n\nThese **dichotomous response variables** are coded as $y_i = 1$ (the event occurred) or $y_i = 0$ (it did not). Applying ordinary least squares regression to a binary outcome creates serious problems, as we will see shortly. This chapter introduces **logistic regression**, the standard method for modeling the relationship between predictors and a binary outcome.\n\nLogistic regression represents a genuine paradigm shift. The core ideas of regression --- specifying a model, estimating parameters, interpreting coefficients, making predictions --- all carry forward, but the mechanics change in important ways. We move from OLS to maximum likelihood estimation, from $R^2$ to odds ratios, and from additive effects on the mean to multiplicative effects on the odds. Understanding these differences is the central goal of this chapter.\n\n::: {.callout-note}\n## Learning Objectives\nAfter completing this chapter, you will be able to:\n\n1. Explain why linear regression is inappropriate for binary outcomes and describe the specific problems it creates\n2. Convert fluently among three scales --- probability, odds, and log-odds --- and explain why the log-odds scale is ideal for regression modeling\n3. Specify the simple logistic regression model and connect it to the linear regression framework through the concept of a **link function**\n4. Fit a logistic regression model in R using `glm()` and interpret the output from `model_parameters()`\n5. Interpret the exponentiated coefficient $\\exp(\\beta)$ as an **odds ratio** for both dummy and continuous predictors\n6. Explain the critical distinction between odds ratios and probability ratios, and identify when the two are approximately equal\n7. Compute and interpret **average marginal effects** and **predicted probabilities** using the `marginaleffects` package\n:::\n\n\n## Motivating Example: Titanic Survival {#sec-ch9-example}\n\nOn April 15, 1912, the RMS Titanic sank after striking an iceberg on its maiden voyage. Of the 1,309 passengers in our dataset, only 500 survived --- a survival rate of 38.2%. The tragedy is seared into collective memory partly because survival was far from random. The famous \"women and children first\" protocol meant that passenger characteristics --- sex, age, ticket class --- strongly predicted who lived and who died.\n\nOur motivating question is: **How does passenger sex predict the probability of surviving the Titanic disaster?**\n\nThis question has a binary outcome (survived: yes or no) and a binary predictor (sex: female or male), making it an ideal starting point for logistic regression.\n\n### Loading the Data\n\n::: {.panel-tabset}\n### Output\n\n::: {.cell}\n\n```{.r .cell-code  code-fold=\"true\" code-summary=\"Show R Code\"}\n# Load the Titanic dataset from regdatasets\ndata(titanic)\n\n# Inspect the structure\nglimpse(titanic)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nRows: 1,309\nColumns: 6\n$ pclass   <int> 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1…\n$ survived <int> 1, 1, 0, 0, 0, 1, 1, 0, 1, 0, 0, 1, 1, 1, 1, 0, 0, 1, 1, 0, 1…\n$ age      <dbl> 29.0000, 0.9167, 2.0000, 30.0000, 25.0000, 48.0000, 63.0000, …\n$ fare     <dbl> 211.3375, 151.5500, 151.5500, 151.5500, 151.5500, 26.5500, 77…\n$ embarked <chr> \"S\", \"S\", \"S\", \"S\", \"S\", \"S\", \"S\", \"S\", \"C\", \"C\", \"C\", \"C\", \"…\n$ sex      <int> 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 0, 1, 1, 1, 0, 0, 0, 1, 1, 0, 0…\n```\n\n\n:::\n:::\n\n\n### Output Interpretation\n\n::: {.cell}\n\n```{.r .cell-code  code-fold=\"true\" code-summary=\"Show R Code\"}\n# Load the Titanic dataset from regdatasets\ndata(titanic)\n\n# Inspect the structure\nglimpse(titanic)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nRows: 1,309\nColumns: 6\n$ pclass   <int> 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1…\n$ survived <int> 1, 1, 0, 0, 0, 1, 1, 0, 1, 0, 0, 1, 1, 1, 1, 0, 0, 1, 1, 0, 1…\n$ age      <dbl> 29.0000, 0.9167, 2.0000, 30.0000, 25.0000, 48.0000, 63.0000, …\n$ fare     <dbl> 211.3375, 151.5500, 151.5500, 151.5500, 151.5500, 26.5500, 77…\n$ embarked <chr> \"S\", \"S\", \"S\", \"S\", \"S\", \"S\", \"S\", \"S\", \"C\", \"C\", \"C\", \"C\", \"…\n$ sex      <int> 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 0, 1, 1, 1, 0, 0, 0, 1, 1, 0, 0…\n```\n\n\n:::\n:::\n\nThe `glimpse()` output reveals the structure of the dataset: 1,309 passengers with variables capturing survival status, passenger class, sex, age, fare, and a text label for sex. Note that `survived` and `sex` are coded numerically (0/1), which is exactly what logistic regression requires. The `age` variable contains some missing values, which we will need to handle when using age as a predictor.\n\n### Code Explanation\n\n::: {.cell}\n\n```{.r .cell-code}\n# Load the Titanic dataset from regdatasets\ndata(titanic)\n\n# Inspect the structure\nglimpse(titanic)\n```\n:::\n\n- `data(titanic)`: Loads the `titanic` dataset from the `regdatasets` package\n- Key variables: `survived` (1 = survived, 0 = died), `sex` (1 = female, 0 = male), `age` (in years), `pclass` (1st, 2nd, 3rd), `fare` (ticket price in British pounds)\n- `glimpse()` shows 1,309 observations with 6 variables\n\n\n:::\n\n### Exploring the Data\n\n::: {.panel-tabset}\n### Output\n\n::: {.cell}\n\n```{.r .cell-code  code-fold=\"true\" code-summary=\"Show R Code\"}\n# Create a labeled sex variable for cleaner output\ntitanic <- titanic |>\n  mutate(sex_label = factor(ifelse(sex == 1, \"Female\", \"Male\")))\n\n# Cross-tabulation of survival by sex\ntable(titanic$sex_label, titanic$survived,\n      dnn = c(\"Sex\", \"Survived\")) |>\n  addmargins()\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n        Survived\nSex         0    1  Sum\n  Female  127  339  466\n  Male    682  161  843\n  Sum     809  500 1309\n```\n\n\n:::\n:::\n\n\n### Output Interpretation\n\n::: {.cell}\n\n```{.r .cell-code  code-fold=\"true\" code-summary=\"Show R Code\"}\n# Create a labeled sex variable for cleaner output\ntitanic <- titanic |>\n  mutate(sex_label = factor(ifelse(sex == 1, \"Female\", \"Male\")))\n\n# Cross-tabulation of survival by sex\ntable(titanic$sex_label, titanic$survived,\n      dnn = c(\"Sex\", \"Survived\")) |>\n  addmargins()\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n        Survived\nSex         0    1  Sum\n  Female  127  339  466\n  Male    682  161  843\n  Sum     809  500 1309\n```\n\n\n:::\n:::\n\nThe cross-tabulation shows the raw counts. To see the pattern more clearly, we compute survival proportions within each group:\n\n- **Males**: 161 survived out of 843 (19.1%)\n- **Females**: 339 survived out of 466 (72.7%)\n\nThe difference is dramatic: women were nearly four times more likely to survive than men.\n\n### Code Explanation\n\n::: {.cell}\n\n```{.r .cell-code}\n# Create a labeled sex variable for cleaner output\ntitanic <- titanic |>\n  mutate(sex_label = factor(ifelse(sex == 1, \"Female\", \"Male\")))\n\n# Cross-tabulation of survival by sex\ntable(titanic$sex_label, titanic$survived,\n      dnn = c(\"Sex\", \"Survived\")) |>\n  addmargins()\n```\n:::\n\n- `table()` creates a 2x2 contingency table of sex by survival status\n- `addmargins()` adds row and column totals\n- The table reveals a stark difference: most women survived while most men did not\n\n\n:::\n\n::: {.panel-tabset}\n### Output\n\n::: {.cell}\n\n```{.r .cell-code  code-fold=\"true\" code-summary=\"Show R Code\"}\n# Survival proportions by sex\ntitanic |>\n  group_by(sex_label) |>\n  summarise(\n    n = n(),\n    survived = sum(survived),\n    died = n - survived,\n    prop_survived = mean(survived)\n  ) |>\n  kable(digits = 3,\n        col.names = c(\"Sex\", \"N\", \"Survived\", \"Died\", \"P(Survived)\"))\n```\n\n::: {.cell-output-display}\n\n\n|Sex    |   N| Survived| Died| P(Survived)|\n|:------|---:|--------:|----:|-----------:|\n|Female | 466|      339|  127|         339|\n|Male   | 843|      161|  682|         161|\n\n\n:::\n:::\n\n\n### Output Interpretation\n\n::: {.cell}\n\n```{.r .cell-code  code-fold=\"true\" code-summary=\"Show R Code\"}\n# Survival proportions by sex\ntitanic |>\n  group_by(sex_label) |>\n  summarise(\n    n = n(),\n    survived = sum(survived),\n    died = n - survived,\n    prop_survived = mean(survived)\n  ) |>\n  kable(digits = 3,\n        col.names = c(\"Sex\", \"N\", \"Survived\", \"Died\", \"P(Survived)\"))\n```\n\n::: {.cell-output-display}\n\n\n|Sex    |   N| Survived| Died| P(Survived)|\n|:------|---:|--------:|----:|-----------:|\n|Female | 466|      339|  127|         339|\n|Male   | 843|      161|  682|         161|\n\n\n:::\n:::\n\nThe table shows a stark contrast: approximately 19.1% of males survived compared to 72.7% of females. This large difference in survival rates suggests that sex is a strong predictor of survival, which we will quantify more precisely using logistic regression. The raw proportions serve as a baseline for comparison with the model's predictions.\n\n### Code Explanation\n\n::: {.cell}\n\n```{.r .cell-code}\n# Survival proportions by sex\ntitanic |>\n  group_by(sex_label) |>\n  summarise(\n    n = n(),\n    survived = sum(survived),\n    died = n - survived,\n    prop_survived = mean(survived)\n  ) |>\n  kable(digits = 3,\n        col.names = c(\"Sex\", \"N\", \"Survived\", \"Died\", \"P(Survived)\"))\n```\n:::\n\n- `group_by(sex_label)` splits the data by sex\n- `mean(survived)` computes the proportion surviving (since `survived` is coded 0/1, its mean equals the proportion of 1s)\n- `kable()` formats the output as a clean table\n\n\n:::\n\n### Visualizing the Relationship\n\n::: {.panel-tabset}\n### Output\n\n::: {.cell}\n\n```{.r .cell-code  code-fold=\"true\" code-summary=\"Show R Code\"}\ntitanic |>\n  group_by(sex_label) |>\n  summarise(prop_survived = mean(survived)) |>\n  ggplot(aes(x = sex_label, y = prop_survived, fill = sex_label)) +\n  geom_col(width = 0.6, alpha = 0.85) +\n  geom_text(aes(label = scales::percent(prop_survived, accuracy = 0.1)),\n            vjust = -0.5, fontface = \"bold\", size = 5) +\n  scale_fill_manual(values = c(ber640_colors[\"accent\"], ber640_colors[\"primary\"])) +\n  scale_y_continuous(labels = scales::percent, limits = c(0, 0.85)) +\n  labs(\n    title = \"Titanic Survival Rate by Sex\",\n    x = \"Passenger Sex\",\n    y = \"Survival Rate\"\n  ) +\n  guides(fill = \"none\")\n```\n\n::: {.cell-output-display}\n![Survival rates on the Titanic by passenger sex. Women had a dramatically higher survival rate (72.7%) compared to men (19.1%), reflecting the 'women and children first' evacuation protocol.](09-simple-logistic-regression_files/figure-html/fig-ch9-survival-bar-1.png){#fig-ch9-survival-bar fig-alt='Bar chart with two vertical bars showing Titanic survival rates by sex. The x-axis displays passenger sex (Female and Male) and the y-axis shows proportion survived. The Female bar reaches approximately 72.7 percent while the Male bar reaches only 19.1 percent, illustrating a stark difference in survival rates between the two groups.' width=2400}\n:::\n:::\n\n\n### Output Interpretation\n\n::: {.cell}\n\n```{.r .cell-code  code-fold=\"true\" code-summary=\"Show R Code\"}\ntitanic |>\n  group_by(sex_label) |>\n  summarise(prop_survived = mean(survived)) |>\n  ggplot(aes(x = sex_label, y = prop_survived, fill = sex_label)) +\n  geom_col(width = 0.6, alpha = 0.85) +\n  geom_text(aes(label = scales::percent(prop_survived, accuracy = 0.1)),\n            vjust = -0.5, fontface = \"bold\", size = 5) +\n  scale_fill_manual(values = c(ber640_colors[\"accent\"], ber640_colors[\"primary\"])) +\n  scale_y_continuous(labels = scales::percent, limits = c(0, 0.85)) +\n  labs(\n    title = \"Titanic Survival Rate by Sex\",\n    x = \"Passenger Sex\",\n    y = \"Survival Rate\"\n  ) +\n  guides(fill = \"none\")\n```\n\n::: {.cell-output-display}\n![](09-simple-logistic-regression_files/figure-html/unnamed-chunk-7-1.png){width=2400}\n:::\n:::\n\nThe bar chart makes the survival disparity visually striking: the female survival rate towers over the male rate. This pattern reflects the historical \"women and children first\" evacuation protocol. The chart also illustrates why a binary predictor (sex) is an ideal starting point --- with only two groups, the relationship is simple to visualize and interpret before we move to more complex models.\n\n### Code Explanation\n\n::: {.cell}\n\n```{.r .cell-code}\ntitanic |>\n  group_by(sex_label) |>\n  summarise(prop_survived = mean(survived)) |>\n  ggplot(aes(x = sex_label, y = prop_survived, fill = sex_label)) +\n  geom_col(width = 0.6, alpha = 0.85) +\n  geom_text(aes(label = scales::percent(prop_survived, accuracy = 0.1)),\n            vjust = -0.5, fontface = \"bold\", size = 5) +\n  scale_fill_manual(values = c(ber640_colors[\"accent\"], ber640_colors[\"primary\"])) +\n  scale_y_continuous(labels = scales::percent, limits = c(0, 0.85)) +\n  labs(\n    title = \"Titanic Survival Rate by Sex\",\n    x = \"Passenger Sex\",\n    y = \"Survival Rate\"\n  ) +\n  guides(fill = \"none\")\n```\n:::\n\n- `geom_col()` creates a bar chart of survival proportions\n- `scales::percent()` formats the y-axis and bar labels as percentages\n- The visualization makes the survival disparity immediately apparent\n\n\n:::\n\n\n::: {.callout-note}\n## Connection to Chapters 1--8: From OLS to GLM\nIn Chapters 1--8 you mastered the linear regression framework: $\\text{E}(y_i) = \\alpha + \\beta x_i$ with normally distributed errors. That framework assumed three things that **break down** with binary outcomes:\n\n1. **The outcome is continuous** --- binary outcomes are not\n2. **Constant variance** --- for binary data, $\\text{Var}(y_i) = \\pi_i(1 - \\pi_i)$ depends on the mean\n3. **Predicted values are unbounded** --- probabilities must stay in $[0, 1]$\n\nLogistic regression solves all three problems by wrapping the same linear predictor $\\alpha + \\beta x$ inside a **link function** (the logit). Everything you learned --- coefficient interpretation, hypothesis testing, model comparison --- still applies, but on a different scale. Think of logistic regression not as a new method, but as the natural **extension** of linear regression to binary outcomes.\n:::\n\n\n## From Linear to Logistic {#sec-ch9-transition}\n\n### The Linear Probability Model and Its Problems\n\nGiven the dramatic difference in survival rates between men and women, your first instinct might be to fit the model you already know: ordinary linear regression. After all, `survived` is numeric (0 or 1), and `sex` is a dummy variable. We could simply write:\n\n$$\n\\text{E}(\\text{survived}_i \\mid \\text{sex}_i) = \\alpha + \\beta \\cdot \\text{sex}_i\n$$\n\nThis is called the **linear probability model (LPM)** because the predicted value $\\hat{y}_i = a + b x_i$ is an estimate of $P(y_i = 1 \\mid x_i)$ --- the probability of the event. With a single binary predictor, the LPM actually works reasonably well: it simply estimates the group means. The trouble emerges when we add continuous predictors.\n\n::: {.panel-tabset}\n### Output\n\n::: {.cell}\n\n```{.r .cell-code  code-fold=\"true\" code-summary=\"Show R Code\"}\n# LPM with dummy predictor (sex)\np1 <- ggplot(titanic, aes(x = sex, y = survived)) +\n  geom_jitter(width = 0.05, height = 0.05, alpha = 0.15,\n              color = ber640_colors[\"primary\"]) +\n  geom_smooth(method = \"lm\", formula = y ~ x, se = FALSE,\n              color = ber640_colors[\"secondary\"], linewidth = 1.2) +\n  scale_x_continuous(breaks = c(0, 1), labels = c(\"Male\", \"Female\")) +\n  labs(title = \"LPM: Dummy Predictor\",\n       x = \"Sex\", y = \"P(Survived)\") +\n  coord_cartesian(ylim = c(-0.1, 1.1))\n\n# LPM with continuous predictor (age) -- showing the problem\ntitanic_age <- titanic |> filter(!is.na(age))\nlpm_age <- lm(survived ~ age, data = titanic_age)\n\np2 <- ggplot(titanic_age, aes(x = age, y = survived)) +\n  geom_jitter(width = 0, height = 0.05, alpha = 0.15,\n              color = ber640_colors[\"primary\"]) +\n  geom_smooth(method = \"lm\", formula = y ~ x, se = FALSE,\n              color = ber640_colors[\"secondary\"], linewidth = 1.2) +\n  geom_hline(yintercept = c(0, 1), linetype = \"dashed\",\n             color = ber640_colors[\"secondary\"], alpha = 0.5) +\n  labs(title = \"LPM: Continuous Predictor\",\n       x = \"Age (years)\", y = \"P(Survived)\") +\n  coord_cartesian(ylim = c(-0.2, 1.2))\n\np1 + p2\n```\n\n::: {.cell-output-display}\n![The linear probability model (LPM) applied to a binary outcome. Left: with a dummy predictor, the LPM simply connects the two group means --- no obvious problem. Right: with a continuous predictor (age), the LPM produces predicted probabilities below 0 and above 1 (red dashed lines), which are nonsensical.](09-simple-logistic-regression_files/figure-html/fig-ch9-lpm-problem-1.png){#fig-ch9-lpm-problem fig-alt='Two-panel scatter plot comparing the linear probability model with different predictor types. Left panel shows survived (0 or 1) on the y-axis versus sex (Male, Female) on the x-axis with a straight line connecting group means, appearing reasonable. Right panel shows survived versus age with a fitted straight line that extends below zero and above one at the extremes, highlighted by red dashed boundary lines, demonstrating the fundamental problem of unbounded predictions in a linear probability model.' width=2400}\n:::\n:::\n\n\n### Output Interpretation\n\n::: {.cell}\n\n```{.r .cell-code  code-fold=\"true\" code-summary=\"Show R Code\"}\n# LPM with dummy predictor (sex)\np1 <- ggplot(titanic, aes(x = sex, y = survived)) +\n  geom_jitter(width = 0.05, height = 0.05, alpha = 0.15,\n              color = ber640_colors[\"primary\"]) +\n  geom_smooth(method = \"lm\", formula = y ~ x, se = FALSE,\n              color = ber640_colors[\"secondary\"], linewidth = 1.2) +\n  scale_x_continuous(breaks = c(0, 1), labels = c(\"Male\", \"Female\")) +\n  labs(title = \"LPM: Dummy Predictor\",\n       x = \"Sex\", y = \"P(Survived)\") +\n  coord_cartesian(ylim = c(-0.1, 1.1))\n\n# LPM with continuous predictor (age) -- showing the problem\ntitanic_age <- titanic |> filter(!is.na(age))\nlpm_age <- lm(survived ~ age, data = titanic_age)\n\np2 <- ggplot(titanic_age, aes(x = age, y = survived)) +\n  geom_jitter(width = 0, height = 0.05, alpha = 0.15,\n              color = ber640_colors[\"primary\"]) +\n  geom_smooth(method = \"lm\", formula = y ~ x, se = FALSE,\n              color = ber640_colors[\"secondary\"], linewidth = 1.2) +\n  geom_hline(yintercept = c(0, 1), linetype = \"dashed\",\n             color = ber640_colors[\"secondary\"], alpha = 0.5) +\n  labs(title = \"LPM: Continuous Predictor\",\n       x = \"Age (years)\", y = \"P(Survived)\") +\n  coord_cartesian(ylim = c(-0.2, 1.2))\n\np1 + p2\n```\n\n::: {.cell-output-display}\n![](09-simple-logistic-regression_files/figure-html/unnamed-chunk-9-1.png){width=2400}\n:::\n:::\n\nThe right panel reveals three fundamental problems with the linear probability model:\n\n1. **Impossible predictions**: The model can predict probabilities below 0 or above 1\n2. **Non-constant variance**: Since $\\text{Var}(y_i) = \\pi_i(1 - \\pi_i)$ for a binary outcome, the variance depends on the mean, violating the homoscedasticity assumption\n3. **Linearity is implausible**: The relationship between a predictor and a probability is unlikely to be linear across the entire range --- probabilities should approach 0 and 1 asymptotically, not shoot past them\n\n### Code Explanation\n\n::: {.cell}\n\n```{.r .cell-code}\n# LPM with dummy predictor (sex)\np1 <- ggplot(titanic, aes(x = sex, y = survived)) +\n  geom_jitter(width = 0.05, height = 0.05, alpha = 0.15,\n              color = ber640_colors[\"primary\"]) +\n  geom_smooth(method = \"lm\", formula = y ~ x, se = FALSE,\n              color = ber640_colors[\"secondary\"], linewidth = 1.2) +\n  scale_x_continuous(breaks = c(0, 1), labels = c(\"Male\", \"Female\")) +\n  labs(title = \"LPM: Dummy Predictor\",\n       x = \"Sex\", y = \"P(Survived)\") +\n  coord_cartesian(ylim = c(-0.1, 1.1))\n\n# LPM with continuous predictor (age) -- showing the problem\ntitanic_age <- titanic |> filter(!is.na(age))\nlpm_age <- lm(survived ~ age, data = titanic_age)\n\np2 <- ggplot(titanic_age, aes(x = age, y = survived)) +\n  geom_jitter(width = 0, height = 0.05, alpha = 0.15,\n              color = ber640_colors[\"primary\"]) +\n  geom_smooth(method = \"lm\", formula = y ~ x, se = FALSE,\n              color = ber640_colors[\"secondary\"], linewidth = 1.2) +\n  geom_hline(yintercept = c(0, 1), linetype = \"dashed\",\n             color = ber640_colors[\"secondary\"], alpha = 0.5) +\n  labs(title = \"LPM: Continuous Predictor\",\n       x = \"Age (years)\", y = \"P(Survived)\") +\n  coord_cartesian(ylim = c(-0.2, 1.2))\n\np1 + p2\n```\n:::\n\n- Left panel: The LPM with a binary predictor simply connects the group proportions with a straight line --- this is fine\n- Right panel: The LPM with `age` as a predictor produces a straight line that extends below 0 and above 1\n- `geom_jitter()` adds small random noise so overlapping points are visible (binary outcomes stack at 0 and 1)\n- The red dashed lines mark the probability boundaries [0, 1]\n\n\n:::\n\n### Interactive Exploration: LPM Problems {.unnumbered}\n\n::: {.callout-tip collapse=\"true\"}\n## Try It: See Why Linear Probability Models Fail\n\nAdjust the intercept and slope to see how the linear probability model produces impossible predictions (probabilities below 0 or above 1), while the logistic curve always stays within bounds.\n:::\n\n```{ojs}\n//| echo: false\n\nimport { ber640 as lpm_ber640, plotDefaults as lpm_plotDefaults, themeColors as lpm_themeColors, sigmoid as lpm_sigmoid, seq as lpm_seq, formatCoef as lpm_formatCoef, withAlpha as lpm_withAlpha } from \"../ojs/shared.js\"\n\nlpm_tc = lpm_themeColors()\n```\n\n```{ojs}\n//| echo: false\n\nviewof lpm_alpha = Inputs.range([-3, 3], {value: 0.5, step: 0.1, label: \"Intercept (α)\"})\nviewof lpm_beta = Inputs.range([-2, 2], {value: 0.3, step: 0.05, label: \"Slope (β)\"})\n```\n\n```{ojs}\n//| echo: false\n\nlpm_mulberry32 = function(seed) {\n  return function() {\n    seed |= 0; seed = seed + 0x6D2B79F5 | 0;\n    let t = Math.imul(seed ^ seed >>> 15, 1 | seed);\n    t = t + Math.imul(t ^ t >>> 7, 61 | t) ^ t;\n    return ((t ^ t >>> 14) >>> 0) / 4294967296;\n  }\n}\n\nlpm_data = {\n  const rng = lpm_mulberry32(42);\n  const n = 100;\n  const alpha_true = -2;\n  const beta_true = 0.5;\n  const data = [];\n  for (let i = 0; i < n; i++) {\n    const x = rng() * 10;\n    const p = lpm_sigmoid(alpha_true + beta_true * x);\n    const y = rng() < p ? 1 : 0;\n    const jitter = (rng() - 0.5) * 0.08;\n    data.push({x, y, yJittered: y + jitter, p});\n  }\n  return data;\n}\n\nlpm_xGrid = lpm_seq(0, 10, 200)\n\nlpm_lpmLine = lpm_xGrid.map(x => ({x, y: lpm_alpha + lpm_beta * x}))\n\nlpm_logisticCurve = lpm_xGrid.map(x => ({x, y: lpm_sigmoid(lpm_alpha + lpm_beta * x)}))\n\nlpm_oobRegions = {\n  const regions = [];\n  const xAt0 = lpm_beta !== 0 ? -lpm_alpha / lpm_beta : null;\n  const xAt1 = lpm_beta !== 0 ? (1 - lpm_alpha) / lpm_beta : null;\n\n  if (lpm_beta > 0) {\n    if (xAt0 > 0) regions.push({x1: 0, x2: Math.min(xAt0, 10), type: \"below\"});\n    if (xAt1 < 10) regions.push({x1: Math.max(xAt1, 0), x2: 10, type: \"above\"});\n  } else if (lpm_beta < 0) {\n    if (xAt1 > 0) regions.push({x1: 0, x2: Math.min(xAt1, 10), type: \"above\"});\n    if (xAt0 < 10) regions.push({x1: Math.max(xAt0, 0), x2: 10, type: \"below\"});\n  } else {\n    if (lpm_alpha < 0) regions.push({x1: 0, x2: 10, type: \"below\"});\n    if (lpm_alpha > 1) regions.push({x1: 0, x2: 10, type: \"above\"});\n  }\n  return regions.filter(r => r.x1 < r.x2 && r.x1 < 10 && r.x2 > 0);\n}\n\nlpm_oobCount = {\n  let count = 0;\n  for (const x of lpm_xGrid) {\n    const yhat = lpm_alpha + lpm_beta * x;\n    if (yhat < 0 || yhat > 1) count++;\n  }\n  return count;\n}\n\nlpm_oobPct = (lpm_oobCount / lpm_xGrid.length * 100).toFixed(1)\n\nlpm_logLikLPM = {\n  let ll = 0;\n  for (const d of lpm_data) {\n    let p = lpm_alpha + lpm_beta * d.x;\n    p = Math.max(1e-8, Math.min(1 - 1e-8, p));\n    ll += d.y * Math.log(p) + (1 - d.y) * Math.log(1 - p);\n  }\n  return ll;\n}\n\nlpm_logLikLogistic = {\n  let ll = 0;\n  for (const d of lpm_data) {\n    const p = lpm_sigmoid(lpm_alpha + lpm_beta * d.x);\n    const pClamped = Math.max(1e-8, Math.min(1 - 1e-8, p));\n    ll += d.y * Math.log(pClamped) + (1 - d.y) * Math.log(1 - pClamped);\n  }\n  return ll;\n}\n\nlpm_plot = {\n  const shadedMarks = lpm_oobRegions.map(r =>\n    Plot.rect([r], {\n      x1: \"x1\", x2: \"x2\",\n      y1: r.type === \"below\" ? -0.3 : 1,\n      y2: r.type === \"below\" ? 0 : 1.3,\n      fill: lpm_withAlpha(lpm_ber640.secondary, 0.15),\n      stroke: \"none\"\n    })\n  );\n\n  return Plot.plot(lpm_plotDefaults({\n    width: 680,\n    height: 420,\n    x: {label: \"X\", domain: [0, 10]},\n    y: {label: \"P(Y = 1)\", domain: [-0.3, 1.3]},\n    marks: [\n      ...shadedMarks,\n      Plot.ruleY([0], {stroke: lpm_tc.muted, strokeDasharray: \"4,4\"}),\n      Plot.ruleY([1], {stroke: lpm_tc.muted, strokeDasharray: \"4,4\"}),\n      Plot.dot(lpm_data, {\n        x: \"x\", y: \"yJittered\",\n        fill: lpm_tc.muted,\n        r: 3,\n        opacity: 0.5\n      }),\n      Plot.line(lpm_lpmLine, {\n        x: \"x\", y: \"y\",\n        stroke: lpm_ber640.secondary,\n        strokeWidth: 2.5\n      }),\n      Plot.line(lpm_logisticCurve, {\n        x: \"x\", y: \"y\",\n        stroke: lpm_ber640.accent,\n        strokeWidth: 2.5\n      }),\n      Plot.text([\"LPM (Linear)\"], {\n        x: [8.5], y: [1.22],\n        fill: lpm_ber640.secondary,\n        fontSize: 12,\n        fontWeight: 600\n      }),\n      Plot.text([\"Logistic\"], {\n        x: [8.5], y: [1.13],\n        fill: lpm_ber640.accent,\n        fontSize: 12,\n        fontWeight: 600\n      })\n    ]\n  }))\n}\n\nlpm_cards = {\n  const alphaStr = lpm_formatCoef(lpm_alpha);\n  const betaStr = lpm_formatCoef(lpm_beta);\n  const sign = lpm_beta >= 0 ? \"+\" : \"−\";\n  const betaAbs = lpm_formatCoef(Math.abs(lpm_beta));\n  const linearEq = `Ŷ = ${alphaStr} ${sign} ${betaAbs}·X`;\n  const logitInner = `${alphaStr} ${sign} ${betaAbs}·X`;\n\n  const oobColor = lpm_oobCount > 0 ? lpm_ber640.secondary : lpm_ber640.success;\n\n  return html`<div style=\"display: grid; grid-template-columns: 1fr 1fr; gap: 12px; margin-top: 8px;\">\n    <div style=\"background: ${lpm_tc.bg}; border: 1px solid ${lpm_tc.muted}; border-radius: 8px; padding: 14px;\">\n      <div style=\"font-size: 0.78em; color: ${lpm_tc.muted}; text-transform: uppercase; letter-spacing: 0.05em; margin-bottom: 4px;\">Out-of-Bounds Predictions</div>\n      <div style=\"font-size: 1.5em; font-weight: 700; color: ${oobColor};\">${lpm_oobCount} / ${lpm_xGrid.length} <span style=\"font-size: 0.6em; font-weight: 400;\">(${lpm_oobPct}%)</span></div>\n      <div style=\"font-size: 0.8em; color: ${lpm_tc.muted}; margin-top: 2px;\">LPM predictions outside [0, 1]</div>\n    </div>\n    <div style=\"background: ${lpm_tc.bg}; border: 1px solid ${lpm_tc.muted}; border-radius: 8px; padding: 14px;\">\n      <div style=\"font-size: 0.78em; color: ${lpm_tc.muted}; text-transform: uppercase; letter-spacing: 0.05em; margin-bottom: 4px;\">Log-Likelihood Comparison</div>\n      <div style=\"font-size: 0.85em; margin-top: 4px;\">\n        <span style=\"color: ${lpm_ber640.secondary}; font-weight: 600;\">LPM:</span> <span style=\"color: ${lpm_tc.text};\">${lpm_logLikLPM.toFixed(2)}</span>\n      </div>\n      <div style=\"font-size: 0.85em; margin-top: 2px;\">\n        <span style=\"color: ${lpm_ber640.accent}; font-weight: 600;\">Logistic:</span> <span style=\"color: ${lpm_tc.text};\">${lpm_logLikLogistic.toFixed(2)}</span>\n      </div>\n    </div>\n    <div style=\"background: ${lpm_tc.bg}; border: 1px solid ${lpm_tc.muted}; border-radius: 8px; padding: 14px;\">\n      <div style=\"font-size: 0.78em; color: ${lpm_tc.muted}; text-transform: uppercase; letter-spacing: 0.05em; margin-bottom: 4px;\">LPM Equation</div>\n      <div style=\"font-size: 1.05em; font-weight: 600; color: ${lpm_ber640.secondary}; font-family: 'JetBrains Mono', 'Fira Code', monospace; margin-top: 4px;\">${linearEq}</div>\n    </div>\n    <div style=\"background: ${lpm_tc.bg}; border: 1px solid ${lpm_tc.muted}; border-radius: 8px; padding: 14px;\">\n      <div style=\"font-size: 0.78em; color: ${lpm_tc.muted}; text-transform: uppercase; letter-spacing: 0.05em; margin-bottom: 4px;\">Logistic Equation</div>\n      <div style=\"font-size: 1.05em; font-weight: 600; color: ${lpm_ber640.accent}; font-family: 'JetBrains Mono', 'Fira Code', monospace; margin-top: 4px;\">P(Y=1) = 1/(1+e<sup>-(${logitInner})</sup>)</div>\n    </div>\n  </div>`\n}\n```\n\n### The Logistic Function as a Solution\n\nWe need a function that maps any real number $(-\\infty, +\\infty)$ to the interval $(0, 1)$. The **logistic function** does exactly this:\n\n$$\nf(z) = \\frac{e^z}{1 + e^z} = \\frac{1}{1 + e^{-z}}\n$$ {#eq-ch9-logistic-fn}\n\nThis function produces the characteristic **S-shaped (sigmoid) curve** that approaches 0 as $z \\to -\\infty$ and approaches 1 as $z \\to +\\infty$, passing through 0.5 when $z = 0$.\n\n::: {.panel-tabset}\n### Output\n\n::: {.cell}\n\n```{.r .cell-code  code-fold=\"true\" code-summary=\"Show R Code\"}\n# Create a comparison of linear vs logistic curves\ncurve_data <- tibble(\n  z = seq(-6, 6, length.out = 200),\n  logistic = plogis(z),\n  linear = 0.5 + 0.15 * z\n)\n\nggplot(curve_data, aes(x = z)) +\n  geom_line(aes(y = logistic, color = \"Logistic\"), linewidth = 1.2) +\n  geom_line(aes(y = linear, color = \"Linear\"), linewidth = 1.2,\n            linetype = \"dashed\") +\n  geom_hline(yintercept = c(0, 1), linetype = \"dotted\", alpha = 0.5) +\n  geom_point(aes(x = 0, y = 0.5), size = 3, color = ber640_colors[\"accent\"]) +\n  scale_color_manual(\n    values = c(\"Logistic\" = ber640_colors[\"accent\"],\n               \"Linear\" = ber640_colors[\"secondary\"]),\n    name = \"Function\"\n  ) +\n  labs(\n    title = \"Logistic Function vs Linear Function\",\n    x = expression(z == alpha + beta * x),\n    y = expression(pi == P(Y == 1))\n  ) +\n  coord_cartesian(ylim = c(-0.15, 1.15))\n```\n\n::: {.cell-output-display}\n![The logistic function (S-shaped curve) compared to a straight line. The logistic function maps any value on the x-axis to a probability between 0 and 1, approaching the boundaries asymptotically rather than crossing them.](09-simple-logistic-regression_files/figure-html/fig-ch9-logistic-curve-1.png){#fig-ch9-logistic-curve fig-alt='Line plot comparing the logistic function and a straight line. The x-axis shows the linear predictor z ranging from negative 6 to 6, and the y-axis shows probability from 0 to 1. The logistic curve follows an S-shape, staying near zero for large negative z values, rising steeply through 0.5 at z equals zero, and leveling off near one for large positive z values. The straight line crosses both the zero and one boundaries, illustrating why the logistic function is preferred for modeling probabilities.' width=2400}\n:::\n:::\n\n\n### Output Interpretation\n\n::: {.cell}\n\n```{.r .cell-code  code-fold=\"true\" code-summary=\"Show R Code\"}\n# Create a comparison of linear vs logistic curves\ncurve_data <- tibble(\n  z = seq(-6, 6, length.out = 200),\n  logistic = plogis(z),\n  linear = 0.5 + 0.15 * z\n)\n\nggplot(curve_data, aes(x = z)) +\n  geom_line(aes(y = logistic, color = \"Logistic\"), linewidth = 1.2) +\n  geom_line(aes(y = linear, color = \"Linear\"), linewidth = 1.2,\n            linetype = \"dashed\") +\n  geom_hline(yintercept = c(0, 1), linetype = \"dotted\", alpha = 0.5) +\n  geom_point(aes(x = 0, y = 0.5), size = 3, color = ber640_colors[\"accent\"]) +\n  scale_color_manual(\n    values = c(\"Logistic\" = ber640_colors[\"accent\"],\n               \"Linear\" = ber640_colors[\"secondary\"]),\n    name = \"Function\"\n  ) +\n  labs(\n    title = \"Logistic Function vs Linear Function\",\n    x = expression(z == alpha + beta * x),\n    y = expression(pi == P(Y == 1))\n  ) +\n  coord_cartesian(ylim = c(-0.15, 1.15))\n```\n\n::: {.cell-output-display}\n![](09-simple-logistic-regression_files/figure-html/unnamed-chunk-14-1.png){width=2400}\n:::\n:::\n\nThe logistic curve has three key properties that make it ideal for modeling probabilities:\n\n1. **Bounded**: It never crosses 0 or 1 --- no impossible predictions\n2. **Symmetric**: It is symmetric around the midpoint $(z = 0, \\pi = 0.5)$\n3. **Non-linear but monotone**: The effect of $x$ on the probability is strongest near $\\pi = 0.5$ and weakens as $\\pi$ approaches 0 or 1 --- a \"diminishing returns\" property that matches our intuition about probability\n\n### Code Explanation\n\n::: {.cell}\n\n```{.r .cell-code}\n# Create a comparison of linear vs logistic curves\ncurve_data <- tibble(\n  z = seq(-6, 6, length.out = 200),\n  logistic = plogis(z),\n  linear = 0.5 + 0.15 * z\n)\n\nggplot(curve_data, aes(x = z)) +\n  geom_line(aes(y = logistic, color = \"Logistic\"), linewidth = 1.2) +\n  geom_line(aes(y = linear, color = \"Linear\"), linewidth = 1.2,\n            linetype = \"dashed\") +\n  geom_hline(yintercept = c(0, 1), linetype = \"dotted\", alpha = 0.5) +\n  geom_point(aes(x = 0, y = 0.5), size = 3, color = ber640_colors[\"accent\"]) +\n  scale_color_manual(\n    values = c(\"Logistic\" = ber640_colors[\"accent\"],\n               \"Linear\" = ber640_colors[\"secondary\"]),\n    name = \"Function\"\n  ) +\n  labs(\n    title = \"Logistic Function vs Linear Function\",\n    x = expression(z == alpha + beta * x),\n    y = expression(pi == P(Y == 1))\n  ) +\n  coord_cartesian(ylim = c(-0.15, 1.15))\n```\n:::\n\n- `plogis(z)` computes the logistic function $e^z/(1 + e^z)$ --- this is R's built-in function for the logistic CDF\n- The logistic curve stays bounded within (0, 1) regardless of $z$\n- The linear function crosses the boundaries at both ends\n- The blue dot marks the inflection point at $(0, 0.5)$, where the curve is steepest\n\n\n:::\n\n### How $\\alpha$ and $\\beta$ Shape the Logistic Curve {#sec-ch9-curve-shapes}\n\nBefore diving into the formal model, it is helpful to visualize **how different parameter values change the logistic curve**. The intercept $\\alpha$ shifts the curve left or right (changing the midpoint), while the slope $\\beta$ controls how steeply the curve rises (the strength of the predictor effect).\n\n::: {.panel-tabset}\n### Output\n\n::: {.cell}\n\n```{.r .cell-code  code-fold=\"true\" code-summary=\"Show R Code\"}\n# Create data for different parameter combinations\nx_seq <- seq(-6, 6, length.out = 300)\n\n# Panel 1: Varying intercept (alpha), fixed slope\np_alpha <- tibble(x = rep(x_seq, 3)) |>\n  mutate(\n    alpha = rep(c(-2, 0, 2), each = length(x_seq)),\n    alpha_label = paste0(\"\\u03b1 = \", alpha),\n    prob = plogis(alpha + 1 * x)\n  ) |>\n  ggplot(aes(x = x, y = prob, color = alpha_label)) +\n  geom_line(linewidth = 1.2) +\n  geom_hline(yintercept = 0.5, linetype = \"dotted\", alpha = 0.4) +\n  scale_color_manual(\n    values = c(ber640_colors[\"accent\"], ber640_colors[\"primary\"],\n               ber640_colors[\"secondary\"]),\n    name = \"Intercept\"\n  ) +\n  labs(title = expression(\"Varying\" ~ alpha ~ \"(fixed\" ~ beta ~ \"= 1)\"),\n       x = \"x\", y = expression(pi == P(Y == 1))) +\n  coord_cartesian(ylim = c(0, 1))\n\n# Panel 2: Varying slope (beta), fixed intercept\np_beta <- tibble(x = rep(x_seq, 4)) |>\n  mutate(\n    beta = rep(c(0, 0.5, 1, 3), each = length(x_seq)),\n    beta_label = factor(paste0(\"\\u03b2 = \", beta),\n                        levels = paste0(\"\\u03b2 = \", c(0, 0.5, 1, 3))),\n    prob = plogis(0 + beta * x)\n  ) |>\n  ggplot(aes(x = x, y = prob, color = beta_label)) +\n  geom_line(linewidth = 1.2) +\n  geom_hline(yintercept = 0.5, linetype = \"dotted\", alpha = 0.4) +\n  scale_color_manual(\n    values = c(ber640_colors[\"warning\"], ber640_colors[\"accent\"],\n               ber640_colors[\"primary\"], ber640_colors[\"secondary\"]),\n    name = \"Slope\"\n  ) +\n  labs(title = expression(\"Varying\" ~ beta ~ \"(fixed\" ~ alpha ~ \"= 0)\"),\n       x = \"x\", y = expression(pi == P(Y == 1))) +\n  coord_cartesian(ylim = c(0, 1))\n\np_alpha + p_beta\n```\n\n::: {.cell-output-display}\n![How the logistic curve changes with different parameter values. Left: varying the intercept shifts the curve horizontally (different baseline probabilities). Right: varying the slope changes the steepness (stronger vs weaker predictor effects). A slope of zero produces a flat line (no association).](09-simple-logistic-regression_files/figure-html/fig-ch9-curve-comparison-1.png){#fig-ch9-curve-comparison fig-alt='Two-panel line plot showing how logistic curve parameters affect its shape. Left panel displays three S-shaped curves with different intercept values (alpha equals negative 2, 0, and 2), shifting the curve left or right along the x-axis while maintaining the same steepness. Right panel displays three curves with different slope values, where a steeper slope produces a sharper transition, a moderate slope gives the standard S-shape, and a slope of zero produces a flat horizontal line at probability 0.5 indicating no association.' width=2400}\n:::\n:::\n\n\n### Output Interpretation\n\n::: {.cell}\n\n```{.r .cell-code  code-fold=\"true\" code-summary=\"Show R Code\"}\n# Create data for different parameter combinations\nx_seq <- seq(-6, 6, length.out = 300)\n\n# Panel 1: Varying intercept (alpha), fixed slope\np_alpha <- tibble(x = rep(x_seq, 3)) |>\n  mutate(\n    alpha = rep(c(-2, 0, 2), each = length(x_seq)),\n    alpha_label = paste0(\"\\u03b1 = \", alpha),\n    prob = plogis(alpha + 1 * x)\n  ) |>\n  ggplot(aes(x = x, y = prob, color = alpha_label)) +\n  geom_line(linewidth = 1.2) +\n  geom_hline(yintercept = 0.5, linetype = \"dotted\", alpha = 0.4) +\n  scale_color_manual(\n    values = c(ber640_colors[\"accent\"], ber640_colors[\"primary\"],\n               ber640_colors[\"secondary\"]),\n    name = \"Intercept\"\n  ) +\n  labs(title = expression(\"Varying\" ~ alpha ~ \"(fixed\" ~ beta ~ \"= 1)\"),\n       x = \"x\", y = expression(pi == P(Y == 1))) +\n  coord_cartesian(ylim = c(0, 1))\n\n# Panel 2: Varying slope (beta), fixed intercept\np_beta <- tibble(x = rep(x_seq, 4)) |>\n  mutate(\n    beta = rep(c(0, 0.5, 1, 3), each = length(x_seq)),\n    beta_label = factor(paste0(\"\\u03b2 = \", beta),\n                        levels = paste0(\"\\u03b2 = \", c(0, 0.5, 1, 3))),\n    prob = plogis(0 + beta * x)\n  ) |>\n  ggplot(aes(x = x, y = prob, color = beta_label)) +\n  geom_line(linewidth = 1.2) +\n  geom_hline(yintercept = 0.5, linetype = \"dotted\", alpha = 0.4) +\n  scale_color_manual(\n    values = c(ber640_colors[\"warning\"], ber640_colors[\"accent\"],\n               ber640_colors[\"primary\"], ber640_colors[\"secondary\"]),\n    name = \"Slope\"\n  ) +\n  labs(title = expression(\"Varying\" ~ beta ~ \"(fixed\" ~ alpha ~ \"= 0)\"),\n       x = \"x\", y = expression(pi == P(Y == 1))) +\n  coord_cartesian(ylim = c(0, 1))\n\np_alpha + p_beta\n```\n\n::: {.cell-output-display}\n![](09-simple-logistic-regression_files/figure-html/unnamed-chunk-16-1.png){width=2400}\n:::\n:::\n\nThese plots build geometric intuition for logistic regression parameters:\n\n- **Intercept ($\\alpha$)**: Controls the **location** of the curve. A larger $\\alpha$ shifts the curve to the left, meaning higher predicted probabilities at any given $x$. The midpoint ($\\pi = 0.5$) occurs at $x = -\\alpha/\\beta$.\n- **Slope ($\\beta$)**: Controls the **steepness** of the curve. A larger $|\\beta|$ creates a sharper S-shape (a stronger predictor). When $\\beta = 0$, the predictor has no effect and the curve is flat. When $\\beta = 3$, the transition from low to high probability happens over a narrow range of $x$.\n\nThis is analogous to linear regression, where $\\alpha$ is the y-intercept and $\\beta$ is the slope --- except that in logistic regression, these parameters operate on the **log-odds** scale, and the effect on probability is non-linear.\n\n### Code Explanation\n\n::: {.cell}\n\n```{.r .cell-code}\n# Create data for different parameter combinations\nx_seq <- seq(-6, 6, length.out = 300)\n\n# Panel 1: Varying intercept (alpha), fixed slope\np_alpha <- tibble(x = rep(x_seq, 3)) |>\n  mutate(\n    alpha = rep(c(-2, 0, 2), each = length(x_seq)),\n    alpha_label = paste0(\"\\u03b1 = \", alpha),\n    prob = plogis(alpha + 1 * x)\n  ) |>\n  ggplot(aes(x = x, y = prob, color = alpha_label)) +\n  geom_line(linewidth = 1.2) +\n  geom_hline(yintercept = 0.5, linetype = \"dotted\", alpha = 0.4) +\n  scale_color_manual(\n    values = c(ber640_colors[\"accent\"], ber640_colors[\"primary\"],\n               ber640_colors[\"secondary\"]),\n    name = \"Intercept\"\n  ) +\n  labs(title = expression(\"Varying\" ~ alpha ~ \"(fixed\" ~ beta ~ \"= 1)\"),\n       x = \"x\", y = expression(pi == P(Y == 1))) +\n  coord_cartesian(ylim = c(0, 1))\n\n# Panel 2: Varying slope (beta), fixed intercept\np_beta <- tibble(x = rep(x_seq, 4)) |>\n  mutate(\n    beta = rep(c(0, 0.5, 1, 3), each = length(x_seq)),\n    beta_label = factor(paste0(\"\\u03b2 = \", beta),\n                        levels = paste0(\"\\u03b2 = \", c(0, 0.5, 1, 3))),\n    prob = plogis(0 + beta * x)\n  ) |>\n  ggplot(aes(x = x, y = prob, color = beta_label)) +\n  geom_line(linewidth = 1.2) +\n  geom_hline(yintercept = 0.5, linetype = \"dotted\", alpha = 0.4) +\n  scale_color_manual(\n    values = c(ber640_colors[\"warning\"], ber640_colors[\"accent\"],\n               ber640_colors[\"primary\"], ber640_colors[\"secondary\"]),\n    name = \"Slope\"\n  ) +\n  labs(title = expression(\"Varying\" ~ beta ~ \"(fixed\" ~ alpha ~ \"= 0)\"),\n       x = \"x\", y = expression(pi == P(Y == 1))) +\n  coord_cartesian(ylim = c(0, 1))\n\np_alpha + p_beta\n```\n:::\n\n- **Left panel**: Three logistic curves with the same slope ($\\beta = 1$) but different intercepts ($\\alpha = -2, 0, 2$). The intercept shifts the midpoint of the curve along the $x$-axis\n- **Right panel**: Four logistic curves with the same intercept ($\\alpha = 0$) but different slopes ($\\beta = 0, 0.5, 1, 3$)\n- `plogis(alpha + beta * x)` computes $P(Y=1) = e^{\\alpha + \\beta x} / (1 + e^{\\alpha + \\beta x})$\n- A slope of $\\beta = 0$ produces a flat line at $\\pi = 0.5$ --- no predictor effect\n\n\n:::\n\n### Interactive Exploration: Logistic Curve Explorer {.unnumbered}\n\n::: {.callout-tip}\n## Try It Yourself\n\nUse the sliders to change the intercept ($\\alpha$) and slope ($\\beta$) of a logistic regression model and observe how the S-curve, midpoint, odds ratio, and maximum slope respond in real time.\n:::\n\n```{ojs}\n//| echo: false\n\nimport { ber640 as logcurve_ber640,\n         withAlpha as logcurve_withAlpha,\n         themeColors as logcurve_themeColors,\n         plotDefaults as logcurve_plotDefaults,\n         sigmoid as logcurve_sigmoid,\n         formatCoef as logcurve_formatCoef,\n         seq as logcurve_seq } from \"../ojs/shared.js\"\n```\n\n```{ojs}\n//| echo: false\n\nviewof logcurve_alpha = Inputs.range([-5, 5], {\n  label: \"Intercept (α)\",\n  step: 0.1,\n  value: 0\n})\n```\n\n```{ojs}\n//| echo: false\n\nviewof logcurve_beta = Inputs.range([-5, 5], {\n  label: \"Slope (β)\",\n  step: 0.1,\n  value: 1\n})\n```\n\n```{ojs}\n//| echo: false\n\n// Derived quantities\nlogcurve_or = Math.exp(logcurve_beta)\nlogcurve_midpoint = logcurve_beta !== 0 ? -logcurve_alpha / logcurve_beta : NaN\nlogcurve_maxSlope = logcurve_beta / 4\n\n// Curve data: 200 points over x = [-6, 6]\nlogcurve_curveData = {\n  const xs = logcurve_seq(-6, 6, 200);\n  return xs.map(x => ({\n    x: x,\n    p: logcurve_sigmoid(logcurve_alpha + logcurve_beta * x)\n  }));\n}\n\n// Steepest-change region: midpoint ± 1/|β| (where ~73% of probability change occurs)\nlogcurve_steepRegion = {\n  if (logcurve_beta === 0 || !isFinite(logcurve_midpoint)) return [];\n  const halfWidth = 1 / Math.abs(logcurve_beta);\n  const lo = logcurve_midpoint - halfWidth;\n  const hi = logcurve_midpoint + halfWidth;\n  return [{ x1: Math.max(lo, -6), x2: Math.min(hi, 6) }];\n}\n```\n\n```{ojs}\n//| echo: false\n\n// Equation display\nhtml`<div style=\"\n  font-family: 'Cambria Math', 'STIX Two Math', Georgia, serif;\n  font-size: 16px;\n  text-align: center;\n  padding: 0.5rem 1rem;\n  margin: 0.25rem 0 0.75rem 0;\n  background: ${logcurve_themeColors().isDark ? 'rgba(255,255,255,0.05)' : 'rgba(0,0,0,0.03)'};\n  border-radius: 6px;\n  color: ${logcurve_themeColors().text};\n\">\n  logit(<em>&pi;</em>) = <span style=\"color:${logcurve_ber640.accent}; font-weight:700;\">${logcurve_formatCoef(logcurve_alpha, 1)}</span> + <span style=\"color:${logcurve_ber640.secondary}; font-weight:700;\">${logcurve_formatCoef(logcurve_beta, 1)}</span> &times; <em>x</em>\n</div>`\n```\n\n```{ojs}\n//| echo: false\n\n// Main logistic curve plot\nPlot.plot(logcurve_plotDefaults({\n  width: 640,\n  height: 420,\n  x: { label: \"x\", domain: [-6, 6], grid: true },\n  y: { label: \"P(Y = 1)\", domain: [-0.02, 1.02], grid: true },\n  marks: [\n    // Steepest-change shaded region\n    logcurve_beta !== 0 && isFinite(logcurve_midpoint)\n      ? Plot.rectY(logcurve_steepRegion, {\n          x1: \"x1\",\n          x2: \"x2\",\n          y1: 0,\n          y2: 1,\n          fill: logcurve_ber640.warning,\n          fillOpacity: 0.10\n        })\n      : null,\n\n    // Horizontal reference line at P = 0.5\n    Plot.ruleY([0.5], {\n      stroke: logcurve_themeColors().muted,\n      strokeWidth: 1,\n      strokeDasharray: \"6,4\"\n    }),\n\n    // Vertical reference line at midpoint x = -α/β\n    logcurve_beta !== 0 && isFinite(logcurve_midpoint) &&\n    logcurve_midpoint >= -6 && logcurve_midpoint <= 6\n      ? Plot.ruleX([logcurve_midpoint], {\n          stroke: logcurve_ber640.accent,\n          strokeWidth: 1.5,\n          strokeDasharray: \"6,4\"\n        })\n      : null,\n\n    // The logistic S-curve\n    Plot.line(logcurve_curveData, {\n      x: \"x\",\n      y: \"p\",\n      stroke: logcurve_ber640.primary,\n      strokeWidth: 2.5\n    }),\n\n    // Midpoint dot\n    logcurve_beta !== 0 && isFinite(logcurve_midpoint) &&\n    logcurve_midpoint >= -6 && logcurve_midpoint <= 6\n      ? Plot.dot([{ x: logcurve_midpoint, p: 0.5 }], {\n          x: \"x\",\n          y: \"p\",\n          r: 5,\n          fill: logcurve_ber640.accent,\n          stroke: \"white\",\n          strokeWidth: 1.5\n        })\n      : null,\n\n    // OR annotation text\n    Plot.text([{\n      x: logcurve_beta >= 0 ? -5.5 : 5.5,\n      p: 0.95\n    }], {\n      x: \"x\",\n      y: \"p\",\n      text: d => `OR = ${logcurve_formatCoef(logcurve_or, 2)}`,\n      fill: logcurve_ber640.secondary,\n      fontWeight: 700,\n      fontSize: 13\n    }),\n\n    // Midpoint label\n    logcurve_beta !== 0 && isFinite(logcurve_midpoint) &&\n    logcurve_midpoint >= -5.5 && logcurve_midpoint <= 5.5\n      ? Plot.text([{\n          x: logcurve_midpoint,\n          p: 0.08\n        }], {\n          x: \"x\",\n          y: \"p\",\n          text: d => `x₅₀ = ${logcurve_formatCoef(logcurve_midpoint, 2)}`,\n          fill: logcurve_ber640.accent,\n          fontWeight: 600,\n          fontSize: 11\n        })\n      : null\n  ].filter(d => d !== null)\n}))\n```\n\n```{ojs}\n//| echo: false\n\n// Readout cards\nhtml`<div style=\"\n  display: grid;\n  grid-template-columns: repeat(3, 1fr);\n  gap: 0.75rem;\n  margin-top: 0.5rem;\n  text-align: center;\n  font-size: 0.9rem;\n\">\n  <div style=\"\n    padding: 0.6rem;\n    border-radius: 8px;\n    background: ${logcurve_withAlpha(logcurve_ber640.secondary, 0.08)};\n    border: 1px solid ${logcurve_withAlpha(logcurve_ber640.secondary, 0.25)};\n  \">\n    <div style=\"font-weight: 600; color: ${logcurve_ber640.secondary};\">Odds Ratio</div>\n    <div style=\"font-size: 1.3rem; font-weight: 700; font-variant-numeric: tabular-nums; color: ${logcurve_themeColors().text};\">\n      ${logcurve_formatCoef(logcurve_or, 3)}\n    </div>\n    <div style=\"font-size: 0.78rem; color: ${logcurve_themeColors().muted};\">\n      ${logcurve_or >= 1\n        ? `Each +1 in x multiplies odds by ${logcurve_formatCoef(logcurve_or, 2)}`\n        : `Each +1 in x multiplies odds by ${logcurve_formatCoef(logcurve_or, 2)}`}\n    </div>\n  </div>\n  <div style=\"\n    padding: 0.6rem;\n    border-radius: 8px;\n    background: ${logcurve_withAlpha(logcurve_ber640.accent, 0.08)};\n    border: 1px solid ${logcurve_withAlpha(logcurve_ber640.accent, 0.25)};\n  \">\n    <div style=\"font-weight: 600; color: ${logcurve_ber640.accent};\">Midpoint (P = 0.5)</div>\n    <div style=\"font-size: 1.3rem; font-weight: 700; font-variant-numeric: tabular-nums; color: ${logcurve_themeColors().text};\">\n      ${logcurve_beta !== 0 ? 'x = ' + logcurve_formatCoef(logcurve_midpoint, 2) : 'undefined'}\n    </div>\n    <div style=\"font-size: 0.78rem; color: ${logcurve_themeColors().muted};\">\n      ${logcurve_beta !== 0\n        ? `P = 0.5 occurs at x = ${logcurve_formatCoef(logcurve_midpoint, 2)}`\n        : 'No midpoint when slope = 0'}\n    </div>\n  </div>\n  <div style=\"\n    padding: 0.6rem;\n    border-radius: 8px;\n    background: ${logcurve_withAlpha(logcurve_ber640.warning, 0.08)};\n    border: 1px solid ${logcurve_withAlpha(logcurve_ber640.warning, 0.25)};\n  \">\n    <div style=\"font-weight: 600; color: ${logcurve_ber640.warning};\">Max Slope (&beta;/4)</div>\n    <div style=\"font-size: 1.3rem; font-weight: 700; font-variant-numeric: tabular-nums; color: ${logcurve_themeColors().text};\">\n      ${logcurve_formatCoef(logcurve_maxSlope, 3)}\n    </div>\n    <div style=\"font-size: 0.78rem; color: ${logcurve_themeColors().muted};\">\n      Max &Delta;P per unit x at the midpoint\n    </div>\n  </div>\n</div>`\n```\n\n```{ojs}\n//| echo: false\n\n// Dynamic narrative\nhtml`<div style=\"\n  font-size: 0.88rem;\n  line-height: 1.5;\n  padding: 0.5rem 0.75rem;\n  margin-top: 0.25rem;\n  color: ${logcurve_themeColors().text};\n  background: ${logcurve_themeColors().isDark ? 'rgba(255,255,255,0.04)' : 'rgba(0,0,0,0.02)'};\n  border-radius: 6px;\n  border-left: 3px solid ${logcurve_ber640.accent};\n\">\n  ${logcurve_beta === 0\n    ? html`When <strong>&beta; = 0</strong>, the predictor has no effect. The predicted probability is constant at <em>&pi;</em> = ${logcurve_formatCoef(logcurve_sigmoid(logcurve_alpha), 3)} for all <em>x</em>, determined entirely by &alpha;.`\n    : logcurve_beta > 0\n      ? html`With <strong>&beta; = ${logcurve_formatCoef(logcurve_beta, 1)}</strong> (positive), the curve rises from left to right. Each unit increase in <em>x</em> multiplies the odds of <em>Y</em> = 1 by <strong>${logcurve_formatCoef(logcurve_or, 2)}</strong>. The steepest change in probability (<strong>${logcurve_formatCoef(Math.abs(logcurve_maxSlope), 3)}</strong> per unit) occurs at the midpoint <em>x</em> = ${logcurve_formatCoef(logcurve_midpoint, 2)}.`\n      : html`With <strong>&beta; = ${logcurve_formatCoef(logcurve_beta, 1)}</strong> (negative), the curve falls from left to right. Each unit increase in <em>x</em> multiplies the odds by <strong>${logcurve_formatCoef(logcurve_or, 2)}</strong> (a ${logcurve_formatCoef((1 - logcurve_or) * 100, 1)}% decrease). The steepest change occurs at <em>x</em> = ${logcurve_formatCoef(logcurve_midpoint, 2)}.`\n  }\n</div>`\n```\n\n\n## Probability, Odds, and Log-Odds {#sec-ch9-scales}\n\nBefore we can write down the logistic regression model, we need to understand three different scales for expressing the likelihood of an event. These three scales --- **probability**, **odds**, and **log-odds** --- are mathematically equivalent (each can be converted to the others), but they have very different properties that make them useful in different contexts.\n\n### The Three Scales\n\nLet $\\pi = P(Y = 1)$ be the probability of the event occurring. The three scales are:\n\n| Scale | Formula | Range | Interpretation |\n|:------|:--------|:------|:---------------|\n| **Probability** | $\\pi$ | $[0, 1]$ | Proportion of times the event occurs |\n| **Odds** | $\\frac{\\pi}{1 - \\pi}$ | $[0, +\\infty)$ | Ratio of successes to failures |\n| **Log-odds (logit)** | $\\log\\!\\left(\\frac{\\pi}{1 - \\pi}\\right)$ | $(-\\infty, +\\infty)$ | Unbounded, symmetric around 0 |\n\n: The three scales for expressing the likelihood of an event. {#tbl-ch9-scales}\n\nLet us compute all three scales for the Titanic survival data:\n\n::: {.panel-tabset}\n### Output\n\n::: {.cell}\n\n```{.r .cell-code  code-fold=\"true\" code-summary=\"Show R Code\"}\n# Compute the three scales for each sex\ntitanic_scales <- titanic |>\n  group_by(sex_label) |>\n  summarise(\n    n = n(),\n    survived = sum(survived),\n    probability = mean(survived),\n    odds = probability / (1 - probability),\n    log_odds = log(odds)\n  )\n\ntitanic_scales |>\n  kable(digits = 3,\n        col.names = c(\"Sex\", \"N\", \"Survived\", \"Probability\",\n                       \"Odds\", \"Log-odds\"))\n```\n\n::: {.cell-output-display}\n\n\n|Sex    |   N| Survived| Probability|   Odds| Log-odds|\n|:------|---:|--------:|-----------:|------:|--------:|\n|Female | 466|      339|         339| -1.003|      NaN|\n|Male   | 843|      161|         161| -1.006|      NaN|\n\n\n:::\n:::\n\n\n### Output Interpretation\n\n::: {.cell}\n\n```{.r .cell-code  code-fold=\"true\" code-summary=\"Show R Code\"}\n# Compute the three scales for each sex\ntitanic_scales <- titanic |>\n  group_by(sex_label) |>\n  summarise(\n    n = n(),\n    survived = sum(survived),\n    probability = mean(survived),\n    odds = probability / (1 - probability),\n    log_odds = log(odds)\n  )\n\ntitanic_scales |>\n  kable(digits = 3,\n        col.names = c(\"Sex\", \"N\", \"Survived\", \"Probability\",\n                       \"Odds\", \"Log-odds\"))\n```\n\n::: {.cell-output-display}\n\n\n|Sex    |   N| Survived| Probability|   Odds| Log-odds|\n|:------|---:|--------:|-----------:|------:|--------:|\n|Female | 466|      339|         339| -1.003|      NaN|\n|Male   | 843|      161|         161| -1.006|      NaN|\n\n\n:::\n:::\n\nFor **males**: $\\hat{\\pi} = 0.191$, odds $= 0.191/0.809 = 0.236$, log-odds $= \\log(0.236) = -1.455$\n\n- The probability means about 19 out of every 100 men survived\n- The odds mean there was roughly 1 survivor for every 4.2 deaths (or 0.236 survivors per death)\n- The negative log-odds indicate the event (survival) is less likely than not\n\nFor **females**: $\\hat{\\pi} = 0.727$, odds $= 0.727/0.273 = 2.668$, log-odds $= \\log(2.668) = 0.981$\n\n- The probability means about 73 out of every 100 women survived\n- The odds mean there were roughly 2.7 survivors for every death\n- The positive log-odds indicate the event (survival) is more likely than not\n\n### Code Explanation\n\n::: {.cell}\n\n```{.r .cell-code}\n# Compute the three scales for each sex\ntitanic_scales <- titanic |>\n  group_by(sex_label) |>\n  summarise(\n    n = n(),\n    survived = sum(survived),\n    probability = mean(survived),\n    odds = probability / (1 - probability),\n    log_odds = log(odds)\n  )\n\ntitanic_scales |>\n  kable(digits = 3,\n        col.names = c(\"Sex\", \"N\", \"Survived\", \"Probability\",\n                       \"Odds\", \"Log-odds\"))\n```\n:::\n\n- **Probability**: `mean(survived)` gives $\\hat{\\pi}$ directly (proportion surviving)\n- **Odds**: $\\hat{\\pi} / (1 - \\hat{\\pi})$ --- the ratio of survivors to non-survivors\n- **Log-odds**: $\\log(\\text{odds})$ --- the natural logarithm of the odds\n\n\n:::\n\n### Understanding Odds\n\nOdds are a way of expressing probability that may be unfamiliar from everyday life (outside of gambling). If the probability of rain is 0.80, the odds of rain are $0.80/0.20 = 4$, which we might say as \"4 to 1 in favor of rain.\" This means we expect 4 rainy days for every 1 dry day.\n\nKey properties of odds:\n\n- Odds $= 1$ means $\\pi = 0.5$ (the event is equally likely to occur or not)\n- Odds $> 1$ means $\\pi > 0.5$ (the event is more likely than not)\n- Odds $< 1$ means $\\pi < 0.5$ (the event is less likely than not)\n- Odds are **asymmetric**: they range from 0 to $\\infty$, with 1 as the midpoint\n\n### Why Log-Odds?\n\nThe log-odds (or **logit**) scale has a crucial property that makes it ideal for regression: it is **unbounded** in both directions, ranging from $-\\infty$ to $+\\infty$. This means we can model log-odds as a linear function of predictors without worrying about impossible values.\n\n::: {.panel-tabset}\n### Output\n\n::: {.cell}\n\n```{.r .cell-code  code-fold=\"true\" code-summary=\"Show R Code\"}\n# Create a sequence of probabilities and compute all three scales\nscale_data <- tibble(\n  probability = seq(0.01, 0.99, by = 0.01),\n  odds = probability / (1 - probability),\n  log_odds = log(odds)\n)\n\np_prob <- ggplot(scale_data, aes(x = probability, y = probability)) +\n  geom_line(color = ber640_colors[\"accent\"], linewidth = 1.2) +\n  geom_hline(yintercept = c(0, 1), linetype = \"dashed\", alpha = 0.3) +\n  labs(title = \"Probability\", x = expression(pi), y = \"Probability\") +\n  scale_x_continuous(breaks = seq(0, 1, 0.25))\n\np_odds <- ggplot(scale_data, aes(x = probability, y = odds)) +\n  geom_line(color = ber640_colors[\"secondary\"], linewidth = 1.2) +\n  geom_hline(yintercept = 1, linetype = \"dashed\", alpha = 0.3) +\n  labs(title = \"Odds\", x = expression(pi), y = \"Odds\")\n\np_logodds <- ggplot(scale_data, aes(x = probability, y = log_odds)) +\n  geom_line(color = ber640_colors[\"success\"], linewidth = 1.2) +\n  geom_hline(yintercept = 0, linetype = \"dashed\", alpha = 0.3) +\n  labs(title = \"Log-Odds (Logit)\", x = expression(pi),\n       y = \"Log-odds\")\n\np_prob + p_odds + p_logodds\n```\n\n::: {.cell-output-display}\n![The same information displayed on three different scales. Probability is bounded between 0 and 1. Odds are bounded below by 0 but unbounded above. Log-odds are unbounded in both directions, making them ideal for linear modeling.](09-simple-logistic-regression_files/figure-html/fig-ch9-three-scales-1.png){#fig-ch9-three-scales fig-alt='Three-panel plot displaying the same information on different scales. Left panel shows probability on both axes, forming a straight diagonal line bounded between 0 and 1. Middle panel shows odds on the y-axis versus probability on the x-axis, producing an exponentially increasing curve that is bounded below by zero but grows without limit. Right panel shows log-odds on the y-axis versus probability on the x-axis, producing an S-shaped curve that extends from negative infinity to positive infinity, demonstrating that log-odds are unbounded in both directions.' width=2400}\n:::\n:::\n\n\n### Output Interpretation\n\n::: {.cell}\n\n```{.r .cell-code  code-fold=\"true\" code-summary=\"Show R Code\"}\n# Create a sequence of probabilities and compute all three scales\nscale_data <- tibble(\n  probability = seq(0.01, 0.99, by = 0.01),\n  odds = probability / (1 - probability),\n  log_odds = log(odds)\n)\n\np_prob <- ggplot(scale_data, aes(x = probability, y = probability)) +\n  geom_line(color = ber640_colors[\"accent\"], linewidth = 1.2) +\n  geom_hline(yintercept = c(0, 1), linetype = \"dashed\", alpha = 0.3) +\n  labs(title = \"Probability\", x = expression(pi), y = \"Probability\") +\n  scale_x_continuous(breaks = seq(0, 1, 0.25))\n\np_odds <- ggplot(scale_data, aes(x = probability, y = odds)) +\n  geom_line(color = ber640_colors[\"secondary\"], linewidth = 1.2) +\n  geom_hline(yintercept = 1, linetype = \"dashed\", alpha = 0.3) +\n  labs(title = \"Odds\", x = expression(pi), y = \"Odds\")\n\np_logodds <- ggplot(scale_data, aes(x = probability, y = log_odds)) +\n  geom_line(color = ber640_colors[\"success\"], linewidth = 1.2) +\n  geom_hline(yintercept = 0, linetype = \"dashed\", alpha = 0.3) +\n  labs(title = \"Log-Odds (Logit)\", x = expression(pi),\n       y = \"Log-odds\")\n\np_prob + p_odds + p_logodds\n```\n\n::: {.cell-output-display}\n![](09-simple-logistic-regression_files/figure-html/unnamed-chunk-28-1.png){width=2400}\n:::\n:::\n\nThe three panels reveal why we use the log-odds scale for logistic regression. Probability is bounded in [0, 1] and odds are bounded below by 0 --- neither can serve as the outcome in an unconstrained linear model. The log-odds (logit) transformation stretches the probability scale to $(-\\infty, +\\infty)$, creating a symmetric, unbounded scale where linear modeling is appropriate. Notice how probabilities near 0.5 correspond to log-odds near 0, and the curve is steepest (most sensitive) in this region.\n\n### Code Explanation\n\n::: {.cell}\n\n```{.r .cell-code}\n# Create a sequence of probabilities and compute all three scales\nscale_data <- tibble(\n  probability = seq(0.01, 0.99, by = 0.01),\n  odds = probability / (1 - probability),\n  log_odds = log(odds)\n)\n\np_prob <- ggplot(scale_data, aes(x = probability, y = probability)) +\n  geom_line(color = ber640_colors[\"accent\"], linewidth = 1.2) +\n  geom_hline(yintercept = c(0, 1), linetype = \"dashed\", alpha = 0.3) +\n  labs(title = \"Probability\", x = expression(pi), y = \"Probability\") +\n  scale_x_continuous(breaks = seq(0, 1, 0.25))\n\np_odds <- ggplot(scale_data, aes(x = probability, y = odds)) +\n  geom_line(color = ber640_colors[\"secondary\"], linewidth = 1.2) +\n  geom_hline(yintercept = 1, linetype = \"dashed\", alpha = 0.3) +\n  labs(title = \"Odds\", x = expression(pi), y = \"Odds\")\n\np_logodds <- ggplot(scale_data, aes(x = probability, y = log_odds)) +\n  geom_line(color = ber640_colors[\"success\"], linewidth = 1.2) +\n  geom_hline(yintercept = 0, linetype = \"dashed\", alpha = 0.3) +\n  labs(title = \"Log-Odds (Logit)\", x = expression(pi),\n       y = \"Log-odds\")\n\np_prob + p_odds + p_logodds\n```\n:::\n\n- Left: Probability is a straight line (trivially) --- bounded between 0 and 1\n- Middle: Odds are highly asymmetric --- they compress all probabilities below 0.5 into [0, 1] and stretch all probabilities above 0.5 across $[1, \\infty)$\n- Right: Log-odds are symmetric around 0 and unbounded in both directions --- the ideal scale for a regression model\n\n\n:::\n\n### Interactive Exploration: Probability, Odds, and Log-Odds {.unnumbered}\n\n::: {.callout-tip}\n## Try It Yourself\n\nUse the slider to set a probability value and watch how it maps onto the three equivalent scales. Notice how probabilities near 0 or 1 get compressed on the probability scale but stretched on the odds and log-odds scales. The natural \"center\" is **p = 0.50 → odds = 1 → log-odds = 0**.\n:::\n\n```{ojs}\n//| echo: false\n\nimport { ber640 as scales_ber640, withAlpha as scales_withAlpha,\n         themeColors as scales_themeColors,\n         plotDefaults as scales_plotDefaults,\n         seq as scales_seq, formatCoef as scales_formatCoef } from \"../ojs/shared.js\"\n```\n\n```{ojs}\n//| echo: false\n\nviewof scales_p = Inputs.range([0.01, 0.99], {\n  value: 0.50,\n  step: 0.01,\n  label: \"Probability (p)\",\n  width: 320\n})\n```\n\n```{ojs}\n//| echo: false\n\n// Derived values\nscales_odds = scales_p / (1 - scales_p)\nscales_logodds = Math.log(scales_odds)\n```\n\n```{ojs}\n//| echo: false\n\n// Build data for the three vertical gauge panels\nscales_plotData = {\n  const oddsMax = 20;\n  const normOdds = (v) => Math.log1p(v) / Math.log1p(oddsMax);\n  const normLogit = (v) => (v + 5) / 10;\n\n  const probTicks = [0, 0.1, 0.2, 0.3, 0.4, 0.5, 0.6, 0.7, 0.8, 0.9, 1.0];\n  const oddsTicks = [0, 0.1, 0.25, 0.5, 1, 2, 4, 7, 10, 15, 20];\n  const logitTicks = [-5, -4, -3, -2, -1, 0, 1, 2, 3, 4, 5];\n\n  const spines = [\n    { panel: \"1. Probability\", px: 0, norm: 0 },\n    { panel: \"1. Probability\", px: 0, norm: 1 },\n    { panel: \"2. Odds\",        px: 0, norm: 0 },\n    { panel: \"2. Odds\",        px: 0, norm: 1 },\n    { panel: \"3. Log-Odds\",    px: 0, norm: 0 },\n    { panel: \"3. Log-Odds\",    px: 0, norm: 1 }\n  ];\n\n  const ticks = [\n    ...probTicks.map(v => ({ panel: \"1. Probability\", norm: v, label: v.toFixed(1), px: 0 })),\n    ...oddsTicks.map(v => ({ panel: \"2. Odds\", norm: normOdds(v), label: v <= 1 ? v.toFixed(1) : String(Math.round(v)), px: 0 })),\n    ...logitTicks.map(v => ({ panel: \"3. Log-Odds\", norm: normLogit(v), label: String(v), px: 0 }))\n  ];\n\n  const markers = [\n    { panel: \"1. Probability\", norm: scales_p, px: 0, color: scales_ber640.accent },\n    { panel: \"2. Odds\", norm: normOdds(Math.min(scales_odds, oddsMax)), px: 0, color: scales_ber640.secondary },\n    { panel: \"3. Log-Odds\", norm: normLogit(Math.max(-5, Math.min(5, scales_logodds))), px: 0, color: scales_ber640.success }\n  ];\n\n  const refs = [\n    { panel: \"1. Probability\", norm: 0.5, px: 0 },\n    { panel: \"2. Odds\", norm: normOdds(1), px: 0 },\n    { panel: \"3. Log-Odds\", norm: normLogit(0), px: 0 }\n  ];\n\n  const labels = [\n    { panel: \"1. Probability\", norm: scales_p,\n      text: scales_p.toFixed(2), px: 0.15, color: scales_ber640.accent },\n    { panel: \"2. Odds\", norm: normOdds(Math.min(scales_odds, oddsMax)),\n      text: scales_odds < 100 ? scales_odds.toFixed(2) : scales_odds.toFixed(0), px: 0.15, color: scales_ber640.secondary },\n    { panel: \"3. Log-Odds\", norm: normLogit(Math.max(-5, Math.min(5, scales_logodds))),\n      text: scales_logodds.toFixed(2), px: 0.15, color: scales_ber640.success }\n  ];\n\n  return { spines, ticks, markers, refs, labels };\n}\n```\n\n```{ojs}\n//| echo: false\n\nPlot.plot(scales_plotDefaults({\n  width: 640,\n  height: 420,\n  marginTop: 20,\n  marginBottom: 25,\n  marginLeft: 30,\n  marginRight: 30,\n  x: { grid: false, label: null, axis: null },\n  y: { grid: false, label: null, domain: [-0.05, 1.05], axis: null },\n  facet: { data: scales_plotData.spines, x: \"panel\", marginRight: 10, marginLeft: 10 },\n  fx: { label: null, padding: 0.25 },\n  marks: [\n    Plot.frame({ strokeOpacity: 0.15 }),\n\n    // Vertical spine lines\n    Plot.link(scales_plotData.spines, {\n      x1: \"px\", y1: 0, x2: \"px\", y2: 1,\n      stroke: scales_themeColors().muted,\n      strokeWidth: 1.5,\n      fx: \"panel\"\n    }),\n\n    // Tick marks\n    Plot.link(scales_plotData.ticks, {\n      x1: -0.08, y1: \"norm\", x2: 0.08, y2: \"norm\",\n      stroke: scales_themeColors().muted,\n      strokeWidth: 1,\n      fx: \"panel\"\n    }),\n\n    // Tick labels\n    Plot.text(scales_plotData.ticks, {\n      x: -0.18, y: \"norm\", text: \"label\",\n      fontSize: 11, fill: scales_themeColors().muted,\n      textAnchor: \"end\", fx: \"panel\"\n    }),\n\n    // Reference dashed lines at center\n    Plot.link(scales_plotData.refs, {\n      x1: -0.25, y1: \"norm\", x2: 0.25, y2: \"norm\",\n      stroke: scales_themeColors().muted,\n      strokeDasharray: \"4,3\", strokeWidth: 1,\n      fx: \"panel\"\n    }),\n\n    // Current value markers\n    Plot.dot(scales_plotData.markers, {\n      x: \"px\", y: \"norm\", r: 9,\n      fill: \"color\", stroke: \"white\", strokeWidth: 2,\n      fx: \"panel\"\n    }),\n\n    // Value labels\n    Plot.text(scales_plotData.labels, {\n      x: \"px\", y: \"norm\", text: \"text\",\n      fill: \"color\", fontWeight: 700, fontSize: 14,\n      dx: 22, textAnchor: \"start\", fx: \"panel\"\n    })\n  ]\n}))\n```\n\n```{ojs}\n//| echo: false\n\n// Readout cards\nhtml`<div style=\"\n  display: grid;\n  grid-template-columns: repeat(3, 1fr);\n  gap: 0.75rem;\n  margin-top: 0.5rem;\n  text-align: center;\n  font-size: 0.9rem;\n\">\n  <div style=\"\n    padding: 0.6rem; border-radius: 8px;\n    background: ${scales_withAlpha(scales_ber640.accent, 0.08)};\n    border: 1px solid ${scales_withAlpha(scales_ber640.accent, 0.25)};\n  \">\n    <div style=\"font-weight: 600; color: ${scales_ber640.accent};\">Probability</div>\n    <div style=\"font-size: 1.3rem; font-weight: 700; font-variant-numeric: tabular-nums; color: ${scales_themeColors().text};\">\n      ${scales_p.toFixed(2)}\n    </div>\n    <div style=\"font-size: 0.8rem; color: ${scales_themeColors().muted};\">Bounded [0, 1]</div>\n  </div>\n  <div style=\"\n    padding: 0.6rem; border-radius: 8px;\n    background: ${scales_withAlpha(scales_ber640.secondary, 0.08)};\n    border: 1px solid ${scales_withAlpha(scales_ber640.secondary, 0.25)};\n  \">\n    <div style=\"font-weight: 600; color: ${scales_ber640.secondary};\">Odds</div>\n    <div style=\"font-size: 1.3rem; font-weight: 700; font-variant-numeric: tabular-nums; color: ${scales_themeColors().text};\">\n      ${scales_odds < 100 ? scales_odds.toFixed(2) : scales_odds.toFixed(0)}\n    </div>\n    <div style=\"font-size: 0.8rem; color: ${scales_themeColors().muted};\">\n      ${scales_p >= 0.5\n        ? (scales_odds >= 1.005 ? scales_odds.toFixed(2) + ' to 1 in favor' : '1 to 1 — even odds')\n        : '1 to ' + (1/scales_odds).toFixed(2) + ' against'}\n    </div>\n  </div>\n  <div style=\"\n    padding: 0.6rem; border-radius: 8px;\n    background: ${scales_withAlpha(scales_ber640.success, 0.08)};\n    border: 1px solid ${scales_withAlpha(scales_ber640.success, 0.25)};\n  \">\n    <div style=\"font-weight: 600; color: ${scales_ber640.success};\">Log-Odds (Logit)</div>\n    <div style=\"font-size: 1.3rem; font-weight: 700; font-variant-numeric: tabular-nums; color: ${scales_themeColors().text};\">\n      ${scales_logodds.toFixed(3)}\n    </div>\n    <div style=\"font-size: 0.8rem; color: ${scales_themeColors().muted};\">\n      ${scales_logodds > 0.01 ? 'Positive → event more likely'\n        : scales_logodds < -0.01 ? 'Negative → event less likely'\n        : 'Zero → equally likely'}\n    </div>\n  </div>\n</div>`\n```\n\n\n::: {.callout-tip}\n## Conversion Formulas\nThe three scales are interchangeable. You can always convert:\n\n**From probability to odds and log-odds:**\n$$\n\\text{odds} = \\frac{\\pi}{1-\\pi}, \\qquad \\text{logit}(\\pi) = \\log\\!\\left(\\frac{\\pi}{1-\\pi}\\right)\n$$\n\n**From log-odds back to probability:**\n$$\n\\pi = \\frac{e^{\\text{logit}}}{1 + e^{\\text{logit}}} = \\frac{1}{1 + e^{-\\text{logit}}}\n$$\n\nIn R: `qlogis(pi)` converts probability to log-odds, and `plogis(logit)` converts log-odds to probability.\n:::\n\n\n## The Logistic Regression Model {#sec-ch9-model}\n\n### The Model on Three Scales\n\nThe simple logistic regression model relates the probability of the outcome to a single predictor $x_i$ through the logistic function. It can be written equivalently on three scales:\n\n**Log-odds (logit) scale** --- the regression equation:\n\n$$\n\\text{logit}(\\pi_i) = \\log\\!\\left(\\frac{\\pi_i}{1 - \\pi_i}\\right) = \\alpha + \\beta x_i\n$$ {#eq-ch9-logit}\n\n**Odds scale:**\n\n$$\n\\frac{\\pi_i}{1 - \\pi_i} = e^{\\alpha + \\beta x_i} = e^{\\alpha} \\cdot e^{\\beta x_i}\n$$ {#eq-ch9-odds}\n\n**Probability scale:**\n\n$$\n\\pi_i = \\frac{e^{\\alpha + \\beta x_i}}{1 + e^{\\alpha + \\beta x_i}}\n$$ {#eq-ch9-prob}\n\n::: {.callout-note}\n## Connection to Linear Regression\nThe logistic regression model has the **same linear structure** as the models from Chapters 1--8: $\\alpha + \\beta x_i$. The difference is that this linear function operates on the **log-odds** of the probability, not on the probability itself.\n\nIn the language of generalized linear models (GLMs), we say:\n\n- **Linear regression**: identity link, $\\text{E}(y_i) = \\alpha + \\beta x_i$\n- **Logistic regression**: logit link, $\\text{logit}[\\text{E}(y_i)] = \\alpha + \\beta x_i$\n\nThe **logit function** is the link that connects the linear predictor to the probability. It is the inverse of the logistic function we saw in @eq-ch9-logistic-fn.\n:::\n\n### What the Parameters Mean\n\nThe parameters $\\alpha$ and $\\beta$ have direct interpretations on the log-odds scale:\n\n- $\\alpha$ is the **log-odds** of the event when $x = 0$\n- $\\beta$ is the **change in log-odds** for a one-unit increase in $x$\n\nExponentiating gives interpretations on the odds scale:\n\n- $e^{\\alpha}$ is the **odds** of the event when $x = 0$\n- $e^{\\beta}$ is the **odds ratio** --- the multiplicative factor by which the odds change for a one-unit increase in $x$\n\n### Fitting the Model with `glm()`\n\nIn R, logistic regression is fit using `glm()` (generalized linear model) with `family = binomial`:\n\n::: {.panel-tabset}\n### Output\n\n::: {.cell}\n\n```{.r .cell-code  code-fold=\"true\" code-summary=\"Show R Code\"}\n# Fit simple logistic regression: survival predicted by sex\nmodel1 <- glm(survived ~ sex, family = binomial, data = titanic)\n\n# Model summary using easystats\nmodel_parameters(model1) |> print_md()\n```\n\n::: {.cell-output-display}\n\n\n|Parameter   | Log-Odds |   SE |         95% CI |      z |      p |\n|:-----------|:--------:|:----:|:--------------:|:------:|:------:|\n|(Intercept) |    -1.44 | 0.09 | (-1.62, -1.27) | -16.48 | < .001 |\n|sex         |     2.43 | 0.14 |   (2.16, 2.70) |  17.83 | < .001 |\n\n\n:::\n:::\n\n\n### Output Interpretation\n\n::: {.cell}\n\n```{.r .cell-code  code-fold=\"true\" code-summary=\"Show R Code\"}\n# Fit simple logistic regression: survival predicted by sex\nmodel1 <- glm(survived ~ sex, family = binomial, data = titanic)\n\n# Model summary using easystats\nmodel_parameters(model1) |> print_md()\n```\n\n::: {.cell-output-display}\n\n\n|Parameter   | Log-Odds |   SE |         95% CI |      z |      p |\n|:-----------|:--------:|:----:|:--------------:|:------:|:------:|\n|(Intercept) |    -1.44 | 0.09 | (-1.62, -1.27) | -16.48 | < .001 |\n|sex         |     2.43 | 0.14 |   (2.16, 2.70) |  17.83 | < .001 |\n\n\n:::\n:::\n\nThe output shows two coefficients on the **log-odds** scale:\n\n- **Intercept** ($a$): The log-odds of survival when `sex = 0` (i.e., for males). Since male survival probability is 0.191, the log-odds are $\\log(0.191/0.809) = -1.455$\n- **sex** ($b$): The change in log-odds when going from male (`sex = 0`) to female (`sex = 1`). The positive value indicates that being female is associated with **higher** log-odds of survival\n\nThe coefficients on the log-odds scale are not directly intuitive. We need to exponentiate them to get odds ratios (@sec-ch9-odds-ratios) or convert to predicted probabilities (@sec-ch9-marginal).\n\n### Code Explanation\n\n::: {.cell}\n\n```{.r .cell-code}\n# Fit simple logistic regression: survival predicted by sex\nmodel1 <- glm(survived ~ sex, family = binomial, data = titanic)\n\n# Model summary using easystats\nmodel_parameters(model1) |> print_md()\n```\n:::\n\n- `glm(survived ~ sex, family = binomial, data = titanic)`: Fits a logistic regression model\n  - `survived ~ sex`: Formula syntax, same as `lm()`\n  - `family = binomial`: Specifies the binomial distribution with the logit link (the default link for `binomial`)\n- `model_parameters()` from the `parameters` package displays the estimated coefficients, standard errors, confidence intervals, $z$-statistics, and $p$-values\n- `|> print_md()` formats the output as a clean markdown table for consistent presentation\n- Note: logistic regression uses $z$-statistics (standard normal), not $t$-statistics, because maximum likelihood estimation does not estimate a separate residual variance\n\n\n:::\n\n\n## Estimation and Interpretation {#sec-ch9-estimation}\n\n### Maximum Likelihood Estimation\n\nUnlike linear regression, which uses OLS, logistic regression is estimated using **maximum likelihood estimation (MLE)**. The basic idea is intuitive:\n\n1. For each observation, the model predicts a probability $\\hat{\\pi}_i$ of the event occurring\n2. If $y_i = 1$, a good model should predict a **high** probability; if $y_i = 0$, a good model should predict a **low** probability\n3. MLE finds the parameter values $(\\alpha, \\beta)$ that make the observed data **most probable** --- that is, it maximizes the **likelihood function**\n\n::: {.callout-note}\n## OLS vs MLE\n| Feature | OLS (Linear Regression) | MLE (Logistic Regression) |\n|:--------|:------------------------|:--------------------------|\n| Objective | Minimize sum of squared residuals | Maximize probability of observed data |\n| Solution | Closed-form (exact formula) | Iterative (computer algorithm) |\n| Test statistic | $t$-distribution | Standard normal ($z$) |\n| Residual variance | Estimated separately ($\\hat{\\sigma}^2$) | Implied by the model |\n| Small-sample performance | Exact tests if normality holds | Approximate (relies on large samples) |\n\nThe key practical difference: OLS gives exact $t$-tests, while MLE gives approximate $z$-tests that work well in large samples. For most applications in education research, sample sizes are large enough that the distinction is negligible.\n:::\n\n### Verifying the Estimates Manually\n\nFor a model with a single dummy predictor, we can verify the `glm()` estimates by hand:\n\n::: {.panel-tabset}\n### Output\n\n::: {.cell}\n\n```{.r .cell-code  code-fold=\"true\" code-summary=\"Show R Code\"}\n# Manual computation of logistic regression coefficients\n# For males (sex = 0): reference group\npi_male <- mean(titanic$survived[titanic$sex == 0])\nodds_male <- pi_male / (1 - pi_male)\nlogodds_male <- log(odds_male)\n\n# For females (sex = 1)\npi_female <- mean(titanic$survived[titanic$sex == 1])\nodds_female <- pi_female / (1 - pi_female)\nlogodds_female <- log(odds_female)\n\n# Compare manual calculations with glm() estimates\ntibble(\n  Source = c(\"Manual calculation\", \"glm() estimates\"),\n  `Intercept (a)` = c(round(logodds_male, 3),\n                       round(coef(model1)[1], 3)),\n  `Slope (b)` = c(round(logodds_female - logodds_male, 3),\n                   round(coef(model1)[2], 3))\n) |>\n  kable(align = \"lrr\")\n```\n\n::: {.cell-output-display}\n\n\n|Source             | Intercept (a)| Slope (b)|\n|:------------------|-------------:|---------:|\n|Manual calculation |        -1.444|     2.425|\n|glm() estimates    |        -1.444|     2.425|\n\n\n:::\n:::\n\n\n### Output Interpretation\n\n::: {.cell}\n\n```{.r .cell-code  code-fold=\"true\" code-summary=\"Show R Code\"}\n# Manual computation of logistic regression coefficients\n# For males (sex = 0): reference group\npi_male <- mean(titanic$survived[titanic$sex == 0])\nodds_male <- pi_male / (1 - pi_male)\nlogodds_male <- log(odds_male)\n\n# For females (sex = 1)\npi_female <- mean(titanic$survived[titanic$sex == 1])\nodds_female <- pi_female / (1 - pi_female)\nlogodds_female <- log(odds_female)\n\n# Compare manual calculations with glm() estimates\ntibble(\n  Source = c(\"Manual calculation\", \"glm() estimates\"),\n  `Intercept (a)` = c(round(logodds_male, 3),\n                       round(coef(model1)[1], 3)),\n  `Slope (b)` = c(round(logodds_female - logodds_male, 3),\n                   round(coef(model1)[2], 3))\n) |>\n  kable(align = \"lrr\")\n```\n\n::: {.cell-output-display}\n\n\n|Source             | Intercept (a)| Slope (b)|\n|:------------------|-------------:|---------:|\n|Manual calculation |        -1.444|     2.425|\n|glm() estimates    |        -1.444|     2.425|\n\n\n:::\n:::\n\nThis confirms what the logistic regression coefficients mean for a dummy predictor:\n\n- $a = \\text{logit}(\\hat{\\pi}_{\\text{male}})$: the log-odds of survival for the reference group\n- $b = \\text{logit}(\\hat{\\pi}_{\\text{female}}) - \\text{logit}(\\hat{\\pi}_{\\text{male}})$: the difference in log-odds between the two groups\n\n### Code Explanation\n\n::: {.cell}\n\n```{.r .cell-code}\n# Manual computation of logistic regression coefficients\n# For males (sex = 0): reference group\npi_male <- mean(titanic$survived[titanic$sex == 0])\nodds_male <- pi_male / (1 - pi_male)\nlogodds_male <- log(odds_male)\n\n# For females (sex = 1)\npi_female <- mean(titanic$survived[titanic$sex == 1])\nodds_female <- pi_female / (1 - pi_female)\nlogodds_female <- log(odds_female)\n\n# Compare manual calculations with glm() estimates\ntibble(\n  Source = c(\"Manual calculation\", \"glm() estimates\"),\n  `Intercept (a)` = c(round(logodds_male, 3),\n                       round(coef(model1)[1], 3)),\n  `Slope (b)` = c(round(logodds_female - logodds_male, 3),\n                   round(coef(model1)[2], 3))\n) |>\n  kable(align = \"lrr\")\n```\n:::\n\n- For the reference group (males), the intercept equals the log-odds of survival\n- The slope equals the difference in log-odds between females and males: $\\text{logit}(\\hat{\\pi}_{\\text{female}}) - \\text{logit}(\\hat{\\pi}_{\\text{male}})$\n- The manual calculations match the `glm()` output exactly (within rounding)\n\n\n:::\n\n### Model Performance\n\n::: {.panel-tabset}\n### Output\n\n::: {.cell}\n\n```{.r .cell-code  code-fold=\"true\" code-summary=\"Show R Code\"}\n# Model performance metrics for logistic regression\nperformance::model_performance(model1) |> print_md()\n```\n\n::: {.cell-output-display}\n\n\nTable: Indices of model performance\n\n|AIC    |   AICc |    BIC | Tjur's R2 | RMSE | Sigma | Log_loss | Score_log | Score_spherical |  PCP |\n|:------|:------:|:------:|:---------:|:----:|:-----:|:--------:|:---------:|:---------------:|:----:|\n|1372.1 | 1372.1 | 1382.5 |      0.28 | 0.41 |     1 |     0.52 |   -297.19 |            0.01 | 0.66 |\n\n\n:::\n:::\n\n\n### Output Interpretation\n\n::: {.cell}\n\n```{.r .cell-code  code-fold=\"true\" code-summary=\"Show R Code\"}\n# Model performance metrics for logistic regression\nperformance::model_performance(model1) |> print_md()\n```\n\n::: {.cell-output-display}\n\n\nTable: Indices of model performance\n\n|AIC    |   AICc |    BIC | Tjur's R2 | RMSE | Sigma | Log_loss | Score_log | Score_spherical |  PCP |\n|:------|:------:|:------:|:---------:|:----:|:-----:|:--------:|:---------:|:---------------:|:----:|\n|1372.1 | 1372.1 | 1382.5 |      0.28 | 0.41 |     1 |     0.52 |   -297.19 |            0.01 | 0.66 |\n\n\n:::\n:::\n\nThe AIC and BIC provide baselines for model comparison --- we will use them later when comparing models with different predictors. Tjur's $R^2$ (also called the coefficient of discrimination) measures how well the model separates survivors from non-survivors. A higher value indicates better discrimination. For this simple model with only sex as a predictor, the value indicates moderate discriminatory power, which makes sense given the strong but imperfect association between sex and survival.\n\n### Code Explanation\n\n::: {.cell}\n\n```{.r .cell-code}\n# Model performance metrics for logistic regression\nperformance::model_performance(model1) |> print_md()\n```\n:::\n\n- `model_performance()` reports several fit indices for logistic regression, including:\n  - **AIC** and **BIC**: Information criteria (lower is better) --- useful for comparing models\n  - **Log-likelihood**: The maximized log-likelihood value\n  - **Tjur's $R^2$**: A pseudo-$R^2$ measure that compares average predicted probabilities for events ($y=1$) versus non-events ($y=0$)\n- Unlike linear regression, there is no single universally accepted $R^2$ for logistic regression\n\n\n:::\n\n\n## Odds Ratios {#sec-ch9-odds-ratios}\n\n### Exponentiated Coefficients\n\nThe log-odds coefficients from the model output are not directly interpretable in practical terms. The solution is to **exponentiate** them, which converts log-odds to **odds ratios**:\n\n::: {.panel-tabset}\n### Output\n\n::: {.cell}\n\n```{.r .cell-code  code-fold=\"true\" code-summary=\"Show R Code\"}\n# Exponentiated coefficients = odds ratios\nmodel_parameters(model1, exponentiate = TRUE) |> print_md()\n```\n\n::: {.cell-output-display}\n\n\n|Parameter   | Odds Ratio |   SE |        95% CI |      z |      p |\n|:-----------|:----------:|:----:|:-------------:|:------:|:------:|\n|(Intercept) |       0.24 | 0.02 |  (0.20, 0.28) | -16.48 | < .001 |\n|sex         |      11.31 | 1.54 | (8.69, 14.81) |  17.83 | < .001 |\n\n\n:::\n:::\n\n\n### Output Interpretation\n\n::: {.cell}\n\n```{.r .cell-code  code-fold=\"true\" code-summary=\"Show R Code\"}\n# Exponentiated coefficients = odds ratios\nmodel_parameters(model1, exponentiate = TRUE) |> print_md()\n```\n\n::: {.cell-output-display}\n\n\n|Parameter   | Odds Ratio |   SE |        95% CI |      z |      p |\n|:-----------|:----------:|:----:|:-------------:|:------:|:------:|\n|(Intercept) |       0.24 | 0.02 |  (0.20, 0.28) | -16.48 | < .001 |\n|sex         |      11.31 | 1.54 | (8.69, 14.81) |  17.83 | < .001 |\n\n\n:::\n:::\n\n- **Intercept** ($e^a$): The **odds** of survival for males. Since $a$ is the log-odds for the reference group, $e^a$ is the odds for the reference group.\n- **sex** ($e^b$): The **odds ratio** comparing females to males. This tells us how many times **higher** (or lower) the odds of survival are for females relative to males.\n\n### Code Explanation\n\n::: {.cell}\n\n```{.r .cell-code}\n# Exponentiated coefficients = odds ratios\nmodel_parameters(model1, exponentiate = TRUE) |> print_md()\n```\n:::\n\n- `model_parameters(model1, exponentiate = TRUE)`: Exponentiates all coefficients and their confidence intervals\n- `|> print_md()` formats the output as a clean markdown table\n- The `Coefficient` column now shows **odds ratios** rather than log-odds coefficients\n- Confidence intervals are also on the odds ratio scale\n\n\n:::\n\n### Computing the Odds Ratio Manually\n\n::: {.panel-tabset}\n### Output\n\n::: {.cell}\n\n```{.r .cell-code  code-fold=\"true\" code-summary=\"Show R Code\"}\n# Manual odds ratio calculation\nor_manual <- odds_female / odds_male\n\ntibble(\n  Measure = c(\"Odds (Males)\", \"Odds (Females)\",\n              \"Odds Ratio (Female / Male)\", \"exp(b) from model\"),\n  Value = c(round(odds_male, 3), round(odds_female, 3),\n            round(or_manual, 3), round(exp(coef(model1)[2]), 3))\n) |>\n  kable(align = \"lr\")\n```\n\n::: {.cell-output-display}\n\n\n|Measure                    |  Value|\n|:--------------------------|------:|\n|Odds (Males)               |  0.236|\n|Odds (Females)             |  2.669|\n|Odds Ratio (Female / Male) | 11.307|\n|exp(b) from model          | 11.307|\n\n\n:::\n:::\n\n\n### Output Interpretation\n\n::: {.cell}\n\n```{.r .cell-code  code-fold=\"true\" code-summary=\"Show R Code\"}\n# Manual odds ratio calculation\nor_manual <- odds_female / odds_male\n\ntibble(\n  Measure = c(\"Odds (Males)\", \"Odds (Females)\",\n              \"Odds Ratio (Female / Male)\", \"exp(b) from model\"),\n  Value = c(round(odds_male, 3), round(odds_female, 3),\n            round(or_manual, 3), round(exp(coef(model1)[2]), 3))\n) |>\n  kable(align = \"lr\")\n```\n\n::: {.cell-output-display}\n\n\n|Measure                    |  Value|\n|:--------------------------|------:|\n|Odds (Males)               |  0.236|\n|Odds (Females)             |  2.669|\n|Odds Ratio (Female / Male) | 11.307|\n|exp(b) from model          | 11.307|\n\n\n:::\n:::\n\nThe odds ratio provides a single number summarizing the strength of the association between sex and survival:\n\n- $\\text{OR} = 1$: No association --- the odds are the same in both groups\n- $\\text{OR} > 1$: Positive association --- the odds are higher in the target group (here, females)\n- $\\text{OR} < 1$: Negative association --- the odds are lower in the target group\n\n### Code Explanation\n\n::: {.cell}\n\n```{.r .cell-code}\n# Manual odds ratio calculation\nor_manual <- odds_female / odds_male\n\ntibble(\n  Measure = c(\"Odds (Males)\", \"Odds (Females)\",\n              \"Odds Ratio (Female / Male)\", \"exp(b) from model\"),\n  Value = c(round(odds_male, 3), round(odds_female, 3),\n            round(or_manual, 3), round(exp(coef(model1)[2]), 3))\n) |>\n  kable(align = \"lr\")\n```\n:::\n\n- The odds ratio is simply the ratio of the odds for the two groups: $\\text{OR} = \\text{odds}_{\\text{female}} / \\text{odds}_{\\text{male}}$\n- This equals $e^b$ from the logistic regression model\n- An OR of approximately 11.3 means the odds of survival for women were about **11.3 times higher** than for men\n\n\n:::\n\n::: {.callout-important}\n## Odds Ratio Properties\n| OR Value | Meaning | Example |\n|:---------|:--------|:--------|\n| OR = 1 | No association | Sex has no relationship with survival |\n| OR > 1 | Positive association | Females have higher odds of survival |\n| OR < 1 | Negative association | Females have lower odds of survival |\n| OR = 2 | Odds are doubled | The odds are 2 times higher |\n| OR = 0.5 | Odds are halved | The odds are 50% lower (or half as large) |\n\nOdds ratios are **symmetric in a useful way**: if the OR for females vs males is 11.3, then the OR for males vs females is $1/11.3 = 0.089$.\n:::\n\n### The Critical Distinction: OR vs Probability Ratio\n\n::: {.callout-warning}\n## Odds Ratios Are NOT Probability Ratios!\nThis is one of the most common misinterpretations in applied research. Consider our Titanic data:\n\n- **Probability ratio** (relative risk): $P(\\text{survived} \\mid \\text{female}) / P(\\text{survived} \\mid \\text{male}) = 0.727 / 0.191 = 3.81$\n- **Odds ratio**: $\\text{odds}_{\\text{female}} / \\text{odds}_{\\text{male}} = 2.668 / 0.236 = 11.30$\n\nWomen were about **3.8 times more likely** to survive (probability ratio), but the **odds** of survival were about **11.3 times higher** for women (odds ratio). These are very different numbers!\n\n**When is OR $\\approx$ probability ratio?** Only when the outcome is **rare** (i.e., $\\pi$ is close to 0 in both groups). This is sometimes called the **rare disease assumption**. When the outcome is common (as it is here --- 38% overall survival rate), the OR substantially overstates the probability ratio.\n\n**Rule of thumb**: If $\\pi < 0.10$ in both groups, the OR is a reasonable approximation to the probability ratio. Otherwise, interpret the OR strictly as an odds ratio, not as a probability ratio.\n:::\n\n::: {.panel-tabset}\n### Output\n\n::: {.cell}\n\n```{.r .cell-code  code-fold=\"true\" code-summary=\"Show R Code\"}\n# Show how OR diverges from RR at different baseline probabilities\nor_rr_data <- tibble(\n  pi_0 = seq(0.01, 0.50, by = 0.01),  # baseline probability\n  rr = 2.0  # fix probability ratio at 2\n) |>\n  mutate(\n    pi_1 = pmin(pi_0 * rr, 0.99),  # ensure pi_1 <= 1\n    odds_0 = pi_0 / (1 - pi_0),\n    odds_1 = pi_1 / (1 - pi_1),\n    or = odds_1 / odds_0,\n    actual_rr = pi_1 / pi_0\n  ) |>\n  filter(pi_1 < 1)\n\nggplot(or_rr_data, aes(x = pi_0)) +\n  geom_line(aes(y = or, color = \"Odds Ratio\"), linewidth = 1.2) +\n  geom_line(aes(y = actual_rr, color = \"Probability Ratio\"), linewidth = 1.2,\n            linetype = \"dashed\") +\n  scale_color_manual(\n    values = c(\"Odds Ratio\" = ber640_colors[\"secondary\"],\n               \"Probability Ratio\" = ber640_colors[\"accent\"]),\n    name = \"\"\n  ) +\n  labs(\n    title = \"Odds Ratio vs Probability Ratio\",\n    subtitle = \"When the true probability ratio is 2.0\",\n    x = expression(\"Baseline Probability\" ~ (pi[0])),\n    y = \"Ratio\"\n  )\n```\n\n::: {.cell-output-display}\n![Odds ratio vs probability ratio (relative risk) across different baseline probabilities. When the event is rare (left side of the plot), the two measures are similar. As the baseline probability increases, the odds ratio increasingly overstates the relative risk.](09-simple-logistic-regression_files/figure-html/fig-ch9-or-vs-rr-1.png){#fig-ch9-or-vs-rr fig-alt='Line plot with baseline probability on the x-axis ranging from 0.01 to 0.50 and the effect measure value on the y-axis. Two lines are shown: one for the probability ratio (relative risk) fixed at 2.0, and one for the corresponding odds ratio. At low baseline probabilities the two lines nearly overlap, but as the baseline probability increases the odds ratio line diverges upward, demonstrating that the odds ratio progressively overstates the relative risk when the outcome is not rare.' width=2400}\n:::\n:::\n\n\n### Output Interpretation\n\n::: {.cell}\n\n```{.r .cell-code  code-fold=\"true\" code-summary=\"Show R Code\"}\n# Show how OR diverges from RR at different baseline probabilities\nor_rr_data <- tibble(\n  pi_0 = seq(0.01, 0.50, by = 0.01),  # baseline probability\n  rr = 2.0  # fix probability ratio at 2\n) |>\n  mutate(\n    pi_1 = pmin(pi_0 * rr, 0.99),  # ensure pi_1 <= 1\n    odds_0 = pi_0 / (1 - pi_0),\n    odds_1 = pi_1 / (1 - pi_1),\n    or = odds_1 / odds_0,\n    actual_rr = pi_1 / pi_0\n  ) |>\n  filter(pi_1 < 1)\n\nggplot(or_rr_data, aes(x = pi_0)) +\n  geom_line(aes(y = or, color = \"Odds Ratio\"), linewidth = 1.2) +\n  geom_line(aes(y = actual_rr, color = \"Probability Ratio\"), linewidth = 1.2,\n            linetype = \"dashed\") +\n  scale_color_manual(\n    values = c(\"Odds Ratio\" = ber640_colors[\"secondary\"],\n               \"Probability Ratio\" = ber640_colors[\"accent\"]),\n    name = \"\"\n  ) +\n  labs(\n    title = \"Odds Ratio vs Probability Ratio\",\n    subtitle = \"When the true probability ratio is 2.0\",\n    x = expression(\"Baseline Probability\" ~ (pi[0])),\n    y = \"Ratio\"\n  )\n```\n\n::: {.cell-output-display}\n![](09-simple-logistic-regression_files/figure-html/unnamed-chunk-46-1.png){width=2400}\n:::\n:::\n\nThis plot demonstrates that the odds ratio is a **faithful** measure of the odds ratio (by definition), but it should **not** be interpreted as a probability ratio or relative risk unless the outcome is rare in both groups.\n\n### Code Explanation\n\n::: {.cell}\n\n```{.r .cell-code}\n# Show how OR diverges from RR at different baseline probabilities\nor_rr_data <- tibble(\n  pi_0 = seq(0.01, 0.50, by = 0.01),  # baseline probability\n  rr = 2.0  # fix probability ratio at 2\n) |>\n  mutate(\n    pi_1 = pmin(pi_0 * rr, 0.99),  # ensure pi_1 <= 1\n    odds_0 = pi_0 / (1 - pi_0),\n    odds_1 = pi_1 / (1 - pi_1),\n    or = odds_1 / odds_0,\n    actual_rr = pi_1 / pi_0\n  ) |>\n  filter(pi_1 < 1)\n\nggplot(or_rr_data, aes(x = pi_0)) +\n  geom_line(aes(y = or, color = \"Odds Ratio\"), linewidth = 1.2) +\n  geom_line(aes(y = actual_rr, color = \"Probability Ratio\"), linewidth = 1.2,\n            linetype = \"dashed\") +\n  scale_color_manual(\n    values = c(\"Odds Ratio\" = ber640_colors[\"secondary\"],\n               \"Probability Ratio\" = ber640_colors[\"accent\"]),\n    name = \"\"\n  ) +\n  labs(\n    title = \"Odds Ratio vs Probability Ratio\",\n    subtitle = \"When the true probability ratio is 2.0\",\n    x = expression(\"Baseline Probability\" ~ (pi[0])),\n    y = \"Ratio\"\n  )\n```\n:::\n\n- We fix the true probability ratio (relative risk) at exactly 2.0 and vary the baseline probability $\\pi_0$\n- As $\\pi_0$ increases, the odds ratio grows increasingly larger than the true probability ratio\n- At $\\pi_0 = 0.01$, $\\text{OR} \\approx \\text{RR} \\approx 2.0$ (the rare event approximation works)\n- At $\\pi_0 = 0.40$, the OR is substantially larger than 2.0, even though the probability ratio is still exactly 2.0\n\n\n:::\n\n::: {.callout-warning}\n## Common Misconceptions About Odds Ratios\n\n1. **\"An OR of 2 means twice as likely.\"** This is only true when the outcome is rare. An OR of 2 means the **odds** are doubled, not the probability. When the baseline probability is 40%, an OR of 2 corresponds to a probability of about 57%, not 80%.\n\n2. **\"An OR of 0.5 and an OR of 2 are equally strong.\"** They are! An OR of 0.5 for group A vs B is the same as an OR of 2.0 for group B vs A. Odds ratios are symmetric around 1 on the log scale: $\\log(0.5) = -0.69$ and $\\log(2.0) = 0.69$.\n\n3. **\"A non-significant OR means no effect.\"** Non-significance may reflect low power rather than no effect. Always examine confidence intervals alongside $p$-values.\n\n4. **\"You can compare ORs across studies with different baseline rates.\"** Be cautious --- odds ratios can differ between populations even when the underlying causal effect is constant, due to non-collapsibility of the OR.\n:::\n\n### Odds Ratios for Continuous Predictors\n\nWhen the predictor is continuous, $e^{\\beta}$ represents the multiplicative change in odds for a **one-unit increase** in $x$. Let us fit a second model using age as a continuous predictor:\n\n::: {.panel-tabset}\n### Output\n\n::: {.cell}\n\n```{.r .cell-code  code-fold=\"true\" code-summary=\"Show R Code\"}\n# Fit logistic regression with age as continuous predictor\nmodel2 <- glm(survived ~ age, family = binomial, data = titanic)\n\n# Coefficients on log-odds scale\nmodel_parameters(model2) |> print_md()\n```\n\n::: {.cell-output-display}\n\n\n|Parameter   |  Log-Odds |       SE |            95% CI |     z |     p |\n|:-----------|:---------:|:--------:|:-----------------:|:-----:|:-----:|\n|(Intercept) |     -0.14 |     0.14 |     (-0.42, 0.15) | -0.94 | 0.345 |\n|age         | -7.90e-03 | 4.41e-03 | (-0.02, 7.03e-04) | -1.79 | 0.073 |\n\n\n:::\n:::\n\n\n### Output Interpretation\n\n::: {.cell}\n\n```{.r .cell-code  code-fold=\"true\" code-summary=\"Show R Code\"}\n# Fit logistic regression with age as continuous predictor\nmodel2 <- glm(survived ~ age, family = binomial, data = titanic)\n\n# Coefficients on log-odds scale\nmodel_parameters(model2) |> print_md()\n```\n\n::: {.cell-output-display}\n\n\n|Parameter   |  Log-Odds |       SE |            95% CI |     z |     p |\n|:-----------|:---------:|:--------:|:-----------------:|:-----:|:-----:|\n|(Intercept) |     -0.14 |     0.14 |     (-0.42, 0.15) | -0.94 | 0.345 |\n|age         | -7.90e-03 | 4.41e-03 | (-0.02, 7.03e-04) | -1.79 | 0.073 |\n\n\n:::\n:::\n\nThe output shows the intercept and the coefficient for `age` on the log-odds scale. A negative coefficient for `age` indicates that older passengers had lower log-odds of survival. However, interpreting coefficients on the log-odds scale is not intuitive --- the next tabset exponentiates these values to produce odds ratios.\n\n### Code Explanation\n\n::: {.cell}\n\n```{.r .cell-code}\n# Fit logistic regression with age as continuous predictor\nmodel2 <- glm(survived ~ age, family = binomial, data = titanic)\n\n# Coefficients on log-odds scale\nmodel_parameters(model2) |> print_md()\n```\n:::\n\n- `glm(survived ~ age, family = binomial)`: Fits logistic regression with `age` (continuous) as the predictor\n- The coefficient for `age` represents the change in log-odds of survival per one-year increase in age\n- `|> print_md()` formats the output as a clean markdown table\n\n\n:::\n\n::: {.panel-tabset}\n### Output\n\n::: {.cell}\n\n```{.r .cell-code  code-fold=\"true\" code-summary=\"Show R Code\"}\n# Odds ratios for continuous predictor\nmodel_parameters(model2, exponentiate = TRUE) |> print_md()\n```\n\n::: {.cell-output-display}\n\n\n|Parameter   | Odds Ratio |       SE |       95% CI |     z |     p |\n|:-----------|:----------:|:--------:|:------------:|:-----:|:-----:|\n|(Intercept) |       0.87 |     0.13 | (0.66, 1.16) | -0.94 | 0.345 |\n|age         |       0.99 | 4.37e-03 | (0.98, 1.00) | -1.79 | 0.073 |\n\n\n:::\n:::\n\n\n### Output Interpretation\n\n::: {.cell}\n\n```{.r .cell-code  code-fold=\"true\" code-summary=\"Show R Code\"}\n# Odds ratios for continuous predictor\nmodel_parameters(model2, exponentiate = TRUE) |> print_md()\n```\n\n::: {.cell-output-display}\n\n\n|Parameter   | Odds Ratio |       SE |       95% CI |     z |     p |\n|:-----------|:----------:|:--------:|:------------:|:-----:|:-----:|\n|(Intercept) |       0.87 |     0.13 | (0.66, 1.16) | -0.94 | 0.345 |\n|age         |       0.99 | 4.37e-03 | (0.98, 1.00) | -1.79 | 0.073 |\n\n\n:::\n:::\n\nFor a continuous predictor, the interpretation of $e^{\\beta}$ is:\n\n- $e^{\\beta} = 1$: No association between $x$ and the outcome\n- $e^{\\beta} > 1$: Each one-unit increase in $x$ **increases** the odds\n- $e^{\\beta} < 1$: Each one-unit increase in $x$ **decreases** the odds\n\nBecause the effect is **multiplicative**, a 10-year increase in age multiplies the odds by $e^{10\\beta} = (e^{\\beta})^{10}$. This multiplicative property is a fundamental feature of logistic regression.\n\n### Code Explanation\n\n::: {.cell}\n\n```{.r .cell-code}\n# Odds ratios for continuous predictor\nmodel_parameters(model2, exponentiate = TRUE) |> print_md()\n```\n:::\n\n- The exponentiated coefficient for `age` is the **odds ratio per one-year increase in age**\n- If $e^b = 0.993$, this means the odds of survival decrease by about 0.7% for each additional year of age\n\n\n:::\n\n::: {.callout-tip}\n## Multiplicative Effects on Odds\nIn linear regression, effects are **additive**: a one-unit increase in $x$ adds $\\beta$ to the expected value of $y$.\n\nIn logistic regression, effects are **multiplicative on the odds scale**: a one-unit increase in $x$ multiplies the odds by $e^{\\beta}$.\n\n| $e^{\\beta}$ | Interpretation |\n|:-------------|:---------------|\n| 1.00 | No change in odds |\n| 1.50 | Odds increase by 50% |\n| 2.00 | Odds double |\n| 0.50 | Odds are halved (decrease by 50%) |\n| 0.80 | Odds decrease by 20% |\n\nTo express as a percentage change: $(e^{\\beta} - 1) \\times 100\\%$.\n:::\n\n### Visualizing Odds Ratios {#sec-ch9-or-viz}\n\nA forest plot (or dot plot) is the standard way to display odds ratios with confidence intervals. Even with a single predictor, this visualization establishes a convention you will use extensively in multiple logistic regression:\n\n::: {.panel-tabset}\n### Output\n\n::: {.cell}\n\n```{.r .cell-code  code-fold=\"true\" code-summary=\"Show R Code\"}\n# Collect odds ratios from both models\nor_data <- bind_rows(\n  tidy(model1, exponentiate = TRUE, conf.int = TRUE) |>\n    filter(term != \"(Intercept)\") |>\n    mutate(model = \"Model 1: Sex\",\n           term_label = \"Female vs Male\"),\n  tidy(model2, exponentiate = TRUE, conf.int = TRUE) |>\n    filter(term != \"(Intercept)\") |>\n    mutate(model = \"Model 2: Age\",\n           term_label = \"Per 1-year increase\"),\n  # Also show a 10-year OR for age\n  tidy(model2, conf.int = TRUE) |>\n    filter(term != \"(Intercept)\") |>\n    mutate(\n      estimate = exp(estimate * 10),\n      conf.low = exp(conf.low * 10),\n      conf.high = exp(conf.high * 10),\n      model = \"Model 2: Age\",\n      term_label = \"Per 10-year increase\"\n    )\n)\n\nggplot(or_data, aes(x = estimate, y = term_label, color = model)) +\n  geom_vline(xintercept = 1, linetype = \"dashed\", alpha = 0.5) +\n  geom_pointrange(aes(xmin = conf.low, xmax = conf.high),\n                  size = 0.8, linewidth = 1) +\n  scale_color_manual(\n    values = c(ber640_colors[\"accent\"], ber640_colors[\"secondary\"]),\n    name = \"\"\n  ) +\n  scale_x_log10(breaks = c(0.5, 1, 2, 5, 10, 15)) +\n  labs(\n    title = \"Odds Ratios with 95% Confidence Intervals\",\n    x = \"Odds Ratio (log scale)\",\n    y = NULL\n  )\n```\n\n::: {.cell-output-display}\n![Odds ratio plot comparing the sex and age models. The dashed vertical line at OR = 1 marks no association. Points to the right indicate higher odds of survival; points to the left indicate lower odds. The sex effect is dramatic (OR = 11.3), while the age effect is small (OR = 0.993 per year, OR = 0.934 per decade).](09-simple-logistic-regression_files/figure-html/fig-ch9-or-forest-1.png){#fig-ch9-or-forest fig-alt='Forest plot displaying odds ratios with 95 percent confidence intervals for predictors from two logistic regression models. The y-axis lists three terms: Female vs Male from Model 1, and Age (per year) and Age (per decade) from Model 2. The x-axis shows odds ratios on a log scale. A vertical dashed line at OR equals 1 marks no association. The Female vs Male point is far to the right at 11.3, indicating dramatically higher odds of survival for women. The age terms are near 1, indicating small effects per year and per decade.' width=2400}\n:::\n:::\n\n\n### Output Interpretation\n\n::: {.cell}\n\n```{.r .cell-code  code-fold=\"true\" code-summary=\"Show R Code\"}\n# Collect odds ratios from both models\nor_data <- bind_rows(\n  tidy(model1, exponentiate = TRUE, conf.int = TRUE) |>\n    filter(term != \"(Intercept)\") |>\n    mutate(model = \"Model 1: Sex\",\n           term_label = \"Female vs Male\"),\n  tidy(model2, exponentiate = TRUE, conf.int = TRUE) |>\n    filter(term != \"(Intercept)\") |>\n    mutate(model = \"Model 2: Age\",\n           term_label = \"Per 1-year increase\"),\n  # Also show a 10-year OR for age\n  tidy(model2, conf.int = TRUE) |>\n    filter(term != \"(Intercept)\") |>\n    mutate(\n      estimate = exp(estimate * 10),\n      conf.low = exp(conf.low * 10),\n      conf.high = exp(conf.high * 10),\n      model = \"Model 2: Age\",\n      term_label = \"Per 10-year increase\"\n    )\n)\n\nggplot(or_data, aes(x = estimate, y = term_label, color = model)) +\n  geom_vline(xintercept = 1, linetype = \"dashed\", alpha = 0.5) +\n  geom_pointrange(aes(xmin = conf.low, xmax = conf.high),\n                  size = 0.8, linewidth = 1) +\n  scale_color_manual(\n    values = c(ber640_colors[\"accent\"], ber640_colors[\"secondary\"]),\n    name = \"\"\n  ) +\n  scale_x_log10(breaks = c(0.5, 1, 2, 5, 10, 15)) +\n  labs(\n    title = \"Odds Ratios with 95% Confidence Intervals\",\n    x = \"Odds Ratio (log scale)\",\n    y = NULL\n  )\n```\n\n::: {.cell-output-display}\n![](09-simple-logistic-regression_files/figure-html/unnamed-chunk-52-1.png){width=2400}\n:::\n:::\n\nThe forest plot reveals:\n\n- **Sex**: The OR of approximately 11.3 (with narrow CI entirely above 1) indicates a very strong association --- women had dramatically higher odds of survival\n- **Age (per year)**: The OR is very close to 1, reflecting a tiny per-year effect. The CI barely excludes 1\n- **Age (per decade)**: Rescaling to a 10-year unit makes the age effect more interpretable --- each additional decade of age reduces the odds of survival by roughly 6--7%\n\nUsing a log scale ensures that an OR of 2 and an OR of 0.5 are displayed equidistant from 1, reflecting their equal strength in opposite directions.\n\n### Code Explanation\n\n::: {.cell}\n\n```{.r .cell-code}\n# Collect odds ratios from both models\nor_data <- bind_rows(\n  tidy(model1, exponentiate = TRUE, conf.int = TRUE) |>\n    filter(term != \"(Intercept)\") |>\n    mutate(model = \"Model 1: Sex\",\n           term_label = \"Female vs Male\"),\n  tidy(model2, exponentiate = TRUE, conf.int = TRUE) |>\n    filter(term != \"(Intercept)\") |>\n    mutate(model = \"Model 2: Age\",\n           term_label = \"Per 1-year increase\"),\n  # Also show a 10-year OR for age\n  tidy(model2, conf.int = TRUE) |>\n    filter(term != \"(Intercept)\") |>\n    mutate(\n      estimate = exp(estimate * 10),\n      conf.low = exp(conf.low * 10),\n      conf.high = exp(conf.high * 10),\n      model = \"Model 2: Age\",\n      term_label = \"Per 10-year increase\"\n    )\n)\n\nggplot(or_data, aes(x = estimate, y = term_label, color = model)) +\n  geom_vline(xintercept = 1, linetype = \"dashed\", alpha = 0.5) +\n  geom_pointrange(aes(xmin = conf.low, xmax = conf.high),\n                  size = 0.8, linewidth = 1) +\n  scale_color_manual(\n    values = c(ber640_colors[\"accent\"], ber640_colors[\"secondary\"]),\n    name = \"\"\n  ) +\n  scale_x_log10(breaks = c(0.5, 1, 2, 5, 10, 15)) +\n  labs(\n    title = \"Odds Ratios with 95% Confidence Intervals\",\n    x = \"Odds Ratio (log scale)\",\n    y = NULL\n  )\n```\n:::\n\n- `tidy(model, exponentiate = TRUE, conf.int = TRUE)` extracts odds ratios with CIs from each model\n- For the age model, we also compute a **10-year** OR by multiplying the log-coefficient by 10 before exponentiating: $e^{10\\beta}$\n- The x-axis uses a **log scale** (`scale_x_log10()`), which is standard for odds ratios because it makes the plot symmetric around OR = 1\n- `geom_pointrange()` draws the point estimate with error bars for the confidence interval\n\n\n:::\n\n\n## Predicted Probabilities and Visualization {#sec-ch9-predicted}\n\n### Predicted Probabilities from the Model\n\nWhile odds ratios summarize the effect of a predictor, **predicted probabilities** are often more intuitive for communication. We can convert the model's log-odds predictions to the probability scale:\n\n::: {.panel-tabset}\n### Output\n\n::: {.cell}\n\n```{.r .cell-code  code-fold=\"true\" code-summary=\"Show R Code\"}\n# Predicted probabilities from model1 (sex predictor)\npredictions(model1,\n            newdata = datagrid(sex = c(0, 1)),\n            type = \"response\") |>\n  as_tibble() |>\n  mutate(sex_label = ifelse(sex == 0, \"Male\", \"Female\")) |>\n  select(sex_label, estimate, conf.low, conf.high) |>\n  kable(digits = 3,\n        col.names = c(\"Sex\", \"P(Survived)\", \"95% CI Lower\", \"95% CI Upper\"))\n```\n\n::: {.cell-output-display}\n\n\n|Sex    | P(Survived)| 95% CI Lower| 95% CI Upper|\n|:------|-----------:|------------:|------------:|\n|Male   |       0.191|        0.164|        0.218|\n|Female |       0.727|        0.687|        0.768|\n\n\n:::\n:::\n\n\n### Output Interpretation\n\n::: {.cell}\n\n```{.r .cell-code  code-fold=\"true\" code-summary=\"Show R Code\"}\n# Predicted probabilities from model1 (sex predictor)\npredictions(model1,\n            newdata = datagrid(sex = c(0, 1)),\n            type = \"response\") |>\n  as_tibble() |>\n  mutate(sex_label = ifelse(sex == 0, \"Male\", \"Female\")) |>\n  select(sex_label, estimate, conf.low, conf.high) |>\n  kable(digits = 3,\n        col.names = c(\"Sex\", \"P(Survived)\", \"95% CI Lower\", \"95% CI Upper\"))\n```\n\n::: {.cell-output-display}\n\n\n|Sex    | P(Survived)| 95% CI Lower| 95% CI Upper|\n|:------|-----------:|------------:|------------:|\n|Male   |       0.191|        0.164|        0.218|\n|Female |       0.727|        0.687|        0.768|\n\n\n:::\n:::\n\nThe predicted probabilities are simply the observed survival proportions (since we have a single binary predictor). For models with continuous or multiple predictors, the predicted probabilities from the model smooth over the raw data.\n\n### Code Explanation\n\n::: {.cell}\n\n```{.r .cell-code}\n# Predicted probabilities from model1 (sex predictor)\npredictions(model1,\n            newdata = datagrid(sex = c(0, 1)),\n            type = \"response\") |>\n  as_tibble() |>\n  mutate(sex_label = ifelse(sex == 0, \"Male\", \"Female\")) |>\n  select(sex_label, estimate, conf.low, conf.high) |>\n  kable(digits = 3,\n        col.names = c(\"Sex\", \"P(Survived)\", \"95% CI Lower\", \"95% CI Upper\"))\n```\n:::\n\n- `predictions()` from the `marginaleffects` package computes predicted probabilities at specified values of the predictor\n- `datagrid(sex = c(0, 1))` creates a grid with both values of `sex`\n- `type = \"response\"` requests predictions on the **probability** scale (rather than the log-odds scale)\n- The output shows the predicted probability of survival for each sex, with 95% confidence intervals\n\n\n:::\n\n### Visualizing the Logistic Curve\n\n::: {.panel-tabset}\n### Output\n\n::: {.cell}\n\n```{.r .cell-code  code-fold=\"true\" code-summary=\"Show R Code\"}\nggplot(titanic_age, aes(x = age, y = survived)) +\n  geom_jitter(width = 0, height = 0.02, alpha = 0.1,\n              color = ber640_colors[\"primary\"]) +\n  geom_smooth(method = \"glm\", formula = y ~ x,\n              method.args = list(family = binomial),\n              color = ber640_colors[\"accent\"], fill = ber640_colors[\"accent\"],\n              alpha = 0.2, linewidth = 1.2) +\n  geom_rug(data = filter(titanic_age, survived == 1),\n           sides = \"t\", alpha = 0.1, color = ber640_colors[\"success\"]) +\n  geom_rug(data = filter(titanic_age, survived == 0),\n           sides = \"b\", alpha = 0.1, color = ber640_colors[\"secondary\"]) +\n  labs(\n    title = \"Logistic Regression: Survival by Age\",\n    x = \"Age (years)\",\n    y = \"P(Survived)\"\n  ) +\n  scale_y_continuous(labels = scales::percent)\n```\n\n::: {.cell-output-display}\n![Fitted logistic regression curve for the age model. The S-shaped curve shows how the predicted probability of survival decreases with age. The rug plot at the top and bottom shows the distribution of survivors (top) and non-survivors (bottom).](09-simple-logistic-regression_files/figure-html/fig-ch9-logistic-fit-age-1.png){#fig-ch9-logistic-fit-age fig-alt='Scatter plot with a fitted logistic regression curve showing predicted probability of survival on the y-axis versus passenger age on the x-axis. Individual observations are jittered at 0 and 1. The S-shaped curve gradually decreases from left to right, indicating that older passengers had lower predicted survival probabilities. Rug marks along the top edge show the age distribution of survivors and along the bottom edge show non-survivors, with a shaded confidence band around the fitted curve.' width=2400}\n:::\n:::\n\n\n### Output Interpretation\n\n::: {.cell}\n\n```{.r .cell-code  code-fold=\"true\" code-summary=\"Show R Code\"}\nggplot(titanic_age, aes(x = age, y = survived)) +\n  geom_jitter(width = 0, height = 0.02, alpha = 0.1,\n              color = ber640_colors[\"primary\"]) +\n  geom_smooth(method = \"glm\", formula = y ~ x,\n              method.args = list(family = binomial),\n              color = ber640_colors[\"accent\"], fill = ber640_colors[\"accent\"],\n              alpha = 0.2, linewidth = 1.2) +\n  geom_rug(data = filter(titanic_age, survived == 1),\n           sides = \"t\", alpha = 0.1, color = ber640_colors[\"success\"]) +\n  geom_rug(data = filter(titanic_age, survived == 0),\n           sides = \"b\", alpha = 0.1, color = ber640_colors[\"secondary\"]) +\n  labs(\n    title = \"Logistic Regression: Survival by Age\",\n    x = \"Age (years)\",\n    y = \"P(Survived)\"\n  ) +\n  scale_y_continuous(labels = scales::percent)\n```\n\n::: {.cell-output-display}\n![](09-simple-logistic-regression_files/figure-html/unnamed-chunk-56-1.png){width=2400}\n:::\n:::\n\nThe logistic curve shows a gradual decline in survival probability with age. Key observations:\n\n- Young passengers had the highest predicted survival probability\n- The curve is relatively flat, reflecting the modest effect of age on survival (compared to the dramatic effect of sex)\n- The wide confidence band at extreme ages reflects fewer observations\n\n### Code Explanation\n\n::: {.cell}\n\n```{.r .cell-code}\nggplot(titanic_age, aes(x = age, y = survived)) +\n  geom_jitter(width = 0, height = 0.02, alpha = 0.1,\n              color = ber640_colors[\"primary\"]) +\n  geom_smooth(method = \"glm\", formula = y ~ x,\n              method.args = list(family = binomial),\n              color = ber640_colors[\"accent\"], fill = ber640_colors[\"accent\"],\n              alpha = 0.2, linewidth = 1.2) +\n  geom_rug(data = filter(titanic_age, survived == 1),\n           sides = \"t\", alpha = 0.1, color = ber640_colors[\"success\"]) +\n  geom_rug(data = filter(titanic_age, survived == 0),\n           sides = \"b\", alpha = 0.1, color = ber640_colors[\"secondary\"]) +\n  labs(\n    title = \"Logistic Regression: Survival by Age\",\n    x = \"Age (years)\",\n    y = \"P(Survived)\"\n  ) +\n  scale_y_continuous(labels = scales::percent)\n```\n:::\n\n- `geom_smooth(method = \"glm\", formula = y ~ x, method.args = list(family = binomial))` fits and plots the logistic regression curve\n- The S-shaped curve stays within [0, 1], unlike the linear probability model\n- `geom_rug()` adds tick marks showing where survivors (top, green) and non-survivors (bottom, red) fall along the age axis\n- The shaded band is a 95% confidence band for the predicted probability\n\n\n:::\n\n### Using `plot_predictions()` for Quick Visualization\n\n::: {.panel-tabset}\n### Output\n\n::: {.cell}\n\n```{.r .cell-code  code-fold=\"true\" code-summary=\"Show R Code\"}\n# Quick plot using marginaleffects\nplot_predictions(model2, condition = \"age\", type = \"response\") +\n  labs(\n    title = \"Predicted Survival Probability by Age\",\n    x = \"Age (years)\",\n    y = \"P(Survived)\"\n  )\n```\n\n::: {.cell-output-display}\n![Predicted probability of survival as a function of age, with 95% confidence band, generated by plot_predictions() from the marginaleffects package.](09-simple-logistic-regression_files/figure-html/fig-ch9-plot-predictions-1.png){#fig-ch9-plot-predictions fig-alt='Line plot generated by the marginaleffects package showing predicted probability of survival on the y-axis versus age in years on the x-axis. A single logistic curve decreases gradually from higher predicted probabilities for younger passengers to lower probabilities for older passengers. A shaded 95 percent confidence band surrounds the curve, widening at the extremes of the age distribution where data are sparse.' width=2400}\n:::\n:::\n\n\n### Output Interpretation\n\n::: {.cell}\n\n```{.r .cell-code  code-fold=\"true\" code-summary=\"Show R Code\"}\n# Quick plot using marginaleffects\nplot_predictions(model2, condition = \"age\", type = \"response\") +\n  labs(\n    title = \"Predicted Survival Probability by Age\",\n    x = \"Age (years)\",\n    y = \"P(Survived)\"\n  )\n```\n\n::: {.cell-output-display}\n![](09-simple-logistic-regression_files/figure-html/unnamed-chunk-58-1.png){width=2400}\n:::\n:::\n\nThe plot shows the characteristic S-shaped (sigmoid) curve of logistic regression applied to real data. The predicted probability of survival decreases gradually with age, but the relationship is weak --- the curve is relatively flat. The wide confidence band at extreme ages (very young and very old) reflects the sparsity of observations at those ages. Compare this with the linear probability model plot earlier: the logistic curve stays within the [0, 1] bounds by design.\n\n### Code Explanation\n\n::: {.cell}\n\n```{.r .cell-code}\n# Quick plot using marginaleffects\nplot_predictions(model2, condition = \"age\", type = \"response\") +\n  labs(\n    title = \"Predicted Survival Probability by Age\",\n    x = \"Age (years)\",\n    y = \"P(Survived)\"\n  )\n```\n:::\n\n- `plot_predictions()` from `marginaleffects` is a one-line command for plotting model predictions\n- `condition = \"age\"` specifies the x-axis variable\n- `type = \"response\"` produces predictions on the probability scale\n- The function automatically computes and displays the 95% confidence band\n\n\n:::\n\n\n### Classification and Decision Thresholds {#sec-ch9-classification}\n\nLogistic regression predicts **probabilities**, not categories. To make a binary classification (e.g., predict \"survived\" or \"died\"), we must choose a **decision threshold**. A common default is 0.5, but this threshold is arbitrary and its choice has important consequences:\n\n::: {.panel-tabset}\n### Output\n\n::: {.cell}\n\n```{.r .cell-code  code-fold=\"true\" code-summary=\"Show R Code\"}\n# Compute sensitivity and specificity across thresholds\nthresholds <- seq(0.05, 0.95, by = 0.01)\n\n# Use the age model for continuous predicted probabilities\npred_probs <- predict(model2, type = \"response\")\nactual <- titanic_age$survived\n\nthreshold_metrics <- tibble(threshold = thresholds) |>\n  mutate(\n    sensitivity = map_dbl(threshold, \\(t) {\n      predicted <- as.integer(pred_probs >= t)\n      sum(predicted == 1 & actual == 1) / sum(actual == 1)\n    }),\n    specificity = map_dbl(threshold, \\(t) {\n      predicted <- as.integer(pred_probs >= t)\n      sum(predicted == 0 & actual == 0) / sum(actual == 0)\n    })\n  ) |>\n  pivot_longer(cols = c(sensitivity, specificity),\n               names_to = \"metric\", values_to = \"value\")\n\nggplot(threshold_metrics, aes(x = threshold, y = value,\n                              color = metric)) +\n  geom_line(linewidth = 1.2) +\n  geom_vline(xintercept = 0.5, linetype = \"dashed\", alpha = 0.5) +\n  scale_color_manual(\n    values = c(\"sensitivity\" = ber640_colors[\"accent\"],\n               \"specificity\" = ber640_colors[\"secondary\"]),\n    labels = c(\"Sensitivity (True Positive Rate)\",\n               \"Specificity (True Negative Rate)\"),\n    name = \"\"\n  ) +\n  scale_y_continuous(labels = scales::percent) +\n  labs(\n    title = \"Sensitivity vs Specificity Across Thresholds\",\n    subtitle = \"Age model --- illustrating the trade-off in binary classification\",\n    x = \"Classification Threshold\",\n    y = \"Rate\"\n  )\n```\n\n::: {.cell-output-display}\n![How the classification threshold affects sensitivity and specificity. As the threshold increases, fewer passengers are predicted to survive: sensitivity (correctly identifying survivors) decreases while specificity (correctly identifying non-survivors) increases. The dashed line marks the default threshold of 0.5.](09-simple-logistic-regression_files/figure-html/fig-ch9-classification-threshold-1.png){#fig-ch9-classification-threshold fig-alt='Line plot with classification threshold on the x-axis ranging from 0.05 to 0.95 and metric value on the y-axis from 0 to 1. Two crossing lines are displayed: sensitivity decreases from near 1.0 at low thresholds to near 0 at high thresholds, while specificity increases from near 0 to near 1.0 over the same range. The lines cross near the middle of the threshold range. A vertical dashed line at threshold equals 0.5 marks the default classification cutoff, illustrating the inherent tradeoff between correctly identifying survivors and non-survivors.' width=2400}\n:::\n:::\n\n\n### Output Interpretation\n\n::: {.cell}\n\n```{.r .cell-code  code-fold=\"true\" code-summary=\"Show R Code\"}\n# Compute sensitivity and specificity across thresholds\nthresholds <- seq(0.05, 0.95, by = 0.01)\n\n# Use the age model for continuous predicted probabilities\npred_probs <- predict(model2, type = \"response\")\nactual <- titanic_age$survived\n\nthreshold_metrics <- tibble(threshold = thresholds) |>\n  mutate(\n    sensitivity = map_dbl(threshold, \\(t) {\n      predicted <- as.integer(pred_probs >= t)\n      sum(predicted == 1 & actual == 1) / sum(actual == 1)\n    }),\n    specificity = map_dbl(threshold, \\(t) {\n      predicted <- as.integer(pred_probs >= t)\n      sum(predicted == 0 & actual == 0) / sum(actual == 0)\n    })\n  ) |>\n  pivot_longer(cols = c(sensitivity, specificity),\n               names_to = \"metric\", values_to = \"value\")\n\nggplot(threshold_metrics, aes(x = threshold, y = value,\n                              color = metric)) +\n  geom_line(linewidth = 1.2) +\n  geom_vline(xintercept = 0.5, linetype = \"dashed\", alpha = 0.5) +\n  scale_color_manual(\n    values = c(\"sensitivity\" = ber640_colors[\"accent\"],\n               \"specificity\" = ber640_colors[\"secondary\"]),\n    labels = c(\"Sensitivity (True Positive Rate)\",\n               \"Specificity (True Negative Rate)\"),\n    name = \"\"\n  ) +\n  scale_y_continuous(labels = scales::percent) +\n  labs(\n    title = \"Sensitivity vs Specificity Across Thresholds\",\n    subtitle = \"Age model --- illustrating the trade-off in binary classification\",\n    x = \"Classification Threshold\",\n    y = \"Rate\"\n  )\n```\n\n::: {.cell-output-display}\n![](09-simple-logistic-regression_files/figure-html/unnamed-chunk-60-1.png){width=2400}\n:::\n:::\n\nThis plot illustrates a fundamental trade-off in classification:\n\n- **Lowering the threshold** catches more true survivors (higher sensitivity) but also falsely classifies more non-survivors as survivors (lower specificity)\n- **Raising the threshold** reduces false positives (higher specificity) but misses more actual survivors (lower sensitivity)\n- The optimal threshold depends on the **costs of different errors** in your specific application. In medical screening, missing a true case (false negative) may be more costly than a false alarm; in spam filtering, the reverse may be true.\n\nThe age model has relatively weak discrimination, so the sensitivity and specificity curves are close together. A strong predictor like sex would show wider separation between the curves.\n\n### Code Explanation\n\n::: {.cell}\n\n```{.r .cell-code}\n# Compute sensitivity and specificity across thresholds\nthresholds <- seq(0.05, 0.95, by = 0.01)\n\n# Use the age model for continuous predicted probabilities\npred_probs <- predict(model2, type = \"response\")\nactual <- titanic_age$survived\n\nthreshold_metrics <- tibble(threshold = thresholds) |>\n  mutate(\n    sensitivity = map_dbl(threshold, \\(t) {\n      predicted <- as.integer(pred_probs >= t)\n      sum(predicted == 1 & actual == 1) / sum(actual == 1)\n    }),\n    specificity = map_dbl(threshold, \\(t) {\n      predicted <- as.integer(pred_probs >= t)\n      sum(predicted == 0 & actual == 0) / sum(actual == 0)\n    })\n  ) |>\n  pivot_longer(cols = c(sensitivity, specificity),\n               names_to = \"metric\", values_to = \"value\")\n\nggplot(threshold_metrics, aes(x = threshold, y = value,\n                              color = metric)) +\n  geom_line(linewidth = 1.2) +\n  geom_vline(xintercept = 0.5, linetype = \"dashed\", alpha = 0.5) +\n  scale_color_manual(\n    values = c(\"sensitivity\" = ber640_colors[\"accent\"],\n               \"specificity\" = ber640_colors[\"secondary\"]),\n    labels = c(\"Sensitivity (True Positive Rate)\",\n               \"Specificity (True Negative Rate)\"),\n    name = \"\"\n  ) +\n  scale_y_continuous(labels = scales::percent) +\n  labs(\n    title = \"Sensitivity vs Specificity Across Thresholds\",\n    subtitle = \"Age model --- illustrating the trade-off in binary classification\",\n    x = \"Classification Threshold\",\n    y = \"Rate\"\n  )\n```\n:::\n\n- **Sensitivity** (true positive rate): proportion of actual survivors correctly classified as survivors\n- **Specificity** (true negative rate): proportion of actual non-survivors correctly classified as non-survivors\n- At a low threshold (e.g., 0.1), almost everyone is predicted to survive --- high sensitivity but low specificity\n- At a high threshold (e.g., 0.9), almost no one is predicted to survive --- low sensitivity but high specificity\n- The vertical dashed line marks the conventional threshold of 0.5\n\n\n:::\n\n::: {.callout-tip}\n## Classification Is Optional\nLogistic regression's primary purpose is to **estimate probabilities and quantify associations** (via odds ratios and marginal effects). Classification is an additional step that requires choosing a threshold, and the default of 0.5 is rarely optimal. In most applied research, reporting predicted probabilities is more informative than reporting classifications.\n:::\n\n\n## Marginal Effects {#sec-ch9-marginal}\n\n### Why Marginal Effects?\n\nOdds ratios tell us about **multiplicative** changes in odds, but many audiences --- especially in policy and practice --- prefer to know about changes in **probability**. The problem is that in logistic regression, the effect of $x$ on the probability $\\pi$ depends on **where you are** on the curve. Near $\\pi = 0.5$, a one-unit increase in $x$ has a relatively large effect on probability; near $\\pi = 0$ or $\\pi = 1$, the same increase has a much smaller effect.\n\nThe **average marginal effect (AME)** solves this by computing the marginal effect at each observed value of $x$ and then averaging:\n\n$$\n\\text{AME} = \\frac{1}{n} \\sum_{i=1}^{n} \\frac{\\partial \\pi_i}{\\partial x_i}\n$$\n\n### Computing Average Marginal Effects\n\n::: {.panel-tabset}\n### Output\n\n::: {.cell}\n\n```{.r .cell-code  code-fold=\"true\" code-summary=\"Show R Code\"}\n# Average marginal effect of sex on survival probability\navg_slopes(model1, type = \"response\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\n Estimate Std. Error    z Pr(>|z|)     S 2.5 % 97.5 %\n    0.536     0.0247 21.7   <0.001 345.8 0.488  0.585\n\nTerm: sex\nType: response\nComparison: 1 - 0\n```\n\n\n:::\n:::\n\n\n### Output Interpretation\n\n::: {.cell}\n\n```{.r .cell-code  code-fold=\"true\" code-summary=\"Show R Code\"}\n# Average marginal effect of sex on survival probability\navg_slopes(model1, type = \"response\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\n Estimate Std. Error    z Pr(>|z|)     S 2.5 % 97.5 %\n    0.536     0.0247 21.7   <0.001 345.8 0.488  0.585\n\nTerm: sex\nType: response\nComparison: 1 - 0\n```\n\n\n:::\n:::\n\nThe AME for `sex` tells us: on average, being female (rather than male) is associated with an increase of approximately 54 percentage points in the probability of survival. This is a straightforward, intuitive measure of the effect on the probability scale.\n\nCompare the three ways of expressing the sex effect:\n\n| Measure | Value | Interpretation |\n|:--------|:------|:---------------|\n| Log-odds difference | $b \\approx 2.42$ | Females have 2.42 higher log-odds of survival |\n| Odds ratio | $e^b \\approx 11.3$ | Odds of survival are 11.3 times higher for females |\n| AME (probability) | $\\approx 0.54$ | Probability of survival is about 54 percentage points higher for females |\n\n### Code Explanation\n\n::: {.cell}\n\n```{.r .cell-code}\n# Average marginal effect of sex on survival probability\navg_slopes(model1, type = \"response\")\n```\n:::\n\n- `avg_slopes()` from `marginaleffects` computes the average marginal effect\n- `type = \"response\"` specifies that the effect should be on the probability scale\n- For a dummy variable, the AME is the average difference in predicted probability between the two groups\n\n\n:::\n\n::: {.panel-tabset}\n### Output\n\n::: {.cell}\n\n```{.r .cell-code  code-fold=\"true\" code-summary=\"Show R Code\"}\n# Average marginal effect of age on survival probability\navg_slopes(model2, type = \"response\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\n Estimate Std. Error    z Pr(>|z|)   S    2.5 %   97.5 %\n  -0.0019    0.00105 -1.8   0.0714 3.8 -0.00397 0.000165\n\nTerm: age\nType: response\nComparison: dY/dX\n```\n\n\n:::\n:::\n\n\n### Output Interpretation\n\n::: {.cell}\n\n```{.r .cell-code  code-fold=\"true\" code-summary=\"Show R Code\"}\n# Average marginal effect of age on survival probability\navg_slopes(model2, type = \"response\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\n Estimate Std. Error    z Pr(>|z|)   S    2.5 %   97.5 %\n  -0.0019    0.00105 -1.8   0.0714 3.8 -0.00397 0.000165\n\nTerm: age\nType: response\nComparison: dY/dX\n```\n\n\n:::\n:::\n\nThe AME for `age` tells us: on average, each additional year of age is associated with a decrease of approximately 1 percentage point in survival probability. This is much more intuitive than saying \"the odds decrease by a factor of 0.993 per year.\"\n\n### Code Explanation\n\n::: {.cell}\n\n```{.r .cell-code}\n# Average marginal effect of age on survival probability\navg_slopes(model2, type = \"response\")\n```\n:::\n\n- For the continuous predictor `age`, the AME represents the average change in survival probability per one-year increase in age\n- The AME is computed at each observed age and then averaged, accounting for the non-linear relationship between age and probability\n\n\n:::\n\n### Marginal Effects at Representative Values\n\nSometimes we want to see how the marginal effect varies across the range of the predictor:\n\n::: {.panel-tabset}\n### Output\n\n::: {.cell}\n\n```{.r .cell-code  code-fold=\"true\" code-summary=\"Show R Code\"}\n# Marginal effects at specific ages\nslopes_by_age <- slopes(model2,\n                        newdata = datagrid(age = seq(1, 75, by = 1)),\n                        type = \"response\")\n\nggplot(as_tibble(slopes_by_age), aes(x = age, y = estimate)) +\n  geom_ribbon(aes(ymin = conf.low, ymax = conf.high),\n              fill = ber640_colors[\"accent\"], alpha = 0.2) +\n  geom_line(color = ber640_colors[\"accent\"], linewidth = 1.2) +\n  geom_hline(yintercept = 0, linetype = \"dashed\", alpha = 0.5) +\n  labs(\n    title = \"Marginal Effect of Age on P(Survived)\",\n    subtitle = \"How the instantaneous effect of age varies across the age range\",\n    x = \"Age (years)\",\n    y = \"Marginal Effect (change in probability per year)\"\n  )\n```\n\n::: {.cell-output-display}\n![Marginal effect of age on survival probability (the slope of the logistic curve) as a function of age. The effect is strongest near the middle of the probability range and weakens as age increases or decreases.](09-simple-logistic-regression_files/figure-html/fig-ch9-marginal-age-1.png){#fig-ch9-marginal-age fig-alt='Line plot showing the marginal effect of age on survival probability on the y-axis versus age in years on the x-axis. A shaded 95 percent confidence ribbon surrounds the curve. The marginal effect is negative throughout, indicating that each additional year of age reduces survival probability. The magnitude of the effect is largest near the middle of the age range where predicted probabilities are closest to 0.5, and the effect attenuates toward both younger and older ages where probabilities approach the boundaries.' width=2400}\n:::\n:::\n\n\n### Output Interpretation\n\n::: {.cell}\n\n```{.r .cell-code  code-fold=\"true\" code-summary=\"Show R Code\"}\n# Marginal effects at specific ages\nslopes_by_age <- slopes(model2,\n                        newdata = datagrid(age = seq(1, 75, by = 1)),\n                        type = \"response\")\n\nggplot(as_tibble(slopes_by_age), aes(x = age, y = estimate)) +\n  geom_ribbon(aes(ymin = conf.low, ymax = conf.high),\n              fill = ber640_colors[\"accent\"], alpha = 0.2) +\n  geom_line(color = ber640_colors[\"accent\"], linewidth = 1.2) +\n  geom_hline(yintercept = 0, linetype = \"dashed\", alpha = 0.5) +\n  labs(\n    title = \"Marginal Effect of Age on P(Survived)\",\n    subtitle = \"How the instantaneous effect of age varies across the age range\",\n    x = \"Age (years)\",\n    y = \"Marginal Effect (change in probability per year)\"\n  )\n```\n\n::: {.cell-output-display}\n![](09-simple-logistic-regression_files/figure-html/unnamed-chunk-66-1.png){width=2400}\n:::\n:::\n\nThe marginal effect of age is negative throughout (each additional year decreases survival probability), but the magnitude varies:\n\n- The effect is strongest around the inflection point of the logistic curve\n- At extreme ages (very young or very old), the effect is weaker because the probability is already near its asymptote\n- This is a direct consequence of the S-shape of the logistic curve: changes in $x$ have the most impact when $\\pi$ is near 0.5\n\n### Code Explanation\n\n::: {.cell}\n\n```{.r .cell-code}\n# Marginal effects at specific ages\nslopes_by_age <- slopes(model2,\n                        newdata = datagrid(age = seq(1, 75, by = 1)),\n                        type = \"response\")\n\nggplot(as_tibble(slopes_by_age), aes(x = age, y = estimate)) +\n  geom_ribbon(aes(ymin = conf.low, ymax = conf.high),\n              fill = ber640_colors[\"accent\"], alpha = 0.2) +\n  geom_line(color = ber640_colors[\"accent\"], linewidth = 1.2) +\n  geom_hline(yintercept = 0, linetype = \"dashed\", alpha = 0.5) +\n  labs(\n    title = \"Marginal Effect of Age on P(Survived)\",\n    subtitle = \"How the instantaneous effect of age varies across the age range\",\n    x = \"Age (years)\",\n    y = \"Marginal Effect (change in probability per year)\"\n  )\n```\n:::\n\n- `slopes()` computes the marginal effect at each specified value of `age`\n- The marginal effect is the instantaneous slope of the logistic curve (the derivative $\\partial \\pi / \\partial x$) at each point\n- This plot shows how the sensitivity of survival probability to age varies across the age range\n\n\n:::\n\n\n## Comparing the Sex and Age Models {#sec-ch9-comparison}\n\nLet us put both models side by side to reinforce the key concepts:\n\n::: {.panel-tabset}\n### Output\n\n::: {#tbl-ch9-comparison .cell tbl-cap='Comparison of two simple logistic regression models predicting Titanic survival. Model 1 uses sex (binary predictor); Model 2 uses age (continuous predictor).'}\n\n```{.r .cell-code  code-fold=\"true\" code-summary=\"Show R Code\"}\n# Create a comparison table\ntbl1 <- tbl_regression(model1, exponentiate = TRUE) |>\n  bold_labels() |> bold_p(t = 0.05)\n\ntbl2 <- tbl_regression(model2, exponentiate = TRUE) |>\n  bold_labels() |> bold_p(t = 0.05)\n\ntbl_merge(\n  tbls = list(tbl1, tbl2),\n  tab_spanner = c(\"**Model 1: Sex**\", \"**Model 2: Age**\")\n)\n```\n\n::: {.cell-output-display}\n\n```{=html}\n<div id=\"brbgykgcyf\" style=\"padding-left:0px;padding-right:0px;padding-top:10px;padding-bottom:10px;overflow-x:auto;overflow-y:auto;width:auto;height:auto;\">\n<style>#brbgykgcyf table {\n  font-family: system-ui, 'Segoe UI', Roboto, Helvetica, Arial, sans-serif, 'Apple Color Emoji', 'Segoe UI Emoji', 'Segoe UI Symbol', 'Noto Color Emoji';\n  -webkit-font-smoothing: antialiased;\n  -moz-osx-font-smoothing: grayscale;\n}\n\n#brbgykgcyf thead, #brbgykgcyf tbody, #brbgykgcyf tfoot, #brbgykgcyf tr, #brbgykgcyf td, #brbgykgcyf th {\n  border-style: none;\n}\n\n#brbgykgcyf p {\n  margin: 0;\n  padding: 0;\n}\n\n#brbgykgcyf .gt_table {\n  display: table;\n  border-collapse: collapse;\n  line-height: normal;\n  margin-left: auto;\n  margin-right: auto;\n  color: #333333;\n  font-size: 16px;\n  font-weight: normal;\n  font-style: normal;\n  background-color: #FFFFFF;\n  width: auto;\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #A8A8A8;\n  border-right-style: none;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #A8A8A8;\n  border-left-style: none;\n  border-left-width: 2px;\n  border-left-color: #D3D3D3;\n}\n\n#brbgykgcyf .gt_caption {\n  padding-top: 4px;\n  padding-bottom: 4px;\n}\n\n#brbgykgcyf .gt_title {\n  color: #333333;\n  font-size: 125%;\n  font-weight: initial;\n  padding-top: 4px;\n  padding-bottom: 4px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-bottom-color: #FFFFFF;\n  border-bottom-width: 0;\n}\n\n#brbgykgcyf .gt_subtitle {\n  color: #333333;\n  font-size: 85%;\n  font-weight: initial;\n  padding-top: 3px;\n  padding-bottom: 5px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-top-color: #FFFFFF;\n  border-top-width: 0;\n}\n\n#brbgykgcyf .gt_heading {\n  background-color: #FFFFFF;\n  text-align: center;\n  border-bottom-color: #FFFFFF;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n}\n\n#brbgykgcyf .gt_bottom_border {\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n}\n\n#brbgykgcyf .gt_col_headings {\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n}\n\n#brbgykgcyf .gt_col_heading {\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: normal;\n  text-transform: inherit;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n  vertical-align: bottom;\n  padding-top: 5px;\n  padding-bottom: 6px;\n  padding-left: 5px;\n  padding-right: 5px;\n  overflow-x: hidden;\n}\n\n#brbgykgcyf .gt_column_spanner_outer {\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: normal;\n  text-transform: inherit;\n  padding-top: 0;\n  padding-bottom: 0;\n  padding-left: 4px;\n  padding-right: 4px;\n}\n\n#brbgykgcyf .gt_column_spanner_outer:first-child {\n  padding-left: 0;\n}\n\n#brbgykgcyf .gt_column_spanner_outer:last-child {\n  padding-right: 0;\n}\n\n#brbgykgcyf .gt_column_spanner {\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  vertical-align: bottom;\n  padding-top: 5px;\n  padding-bottom: 5px;\n  overflow-x: hidden;\n  display: inline-block;\n  width: 100%;\n}\n\n#brbgykgcyf .gt_spanner_row {\n  border-bottom-style: hidden;\n}\n\n#brbgykgcyf .gt_group_heading {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: initial;\n  text-transform: inherit;\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n  vertical-align: middle;\n  text-align: left;\n}\n\n#brbgykgcyf .gt_empty_group_heading {\n  padding: 0.5px;\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: initial;\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  vertical-align: middle;\n}\n\n#brbgykgcyf .gt_from_md > :first-child {\n  margin-top: 0;\n}\n\n#brbgykgcyf .gt_from_md > :last-child {\n  margin-bottom: 0;\n}\n\n#brbgykgcyf .gt_row {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  margin: 10px;\n  border-top-style: solid;\n  border-top-width: 1px;\n  border-top-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n  vertical-align: middle;\n  overflow-x: hidden;\n}\n\n#brbgykgcyf .gt_stub {\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: initial;\n  text-transform: inherit;\n  border-right-style: solid;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#brbgykgcyf .gt_stub_row_group {\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: initial;\n  text-transform: inherit;\n  border-right-style: solid;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n  padding-left: 5px;\n  padding-right: 5px;\n  vertical-align: top;\n}\n\n#brbgykgcyf .gt_row_group_first td {\n  border-top-width: 2px;\n}\n\n#brbgykgcyf .gt_row_group_first th {\n  border-top-width: 2px;\n}\n\n#brbgykgcyf .gt_summary_row {\n  color: #333333;\n  background-color: #FFFFFF;\n  text-transform: inherit;\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#brbgykgcyf .gt_first_summary_row {\n  border-top-style: solid;\n  border-top-color: #D3D3D3;\n}\n\n#brbgykgcyf .gt_first_summary_row.thick {\n  border-top-width: 2px;\n}\n\n#brbgykgcyf .gt_last_summary_row {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n}\n\n#brbgykgcyf .gt_grand_summary_row {\n  color: #333333;\n  background-color: #FFFFFF;\n  text-transform: inherit;\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#brbgykgcyf .gt_first_grand_summary_row {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-top-style: double;\n  border-top-width: 6px;\n  border-top-color: #D3D3D3;\n}\n\n#brbgykgcyf .gt_last_grand_summary_row_top {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-bottom-style: double;\n  border-bottom-width: 6px;\n  border-bottom-color: #D3D3D3;\n}\n\n#brbgykgcyf .gt_striped {\n  background-color: rgba(128, 128, 128, 0.05);\n}\n\n#brbgykgcyf .gt_table_body {\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n}\n\n#brbgykgcyf .gt_footnotes {\n  color: #333333;\n  background-color: #FFFFFF;\n  border-bottom-style: none;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 2px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n}\n\n#brbgykgcyf .gt_footnote {\n  margin: 0px;\n  font-size: 90%;\n  padding-top: 4px;\n  padding-bottom: 4px;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#brbgykgcyf .gt_sourcenotes {\n  color: #333333;\n  background-color: #FFFFFF;\n  border-bottom-style: none;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 2px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n}\n\n#brbgykgcyf .gt_sourcenote {\n  font-size: 90%;\n  padding-top: 4px;\n  padding-bottom: 4px;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#brbgykgcyf .gt_left {\n  text-align: left;\n}\n\n#brbgykgcyf .gt_center {\n  text-align: center;\n}\n\n#brbgykgcyf .gt_right {\n  text-align: right;\n  font-variant-numeric: tabular-nums;\n}\n\n#brbgykgcyf .gt_font_normal {\n  font-weight: normal;\n}\n\n#brbgykgcyf .gt_font_bold {\n  font-weight: bold;\n}\n\n#brbgykgcyf .gt_font_italic {\n  font-style: italic;\n}\n\n#brbgykgcyf .gt_super {\n  font-size: 65%;\n}\n\n#brbgykgcyf .gt_footnote_marks {\n  font-size: 75%;\n  vertical-align: 0.4em;\n  position: initial;\n}\n\n#brbgykgcyf .gt_asterisk {\n  font-size: 100%;\n  vertical-align: 0;\n}\n\n#brbgykgcyf .gt_indent_1 {\n  text-indent: 5px;\n}\n\n#brbgykgcyf .gt_indent_2 {\n  text-indent: 10px;\n}\n\n#brbgykgcyf .gt_indent_3 {\n  text-indent: 15px;\n}\n\n#brbgykgcyf .gt_indent_4 {\n  text-indent: 20px;\n}\n\n#brbgykgcyf .gt_indent_5 {\n  text-indent: 25px;\n}\n\n#brbgykgcyf .katex-display {\n  display: inline-flex !important;\n  margin-bottom: 0.75em !important;\n}\n\n#brbgykgcyf div.Reactable > div.rt-table > div.rt-thead > div.rt-tr.rt-tr-group-header > div.rt-th-group:after {\n  height: 0px !important;\n}\n</style>\n<table class=\"gt_table\" data-quarto-disable-processing=\"false\" data-quarto-bootstrap=\"false\">\n  <thead>\n    <tr class=\"gt_col_headings gt_spanner_row\">\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_left\" rowspan=\"2\" colspan=\"1\" scope=\"col\" id=\"label\"><span data-qmd-base64=\"KipDaGFyYWN0ZXJpc3RpYyoq\"><span class='gt_from_md'><strong>Characteristic</strong></span></span></th>\n      <th class=\"gt_center gt_columns_top_border gt_column_spanner_outer\" rowspan=\"1\" colspan=\"3\" scope=\"colgroup\" id=\"level 1; estimate_1\">\n        <div class=\"gt_column_spanner\"><span data-qmd-base64=\"KipNb2RlbCAxOiBTZXgqKg==\"><span class='gt_from_md'><strong>Model 1: Sex</strong></span></span></div>\n      </th>\n      <th class=\"gt_center gt_columns_top_border gt_column_spanner_outer\" rowspan=\"1\" colspan=\"3\" scope=\"colgroup\" id=\"level 1; estimate_2\">\n        <div class=\"gt_column_spanner\"><span data-qmd-base64=\"KipNb2RlbCAyOiBBZ2UqKg==\"><span class='gt_from_md'><strong>Model 2: Age</strong></span></span></div>\n      </th>\n    </tr>\n    <tr class=\"gt_col_headings\">\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_center\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"estimate_1\"><span data-qmd-base64=\"KipPUioq\"><span class='gt_from_md'><strong>OR</strong></span></span></th>\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_center\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"conf.low_1\"><span data-qmd-base64=\"Kio5NSUgQ0kqKg==\"><span class='gt_from_md'><strong>95% CI</strong></span></span></th>\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_center\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"p.value_1\"><span data-qmd-base64=\"KipwLXZhbHVlKio=\"><span class='gt_from_md'><strong>p-value</strong></span></span></th>\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_center\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"estimate_2\"><span data-qmd-base64=\"KipPUioq\"><span class='gt_from_md'><strong>OR</strong></span></span></th>\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_center\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"conf.low_2\"><span data-qmd-base64=\"Kio5NSUgQ0kqKg==\"><span class='gt_from_md'><strong>95% CI</strong></span></span></th>\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_center\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"p.value_2\"><span data-qmd-base64=\"KipwLXZhbHVlKio=\"><span class='gt_from_md'><strong>p-value</strong></span></span></th>\n    </tr>\n  </thead>\n  <tbody class=\"gt_table_body\">\n    <tr><td headers=\"label\" class=\"gt_row gt_left\" style=\"font-weight: bold;\">sex</td>\n<td headers=\"estimate_1\" class=\"gt_row gt_center\">11.3</td>\n<td headers=\"conf.low_1\" class=\"gt_row gt_center\">8.69, 14.8</td>\n<td headers=\"p.value_1\" class=\"gt_row gt_center\" style=\"font-weight: bold;\"><0.001</td>\n<td headers=\"estimate_2\" class=\"gt_row gt_center\"><br /></td>\n<td headers=\"conf.low_2\" class=\"gt_row gt_center\"><br /></td>\n<td headers=\"p.value_2\" class=\"gt_row gt_center\"><br /></td></tr>\n    <tr><td headers=\"label\" class=\"gt_row gt_left\" style=\"font-weight: bold;\">age in years</td>\n<td headers=\"estimate_1\" class=\"gt_row gt_center\"><br /></td>\n<td headers=\"conf.low_1\" class=\"gt_row gt_center\"><br /></td>\n<td headers=\"p.value_1\" class=\"gt_row gt_center\"><br /></td>\n<td headers=\"estimate_2\" class=\"gt_row gt_center\">0.99</td>\n<td headers=\"conf.low_2\" class=\"gt_row gt_center\">0.98, 1.00</td>\n<td headers=\"p.value_2\" class=\"gt_row gt_center\">0.073</td></tr>\n  </tbody>\n  <tfoot>\n    <tr class=\"gt_sourcenotes\">\n      <td class=\"gt_sourcenote\" colspan=\"7\"><span data-qmd-base64=\"QWJicmV2aWF0aW9uczogQ0kgPSBDb25maWRlbmNlIEludGVydmFsLCBPUiA9IE9kZHMgUmF0aW8=\"><span class='gt_from_md'>Abbreviations: CI = Confidence Interval, OR = Odds Ratio</span></span></td>\n    </tr>\n  </tfoot>\n</table>\n</div>\n```\n\n:::\n:::\n\n\n### Output Interpretation\n\n::: {.cell}\n\n```{.r .cell-code  code-fold=\"true\" code-summary=\"Show R Code\"}\n# Create a comparison table\ntbl1 <- tbl_regression(model1, exponentiate = TRUE) |>\n  bold_labels() |> bold_p(t = 0.05)\n\ntbl2 <- tbl_regression(model2, exponentiate = TRUE) |>\n  bold_labels() |> bold_p(t = 0.05)\n\ntbl_merge(\n  tbls = list(tbl1, tbl2),\n  tab_spanner = c(\"**Model 1: Sex**\", \"**Model 2: Age**\")\n)\n```\n\n::: {.cell-output-display}\n\n```{=html}\n<div id=\"yxcdcqhsxl\" style=\"padding-left:0px;padding-right:0px;padding-top:10px;padding-bottom:10px;overflow-x:auto;overflow-y:auto;width:auto;height:auto;\">\n<style>#yxcdcqhsxl table {\n  font-family: system-ui, 'Segoe UI', Roboto, Helvetica, Arial, sans-serif, 'Apple Color Emoji', 'Segoe UI Emoji', 'Segoe UI Symbol', 'Noto Color Emoji';\n  -webkit-font-smoothing: antialiased;\n  -moz-osx-font-smoothing: grayscale;\n}\n\n#yxcdcqhsxl thead, #yxcdcqhsxl tbody, #yxcdcqhsxl tfoot, #yxcdcqhsxl tr, #yxcdcqhsxl td, #yxcdcqhsxl th {\n  border-style: none;\n}\n\n#yxcdcqhsxl p {\n  margin: 0;\n  padding: 0;\n}\n\n#yxcdcqhsxl .gt_table {\n  display: table;\n  border-collapse: collapse;\n  line-height: normal;\n  margin-left: auto;\n  margin-right: auto;\n  color: #333333;\n  font-size: 16px;\n  font-weight: normal;\n  font-style: normal;\n  background-color: #FFFFFF;\n  width: auto;\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #A8A8A8;\n  border-right-style: none;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #A8A8A8;\n  border-left-style: none;\n  border-left-width: 2px;\n  border-left-color: #D3D3D3;\n}\n\n#yxcdcqhsxl .gt_caption {\n  padding-top: 4px;\n  padding-bottom: 4px;\n}\n\n#yxcdcqhsxl .gt_title {\n  color: #333333;\n  font-size: 125%;\n  font-weight: initial;\n  padding-top: 4px;\n  padding-bottom: 4px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-bottom-color: #FFFFFF;\n  border-bottom-width: 0;\n}\n\n#yxcdcqhsxl .gt_subtitle {\n  color: #333333;\n  font-size: 85%;\n  font-weight: initial;\n  padding-top: 3px;\n  padding-bottom: 5px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-top-color: #FFFFFF;\n  border-top-width: 0;\n}\n\n#yxcdcqhsxl .gt_heading {\n  background-color: #FFFFFF;\n  text-align: center;\n  border-bottom-color: #FFFFFF;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n}\n\n#yxcdcqhsxl .gt_bottom_border {\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n}\n\n#yxcdcqhsxl .gt_col_headings {\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n}\n\n#yxcdcqhsxl .gt_col_heading {\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: normal;\n  text-transform: inherit;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n  vertical-align: bottom;\n  padding-top: 5px;\n  padding-bottom: 6px;\n  padding-left: 5px;\n  padding-right: 5px;\n  overflow-x: hidden;\n}\n\n#yxcdcqhsxl .gt_column_spanner_outer {\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: normal;\n  text-transform: inherit;\n  padding-top: 0;\n  padding-bottom: 0;\n  padding-left: 4px;\n  padding-right: 4px;\n}\n\n#yxcdcqhsxl .gt_column_spanner_outer:first-child {\n  padding-left: 0;\n}\n\n#yxcdcqhsxl .gt_column_spanner_outer:last-child {\n  padding-right: 0;\n}\n\n#yxcdcqhsxl .gt_column_spanner {\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  vertical-align: bottom;\n  padding-top: 5px;\n  padding-bottom: 5px;\n  overflow-x: hidden;\n  display: inline-block;\n  width: 100%;\n}\n\n#yxcdcqhsxl .gt_spanner_row {\n  border-bottom-style: hidden;\n}\n\n#yxcdcqhsxl .gt_group_heading {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: initial;\n  text-transform: inherit;\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n  vertical-align: middle;\n  text-align: left;\n}\n\n#yxcdcqhsxl .gt_empty_group_heading {\n  padding: 0.5px;\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: initial;\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  vertical-align: middle;\n}\n\n#yxcdcqhsxl .gt_from_md > :first-child {\n  margin-top: 0;\n}\n\n#yxcdcqhsxl .gt_from_md > :last-child {\n  margin-bottom: 0;\n}\n\n#yxcdcqhsxl .gt_row {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  margin: 10px;\n  border-top-style: solid;\n  border-top-width: 1px;\n  border-top-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n  vertical-align: middle;\n  overflow-x: hidden;\n}\n\n#yxcdcqhsxl .gt_stub {\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: initial;\n  text-transform: inherit;\n  border-right-style: solid;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#yxcdcqhsxl .gt_stub_row_group {\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: initial;\n  text-transform: inherit;\n  border-right-style: solid;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n  padding-left: 5px;\n  padding-right: 5px;\n  vertical-align: top;\n}\n\n#yxcdcqhsxl .gt_row_group_first td {\n  border-top-width: 2px;\n}\n\n#yxcdcqhsxl .gt_row_group_first th {\n  border-top-width: 2px;\n}\n\n#yxcdcqhsxl .gt_summary_row {\n  color: #333333;\n  background-color: #FFFFFF;\n  text-transform: inherit;\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#yxcdcqhsxl .gt_first_summary_row {\n  border-top-style: solid;\n  border-top-color: #D3D3D3;\n}\n\n#yxcdcqhsxl .gt_first_summary_row.thick {\n  border-top-width: 2px;\n}\n\n#yxcdcqhsxl .gt_last_summary_row {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n}\n\n#yxcdcqhsxl .gt_grand_summary_row {\n  color: #333333;\n  background-color: #FFFFFF;\n  text-transform: inherit;\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#yxcdcqhsxl .gt_first_grand_summary_row {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-top-style: double;\n  border-top-width: 6px;\n  border-top-color: #D3D3D3;\n}\n\n#yxcdcqhsxl .gt_last_grand_summary_row_top {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-bottom-style: double;\n  border-bottom-width: 6px;\n  border-bottom-color: #D3D3D3;\n}\n\n#yxcdcqhsxl .gt_striped {\n  background-color: rgba(128, 128, 128, 0.05);\n}\n\n#yxcdcqhsxl .gt_table_body {\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n}\n\n#yxcdcqhsxl .gt_footnotes {\n  color: #333333;\n  background-color: #FFFFFF;\n  border-bottom-style: none;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 2px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n}\n\n#yxcdcqhsxl .gt_footnote {\n  margin: 0px;\n  font-size: 90%;\n  padding-top: 4px;\n  padding-bottom: 4px;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#yxcdcqhsxl .gt_sourcenotes {\n  color: #333333;\n  background-color: #FFFFFF;\n  border-bottom-style: none;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 2px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n}\n\n#yxcdcqhsxl .gt_sourcenote {\n  font-size: 90%;\n  padding-top: 4px;\n  padding-bottom: 4px;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#yxcdcqhsxl .gt_left {\n  text-align: left;\n}\n\n#yxcdcqhsxl .gt_center {\n  text-align: center;\n}\n\n#yxcdcqhsxl .gt_right {\n  text-align: right;\n  font-variant-numeric: tabular-nums;\n}\n\n#yxcdcqhsxl .gt_font_normal {\n  font-weight: normal;\n}\n\n#yxcdcqhsxl .gt_font_bold {\n  font-weight: bold;\n}\n\n#yxcdcqhsxl .gt_font_italic {\n  font-style: italic;\n}\n\n#yxcdcqhsxl .gt_super {\n  font-size: 65%;\n}\n\n#yxcdcqhsxl .gt_footnote_marks {\n  font-size: 75%;\n  vertical-align: 0.4em;\n  position: initial;\n}\n\n#yxcdcqhsxl .gt_asterisk {\n  font-size: 100%;\n  vertical-align: 0;\n}\n\n#yxcdcqhsxl .gt_indent_1 {\n  text-indent: 5px;\n}\n\n#yxcdcqhsxl .gt_indent_2 {\n  text-indent: 10px;\n}\n\n#yxcdcqhsxl .gt_indent_3 {\n  text-indent: 15px;\n}\n\n#yxcdcqhsxl .gt_indent_4 {\n  text-indent: 20px;\n}\n\n#yxcdcqhsxl .gt_indent_5 {\n  text-indent: 25px;\n}\n\n#yxcdcqhsxl .katex-display {\n  display: inline-flex !important;\n  margin-bottom: 0.75em !important;\n}\n\n#yxcdcqhsxl div.Reactable > div.rt-table > div.rt-thead > div.rt-tr.rt-tr-group-header > div.rt-th-group:after {\n  height: 0px !important;\n}\n</style>\n<table class=\"gt_table\" data-quarto-disable-processing=\"false\" data-quarto-bootstrap=\"false\">\n  <thead>\n    <tr class=\"gt_col_headings gt_spanner_row\">\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_left\" rowspan=\"2\" colspan=\"1\" scope=\"col\" id=\"label\"><span data-qmd-base64=\"KipDaGFyYWN0ZXJpc3RpYyoq\"><span class='gt_from_md'><strong>Characteristic</strong></span></span></th>\n      <th class=\"gt_center gt_columns_top_border gt_column_spanner_outer\" rowspan=\"1\" colspan=\"3\" scope=\"colgroup\" id=\"level 1; estimate_1\">\n        <div class=\"gt_column_spanner\"><span data-qmd-base64=\"KipNb2RlbCAxOiBTZXgqKg==\"><span class='gt_from_md'><strong>Model 1: Sex</strong></span></span></div>\n      </th>\n      <th class=\"gt_center gt_columns_top_border gt_column_spanner_outer\" rowspan=\"1\" colspan=\"3\" scope=\"colgroup\" id=\"level 1; estimate_2\">\n        <div class=\"gt_column_spanner\"><span data-qmd-base64=\"KipNb2RlbCAyOiBBZ2UqKg==\"><span class='gt_from_md'><strong>Model 2: Age</strong></span></span></div>\n      </th>\n    </tr>\n    <tr class=\"gt_col_headings\">\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_center\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"estimate_1\"><span data-qmd-base64=\"KipPUioq\"><span class='gt_from_md'><strong>OR</strong></span></span></th>\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_center\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"conf.low_1\"><span data-qmd-base64=\"Kio5NSUgQ0kqKg==\"><span class='gt_from_md'><strong>95% CI</strong></span></span></th>\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_center\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"p.value_1\"><span data-qmd-base64=\"KipwLXZhbHVlKio=\"><span class='gt_from_md'><strong>p-value</strong></span></span></th>\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_center\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"estimate_2\"><span data-qmd-base64=\"KipPUioq\"><span class='gt_from_md'><strong>OR</strong></span></span></th>\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_center\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"conf.low_2\"><span data-qmd-base64=\"Kio5NSUgQ0kqKg==\"><span class='gt_from_md'><strong>95% CI</strong></span></span></th>\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_center\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"p.value_2\"><span data-qmd-base64=\"KipwLXZhbHVlKio=\"><span class='gt_from_md'><strong>p-value</strong></span></span></th>\n    </tr>\n  </thead>\n  <tbody class=\"gt_table_body\">\n    <tr><td headers=\"label\" class=\"gt_row gt_left\" style=\"font-weight: bold;\">sex</td>\n<td headers=\"estimate_1\" class=\"gt_row gt_center\">11.3</td>\n<td headers=\"conf.low_1\" class=\"gt_row gt_center\">8.69, 14.8</td>\n<td headers=\"p.value_1\" class=\"gt_row gt_center\" style=\"font-weight: bold;\"><0.001</td>\n<td headers=\"estimate_2\" class=\"gt_row gt_center\"><br /></td>\n<td headers=\"conf.low_2\" class=\"gt_row gt_center\"><br /></td>\n<td headers=\"p.value_2\" class=\"gt_row gt_center\"><br /></td></tr>\n    <tr><td headers=\"label\" class=\"gt_row gt_left\" style=\"font-weight: bold;\">age in years</td>\n<td headers=\"estimate_1\" class=\"gt_row gt_center\"><br /></td>\n<td headers=\"conf.low_1\" class=\"gt_row gt_center\"><br /></td>\n<td headers=\"p.value_1\" class=\"gt_row gt_center\"><br /></td>\n<td headers=\"estimate_2\" class=\"gt_row gt_center\">0.99</td>\n<td headers=\"conf.low_2\" class=\"gt_row gt_center\">0.98, 1.00</td>\n<td headers=\"p.value_2\" class=\"gt_row gt_center\">0.073</td></tr>\n  </tbody>\n  <tfoot>\n    <tr class=\"gt_sourcenotes\">\n      <td class=\"gt_sourcenote\" colspan=\"7\"><span data-qmd-base64=\"QWJicmV2aWF0aW9uczogQ0kgPSBDb25maWRlbmNlIEludGVydmFsLCBPUiA9IE9kZHMgUmF0aW8=\"><span class='gt_from_md'>Abbreviations: CI = Confidence Interval, OR = Odds Ratio</span></span></td>\n    </tr>\n  </tfoot>\n</table>\n</div>\n```\n\n:::\n:::\n\nThe comparison shows:\n\n- **Sex** is a very strong predictor with a large odds ratio and highly significant $p$-value\n- **Age** has a much smaller effect, with an odds ratio close to 1 (meaning each year of age makes only a small difference to the odds of survival)\n- Both models use the same estimation method (MLE) and the same link function (logit)\n\n### Code Explanation\n\n::: {.cell}\n\n```{.r .cell-code}\n# Create a comparison table\ntbl1 <- tbl_regression(model1, exponentiate = TRUE) |>\n  bold_labels() |> bold_p(t = 0.05)\n\ntbl2 <- tbl_regression(model2, exponentiate = TRUE) |>\n  bold_labels() |> bold_p(t = 0.05)\n\ntbl_merge(\n  tbls = list(tbl1, tbl2),\n  tab_spanner = c(\"**Model 1: Sex**\", \"**Model 2: Age**\")\n)\n```\n:::\n\n- `tbl_regression(exponentiate = TRUE)` creates a publication-quality regression table with odds ratios\n- `tbl_merge()` places both models side by side for easy comparison\n- The table shows odds ratios, 95% confidence intervals, and $p$-values\n\n\n:::\n\n\n## Summary and Key Takeaways {#sec-ch9-summary}\n\nThis chapter marked a fundamental transition from continuous outcomes (Chapters 1--8) to binary outcomes. Logistic regression shares the linear structure of all the models we have studied, but it operates on a different scale and requires a different estimation method. The key ideas are:\n\n::: {.callout-important}\n## Key Takeaways\n\n1. **Binary outcomes require special treatment.** The linear probability model can produce impossible predictions (probabilities outside [0, 1]) and violates key OLS assumptions. The logistic function solves this by mapping any real number to a valid probability.\n\n2. **Three scales, one model.** The logistic regression model can be expressed equivalently on the probability, odds, or log-odds (logit) scale. The logit scale is where the model is linear: $\\text{logit}(\\pi_i) = \\alpha + \\beta x_i$.\n\n3. **Estimation uses maximum likelihood**, not OLS. MLE finds the parameters that make the observed data most probable. In large samples, it produces $z$-tests rather than $t$-tests, but the logic of hypothesis testing is the same.\n\n4. **Coefficients are on the log-odds scale** by default. For a dummy predictor, $\\beta$ is the difference in log-odds between groups. For a continuous predictor, $\\beta$ is the change in log-odds per one-unit increase.\n\n5. **Exponentiated coefficients are odds ratios.** $e^{\\beta}$ gives the multiplicative change in odds for a one-unit increase in $x$. For a dummy predictor, $e^{\\beta}$ is the ratio of odds between the two groups.\n\n6. **Odds ratios are NOT probability ratios.** The OR equals the relative risk only when the outcome is rare ($\\pi < 0.10$ in both groups). For common outcomes, the OR overstates the relative risk. Always be precise about which measure you are reporting.\n\n7. **Marginal effects translate to the probability scale.** The `avg_slopes()` function from `marginaleffects` computes the average change in probability for a one-unit change in $x$, which is often the most intuitive summary of the effect.\n\n8. **The logistic model is a generalized linear model (GLM).** It uses the same linear predictor $\\alpha + \\beta x$ as OLS regression but applies a logit **link function** to connect it to the binary outcome. This framework extends naturally to multiple predictors (@sec-ch10), model diagnostics (@sec-ch11), and other outcome types (@sec-ch12, @sec-ch13).\n:::\n\n\n## Exercises {#sec-ch9-exercises}\n\n::: {.callout-caution collapse=\"true\"}\n## Exercise 9.1: Disciplinary Referrals by Sex\nUsing the `disc` dataset from the `regdatasets` package, fit a logistic regression model predicting `sentoff` (whether a student was sent to the office: 1 = yes, 0 = no) from `male` (1 = male, 0 = female).\n\na. Compute the proportion of students sent to the office separately for males and females.\nb. Fit the logistic regression model using `glm()` and verify that the intercept equals the log-odds of the event for females (the reference group).\nc. Compute and interpret the odds ratio for `male`. Are males more or less likely to be sent to the office?\nd. Compute the average marginal effect of `male` on the probability of being sent to the office.\n:::\n\n::: {.callout-tip collapse=\"true\"}\n## Hint for Exercise 9.1\n- `data(disc)` loads the dataset. Use `glm(sentoff ~ male, family = binomial, data = disc)`.\n- For part (a): `disc |> group_by(male) |> summarise(prop = mean(sentoff))`\n- For part (b): The intercept should equal `log(prop_female / (1 - prop_female))`\n- For part (c): Use `model_parameters(model, exponentiate = TRUE)`\n- For part (d): Use `avg_slopes(model, type = \"response\")`\n:::\n\n::: {.callout-caution collapse=\"true\"}\n## Exercise 9.2: Titanic Survival by Ticket Class\nUsing the `titanic` dataset, create a binary variable `first_class` (1 if `pclass == 1`, 0 otherwise) and fit a logistic regression predicting `survived` from `first_class`.\n\na. What is the odds ratio for first-class passengers compared to other passengers?\nb. What is the predicted probability of survival for first-class vs non-first-class passengers?\nc. Is the odds ratio a good approximation of the probability ratio in this case? Why or why not?\n:::\n\n::: {.callout-tip collapse=\"true\"}\n## Hint for Exercise 9.2\n- `mutate(first_class = ifelse(pclass == 1, 1, 0))` creates the dummy variable\n- For part (b): Use `predictions(model, newdata = datagrid(first_class = c(0, 1)), type = \"response\")`\n- For part (c): Compute both the OR and the probability ratio ($P_1 / P_0$). The survival rate is far from rare (38% overall), so the OR will **overstate** the probability ratio. Refer to @sec-ch9-odds-ratios for the rare disease assumption.\n:::\n\n::: {.callout-caution collapse=\"true\"}\n## Exercise 9.3: Continuous Predictor --- Fare\nFit a logistic regression predicting Titanic survival from `fare` (ticket price in British pounds).\n\na. Interpret the odds ratio for `fare`. What does a one-pound increase in fare do to the odds of survival?\nb. What about a 10-pound increase? (Hint: use $e^{10\\beta}$.)\nc. Plot the predicted probability of survival as a function of fare using `plot_predictions()`.\nd. Compute the average marginal effect. On average, how much does each additional pound of fare change the survival probability?\n:::\n\n::: {.callout-tip collapse=\"true\"}\n## Hint for Exercise 9.3\n- The fare variable has a wide range. Consider whether the one-unit odds ratio is practically meaningful, or whether a larger unit (e.g., 10 pounds) gives a more useful interpretation.\n- For part (b): `exp(10 * coef(model)[\"fare\"])`\n- For part (c): `plot_predictions(model, condition = \"fare\", type = \"response\")`\n- For part (d): `avg_slopes(model, type = \"response\")`. The AME gives the average change in probability per one-pound increase. Multiply by 10 for a per-10-pound interpretation.\n:::\n\n::: {.callout-caution collapse=\"true\"}\n## Exercise 9.4: Probability, Odds, and Log-Odds Conversions\nA study reports that 30% of students in a program dropped out before completion.\n\na. Convert this probability to odds and log-odds.\nb. If the odds ratio for male students vs female students is 1.8, what are the odds of dropping out for males? (Assume the 30% is for females.)\nc. Convert the male odds back to a probability. Is the probability ratio equal to 1.8?\nd. Under what conditions would the odds ratio closely approximate the probability ratio?\n:::\n\n::: {.callout-tip collapse=\"true\"}\n## Hint for Exercise 9.4\n- For part (a): Odds $= 0.30 / 0.70$, log-odds $= \\log(0.30/0.70)$. In R: `qlogis(0.30)`\n- For part (b): Male odds $= \\text{female odds} \\times \\text{OR} = (0.30/0.70) \\times 1.8$\n- For part (c): Convert using $\\pi = \\text{odds}/(1 + \\text{odds})$. In R: `plogis(log(male_odds))`. Compare the probability ratio $\\pi_{\\text{male}} / \\pi_{\\text{female}}$ to the OR of 1.8.\n- For part (d): The OR approximates the probability ratio when $\\pi < 0.10$ in both groups (the rare event assumption). Here the baseline is 30%, so the approximation is poor.\n:::\n\n::: {.callout-caution collapse=\"true\"}\n## Exercise 9.5: Visualizing LPM vs Logistic Regression\nUsing the `titanic` dataset, create a side-by-side plot comparing the linear probability model and logistic regression for predicting `survived` from `fare`.\n\na. Fit both models: `lm(survived ~ fare)` and `glm(survived ~ fare, family = binomial)`.\nb. Create a plot with two panels: one showing the LPM line and one showing the logistic curve, both overlaid on the jittered data points.\nc. At what fare values does the LPM produce impossible predictions (below 0 or above 1)?\nd. In a short paragraph, explain why the logistic model is preferred even though the LPM line might \"look fine\" over most of the fare range.\n:::\n\n::: {.callout-tip collapse=\"true\"}\n## Hint for Exercise 9.5\n- Use `patchwork` to combine two ggplot panels\n- For the LPM panel: `geom_smooth(method = \"lm\", formula = y ~ x)`\n- For the logistic panel: `geom_smooth(method = \"glm\", formula = y ~ x, method.args = list(family = binomial))`\n- For part (c): Use `predict(lpm_model)` and check `range()`. Also try `predict(lpm_model, newdata = tibble(fare = c(0, 300, 500)))`.\n:::\n\n::: {.callout-caution collapse=\"true\"}\n## Exercise 9.6: Interpreting a Published Odds Ratio\nA published study reports: \"Students who participated in tutoring had 2.5 times higher odds of passing the exam (OR = 2.50, 95% CI: 1.40--4.46, p = 0.002). The overall pass rate was 65%.\"\n\na. Is it correct to say \"students who participated in tutoring were 2.5 times more likely to pass\"? Why or why not?\nb. If the pass rate for non-tutored students was 55%, use the OR of 2.5 to compute the odds and probability of passing for tutored students.\nc. What is the actual probability ratio? How does it compare to 2.5?\nd. If the overall pass rate had been 5% instead of 65%, would the OR be a better approximation of the probability ratio? Demonstrate with a calculation.\n:::\n\n::: {.callout-tip collapse=\"true\"}\n## Hint for Exercise 9.6\n- For part (a): \"2.5 times more likely\" implies a probability ratio of 2.5, but the OR is 2.5. These are only approximately equal when the event is rare.\n- For part (b): Odds for non-tutored $= 0.55/0.45$. Odds for tutored $= (0.55/0.45) \\times 2.5$. Convert back: $\\pi = \\text{odds}/(1+\\text{odds})$.\n- For part (d): Try $\\pi_0 = 0.03$ (so overall $\\approx 5\\%$). Compute tutored probability using the same OR of 2.5 and compare OR to the probability ratio.\n:::\n\n::: {.callout-caution collapse=\"true\"}\n## Exercise 9.7: Why Not Use a Linear Probability Model?\nSuppose you fit a linear probability model (LPM) predicting college admission (1 = admitted, 0 = rejected) from SAT score. The estimated equation is $\\hat{P}(\\text{admitted}) = -0.60 + 0.0012 \\times \\text{SAT}$.\n\na. For a student with SAT = 1400, what is the predicted probability of admission? What about SAT = 1550? Are both predictions sensible?\nb. At what SAT score does the LPM predict a probability greater than 1? Why is this a fundamental problem rather than merely an inconvenience?\nc. The logistic model constrains predicted probabilities to (0, 1) by design. Explain conceptually why the S-shaped logistic curve is a more natural model for a binary outcome than a straight line.\n:::\n\n::: {.callout-tip collapse=\"true\"}\n## Hint for Exercise 9.7\nFor part (a), plug in the values: $-0.60 + 0.0012 \\times 1400$, etc. For part (b), set $-0.60 + 0.0012 \\times \\text{SAT} = 1$ and solve. The deeper issue is that probabilities are bounded but linear functions are not. For part (c), think about how the rate of change in probability should slow down as you approach 0 or 1---a phenomenon called the \"ceiling/floor effect.\"\n:::\n\n::: {.callout-caution collapse=\"true\"}\n## Exercise 9.8: When Does the Odds Ratio Approximate the Risk Ratio?\nConsider two scenarios: (A) a disease with baseline prevalence of 2%, where exposure doubles the odds, and (B) a condition with baseline prevalence of 40%, where exposure also doubles the odds.\n\na. For each scenario, compute the probability of the outcome for the exposed group using the given odds ratio of 2.\nb. Compute the probability ratio (risk ratio) for each scenario. In which scenario is the OR a good approximation of the risk ratio?\nc. Explain in your own words why the \"rare disease assumption\" matters when interpreting odds ratios as though they were risk ratios. What threshold of baseline prevalence would you use as a rough guideline?\n:::\n\n::: {.callout-tip collapse=\"true\"}\n## Hint for Exercise 9.8\nFor scenario A: baseline odds $= 0.02/0.98$. Multiply by 2 to get exposed odds, then convert back to probability. For scenario B: baseline odds $= 0.40/0.60$. The OR approximates the RR well when the outcome is rare (typically below 10%) because $\\text{odds} = \\pi/(1-\\pi) \\approx \\pi$ when $\\pi$ is small.\n:::\n\n::: {.callout-caution collapse=\"true\"}\n## Exercise 9.9: Interpreting the Intercept in Logistic Regression\nA logistic regression predicting whether a customer will churn (1 = yes) from monthly bill amount yields $\\hat{\\beta}_0 = -2.3$ and $\\hat{\\beta}_1 = 0.015$.\n\na. What is the predicted probability of churn for a customer with a bill of \\$0? Is this interpretation practically meaningful?\nb. The intercept on the log-odds scale is $-2.3$. Convert this to an odds and then to a probability. What does this baseline probability represent?\nc. Compare this to interpreting the intercept in ordinary linear regression. Why is the intercept in logistic regression often less directly interpretable, and when might centering the predictor help?\n:::\n\n::: {.callout-tip collapse=\"true\"}\n## Hint for Exercise 9.9\nFor part (a), plug $x = 0$ into the logistic function: $\\hat{\\pi} = e^{-2.3}/(1 + e^{-2.3})$. A monthly bill of \\$0 is usually outside the range of observed data, so extrapolation is a concern. For part (c), if you center the predictor at its mean (e.g., \\$80), the intercept becomes the log-odds of churn for an \"average\" customer, which is far more interpretable.\n:::\n",
    "supporting": [
      "09-simple-logistic-regression_files"
    ],
    "filters": [
      "rmarkdown/pagebreak.lua"
    ],
    "includes": {},
    "engineDependencies": {},
    "preserve": {},
    "postProcess": true
  }
}