{
  "hash": "a52e1604c1fa14aac763b878288bb93b",
  "result": {
    "engine": "knitr",
    "markdown": "---\ntitle: \"Lab 9: Introduction to Logistic Regression\"\n---\n\n\n\n\n## Goals\n\n::: {.callout-note}\n## What You'll Learn in This Lab\n- Understand why we need logistic regression for binary outcomes\n- Compute probabilities, odds, and odds ratios from a cross-tabulation\n- Fit a logistic regression using `glm()` with `family = binomial`\n- Interpret coefficients on the log-odds, odds, and probability scales\n- Fit logistic regression with a continuous predictor\n- **Lecture Notes Reference:** Chapter 9: *Introduction to Logistic Regression*\n:::\n\n::: {.callout-tip}\n## Stata → R Translation\n| Stata | R | Notes |\n|:------|:--|:------|\n| `logit survived female` | `glm(survived ~ female, family = binomial)` | Log-odds coefficients |\n| `logit survived female, or` | `exp(coef(model))` | Odds ratios |\n| `logistic survived female` | `tbl_regression(exponentiate = TRUE)` | OR with pretty table |\n| `cs survived female, or` | Manual calculation | Cohort study odds ratio |\n:::\n\n**Dataset:** `titanic` from the `regdatasets` package\n\n## Setup\n\n\n::: {.cell}\n\n```{.r .cell-code}\nlibrary(regdatasets)\ndata(titanic)\nglimpse(titanic)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nRows: 1,309\nColumns: 6\n$ pclass   <int> 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1…\n$ survived <int> 1, 1, 0, 0, 0, 1, 1, 0, 1, 0, 0, 1, 1, 1, 1, 0, 0, 1, 1, 0, 1…\n$ age      <dbl> 29.0000, 0.9167, 2.0000, 30.0000, 25.0000, 48.0000, 63.0000, …\n$ fare     <dbl> 211.3375, 151.5500, 151.5500, 151.5500, 151.5500, 26.5500, 77…\n$ embarked <chr> \"S\", \"S\", \"S\", \"S\", \"S\", \"S\", \"S\", \"S\", \"C\", \"C\", \"C\", \"C\", \"…\n$ sex      <int> 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 0, 1, 1, 1, 0, 0, 0, 1, 1, 0, 0…\n```\n\n\n:::\n:::\n\n\n\n## Part 1: Meet the Titanic Data\n\nThe `titanic` dataset describes the survival status of individual passengers on the Titanic. Our goal today is to model **who survived** --- a binary outcome (0 = died, 1 = survived).\n\n### Step 1: Explore the Variables\n\n\n::: {.cell}\n\n```{.r .cell-code}\ntitanic |>\n  summarise(\n    n = n(),\n    survived_mean = mean(survived, na.rm = TRUE),\n    age_mean = mean(age, na.rm = TRUE),\n    fare_mean = mean(fare, na.rm = TRUE)\n  ) |>\n  mutate(across(where(is.numeric), \\(x) round(x, 2)))\n```\n\n::: {.cell-output-display}\n<div class=\"kable-table\">\n\n|    n| survived_mean| age_mean| fare_mean|\n|----:|-------------:|--------:|---------:|\n| 1309|          0.38|    29.88|      33.3|\n\n</div>\n:::\n:::\n\n\n> The variable `survived` is coded 0/1, so its mean gives us the overall survival rate. What proportion of passengers survived?\n\n### Step 2: Create the Female Dummy Variable\n\nThe `sex` variable is already coded as 0 (male) and 1 (female). We'll rename it to `female` for clarity.\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# The 'sex' variable is already coded as 0 = male, 1 = female\n# Rename it to 'female' for clarity\ntitanic <- titanic |>\n  rename(female = sex)\n```\n:::\n\n\nLet's verify the coding:\n\n\n::: {.cell}\n\n```{.r .cell-code}\ntitanic |>\n  count(female)\n```\n\n::: {.cell-output-display}\n<div class=\"kable-table\">\n\n| female|   n|\n|------:|---:|\n|      0| 843|\n|      1| 466|\n\n</div>\n:::\n:::\n\n\n> We created `female` so that 1 = female and 0 = male. This makes males the reference group, which will be important when we interpret logistic regression coefficients.\n\n### Step 3: Cross-Tabulation of Survival by Gender\n\nBefore fitting any model, let's look at the raw data. A cross-tabulation tells us everything we need.\n\n\n::: {.cell}\n\n```{.r .cell-code}\ntitanic |>\n  count(female, survived) |>\n  pivot_wider(names_from = survived, values_from = n, names_prefix = \"survived_\")\n```\n\n::: {.cell-output-display}\n<div class=\"kable-table\">\n\n| female| survived_0| survived_1|\n|------:|----------:|----------:|\n|      0|        682|        161|\n|      1|        127|        339|\n\n</div>\n:::\n:::\n\n\nNow let's add row percentages to see survival rates within each gender:\n\n\n::: {.cell}\n\n```{.r .cell-code}\ntitanic |>\n  group_by(female) |>\n  summarise(\n    n = n(),\n    n_survived = sum(survived),\n    prop_survived = mean(survived),\n    .groups = \"drop\"\n  ) |>\n  mutate(prop_survived = round(prop_survived, 4))\n```\n\n::: {.cell-output-display}\n<div class=\"kable-table\">\n\n| female|   n| n_survived| prop_survived|\n|------:|---:|----------:|-------------:|\n|      0| 843|        161|        0.1910|\n|      1| 466|        339|        0.7275|\n\n</div>\n:::\n:::\n\n\n> Compare the survival rates. Females had a much higher survival rate than males. This is the pattern we will model with logistic regression.\n\n\n## Part 2: Understanding Odds and Odds Ratios\n\nBefore jumping into logistic regression, let's build intuition about **probabilities**, **odds**, and **odds ratios**. These three quantities are all different ways of describing the same information, and converting between them is the key skill for this lab.\n\n### Step 1: Probabilities from the Cross-Tab\n\nLet's extract the survival probabilities we just computed:\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Store the survival proportions\nsurv_stats <- titanic |>\n  group_by(female) |>\n  summarise(prob_survived = mean(survived), .groups = \"drop\")\n\nprob_male   <- surv_stats$prob_survived[surv_stats$female == 0]\nprob_female <- surv_stats$prob_survived[surv_stats$female == 1]\n\ncat(\"P(survived | male)   =\", round(prob_male, 4), \"\\n\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nP(survived | male)   = 0.191 \n```\n\n\n:::\n\n```{.r .cell-code}\ncat(\"P(survived | female) =\", round(prob_female, 4), \"\\n\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nP(survived | female) = 0.7275 \n```\n\n\n:::\n:::\n\n\n### Step 2: From Probabilities to Odds\n\n**Odds** express the ratio of the probability of an event happening to the probability of it not happening:\n\n$$\\text{Odds} = \\frac{p}{1 - p}$$\n\n\n::: {.cell}\n\n```{.r .cell-code}\nodds_male   <- prob_male / (1 - prob_male)\nodds_female <- prob_female / (1 - prob_female)\n\ncat(\"Odds(survived | male)   =\", round(odds_male, 4), \"\\n\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nOdds(survived | male)   = 0.2361 \n```\n\n\n:::\n\n```{.r .cell-code}\ncat(\"Odds(survived | female) =\", round(odds_female, 4), \"\\n\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nOdds(survived | female) = 2.6693 \n```\n\n\n:::\n:::\n\n\n> An odds of 0.24 for males means that for every male who survived, roughly 4 died. An odds greater than 1 for females means more females survived than died.\n\n### Step 3: The Odds Ratio\n\nThe **odds ratio (OR)** compares the odds between two groups:\n\n$$\\text{OR} = \\frac{\\text{Odds(female)}}{\\text{Odds(male)}}$$\n\n\n::: {.cell}\n\n```{.r .cell-code}\nor_manual <- odds_female / odds_male\n\ncat(\"Odds Ratio (female vs. male) =\", round(or_manual, 4), \"\\n\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nOdds Ratio (female vs. male) = 11.3072 \n```\n\n\n:::\n:::\n\n\n> This tells us that the odds of survival for females were about 11.3 times the odds of survival for males. This is a huge difference --- and it is exactly what logistic regression will estimate for us.\n\n::: {.callout-tip}\n## The Three Scales\nKeep this conversion chain in mind --- you will use it throughout the rest of the course:\n\n**Log-odds** $\\xrightarrow{\\exp()}$ **Odds** $\\xrightarrow{p = \\text{odds}/(1+\\text{odds})}$ **Probability**\n\nGoing back: **Probability** $\\xrightarrow{p/(1-p)}$ **Odds** $\\xrightarrow{\\log()}$ **Log-odds**\n:::\n\n\n## Part 3: Your First Logistic Regression\n\nNow let's fit the same analysis as a logistic regression. We use `glm()` with `family = binomial` (which uses the logit link by default).\n\n### Step 1: Fit the Model\n\n\n::: {.cell}\n\n```{.r .cell-code}\nmodel_female <- glm(survived ~ female, data = titanic, family = binomial)\n```\n:::\n\n\n:::: {.panel-tabset}\n\n#### Simple\n\n\n::: {.cell}\n\n```{.r .cell-code}\nsummary(model_female)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\nCall:\nglm(formula = survived ~ female, family = binomial, data = titanic)\n\nCoefficients:\n            Estimate Std. Error z value Pr(>|z|)    \n(Intercept) -1.44363    0.08762  -16.48   <2e-16 ***\nfemale       2.42544    0.13602   17.83   <2e-16 ***\n---\nSignif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1\n\n(Dispersion parameter for binomial family taken to be 1)\n\n    Null deviance: 1741.0  on 1308  degrees of freedom\nResidual deviance: 1368.1  on 1307  degrees of freedom\nAIC: 1372.1\n\nNumber of Fisher Scoring iterations: 4\n```\n\n\n:::\n:::\n\n\n#### Advanced\n\n\n::: {.cell}\n\n```{.r .cell-code}\nmodel_female |>\n  tbl_regression(exponentiate = TRUE) |>\n  bold_labels() |>\n  bold_p(t = 0.05)\n```\n\n::: {.cell-output-display}\n\n```{=html}\n<div id=\"bsvnedsmad\" style=\"padding-left:0px;padding-right:0px;padding-top:10px;padding-bottom:10px;overflow-x:auto;overflow-y:auto;width:auto;height:auto;\">\n<style>#bsvnedsmad table {\n  font-family: system-ui, 'Segoe UI', Roboto, Helvetica, Arial, sans-serif, 'Apple Color Emoji', 'Segoe UI Emoji', 'Segoe UI Symbol', 'Noto Color Emoji';\n  -webkit-font-smoothing: antialiased;\n  -moz-osx-font-smoothing: grayscale;\n}\n\n#bsvnedsmad thead, #bsvnedsmad tbody, #bsvnedsmad tfoot, #bsvnedsmad tr, #bsvnedsmad td, #bsvnedsmad th {\n  border-style: none;\n}\n\n#bsvnedsmad p {\n  margin: 0;\n  padding: 0;\n}\n\n#bsvnedsmad .gt_table {\n  display: table;\n  border-collapse: collapse;\n  line-height: normal;\n  margin-left: auto;\n  margin-right: auto;\n  color: #333333;\n  font-size: 16px;\n  font-weight: normal;\n  font-style: normal;\n  background-color: #FFFFFF;\n  width: auto;\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #A8A8A8;\n  border-right-style: none;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #A8A8A8;\n  border-left-style: none;\n  border-left-width: 2px;\n  border-left-color: #D3D3D3;\n}\n\n#bsvnedsmad .gt_caption {\n  padding-top: 4px;\n  padding-bottom: 4px;\n}\n\n#bsvnedsmad .gt_title {\n  color: #333333;\n  font-size: 125%;\n  font-weight: initial;\n  padding-top: 4px;\n  padding-bottom: 4px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-bottom-color: #FFFFFF;\n  border-bottom-width: 0;\n}\n\n#bsvnedsmad .gt_subtitle {\n  color: #333333;\n  font-size: 85%;\n  font-weight: initial;\n  padding-top: 3px;\n  padding-bottom: 5px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-top-color: #FFFFFF;\n  border-top-width: 0;\n}\n\n#bsvnedsmad .gt_heading {\n  background-color: #FFFFFF;\n  text-align: center;\n  border-bottom-color: #FFFFFF;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n}\n\n#bsvnedsmad .gt_bottom_border {\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n}\n\n#bsvnedsmad .gt_col_headings {\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n}\n\n#bsvnedsmad .gt_col_heading {\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: normal;\n  text-transform: inherit;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n  vertical-align: bottom;\n  padding-top: 5px;\n  padding-bottom: 6px;\n  padding-left: 5px;\n  padding-right: 5px;\n  overflow-x: hidden;\n}\n\n#bsvnedsmad .gt_column_spanner_outer {\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: normal;\n  text-transform: inherit;\n  padding-top: 0;\n  padding-bottom: 0;\n  padding-left: 4px;\n  padding-right: 4px;\n}\n\n#bsvnedsmad .gt_column_spanner_outer:first-child {\n  padding-left: 0;\n}\n\n#bsvnedsmad .gt_column_spanner_outer:last-child {\n  padding-right: 0;\n}\n\n#bsvnedsmad .gt_column_spanner {\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  vertical-align: bottom;\n  padding-top: 5px;\n  padding-bottom: 5px;\n  overflow-x: hidden;\n  display: inline-block;\n  width: 100%;\n}\n\n#bsvnedsmad .gt_spanner_row {\n  border-bottom-style: hidden;\n}\n\n#bsvnedsmad .gt_group_heading {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: initial;\n  text-transform: inherit;\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n  vertical-align: middle;\n  text-align: left;\n}\n\n#bsvnedsmad .gt_empty_group_heading {\n  padding: 0.5px;\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: initial;\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  vertical-align: middle;\n}\n\n#bsvnedsmad .gt_from_md > :first-child {\n  margin-top: 0;\n}\n\n#bsvnedsmad .gt_from_md > :last-child {\n  margin-bottom: 0;\n}\n\n#bsvnedsmad .gt_row {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  margin: 10px;\n  border-top-style: solid;\n  border-top-width: 1px;\n  border-top-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n  vertical-align: middle;\n  overflow-x: hidden;\n}\n\n#bsvnedsmad .gt_stub {\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: initial;\n  text-transform: inherit;\n  border-right-style: solid;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#bsvnedsmad .gt_stub_row_group {\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: initial;\n  text-transform: inherit;\n  border-right-style: solid;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n  padding-left: 5px;\n  padding-right: 5px;\n  vertical-align: top;\n}\n\n#bsvnedsmad .gt_row_group_first td {\n  border-top-width: 2px;\n}\n\n#bsvnedsmad .gt_row_group_first th {\n  border-top-width: 2px;\n}\n\n#bsvnedsmad .gt_summary_row {\n  color: #333333;\n  background-color: #FFFFFF;\n  text-transform: inherit;\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#bsvnedsmad .gt_first_summary_row {\n  border-top-style: solid;\n  border-top-color: #D3D3D3;\n}\n\n#bsvnedsmad .gt_first_summary_row.thick {\n  border-top-width: 2px;\n}\n\n#bsvnedsmad .gt_last_summary_row {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n}\n\n#bsvnedsmad .gt_grand_summary_row {\n  color: #333333;\n  background-color: #FFFFFF;\n  text-transform: inherit;\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#bsvnedsmad .gt_first_grand_summary_row {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-top-style: double;\n  border-top-width: 6px;\n  border-top-color: #D3D3D3;\n}\n\n#bsvnedsmad .gt_last_grand_summary_row_top {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-bottom-style: double;\n  border-bottom-width: 6px;\n  border-bottom-color: #D3D3D3;\n}\n\n#bsvnedsmad .gt_striped {\n  background-color: rgba(128, 128, 128, 0.05);\n}\n\n#bsvnedsmad .gt_table_body {\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n}\n\n#bsvnedsmad .gt_footnotes {\n  color: #333333;\n  background-color: #FFFFFF;\n  border-bottom-style: none;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 2px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n}\n\n#bsvnedsmad .gt_footnote {\n  margin: 0px;\n  font-size: 90%;\n  padding-top: 4px;\n  padding-bottom: 4px;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#bsvnedsmad .gt_sourcenotes {\n  color: #333333;\n  background-color: #FFFFFF;\n  border-bottom-style: none;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 2px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n}\n\n#bsvnedsmad .gt_sourcenote {\n  font-size: 90%;\n  padding-top: 4px;\n  padding-bottom: 4px;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#bsvnedsmad .gt_left {\n  text-align: left;\n}\n\n#bsvnedsmad .gt_center {\n  text-align: center;\n}\n\n#bsvnedsmad .gt_right {\n  text-align: right;\n  font-variant-numeric: tabular-nums;\n}\n\n#bsvnedsmad .gt_font_normal {\n  font-weight: normal;\n}\n\n#bsvnedsmad .gt_font_bold {\n  font-weight: bold;\n}\n\n#bsvnedsmad .gt_font_italic {\n  font-style: italic;\n}\n\n#bsvnedsmad .gt_super {\n  font-size: 65%;\n}\n\n#bsvnedsmad .gt_footnote_marks {\n  font-size: 75%;\n  vertical-align: 0.4em;\n  position: initial;\n}\n\n#bsvnedsmad .gt_asterisk {\n  font-size: 100%;\n  vertical-align: 0;\n}\n\n#bsvnedsmad .gt_indent_1 {\n  text-indent: 5px;\n}\n\n#bsvnedsmad .gt_indent_2 {\n  text-indent: 10px;\n}\n\n#bsvnedsmad .gt_indent_3 {\n  text-indent: 15px;\n}\n\n#bsvnedsmad .gt_indent_4 {\n  text-indent: 20px;\n}\n\n#bsvnedsmad .gt_indent_5 {\n  text-indent: 25px;\n}\n\n#bsvnedsmad .katex-display {\n  display: inline-flex !important;\n  margin-bottom: 0.75em !important;\n}\n\n#bsvnedsmad div.Reactable > div.rt-table > div.rt-thead > div.rt-tr.rt-tr-group-header > div.rt-th-group:after {\n  height: 0px !important;\n}\n</style>\n<table class=\"gt_table\" data-quarto-disable-processing=\"false\" data-quarto-bootstrap=\"false\">\n  <thead>\n    <tr class=\"gt_col_headings\">\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_left\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"label\"><span data-qmd-base64=\"KipDaGFyYWN0ZXJpc3RpYyoq\"><span class='gt_from_md'><strong>Characteristic</strong></span></span></th>\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_center\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"estimate\"><span data-qmd-base64=\"KipPUioq\"><span class='gt_from_md'><strong>OR</strong></span></span></th>\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_center\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"conf.low\"><span data-qmd-base64=\"Kio5NSUgQ0kqKg==\"><span class='gt_from_md'><strong>95% CI</strong></span></span></th>\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_center\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"p.value\"><span data-qmd-base64=\"KipwLXZhbHVlKio=\"><span class='gt_from_md'><strong>p-value</strong></span></span></th>\n    </tr>\n  </thead>\n  <tbody class=\"gt_table_body\">\n    <tr><td headers=\"label\" class=\"gt_row gt_left\" style=\"font-weight: bold;\">female</td>\n<td headers=\"estimate\" class=\"gt_row gt_center\">11.3</td>\n<td headers=\"conf.low\" class=\"gt_row gt_center\">8.69, 14.8</td>\n<td headers=\"p.value\" class=\"gt_row gt_center\" style=\"font-weight: bold;\"><0.001</td></tr>\n  </tbody>\n  <tfoot class=\"gt_sourcenotes\">\n    <tr>\n      <td class=\"gt_sourcenote\" colspan=\"4\"><span data-qmd-base64=\"QWJicmV2aWF0aW9uczogQ0kgPSBDb25maWRlbmNlIEludGVydmFsLCBPUiA9IE9kZHMgUmF0aW8=\"><span class='gt_from_md'>Abbreviations: CI = Confidence Interval, OR = Odds Ratio</span></span></td>\n    </tr>\n  </tfoot>\n  \n</table>\n</div>\n```\n\n:::\n:::\n\n\n> The `exponentiate = TRUE` option displays odds ratios instead of log-odds coefficients. This is typically what we report in applied research.\n\n::::\n\n### Step 2: Interpret the Log-Odds Coefficients\n\nThe default output is on the **log-odds scale**:\n\n\n::: {.cell}\n\n```{.r .cell-code}\ncoef(model_female)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n(Intercept)      female \n  -1.443625    2.425438 \n```\n\n\n:::\n:::\n\n\n> - **Intercept** (-1.4436): This is the log-odds of survival for the reference group (males, when `female = 0`).\n> - **female** (2.4254): This is the difference in log-odds of survival between females and males.\n\nLog-odds are hard to interpret directly. Let's convert them.\n\n::: {.callout-warning}\n## R Reports Log-Odds, Not Odds Ratios\nR's `glm()` with `family = binomial` always reports coefficients on the **log-odds** scale. To get **odds ratios** (which is what Stata's `logistic` command reports by default), you need to exponentiate: `exp(coef(model))` or use `parameters::model_parameters(model, exponentiate = TRUE)`. Don't interpret log-odds coefficients as odds ratios!\n:::\n\n### Step 3: Transform to Odds\n\nApply `exp()` to convert from log-odds to odds:\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Odds of survival for males (reference group)\nodds_male_model <- exp(coef(model_female)[1])\n\n# Odds of survival for females\nodds_female_model <- exp(coef(model_female)[1] + coef(model_female)[2])\n\ncat(\"Estimated odds (male)   =\", round(odds_male_model, 4), \"\\n\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nEstimated odds (male)   = 0.2361 \n```\n\n\n:::\n\n```{.r .cell-code}\ncat(\"Estimated odds (female) =\", round(odds_female_model, 4), \"\\n\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nEstimated odds (female) = 2.6693 \n```\n\n\n:::\n:::\n\n\n> Compare these to the odds we calculated by hand in Part 2. They should match exactly!\n\n### Step 4: Get the Odds Ratio Directly\n\nThe odds ratio is simply `exp()` of the slope coefficient:\n\n\n::: {.cell}\n\n```{.r .cell-code}\nexp(coef(model_female))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n(Intercept)      female \n  0.2360704  11.3071844 \n```\n\n\n:::\n:::\n\n\n> The odds ratio for `female` is 11.31. This means the estimated odds of surviving for females are about 11.3 times the odds for males --- exactly what we calculated by hand.\n\n### Step 5: Transform to Probabilities\n\nFinally, let's convert to the probability scale using the inverse logit function:\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Predicted probability of survival for males\nprob_male_model <- plogis(coef(model_female)[1])\n\n# Predicted probability of survival for females\nprob_female_model <- plogis(coef(model_female)[1] + coef(model_female)[2])\n\ncat(\"P(survived | male)   =\", round(prob_male_model, 4), \"\\n\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nP(survived | male)   = 0.191 \n```\n\n\n:::\n\n```{.r .cell-code}\ncat(\"P(survived | female) =\", round(prob_female_model, 4), \"\\n\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nP(survived | female) = 0.7275 \n```\n\n\n:::\n:::\n\n\n> Again, these match our hand calculations from Part 2. With a single dummy predictor, logistic regression simply reproduces the group proportions from the cross-tabulation.\n\n::: {.callout-important}\n## Why Not Just Use Linear Regression?\nWith a binary outcome, linear regression (OLS) can predict probabilities below 0 or above 1, which makes no sense. Logistic regression constrains predicted probabilities to stay between 0 and 1 by modeling the **log-odds** as a linear function of the predictors.\n:::\n\n\n## Part 4: Logistic Regression with a Continuous Predictor\n\nThe real power of logistic regression emerges when we use continuous predictors. Let's model survival as a function of ticket fare.\n\n### Step 1: Fit the Model\n\n\n::: {.cell}\n\n```{.r .cell-code}\nmodel_fare <- glm(survived ~ fare, data = titanic, family = binomial)\n```\n:::\n\n\n:::: {.panel-tabset}\n\n#### Simple\n\n\n::: {.cell}\n\n```{.r .cell-code}\nsummary(model_fare)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\nCall:\nglm(formula = survived ~ fare, family = binomial, data = titanic)\n\nCoefficients:\n             Estimate Std. Error z value Pr(>|z|)    \n(Intercept) -0.882427   0.075522 -11.684  < 2e-16 ***\nfare         0.012453   0.001604   7.762 8.35e-15 ***\n---\nSignif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1\n\n(Dispersion parameter for binomial family taken to be 1)\n\n    Null deviance: 1740.1  on 1307  degrees of freedom\nResidual deviance: 1654.0  on 1306  degrees of freedom\n  (1 observation deleted due to missingness)\nAIC: 1658\n\nNumber of Fisher Scoring iterations: 4\n```\n\n\n:::\n:::\n\n\n#### Advanced\n\n\n::: {.cell}\n\n```{.r .cell-code}\nmodel_fare |>\n  tbl_regression(exponentiate = TRUE) |>\n  bold_labels() |>\n  bold_p(t = 0.05)\n```\n\n::: {.cell-output-display}\n\n```{=html}\n<div id=\"utlwkvxsyi\" style=\"padding-left:0px;padding-right:0px;padding-top:10px;padding-bottom:10px;overflow-x:auto;overflow-y:auto;width:auto;height:auto;\">\n<style>#utlwkvxsyi table {\n  font-family: system-ui, 'Segoe UI', Roboto, Helvetica, Arial, sans-serif, 'Apple Color Emoji', 'Segoe UI Emoji', 'Segoe UI Symbol', 'Noto Color Emoji';\n  -webkit-font-smoothing: antialiased;\n  -moz-osx-font-smoothing: grayscale;\n}\n\n#utlwkvxsyi thead, #utlwkvxsyi tbody, #utlwkvxsyi tfoot, #utlwkvxsyi tr, #utlwkvxsyi td, #utlwkvxsyi th {\n  border-style: none;\n}\n\n#utlwkvxsyi p {\n  margin: 0;\n  padding: 0;\n}\n\n#utlwkvxsyi .gt_table {\n  display: table;\n  border-collapse: collapse;\n  line-height: normal;\n  margin-left: auto;\n  margin-right: auto;\n  color: #333333;\n  font-size: 16px;\n  font-weight: normal;\n  font-style: normal;\n  background-color: #FFFFFF;\n  width: auto;\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #A8A8A8;\n  border-right-style: none;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #A8A8A8;\n  border-left-style: none;\n  border-left-width: 2px;\n  border-left-color: #D3D3D3;\n}\n\n#utlwkvxsyi .gt_caption {\n  padding-top: 4px;\n  padding-bottom: 4px;\n}\n\n#utlwkvxsyi .gt_title {\n  color: #333333;\n  font-size: 125%;\n  font-weight: initial;\n  padding-top: 4px;\n  padding-bottom: 4px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-bottom-color: #FFFFFF;\n  border-bottom-width: 0;\n}\n\n#utlwkvxsyi .gt_subtitle {\n  color: #333333;\n  font-size: 85%;\n  font-weight: initial;\n  padding-top: 3px;\n  padding-bottom: 5px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-top-color: #FFFFFF;\n  border-top-width: 0;\n}\n\n#utlwkvxsyi .gt_heading {\n  background-color: #FFFFFF;\n  text-align: center;\n  border-bottom-color: #FFFFFF;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n}\n\n#utlwkvxsyi .gt_bottom_border {\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n}\n\n#utlwkvxsyi .gt_col_headings {\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n}\n\n#utlwkvxsyi .gt_col_heading {\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: normal;\n  text-transform: inherit;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n  vertical-align: bottom;\n  padding-top: 5px;\n  padding-bottom: 6px;\n  padding-left: 5px;\n  padding-right: 5px;\n  overflow-x: hidden;\n}\n\n#utlwkvxsyi .gt_column_spanner_outer {\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: normal;\n  text-transform: inherit;\n  padding-top: 0;\n  padding-bottom: 0;\n  padding-left: 4px;\n  padding-right: 4px;\n}\n\n#utlwkvxsyi .gt_column_spanner_outer:first-child {\n  padding-left: 0;\n}\n\n#utlwkvxsyi .gt_column_spanner_outer:last-child {\n  padding-right: 0;\n}\n\n#utlwkvxsyi .gt_column_spanner {\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  vertical-align: bottom;\n  padding-top: 5px;\n  padding-bottom: 5px;\n  overflow-x: hidden;\n  display: inline-block;\n  width: 100%;\n}\n\n#utlwkvxsyi .gt_spanner_row {\n  border-bottom-style: hidden;\n}\n\n#utlwkvxsyi .gt_group_heading {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: initial;\n  text-transform: inherit;\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n  vertical-align: middle;\n  text-align: left;\n}\n\n#utlwkvxsyi .gt_empty_group_heading {\n  padding: 0.5px;\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: initial;\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  vertical-align: middle;\n}\n\n#utlwkvxsyi .gt_from_md > :first-child {\n  margin-top: 0;\n}\n\n#utlwkvxsyi .gt_from_md > :last-child {\n  margin-bottom: 0;\n}\n\n#utlwkvxsyi .gt_row {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  margin: 10px;\n  border-top-style: solid;\n  border-top-width: 1px;\n  border-top-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n  vertical-align: middle;\n  overflow-x: hidden;\n}\n\n#utlwkvxsyi .gt_stub {\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: initial;\n  text-transform: inherit;\n  border-right-style: solid;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#utlwkvxsyi .gt_stub_row_group {\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: initial;\n  text-transform: inherit;\n  border-right-style: solid;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n  padding-left: 5px;\n  padding-right: 5px;\n  vertical-align: top;\n}\n\n#utlwkvxsyi .gt_row_group_first td {\n  border-top-width: 2px;\n}\n\n#utlwkvxsyi .gt_row_group_first th {\n  border-top-width: 2px;\n}\n\n#utlwkvxsyi .gt_summary_row {\n  color: #333333;\n  background-color: #FFFFFF;\n  text-transform: inherit;\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#utlwkvxsyi .gt_first_summary_row {\n  border-top-style: solid;\n  border-top-color: #D3D3D3;\n}\n\n#utlwkvxsyi .gt_first_summary_row.thick {\n  border-top-width: 2px;\n}\n\n#utlwkvxsyi .gt_last_summary_row {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n}\n\n#utlwkvxsyi .gt_grand_summary_row {\n  color: #333333;\n  background-color: #FFFFFF;\n  text-transform: inherit;\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#utlwkvxsyi .gt_first_grand_summary_row {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-top-style: double;\n  border-top-width: 6px;\n  border-top-color: #D3D3D3;\n}\n\n#utlwkvxsyi .gt_last_grand_summary_row_top {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-bottom-style: double;\n  border-bottom-width: 6px;\n  border-bottom-color: #D3D3D3;\n}\n\n#utlwkvxsyi .gt_striped {\n  background-color: rgba(128, 128, 128, 0.05);\n}\n\n#utlwkvxsyi .gt_table_body {\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n}\n\n#utlwkvxsyi .gt_footnotes {\n  color: #333333;\n  background-color: #FFFFFF;\n  border-bottom-style: none;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 2px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n}\n\n#utlwkvxsyi .gt_footnote {\n  margin: 0px;\n  font-size: 90%;\n  padding-top: 4px;\n  padding-bottom: 4px;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#utlwkvxsyi .gt_sourcenotes {\n  color: #333333;\n  background-color: #FFFFFF;\n  border-bottom-style: none;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 2px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n}\n\n#utlwkvxsyi .gt_sourcenote {\n  font-size: 90%;\n  padding-top: 4px;\n  padding-bottom: 4px;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#utlwkvxsyi .gt_left {\n  text-align: left;\n}\n\n#utlwkvxsyi .gt_center {\n  text-align: center;\n}\n\n#utlwkvxsyi .gt_right {\n  text-align: right;\n  font-variant-numeric: tabular-nums;\n}\n\n#utlwkvxsyi .gt_font_normal {\n  font-weight: normal;\n}\n\n#utlwkvxsyi .gt_font_bold {\n  font-weight: bold;\n}\n\n#utlwkvxsyi .gt_font_italic {\n  font-style: italic;\n}\n\n#utlwkvxsyi .gt_super {\n  font-size: 65%;\n}\n\n#utlwkvxsyi .gt_footnote_marks {\n  font-size: 75%;\n  vertical-align: 0.4em;\n  position: initial;\n}\n\n#utlwkvxsyi .gt_asterisk {\n  font-size: 100%;\n  vertical-align: 0;\n}\n\n#utlwkvxsyi .gt_indent_1 {\n  text-indent: 5px;\n}\n\n#utlwkvxsyi .gt_indent_2 {\n  text-indent: 10px;\n}\n\n#utlwkvxsyi .gt_indent_3 {\n  text-indent: 15px;\n}\n\n#utlwkvxsyi .gt_indent_4 {\n  text-indent: 20px;\n}\n\n#utlwkvxsyi .gt_indent_5 {\n  text-indent: 25px;\n}\n\n#utlwkvxsyi .katex-display {\n  display: inline-flex !important;\n  margin-bottom: 0.75em !important;\n}\n\n#utlwkvxsyi div.Reactable > div.rt-table > div.rt-thead > div.rt-tr.rt-tr-group-header > div.rt-th-group:after {\n  height: 0px !important;\n}\n</style>\n<table class=\"gt_table\" data-quarto-disable-processing=\"false\" data-quarto-bootstrap=\"false\">\n  <thead>\n    <tr class=\"gt_col_headings\">\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_left\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"label\"><span data-qmd-base64=\"KipDaGFyYWN0ZXJpc3RpYyoq\"><span class='gt_from_md'><strong>Characteristic</strong></span></span></th>\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_center\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"estimate\"><span data-qmd-base64=\"KipPUioq\"><span class='gt_from_md'><strong>OR</strong></span></span></th>\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_center\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"conf.low\"><span data-qmd-base64=\"Kio5NSUgQ0kqKg==\"><span class='gt_from_md'><strong>95% CI</strong></span></span></th>\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_center\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"p.value\"><span data-qmd-base64=\"KipwLXZhbHVlKio=\"><span class='gt_from_md'><strong>p-value</strong></span></span></th>\n    </tr>\n  </thead>\n  <tbody class=\"gt_table_body\">\n    <tr><td headers=\"label\" class=\"gt_row gt_left\" style=\"font-weight: bold;\">fare in british pounds</td>\n<td headers=\"estimate\" class=\"gt_row gt_center\">1.01</td>\n<td headers=\"conf.low\" class=\"gt_row gt_center\">1.01, 1.02</td>\n<td headers=\"p.value\" class=\"gt_row gt_center\" style=\"font-weight: bold;\"><0.001</td></tr>\n  </tbody>\n  <tfoot class=\"gt_sourcenotes\">\n    <tr>\n      <td class=\"gt_sourcenote\" colspan=\"4\"><span data-qmd-base64=\"QWJicmV2aWF0aW9uczogQ0kgPSBDb25maWRlbmNlIEludGVydmFsLCBPUiA9IE9kZHMgUmF0aW8=\"><span class='gt_from_md'>Abbreviations: CI = Confidence Interval, OR = Odds Ratio</span></span></td>\n    </tr>\n  </tfoot>\n  \n</table>\n</div>\n```\n\n:::\n:::\n\n\n::::\n\n### Step 2: Interpret the Odds Ratio\n\n\n::: {.cell}\n\n```{.r .cell-code}\nexp(coef(model_fare))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n(Intercept)        fare \n  0.4137776   1.0125306 \n```\n\n\n:::\n:::\n\n\n> The odds ratio for `fare` is approximately 1.0125. For each additional British pound of fare, the odds of survival increase by about 1.25%. Passengers who paid more for their tickets had higher odds of surviving.\n\n::: {.callout-tip}\n## Interpreting OR for Continuous Predictors\n- **OR > 1**: each unit increase in the predictor is associated with *higher* odds of the outcome.\n- **OR < 1**: each unit increase is associated with *lower* odds.\n- **OR = 1**: no association.\n\nFor small effects close to 1, the interpretation is: (OR - 1) x 100 = percentage change in odds per unit increase.\n:::\n\n### Step 3: Predicted Probability Curve\n\nUnlike linear regression, the relationship between a continuous predictor and the predicted probability is **curved** (S-shaped):\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Create prediction data\npred_data <- tibble(fare = seq(0, 300, length.out = 200))\n\npred_data <- pred_data |>\n  mutate(prob = predict(model_fare, newdata = pred_data, type = \"response\"))\n\nggplot() +\n  geom_jitter(data = titanic, aes(x = fare, y = survived),\n              height = 0.03, alpha = 0.2, size = 1, color = \"#2C3E50\") +\n  geom_line(data = pred_data, aes(x = fare, y = prob),\n            color = \"#E74C3C\", linewidth = 1.2) +\n  labs(x = \"Ticket Fare (British Pounds)\",\n       y = \"Predicted P(Survived)\",\n       title = \"Logistic Regression: Survival by Fare\",\n       subtitle = \"S-shaped curve keeps predictions between 0 and 1\") +\n  scale_y_continuous(limits = c(0, 1))\n```\n\n::: {.cell-output-display}\n![Predicted probability of survival as a function of ticket fare](lab09-logistic-intro_files/figure-html/predicted-prob-curve-1.png){fig-alt='S-shaped predicted probability curve showing survival probability increasing with ticket fare, with jittered observed outcomes at 0 and 1' width=2100}\n:::\n:::\n\n\n> The jittered dots at 0 and 1 are the actual outcomes. The red S-shaped curve shows the predicted probability from our logistic model. Notice how the curve stays between 0 and 1 --- this is the advantage of logistic over linear regression for binary outcomes.\n\n\n## Key Takeaways\n\n::: {.callout-note}\n## What We Learned\n\n1. **Why logistic regression?** When the outcome is binary (0/1), linear regression can produce impossible predictions (below 0 or above 1). Logistic regression solves this by modeling the log-odds as a linear function of predictors.\n\n2. **The log-odds to odds to probability pipeline:**\n   - `glm()` estimates coefficients on the **log-odds** scale\n   - `exp(coef)` converts to the **odds** scale (odds ratios)\n   - `plogis(linear predictor)` converts to the **probability** scale\n\n3. **Odds ratio interpretation:**\n   - **OR > 1** means higher odds of the outcome\n   - **OR < 1** means lower odds of the outcome\n   - For a **dummy variable**: OR compares the odds between two groups\n   - For a **continuous variable**: OR is the multiplicative change in odds for each one-unit increase\n\n4. **In our Titanic example:**\n   - Females had roughly 11 times the odds of survival compared to males\n   - Each additional pound of fare increased the odds of survival by about 1.25%\n:::\n",
    "supporting": [
      "lab09-logistic-intro_files"
    ],
    "filters": [
      "rmarkdown/pagebreak.lua"
    ],
    "includes": {},
    "engineDependencies": {},
    "preserve": {},
    "postProcess": true
  }
}