{
  "hash": "db919aa676e1307dfdfd6cc8a27b51df",
  "result": {
    "engine": "knitr",
    "markdown": "---\ntitle: \"Homework 6: Two-Way ANOVA and Interactions\"\n---\n\n\n\n\n## Overview\n\n::: {.callout-note}\n## Learning Objectives\n- Conduct and interpret a two-way ANOVA with two categorical predictors\n- Test a country-by-test-language interaction\n- Use estimated cell means to explain a significant interaction\n- Show that two-way ANOVA is equivalent to regression with dummies and interaction terms\n- **Related notes:** [Chapter 3: *One-Way ANOVA*](../../notes/chapters/03-one-way-anova.html) and [Chapter 5: *Interactions*](../../notes/chapters/05-interactions.html)\n- **Related labs:** [Lab 4: *One-Way ANOVA and Categorical Predictors*](../../labs/labs/lab04-categorical-contrasts.html) and [Lab 6: *Interactions in Regression*](../../labs/labs/lab06-interactions.html)\n:::\n\n::: {.callout-tip}\n## Stata-to-R Translation\n| Stata command | R equivalent | Used in |\n|:---|:---|:---|\n| `anova wleread i.test_lan i.country i.test_lan#i.country` | `lm()` followed by `car::Anova(type = 3)` with sum contrasts | Problem 1 |\n| `margins test_lan#country` | `emmeans(model, ~ test_lan_f * country_f)` | Problem 2 |\n| `marginsplot` | `ggplot()` using the estimated-means table | Problem 2 |\n| `regress wleread uk germany test_lan lang_germ lang_uk` | `lm(wleread ~ uk + germany + test_lan + lang_germ + lang_uk)` | Problem 3 |\n:::\n\n**Dataset:** `pisa2000` from the `regdatasets` package.\n\nWe use students from the USA, UK, and Germany ($N = 4{,}528$). The outcome is reading literacy score (`wleread`). The two categorical predictors are country and whether the student speaks the test language at home (`test_lan`).\n\n\n## Setup\n\n\n::: {.cell}\n\n```{.r .cell-code}\ndata(pisa2000)\n\npisa_3 <- pisa2000 |>\n  filter(usa == 1 | uk == 1 | germany == 1) |>\n  mutate(\n    country_f = factor(\n      case_when(\n        usa == 1 ~ \"USA\",\n        uk == 1 ~ \"UK\",\n        germany == 1 ~ \"Germany\"\n      ),\n      levels = c(\"USA\", \"UK\", \"Germany\")\n    ),\n    test_lan_f = factor(\n      test_lan,\n      levels = c(0, 1),\n      labels = c(\"No\", \"Yes\")\n    )\n  )\n\npisa_3 |>\n  count(country_f, test_lan_f, name = \"n\")\n```\n\n::: {.cell-output-display}\n<div class=\"kable-table\">\n\n|country_f |test_lan_f |    n|\n|:---------|:----------|----:|\n|USA       |No         |   89|\n|USA       |Yes        |  931|\n|UK        |No         |   44|\n|UK        |Yes        | 1790|\n|Germany   |No         |   71|\n|Germany   |Yes        | 1603|\n\n</div>\n:::\n:::\n\n\n\n\n\n## Problem 1\n\n### Problem Statement\n\n> Using a two-way ANOVA, test whether there is a main effect of test language, a main effect of country, and an interaction between the two on reading literacy scores (`wleread`).\n\n### Solution\n\nA two-way ANOVA with interaction asks three questions:\n\n- Does average reading score differ by test-language status?\n- Does average reading score differ by country?\n- Does the test-language difference change across countries?\n\nThe interaction is the key test. If the interaction is significant, the effect of test language cannot be summarized well with one single average difference.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nmodel_anova <- lm(\n  wleread ~ test_lan_f * country_f,\n  data = pisa_3,\n  contrasts = list(test_lan_f = contr.sum, country_f = contr.sum)\n)\n\nanova_type3 <- car::Anova(model_anova, type = 3)\n\nanova_tests <- anova_type3 |>\n  as.data.frame() |>\n  tibble::rownames_to_column(\"Source\") |>\n  filter(Source != \"(Intercept)\") |>\n  mutate(\n    Source = dplyr::recode(\n      Source,\n      test_lan_f = \"Test language\",\n      country_f = \"Country\",\n      `test_lan_f:country_f` = \"Test language x country\",\n      Residuals = \"Residual\"\n    ),\n    MS = `Sum Sq` / Df,\n    p = format_p(`Pr(>F)`)\n  ) |>\n  select(Source, Df, SS = `Sum Sq`, MS, F = `F value`, p)\n\nanova_tests |>\n  round_numeric(digits = 4)\n```\n\n::: {.cell-output-display}\n<div class=\"kable-table\">\n\n|Source                  |   Df|         SS|         MS|       F|p      |\n|:-----------------------|----:|----------:|----------:|-------:|:------|\n|Test language           |    1|   517794.3| 517794.271| 59.5659|< .001 |\n|Country                 |    2|   452092.8| 226046.411| 26.0039|< .001 |\n|Test language x country |    2|   255837.1| 127918.548| 14.7155|< .001 |\n|Residual                | 4522| 39308808.0|   8692.793|      NA|NA     |\n\n</div>\n:::\n:::\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nglance_anova <- model_glance(model_anova)\nanova_y <- model.response(model.frame(model_anova))\nrss_anova <- sum(resid(model_anova)^2)\ntss_anova <- sum((anova_y - mean(anova_y))^2)\nmodel_ss_anova <- tss_anova - rss_anova\n\nanova_fit <- tibble(\n  component = c(\"Model\", \"Residual\", \"Total\"),\n  df = c(glance_anova$df_model, glance_anova$df_error, nobs(model_anova) - 1),\n  ss = c(model_ss_anova, rss_anova, tss_anova),\n  ms = c(\n    model_ss_anova / glance_anova$df_model,\n    rss_anova / glance_anova$df_error,\n    NA_real_\n  ),\n  F = c(glance_anova$F, NA_real_, NA_real_),\n  p = c(glance_anova$p, NA_character_, NA_character_)\n)\n\nanova_fit |>\n  round_numeric(digits = 4)\n```\n\n::: {.cell-output-display}\n<div class=\"kable-table\">\n\n|component |   df|       ss|         ms|       F|p      |\n|:---------|----:|--------:|----------:|-------:|:------|\n|Model     |    5|  1368555| 273711.043| 31.4871|< .001 |\n|Residual  | 4522| 39308808|   8692.793|      NA|NA     |\n|Total     | 4527| 40677363|         NA|      NA|NA     |\n\n</div>\n:::\n:::\n\n\nThe interaction is statistically significant:\n\n$$\nF(2, 4522) = 14.72, \\qquad p < .001.\n$$\n\nThat means the test-language difference is not the same in the USA, UK, and Germany. The main effects are also statistically significant:\n\n- **Test language:** $F(1, 4522) = 59.57$, $p < .001$.\n- **Country:** $F(2, 4522) = 26.00$, $p < .001$.\n\nBecause the interaction is significant, the main effects are incomplete summaries. The next step is to inspect the six cell means.\n\n::: {.callout-warning}\n## Why Sum Contrasts?\nStata's `anova` output for factor variables is a Type III ANOVA table. To match that table in R, fit the model with sum-to-zero contrasts and then use `car::Anova(type = 3)`. The fitted cell means do not change; this only affects how the main-effect sums of squares are computed.\n:::\n\n\n\n\n## Problem 2\n\n### Problem Statement\n\n> Produce interaction plots to visualize the nature of the interaction between country and test language. Interpret the pattern.\n\n### Solution\n\nAn interaction plot displays the estimated mean outcome in each combination of the two predictors. Parallel lines suggest no interaction. Non-parallel lines suggest that the fitted difference for one predictor changes across levels of the other.\n\n\n::: {.cell}\n\n```{.r .cell-code}\ncell_means <- emmeans::emmeans(model_anova, ~ test_lan_f * country_f)\n\ncell_table <- cell_means |>\n  as.data.frame() |>\n  mutate(\n    country_f = factor(country_f, levels = c(\"Germany\", \"USA\", \"UK\")),\n    test_lan_f = factor(test_lan_f, levels = c(\"No\", \"Yes\"))\n  ) |>\n  arrange(test_lan_f, country_f)\n\ncell_table |>\n  select(\n    test_language = test_lan_f,\n    country = country_f,\n    mean_reading = emmean,\n    SE,\n    CI_low = lower.CL,\n    CI_high = upper.CL\n  ) |>\n  round_numeric(digits = 4)\n```\n\n::: {.cell-output-display}\n<div class=\"kable-table\">\n\n|test_language |country | mean_reading|      SE|   CI_low|  CI_high|\n|:-------------|:-------|------------:|-------:|--------:|--------:|\n|No            |Germany |     423.4007| 11.0650| 401.7079| 445.0935|\n|No            |USA     |     465.7657|  9.8829| 446.3904| 485.1411|\n|No            |UK      |     538.1898| 14.0557| 510.6337| 565.7459|\n|Yes           |Germany |     521.9310|  2.3287| 517.3656| 526.4964|\n|Yes           |USA     |     528.6330|  3.0557| 522.6424| 534.6236|\n|Yes           |UK      |     538.1839|  2.2037| 533.8636| 542.5043|\n\n</div>\n:::\n:::\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nlanguage_effects <- cell_table |>\n  select(country_f, test_lan_f, emmean) |>\n  tidyr::pivot_wider(names_from = test_lan_f, values_from = emmean) |>\n  mutate(\n    test_language_effect = Yes - No,\n    country_f = factor(country_f, levels = c(\"Germany\", \"USA\", \"UK\"))\n  ) |>\n  arrange(country_f)\n\nlanguage_effects |>\n  rename(country = country_f) |>\n  round_numeric(digits = 4)\n```\n\n::: {.cell-output-display}\n<div class=\"kable-table\">\n\n|country |       No|      Yes| test_language_effect|\n|:-------|--------:|--------:|--------------------:|\n|Germany | 423.4007| 521.9310|              98.5303|\n|USA     | 465.7657| 528.6330|              62.8673|\n|UK      | 538.1898| 538.1839|              -0.0058|\n\n</div>\n:::\n:::\n\n\nThe test-language difference is not constant:\n\n- **Germany:** $521.93 - 423.40 = 98.53$ points.\n- **USA:** $528.63 - 465.77 = 62.87$ points.\n- **UK:** $538.18 - 538.19 \\approx 0$ points.\n\nSo the fitted test-language difference is largest in Germany, moderate in the USA, and nearly zero in the UK.\n\n\n::: {.cell}\n\n```{.r .cell-code  code-fold=\"true\"}\nggplot(\n  cell_table,\n  aes(\n    x = test_lan_f,\n    y = emmean,\n    color = country_f,\n    linetype = country_f,\n    shape = country_f,\n    group = country_f\n  )\n) +\n  geom_line(linewidth = 1) +\n  geom_point(size = 3) +\n  geom_errorbar(aes(ymin = lower.CL, ymax = upper.CL), width = 0.08) +\n  scale_color_manual(\n    values = c(\n      \"Germany\" = unname(ber640_colors[\"primary\"]),\n      \"USA\" = unname(ber640_colors[\"secondary\"]),\n      \"UK\" = unname(ber640_colors[\"accent\"])\n    )\n  ) +\n  scale_linetype_manual(values = c(\"Germany\" = \"solid\", \"USA\" = \"dashed\", \"UK\" = \"dotted\")) +\n  scale_shape_manual(values = c(\"Germany\" = 16, \"USA\" = 17, \"UK\" = 15)) +\n  labs(\n    x = \"Speaks Test Language at Home\",\n    y = \"Estimated Mean Reading Score\",\n    color = \"Country\",\n    linetype = \"Country\",\n    shape = \"Country\"\n  )\n```\n\n::: {.cell-output-display}\n![Estimated reading means by test-language status and country. Error bars show 95% confidence intervals. The non-parallel lines show that the test-language difference changes across countries.](hw06-two-way-anova_files/figure-html/fig-hw06-interaction-means-1.png){#fig-hw06-interaction-means fig-alt='Interaction plot of estimated reading scores by test-language status and country. Germany rises sharply from about 423 to 522, USA rises from about 466 to 529, and UK stays nearly flat around 538.' width=2400}\n:::\n:::\n\n\nThe plot shows the same story as the table. Among students who do not speak the test language at home, the country means are far apart. Among students who do speak the test language at home, the three country means are much closer together. That convergence is the visible form of the interaction.\n\n::: {.callout-important}\n## Interpretation of the Interaction\nThe test-language variable is associated with reading score, but not in the same way everywhere. The fitted difference is about 98.5 points in Germany, 62.9 points in the USA, and almost zero in the UK. This is why the interaction term matters.\n:::\n\n\n\n\n## Problem 3\n\n### Problem Statement\n\n> By forming appropriate dummy variables for two of the countries and their interactions with `test_lan`, estimate the two-way ANOVA model using multiple regression. Use the USA as the reference group. Verify that the regression results match the ANOVA output.\n\n### Solution\n\nWith USA as the reference country, the regression version of the two-way ANOVA is:\n\n$$\n\\widehat{\\text{wleread}}\n= \\hat{\\beta}_0\n+ \\hat{\\beta}_1\\text{uk}\n+ \\hat{\\beta}_2\\text{germany}\n+ \\hat{\\beta}_3\\text{test\\_lan}\n+ \\hat{\\beta}_4\\text{lang\\_germ}\n+ \\hat{\\beta}_5\\text{lang\\_uk}.\n$$\n\nThe interaction dummies are simple products:\n\n$$\n\\text{lang\\_germ} = \\text{test\\_lan} \\times \\text{germany},\n\\qquad\n\\text{lang\\_uk} = \\text{test\\_lan} \\times \\text{uk}.\n$$\n\n\n::: {.cell}\n\n```{.r .cell-code}\npisa_3_reg <- pisa_3 |>\n  mutate(\n    lang_germ = test_lan * germany,\n    lang_uk = test_lan * uk\n  )\n\nmodel_reg <- lm(\n  wleread ~ uk + germany + test_lan + lang_germ + lang_uk,\n  data = pisa_3_reg\n)\n\nmodel_params(model_reg) |>\n  as_tibble() |>\n  mutate(p = format_p(p)) |>\n  select(Parameter, Coefficient, SE, CI_low, CI_high, t, df_error, p) |>\n  round_numeric(digits = 4)\n```\n\n::: {.cell-output-display}\n<div class=\"kable-table\">\n\n|Parameter   | Coefficient|      SE|   CI_low|  CI_high|       t| df_error|p      |\n|:-----------|-----------:|-------:|--------:|--------:|-------:|--------:|:------|\n|(Intercept) |    465.7657|  9.8829| 446.3904| 485.1411| 47.1284|     4522|< .001 |\n|uk          |     72.4240| 17.1824|  38.7381| 106.1100|  4.2150|     4522|< .001 |\n|germany     |    -42.3650| 14.8360| -71.4507| -13.2793| -2.8556|     4522|0.004  |\n|test_lan    |     62.8673| 10.3445|  42.5870|  83.1476|  6.0774|     4522|< .001 |\n|lang_germ   |     35.6630| 15.3253|   5.6179|  65.7081|  2.3271|     4522|0.020  |\n|lang_uk     |    -62.8731| 17.5906| -97.3593| -28.3870| -3.5742|     4522|< .001 |\n\n</div>\n:::\n:::\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nfit_comparison <- bind_rows(\n  model_glance(model_anova) |>\n    mutate(model = \"Two-way ANOVA factor model\", .before = 1),\n  model_glance(model_reg) |>\n    mutate(model = \"Dummy-coded regression\", .before = 1)\n)\n\nfit_comparison |>\n  select(model, n, df_model, df_error, F, p, r_squared, root_mse) |>\n  round_numeric(digits = 4)\n```\n\n::: {.cell-output-display}\n<div class=\"kable-table\">\n\n|model                      |    n| df_model| df_error|       F|p      | r_squared| root_mse|\n|:--------------------------|----:|--------:|--------:|-------:|:------|---------:|--------:|\n|Two-way ANOVA factor model | 4528|        5|     4522| 31.4871|< .001 |    0.0336|  93.2351|\n|Dummy-coded regression     | 4528|        5|     4522| 31.4871|< .001 |    0.0336|  93.2351|\n\n</div>\n:::\n:::\n\n\nThe two models have the same $F$-statistic, $R^2$, Root MSE, and fitted values. They are the same model written in two different languages.\n\nThe coefficients map directly onto cell means:\n\n- **Intercept** ($465.77$): USA students who do not speak the test language at home.\n- **`uk`** ($72.42$): among non-speakers, UK minus USA.\n- **`germany`** ($-42.37$): among non-speakers, Germany minus USA.\n- **`test_lan`** ($62.87$): test-language difference in the USA.\n- **`lang_germ`** ($35.66$): how much larger the test-language difference is in Germany than in the USA.\n- **`lang_uk`** ($-62.87$): how much smaller the test-language difference is in the UK than in the USA.\n\nThe country-specific test-language effects are:\n\n$$\n\\begin{aligned}\n\\text{USA:} \\quad & \\hat{\\beta}_3 = 62.87,\\\\\n\\text{Germany:} \\quad & \\hat{\\beta}_3 + \\hat{\\beta}_4 = 62.87 + 35.66 = 98.53,\\\\\n\\text{UK:} \\quad & \\hat{\\beta}_3 + \\hat{\\beta}_5 = 62.87 - 62.87 \\approx 0.\n\\end{aligned}\n$$\n\n\n::: {.cell}\n\n```{.r .cell-code}\nb <- coef(model_reg)\n\nregression_cells <- tibble(\n  country = factor(c(\"Germany\", \"USA\", \"UK\"), levels = c(\"Germany\", \"USA\", \"UK\")),\n  no_test_language = c(\n    b[\"(Intercept)\"] + b[\"germany\"],\n    b[\"(Intercept)\"],\n    b[\"(Intercept)\"] + b[\"uk\"]\n  ),\n  yes_test_language = c(\n    b[\"(Intercept)\"] + b[\"germany\"] + b[\"test_lan\"] + b[\"lang_germ\"],\n    b[\"(Intercept)\"] + b[\"test_lan\"],\n    b[\"(Intercept)\"] + b[\"uk\"] + b[\"test_lan\"] + b[\"lang_uk\"]\n  )\n) |>\n  mutate(test_language_effect = yes_test_language - no_test_language)\n\nregression_cells |>\n  round_numeric(digits = 4)\n```\n\n::: {.cell-output-display}\n<div class=\"kable-table\">\n\n|country | no_test_language| yes_test_language| test_language_effect|\n|:-------|----------------:|-----------------:|--------------------:|\n|Germany |         423.4007|          521.9310|              98.5303|\n|USA     |         465.7657|          528.6330|              62.8673|\n|UK      |         538.1898|          538.1839|              -0.0058|\n\n</div>\n:::\n:::\n\n\nThis table reproduces the estimated cell means from Problem 2. The regression coefficients and the interaction plot are therefore telling the same story.\n\n::: {.callout-important}\n## ANOVA = Regression\nANOVA is a regression model with categorical predictors. The ANOVA table groups coefficients into factor-level tests; the regression table shows the individual dummy and interaction coefficients. The fitted values are identical.\n:::\n\n\n\n\n## Summary\n\nThis homework used three views of the same model:\n\n1. **Two-way ANOVA** tests the test-language term, country term, and their interaction. The interaction is significant: $F(2, 4522) = 14.72$, $p < .001$.\n\n2. **Estimated cell means and an interaction plot** show the pattern: the test-language difference is large in Germany, moderate in the USA, and nearly zero in the UK.\n\n3. **Dummy-coded regression** shows that ANOVA is regression with categorical predictors and product terms. The regression and ANOVA versions have identical fitted values, $R^2$, Root MSE, and overall $F$-test.\n\nThe core lesson is simple: when an interaction is present, ask \"the effect for whom or under what condition?\" Cell means and interaction plots are the quickest way to answer that question.\n",
    "supporting": [],
    "filters": [
      "rmarkdown/pagebreak.lua"
    ],
    "includes": {},
    "engineDependencies": {},
    "preserve": {},
    "postProcess": true
  }
}