{
  "hash": "c24fa4422130e5943977c387721c1650",
  "result": {
    "engine": "knitr",
    "markdown": "---\ntitle: \"Homework 5: Multiple Regression and Interactions\"\n---\n\n\n\n\n## Overview\n\n::: {.callout-note}\n## Learning Objectives\n- Interpret coefficients in a multiple regression with many predictors\n- Understand and interpret interaction terms in the context of a published regression table\n- Distinguish between main effects and conditional effects in interaction models\n- Decompose interaction models into separate equations for each group\n- **Related:** Chapter 4: *Continuous Predictors* and Chapter 5: *Interactions* (in Lecture Notes)\n:::\n\nThis homework is entirely **conceptual** --- no raw data, only a published regression table to interpret. The table comes from @langton1994, who studied salary determinants among tenured and tenure-track faculty at 308 U.S. colleges and universities in 1969 ($N = 35{,}491$).\n\n\n## The Regression Table\n\nThe table below reproduces Table 3 from @langton1994. Model 1 is a main-effects model. Model 2 adds a measure of salary variation within the professor's field and its interaction with sex.\n\n\n::: {#tbl-hw05-regression .cell tbl-cap='Unstandardized OLS Coefficients for Faculty Salary [@langton1994, Table 3]'}\n\n```{.r .cell-code  code-fold=\"true\" code-summary=\"Show R Code\"}\n# Reproduce the published regression table\nreg_table_df <- data.frame(\n  Variable = c(\n    \"Years of experience\",\n    \"Terminal degree (Ph.D. = 1)\",\n    \"Degree quality\",\n    \"Research productivity\",\n    \"Marital status (married = 1)\",\n    \"Race (nonwhite = 1)\",\n    \"Sex (female = 1)\",\n    \"Salary variation\",\n    \"Sex × salary variation\",\n    \"Intercept\",\n    \"R² (adjusted)\"\n  ),\n  Model_1 = c(\n    \"162.68*** (2.05)\",\n    \"264.050*** (40.09)\",\n    \"616.77*** (34.48)\",\n    \"616.52*** (7.68)\",\n    \"850.26*** (51.19)\",\n    \"-310.27** (106.96)\",\n    \"-1863.70*** (62.07)\",\n    \"—\",\n    \"—\",\n    \"10033.24***\",\n    \".40\"\n  ),\n  Model_2 = c(\n    \"162.59*** (2.05)\",\n    \"270.15*** (40.12)\",\n    \"657.08*** (34.64)\",\n    \"614.96*** (7.68)\",\n    \"816.00*** (53.23)\",\n    \"-342.13*** (106.83)\",\n    \"-698.46 (566.87)\",\n    \"-5571.50*** (585.62)\",\n    \"-3932.71* (1872.05)\",\n    \"11712.80***\",\n    \".40\"\n  )\n)\n\nknitr::kable(\n  reg_table_df,\n  col.names = c(\"Variable\", \"Model 1\", \"Model 2\"),\n  align = c(\"l\", \"r\", \"r\"),\n  caption = NULL\n)\n```\n\n::: {.cell-output-display}\n\n\n|Variable                     |             Model 1|              Model 2|\n|:----------------------------|-------------------:|--------------------:|\n|Years of experience          |    162.68*** (2.05)|     162.59*** (2.05)|\n|Terminal degree (Ph.D. = 1)  |  264.050*** (40.09)|    270.15*** (40.12)|\n|Degree quality               |   616.77*** (34.48)|    657.08*** (34.64)|\n|Research productivity        |    616.52*** (7.68)|     614.96*** (7.68)|\n|Marital status (married = 1) |   850.26*** (51.19)|    816.00*** (53.23)|\n|Race (nonwhite = 1)          |  -310.27** (106.96)|  -342.13*** (106.83)|\n|Sex (female = 1)             | -1863.70*** (62.07)|     -698.46 (566.87)|\n|Salary variation             |                   —| -5571.50*** (585.62)|\n|Sex × salary variation       |                   —|  -3932.71* (1872.05)|\n|Intercept                    |         10033.24***|          11712.80***|\n|R² (adjusted)                |                 .40|                  .40|\n\n\n:::\n:::\n\n\n**Note:** \\*$p < .05$, \\*\\*$p < .01$, \\*\\*\\*$p < .001$ (two-tailed). Numbers in parentheses are standard errors.\n\n::: {.callout-note}\n## Variable Definitions\n- **Degree quality:** Rating of institution from which degree was received (Carnegie Commission), scale 0--4.\n- **Research productivity:** Scale based on number of articles/books published.\n- **Salary variation:** Variability in salary within the professor's field controlling for the other variables --- a measure of \"uncertainty and dispersion in wages paid in the labor market.\"\n- **Sex:** $1 =$ female, $0 =$ male.\n:::\n\n\n## Problem 1\n\n### Problem Statement\n\n> Interpret each of the regression coefficients in Model 1 (main effects only) from the @langton1994 table on faculty salaries.\n\n### Solution\n\nModel 1 contains seven predictors --- four continuous and three dummy variables. Each coefficient represents the estimated effect of that variable **after controlling for all other variables in the model**.\n\n::: {.callout-tip}\n## Interpretation Template\n- **Continuous predictor:** \"After controlling for each of the other variables, each one-unit increase in $X$ is associated with a \\$___ change in estimated mean salary.\"\n- **Dummy predictor:** \"After controlling for each of the other variables, the estimated mean salary for [group = 1] is \\$___ higher/lower than for [group = 0].\"\n:::\n\nAfter controlling for each of the other variables in the model, the estimated mean 9-month salary:\n\n1. **Years of experience** ($\\hat{\\beta} = 162.68$, $p < .001$): increases by **\\$162.68** for each additional year of experience.\n\n2. **Terminal degree** ($\\hat{\\beta} = 264.050$, $p < .001$): is **\\$264.05 higher** for Ph.D. holders than for those without a Ph.D.\n\n3. **Degree quality** ($\\hat{\\beta} = 616.77$, $p < .001$): increases by **\\$616.77** for each one-unit increase in degree quality (on the 0--4 Carnegie scale).\n\n4. **Research productivity** ($\\hat{\\beta} = 616.52$, $p < .001$): increases by **\\$616.52** for each one-unit increase in research productivity.\n\n5. **Marital status** ($\\hat{\\beta} = 850.26$, $p < .001$): is **\\$850.26 higher** for married faculty than for non-married faculty.\n\n6. **Race** ($\\hat{\\beta} = -310.27$, $p < .01$): is **\\$310.27 lower** for nonwhite faculty than for white faculty.\n\n7. **Sex** ($\\hat{\\beta} = -1863.70$, $p < .001$): is **\\$1,863.70 lower** for female faculty than for male faculty.\n\n::: {.callout-important}\n## The Gender Pay Gap\nThe sex coefficient is the largest in absolute value among all predictors. Even after controlling for experience, terminal degree, degree quality, research productivity, marital status, and race, **women earned nearly \\$1,864 less than men** on a 9-month salary basis. This is a substantial disparity that persists after accounting for many legitimate determinants of salary.\n:::\n\n\n## Problem 2\n\n### Problem Statement\n\n> In Model 2, interpret the coefficients of Sex, Salary variation, and Sex $\\times$ Salary variation.\n\n### Solution\n\nModel 2 introduces an **interaction term** between Sex and Salary variation. To interpret these coefficients, we first write out the relevant portion of the regression equation (focusing on the three variables of interest and holding the other predictors constant at fixed values):\n\n$$\n\\hat{y} = \\hat{\\beta}_0 + \\hat{\\beta}_1 \\cdot \\text{Female} + \\hat{\\beta}_2 \\cdot \\text{SV} + \\hat{\\beta}_3 \\cdot \\text{Female} \\times \\text{SV} + \\cdots\n$$\n\nwhere:\n\n- $\\hat{\\beta}_1 = -698.46$ (Sex)\n- $\\hat{\\beta}_2 = -5571.50$ (Salary variation)\n- $\\hat{\\beta}_3 = -3932.71$ (Sex $\\times$ Salary variation)\n\n**Algebraic decomposition by group:**\n\nFor **men** (Female $= 0$):\n\n$$\n\\hat{y}_{\\text{men}} = \\hat{\\beta}_0 + (-5571.50) \\cdot \\text{SV} + \\cdots\n$$\n\nFor **women** (Female $= 1$):\n\n$$\n\\hat{y}_{\\text{women}} = (\\hat{\\beta}_0 - 698.46) + (-5571.50 - 3932.71) \\cdot \\text{SV} + \\cdots\n$$\n\n$$\n= (\\hat{\\beta}_0 - 698.46) + (-9504.21) \\cdot \\text{SV} + \\cdots\n$$\n\n::: {.panel-tabset}\n\n#### Version 1: Emphasis on Salary Variation Effect\n\nThis interpretation focuses on what each coefficient tells us about the effect of salary variation:\n\n- **Sex** ($\\hat{\\beta}_1 = -698.46$, $p > .05$): When salary variation $= 0$, the estimated mean salary for women is \\$698.46 lower than for men, holding all other variables constant. However, this coefficient is **not statistically significant** ($\\text{SE} = 566.87$).\n\n- **Salary variation** ($\\hat{\\beta}_2 = -5571.50$, $p < .001$): For **men** (the reference group), a one-unit increase in salary variation is associated with a **\\$5,571.50 decrease** in estimated mean salary.\n\n- **Sex $\\times$ Salary variation** ($\\hat{\\beta}_3 = -3932.71$, $p < .05$): For **women**, the negative effect of salary variation is **even larger**. Each one-unit increase in salary variation is associated with an *additional* \\$3,932.71 decrease in salary beyond the men's effect. Women's total effect of salary variation is:\n\n$$\n\\hat{\\beta}_2 + \\hat{\\beta}_3 = -5571.50 + (-3932.71) = -\\$9{,}504.21\n$$\n\n::: {.callout-warning}\n## When $X = 0$ Might Be Meaningless\nThe Sex coefficient in Model 2 ($-698.46$) represents the male-female difference **when salary variation equals zero**. But salary variation is unlikely to be exactly zero in any real academic field. This makes $\\hat{\\beta}_1$ a mathematical extrapolation rather than a substantively meaningful quantity. Always consider whether the \"when the other variable equals zero\" condition is realistic when interpreting coefficients in interaction models.\n:::\n\n#### Version 2: Emphasis on the Sex Effect\n\nThis interpretation focuses on what the interaction tells us about the **gender gap**:\n\n- **Sex** ($\\hat{\\beta}_1 = -698.46$): The baseline gender gap (at salary variation $= 0$).\n\n- **Sex $\\times$ Salary variation** ($\\hat{\\beta}_3 = -3932.71$, $p < .05$): The gender gap **increases by \\$3,932.71** for each one-unit increase in salary variation. In fields where salary variation is higher, women are disadvantaged *even more* relative to men.\n\nAt any given level of salary variation (SV), the estimated male-female wage gap is:\n\n$$\n\\hat{y}_{\\text{men}} - \\hat{y}_{\\text{women}} = 698.46 + 3932.71 \\cdot \\text{SV}\n$$\n\nThis means the gender gap is not constant --- it **widens** as salary variation increases.\n\n:::\n\n::: {.panel-tabset group=\"fig-hw05-interaction\"}\n\n#### Simple\n\n\n::: {.cell}\n\n```{.r .cell-code  code-fold=\"true\" code-summary=\"Show R Code\"}\n# Simple: Interaction plot - salary by gender and salary variation\nsalary_var <- seq(0, 1, length.out = 100)\nmen_salary <- 11712.80 - 5571.50 * salary_var\nwomen_salary <- (11712.80 - 698.46) + (-5571.50 - 3932.71) * salary_var\n\ndf_interaction <- data.frame(\n  sv = rep(salary_var, 2),\n  salary = c(men_salary, women_salary),\n  gender = rep(c(\"Men\", \"Women\"), each = 100)\n)\n\nggplot(df_interaction, aes(x = sv, y = salary, color = gender)) +\n  geom_line(linewidth = 1) +\n  labs(x = \"Salary Variation\", y = \"Predicted Salary ($)\",\n       title = \"Gender Pay Gap Widens with Salary Variation\",\n       color = \"Gender\")\n```\n\n::: {.cell-output-display}\n![Predicted salary as a function of salary variation for men and women (Model 2). The lines diverge as salary variation increases, illustrating the interaction effect.](hw05-interactions_files/figure-html/fig-hw05-interaction-simple-1.png){#fig-hw05-interaction-simple fig-alt='Two lines showing predicted salary as a function of salary variation. Both lines slope downward, but the women\\'s line falls much more steeply than the men\\'s line, creating a widening gender gap as salary variation increases.' width=2700}\n:::\n:::\n\n\n#### Detailed\n\n\n::: {.cell}\n\n```{.r .cell-code  code-fold=\"true\" code-summary=\"Show R Code\"}\n# --- Construct predicted salary lines from Model 2 coefficients ---\n# Focus on the three key variables: Sex, Salary variation, and interaction\n# Hold other predictors at plausible constant values for illustration\n# (exact baseline doesn't matter for showing the interaction pattern)\n\n# Coefficients from Model 2\nb0 <- 11712.80      # Intercept\nb_sex <- -698.46     # Sex (female = 1)\nb_sv <- -5571.50     # Salary variation\nb_int <- -3932.71    # Sex x Salary variation\n\n# Plausible constants for other predictors (approximate sample means)\nother_terms <- 162.59 * 10 +   # 10 years experience\n               270.15 * 0.7 +  # 70% Ph.D.\n               657.08 * 2.0 +  # Degree quality = 2\n               614.96 * 3.0 +  # Research productivity = 3\n               816.00 * 0.7 +  # 70% married\n              -342.13 * 0.05   # 5% nonwhite\n\n# Salary variation range for plotting\nsv_range <- seq(0, 1.2, length.out = 200)\n\n# Predicted salary for men (Female = 0)\ny_men <- b0 + b_sv * sv_range + other_terms\n\n# Predicted salary for women (Female = 1)\ny_women <- (b0 + b_sex) + (b_sv + b_int) * sv_range + other_terms\n\n# Create data frame for plotting\nplot_data <- data.frame(\n  salary_variation = rep(sv_range, 2),\n  predicted_salary = c(y_men, y_women),\n  sex = rep(c(\"Men\", \"Women\"), each = length(sv_range))\n)\n\n# --- Plot ---\nggplot(plot_data, aes(x = salary_variation, y = predicted_salary,\n                      color = sex, linetype = sex)) +\n  geom_line(linewidth = 1.3) +\n  # Annotate the gap at SV = 0.8\n  annotate(\n    \"segment\",\n    x = 0.8, xend = 0.8,\n    y = b0 + b_sv * 0.8 + other_terms,\n    yend = (b0 + b_sex) + (b_sv + b_int) * 0.8 + other_terms,\n    color = ber640_colors[\"secondary\"],\n    linewidth = 0.8, linetype = \"dotted\",\n    arrow = arrow(ends = \"both\", length = unit(0.15, \"inches\"))\n  ) +\n  annotate(\n    \"text\",\n    x = 0.83,\n    y = ((b0 + b_sv * 0.8 + other_terms) +\n         ((b0 + b_sex) + (b_sv + b_int) * 0.8 + other_terms)) / 2,\n    label = paste0(\n      \"Gap = $\",\n      format(round(698.46 + 3932.71 * 0.8, 0), big.mark = \",\")\n    ),\n    hjust = 0, size = 4,\n    color = ber640_colors[\"secondary\"],\n    fontface = \"bold\"\n  ) +\n  # Annotate line equations\n  annotate(\n    \"text\",\n    x = 0.05,\n    y = b0 + b_sv * 0.05 + other_terms + 300,\n    label = \"Men: slope = -$5,572\",\n    hjust = 0, size = 3.8,\n    color = ber640_colors[\"primary\"],\n    fontface = \"bold\"\n  ) +\n  annotate(\n    \"text\",\n    x = 0.05,\n    y = (b0 + b_sex) + (b_sv + b_int) * 0.05 + other_terms - 300,\n    label = \"Women: slope = -$9,504\",\n    hjust = 0, size = 3.8,\n    color = ber640_colors[\"accent\"],\n    fontface = \"bold\"\n  ) +\n  # Scales\n  scale_color_manual(\n    name = \"Sex\",\n    values = c(\n      \"Men\" = unname(ber640_colors[\"primary\"]),\n      \"Women\" = unname(ber640_colors[\"accent\"])\n    )\n  ) +\n  scale_linetype_manual(\n    name = \"Sex\",\n    values = c(\"Men\" = \"solid\", \"Women\" = \"dashed\")\n  ) +\n  scale_y_continuous(labels = scales::dollar_format()) +\n  labs(\n    title = \"Interaction Effect: Sex x Salary Variation\",\n    subtitle = \"The gender pay gap widens as salary variation increases\",\n    x = \"Salary Variation (within field)\",\n    y = \"Predicted 9-Month Salary ($)\"\n  )\n```\n\n::: {.cell-output-display}\n![Predicted salary as a function of salary variation for men and women (Model 2). The lines diverge as salary variation increases, illustrating the interaction effect. Other predictors held constant at sample means (values chosen for illustration only).](hw05-interactions_files/figure-html/fig-hw05-interaction-detailed-1.png){#fig-hw05-interaction-detailed fig-alt='Two diverging lines showing predicted salary versus salary variation. Men\\'s salary decreases by 5572 dollars per unit increase in salary variation, while women\\'s salary decreases by 9504 dollars. The gender gap widens from about 698 dollars at zero salary variation, illustrating the interaction effect.' width=2700}\n:::\n:::\n\n\n:::\n\n::: {.callout-warning}\n## Main Effects in Interaction Models Are Conditional\nWhen an interaction term is present, the \"main effect\" of a variable represents its effect **only when the interacting variable equals zero** (or the reference category). It is NOT the average effect across all levels. In Model 2, the coefficient of Sex ($-698.46$) is the gender gap only when Salary variation $= 0$ --- which may never occur in practice. Always state the conditioning value when interpreting main effects in interaction models.\n:::\n\nThe figure makes the interaction visually clear: the two lines **diverge** as salary variation increases. Both men and women earn less in fields with higher salary variation, but the negative effect is nearly **twice as large** for women ($-\\$9{,}504$) as for men ($-\\$5{,}572$). The widening gap between the lines is the interaction effect.\n\n\n## Problem 3\n\n### Problem Statement\n\n> By looking at the estimates, can you answer the question of whether the male-female wage differential is exacerbated by more uncertainty and dispersion in wages?\n\n### Solution\n\n**Yes.** The male-female wage differential is exacerbated by greater salary variation.\n\nThe interaction coefficient ($\\hat{\\beta}_3 = -3932.71$, $p < .05$) tells us that for each one-unit increase in salary variation, the gender gap in salary **increases by \\$3,932.71**. Recall from Version 2 in Problem 2 that the estimated gender gap at any level of salary variation is:\n\n$$\n\\text{Gender gap} = \\hat{y}_{\\text{men}} - \\hat{y}_{\\text{women}} = 698.46 + 3932.71 \\cdot \\text{SV}\n$$\n\nAs salary variation (SV) increases, the gap grows. In fields with more uncertainty and dispersion in wages, women fare **disproportionately worse** relative to men.\n\n::: {.callout-important}\n## What Interaction Terms Tell Us\nAn interaction term tells us that the effect of one variable **depends on the level of another variable**. Here, the interaction between sex and salary variation means:\n\n- The effect of salary variation on salary is **different for men and women** (Version 1).\n- Equivalently, the male-female salary gap is **not constant** across fields with different salary variation (Version 2).\n\nBoth statements describe the same statistical relationship from different perspectives. The substantive conclusion is that labor market uncertainty amplifies gender inequality in faculty pay.\n:::\n\n\n::: {.callout-caution}\n## Common Mistake: Reading Main Effects as Unconditional in Interaction Models\nIn Model 2, the coefficient of Sex ($-698.46$) does NOT represent the \"overall\" gender gap. It is the gender gap *only when salary variation equals zero*. Students frequently interpret main effects in interaction models as if the interaction term were absent. When an interaction is present, every main effect is conditional on the interacting variable being at its reference value (often zero). Always state the conditioning value.\n:::\n\n\n## Summary\n\nThis homework practiced three key skills for interpreting multiple regression with interaction terms:\n\n1. **Coefficient interpretation in main-effects models.** Each coefficient in Model 1 represents the estimated change in salary associated with a one-unit change in the predictor, **controlling for all other variables**. The \"controlling for\" qualifier is essential in multiple regression --- it distinguishes partial effects from marginal (unadjusted) effects.\n\n2. **Interaction interpretation.** When a model includes $X_1$, $X_2$, and $X_1 \\times X_2$, the coefficient of $X_1$ is its effect **when $X_2 = 0$** (and vice versa). The interaction coefficient tells us how the effect of one variable changes across levels of the other. Algebraic decomposition into separate group equations makes this concrete.\n\n3. **Conditional effects and diverging slopes.** The interaction between sex and salary variation produced two regression lines with different slopes --- the hallmark of a moderated relationship. The gender pay gap is not a fixed quantity but depends on the labor market context (salary variation) of the professor's field.\n\n::: {.callout-note}\n## Looking Ahead\nIn **Homework 6** (Two-Way ANOVA), we extend interaction concepts to models with **two categorical predictors**. Instead of diverging slopes (continuous $\\times$ dummy), you will see crossing or non-parallel cell means --- but the core logic of \"the effect of one variable depends on the level of the other\" remains the same.\n:::\n",
    "supporting": [
      "hw05-interactions_files"
    ],
    "filters": [
      "rmarkdown/pagebreak.lua"
    ],
    "includes": {},
    "engineDependencies": {},
    "preserve": {},
    "postProcess": true
  }
}