{
  "hash": "21a6bffb9c1dcb2847c26621cbd55e5e",
  "result": {
    "engine": "knitr",
    "markdown": "---\ntitle: \"Lab 10: Logistic Regression with Multiple Predictors\"\n---\n\n\n\n\n## Goals\n\n::: {.callout-note}\n## What You'll Learn in This Lab\n- Compute and interpret confidence intervals for odds ratios\n- Standardize continuous predictors so odds ratios have practical meaning\n- Plot predicted probability curves (the logistic S-curve)\n- Include categorical predictors with 3+ levels in logistic regression\n- Change reference groups and compute pairwise comparisons\n- **Lecture Notes Reference:** Chapters 9--10: *Logistic Regression with Multiple Predictors*\n:::\n\n**Dataset:** `titanic` from the `regdatasets` package\n\n## Setup\n\n\n::: {.cell}\n\n```{.r .cell-code}\nlibrary(regdatasets)\ndata(titanic)\n\n# The 'sex' variable is already coded as 0 = male, 1 = female\n# Rename it to 'female' for clarity (same as Lab 9)\ntitanic <- titanic |>\n  rename(female = sex)\n\nglimpse(titanic)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nRows: 1,309\nColumns: 6\n$ pclass   <int> 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1…\n$ survived <int> 1, 1, 0, 0, 0, 1, 1, 0, 1, 0, 0, 1, 1, 1, 1, 0, 0, 1, 1, 0, 1…\n$ age      <dbl> 29.0000, 0.9167, 2.0000, 30.0000, 25.0000, 48.0000, 63.0000, …\n$ fare     <dbl> 211.3375, 151.5500, 151.5500, 151.5500, 151.5500, 26.5500, 77…\n$ embarked <chr> \"S\", \"S\", \"S\", \"S\", \"S\", \"S\", \"S\", \"S\", \"C\", \"C\", \"C\", \"C\", \"…\n$ female   <int> 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 0, 1, 1, 1, 0, 0, 0, 1, 1, 0, 0…\n```\n\n\n:::\n:::\n\n\n\n## Part 1: Review and Confidence Intervals\n\nIn Lab 9 we fit a simple logistic regression predicting survival from gender. Let's revisit that model and add something new: **confidence intervals for the odds ratio**.\n\n### Step 1: Quick Review\n\n\n::: {.cell}\n\n```{.r .cell-code}\nmodel_female <- glm(survived ~ female, data = titanic, family = binomial)\nexp(coef(model_female))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n(Intercept)      female \n  0.2360704  11.3071844 \n```\n\n\n:::\n:::\n\n\n> Recall: the odds ratio of 11.31 means females had roughly 11.3 times the odds of surviving compared to males. But how precise is that estimate? We need a confidence interval.\n\n### Step 2: Confidence Intervals for Odds Ratios\n\nR provides profile-likelihood confidence intervals with `confint()`. We exponentiate them to get CIs on the odds ratio scale:\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Profile-likelihood CI (the default for glm)\nexp(confint(model_female))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n                2.5 %     97.5 %\n(Intercept) 0.1981912  0.2794823\nfemale      8.6871038 14.8093675\n```\n\n\n:::\n:::\n\n\n> The 95% CI for the odds ratio of `female` runs from roughly 8.69 to 14.81. Since this interval does not include 1, we are confident that gender has a statistically significant association with survival. More importantly, we can say the true odds ratio is at least about 8---a substantial effect by any standard.\n\n### Step 3: Manual CI Using the Wald Method\n\nYou can also compute CIs manually using the formula: $\\exp\\!\\bigl(b \\pm 1.96 \\times SE\\bigr)$.\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Extract coefficient and SE\nb  <- coef(summary(model_female))[\"female\", \"Estimate\"]\nse <- coef(summary(model_female))[\"female\", \"Std. Error\"]\n\n# Wald 95% CI on the log-odds scale\nci_logit <- b + c(-1.96, 1.96) * se\n\n# Convert to odds ratio scale\nci_or <- exp(ci_logit)\ncat(\"Manual 95% CI for OR:\", round(ci_or[1], 2), \"to\", round(ci_or[2], 2), \"\\n\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nManual 95% CI for OR: 8.66 to 14.76 \n```\n\n\n:::\n:::\n\n\n> The manual Wald CI and the profile-likelihood CI will be similar but not identical. Profile CIs are slightly more accurate because they account for the curvature of the likelihood function. In practice, both approaches lead to the same conclusion.\n\n::: {.callout-warning}\n## Profile vs. Wald Confidence Intervals\nR's `confint()` computes **profile-likelihood** CIs by default, while Stata computes **Wald** CIs. The two methods give slightly different numbers (especially in small samples). For Wald CIs that match Stata more closely, use `confint.default()` instead of `confint()`. In practice, the differences are usually small and both methods lead to the same conclusions.\n:::\n\n::: {.callout-tip}\n## When to Report CIs\nAlways report confidence intervals alongside odds ratios. A point estimate like OR = 11.4 is incomplete without knowing its precision. The CI tells your reader whether the effect could plausibly be small, large, or anywhere in between.\n:::\n\n\n## Part 2: Making Continuous Predictors Meaningful\n\n### Step 1: The Interpretation Problem\n\nIn Lab 9 we fit a model with `fare` as a continuous predictor. Let's look at that odds ratio again:\n\n\n::: {.cell}\n\n```{.r .cell-code}\nmodel_fare <- glm(survived ~ fare, data = titanic, family = binomial)\nexp(coef(model_fare))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n(Intercept)        fare \n  0.4137776   1.0125306 \n```\n\n\n:::\n:::\n\n\n> The OR for fare is about 1.0125. That means for each additional **one pound** of fare, the odds of survival increase by about 1.25%. Technically correct, but not very informative. One pound is a tiny change on a scale that ranges from 0 to over 500.\n\n### Step 2: Standardize the Predictor\n\nThe solution is to **standardize** fare so the OR describes the effect of a one standard deviation change:\n\n$$z_{\\text{fare}} = \\frac{\\text{fare} - \\overline{\\text{fare}}}{SD_{\\text{fare}}}$$\n\n\n::: {.cell}\n\n```{.r .cell-code}\ntitanic <- titanic |>\n  mutate(z_fare = (fare - mean(fare, na.rm = TRUE)) / sd(fare, na.rm = TRUE))\n\n# Check that standardization worked\ntitanic |>\n  summarise(\n    fare_mean = round(mean(fare, na.rm = TRUE), 2),\n    fare_sd   = round(sd(fare, na.rm = TRUE), 2),\n    z_fare_mean = round(mean(z_fare, na.rm = TRUE), 2),\n    z_fare_sd   = round(sd(z_fare, na.rm = TRUE), 2)\n  )\n```\n\n::: {.cell-output-display}\n<div class=\"kable-table\">\n\n| fare_mean| fare_sd| z_fare_mean| z_fare_sd|\n|---------:|-------:|-----------:|---------:|\n|      33.3|   51.76|           0|         1|\n\n</div>\n:::\n:::\n\n\n> After standardizing, `z_fare` has a mean of 0 and a SD of 1. Now a one-unit change in `z_fare` corresponds to a one SD change in the original fare.\n\n### Step 3: Fit the Model with the Standardized Predictor\n\n\n::: {.cell}\n\n```{.r .cell-code}\nmodel_z_fare <- glm(survived ~ z_fare, data = titanic, family = binomial)\n```\n:::\n\n\n:::: {.panel-tabset}\n\n#### Simple\n\n\n::: {.cell}\n\n```{.r .cell-code}\nsummary(model_z_fare)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\nCall:\nglm(formula = survived ~ z_fare, family = binomial, data = titanic)\n\nCoefficients:\n            Estimate Std. Error z value Pr(>|z|)    \n(Intercept) -0.46781    0.05914  -7.910 2.56e-15 ***\nz_fare       0.64454    0.08304   7.762 8.35e-15 ***\n---\nSignif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1\n\n(Dispersion parameter for binomial family taken to be 1)\n\n    Null deviance: 1740.1  on 1307  degrees of freedom\nResidual deviance: 1654.0  on 1306  degrees of freedom\n  (1 observation deleted due to missingness)\nAIC: 1658\n\nNumber of Fisher Scoring iterations: 4\n```\n\n\n:::\n:::\n\n\n#### Advanced\n\n\n::: {.cell}\n\n```{.r .cell-code}\nmodel_z_fare |>\n  tbl_regression(exponentiate = TRUE) |>\n  bold_labels() |>\n  bold_p(t = 0.05)\n```\n\n::: {.cell-output-display}\n\n```{=html}\n<div id=\"ovbflbpmbc\" style=\"padding-left:0px;padding-right:0px;padding-top:10px;padding-bottom:10px;overflow-x:auto;overflow-y:auto;width:auto;height:auto;\">\n<style>#ovbflbpmbc table {\n  font-family: system-ui, 'Segoe UI', Roboto, Helvetica, Arial, sans-serif, 'Apple Color Emoji', 'Segoe UI Emoji', 'Segoe UI Symbol', 'Noto Color Emoji';\n  -webkit-font-smoothing: antialiased;\n  -moz-osx-font-smoothing: grayscale;\n}\n\n#ovbflbpmbc thead, #ovbflbpmbc tbody, #ovbflbpmbc tfoot, #ovbflbpmbc tr, #ovbflbpmbc td, #ovbflbpmbc th {\n  border-style: none;\n}\n\n#ovbflbpmbc p {\n  margin: 0;\n  padding: 0;\n}\n\n#ovbflbpmbc .gt_table {\n  display: table;\n  border-collapse: collapse;\n  line-height: normal;\n  margin-left: auto;\n  margin-right: auto;\n  color: #333333;\n  font-size: 16px;\n  font-weight: normal;\n  font-style: normal;\n  background-color: #FFFFFF;\n  width: auto;\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #A8A8A8;\n  border-right-style: none;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #A8A8A8;\n  border-left-style: none;\n  border-left-width: 2px;\n  border-left-color: #D3D3D3;\n}\n\n#ovbflbpmbc .gt_caption {\n  padding-top: 4px;\n  padding-bottom: 4px;\n}\n\n#ovbflbpmbc .gt_title {\n  color: #333333;\n  font-size: 125%;\n  font-weight: initial;\n  padding-top: 4px;\n  padding-bottom: 4px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-bottom-color: #FFFFFF;\n  border-bottom-width: 0;\n}\n\n#ovbflbpmbc .gt_subtitle {\n  color: #333333;\n  font-size: 85%;\n  font-weight: initial;\n  padding-top: 3px;\n  padding-bottom: 5px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-top-color: #FFFFFF;\n  border-top-width: 0;\n}\n\n#ovbflbpmbc .gt_heading {\n  background-color: #FFFFFF;\n  text-align: center;\n  border-bottom-color: #FFFFFF;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n}\n\n#ovbflbpmbc .gt_bottom_border {\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n}\n\n#ovbflbpmbc .gt_col_headings {\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n}\n\n#ovbflbpmbc .gt_col_heading {\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: normal;\n  text-transform: inherit;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n  vertical-align: bottom;\n  padding-top: 5px;\n  padding-bottom: 6px;\n  padding-left: 5px;\n  padding-right: 5px;\n  overflow-x: hidden;\n}\n\n#ovbflbpmbc .gt_column_spanner_outer {\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: normal;\n  text-transform: inherit;\n  padding-top: 0;\n  padding-bottom: 0;\n  padding-left: 4px;\n  padding-right: 4px;\n}\n\n#ovbflbpmbc .gt_column_spanner_outer:first-child {\n  padding-left: 0;\n}\n\n#ovbflbpmbc .gt_column_spanner_outer:last-child {\n  padding-right: 0;\n}\n\n#ovbflbpmbc .gt_column_spanner {\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  vertical-align: bottom;\n  padding-top: 5px;\n  padding-bottom: 5px;\n  overflow-x: hidden;\n  display: inline-block;\n  width: 100%;\n}\n\n#ovbflbpmbc .gt_spanner_row {\n  border-bottom-style: hidden;\n}\n\n#ovbflbpmbc .gt_group_heading {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: initial;\n  text-transform: inherit;\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n  vertical-align: middle;\n  text-align: left;\n}\n\n#ovbflbpmbc .gt_empty_group_heading {\n  padding: 0.5px;\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: initial;\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  vertical-align: middle;\n}\n\n#ovbflbpmbc .gt_from_md > :first-child {\n  margin-top: 0;\n}\n\n#ovbflbpmbc .gt_from_md > :last-child {\n  margin-bottom: 0;\n}\n\n#ovbflbpmbc .gt_row {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  margin: 10px;\n  border-top-style: solid;\n  border-top-width: 1px;\n  border-top-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n  vertical-align: middle;\n  overflow-x: hidden;\n}\n\n#ovbflbpmbc .gt_stub {\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: initial;\n  text-transform: inherit;\n  border-right-style: solid;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#ovbflbpmbc .gt_stub_row_group {\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: initial;\n  text-transform: inherit;\n  border-right-style: solid;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n  padding-left: 5px;\n  padding-right: 5px;\n  vertical-align: top;\n}\n\n#ovbflbpmbc .gt_row_group_first td {\n  border-top-width: 2px;\n}\n\n#ovbflbpmbc .gt_row_group_first th {\n  border-top-width: 2px;\n}\n\n#ovbflbpmbc .gt_summary_row {\n  color: #333333;\n  background-color: #FFFFFF;\n  text-transform: inherit;\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#ovbflbpmbc .gt_first_summary_row {\n  border-top-style: solid;\n  border-top-color: #D3D3D3;\n}\n\n#ovbflbpmbc .gt_first_summary_row.thick {\n  border-top-width: 2px;\n}\n\n#ovbflbpmbc .gt_last_summary_row {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n}\n\n#ovbflbpmbc .gt_grand_summary_row {\n  color: #333333;\n  background-color: #FFFFFF;\n  text-transform: inherit;\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#ovbflbpmbc .gt_first_grand_summary_row {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-top-style: double;\n  border-top-width: 6px;\n  border-top-color: #D3D3D3;\n}\n\n#ovbflbpmbc .gt_last_grand_summary_row_top {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-bottom-style: double;\n  border-bottom-width: 6px;\n  border-bottom-color: #D3D3D3;\n}\n\n#ovbflbpmbc .gt_striped {\n  background-color: rgba(128, 128, 128, 0.05);\n}\n\n#ovbflbpmbc .gt_table_body {\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n}\n\n#ovbflbpmbc .gt_footnotes {\n  color: #333333;\n  background-color: #FFFFFF;\n  border-bottom-style: none;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 2px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n}\n\n#ovbflbpmbc .gt_footnote {\n  margin: 0px;\n  font-size: 90%;\n  padding-top: 4px;\n  padding-bottom: 4px;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#ovbflbpmbc .gt_sourcenotes {\n  color: #333333;\n  background-color: #FFFFFF;\n  border-bottom-style: none;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 2px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n}\n\n#ovbflbpmbc .gt_sourcenote {\n  font-size: 90%;\n  padding-top: 4px;\n  padding-bottom: 4px;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#ovbflbpmbc .gt_left {\n  text-align: left;\n}\n\n#ovbflbpmbc .gt_center {\n  text-align: center;\n}\n\n#ovbflbpmbc .gt_right {\n  text-align: right;\n  font-variant-numeric: tabular-nums;\n}\n\n#ovbflbpmbc .gt_font_normal {\n  font-weight: normal;\n}\n\n#ovbflbpmbc .gt_font_bold {\n  font-weight: bold;\n}\n\n#ovbflbpmbc .gt_font_italic {\n  font-style: italic;\n}\n\n#ovbflbpmbc .gt_super {\n  font-size: 65%;\n}\n\n#ovbflbpmbc .gt_footnote_marks {\n  font-size: 75%;\n  vertical-align: 0.4em;\n  position: initial;\n}\n\n#ovbflbpmbc .gt_asterisk {\n  font-size: 100%;\n  vertical-align: 0;\n}\n\n#ovbflbpmbc .gt_indent_1 {\n  text-indent: 5px;\n}\n\n#ovbflbpmbc .gt_indent_2 {\n  text-indent: 10px;\n}\n\n#ovbflbpmbc .gt_indent_3 {\n  text-indent: 15px;\n}\n\n#ovbflbpmbc .gt_indent_4 {\n  text-indent: 20px;\n}\n\n#ovbflbpmbc .gt_indent_5 {\n  text-indent: 25px;\n}\n\n#ovbflbpmbc .katex-display {\n  display: inline-flex !important;\n  margin-bottom: 0.75em !important;\n}\n\n#ovbflbpmbc div.Reactable > div.rt-table > div.rt-thead > div.rt-tr.rt-tr-group-header > div.rt-th-group:after {\n  height: 0px !important;\n}\n</style>\n<table class=\"gt_table\" data-quarto-disable-processing=\"false\" data-quarto-bootstrap=\"false\">\n  <thead>\n    <tr class=\"gt_col_headings\">\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_left\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"label\"><span data-qmd-base64=\"KipDaGFyYWN0ZXJpc3RpYyoq\"><span class='gt_from_md'><strong>Characteristic</strong></span></span></th>\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_center\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"estimate\"><span data-qmd-base64=\"KipPUioq\"><span class='gt_from_md'><strong>OR</strong></span></span></th>\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_center\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"conf.low\"><span data-qmd-base64=\"Kio5NSUgQ0kqKg==\"><span class='gt_from_md'><strong>95% CI</strong></span></span></th>\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_center\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"p.value\"><span data-qmd-base64=\"KipwLXZhbHVlKio=\"><span class='gt_from_md'><strong>p-value</strong></span></span></th>\n    </tr>\n  </thead>\n  <tbody class=\"gt_table_body\">\n    <tr><td headers=\"label\" class=\"gt_row gt_left\" style=\"font-weight: bold;\">fare in british pounds</td>\n<td headers=\"estimate\" class=\"gt_row gt_center\">1.91</td>\n<td headers=\"conf.low\" class=\"gt_row gt_center\">1.63, 2.26</td>\n<td headers=\"p.value\" class=\"gt_row gt_center\" style=\"font-weight: bold;\"><0.001</td></tr>\n  </tbody>\n  <tfoot class=\"gt_sourcenotes\">\n    <tr>\n      <td class=\"gt_sourcenote\" colspan=\"4\"><span data-qmd-base64=\"QWJicmV2aWF0aW9uczogQ0kgPSBDb25maWRlbmNlIEludGVydmFsLCBPUiA9IE9kZHMgUmF0aW8=\"><span class='gt_from_md'>Abbreviations: CI = Confidence Interval, OR = Odds Ratio</span></span></td>\n    </tr>\n  </tfoot>\n  \n</table>\n</div>\n```\n\n:::\n:::\n\n\n::::\n\n### Step 4: Compare Unstandardized vs. Standardized\n\n\n::: {.cell}\n\n```{.r .cell-code}\ntibble(\n  Model = c(\"Unstandardized (per 1 pound)\", \"Standardized (per 1 SD)\"),\n  OR = c(exp(coef(model_fare)[2]), exp(coef(model_z_fare)[2])),\n  CI_lower = c(exp(confint(model_fare)[2, 1]), exp(confint(model_z_fare)[2, 1])),\n  CI_upper = c(exp(confint(model_fare)[2, 2]), exp(confint(model_z_fare)[2, 2]))\n) |>\n  mutate(across(where(is.numeric), \\(x) round(x, 4))) |>\n  knitr::kable()\n```\n\n::: {.cell-output-display}\n\n\n|Model                        |     OR| CI_lower| CI_upper|\n|:----------------------------|------:|--------:|--------:|\n|Unstandardized (per 1 pound) | 1.0125|   1.0095|   1.0159|\n|Standardized (per 1 SD)      | 1.9051|   1.6295|   2.2572|\n\n\n:::\n:::\n\n\n> Now we can say: a one SD increase in fare (about 52 pounds) is associated with an odds ratio of roughly 1.91. That is much more interpretable than saying each single pound changes the odds by 1.25%.\n\n::: {.callout-important}\n## When to Standardize\nStandardize continuous predictors when the natural unit of measurement is awkward for interpretation (e.g., one pound, one year, one test point). The OR per 1 SD change gives a \"practical effect size\" that readers can understand without knowing the original scale.\n:::\n\n\n## Part 3: Predicted Probability Curves\n\nOne of the most informative ways to present logistic regression results is through **predicted probability plots**. These show the S-shaped curve that is the hallmark of logistic regression.\n\n### Step 1: The Quick Way with ggplot\n\n`ggplot2` can fit and display the logistic curve in a single call using `geom_smooth()`:\n\n\n::: {.cell}\n\n```{.r .cell-code}\nggplot(titanic, aes(x = fare, y = survived)) +\n  geom_jitter(height = 0.03, alpha = 0.15, size = 1, color = \"#2C3E50\") +\n  geom_smooth(method = \"glm\",\n              method.args = list(family = binomial),\n              color = \"#E74C3C\", linewidth = 1.2, se = TRUE) +\n  labs(x = \"Ticket Fare (British Pounds)\",\n       y = \"Predicted P(Survived)\",\n       title = \"Logistic Regression: Survival by Fare\",\n       subtitle = \"Shaded band shows the 95% confidence envelope\") +\n  scale_y_continuous(limits = c(0, 1))\n```\n\n::: {.cell-output-display}\n![Predicted probability of survival by fare (quick method)](lab10-logistic-extended_files/figure-html/quick-s-curve-1.png){fig-alt='S-shaped logistic curve with 95% confidence band showing predicted survival probability increasing with fare, with jittered binary outcomes' width=2100}\n:::\n:::\n\n\n> The gray shaded region is the 95% confidence band around the predicted probability. Notice how the band is narrower where we have more data (middle fare values) and wider at the extremes.\n\n### Step 2: The Manual Way (More Control)\n\nFor presentations or publications, you often want more control. The manual approach uses `predict()` with `type = \"response\"` to get predicted probabilities:\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Create a grid of fare values\nnew_data <- tibble(fare = seq(0, 300, length.out = 300))\n\n# Get predicted probabilities and confidence intervals\npreds <- predict(model_fare, newdata = new_data, type = \"link\", se.fit = TRUE)\n\nnew_data <- new_data |>\n  mutate(\n    prob    = plogis(preds$fit),\n    ci_low  = plogis(preds$fit - 1.96 * preds$se.fit),\n    ci_high = plogis(preds$fit + 1.96 * preds$se.fit)\n  )\n\nggplot() +\n  geom_jitter(data = titanic, aes(x = fare, y = survived),\n              height = 0.03, alpha = 0.15, size = 1, color = \"#2C3E50\") +\n  geom_ribbon(data = new_data, aes(x = fare, ymin = ci_low, ymax = ci_high),\n              fill = \"#E74C3C\", alpha = 0.2) +\n  geom_line(data = new_data, aes(x = fare, y = prob),\n            color = \"#E74C3C\", linewidth = 1.2) +\n  labs(x = \"Ticket Fare (British Pounds)\",\n       y = \"Predicted P(Survived)\",\n       title = \"Logistic Regression: Survival by Fare\",\n       subtitle = \"Manual predictions with 95% CI\") +\n  scale_y_continuous(limits = c(0, 1))\n```\n\n::: {.cell-output-display}\n![Predicted probability of survival by fare (manual method)](lab10-logistic-extended_files/figure-html/manual-s-curve-1.png){fig-alt='S-shaped logistic curve with shaded 95% confidence interval showing predicted survival probability increasing with fare, narrower in the data-rich middle range' width=2100}\n:::\n:::\n\n\n> We used `type = \"link\"` (log-odds scale) for the predictions, then applied `plogis()` to convert to probabilities. The key trick is to compute the CI on the log-odds scale first, then transform --- this ensures the CI stays within [0, 1].\n\n### Step 3: Interpreting the S-Curve\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Predicted probabilities at specific fare values\ncheck_fares <- tibble(fare = c(10, 30, 50, 100, 200))\n\ncheck_fares <- check_fares |>\n  mutate(\n    predicted_prob = predict(model_fare, newdata = check_fares, type = \"response\")\n  ) |>\n  mutate(predicted_prob = round(predicted_prob, 3))\n\nknitr::kable(check_fares, col.names = c(\"Fare (pounds)\", \"P(Survived)\"))\n```\n\n::: {.cell-output-display}\n\n\n| Fare (pounds)| P(Survived)|\n|-------------:|-----------:|\n|            10|       0.319|\n|            30|       0.375|\n|            50|       0.435|\n|           100|       0.590|\n|           200|       0.833|\n\n\n:::\n:::\n\n\n> The predicted probability of survival increases with fare, but not linearly. At low fares, the probability is relatively flat and low. In the middle range, it climbs steeply. At high fares, it levels off again. This S-shape is the **logistic function** in action.\n\n::: {.callout-tip}\n## The Logistic (Sigmoid) Function\nThe S-curve is described by the logistic function:\n\n$$P(Y = 1) = \\frac{1}{1 + e^{-(b_0 + b_1 X)}}$$\n\nAt the middle of the curve, small changes in $X$ produce large changes in probability. At the extremes (very high or very low $X$), changes in $X$ have little effect on the predicted probability. This is why logistic regression is better than linear regression for binary outcomes --- it naturally captures this ceiling and floor behavior.\n:::\n\n\n## Part 4: Categorical Predictors with 3+ Levels\n\nSo far we have worked with a binary predictor (`female`) and a continuous predictor (`fare`). Now let's tackle a categorical predictor with **three levels**: passenger class (`pclass`), coded 1, 2, or 3.\n\n### Step 1: Prepare the Variable\n\nThe `pclass` variable is numeric (1, 2, 3), so we need to tell R to treat it as a factor:\n\n\n::: {.cell}\n\n```{.r .cell-code}\ntitanic <- titanic |>\n  mutate(pclass_f = factor(pclass, labels = c(\"1st\", \"2nd\", \"3rd\")))\n\ntitanic |>\n  count(pclass_f, survived) |>\n  group_by(pclass_f) |>\n  mutate(prop = round(n / sum(n), 3)) |>\n  filter(survived == 1) |>\n  select(pclass_f, n_survived = n, survival_rate = prop)\n```\n\n::: {.cell-output-display}\n<div class=\"kable-table\">\n\n|pclass_f | n_survived| survival_rate|\n|:--------|----------:|-------------:|\n|1st      |        200|         0.619|\n|2nd      |        119|         0.430|\n|3rd      |        181|         0.255|\n\n</div>\n:::\n:::\n\n\n> First class passengers had the highest survival rate and third class the lowest --- a pattern that reflects both cabin location and social privilege.\n\n### Step 2: Fit the Model\n\n\n::: {.cell}\n\n```{.r .cell-code}\nmodel_pclass <- glm(survived ~ pclass_f, data = titanic, family = binomial)\n```\n:::\n\n\n:::: {.panel-tabset}\n\n#### Simple\n\n\n::: {.cell}\n\n```{.r .cell-code}\nsummary(model_pclass)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\nCall:\nglm(formula = survived ~ pclass_f, family = binomial, data = titanic)\n\nCoefficients:\n            Estimate Std. Error z value Pr(>|z|)    \n(Intercept)   0.4861     0.1146   4.242 2.21e-05 ***\npclass_f2nd  -0.7696     0.1669  -4.611 4.02e-06 ***\npclass_f3rd  -1.5567     0.1433 -10.860  < 2e-16 ***\n---\nSignif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1\n\n(Dispersion parameter for binomial family taken to be 1)\n\n    Null deviance: 1741.0  on 1308  degrees of freedom\nResidual deviance: 1613.3  on 1306  degrees of freedom\nAIC: 1619.3\n\nNumber of Fisher Scoring iterations: 4\n```\n\n\n:::\n:::\n\n\n#### Advanced\n\n\n::: {.cell}\n\n```{.r .cell-code}\nmodel_pclass |>\n  tbl_regression(exponentiate = TRUE) |>\n  bold_labels() |>\n  bold_p(t = 0.05)\n```\n\n::: {.cell-output-display}\n\n```{=html}\n<div id=\"lapxunyhql\" style=\"padding-left:0px;padding-right:0px;padding-top:10px;padding-bottom:10px;overflow-x:auto;overflow-y:auto;width:auto;height:auto;\">\n<style>#lapxunyhql table {\n  font-family: system-ui, 'Segoe UI', Roboto, Helvetica, Arial, sans-serif, 'Apple Color Emoji', 'Segoe UI Emoji', 'Segoe UI Symbol', 'Noto Color Emoji';\n  -webkit-font-smoothing: antialiased;\n  -moz-osx-font-smoothing: grayscale;\n}\n\n#lapxunyhql thead, #lapxunyhql tbody, #lapxunyhql tfoot, #lapxunyhql tr, #lapxunyhql td, #lapxunyhql th {\n  border-style: none;\n}\n\n#lapxunyhql p {\n  margin: 0;\n  padding: 0;\n}\n\n#lapxunyhql .gt_table {\n  display: table;\n  border-collapse: collapse;\n  line-height: normal;\n  margin-left: auto;\n  margin-right: auto;\n  color: #333333;\n  font-size: 16px;\n  font-weight: normal;\n  font-style: normal;\n  background-color: #FFFFFF;\n  width: auto;\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #A8A8A8;\n  border-right-style: none;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #A8A8A8;\n  border-left-style: none;\n  border-left-width: 2px;\n  border-left-color: #D3D3D3;\n}\n\n#lapxunyhql .gt_caption {\n  padding-top: 4px;\n  padding-bottom: 4px;\n}\n\n#lapxunyhql .gt_title {\n  color: #333333;\n  font-size: 125%;\n  font-weight: initial;\n  padding-top: 4px;\n  padding-bottom: 4px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-bottom-color: #FFFFFF;\n  border-bottom-width: 0;\n}\n\n#lapxunyhql .gt_subtitle {\n  color: #333333;\n  font-size: 85%;\n  font-weight: initial;\n  padding-top: 3px;\n  padding-bottom: 5px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-top-color: #FFFFFF;\n  border-top-width: 0;\n}\n\n#lapxunyhql .gt_heading {\n  background-color: #FFFFFF;\n  text-align: center;\n  border-bottom-color: #FFFFFF;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n}\n\n#lapxunyhql .gt_bottom_border {\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n}\n\n#lapxunyhql .gt_col_headings {\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n}\n\n#lapxunyhql .gt_col_heading {\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: normal;\n  text-transform: inherit;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n  vertical-align: bottom;\n  padding-top: 5px;\n  padding-bottom: 6px;\n  padding-left: 5px;\n  padding-right: 5px;\n  overflow-x: hidden;\n}\n\n#lapxunyhql .gt_column_spanner_outer {\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: normal;\n  text-transform: inherit;\n  padding-top: 0;\n  padding-bottom: 0;\n  padding-left: 4px;\n  padding-right: 4px;\n}\n\n#lapxunyhql .gt_column_spanner_outer:first-child {\n  padding-left: 0;\n}\n\n#lapxunyhql .gt_column_spanner_outer:last-child {\n  padding-right: 0;\n}\n\n#lapxunyhql .gt_column_spanner {\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  vertical-align: bottom;\n  padding-top: 5px;\n  padding-bottom: 5px;\n  overflow-x: hidden;\n  display: inline-block;\n  width: 100%;\n}\n\n#lapxunyhql .gt_spanner_row {\n  border-bottom-style: hidden;\n}\n\n#lapxunyhql .gt_group_heading {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: initial;\n  text-transform: inherit;\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n  vertical-align: middle;\n  text-align: left;\n}\n\n#lapxunyhql .gt_empty_group_heading {\n  padding: 0.5px;\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: initial;\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  vertical-align: middle;\n}\n\n#lapxunyhql .gt_from_md > :first-child {\n  margin-top: 0;\n}\n\n#lapxunyhql .gt_from_md > :last-child {\n  margin-bottom: 0;\n}\n\n#lapxunyhql .gt_row {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  margin: 10px;\n  border-top-style: solid;\n  border-top-width: 1px;\n  border-top-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n  vertical-align: middle;\n  overflow-x: hidden;\n}\n\n#lapxunyhql .gt_stub {\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: initial;\n  text-transform: inherit;\n  border-right-style: solid;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#lapxunyhql .gt_stub_row_group {\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: initial;\n  text-transform: inherit;\n  border-right-style: solid;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n  padding-left: 5px;\n  padding-right: 5px;\n  vertical-align: top;\n}\n\n#lapxunyhql .gt_row_group_first td {\n  border-top-width: 2px;\n}\n\n#lapxunyhql .gt_row_group_first th {\n  border-top-width: 2px;\n}\n\n#lapxunyhql .gt_summary_row {\n  color: #333333;\n  background-color: #FFFFFF;\n  text-transform: inherit;\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#lapxunyhql .gt_first_summary_row {\n  border-top-style: solid;\n  border-top-color: #D3D3D3;\n}\n\n#lapxunyhql .gt_first_summary_row.thick {\n  border-top-width: 2px;\n}\n\n#lapxunyhql .gt_last_summary_row {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n}\n\n#lapxunyhql .gt_grand_summary_row {\n  color: #333333;\n  background-color: #FFFFFF;\n  text-transform: inherit;\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#lapxunyhql .gt_first_grand_summary_row {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-top-style: double;\n  border-top-width: 6px;\n  border-top-color: #D3D3D3;\n}\n\n#lapxunyhql .gt_last_grand_summary_row_top {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-bottom-style: double;\n  border-bottom-width: 6px;\n  border-bottom-color: #D3D3D3;\n}\n\n#lapxunyhql .gt_striped {\n  background-color: rgba(128, 128, 128, 0.05);\n}\n\n#lapxunyhql .gt_table_body {\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n}\n\n#lapxunyhql .gt_footnotes {\n  color: #333333;\n  background-color: #FFFFFF;\n  border-bottom-style: none;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 2px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n}\n\n#lapxunyhql .gt_footnote {\n  margin: 0px;\n  font-size: 90%;\n  padding-top: 4px;\n  padding-bottom: 4px;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#lapxunyhql .gt_sourcenotes {\n  color: #333333;\n  background-color: #FFFFFF;\n  border-bottom-style: none;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 2px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n}\n\n#lapxunyhql .gt_sourcenote {\n  font-size: 90%;\n  padding-top: 4px;\n  padding-bottom: 4px;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#lapxunyhql .gt_left {\n  text-align: left;\n}\n\n#lapxunyhql .gt_center {\n  text-align: center;\n}\n\n#lapxunyhql .gt_right {\n  text-align: right;\n  font-variant-numeric: tabular-nums;\n}\n\n#lapxunyhql .gt_font_normal {\n  font-weight: normal;\n}\n\n#lapxunyhql .gt_font_bold {\n  font-weight: bold;\n}\n\n#lapxunyhql .gt_font_italic {\n  font-style: italic;\n}\n\n#lapxunyhql .gt_super {\n  font-size: 65%;\n}\n\n#lapxunyhql .gt_footnote_marks {\n  font-size: 75%;\n  vertical-align: 0.4em;\n  position: initial;\n}\n\n#lapxunyhql .gt_asterisk {\n  font-size: 100%;\n  vertical-align: 0;\n}\n\n#lapxunyhql .gt_indent_1 {\n  text-indent: 5px;\n}\n\n#lapxunyhql .gt_indent_2 {\n  text-indent: 10px;\n}\n\n#lapxunyhql .gt_indent_3 {\n  text-indent: 15px;\n}\n\n#lapxunyhql .gt_indent_4 {\n  text-indent: 20px;\n}\n\n#lapxunyhql .gt_indent_5 {\n  text-indent: 25px;\n}\n\n#lapxunyhql .katex-display {\n  display: inline-flex !important;\n  margin-bottom: 0.75em !important;\n}\n\n#lapxunyhql div.Reactable > div.rt-table > div.rt-thead > div.rt-tr.rt-tr-group-header > div.rt-th-group:after {\n  height: 0px !important;\n}\n</style>\n<table class=\"gt_table\" data-quarto-disable-processing=\"false\" data-quarto-bootstrap=\"false\">\n  <thead>\n    <tr class=\"gt_col_headings\">\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_left\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"label\"><span data-qmd-base64=\"KipDaGFyYWN0ZXJpc3RpYyoq\"><span class='gt_from_md'><strong>Characteristic</strong></span></span></th>\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_center\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"estimate\"><span data-qmd-base64=\"KipPUioq\"><span class='gt_from_md'><strong>OR</strong></span></span></th>\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_center\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"conf.low\"><span data-qmd-base64=\"Kio5NSUgQ0kqKg==\"><span class='gt_from_md'><strong>95% CI</strong></span></span></th>\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_center\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"p.value\"><span data-qmd-base64=\"KipwLXZhbHVlKio=\"><span class='gt_from_md'><strong>p-value</strong></span></span></th>\n    </tr>\n  </thead>\n  <tbody class=\"gt_table_body\">\n    <tr><td headers=\"label\" class=\"gt_row gt_left\" style=\"font-weight: bold;\">pclass_f</td>\n<td headers=\"estimate\" class=\"gt_row gt_center\"><br /></td>\n<td headers=\"conf.low\" class=\"gt_row gt_center\"><br /></td>\n<td headers=\"p.value\" class=\"gt_row gt_center\"><br /></td></tr>\n    <tr><td headers=\"label\" class=\"gt_row gt_left\">    1st</td>\n<td headers=\"estimate\" class=\"gt_row gt_center\">—</td>\n<td headers=\"conf.low\" class=\"gt_row gt_center\">—</td>\n<td headers=\"p.value\" class=\"gt_row gt_center\"><br /></td></tr>\n    <tr><td headers=\"label\" class=\"gt_row gt_left\">    2nd</td>\n<td headers=\"estimate\" class=\"gt_row gt_center\">0.46</td>\n<td headers=\"conf.low\" class=\"gt_row gt_center\">0.33, 0.64</td>\n<td headers=\"p.value\" class=\"gt_row gt_center\" style=\"font-weight: bold;\"><0.001</td></tr>\n    <tr><td headers=\"label\" class=\"gt_row gt_left\">    3rd</td>\n<td headers=\"estimate\" class=\"gt_row gt_center\">0.21</td>\n<td headers=\"conf.low\" class=\"gt_row gt_center\">0.16, 0.28</td>\n<td headers=\"p.value\" class=\"gt_row gt_center\" style=\"font-weight: bold;\"><0.001</td></tr>\n  </tbody>\n  <tfoot class=\"gt_sourcenotes\">\n    <tr>\n      <td class=\"gt_sourcenote\" colspan=\"4\"><span data-qmd-base64=\"QWJicmV2aWF0aW9uczogQ0kgPSBDb25maWRlbmNlIEludGVydmFsLCBPUiA9IE9kZHMgUmF0aW8=\"><span class='gt_from_md'>Abbreviations: CI = Confidence Interval, OR = Odds Ratio</span></span></td>\n    </tr>\n  </tfoot>\n  \n</table>\n</div>\n```\n\n:::\n:::\n\n\n::::\n\n### Step 3: Interpret the Coefficients\n\nWith a three-level factor, R creates two dummy variables: `pclass_f2nd` and `pclass_f3rd`. The reference category is **1st class** (the first level of the factor).\n\n\n::: {.cell}\n\n```{.r .cell-code}\nexp(coef(model_pclass))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n(Intercept) pclass_f2nd pclass_f3rd \n  1.6260163   0.4631962   0.2108239 \n```\n\n\n:::\n\n```{.r .cell-code}\nexp(confint(model_pclass))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n                2.5 %    97.5 %\n(Intercept) 1.3012373 2.0400409\npclass_f2nd 0.3333370 0.6415244\npclass_f3rd 0.1588234 0.2786634\n```\n\n\n:::\n:::\n\n\n> - **2nd class vs. 1st class:** The OR of 0.46 means that 2nd class passengers had about 46% of the odds of surviving compared to 1st class passengers.\n> - **3rd class vs. 1st class:** The OR of 0.21 is even lower. Third class passengers had much lower odds of survival than first class.\n\nBoth comparisons use 1st class as the baseline. But what if we want 3rd class as the reference instead?\n\n### Step 4: Change the Reference Group\n\nUse `relevel()` to change which category serves as the reference:\n\n\n::: {.cell}\n\n```{.r .cell-code}\ntitanic <- titanic |>\n  mutate(pclass_f = relevel(pclass_f, ref = \"3rd\"))\n\nmodel_pclass_ref3 <- glm(survived ~ pclass_f, data = titanic, family = binomial)\n```\n:::\n\n\n::: {.callout-note}\nNote that `relevel()` permanently changes the factor levels in the data. If you re-run earlier code chunks after this point, the reference group will be different.\n:::\n\n:::: {.panel-tabset}\n\n#### Simple\n\n\n::: {.cell}\n\n```{.r .cell-code}\nsummary(model_pclass_ref3)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\nCall:\nglm(formula = survived ~ pclass_f, family = binomial, data = titanic)\n\nCoefficients:\n            Estimate Std. Error z value Pr(>|z|)    \n(Intercept) -1.07060    0.08613 -12.430  < 2e-16 ***\npclass_f1st  1.55673    0.14335  10.860  < 2e-16 ***\npclass_f2nd  0.78713    0.14883   5.289 1.23e-07 ***\n---\nSignif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1\n\n(Dispersion parameter for binomial family taken to be 1)\n\n    Null deviance: 1741.0  on 1308  degrees of freedom\nResidual deviance: 1613.3  on 1306  degrees of freedom\nAIC: 1619.3\n\nNumber of Fisher Scoring iterations: 4\n```\n\n\n:::\n:::\n\n\n#### Advanced\n\n\n::: {.cell}\n\n```{.r .cell-code}\nmodel_pclass_ref3 |>\n  tbl_regression(exponentiate = TRUE) |>\n  bold_labels() |>\n  bold_p(t = 0.05)\n```\n\n::: {.cell-output-display}\n\n```{=html}\n<div id=\"tmhezhbgjh\" style=\"padding-left:0px;padding-right:0px;padding-top:10px;padding-bottom:10px;overflow-x:auto;overflow-y:auto;width:auto;height:auto;\">\n<style>#tmhezhbgjh table {\n  font-family: system-ui, 'Segoe UI', Roboto, Helvetica, Arial, sans-serif, 'Apple Color Emoji', 'Segoe UI Emoji', 'Segoe UI Symbol', 'Noto Color Emoji';\n  -webkit-font-smoothing: antialiased;\n  -moz-osx-font-smoothing: grayscale;\n}\n\n#tmhezhbgjh thead, #tmhezhbgjh tbody, #tmhezhbgjh tfoot, #tmhezhbgjh tr, #tmhezhbgjh td, #tmhezhbgjh th {\n  border-style: none;\n}\n\n#tmhezhbgjh p {\n  margin: 0;\n  padding: 0;\n}\n\n#tmhezhbgjh .gt_table {\n  display: table;\n  border-collapse: collapse;\n  line-height: normal;\n  margin-left: auto;\n  margin-right: auto;\n  color: #333333;\n  font-size: 16px;\n  font-weight: normal;\n  font-style: normal;\n  background-color: #FFFFFF;\n  width: auto;\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #A8A8A8;\n  border-right-style: none;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #A8A8A8;\n  border-left-style: none;\n  border-left-width: 2px;\n  border-left-color: #D3D3D3;\n}\n\n#tmhezhbgjh .gt_caption {\n  padding-top: 4px;\n  padding-bottom: 4px;\n}\n\n#tmhezhbgjh .gt_title {\n  color: #333333;\n  font-size: 125%;\n  font-weight: initial;\n  padding-top: 4px;\n  padding-bottom: 4px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-bottom-color: #FFFFFF;\n  border-bottom-width: 0;\n}\n\n#tmhezhbgjh .gt_subtitle {\n  color: #333333;\n  font-size: 85%;\n  font-weight: initial;\n  padding-top: 3px;\n  padding-bottom: 5px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-top-color: #FFFFFF;\n  border-top-width: 0;\n}\n\n#tmhezhbgjh .gt_heading {\n  background-color: #FFFFFF;\n  text-align: center;\n  border-bottom-color: #FFFFFF;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n}\n\n#tmhezhbgjh .gt_bottom_border {\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n}\n\n#tmhezhbgjh .gt_col_headings {\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n}\n\n#tmhezhbgjh .gt_col_heading {\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: normal;\n  text-transform: inherit;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n  vertical-align: bottom;\n  padding-top: 5px;\n  padding-bottom: 6px;\n  padding-left: 5px;\n  padding-right: 5px;\n  overflow-x: hidden;\n}\n\n#tmhezhbgjh .gt_column_spanner_outer {\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: normal;\n  text-transform: inherit;\n  padding-top: 0;\n  padding-bottom: 0;\n  padding-left: 4px;\n  padding-right: 4px;\n}\n\n#tmhezhbgjh .gt_column_spanner_outer:first-child {\n  padding-left: 0;\n}\n\n#tmhezhbgjh .gt_column_spanner_outer:last-child {\n  padding-right: 0;\n}\n\n#tmhezhbgjh .gt_column_spanner {\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  vertical-align: bottom;\n  padding-top: 5px;\n  padding-bottom: 5px;\n  overflow-x: hidden;\n  display: inline-block;\n  width: 100%;\n}\n\n#tmhezhbgjh .gt_spanner_row {\n  border-bottom-style: hidden;\n}\n\n#tmhezhbgjh .gt_group_heading {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: initial;\n  text-transform: inherit;\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n  vertical-align: middle;\n  text-align: left;\n}\n\n#tmhezhbgjh .gt_empty_group_heading {\n  padding: 0.5px;\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: initial;\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  vertical-align: middle;\n}\n\n#tmhezhbgjh .gt_from_md > :first-child {\n  margin-top: 0;\n}\n\n#tmhezhbgjh .gt_from_md > :last-child {\n  margin-bottom: 0;\n}\n\n#tmhezhbgjh .gt_row {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  margin: 10px;\n  border-top-style: solid;\n  border-top-width: 1px;\n  border-top-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n  vertical-align: middle;\n  overflow-x: hidden;\n}\n\n#tmhezhbgjh .gt_stub {\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: initial;\n  text-transform: inherit;\n  border-right-style: solid;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#tmhezhbgjh .gt_stub_row_group {\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: initial;\n  text-transform: inherit;\n  border-right-style: solid;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n  padding-left: 5px;\n  padding-right: 5px;\n  vertical-align: top;\n}\n\n#tmhezhbgjh .gt_row_group_first td {\n  border-top-width: 2px;\n}\n\n#tmhezhbgjh .gt_row_group_first th {\n  border-top-width: 2px;\n}\n\n#tmhezhbgjh .gt_summary_row {\n  color: #333333;\n  background-color: #FFFFFF;\n  text-transform: inherit;\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#tmhezhbgjh .gt_first_summary_row {\n  border-top-style: solid;\n  border-top-color: #D3D3D3;\n}\n\n#tmhezhbgjh .gt_first_summary_row.thick {\n  border-top-width: 2px;\n}\n\n#tmhezhbgjh .gt_last_summary_row {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n}\n\n#tmhezhbgjh .gt_grand_summary_row {\n  color: #333333;\n  background-color: #FFFFFF;\n  text-transform: inherit;\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#tmhezhbgjh .gt_first_grand_summary_row {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-top-style: double;\n  border-top-width: 6px;\n  border-top-color: #D3D3D3;\n}\n\n#tmhezhbgjh .gt_last_grand_summary_row_top {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-bottom-style: double;\n  border-bottom-width: 6px;\n  border-bottom-color: #D3D3D3;\n}\n\n#tmhezhbgjh .gt_striped {\n  background-color: rgba(128, 128, 128, 0.05);\n}\n\n#tmhezhbgjh .gt_table_body {\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n}\n\n#tmhezhbgjh .gt_footnotes {\n  color: #333333;\n  background-color: #FFFFFF;\n  border-bottom-style: none;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 2px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n}\n\n#tmhezhbgjh .gt_footnote {\n  margin: 0px;\n  font-size: 90%;\n  padding-top: 4px;\n  padding-bottom: 4px;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#tmhezhbgjh .gt_sourcenotes {\n  color: #333333;\n  background-color: #FFFFFF;\n  border-bottom-style: none;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 2px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n}\n\n#tmhezhbgjh .gt_sourcenote {\n  font-size: 90%;\n  padding-top: 4px;\n  padding-bottom: 4px;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#tmhezhbgjh .gt_left {\n  text-align: left;\n}\n\n#tmhezhbgjh .gt_center {\n  text-align: center;\n}\n\n#tmhezhbgjh .gt_right {\n  text-align: right;\n  font-variant-numeric: tabular-nums;\n}\n\n#tmhezhbgjh .gt_font_normal {\n  font-weight: normal;\n}\n\n#tmhezhbgjh .gt_font_bold {\n  font-weight: bold;\n}\n\n#tmhezhbgjh .gt_font_italic {\n  font-style: italic;\n}\n\n#tmhezhbgjh .gt_super {\n  font-size: 65%;\n}\n\n#tmhezhbgjh .gt_footnote_marks {\n  font-size: 75%;\n  vertical-align: 0.4em;\n  position: initial;\n}\n\n#tmhezhbgjh .gt_asterisk {\n  font-size: 100%;\n  vertical-align: 0;\n}\n\n#tmhezhbgjh .gt_indent_1 {\n  text-indent: 5px;\n}\n\n#tmhezhbgjh .gt_indent_2 {\n  text-indent: 10px;\n}\n\n#tmhezhbgjh .gt_indent_3 {\n  text-indent: 15px;\n}\n\n#tmhezhbgjh .gt_indent_4 {\n  text-indent: 20px;\n}\n\n#tmhezhbgjh .gt_indent_5 {\n  text-indent: 25px;\n}\n\n#tmhezhbgjh .katex-display {\n  display: inline-flex !important;\n  margin-bottom: 0.75em !important;\n}\n\n#tmhezhbgjh div.Reactable > div.rt-table > div.rt-thead > div.rt-tr.rt-tr-group-header > div.rt-th-group:after {\n  height: 0px !important;\n}\n</style>\n<table class=\"gt_table\" data-quarto-disable-processing=\"false\" data-quarto-bootstrap=\"false\">\n  <thead>\n    <tr class=\"gt_col_headings\">\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_left\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"label\"><span data-qmd-base64=\"KipDaGFyYWN0ZXJpc3RpYyoq\"><span class='gt_from_md'><strong>Characteristic</strong></span></span></th>\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_center\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"estimate\"><span data-qmd-base64=\"KipPUioq\"><span class='gt_from_md'><strong>OR</strong></span></span></th>\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_center\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"conf.low\"><span data-qmd-base64=\"Kio5NSUgQ0kqKg==\"><span class='gt_from_md'><strong>95% CI</strong></span></span></th>\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_center\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"p.value\"><span data-qmd-base64=\"KipwLXZhbHVlKio=\"><span class='gt_from_md'><strong>p-value</strong></span></span></th>\n    </tr>\n  </thead>\n  <tbody class=\"gt_table_body\">\n    <tr><td headers=\"label\" class=\"gt_row gt_left\" style=\"font-weight: bold;\">pclass_f</td>\n<td headers=\"estimate\" class=\"gt_row gt_center\"><br /></td>\n<td headers=\"conf.low\" class=\"gt_row gt_center\"><br /></td>\n<td headers=\"p.value\" class=\"gt_row gt_center\"><br /></td></tr>\n    <tr><td headers=\"label\" class=\"gt_row gt_left\">    3rd</td>\n<td headers=\"estimate\" class=\"gt_row gt_center\">—</td>\n<td headers=\"conf.low\" class=\"gt_row gt_center\">—</td>\n<td headers=\"p.value\" class=\"gt_row gt_center\"><br /></td></tr>\n    <tr><td headers=\"label\" class=\"gt_row gt_left\">    1st</td>\n<td headers=\"estimate\" class=\"gt_row gt_center\">4.74</td>\n<td headers=\"conf.low\" class=\"gt_row gt_center\">3.59, 6.30</td>\n<td headers=\"p.value\" class=\"gt_row gt_center\" style=\"font-weight: bold;\"><0.001</td></tr>\n    <tr><td headers=\"label\" class=\"gt_row gt_left\">    2nd</td>\n<td headers=\"estimate\" class=\"gt_row gt_center\">2.20</td>\n<td headers=\"conf.low\" class=\"gt_row gt_center\">1.64, 2.94</td>\n<td headers=\"p.value\" class=\"gt_row gt_center\" style=\"font-weight: bold;\"><0.001</td></tr>\n  </tbody>\n  <tfoot class=\"gt_sourcenotes\">\n    <tr>\n      <td class=\"gt_sourcenote\" colspan=\"4\"><span data-qmd-base64=\"QWJicmV2aWF0aW9uczogQ0kgPSBDb25maWRlbmNlIEludGVydmFsLCBPUiA9IE9kZHMgUmF0aW8=\"><span class='gt_from_md'>Abbreviations: CI = Confidence Interval, OR = Odds Ratio</span></span></td>\n    </tr>\n  </tfoot>\n  \n</table>\n</div>\n```\n\n:::\n:::\n\n\n::::\n\n\n::: {.cell}\n\n```{.r .cell-code}\nexp(coef(model_pclass_ref3))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n(Intercept) pclass_f1st pclass_f2nd \n   0.342803    4.743296    2.197077 \n```\n\n\n:::\n\n```{.r .cell-code}\nexp(confint(model_pclass_ref3))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n                2.5 %   97.5 %\n(Intercept) 0.2888481 0.404945\npclass_f1st 3.5885592 6.296300\npclass_f2nd 1.6406894 2.941509\n```\n\n\n:::\n:::\n\n\n> Now the comparisons are flipped. The OR for 1st class vs. 3rd class is the reciprocal of what we saw before. Both models fit the data identically --- only the parameterization (which group is the baseline) changes.\n\n::: {.callout-tip}\n## Choosing a Reference Group\nThere is no single \"correct\" reference group. Choose the one that makes your research question easiest to answer:\n\n- If you want to compare other classes **against the most privileged** group, use 1st class as reference.\n- If you want to compare other classes **against the least privileged** group, use 3rd class as reference.\n- The model fit statistics (deviance, AIC) are identical regardless of your choice.\n:::\n\n### Step 5: Pairwise Comparisons with emmeans\n\nChanging the reference group only gives us comparisons against one baseline at a time. What if we want **all pairwise comparisons** (1st vs. 2nd, 1st vs. 3rd, 2nd vs. 3rd) simultaneously? The `emmeans` package makes this easy:\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Estimated marginal means on the response (probability) scale\nem <- emmeans(model_pclass_ref3, ~ pclass_f, type = \"response\")\nem\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n pclass_f  prob     SE  df asymp.LCL asymp.UCL\n 3rd      0.255 0.0164 Inf     0.225     0.289\n 1st      0.619 0.0270 Inf     0.565     0.671\n 2nd      0.430 0.0297 Inf     0.373     0.489\n\nConfidence level used: 0.95 \nIntervals are back-transformed from the logit scale \n```\n\n\n:::\n:::\n\n\n> These are the model-predicted survival probabilities for each class --- they match the observed proportions exactly (as they should, since `pclass_f` is the only predictor).\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Pairwise comparisons on the odds ratio scale\npairs(em, type = \"response\", reverse = TRUE)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n contrast  odds.ratio     SE  df null z.ratio p.value\n 1st / 3rd      4.743 0.6800 Inf    1  10.860  <.0001\n 2nd / 3rd      2.197 0.3270 Inf    1   5.289  <.0001\n 2nd / 1st      0.463 0.0773 Inf    1  -4.611  <.0001\n\nP value adjustment: tukey method for comparing a family of 3 estimates \nTests are performed on the log odds ratio scale \n```\n\n\n:::\n:::\n\n\n> Now we see all three pairwise odds ratios at once: 1st vs. 2nd, 1st vs. 3rd, and 2nd vs. 3rd. The `reverse = TRUE` option puts the higher-survival group in the numerator, so all ORs are greater than 1. Notice that the p-values are adjusted for multiple comparisons (Tukey method by default).\n\n\n::: {.cell}\n\n```{.r .cell-code}\nem_df <- as.data.frame(em)\n\nggplot(em_df, aes(x = pclass_f, y = prob)) +\n  geom_point(size = 4, color = \"#E74C3C\") +\n  geom_errorbar(aes(ymin = asymp.LCL, ymax = asymp.UCL),\n                width = 0.15, linewidth = 1, color = \"#E74C3C\") +\n  labs(x = \"Passenger Class\",\n       y = \"Predicted P(Survived)\",\n       title = \"Survival Probability by Passenger Class\",\n       subtitle = \"Error bars show 95% confidence intervals\") +\n  scale_y_continuous(limits = c(0, 1), labels = scales::percent)\n```\n\n::: {.cell-output-display}\n![Estimated survival probabilities by passenger class with 95% CIs](lab10-logistic-extended_files/figure-html/pairwise-plot-1.png){fig-alt='Point-and-error-bar plot showing estimated survival probabilities decreasing from 1st class (about 63%) to 2nd class (about 47%) to 3rd class (about 24%) with non-overlapping 95% confidence intervals' width=2100}\n:::\n:::\n\n\n> The plot makes the survival gradient crystal clear. First class passengers had roughly a 63% chance of surviving, while third class passengers had only about 24%. The non-overlapping confidence intervals confirm these differences are statistically significant.\n\n\n## Key Takeaways\n\n::: {.callout-note}\n## What We Learned\n\n1. **Confidence intervals for odds ratios:** Always report CIs alongside point estimates. Use `exp(confint(model))` for profile-likelihood CIs or `exp(coef +/- 1.96 * SE)` for Wald CIs.\n\n2. **Standardizing continuous predictors:** When the natural unit is awkward (e.g., one pound of fare), standardize the predictor so the OR describes a one SD change. This gives a practical effect size that is easier to communicate.\n\n3. **Predicted probability curves:** The S-shaped logistic curve is the best way to communicate how a continuous predictor relates to a binary outcome. Use `geom_smooth(method = \"glm\")` for quick plots or `predict(type = \"response\")` for full control.\n\n4. **Categorical predictors with 3+ levels:** Convert to a factor, and R creates dummy variables automatically. The first level is the reference group by default. Use `relevel()` to change the reference.\n\n5. **Pairwise comparisons:** `emmeans` computes all pairwise odds ratios with appropriate multiple-comparison adjustments, so you are not limited to comparisons against a single reference group.\n:::\n",
    "supporting": [
      "lab10-logistic-extended_files"
    ],
    "filters": [
      "rmarkdown/pagebreak.lua"
    ],
    "includes": {},
    "engineDependencies": {},
    "preserve": {},
    "postProcess": true
  }
}