{
  "hash": "af4eed9ed68d7d22702d4dc86fd9997b",
  "result": {
    "engine": "knitr",
    "markdown": "---\ntitle: \"Lab 2: Simple Linear Regression\"\n---\n\n\n\n\n::: {.objectives}\n## What You'll Learn in This Lab\n\n- Prepare a clean analysis dataset without overwriting the raw data\n- Fit a simple linear regression model with `lm()`\n- Inspect coefficients with `model_params()`\n- Inspect model fit with `model_fit()` and `performance::r2()`\n- Use the model to make simple predictions\n- Compute fitted values and residuals with minimal code\n- Use `performance::check_model()` for a quick visual diagnostic panel\n- **Lecture Notes Reference:** Chapter 1: *Simple Linear Regression*\n\n::: {.meta}\nDataset: `instruction`. Estimated time: 75-90 minutes.\n:::\n:::\n\n\n## Part 1: Data Preparation\n\nIn Lab 1, we learned the basic R workflow: load data, inspect it, create a clean working dataset, and then analyze. We will use the same pattern here.\n\n### Step 1: Load the Data\n\nThe course setup has already loaded the packages we need. The first code you run is the data-loading code:\n\n\n::: {.cell}\n\n```{.r .cell-code}\ndata(instruction)\ninstruction_raw <- instruction\n```\n:::\n\n\nWe keep the original dataset in `instruction_raw`. All changes for analysis will go into a separate object.\n\n### Step 2: Create a Clean Working Dataset\n\nFor readable tables and plots, we will rename `girl` to `female`, add labeled group variables, and create a first-grade math score.\n\n\n::: {.cell}\n\n```{.r .cell-code}\ninstruction_clean <- instruction_raw |>\n  rename(female = girl) |>\n  mutate(\n    gender = factor(female,\n                    levels = c(0, 1),\n                    labels = c(\"Male\", \"Female\")),\n    minority_group = factor(minority,\n                            levels = c(0, 1),\n                            labels = c(\"Non-minority\", \"Minority\")),\n    newteach = if_else(yearstea < 5, 1, 0),\n    mathfirst = mathkind + mathgain\n  )\n```\n:::\n\n\n> `instruction_clean` is the dataset we will use for analysis. `instruction_raw` remains unchanged.\n\n### Step 3: Focus on One School\n\nTo learn the mechanics of simple regression, we will start with a small subset: students in School 11.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nschool11 <- instruction_clean |>\n  filter(schoolid == 11)\n\ntibble(\n  students = nrow(school11),\n  classrooms = n_distinct(school11$classid)\n)\n```\n\n::: {.cell-output-display}\n<div class=\"kable-table\">\n\n| students| classrooms|\n|--------:|----------:|\n|       31|          9|\n\n</div>\n:::\n:::\n\n\nWorking with one school keeps the first regression example small and concrete. Later in the lab, we will return to the full dataset.\n\n### Step 4: Preflight Check\n\nBefore fitting a model, check the variables that will enter the model:\n\n\n::: {.cell}\n\n```{.r .cell-code}\nschool11 |>\n  summarise(\n    n = n(),\n    missing_mathgain = sum(is.na(mathgain)),\n    missing_mathkind = sum(is.na(mathkind)),\n    min_mathkind = min(mathkind, na.rm = TRUE),\n    max_mathkind = max(mathkind, na.rm = TRUE),\n    min_mathgain = min(mathgain, na.rm = TRUE),\n    max_mathgain = max(mathgain, na.rm = TRUE)\n  )\n```\n\n::: {.cell-output-display}\n<div class=\"kable-table\">\n\n|  n| missing_mathgain| missing_mathkind| min_mathkind| max_mathkind| min_mathgain| max_mathgain|\n|--:|----------------:|----------------:|------------:|------------:|------------:|------------:|\n| 31|                0|                0|          434|          629|          -35|          111|\n\n</div>\n:::\n:::\n\n\nThe outcome will be `mathgain`, and the predictor will be `mathkind`.\n\n### Step 5: Descriptive Statistics\n\nHere are simple summaries for the key continuous variables:\n\n\n::: {.cell}\n\n```{.r .cell-code}\nschool11 |>\n  summarise(\n    mean_ses = round(mean(ses, na.rm = TRUE), 2),\n    sd_ses = round(sd(ses, na.rm = TRUE), 2),\n    mean_mathkind = round(mean(mathkind, na.rm = TRUE), 2),\n    sd_mathkind = round(sd(mathkind, na.rm = TRUE), 2),\n    mean_mathgain = round(mean(mathgain, na.rm = TRUE), 2),\n    sd_mathgain = round(sd(mathgain, na.rm = TRUE), 2)\n  )\n```\n\n::: {.cell-output-display}\n<div class=\"kable-table\">\n\n| mean_ses| sd_ses| mean_mathkind| sd_mathkind| mean_mathgain| sd_mathgain|\n|--------:|------:|-------------:|-----------:|-------------:|-----------:|\n|     0.43|   0.77|        499.81|       37.77|         50.45|       30.53|\n\n</div>\n:::\n:::\n\n\nAnd here are the same regression variables summarized by gender:\n\n\n::: {.cell}\n\n```{.r .cell-code}\nschool11 |>\n  group_by(gender) |>\n  summarise(\n    n = n(),\n    mean_mathkind = round(mean(mathkind, na.rm = TRUE), 2),\n    mean_mathgain = round(mean(mathgain, na.rm = TRUE), 2),\n    .groups = \"drop\"\n  )\n```\n\n::: {.cell-output-display}\n<div class=\"kable-table\">\n\n|gender |  n| mean_mathkind| mean_mathgain|\n|:------|--:|-------------:|-------------:|\n|Male   | 11|        496.64|         54.18|\n|Female | 20|        501.55|         48.40|\n\n</div>\n:::\n:::\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nschool11 |>\n  count(gender, minority_group)\n```\n\n::: {.cell-output-display}\n<div class=\"kable-table\">\n\n|gender |minority_group |  n|\n|:------|:--------------|--:|\n|Male   |Non-minority   |  8|\n|Male   |Minority       |  3|\n|Female |Non-minority   | 18|\n|Female |Minority       |  2|\n\n</div>\n:::\n:::\n\n\n\n## Part 2: Explore the Relationship\n\nRegression starts with a visual question: do the two variables appear to move together?\n\n### Boxplot\n\n\n::: {.cell}\n\n```{.r .cell-code}\nggplot(school11, aes(x = gender, y = mathkind, fill = gender)) +\n  geom_boxplot(alpha = 0.7, show.legend = FALSE) +\n  ber640_fill +\n  labs(x = \"Gender\", y = \"Math Score at Kindergarten Entry\")\n```\n\n::: {.cell-output-display}\n![Distribution of kindergarten math scores by gender in School 11](lab02-simple-regression_files/figure-html/lab02-boxplot-mathkind-1.png){fig-alt='Boxplot comparing kindergarten math scores for male and female students in School 11, with similar medians and overlapping interquartile ranges' width=2100}\n:::\n:::\n\n\n### Histogram\n\n\n::: {.cell}\n\n```{.r .cell-code}\nggplot(school11, aes(x = ses)) +\n  geom_histogram(bins = 10, fill = ber640_colors[\"accent\"],\n                 color = \"white\", alpha = 0.8) +\n  labs(x = \"Socioeconomic Status (SES)\", y = \"Count\")\n```\n\n::: {.cell-output-display}\n![Distribution of SES in School 11](lab02-simple-regression_files/figure-html/lab02-histogram-ses-1.png){fig-alt='Histogram of socioeconomic status in School 11, showing values distributed around the center with moderate spread' width=2100}\n:::\n:::\n\n\n### Scatterplot\n\nThe most important plot for simple regression is a scatterplot of the outcome and predictor.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nggplot(school11, aes(x = mathkind, y = mathgain)) +\n  geom_point(alpha = 0.65, size = 2, color = ber640_colors[\"primary\"]) +\n  labs(x = \"Math Score at Kindergarten Entry\",\n       y = \"Math Achievement Gain\")\n```\n\n::: {.cell-output-display}\n![Math gain vs. kindergarten math score in School 11](lab02-simple-regression_files/figure-html/lab02-scatter-mathkind-mathgain-1.png){fig-alt='Scatterplot of math gain versus kindergarten math score in School 11, showing a negative relationship where students with higher initial scores tend to gain fewer points' width=2100}\n:::\n:::\n\n\nWe can color the same relationship by gender:\n\n\n::: {.cell}\n\n```{.r .cell-code}\nggplot(school11, aes(x = mathkind, y = mathgain, color = gender)) +\n  geom_point(alpha = 0.65, size = 2) +\n  ber640_palette +\n  labs(x = \"Math Score at Kindergarten Entry\",\n       y = \"Math Achievement Gain\",\n       color = \"Gender\")\n```\n\n::: {.cell-output-display}\n![Math gain vs. kindergarten math score by gender](lab02-simple-regression_files/figure-html/lab02-scatter-by-gender-1.png){fig-alt='Scatterplot of math gain versus kindergarten math score colored by gender, showing similar negative trends for male and female students' width=2100}\n:::\n:::\n\n\nFinally, add a fitted regression line:\n\n\n::: {.cell}\n\n```{.r .cell-code}\nggplot(school11, aes(x = mathkind, y = mathgain)) +\n  geom_point(alpha = 0.65, size = 2, color = ber640_colors[\"primary\"]) +\n  geom_smooth(method = \"lm\", se = TRUE,\n              color = ber640_colors[\"secondary\"], linewidth = 1) +\n  labs(x = \"Math Score at Kindergarten Entry\",\n       y = \"Math Achievement Gain\")\n```\n\n::: {.cell-output-display}\n![Math gain vs. kindergarten math score with fitted regression line](lab02-simple-regression_files/figure-html/lab02-scatter-with-line-1.png){fig-alt='Scatterplot of math gain versus kindergarten math score with a downward-sloping fitted regression line and confidence band' width=2100}\n:::\n:::\n\n\nThe downward line suggests a **negative relationship**: students who entered with higher math scores tended to gain fewer points.\n\n\n## Part 3: Fit a Simple Linear Regression\n\nNow we fit the same relationship formally:\n\n$$\n\\text{mathgain}_i = \\beta_0 + \\beta_1 \\cdot \\text{mathkind}_i + \\varepsilon_i\n$$\n\n### Step 1: Fit the Model\n\n\n::: {.cell}\n\n```{.r .cell-code}\nmodel1 <- lm(mathgain ~ mathkind, data = school11)\n```\n:::\n\n\nThe formula `mathgain ~ mathkind` reads as: \"predict math gain from kindergarten math score.\"\n\n### Step 2: Inspect the Coefficients\n\n\n::: {.cell}\n\n```{.r .cell-code}\nmodel_params(model1)\n```\n\n::: {.cell-output-display}\n<div class=\"kable-table\">\n\n|Parameter   | Coefficient|         SE|   CI|     CI_low|     CI_high|         t| df_error|     p|\n|:-----------|-----------:|----------:|----:|----------:|-----------:|---------:|--------:|-----:|\n|(Intercept) |  338.124724| 52.8168551| 0.95| 230.102126| 446.1473215|  6.401834|       29| 5e-07|\n|mathkind    |   -0.575569|  0.1053838| 0.95|  -0.791103|  -0.3600351| -5.461649|       29| 7e-06|\n\n</div>\n:::\n:::\n\n\n> `model_params()` prints the coefficient estimate, standard error, confidence interval, test statistic, and p-value in a compact table.\n\n::: {.interpretation}\nThe intercept is the predicted math gain for a student with `mathkind = 0`.\nThat value is outside the observed range here, so it is mostly a mathematical anchor for the line.\n\nThe slope is the main result: for each 1-point higher kindergarten math score, the model predicts about 0.58 fewer math-gain points.\nUse \"predicts\" or \"is associated with\" here; this simple model alone does not prove a causal effect.\n:::\n\n::: {.your-turn}\n[Your turn]{.yt-title} [R]{.badge-r}\n\nWrite one plain-language sentence interpreting the slope for `mathkind`.\nYour sentence should include the direction, the unit of the predictor, and the unit of the outcome.\n\n<details><summary>Hint</summary>\nStart with: \"In School 11, each 1-point higher kindergarten math score is associated with...\"\n</details>\n:::\n\n::: {.pitfall}\nDo not write that a higher kindergarten score **causes** lower math gain.\nAt this point, the model describes an association in one school.\n:::\n\n### Step 3: Inspect Model Fit\n\n\n::: {.cell}\n\n```{.r .cell-code}\nmodel_fit(model1)\n```\n\n::: {.cell-output-display}\n<div class=\"kable-table\">\n\n|      AIC|      BIC|        R2| R2_adjusted|     RMSE|\n|--------:|--------:|---------:|-----------:|--------:|\n| 282.9957| 287.2977| 0.5070509|   0.4900527| 21.08863|\n\n</div>\n:::\n\n```{.r .cell-code}\nperformance::r2(model1)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# R2 for Linear Regression\n       R2: 0.507\n  adj. R2: 0.490\n```\n\n\n:::\n:::\n\n\n> `model_fit()` gives common model-fit statistics. `performance::r2()` focuses on $R^2$, the proportion of outcome variation explained by the model.\n\n::: {.interpretation}\n$R^2$ is about 0.507.\nThis means the model explains about 50.7% of the variation in math gain among students in School 11.\nDo not read $R^2$ as \"percent correct\"; it is about variation explained, not classification accuracy.\n:::\n\n### Step 4: Write the Regression Equation\n\nBased on the fitted model, the estimated regression equation is:\n\n$$\n\\widehat{\\text{mathgain}} = 338.12 + (-0.58) \\times \\text{mathkind}\n$$\n\nThe slope is negative. Students with kindergarten math scores 1 point higher are predicted to have math gain about 0.58 points lower, on average.\n\n\n## Part 4: Predictions and Residuals\n\nAfter fitting a model, we often ask two practical questions:\n\n- What does the model predict for specific predictor values?\n- How far away are the observed values from the fitted line?\n\n### Step 1: Make Simple Predictions\n\n\n::: {.cell}\n\n```{.r .cell-code}\nprediction_grid <- tibble(mathkind = c(450, 500, 550))\n\nprediction_grid |>\n  mutate(\n    predicted_mathgain = round(predict(model1, newdata = prediction_grid), 2)\n  )\n```\n\n::: {.cell-output-display}\n<div class=\"kable-table\">\n\n| mathkind| predicted_mathgain|\n|--------:|------------------:|\n|      450|              79.12|\n|      500|              50.34|\n|      550|              21.56|\n\n</div>\n:::\n:::\n\n\nThis table answers: \"What math gain does the model predict for students with these kindergarten math scores?\"\n\n::: {.your-turn}\n[Your turn]{.yt-title} [R]{.badge-r}\n\nAdd `600` to `prediction_grid` and rerun the prediction code.\nWhat happens to predicted math gain as the kindergarten score gets larger?\n\n<details><summary>Hint</summary>\nChange the first line to `prediction_grid <- tibble(mathkind = c(450, 500, 550, 600))`.\n</details>\n:::\n\n### Step 2: Add Fitted Values and Residuals\n\n\n::: {.cell}\n\n```{.r .cell-code}\nschool11_aug <- school11 |>\n  mutate(\n    mathgain_hat = predict(model1),\n    resid = residuals(model1)\n  )\n```\n:::\n\n\nThe fitted value is the model's prediction. The residual is:\n\n$$\ne_i = Y_i - \\widehat{Y}_i\n$$\n\n### Step 3: Check the Residual Calculation\n\n\n::: {.cell}\n\n```{.r .cell-code}\nschool11_aug |>\n  select(mathgain, mathgain_hat, resid) |>\n  mutate(check = mathgain - mathgain_hat) |>\n  head(8)\n```\n\n::: {.cell-output-display}\n<div class=\"kable-table\">\n\n| mathgain| mathgain_hat|      resid|      check|\n|--------:|------------:|----------:|----------:|\n|       44|    35.375418|  8.6245821|  8.6245821|\n|       66|    53.793627| 12.2063734| 12.2063734|\n|       58|    53.793627|  4.2063734|  4.2063734|\n|       90|    62.427162| 27.5728381| 27.5728381|\n|       35|    28.468590|  6.5314104|  6.5314104|\n|       84|    59.549317| 24.4506832| 24.4506832|\n|        8|     6.596967|  1.4030333|  1.4030333|\n|       58|    58.973748| -0.9737478| -0.9737478|\n\n</div>\n:::\n:::\n\n\nThe `resid` column and the `check` column should match, up to small rounding differences.\n\n### Step 4: Summarize Residuals\n\n\n::: {.cell}\n\n```{.r .cell-code}\nschool11_aug |>\n  summarise(\n    mean_resid = round(mean(resid), 4),\n    sd_resid = round(sd(resid), 4),\n    min_resid = round(min(resid), 4),\n    max_resid = round(max(resid), 4)\n  )\n```\n\n::: {.cell-output-display}\n<div class=\"kable-table\">\n\n| mean_resid| sd_resid| min_resid| max_resid|\n|----------:|--------:|---------:|---------:|\n|          0|  21.4372|  -39.8516|   60.0842|\n\n</div>\n:::\n:::\n\n\nIn an ordinary least squares regression with an intercept, the mean residual is essentially zero.\n\n::: {.your-turn}\n[Your turn]{.yt-title} [R]{.badge-r}\n\nFind one student with a positive residual and one student with a negative residual.\nIn one sentence for each student, describe whether the observed math gain was above or below the model prediction.\n\n<details><summary>Hint</summary>\nUse `arrange(desc(resid))` to find a large positive residual and `arrange(resid)` to find a large negative residual.\n</details>\n:::\n\n### Step 5: Visualize Residuals\n\n\n::: {.cell}\n\n```{.r .cell-code}\nggplot(school11_aug, aes(x = mathkind, y = mathgain)) +\n  geom_segment(aes(xend = mathkind, yend = mathgain_hat),\n               color = \"grey60\", linewidth = 0.4) +\n  geom_point(alpha = 0.7, size = 2, color = ber640_colors[\"primary\"]) +\n  geom_line(data = school11_aug |> arrange(mathkind),\n            aes(y = mathgain_hat),\n            color = ber640_colors[\"secondary\"], linewidth = 1) +\n  labs(x = \"Math Score at Kindergarten Entry\",\n       y = \"Math Achievement Gain\",\n       subtitle = \"Vertical grey lines show residuals\")\n```\n\n::: {.cell-output-display}\n![Observed data, fitted line, and residuals](lab02-simple-regression_files/figure-html/lab02-scatter-fitted-residuals-1.png){fig-alt='Scatterplot with observed math gain values, a fitted regression line, and vertical grey line segments showing residuals from each observed value to the fitted line' width=2100}\n:::\n:::\n\n\nEach grey line is one residual. The regression line is the line that minimizes the sum of squared residuals.\n\n\n## Part 5: Quick Model Diagnostics\n\nAfter fitting a model, inspect whether the model's assumptions look reasonable enough for the classroom analysis.\nFor linear regression, start with a visual diagnostic panel:\n\n\n::: {.cell}\n\n```{.r .cell-code}\nperformance::check_model(\n  model1,\n  check = c(\"linearity\", \"homogeneity\", \"outliers\", \"qq\"),\n  base_size = 9\n)\n```\n\n::: {.cell-output-display}\n![Quick diagnostic checks for the simple regression model](lab02-simple-regression_files/figure-html/lab02-check-model-1.png){fig-alt='Four diagnostic plots for the simple regression model. The residual smooth is mostly near zero with some waviness, the variance smooth rises in the middle, one labeled point has the largest standardized residual, and the normality panel shows most points near the reference line with one upper-tail point.' width=100%}\n:::\n:::\n\n\n::: {.assumption-check}\nUse the diagnostic panel to make a decision:\n\n1. **Linearity:** Is the smooth line roughly flat, or does it curve strongly?\n2. **Equal variance:** Does the spread of residuals look fairly even, or does it fan out?\n3. **Influential observations:** Are any points marked as unusually influential?\n4. **Normality:** Do most points in the Q-Q plot follow the reference line?\n\nFor this lab, write a short diagnostic note rather than trying to \"fix\" the model.\nLater labs will show targeted tools for nonlinearity, robust standard errors, and influential observations.\n:::\n\n::: {.your-turn}\n[Your turn]{.yt-title} [R]{.badge-r}\n\nLook at the diagnostic panel and choose one label: **acceptable**, **questionable**, or **serious concern**.\nWrite one sentence naming the plot that most influenced your decision.\n\n<details><summary>Hint</summary>\nA good diagnostic sentence has this shape: \"I would label the model as ___ because the ___ plot shows ___.\"\n</details>\n:::\n\n\n## Part 6: Additional Simple Regression Examples\n\nThe same workflow applies to other simple regression questions. The pattern is:\n\n1. Fit the model with `lm()`.\n2. Inspect coefficients with `model_params()`.\n3. Inspect fit with `model_fit()` when fit matters.\n4. Interpret the slope in substantive units.\n\n### Example 1: A Binary Predictor\n\nIs there a difference in kindergarten math scores between minority and non-minority students?\n\n\n::: {.cell}\n\n```{.r .cell-code}\nt.test(mathkind ~ minority_group,\n       data = instruction_clean,\n       var.equal = TRUE)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\n\tTwo Sample t-test\n\ndata:  mathkind by minority_group\nt = 10.347, df = 1188, p-value < 2.2e-16\nalternative hypothesis: true difference in means between group Non-minority and group Minority is not equal to 0\n95 percent confidence interval:\n 20.65493 30.32033\nsample estimates:\nmean in group Non-minority     mean in group Minority \n                  483.9219                   458.4342 \n```\n\n\n:::\n:::\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nmodel2 <- lm(mathkind ~ minority, data = instruction_clean)\nmodel_params(model2)\n```\n\n::: {.cell-output-display}\n<div class=\"kable-table\">\n\n|Parameter   | Coefficient|       SE|   CI|    CI_low|   CI_high|         t| df_error|  p|\n|:-----------|-----------:|--------:|----:|---------:|---------:|---------:|--------:|--:|\n|(Intercept) |   483.92188| 2.027183| 0.95| 479.94462| 487.89913| 238.71643|     1188|  0|\n|minority    |   -25.48763| 2.463196| 0.95| -30.32033| -20.65493| -10.34738|     1188|  0|\n\n</div>\n:::\n:::\n\n\nWhen the predictor is binary, the slope is the mean difference between the two groups.\n\n### Example 2: A Continuous Predictor\n\nDoes SES predict math gain in the full dataset?\n\n\n::: {.cell}\n\n```{.r .cell-code}\nmodel3 <- lm(mathgain ~ ses, data = instruction_clean)\nmodel_params(model3)\n```\n\n::: {.cell-output-display}\n<div class=\"kable-table\">\n\n|Parameter   | Coefficient|       SE|   CI|    CI_low|   CI_high|          t| df_error|         p|\n|:-----------|-----------:|--------:|----:|---------:|---------:|----------:|--------:|---------:|\n|(Intercept) |  57.5630914| 1.003966| 0.95| 55.593348| 59.532835| 57.3357116|     1188| 0.0000000|\n|ses         |  -0.2538051| 1.354258| 0.95| -2.910809|  2.403198| -0.1874127|     1188| 0.8513691|\n\n</div>\n:::\n\n```{.r .cell-code}\nmodel_fit(model3)\n```\n\n::: {.cell-output-display}\n<div class=\"kable-table\">\n\n|      AIC|      BIC|       R2| R2_adjusted|     RMSE|\n|--------:|--------:|--------:|-----------:|--------:|\n| 11817.36| 11832.61| 2.96e-05|  -0.0008122| 34.59876|\n\n</div>\n:::\n:::\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nggplot(instruction_clean, aes(x = ses, y = mathgain)) +\n  geom_point(alpha = 0.3, size = 1.5, color = ber640_colors[\"primary\"]) +\n  geom_smooth(method = \"lm\", se = TRUE,\n              color = ber640_colors[\"secondary\"], linewidth = 1) +\n  labs(x = \"Socioeconomic Status (SES)\",\n       y = \"Math Achievement Gain\")\n```\n\n::: {.cell-output-display}\n![Math gain vs. SES with fitted regression line](lab02-simple-regression_files/figure-html/lab02-example-ses-plot-1.png){fig-alt='Scatterplot of math gain versus socioeconomic status for the full dataset with a nearly flat fitted regression line and confidence band, showing little association' width=2100}\n:::\n:::\n\n\n### Example 3: A Gender Difference\n\nDoes average math gain differ by gender?\n\n\n::: {.cell}\n\n```{.r .cell-code}\nmodel4 <- lm(mathgain ~ female, data = instruction_clean)\nmodel_params(model4)\n```\n\n::: {.cell-output-display}\n<div class=\"kable-table\">\n\n|Parameter   | Coefficient|       SE|   CI|    CI_low|   CI_high|         t| df_error|         p|\n|:-----------|-----------:|--------:|----:|---------:|---------:|---------:|--------:|---------:|\n|(Intercept) |    58.59864| 1.427429| 0.95| 55.798076| 61.399203| 41.051863|     1188| 0.0000000|\n|female      |    -2.04050| 2.006919| 0.95| -5.978001|  1.897001| -1.016733|     1188| 0.3094877|\n\n</div>\n:::\n:::\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\ninstruction_clean |>\n  group_by(gender) |>\n  summarise(\n    n = n(),\n    mean_mathgain = round(mean(mathgain, na.rm = TRUE), 2),\n    sd_mathgain = round(sd(mathgain, na.rm = TRUE), 2),\n    .groups = \"drop\"\n  )\n```\n\n::: {.cell-output-display}\n<div class=\"kable-table\">\n\n|gender |   n| mean_mathgain| sd_mathgain|\n|:------|---:|-------------:|-----------:|\n|Male   | 588|         58.60|       36.22|\n|Female | 602|         56.56|       32.97|\n\n</div>\n:::\n:::\n\n\nThe intercept is the mean for boys (`female = 0`). The slope is the difference in mean math gain between girls and boys.\n\n\n## Part 7: Mini Regression Report\n\nA compact regression report should answer the research question, name the model, interpret the main coefficient, summarize fit, and mention one diagnostic check.\n\n::: {.interpretation}\nExample report:\n\n> In School 11, kindergarten math score was negatively associated with math gain.\n> A simple linear regression estimated that each 1-point higher kindergarten score predicted about 0.58 fewer gain points.\n> The model explained about 0.507 of the variation in math gain.\n> The quick diagnostic panel should be checked for curvature, unequal residual spread, influential observations, and Q-Q plot departures before treating this as a final analysis.\n:::\n\n::: {.your-turn}\n[Your turn]{.yt-title} [Write]{.badge-r}\n\nWrite your own 4-sentence mini report for `model1`.\nUse the example above as a template, but use your own words.\n:::\n\n::: {.exercises}\n## What to Submit\n\n1. A coefficient table for `model1` from `model_params(model1)`. [core]{.chip .easy}\n2. A prediction table with at least four `mathkind` values. [core]{.chip .easy}\n3. One residual check: one positive residual and one negative residual, with a sentence interpreting each. [core]{.chip .med}\n4. One diagnostic note using the `performance::check_model()` panel. [core]{.chip .med}\n5. A 4-sentence mini regression report answering the School 11 research question. [core]{.chip .med}\n:::\n\n::: {.summary}\n## Lab Summary\n\n1. Simple linear regression starts with a clear outcome, one predictor, and an `lm()` formula.\n\n2. `model_params()` is the default coefficient table for this course.\n\n3. `model_fit()` and `performance::r2()` summarize how well the model fits.\n\n4. `predict()` turns a fitted model into predicted values for new or existing cases.\n\n5. Residuals are the differences between observed outcomes and fitted values.\n\n6. The same `lm()` workflow works for continuous predictors and binary predictors.\n\n7. `performance::check_model()` gives a quick visual diagnostic panel; your job is to make a reasoned decision, not just paste the plot.\n\n**Next:** Lab 3 moves from simple regression to ANCOVA: comparing groups while adjusting for another variable.\n:::\n",
    "supporting": [
      "lab02-simple-regression_files"
    ],
    "filters": [
      "rmarkdown/pagebreak.lua"
    ],
    "includes": {},
    "engineDependencies": {},
    "preserve": {},
    "postProcess": true
  }
}