{
  "hash": "49e39bb7ed84fb92d7c721ac53b5bf7b",
  "result": {
    "engine": "knitr",
    "markdown": "---\ntitle: \"Homework 7: Logistic Regression Interpretation\"\n---\n\n\n\n\n## Overview\n\n::: {.callout-note}\n## Learning Objectives\n- Convert logistic regression coefficients to odds ratios using $\\exp(\\hat{\\beta})$\n- Interpret odds ratios for both continuous and dummy predictors\n- Construct 95% confidence intervals for odds ratios (log-odds scale first, then exponentiate)\n- Calculate and interpret percentage change in odds from logistic coefficients\n- Use the reciprocal odds ratio when $\\text{OR} < 1$ for clearer interpretation\n- **Related:** Chapter 9: *Simple Logistic Regression* and Chapter 10: *Multiple Logistic Regression* (in Lecture Notes)\n:::\n\nThis homework is entirely **conceptual** --- no raw data, only a published logistic regression table to interpret. The table comes from @kalmijn1994, who studied intergenerational effects of family background on educational attainment.\n\n**Data:** National Survey of Families and Households (NSFH), 1987--1988. Non-Hispanic white respondents born 1900--1963, raised by two parents ($N = 6{,}092$).\n\n**Response variable:** Whether the respondent completed high school (binary: $1 =$ yes, $0 =$ no).\n\n\n## The Logistic Regression Table\n\nThe table below reproduces Model B from Table 2 of @kalmijn1994. All coefficients are maximum-likelihood estimates from a logistic regression predicting high school completion.\n\n\n::: {#tbl-hw07-kalmijn .cell tbl-cap='Logistic Regression Coefficients for Obtaining a High School Degree [@kalmijn1994, Table 2, Model B]'}\n\n```{.r .cell-code  code-fold=\"true\" code-summary=\"Show R Code\"}\n# Reproduce the published logistic regression table (Model B only)\nkalmijn_table <- data.frame(\n  Variable = c(\n    \"Respondent's year of birth (-63 to 0)\",\n    \"Father's education (0 to 17)\",\n    \"Mother's education (0 to 17)\",\n    \"Father's occupation (1 to 9)\",\n    \"Mother's occupation (0, 1 to 9)\",\n    \"Mother employed (0 to 1)\",\n    \"Number of siblings\",\n    \"Intercept\",\n    \"N\"\n  ),\n  Model_B = c(\n    \".350** (.033)\",\n    \".126** (.016)\",\n    \".093** (.018)\",\n    \".295** (.047)\",\n    \".212* (.068)\",\n    \"-.921* (.189)\",\n    \"-.162** (.016)\",\n    \".747** (.247)\",\n    \"6,092\"\n  )\n)\n\nknitr::kable(\n  kalmijn_table,\n  col.names = c(\"Independent Variable\", \"Model B\"),\n  align = c(\"l\", \"r\"),\n  caption = NULL\n)\n```\n\n::: {.cell-output-display}\n\n\n|Independent Variable                  |        Model B|\n|:-------------------------------------|--------------:|\n|Respondent's year of birth (-63 to 0) |  .350** (.033)|\n|Father's education (0 to 17)          |  .126** (.016)|\n|Mother's education (0 to 17)          |  .093** (.018)|\n|Father's occupation (1 to 9)          |  .295** (.047)|\n|Mother's occupation (0, 1 to 9)       |   .212* (.068)|\n|Mother employed (0 to 1)              |  -.921* (.189)|\n|Number of siblings                    | -.162** (.016)|\n|Intercept                             |  .747** (.247)|\n|N                                     |          6,092|\n\n\n:::\n:::\n\n\n**Note:** \\*$p < .05$, \\*\\*$p < .01$ (two-tailed). Numbers in parentheses are estimated standard errors. Coefficients are maximum-likelihood estimates. Coefficients for year of birth are multiplied by 10.\n\n::: {.callout-note}\n## Variable Definitions\n- **Respondent's year of birth:** Year of birth minus 1963 (ranges from $-63$ to $0$).\n- **Father's/Mother's education:** Completed years of schooling (0 to 17).\n- **Father's occupation:** Socioeconomic Index (SEI) of father's occupation when respondent was 16 (scale 1 to 9).\n- **Mother's occupation:** SEI of mother's last occupation before respondent turned 18 (scale 0, 1 to 9).\n- **Mother employed:** Dummy variable ($1 =$ mother was employed between respondent's birth and age 18; $0 =$ not employed).\n- **Number of siblings:** Count of siblings.\n:::\n\n\n## Problem 1 {#sec-hw07-p1}\n\n### Problem Statement\n\n> For Model B, calculate and interpret the estimated odds ratio for mother's education.\n\n### Solution\n\n::: {.panel-tabset}\n\n#### Solution\n\nIn a logistic regression, the coefficient $\\hat{\\beta}$ represents the change in **log-odds** for a one-unit increase in the predictor. To convert to an **odds ratio**, we exponentiate:\n\n$$\n\\widehat{\\text{OR}} = \\exp(\\hat{\\beta})\n$$\n\nFor mother's education, $\\hat{\\beta} = 0.093$:\n\n$$\n\\widehat{\\text{OR}} = \\exp(0.093) = 1.10\n$$\n\n**Interpretation:** The odds of obtaining a high school degree are estimated to increase by **10%** for each extra year of mother's schooling, holding constant the other explanatory variables.\n\nIn other words, comparing two respondents who are identical on all other variables but differ by one year in mother's education, the respondent with the higher maternal education has **1.10 times the odds** of completing high school.\n\n::: {.callout-important}\n## General Formula for Odds Ratio Interpretation\nFor a continuous predictor with coefficient $\\hat{\\beta}$:\n\n$$\n\\widehat{\\text{OR}} = \\exp(\\hat{\\beta})\n$$\n\n- If $\\widehat{\\text{OR}} > 1$: A one-unit increase in $X$ is associated with **higher odds** of the outcome.\n- If $\\widehat{\\text{OR}} < 1$: A one-unit increase in $X$ is associated with **lower odds** of the outcome.\n- If $\\widehat{\\text{OR}} = 1$: No association (equivalent to $\\hat{\\beta} = 0$).\n\nThe phrase \"holding constant the other explanatory variables\" is essential --- just as in multiple linear regression.\n:::\n\n::: {.callout-warning}\n## Odds Are Not Probabilities\nAn odds ratio of 1.10 does **not** mean the probability increases by 10%. Odds and probabilities are related but different quantities:\n\n- If the probability of an event is $p$, the odds are $p/(1-p)$.\n- An OR of 1.10 means the **odds** are 10% higher, which translates to a **smaller** percentage increase in probability (the exact amount depends on the baseline probability).\n- When the outcome is rare (probability $< 10\\%$), the OR approximates the risk ratio. But for common outcomes, the OR exaggerates the magnitude of the association.\n\nAlways say \"the **odds** increase by...\" rather than \"the probability increases by...\" when interpreting odds ratios.\n:::\n\n#### Code Explanation\n\n\n::: {.cell}\n\n```{.r .cell-code  code-fold=\"true\" code-summary=\"Show R Code\"}\n# --- Problem 1: Odds ratio for mother's education ---\n\n# Logistic regression coefficient for mother's education\nbeta_mother_ed <- 0.093\n\n# Convert to odds ratio\nOR_mother_ed <- exp(beta_mother_ed)\n\ncat(\"Coefficient (log-odds):\", beta_mother_ed, \"\\n\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nCoefficient (log-odds): 0.093 \n```\n\n\n:::\n\n```{.r .cell-code  code-fold=\"true\" code-summary=\"Show R Code\"}\ncat(\"Odds Ratio: exp(\", beta_mother_ed, \") =\", round(OR_mother_ed, 2), \"\\n\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nOdds Ratio: exp( 0.093 ) = 1.1 \n```\n\n\n:::\n\n```{.r .cell-code  code-fold=\"true\" code-summary=\"Show R Code\"}\ncat(\"Percentage change in odds:\", round(100 * (OR_mother_ed - 1), 1), \"%\\n\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nPercentage change in odds: 9.7 %\n```\n\n\n:::\n:::\n\n\nThe R function `exp()` computes $e^x$. The odds ratio of $1.10$ means the odds are multiplied by $1.10$ for each additional year --- a **10% increase** in the odds.\n\n:::\n\n\n## Problem 2 {#sec-hw07-p2}\n\n### Problem Statement\n\n> For Model B, calculate the estimated odds ratio for \"Mother employed\" and form an approximate 95% confidence interval for the odds ratio. Interpret these results.\n\n### Solution\n\n::: {.panel-tabset}\n\n#### Solution\n\nThis problem requires five steps: (1) compute the odds ratio, (2) interpret using the reciprocal, (3) construct the CI for the log-odds coefficient, (4) transform to a CI for the odds ratio, and (5) interpret the reciprocal CI.\n\n**Step 1. Compute the odds ratio.**\n\nFor the \"Mother employed\" dummy variable, $\\hat{\\beta} = -0.921$ and $\\text{SE}(\\hat{\\beta}) = 0.189$:\n\n$$\n\\widehat{\\text{OR}} = \\exp(-0.921) = 0.40\n$$\n\n**Step 2. Interpret using the reciprocal.**\n\nAn odds ratio of $0.40$ means that students whose mothers **are** employed have only $0.40$ times the odds of completing high school compared to students whose mothers are **not** employed. Because $\\text{OR} < 1$, it is clearer to take the reciprocal:\n\n$$\n\\frac{1}{\\widehat{\\text{OR}}} = \\frac{1}{0.40} = 2.5\n$$\n\n**Reciprocal interpretation:** Students whose mothers are **not** employed are estimated to have **2.5 times the odds** of graduating from high school as students whose mothers **are** employed, holding all other variables constant.\n\n::: {.callout-warning}\n## When OR < 1, Consider the Reciprocal\nAn odds ratio of $0.40$ and its reciprocal $2.5$ convey the same information --- they just flip the comparison group. Saying \"2.5 times the odds\" is often easier for readers to grasp than \"0.40 times the odds.\" When the OR is less than 1, consider reporting the reciprocal and reversing the direction of the comparison.\n:::\n\n**Step 3. Form a 95% CI for the log-odds coefficient.**\n\nThe approximate 95% confidence interval for $\\beta$ is:\n\n$$\n\\hat{\\beta} \\pm 1.96 \\times \\text{SE}(\\hat{\\beta}) = -0.921 \\pm 1.96 \\times 0.189\n$$\n\n$$\n= -0.921 \\pm 0.370 = [-1.291, \\; -0.551]\n$$\n\n**Step 4. Transform to a 95% CI for the odds ratio.**\n\n::: {.callout-tip}\n## The CI Procedure: Log-Odds Scale First, Then Exponentiate\nTo construct a confidence interval for an odds ratio:\n\n1. **Form the CI on the log-odds scale:** $\\hat{\\beta} \\pm z^* \\times \\text{SE}(\\hat{\\beta})$\n2. **Exponentiate both endpoints:** $[\\exp(\\text{lower}), \\; \\exp(\\text{upper})]$\n\nThis order matters because the CI must be constructed on the **symmetric** (log-odds) scale and then transformed. You cannot form the CI directly on the odds ratio scale.\n:::\n\n$$\n\\text{95\\% CI for OR} = [\\exp(-1.291), \\; \\exp(-0.551)] = [0.275, \\; 0.576]\n$$\n\n**Step 5. Reciprocal CI.**\n\nTaking the reciprocal of both endpoints (and reversing their order):\n\n$$\n\\text{Reciprocal CI} = \\left[\\frac{1}{0.576}, \\; \\frac{1}{0.275}\\right] = [1.7, \\; 3.6]\n$$\n\n**Full interpretation:** Students whose mothers are **not** employed have between **1.7 and 3.6 times the odds** of obtaining a high school degree compared to students whose mothers are employed (95% CI), with a point estimate of **2.5 times the odds**.\n\n#### Code Explanation\n\n\n::: {.cell}\n\n```{.r .cell-code  code-fold=\"true\" code-summary=\"Show R Code\"}\n# --- Problem 2: OR and 95% CI for Mother employed ---\n\n# Coefficient and standard error\nbeta_employed <- -0.921\nse_employed   <- 0.189\n\n# Step 1: Odds ratio\nOR_employed <- exp(beta_employed)\ncat(\"Step 1 — Odds Ratio:\\n\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nStep 1 — Odds Ratio:\n```\n\n\n:::\n\n```{.r .cell-code  code-fold=\"true\" code-summary=\"Show R Code\"}\ncat(\"  OR = exp(\", beta_employed, \") =\", round(OR_employed, 2), \"\\n\\n\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n  OR = exp( -0.921 ) = 0.4 \n```\n\n\n:::\n\n```{.r .cell-code  code-fold=\"true\" code-summary=\"Show R Code\"}\n# Step 2: Reciprocal OR\nreciprocal_OR <- 1 / OR_employed\ncat(\"Step 2 — Reciprocal OR:\\n\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nStep 2 — Reciprocal OR:\n```\n\n\n:::\n\n```{.r .cell-code  code-fold=\"true\" code-summary=\"Show R Code\"}\ncat(\"  1 / OR = 1 /\", round(OR_employed, 2), \"=\",\n    round(reciprocal_OR, 1), \"\\n\\n\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n  1 / OR = 1 / 0.4 = 2.5 \n```\n\n\n:::\n\n```{.r .cell-code  code-fold=\"true\" code-summary=\"Show R Code\"}\n# Step 3: 95% CI for the log-odds coefficient\nz_star <- 1.96\nci_lower_logit <- beta_employed - z_star * se_employed\nci_upper_logit <- beta_employed + z_star * se_employed\ncat(\"Step 3 — 95% CI for coefficient (log-odds scale):\\n\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nStep 3 — 95% CI for coefficient (log-odds scale):\n```\n\n\n:::\n\n```{.r .cell-code  code-fold=\"true\" code-summary=\"Show R Code\"}\ncat(\"  [\", round(ci_lower_logit, 3), \",\", round(ci_upper_logit, 3), \"]\\n\\n\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n  [ -1.291 , -0.551 ]\n```\n\n\n:::\n\n```{.r .cell-code  code-fold=\"true\" code-summary=\"Show R Code\"}\n# Step 4: 95% CI for the odds ratio\nci_lower_OR <- exp(ci_lower_logit)\nci_upper_OR <- exp(ci_upper_logit)\ncat(\"Step 4 — 95% CI for OR:\\n\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nStep 4 — 95% CI for OR:\n```\n\n\n:::\n\n```{.r .cell-code  code-fold=\"true\" code-summary=\"Show R Code\"}\ncat(\"  [exp(\", round(ci_lower_logit, 3), \"), exp(\",\n    round(ci_upper_logit, 3), \")]\\n\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n  [exp( -1.291 ), exp( -0.551 )]\n```\n\n\n:::\n\n```{.r .cell-code  code-fold=\"true\" code-summary=\"Show R Code\"}\ncat(\"  = [\", round(ci_lower_OR, 3), \",\", round(ci_upper_OR, 3), \"]\\n\\n\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n  = [ 0.275 , 0.577 ]\n```\n\n\n:::\n\n```{.r .cell-code  code-fold=\"true\" code-summary=\"Show R Code\"}\n# Step 5: Reciprocal CI\nrecip_ci_lower <- 1 / ci_upper_OR\nrecip_ci_upper <- 1 / ci_lower_OR\ncat(\"Step 5 — Reciprocal CI:\\n\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nStep 5 — Reciprocal CI:\n```\n\n\n:::\n\n```{.r .cell-code  code-fold=\"true\" code-summary=\"Show R Code\"}\ncat(\"  [1/\", round(ci_upper_OR, 3), \", 1/\",\n    round(ci_lower_OR, 3), \"]\\n\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n  [1/ 0.577 , 1/ 0.275 ]\n```\n\n\n:::\n\n```{.r .cell-code  code-fold=\"true\" code-summary=\"Show R Code\"}\ncat(\"  = [\", round(recip_ci_lower, 1), \",\",\n    round(recip_ci_upper, 1), \"]\\n\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n  = [ 1.7 , 3.6 ]\n```\n\n\n:::\n:::\n\n\nNote that when taking the reciprocal of a confidence interval, you must **reverse the endpoints**: the reciprocal of the upper bound becomes the new lower bound, and vice versa.\n\n:::\n\n\n## Problem 3 {#sec-hw07-p3}\n\n### Problem Statement\n\n> (a) The author reported that a one-point increase in mother's occupational level is associated with a 24% increase in the odds of a high school diploma. Explain how he made this interpretation.\n>\n> (b) Form a 95% confidence interval for the percentage increase in the odds.\n\n### Solution\n\n::: {.panel-tabset}\n\n#### Solution\n\n**Part (a): Deriving the 24% increase.**\n\nFor mother's occupation, $\\hat{\\beta} = 0.212$. The odds ratio is:\n\n$$\n\\widehat{\\text{OR}} = \\exp(0.212) = 1.24\n$$\n\nThe **percentage change in odds** is computed from the odds ratio:\n\n$$\n\\text{Percentage change} = 100\\% \\times (\\widehat{\\text{OR}} - 1) = 100\\% \\times (1.24 - 1) = 24\\%\n$$\n\n::: {.callout-important}\n## Percentage Change in Odds Formula\nFor a one-unit increase in a predictor with odds ratio $\\widehat{\\text{OR}}$:\n\n$$\n\\text{Percentage change in odds} = 100\\% \\times (\\widehat{\\text{OR}} - 1)\n$$\n\n- $\\widehat{\\text{OR}} = 1.24$ $\\Rightarrow$ 24% **increase** in odds\n- $\\widehat{\\text{OR}} = 0.85$ $\\Rightarrow$ 15% **decrease** in odds\n- $\\widehat{\\text{OR}} = 2.00$ $\\Rightarrow$ 100% **increase** (i.e., the odds double)\n\nThis is the logistic regression analogue of interpreting a coefficient as a \"percent change\" in the **odds** of the outcome.\n:::\n\n**Interpretation:** Each one-point increase in mother's occupational level (SEI) is associated with a **24% increase** in the estimated odds of completing high school, holding constant the other explanatory variables.\n\n**Part (b): 95% CI for the percentage increase.**\n\nWe follow the same three-stage pipeline: log-odds $\\rightarrow$ odds ratio $\\rightarrow$ percentage change.\n\n**Stage 1.** Form the 95% CI for the coefficient ($\\hat{\\beta} = 0.212$, $\\text{SE} = 0.068$):\n\n$$\n0.212 \\pm 1.96 \\times 0.068 = 0.212 \\pm 0.133 = [0.079, \\; 0.345]\n$$\n\n**Stage 2.** Exponentiate to get the CI for the odds ratio:\n\n$$\n[\\exp(0.079), \\; \\exp(0.345)] = [1.08, \\; 1.41]\n$$\n\n**Stage 3.** Convert to percentage change:\n\n$$\n\\text{Lower:} \\quad 100\\% \\times (1.08 - 1) = 8\\%\n$$\n\n$$\n\\text{Upper:} \\quad 100\\% \\times (1.41 - 1) = 41\\%\n$$\n\n**Conclusion:** We are 95% confident that a one-point increase in mother's occupational level is associated with between an **8% and 41% increase** in the odds of completing high school, with a point estimate of **24%**.\n\n#### Code Explanation\n\n\n::: {.cell}\n\n```{.r .cell-code  code-fold=\"true\" code-summary=\"Show R Code\"}\n# --- Problem 3: Mother's occupation — OR, percentage, and CI ---\n\n# Coefficient and standard error\nbeta_mother_occ <- 0.212\nse_mother_occ   <- 0.068\n\n# Part (a): OR and percentage change\nOR_mother_occ <- exp(beta_mother_occ)\npct_change    <- 100 * (OR_mother_occ - 1)\n\ncat(\"Part (a):\\n\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nPart (a):\n```\n\n\n:::\n\n```{.r .cell-code  code-fold=\"true\" code-summary=\"Show R Code\"}\ncat(\"  OR = exp(\", beta_mother_occ, \") =\", round(OR_mother_occ, 2), \"\\n\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n  OR = exp( 0.212 ) = 1.24 \n```\n\n\n:::\n\n```{.r .cell-code  code-fold=\"true\" code-summary=\"Show R Code\"}\ncat(\"  Percentage change = 100% × (\", round(OR_mother_occ, 2),\n    \"- 1) =\", round(pct_change, 0), \"%\\n\\n\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n  Percentage change = 100% × ( 1.24 - 1) = 24 %\n```\n\n\n:::\n\n```{.r .cell-code  code-fold=\"true\" code-summary=\"Show R Code\"}\n# Part (b): 95% CI\nz_star <- 1.96\n\n# Stage 1: CI for log-odds coefficient\nci_lower_logit <- beta_mother_occ - z_star * se_mother_occ\nci_upper_logit <- beta_mother_occ + z_star * se_mother_occ\ncat(\"Part (b):\\n\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nPart (b):\n```\n\n\n:::\n\n```{.r .cell-code  code-fold=\"true\" code-summary=\"Show R Code\"}\ncat(\"  Stage 1 — CI for coefficient: [\",\n    round(ci_lower_logit, 3), \",\", round(ci_upper_logit, 3), \"]\\n\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n  Stage 1 — CI for coefficient: [ 0.079 , 0.345 ]\n```\n\n\n:::\n\n```{.r .cell-code  code-fold=\"true\" code-summary=\"Show R Code\"}\n# Stage 2: CI for OR\nci_lower_OR <- exp(ci_lower_logit)\nci_upper_OR <- exp(ci_upper_logit)\ncat(\"  Stage 2 — CI for OR: [\",\n    round(ci_lower_OR, 2), \",\", round(ci_upper_OR, 2), \"]\\n\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n  Stage 2 — CI for OR: [ 1.08 , 1.41 ]\n```\n\n\n:::\n\n```{.r .cell-code  code-fold=\"true\" code-summary=\"Show R Code\"}\n# Stage 3: CI for percentage change\npct_lower <- 100 * (ci_lower_OR - 1)\npct_upper <- 100 * (ci_upper_OR - 1)\ncat(\"  Stage 3 — CI for % change: [\",\n    round(pct_lower, 0), \"%,\", round(pct_upper, 0), \"%]\\n\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n  Stage 3 — CI for % change: [ 8 %, 41 %]\n```\n\n\n:::\n:::\n\n\nThe key insight is that the **same three-stage pipeline** works for both the point estimate and the confidence interval: start on the log-odds scale, exponentiate to get odds ratios, then subtract 1 and multiply by 100 for percentages.\n\n:::\n\n\n::: {.callout-caution}\n## Common Mistake: Treating Odds Ratios as Probability Ratios\nAn odds ratio of 1.10 means the *odds* increase by 10%, NOT the *probability*. For rare outcomes, the OR approximates the risk ratio. But for common outcomes (like high school completion in this dataset), the OR substantially overstates the change in probability. When communicating results to non-technical audiences, consider converting to predicted probabilities for specific covariate profiles rather than relying solely on odds ratios.\n:::\n\n\n## Summary\n\nThis homework practiced three essential skills for interpreting logistic regression output from published tables:\n\n1. **Odds ratio computation.** The coefficient $\\hat{\\beta}$ is on the log-odds scale. Exponentiate with $\\exp(\\hat{\\beta})$ to obtain the odds ratio. For mother's education ($\\hat{\\beta} = 0.093$), the OR is $1.10$ --- a 10% increase in odds per additional year of schooling.\n\n2. **Confidence intervals for odds ratios.** Always construct the CI on the **log-odds scale** first ($\\hat{\\beta} \\pm 1.96 \\times \\text{SE}$), then exponentiate both endpoints. For the mother employed dummy, the 95% CI for the OR is $[0.275, \\; 0.576]$, or in reciprocal form, $[1.7, \\; 3.6]$.\n\n3. **Percentage change in odds.** The formula $100\\% \\times (\\text{OR} - 1)$ converts an odds ratio to a percentage change. For mother's occupation ($\\text{OR} = 1.24$), a one-point increase in SEI corresponds to a 24% increase in the odds of high school completion (95% CI: 8% to 41%).\n\nThese three operations form a coherent **pipeline** for logistic regression interpretation:\n\n$$\n\\hat{\\beta} \\;\\xrightarrow{\\;\\exp(\\cdot)\\;}\\; \\widehat{\\text{OR}} \\;\\xrightarrow{\\;100\\% \\times (\\cdot - 1)\\;}\\; \\text{Percentage change in odds}\n$$\n\n::: {.callout-note}\n## Looking Ahead\nIn **Homework 8**, you will fit logistic regression models to real data and encounter **Simpson's Paradox** --- a situation where the direction of an association reverses after controlling for a confounding variable. The interpretation skills from this homework (odds ratios, CIs, percentage changes) will be applied in the context of model-building and variable selection.\n:::\n",
    "supporting": [
      "hw07-logistic-interpretation_files"
    ],
    "filters": [
      "rmarkdown/pagebreak.lua"
    ],
    "includes": {},
    "engineDependencies": {},
    "preserve": {},
    "postProcess": true
  }
}