{
  "hash": "79bf6070009619dec75210e764a186cc",
  "result": {
    "engine": "knitr",
    "markdown": "# Dataset Descriptions {#sec-app-datasets .unnumbered}\n\n\n\n\nThis appendix documents every dataset used in this book. All datasets are available in the `regdatasets` package (see @sec-app-regdatasets for installation instructions).\n\n\n## Overview {#sec-app-data-overview}\n\nThe `regdatasets` package bundles cleaned, ready-to-use datasets for teaching regression analysis in the social and behavioral sciences. Each dataset has been selected to illustrate specific statistical concepts and is used in one or more chapters of this book.\n\n### Listing All Datasets\n\n::: {.panel-tabset}\n### R Code\n\n::: {.cell}\n\n```{.r .cell-code}\n# List all datasets in the regdatasets package\ndata(package = \"regdatasets\")$results |>\n  as_tibble() |>\n  select(Item, Title) |>\n  knitr::kable(col.names = c(\"Dataset\", \"Description\"))\n```\n\n::: {.cell-output-display}\n\n\n|Dataset      |Description                                                         |\n|:------------|:-------------------------------------------------------------------|\n|alcohol1_pp  |Adolescent Alcohol Use Person-Period Data                           |\n|berk_sub     |UC Berkeley Graduate Admissions Subset (Engineering and Psychology) |\n|berkeley     |UC Berkeley Graduate Admissions Data (Five Departments)             |\n|civic_ed     |Civic Education Study: Pre-Post Survey Data                         |\n|classdata_07 |Class Survey Data (2007)                                            |\n|crime        |Florida County Crime Rates                                          |\n|disc         |NELS:88 Discipline and School Experiences Study                     |\n|disc2        |NELS:88 Discipline Study with Achievement Scores                    |\n|faculty      |Faculty Salary Data                                                 |\n|gcse         |GCSE and London Reading Test Data                                   |\n|grades       |Essay Grades and Writing Features                                   |\n|gss_1        |General Social Survey Data                                          |\n|hsb_sub      |High School and Beyond Subset                                       |\n|hsbs1        |High School and Beyond Survey (Full Sample)                         |\n|individuals  |Bureau of Labor Statistics March 2000 CPS Individual Data           |\n|instruction  |Reading Instruction Methods Study                                   |\n|lambert      |Lambert Longitudinal Study Data                                     |\n|nels_data    |National Education Longitudinal Study of 1988 (NELS:88)             |\n|penalty      |Death Penalty Sentencing Data                                       |\n|pisa2000     |PISA 2000 International Reading Assessment Data                     |\n|reading      |Reading Comprehension Instruction Experiment                        |\n|satisfaction |Satisfaction Survey Data                                            |\n|titanic      |Titanic Passenger Survival Data                                     |\n|womenlf      |Canadian Women's Labor Force Participation                          |\n\n\n:::\n:::\n\n\n### Code Explanation\n- `data(package = \"regdatasets\")` returns metadata about all datasets in the package\n- The `$results` element contains a matrix with dataset names and descriptions\n- We convert it to a tibble and display as a formatted table\n\n### Output Interpretation\n- The table lists all 25 datasets available in the package, with the `Dataset` column showing the name to use with `data()` and the `Description` column providing a brief summary\n- Use the dataset name exactly as shown (e.g., `data(gcse)`) to load it into your R environment\n:::\n\n\n### Dataset-Chapter Map\n\nThe table below shows which datasets are used in each chapter, so you can quickly locate the relevant data for any topic.\n\n| Dataset | Chapters | Primary Topic |\n|:--------|:---------|:--------------|\n| `gcse` | @sec-ch1, @sec-ch2, @sec-ch5, @sec-ch6, @sec-ch8 | Simple & multiple regression, ANCOVA, interactions, nonlinear, diagnostics |\n| `crime` | @sec-ch4, @sec-ch5, @sec-ch6 | Continuous predictors, interactions, nonlinear relationships |\n| `faculty` | @sec-ch5 | Categorical x categorical interaction |\n| `instruction` | @sec-ch3 | One-way ANOVA |\n| `hsb_sub` | @sec-ch5, @sec-ch6, @sec-ch7 | Interactions, nonlinear relationships, model building |\n| `nels_data` | @sec-ch7, @sec-ch8 | Model building, diagnostics |\n| `titanic` | @sec-ch9, @sec-ch10, @sec-ch11, @sec-ch12 | Logistic regression, diagnostics, latent response & GLM |\n| `penalty` | @sec-ch11 | Logistic diagnostics |\n| `grades` | @sec-ch13 | Ordinal models |\n| `satisfaction` | @sec-ch13 | Ordinal models (exercises) |\n| `alcohol1_pp` | Supplementary | Longitudinal / person-period analysis |\n| `berk_sub` | Supplementary | Logistic regression, Simpson's paradox |\n| `berkeley` | Supplementary | Logistic regression, Simpson's paradox |\n| `civic_ed` | Supplementary | Pre-post survey, civic education |\n| `classdata_07` | Supplementary | In-class survey demonstration |\n| `disc` / `disc2` | Supplementary | Discipline, school experiences, achievement |\n| `gss_1` | Supplementary | Social attitudes and demographics |\n| `hsbs1` | Supplementary | Full HS&B sample, psychometric measures |\n| `individuals` | Supplementary | Earnings, labor economics |\n| `lambert` | Supplementary | Longitudinal child development |\n| `pisa2000` | Supplementary | International reading assessment |\n| `reading` | Supplementary | Reading instruction experiment |\n| `womenlf` | Supplementary | Multinomial logit, labor force participation |\n\n\n## Dataset Details {#sec-app-data-details}\n\n### gcse {#sec-app-data-gcse}\n\n**General Certificate of Secondary Education exam data from London schools.**\n\n- **Source**: Goldstein et al. (1993); distributed in the `mlmRev` package\n- **Context**: Students nested within secondary schools in London. The GCSE exam is taken at age 16; the London Reading Test (LRT) is administered at age 11 as an intake measure.\n- **n**: 4,059 students in 65 schools\n\n| Variable | Type | Description |\n|:---------|:-----|:------------|\n| `school` | Factor | School identifier |\n| `student` | Integer | Student identifier |\n| `girl` | Factor | Gender (0 = boy, 1 = girl) |\n| `gcse` | Numeric | Standardized GCSE exam score (mean = 0, SD $\\approx$ 10) |\n| `lrt` | Numeric | Standardized London Reading Test score at intake (mean = 0, SD $\\approx$ 10) |\n\n::: {.panel-tabset}\n### R Code\n\n::: {.cell}\n\n```{.r .cell-code}\ndata(gcse)\nglimpse(gcse)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nRows: 4,059\nColumns: 6\n$ school  <int> 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,…\n$ student <int> 143, 145, 142, 141, 138, 155, 158, 115, 117, 113, 112, 137, 13…\n$ gcse    <dbl> 2.6132, 1.3407, -17.2390, 9.6759, 5.4434, 17.3490, 10.3960, -1…\n$ lrt     <dbl> 6.19060, 2.05800, -13.64600, 2.05800, 3.71100, 21.89400, -11.1…\n$ gender  <int> 1, 1, 0, 1, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 1, 1,…\n$ pred    <dbl> 0.7854500, 0.5037300, -0.5668100, 0.5037300, 0.6164100, 1.8559…\n```\n\n\n:::\n:::\n\n\n### Code Explanation\n- `data(gcse)`: Loads the dataset into the global environment\n- `glimpse()`: Displays variable names, types, and first few values\n\n### Output Interpretation\n- 4,059 rows (students) and 5 columns --- a manageable size for learning regression\n- `school` and `girl` are stored as factors, ready for use as categorical predictors in `lm()`\n- `gcse` and `lrt` are continuous numeric scores, both standardized around zero\n:::\n\n::: {.callout-note}\n## Chapter usage\n`gcse` serves as the primary motivating dataset in @sec-ch1 (simple linear regression), @sec-ch2 (ANCOVA with school and gender effects), and @sec-ch8 (model diagnostics).\n:::\n\n\n### crime {#sec-app-data-crime}\n\n**State-level crime data from the United States.**\n\n- **Source**: U.S. Census Bureau and FBI Uniform Crime Reports\n- **Context**: Cross-sectional data on crime rates and socioeconomic indicators across U.S. states, used to illustrate multiple regression with continuous predictors.\n- **n**: 51 observations (50 states + District of Columbia)\n\n| Variable | Type | Description |\n|:---------|:-----|:------------|\n| `state` | Character | State name |\n| `crime_rate` | Numeric | Violent crimes per 100,000 population |\n| `poverty` | Numeric | Percent of population below the poverty line |\n| `single_parent` | Numeric | Percent of single-parent households |\n| `metro` | Numeric | Percent of population in metropolitan areas |\n| `education` | Numeric | Percent with high school diploma or higher |\n| `unemployment` | Numeric | Unemployment rate (%) |\n\n::: {.panel-tabset}\n### R Code\n\n::: {.cell}\n\n```{.r .cell-code}\ndata(crime)\nglimpse(crime)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nRows: 67\nColumns: 5\n$ county <chr> \"ALACHUA\", \"BAKER\", \"BAY\", \"BRADFORD\", \"BREVARD\", \"BROWARD\", \"C…\n$ c      <int> 104, 20, 64, 50, 64, 94, 8, 35, 27, 41, 55, 69, 128, 69, 49, 97…\n$ i      <dbl> 22.1, 25.8, 24.7, 24.6, 30.5, 30.6, 18.6, 25.7, 21.3, 34.9, 34.…\n$ hs     <dbl> 82.7, 64.1, 74.7, 65.0, 82.3, 76.8, 55.9, 75.7, 68.6, 81.2, 79.…\n$ u      <dbl> 73.2, 21.5, 85.0, 23.2, 91.9, 98.9, 0.0, 80.2, 31.0, 65.8, 77.6…\n```\n\n\n:::\n:::\n\n\n### Code Explanation\n- This dataset illustrates regression with multiple continuous predictors (@sec-ch4) and model building strategies (@sec-ch7)\n\n### Output Interpretation\n- 51 rows represent all 50 U.S. states plus D.C. --- a small, complete cross-sectional dataset\n- All predictor variables are continuous and measured on different scales; consider standardizing when comparing effect sizes\n:::\n\n\n### faculty {#sec-app-data-faculty}\n\n**Faculty salary data from a U.S. university.**\n\n- **Source**: Adapted from academic salary studies\n- **Context**: Faculty members across different ranks, used to illustrate categorical × categorical interactions (gender × rank) in regression.\n- **n**: 514 faculty members\n\n| Variable | Type | Description |\n|:---------|:-----|:------------|\n| `salary` | Numeric | Annual salary (in dollars) |\n| `rank` | Numeric | Academic rank (1 = Assistant, 2 = Associate, 3 = Full) |\n| `male` | Numeric | Gender (1 = male, 0 = female) |\n| `exprior` | Numeric | Years of prior experience |\n| `yearsbg` | Numeric | Years since beginning appointment |\n| `yearsrank` | Numeric | Years in current rank |\n| `market` | Numeric | Market adjustment factor |\n| `termdeg` | Numeric | Terminal degree (1 = yes) |\n| `admin` | Numeric | Administrative duties (1 = yes) |\n| `yearsdg` | Numeric | Years since degree |\n\n::: {.panel-tabset}\n### R Code\n\n::: {.cell}\n\n```{.r .cell-code}\ndata(faculty)\nglimpse(faculty)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nRows: 514\nColumns: 10\n$ salary    <dbl> 38361.75, 68906.00, 55979.00, 61008.00, 42977.00, 51640.00, …\n$ exprior   <int> 0, 2, 0, 0, 5, 4, 1, 0, 0, 0, 0, 0, 2, 15, 0, 0, 1, 0, 19, 4…\n$ yearsbg   <int> 14, 29, 14, 3, 7, 13, 8, 0, 25, 2, 26, 29, 16, 3, 25, 21, 30…\n$ yearsrank <int> 2, 20, 3, 3, 1, 5, 4, 0, 5, 1, 17, 16, 11, 3, 12, 11, 24, 0,…\n$ market    <dbl> 0.72, 1.00, 1.04, 1.24, 0.99, 0.99, 0.79, 0.88, 0.96, 0.99, …\n$ termdeg   <int> 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, …\n$ admin     <int> 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, …\n$ yearsdg   <int> 14, 31, 14, 2, 12, 17, 9, 0, 23, 1, 22, 27, 18, 18, 21, 20, …\n$ rank      <int> 2, 3, 3, 1, 2, 3, 2, 1, 2, 1, 2, 3, 2, 1, 3, 3, 3, 2, 2, 2, …\n$ male      <int> 0, 1, 1, 1, 1, 0, 0, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, …\n```\n\n\n:::\n:::\n\n\n### Code Explanation\n- Primary dataset for @sec-ch5 (categorical x categorical interaction), where the gender salary gap is examined across academic ranks\n\n### Output Interpretation\n- 514 rows and 10 columns; note that `rank`, `male`, `termdeg`, and `admin` are stored as numeric but represent categorical variables\n- Convert these to factors before modeling: `mutate(faculty, rank = factor(rank), male = factor(male))`\n:::\n\n\n### hsb_sub {#sec-app-data-hsb}\n\n**High School and Beyond survey subset.**\n\n- **Source**: National Center for Education Statistics (NCES), High School and Beyond longitudinal study\n- **Context**: A subset of the HS&B survey, a nationally representative sample of U.S. high school students, used to illustrate interactions and nonlinear relationships.\n- **n**: ~200 students (subset)\n\n| Variable | Type | Description |\n|:---------|:-----|:------------|\n| `math` | Numeric | Math achievement score |\n| `science` | Numeric | Science achievement score |\n| `reading` | Numeric | Reading achievement score |\n| `ses` | Numeric | Socioeconomic status (composite) |\n| `female` | Factor | Gender (0 = male, 1 = female) |\n| `race` | Factor | Race/ethnicity |\n| `schtyp` | Factor | School type (public, private) |\n| `prog` | Factor | Program type (academic, general, vocational) |\n\n::: {.panel-tabset}\n### R Code\n\n::: {.cell}\n\n```{.r .cell-code}\ndata(hsb_sub)\nglimpse(hsb_sub)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nRows: 188\nColumns: 7\n$ minority <int> 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0…\n$ female   <int> 1, 1, 0, 0, 0, 0, 1, 0, 1, 0, 1, 1, 0, 1, 0, 1, 0, 0, 1, 0, 1…\n$ ses      <dbl> -1.528, -0.588, -0.528, -0.668, -0.158, 0.022, -0.618, -0.998…\n$ mathach  <dbl> 5.876, 19.708, 20.349, 8.781, 17.898, 4.583, -2.832, 0.523, 1…\n$ size     <int> 842, 842, 842, 842, 842, 842, 842, 842, 842, 842, 842, 842, 8…\n$ sector   <int> 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0…\n$ schoolid <int> 1224, 1224, 1224, 1224, 1224, 1224, 1224, 1224, 1224, 1224, 1…\n```\n\n\n:::\n:::\n\n\n### Code Explanation\n- Used in @sec-ch5 (interactions between predictors), @sec-ch6 (nonlinear relationships such as polynomial regression), and @sec-ch7 (model building)\n\n### Output Interpretation\n- Approximately 200 rows with a mix of factor and numeric variables\n- `female`, `race`, `schtyp`, and `prog` are already stored as factors, ready for use as categorical predictors\n- Multiple achievement scores (`math`, `science`, `reading`) allow for comparing models with different outcomes\n:::\n\n\n### titanic {#sec-app-data-titanic}\n\n**Passenger survival data from the RMS Titanic.**\n\n- **Source**: Encyclopedia Titanica and British Board of Trade inquiry\n- **Context**: The sinking of the Titanic in 1912 provides a compelling case for logistic regression --- survival depended on passenger class, age, and gender.\n- **n**: ~1,309 passengers\n\n| Variable | Type | Description |\n|:---------|:-----|:------------|\n| `survived` | Factor | Survival (0 = no, 1 = yes) |\n| `pclass` | Factor | Passenger class (1st, 2nd, 3rd) |\n| `name` | Character | Passenger name |\n| `sex` | Factor | Gender (male, female) |\n| `age` | Numeric | Age in years |\n| `sibsp` | Integer | Number of siblings/spouses aboard |\n| `parch` | Integer | Number of parents/children aboard |\n| `fare` | Numeric | Ticket fare (in British pounds) |\n\n::: {.panel-tabset}\n### R Code\n\n::: {.cell}\n\n```{.r .cell-code}\ndata(titanic)\nglimpse(titanic)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nRows: 1,309\nColumns: 6\n$ pclass   <int> 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1…\n$ survived <int> 1, 1, 0, 0, 0, 1, 1, 0, 1, 0, 0, 1, 1, 1, 1, 0, 0, 1, 1, 0, 1…\n$ age      <dbl> 29.0000, 0.9167, 2.0000, 30.0000, 25.0000, 48.0000, 63.0000, …\n$ fare     <dbl> 211.3375, 151.5500, 151.5500, 151.5500, 151.5500, 26.5500, 77…\n$ embarked <chr> \"S\", \"S\", \"S\", \"S\", \"S\", \"S\", \"S\", \"S\", \"C\", \"C\", \"C\", \"C\", \"…\n$ sex      <int> 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 0, 1, 1, 1, 0, 0, 0, 1, 1, 0, 0…\n```\n\n\n:::\n:::\n\n\n### Code Explanation\n- Primary dataset for @sec-ch9 (simple logistic regression), @sec-ch10 (multiple logistic regression), and @sec-ch11 (logistic regression diagnostics)\n\n### Output Interpretation\n- Approximately 1,309 rows; `survived`, `pclass`, and `sex` are factors ready for logistic regression\n- `age` contains missing values --- check with `sum(is.na(titanic$age))` before modeling\n- `fare` is right-skewed; consider a log transformation in exploratory analysis\n:::\n\n\n### penalty {#sec-app-data-penalty}\n\n**Death penalty sentencing data.**\n\n- **Source**: Adapted from Agresti (2013); originally from legal studies on sentencing disparities\n- **Context**: Binary outcome (death sentence yes/no) with predictors related to case characteristics, illustrating simple logistic regression.\n- **n**: Varies by version\n\n| Variable | Type | Description |\n|:---------|:-----|:------------|\n| `death` | Factor | Death sentence (0 = no, 1 = yes) |\n| `black_defendant` | Factor | Defendant race (0 = other, 1 = Black) |\n| `white_victim` | Factor | Victim race (0 = other, 1 = White) |\n| `aggravation` | Numeric | Aggravation level of the crime |\n\n::: {.panel-tabset}\n### R Code\n\n::: {.cell}\n\n```{.r .cell-code}\ndata(penalty)\nglimpse(penalty)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nRows: 674\nColumns: 3\n$ def_bl   <int> 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0…\n$ vic_bl   <int> 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0…\n$ death_pe <int> 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0…\n```\n\n\n:::\n:::\n\n\n### Code Explanation\n- Introduced in @sec-ch9 as a supplementary example for simple logistic regression, illustrating the relationship between case characteristics and sentencing outcomes\n\n### Output Interpretation\n- A compact dataset with binary and numeric variables; `death`, `black_defendant`, and `white_victim` are factors\n- `aggravation` is a continuous numeric scale measuring crime severity\n:::\n\n\n### grades {#sec-app-data-grades}\n\n**Essay grading data (ordinal outcome).**\n\n- **Source**: Adapted from educational assessment studies\n- **Context**: Student essays scored on an ordinal scale from 1 (Poor) to 4 (Excellent), with several writing quality features measured for each essay. Used to illustrate ordinal regression models.\n- **n**: 198 essays\n\n| Variable | Type | Description |\n|:---------|:-----|:------------|\n| `essay` | Numeric | Essay identifier |\n| `grade` | Numeric | Essay grade from 1 (Poor) to 4 (Excellent) |\n| `wordlength` | Numeric | Average word length |\n| `sqrtwords` | Numeric | Square root of number of words |\n| `commas` | Numeric | Number of commas × 100 ÷ number of words |\n| `errors` | Numeric | Percentage of words with spelling errors |\n| `prepos` | Numeric | Percentage of words that are prepositions |\n| `sentlength` | Numeric | Average number of words per sentence |\n\n::: {.panel-tabset}\n### R Code\n\n::: {.cell}\n\n```{.r .cell-code}\ndata(grades)\nglimpse(grades)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nRows: 198\nColumns: 8\n$ essay      <int> 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, …\n$ grade      <int> 3, 3, 1, 2, 1, 3, 3, 1, 1, 1, 1, 3, 1, 4, 2, 2, 2, 2, 1, 4,…\n$ wordlength <dbl> 4.760, 4.244, 4.087, 4.355, 4.306, 4.508, 3.938, 4.043, 4.2…\n$ sqrtwords  <dbl> 15.460, 9.055, 16.186, 7.550, 9.644, 11.916, 8.544, 7.211, …\n$ commas     <dbl> 5.6, 3.6, 1.1, 1.8, 2.3, 1.3, 2.8, 0.0, 5.3, 1.3, 0.0, 3.8,…\n$ errors     <dbl> 5.549, 1.269, 2.608, 1.808, 0.000, 0.000, 0.000, 0.000, 1.7…\n$ prepos     <dbl> 8.0, 9.5, 14.0, 0.0, 10.0, 11.1, 13.8, 5.9, 14.0, 14.7, 8.0…\n$ sentlength <dbl> 19.527, 16.376, 18.433, 14.648, 18.721, 20.002, 23.749, 25.…\n```\n\n\n:::\n:::\n\n\n### Code Explanation\n- Primary dataset for @sec-ch13 (ordinal logistic regression models), where essay grades are predicted from writing features such as word length and spelling errors\n\n### Output Interpretation\n- 198 rows and 8 columns; `grade` is numeric (1--4) but should be converted to an ordered factor for ordinal regression: `mutate(grades, grade = ordered(grade))`\n- All predictor variables are continuous writing quality measures\n:::\n\n\n### satisfaction {#sec-app-data-satisfaction}\n\n**Course satisfaction survey data (ordinal outcome).**\n\n- **Source**: Adapted from educational survey research\n- **Context**: Student satisfaction ratings on an ordinal scale, with gender and income level as predictors. Used in exercises to practice ordinal regression modeling.\n- **n**: 110 respondents\n\n| Variable | Type | Description |\n|:---------|:-----|:------------|\n| `gender` | Character | Gender (`\"F\"` = Female, `\"M\"` = Male) |\n| `income` | Numeric | Income level (1 = low, 2, 3, 4 = high) |\n| `satisfaction` | Numeric | Satisfaction rating (ordinal scale) |\n\n::: {.panel-tabset}\n### R Code\n\n::: {.cell}\n\n```{.r .cell-code}\ndata(satisfaction)\nglimpse(satisfaction)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nRows: 110\nColumns: 3\n$ gender       <chr> \"F\", \"F\", \"F\", \"F\", \"M\", \"M\", \"M\", \"M\", \"F\", \"F\", \"F\", \"F…\n$ income       <int> 1, 2, 3, 4, 1, 2, 3, 4, 1, 2, 3, 4, 1, 2, 3, 4, 1, 2, 3, …\n$ satisfaction <int> 1, 1, 1, 1, 1, 1, 1, 1, 2, 2, 2, 2, 2, 2, 2, 2, 3, 3, 3, …\n```\n\n\n:::\n:::\n\n\n### Code Explanation\n- Used in @sec-ch13 exercises to practice fitting ordinal logistic regression with `polr()`, interpreting odds ratios, and testing the proportional odds assumption\n\n### Output Interpretation\n- 110 rows with 3 variables; `gender` is character (convert with `factor()`), `income` and `satisfaction` are numeric ordinal scales\n- For ordinal modeling, convert `satisfaction` to an ordered factor: `mutate(satisfaction, satisfaction = ordered(satisfaction))`\n:::\n\n\n### instruction {#sec-app-data-instruction}\n\n**Instructional method experiment data.**\n\n- **Source**: Adapted from educational intervention studies\n- **Context**: Comparison of different instructional methods on student outcomes, used to illustrate ANOVA and interaction effects.\n- **n**: Varies by version\n\n| Variable | Type | Description |\n|:---------|:-----|:------------|\n| `score` | Numeric | Post-test achievement score |\n| `method` | Factor | Instructional method (e.g., lecture, discussion, active learning) |\n| `prior` | Numeric | Pre-test or prior knowledge score |\n| `group` | Factor | Additional grouping variable |\n\n::: {.panel-tabset}\n### R Code\n\n::: {.cell}\n\n```{.r .cell-code}\ndata(instruction)\nglimpse(instruction)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nRows: 1,190\nColumns: 12\n$ girl     <int> 1, 0, 1, 0, 0, 1, 0, 0, 1, 0, 0, 1, 0, 0, 0, 1, 1, 0, 1, 0, 0…\n$ minority <int> 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 0, 0, 0, 0, 0, 1, 1, 1…\n$ mathkind <int> 448, 460, 511, 449, 425, 450, 452, 443, 422, 480, 502, 502, 4…\n$ mathgain <int> 32, 109, 56, 83, 53, 65, 51, 66, 88, -7, 60, -2, 101, 30, 65,…\n$ ses      <dbl> 0.46, -0.27, -0.03, -0.38, -0.03, 0.76, -0.03, 0.20, 0.64, 0.…\n$ yearstea <dbl> 1.00, 1.00, 1.00, 2.00, 2.00, 2.00, 2.00, 2.00, 2.00, 2.00, 2…\n$ mathknow <dbl> NA, NA, NA, -0.11, -0.11, -0.11, -0.11, -0.11, -0.11, -0.11, …\n$ housepov <dbl> 0.082, 0.082, 0.082, 0.082, 0.082, 0.082, 0.082, 0.082, 0.082…\n$ mathprep <dbl> 2.00, 2.00, 2.00, 3.25, 3.25, 3.25, 3.25, 3.25, 3.25, 3.25, 3…\n$ classid  <int> 160, 160, 160, 217, 217, 217, 217, 217, 217, 217, 217, 197, 1…\n$ schoolid <int> 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2…\n$ childid  <int> 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18…\n```\n\n\n:::\n:::\n\n\n### Code Explanation\n- Used in @sec-ch3 (one-way ANOVA comparing instructional methods) and @sec-ch5 (interactions between method and student characteristics)\n\n### Output Interpretation\n- `method` is a factor with multiple levels representing different instructional approaches\n- `score` is the continuous outcome; `prior` is a continuous covariate useful for ANCOVA designs\n:::\n\n\n### nels_data {#sec-app-data-nels}\n\n**National Education Longitudinal Study of 1988 (NELS:88).**\n\n- **Source**: National Center for Education Statistics (NCES)\n- **Context**: Longitudinal study following a nationally representative sample of 8th-graders through high school. Contains extensive student, family, and school variables. Used for model building and diagnostics.\n- **n**: 2,000 students (subset)\n\n| Variable | Type | Description |\n|:---------|:-----|:------------|\n| `id` | Numeric | Student identifier |\n| `byses` | Numeric | Base-year socioeconomic status composite |\n| `bypared` | Numeric | Parents' highest education level |\n| `byfaminc` | Numeric | Family income category |\n| `by2xrstd` | Numeric | Standardized reading score (base year) |\n| `by2xmstd` | Numeric | Standardized math score (base year) |\n| `f12xrstd` | Numeric | Standardized reading score (first follow-up) |\n\n::: {.callout-note}\nThis is a wide dataset with 299 variables from the NELS:88 survey. Most analyses in this book use only a handful of key variables. See @sec-ch7 and @sec-ch8 for model building and diagnostics applications.\n:::\n\n::: {.panel-tabset}\n### R Code\n\n::: {.cell}\n\n```{.r .cell-code}\ndata(nels_data)\nglimpse(nels_data[, 1:10])\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nRows: 2,000\nColumns: 10\n$ id      <int> 124966, 124968, 124972, 124999, 175551, 180655, 180665, 180672…\n$ bys2a   <int> 1, 8, 1, 1, 1, 1, 1, 1, 1, 1, 8, 8, 1, 1, 1, 1, 1, 8, 8, 1, 8,…\n$ bys4a   <int> 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 8, 8, 1, 1, 1, 1, 1, 8, 8, 1, 8,…\n$ bys4occ <int> 15, 1, 1, 15, 1, 18, 18, 1, 15, 13, 98, 98, 4, 6, 9, 4, 6, 98,…\n$ bys5a   <int> 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 8, 8, 1, 1, 1, 1, 1, 8, 8, 1, 8,…\n$ bys7a   <int> 2, 1, 1, 1, 1, 1, 1, 1, 1, 1, 8, 8, 1, 1, 1, 1, 1, 8, 8, 1, 8,…\n$ bys7occ <int> 2, 8, 12, 5, 6, 13, 13, 18, 8, 6, 98, 98, 15, 9, 9, 6, 8, 98, …\n$ bys12   <int> 2, 1, 1, 1, 2, 1, 1, 2, 1, 1, 8, 8, 1, 1, 2, 2, 2, 8, 8, 2, 8,…\n$ bys18   <int> 1, 99, 99, 99, 99, 99, 99, 99, 99, 98, 99, 98, 8, 99, 99, 1, 9…\n$ bys20   <int> 1, 1, 1, 1, 1, 1, 1, 1, 1, 98, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1…\n```\n\n\n:::\n:::\n\n\n### Code Explanation\n- Only the first 10 columns are shown; the full dataset has 299 variables from the NELS:88 longitudinal study\n- Variable names follow NCES naming conventions: `by` = base year, `f1` = first follow-up\n\n### Output Interpretation\n- 2,000 rows represent a manageable subset of the full NELS:88 sample\n- Many variables are coded numerically; some special codes (e.g., 99, 98) represent missing or not-applicable values\n:::\n\n\n### alcohol1_pp {#sec-app-data-alcohol}\n\n**Adolescent alcohol use person-period data.**\n\n- **Source**: Adapted from longitudinal studies on adolescent substance use\n- **Context**: Person-period format data tracking alcohol use across multiple time points, suitable for longitudinal or growth-curve modeling.\n- **n**: 246 person-period observations\n\n| Variable | Type | Description |\n|:---------|:-----|:------------|\n| `id` | Numeric | Participant identifier |\n| `age` | Numeric | Age at measurement occasion |\n| `coa` | Numeric | Child of alcoholic (0 = no, 1 = yes) |\n| `male` | Numeric | Gender (1 = male, 0 = female) |\n| `age_14` | Numeric | Age centered at 14 |\n| `alcuse` | Numeric | Alcohol use frequency |\n| `peer` | Numeric | Peer alcohol use |\n| `cpeer` | Numeric | Centered peer alcohol use |\n| `ccoa` | Numeric | Centered COA indicator |\n\n::: {.panel-tabset}\n### R Code\n\n::: {.cell}\n\n```{.r .cell-code}\ndata(alcohol1_pp)\nglimpse(alcohol1_pp)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nRows: 246\nColumns: 9\n$ id     <int> 1, 1, 1, 2, 2, 2, 3, 3, 3, 4, 4, 4, 5, 5, 5, 6, 6, 6, 7, 7, 7, …\n$ age    <int> 14, 15, 16, 14, 15, 16, 14, 15, 16, 14, 15, 16, 14, 15, 16, 14,…\n$ coa    <int> 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, …\n$ male   <int> 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 0, 0, 1, 1, 1, 0, 0, 0, …\n$ age_14 <int> 0, 1, 2, 0, 1, 2, 0, 1, 2, 0, 1, 2, 0, 1, 2, 0, 1, 2, 0, 1, 2, …\n$ alcuse <dbl> 1.732051, 2.000000, 2.000000, 0.000000, 0.000000, 1.000000, 1.0…\n$ peer   <dbl> 1.2649111, 1.2649111, 1.2649111, 0.8944272, 0.8944272, 0.894427…\n$ cpeer  <dbl> 0.2469110, 0.2469110, 0.2469110, -0.1235728, -0.1235728, -0.123…\n$ ccoa   <dbl> 0.549, 0.549, 0.549, 0.549, 0.549, 0.549, 0.549, 0.549, 0.549, …\n```\n\n\n:::\n:::\n\n\n### Code Explanation\n- Person-period format: each row is one measurement occasion for one individual\n- Centered variables (`age_14`, `cpeer`, `ccoa`) are pre-computed for modeling convenience\n\n### Output Interpretation\n- 246 rows spanning multiple individuals across time points; `id` groups observations within the same person\n- `alcuse` and `peer` are the key outcome and predictor variables for longitudinal models\n:::\n\n\n### berk_sub {#sec-app-data-berksub}\n\n**UC Berkeley graduate admissions subset (Engineering and Psychology).**\n\n- **Source**: Bickel et al. (1975); UC Berkeley graduate admissions records\n- **Context**: A simplified two-department subset of the Berkeley admissions data, used to introduce logistic regression and illustrate Simpson's paradox.\n- **n**: 1,169 applicants\n\n| Variable | Type | Description |\n|:---------|:-----|:------------|\n| `admitted` | Numeric | Admission status (1 = admitted, 0 = rejected) |\n| `male` | Numeric | Gender (1 = male, 0 = female) |\n| `engineering` | Numeric | Department (1 = Engineering, 0 = Psychology) |\n\n::: {.panel-tabset}\n### R Code\n\n::: {.cell}\n\n```{.r .cell-code}\ndata(berk_sub)\nglimpse(berk_sub)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nRows: 1,169\nColumns: 3\n$ admitted    <int> 0, 0, 0, 0, 1, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0…\n$ male        <int> 1, 0, 1, 0, 1, 0, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1…\n$ engineering <int> 1, 1, 0, 0, 1, 1, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1…\n```\n\n\n:::\n:::\n\n\n### Code Explanation\n- A compact 3-variable dataset ideal for demonstrating logistic regression and confounding\n- `admitted` is the binary outcome; `male` and `engineering` are binary predictors\n\n### Output Interpretation\n- 1,169 rows with only 3 variables --- a clean dataset for illustrating how aggregated and disaggregated analyses can yield opposite conclusions (Simpson's paradox)\n:::\n\n\n### berkeley {#sec-app-data-berkeley}\n\n**UC Berkeley graduate admissions data (five departments).**\n\n- **Source**: Bickel et al. (1975); UC Berkeley graduate admissions records\n- **Context**: Admissions data across five departments, the classic dataset for demonstrating Simpson's paradox in logistic regression.\n- **n**: 3,593 applicants\n\n| Variable | Type | Description |\n|:---------|:-----|:------------|\n| `departme` | Character | Department identifier (A through E) |\n| `female` | Numeric | Gender (1 = female, 0 = male) |\n| `admitted` | Numeric | Admission status (1 = admitted, 0 = rejected) |\n\n::: {.panel-tabset}\n### R Code\n\n::: {.cell}\n\n```{.r .cell-code}\ndata(berkeley)\nglimpse(berkeley)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nRows: 3,593\nColumns: 3\n$ department <int> 1, 1, 2, 2, 3, 3, 4, 4, 5, 5, 1, 1, 2, 2, 3, 3, 4, 4, 5, 5,…\n$ female     <int> 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1,…\n$ admitted   <int> 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,…\n```\n\n\n:::\n:::\n\n\n### Code Explanation\n- The five-department version allows for richer analyses of confounding across multiple groups\n- `departme` should be converted to a factor for use as a categorical predictor\n\n### Output Interpretation\n- 3,593 rows across 5 departments; compare admission rates by gender within and across departments to observe Simpson's paradox\n:::\n\n\n### civic_ed {#sec-app-data-civiced}\n\n**Civic education study: pre-post survey data.**\n\n- **Source**: Adapted from civic education intervention studies\n- **Context**: Pre- and post-survey data from a civic education program, measuring attitudes toward government, political efficacy, tolerance, and civic participation.\n- **n**: 794 students in multiple schools\n\n| Variable | Type | Description |\n|:---------|:-----|:------------|\n| `id_match` | Numeric | Student identifier |\n| `school` | Numeric | School identifier |\n| `wtp` | Numeric | Willingness to participate indicator |\n| `t_q1`--`t_q99` | Numeric | Pre-test (treatment) survey items |\n| `r_q1`--`r_q84` | Numeric | Post-test (result) survey items |\n| `attn_pre`, `attn_pos` | Numeric | Attention composite (pre/post) |\n\n::: {.callout-note}\nThis is a wide dataset with 237 variables including individual survey items. Most analyses use composite scores (e.g., `attn_pre`, `inf_post`, `tol_t_m`) rather than individual items.\n:::\n\n::: {.panel-tabset}\n### R Code\n\n::: {.cell}\n\n```{.r .cell-code}\ndata(civic_ed)\nglimpse(civic_ed[, c(\"id_match\", \"school\", \"attn_pre\", \"attn_pos\")])\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nRows: 794\nColumns: 4\n$ id_match <int> 201180006, 201185023, 201185028, 211185008, 221180001, 221190…\n$ school   <chr> \"20\", \"20\", \"20\", \"21\", \"22\", \"22\", \"22\", \"22\", \"22\", \"23\", \"…\n$ attn_pre <dbl> -0.736738622, -0.292624533, 0.321411341, -0.007594591, -0.765…\n$ attn_pos <dbl> 0.17479886, -0.29936010, -0.19243185, -0.47762442, -0.3891652…\n```\n\n\n:::\n:::\n\n\n### Code Explanation\n- Showing only selected composite variables for readability; the full dataset has 237 columns\n- Composite scores ending in `_m` are scale means; `_pre`/`_pos` indicate measurement occasion\n\n### Output Interpretation\n- 794 rows represent individual students; `school` can be used as a grouping variable for multilevel analyses\n:::\n\n\n### classdata_07 {#sec-app-data-classdata}\n\n**Class survey data (2007).**\n\n- **Source**: In-class survey collected for instructional purposes\n- **Context**: A small survey dataset from a statistics class, useful for in-class demonstrations of basic regression.\n- **n**: 44 students\n\n| Variable | Type | Description |\n|:---------|:-----|:------------|\n| `actual_study` | Numeric | Actual hours of study per week |\n| `desired_study` | Numeric | Desired hours of study per week |\n| `actual_work` | Numeric | Actual hours of work per week |\n| `desired_work` | Numeric | Desired hours of work per week |\n| `gender` | Numeric | Gender |\n| `height` | Numeric | Height |\n| `desired_weight` | Numeric | Desired weight |\n| `exer` | Numeric | Hours of exercise per week |\n| `sleep` | Numeric | Hours of sleep per night |\n| `alcohol` | Numeric | Alcoholic drinks per week |\n| `overage` | Numeric | Over 25 years old (1 = yes) |\n| `age` | Numeric | Age in years |\n\n::: {.panel-tabset}\n### R Code\n\n::: {.cell}\n\n```{.r .cell-code}\ndata(classdata_07)\nglimpse(classdata_07)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nRows: 44\nColumns: 12\n$ actual_study   <int> 50, 40, 16, 30, 25, 20, 10, 20, 15, 45, 18, 40, 40, 35,…\n$ desired_study  <int> 65, 25, 25, 30, 15, 10, 2, 40, 20, 30, 24, 25, 20, 10, …\n$ actual_work    <int> 0, 10, 20, 0, 13, 10, 20, 5, 30, 20, 9, 10, 20, 20, 8, …\n$ desired_work   <int> 0, 20, 20, 0, 5, 10, 5, 5, 20, 10, 12, 0, 10, 0, 10, 20…\n$ gender         <int> 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0…\n$ height         <dbl> 64.0, 63.0, 67.0, 67.0, 65.0, 63.5, 65.0, 64.0, 63.0, 7…\n$ desired_weight <int> 127, 105, 125, 115, 125, 120, 170, 112, 112, 150, 150, …\n$ exer           <dbl> 4.0, 0.0, 6.0, 3.5, 4.0, 3.0, 5.0, 6.0, 3.0, 5.0, 4.0, …\n$ sleep          <dbl> 7.0, 7.0, 7.0, 8.0, 8.0, 7.5, 8.0, 8.0, 7.0, 7.0, 6.5, …\n$ alcohol        <int> 6, 0, 4, 7, 4, 0, 5, 2, 3, 8, 6, 1, 8, 1, 3, 0, 1, 4, 4…\n$ overage        <chr> \"no\", \"no\", \"no\", \"no\", \"no\", \"no\", \"no\", \"no\", \"no\", \"…\n$ age            <int> 0, 2, 0, 1, 1, 2, 2, 2, 2, 1, 2, 2, 1, 0, 1, 0, 0, 0, 0…\n```\n\n\n:::\n:::\n\n\n### Code Explanation\n- A small, intuitive dataset for hands-on classroom demonstrations\n- Variables are self-reported and easy to interpret\n\n### Output Interpretation\n- 44 rows and 12 columns --- small enough to view entirely with `print(classdata_07)`\n- Good for demonstrating simple regression, scatterplots, and correlation\n:::\n\n\n### disc {#sec-app-data-disc}\n\n**NELS:88 discipline and school experiences study.**\n\n- **Source**: National Education Longitudinal Study of 1988 (NCES)\n- **Context**: Subset of NELS:88 focusing on disciplinary outcomes and school experiences, used for logistic regression modeling.\n- **n**: 2,000 students\n\n| Variable | Type | Description |\n|:---------|:-----|:------------|\n| `sentoff` | Numeric | Ever sent to the office (0 = no, 1 = yes) |\n| `male` | Numeric | Gender (1 = male, 0 = female) |\n| `race` | Numeric | Race/ethnicity code |\n| `fath_ed` | Numeric | Father's education level |\n| `moth_ed` | Numeric | Mother's education level |\n| `bedroom` | Numeric | Has own bedroom (0 = no, 1 = yes) |\n| `discuss` | Numeric | Discusses school with parents (0 = no, 1 = yes) |\n| `osentoff` | Numeric | Number of times sent to the office |\n\n::: {.panel-tabset}\n### R Code\n\n::: {.cell}\n\n```{.r .cell-code}\ndata(disc)\nglimpse(disc)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nRows: 2,000\nColumns: 15\n$ bys55a   <int> 0, 0, 0, 0, 1, 0, 0, 1, 0, 2, 1, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0…\n$ bys12    <int> 2, 1, 1, 1, 2, 1, 1, 2, 1, 1, 8, 8, 1, 1, 2, 2, 2, 8, 8, 2, 8…\n$ bys31a   <int> 4, 4, 4, 4, 3, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4…\n$ bys34a   <int> 1, 2, 3, 2, 2, 4, 6, 5, 2, 1, 7, 2, 1, NA, 6, 5, NA, 7, 5, NA…\n$ bys34b   <int> 2, 2, 3, 2, 3, 1, NA, 2, 2, 1, 5, 2, 5, 2, 6, 5, 6, 6, 5, NA,…\n$ bys35p   <int> 1, 1, 1, 1, 2, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 1, 1, 2, 1, 1…\n$ bys36c   <int> 3, 3, 2, 3, 2, 3, 3, 3, 3, 2, 3, 1, 3, 2, 2, 3, 3, 1, 3, 2, 3…\n$ sentoff  <int> 0, 0, 0, 0, 1, 0, 0, 1, 0, 1, 1, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0…\n$ male     <int> 0, 1, 1, 1, 0, 1, 1, 0, 1, 1, NA, NA, 1, 1, 0, 0, 0, NA, NA, …\n$ race     <fct> White, White, White, White, Black, White, White, White, White…\n$ fath_ed  <int> 0, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 0, NA, 1, 1, NA, 1, 1, NA…\n$ moth_ed  <int> 1, 1, 1, 1, 1, 0, NA, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, NA,…\n$ bedroom  <int> 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 0, 1, 1…\n$ discuss  <int> 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0…\n$ osentoff <int> 0, 0, 0, 0, 1, 0, 0, 1, 0, 2, 1, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0…\n```\n\n\n:::\n:::\n\n\n### Code Explanation\n- `sentoff` is a binary outcome suitable for logistic regression; `osentoff` is a count version of the same variable\n- `disc2` is a companion dataset that adds achievement score variables\n\n### Output Interpretation\n- 2,000 rows and 15 variables; binary outcomes (`sentoff`) and count outcomes (`osentoff`) allow for comparing logistic and count regression approaches\n:::\n\n\n### disc2 {#sec-app-data-disc2}\n\n**NELS:88 discipline study with achievement scores.**\n\n- **Source**: National Education Longitudinal Study of 1988 (NCES)\n- **Context**: Extended version of `disc` that includes reading and math achievement scores, allowing for richer models.\n- **n**: 2,000 students\n\n| Variable | Type | Description |\n|:---------|:-----|:------------|\n| `sentoff` | Numeric | Ever sent to the office (0 = no, 1 = yes) |\n| `ses` | Numeric | Socioeconomic status composite |\n| `reading1` | Numeric | Reading score (base year) |\n| `math1` | Numeric | Math score (base year) |\n| `reading2` | Numeric | Reading score (follow-up) |\n| `minority` | Numeric | Minority status (0 = no, 1 = yes) |\n\n::: {.panel-tabset}\n### R Code\n\n::: {.cell}\n\n```{.r .cell-code}\ndata(disc2)\nglimpse(disc2)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nRows: 2,000\nColumns: 15\n$ male      <int> 0, 1, 1, 1, 0, 1, 1, 0, 1, 1, NA, NA, 1, 1, 0, 0, 0, NA, NA,…\n$ notengl   <int> 0, 0, 0, 0, 0, 0, 0, 0, 0, NA, 0, NA, 0, 0, 0, 0, 0, 0, 0, 1…\n$ bedroom   <int> 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 0, 1, …\n$ osentoff  <int> 0, 0, 0, 0, 1, 0, 0, 1, 0, 2, 1, 1, 1, 1, 0, 0, 0, 0, 0, 0, …\n$ ses       <dbl> -0.601, -0.070, 0.096, -0.715, 0.205, 0.355, 1.369, 0.611, -…\n$ reading1  <dbl> 66.85, 58.58, 49.46, 55.60, 56.26, 52.22, 57.12, 62.65, 38.6…\n$ math1     <dbl> 58.63, 59.85, 49.65, 49.09, 44.46, 54.76, 61.04, 52.31, 39.9…\n$ reading2  <dbl> 50.17, 61.57, 44.00, 40.73, 53.71, 43.31, 53.50, 52.30, 40.2…\n$ fath_coll <int> 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 1, 0, 0, NA, 1, 1, NA, 1, 1, N…\n$ fath_ed   <int> 0, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 0, NA, 1, 1, NA, 1, 1, N…\n$ moth_coll <int> 0, 0, 0, 0, 0, 0, NA, 0, 0, 0, 1, 0, 1, 0, 1, 1, 1, 1, 1, NA…\n$ moth_ed   <int> 1, 1, 1, 1, 1, 0, NA, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, NA…\n$ minority  <int> 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, …\n$ race      <fct> White, White, White, White, Black, White, White, White, Whit…\n$ sentoff   <int> 0, 0, 0, 0, 1, 0, 0, 1, 0, 1, 1, 1, 1, 1, 0, 0, 0, 0, 0, 0, …\n```\n\n\n:::\n:::\n\n\n### Code Explanation\n- Extends `disc` with continuous achievement variables (`reading1`, `math1`, `reading2`)\n- `ses` is a continuous composite; `minority` is binary\n\n### Output Interpretation\n- 2,000 rows and 15 variables; contains some missing values (`NA`) in education and achievement variables\n:::\n\n\n### gss_1 {#sec-app-data-gss}\n\n**General Social Survey data.**\n\n- **Source**: National Opinion Research Center (NORC), General Social Survey\n- **Context**: Survey data on social attitudes, demographics, and behavior from a representative sample of U.S. adults.\n- **n**: 2,832 respondents\n\n| Variable | Type | Description |\n|:---------|:-----|:------------|\n| `abortion` | Numeric | Abortion attitude scale |\n| `cohabit` | Numeric | Cohabitation attitude |\n| `income` | Numeric | Income category |\n| `conserv` | Numeric | Political conservatism scale |\n| `educat` | Numeric | Years of education |\n| `male` | Numeric | Gender (1 = male, 0 = female) |\n| `respage` | Numeric | Respondent age |\n| `relosity` | Numeric | Religiosity composite score |\n\n::: {.panel-tabset}\n### R Code\n\n::: {.cell}\n\n```{.r .cell-code}\ndata(gss_1)\nglimpse(gss_1)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nRows: 2,832\nColumns: 16\n$ abortion <dbl> NA, NA, NA, 3.000000, 7.000000, 5.600000, NA, NA, 7.000000, 7…\n$ cohabit  <int> 7, 9, 3, 8, NA, NA, NA, 9, 4, NA, NA, NA, NA, 6, 8, 4, 6, 8, …\n$ income   <int> 18, 11, 21, 11, 18, NA, 18, 17, NA, 20, 19, 16, 5, 18, NA, 6,…\n$ conserv  <int> 4, 2, 6, 2, 4, 4, 4, 4, 5, 5, 3, 2, 4, 3, 4, 7, 1, 6, 2, 6, 6…\n$ educat   <int> 12, 17, 12, 13, 16, 16, 12, 13, 18, 15, 12, 15, 14, 20, 12, 1…\n$ male     <int> 1, 0, 1, 1, 0, 1, 1, 1, 0, 1, 1, 0, 0, 1, 0, 1, 0, 0, 1, 1, 1…\n$ maed     <int> 12, NA, 12, 12, 12, 6, 12, 12, 12, 12, 12, 8, 12, 8, 12, 6, 4…\n$ paed     <int> 12, 20, 12, NA, NA, 9, 14, 16, 16, 16, 12, NA, NA, 12, 12, 6,…\n$ marital  <int> 3, 5, 1, 5, 5, 3, 4, 5, 1, 3, 5, 1, 3, 1, 5, 1, 3, 2, 4, 1, 1…\n$ partnrs5 <int> 1, 0, 1, 7, 2, 5, 3, 2, 1, 2, 3, NA, 1, 1, 5, 1, 1, NA, 2, 1,…\n$ respage  <dbl> 60, 27, 36, 21, 35, 33, 43, 29, 39, 45, 29, 41, 32, 48, 20, 4…\n$ race     <int> 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 1, 1, 1, 3, 3, 3, 3, 1, 1…\n$ black    <int> 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0…\n$ othrace  <int> 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 0, 0…\n$ relosity <dbl> -2.42487907, -3.80991101, 3.80089211, 0.50612688, -0.96002108…\n$ religion <int> 4, 1, 1, 2, 4, 1, 1, 4, 1, 1, 2, 1, 1, 1, 2, 1, 2, 2, 1, 2, 1…\n```\n\n\n:::\n:::\n\n\n### Code Explanation\n- A rich survey dataset with attitudinal, demographic, and behavioral variables\n- Contains some missing values; check with `colSums(is.na(gss_1))` before modeling\n\n### Output Interpretation\n- 2,832 rows and 16 variables covering a broad range of social science topics\n- Suitable for multiple regression examples examining how demographics predict attitudes\n:::\n\n\n### hsbs1 {#sec-app-data-hsbs1}\n\n**High School and Beyond survey (full sample).**\n\n- **Source**: National Center for Education Statistics (NCES), High School and Beyond\n- **Context**: A larger sample from the HS&B study with psychometric composites (locus of control, self-concept, motivation) and achievement scores.\n- **n**: 350 students\n\n| Variable | Type | Description |\n|:---------|:-----|:------------|\n| `id` | Numeric | Student identifier |\n| `gender` | Numeric | Gender (1 = male, 2 = female) |\n| `race` | Numeric | Race/ethnicity code |\n| `ses` | Numeric | Socioeconomic status (1 = low, 2 = middle, 3 = high) |\n| `prog` | Numeric | Program type (1 = academic, 2 = general, 3 = vocational) |\n| `locus` | Numeric | Locus of control composite |\n| `concept` | Numeric | Self-concept composite |\n| `read` | Numeric | Reading achievement score |\n| `math` | Numeric | Math achievement score |\n| `sci` | Numeric | Science achievement score |\n\n::: {.panel-tabset}\n### R Code\n\n::: {.cell}\n\n```{.r .cell-code}\ndata(hsbs1)\nglimpse(hsbs1)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nRows: 350\nColumns: 16\n$ id      <int> 303, 404, 225, 553, 433, 189, 336, 321, 358, 422, 461, 593, 34…\n$ gender  <int> 2, 2, 1, 1, 2, 2, 1, 1, 2, 2, 1, 1, 2, 2, 2, 1, 2, 2, 2, 2, 2,…\n$ race    <int> 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 1, 4, 4, 4, 4,…\n$ ses     <int> 1, 2, 2, 2, 2, 3, 3, 1, 3, 2, 1, 2, 2, 3, 1, 3, 3, 2, 1, 3, 1,…\n$ sch     <int> 1, 1, 1, 2, 1, 1, 1, 1, 1, 1, 1, 2, 1, 2, 1, 2, 2, 1, 1, 1, 1,…\n$ prog    <int> 1, 1, 2, 2, 3, 2, 1, 3, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 1, 2, 2,…\n$ locus   <dbl> -0.84, -0.38, 0.89, 0.71, -0.64, 1.11, 0.06, -0.91, 0.45, 0.00…\n$ concept <dbl> -0.24, -0.47, 0.59, 0.28, 0.03, 0.90, 0.03, -0.59, 0.03, 0.03,…\n$ mot     <dbl> 1.00, 0.67, 0.67, 0.67, 1.00, 0.33, 0.67, 0.67, 1.00, 0.67, 0.…\n$ career  <int> 4, 4, 6, 16, 4, 6, 11, 8, 4, 9, 16, 11, 9, 1, 9, 9, 9, 15, 5, …\n$ read    <dbl> 54.8, 62.7, 60.6, 62.7, 41.6, 62.7, 41.6, 44.2, 62.7, 62.7, 70…\n$ write   <dbl> 64.5, 43.7, 56.7, 56.7, 46.3, 64.5, 39.1, 39.1, 51.5, 64.5, 43…\n$ math    <dbl> 44.5, 44.7, 70.5, 54.7, 38.4, 61.4, 56.3, 46.3, 54.4, 38.3, 58…\n$ sci     <dbl> 52.6, 52.6, 58.0, 58.0, 36.3, 58.0, 45.0, 36.3, 49.8, 55.8, 66…\n$ ss      <dbl> 50.6, 41.9, 65.5, 40.6, 45.6, 60.5, 50.6, 40.6, 50.6, 55.6, 60…\n$ sample  <int> 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,…\n```\n\n\n:::\n:::\n\n\n### Code Explanation\n- Extends `hsb_sub` with psychometric variables (`locus`, `concept`, `mot`) and additional achievement measures\n- Numeric codes for `gender`, `race`, `ses`, and `prog` should be converted to factors for modeling\n\n### Output Interpretation\n- 350 rows and 16 variables; includes both categorical predictors (coded numerically) and continuous achievement/psychometric outcomes\n:::\n\n\n### individuals {#sec-app-data-individuals}\n\n**Bureau of Labor Statistics March 2000 CPS individual data.**\n\n- **Source**: Current Population Survey (CPS), Bureau of Labor Statistics\n- **Context**: Individual-level labor market data including earnings, education, and demographic characteristics. Useful for wage regression and labor economics examples.\n- **n**: 55,899 individuals\n\n| Variable | Type | Description |\n|:---------|:-----|:------------|\n| `id` | Numeric | Individual identifier |\n| `age` | Numeric | Age in years |\n| `educ` | Numeric | Education level code |\n| `sex` | Numeric | Sex (1 = male, 2 = female) |\n| `earn` | Numeric | Annual earnings (dollars) |\n| `job` | Numeric | Job category code |\n\n::: {.panel-tabset}\n### R Code\n\n::: {.cell}\n\n```{.r .cell-code}\ndata(individuals)\nglimpse(individuals)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nRows: 55,899\nColumns: 6\n$ id   <int> 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19…\n$ age  <int> 25, 25, 25, 25, 25, 25, 25, 25, 25, 25, 25, 25, 25, 25, 25, 25, 2…\n$ educ <int> 2, 5, 4, 3, 4, 4, 4, 5, 3, 5, 3, 1, 2, 4, 5, 5, 3, 5, 4, 6, 3, 5,…\n$ sex  <int> 2, 1, 2, 2, 1, 1, 2, 2, 1, 2, 2, 2, 2, 2, 2, 2, 1, 2, 2, 2, 1, 2,…\n$ earn <int> 7234, 37413, 29500, 13500, 17660, 37250, 20005, 50602, 10400, 249…\n$ job  <int> 5, 5, 5, 5, 6, 5, 5, 6, 5, 6, 5, 5, 5, 5, 5, 5, 5, 5, 5, 6, 5, 5,…\n```\n\n\n:::\n:::\n\n\n### Code Explanation\n- A large dataset useful for demonstrating regression with large sample sizes\n- `earn` is the typical outcome variable; `educ`, `age`, and `sex` are common predictors\n\n### Output Interpretation\n- 55,899 rows --- the largest dataset in the package; useful for demonstrating large-sample regression properties\n- `earn` likely has a right-skewed distribution; consider log transformation\n:::\n\n\n### lambert {#sec-app-data-lambert}\n\n**Lambert longitudinal study data.**\n\n- **Source**: Lambert longitudinal child development study\n- **Context**: Longitudinal data tracking children's behavioral, psychological, and social development from childhood through adulthood. Contains teacher ratings, parent ratings, and adult outcome measures.\n- **n**: 492 participants\n\n| Variable | Type | Description |\n|:---------|:-----|:------------|\n| `pupil` | Character | Participant identifier |\n| `rclass` | Numeric | Classroom identifier |\n| `byear` | Numeric | Birth year |\n| `b3005` | Character | Sex (F/M) |\n| `ethnic` | Numeric | Ethnicity code |\n| `tagg`--`tadhd` | Numeric | Teacher-rated behavior scales |\n| `depress`, `anxiety` | Numeric | Adult mental health outcomes |\n\n::: {.callout-note}\nThis is a wide dataset with 109 variables spanning multiple developmental periods. Most analyses use selected subsets of variables.\n:::\n\n::: {.panel-tabset}\n### R Code\n\n::: {.cell}\n\n```{.r .cell-code}\ndata(lambert)\nglimpse(lambert[, 1:10])\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nRows: 492\nColumns: 10\n$ pupil  <chr> \"AI500D\", \"AL120\", \"AL255\", \"AL500D\", \"AM600\", \"AN120\", \"AN180\"…\n$ rclass <int> 1, 6, 7, 1, 5, 5, 1, 6, 1, 5, 2, 6, 7, 1, 5, 6, 6, 6, 5, 5, 1, …\n$ byear  <int> 63, 65, 67, 68, 65, 64, 67, 65, 64, 67, 64, 66, 67, 67, 64, 64,…\n$ b3005  <chr> \"F\", \"M\", \"M\", \"M\", \"F\", \"M\", \"M\", \"M\", \"M\", \"M\", \"M\", \"M\", \"M\"…\n$ ethnic <int> 1, 1, 1, 2, 2, 1, 1, 1, 1, 1, 1, 1, 1, 3, 1, 1, 1, 1, 2, 1, 1, …\n$ hm1    <chr> \"Y\", \"N\", \"N\", \"Y\", \"N\", \"N\", \"Y\", \"N\", \"Y\", \"N\", \"Y\", \"N\", \"N\"…\n$ fs001  <dbl> 0.570, -0.167, -0.685, -0.730, -0.382, -0.727, -0.450, 0.382, 2…\n$ fs004  <dbl> -0.019, 0.354, 0.857, -0.429, -0.241, 0.133, 0.732, 0.457, -0.4…\n$ fs006  <dbl> -1.009, 0.056, -0.920, -0.899, 0.519, 0.424, -0.974, 0.088, -0.…\n$ fs011  <dbl> -0.930, 0.397, -1.439, -0.691, 0.340, 1.412, -1.108, -0.251, -0…\n```\n\n\n:::\n:::\n\n\n### Code Explanation\n- Showing only the first 10 of 109 variables; includes childhood predictors and adult outcomes\n- Variable prefixes indicate the source: `t` = teacher rating, `p` = parent rating, `wh` = adult well-being\n\n### Output Interpretation\n- 492 rows; a moderate-sized longitudinal dataset with many potential predictor-outcome combinations\n:::\n\n\n### pisa2000 {#sec-app-data-pisa}\n\n**PISA 2000 international reading assessment data.**\n\n- **Source**: OECD Programme for International Student Assessment (PISA) 2000\n- **Context**: International reading assessment data from 15-year-olds in the UK, Germany, and USA, including student background and school characteristics.\n- **n**: 4,528 students\n\n| Variable | Type | Description |\n|:---------|:-----|:------------|\n| `country` | Character | Country code |\n| `female` | Numeric | Gender (1 = female, 0 = male) |\n| `isei` | Numeric | International Socio-Economic Index of occupational status |\n| `wleread` | Numeric | Reading proficiency score (continuous) |\n| `pass_rea` | Numeric | Passed reading threshold (0 = no, 1 = yes) |\n| `uk` | Numeric | UK indicator (1 = yes) |\n| `germany` | Numeric | Germany indicator (1 = yes) |\n| `usa` | Numeric | USA indicator (1 = yes) |\n\n::: {.panel-tabset}\n### R Code\n\n::: {.cell}\n\n```{.r .cell-code}\ndata(pisa2000)\nglimpse(pisa2000)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nRows: 4,528\nColumns: 15\n$ country  <chr> \"826\", \"826\", \"826\", \"826\", \"826\", \"826\", \"826\", \"826\", \"826\"…\n$ female   <int> 0, 1, 0, 0, 0, 0, 0, 1, 1, 0, 1, 0, 1, 1, 1, 1, 0, 1, 0, 1, 1…\n$ isei     <int> 30, 30, 61, 34, 23, 51, 67, 29, 55, 70, 47, 30, 52, 25, 40, 4…\n$ wleread  <dbl> 539.39, 598.80, 501.85, 555.34, 464.52, 565.31, 578.25, 357.2…\n$ high_sch <int> 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0…\n$ college  <int> 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 1, 1, 1, 0, 1, 0…\n$ one_for  <int> 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0…\n$ both_for <int> 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0…\n$ test_lan <int> 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1…\n$ reading  <int> 3, 4, 3, 4, 2, 4, 4, 1, 5, 1, 3, 2, 4, 4, 5, 5, 3, 3, 3, 5, 2…\n$ pass_rea <int> 0, 1, 0, 1, 0, 1, 1, 0, 1, 0, 0, 0, 1, 1, 1, 1, 0, 0, 0, 1, 0…\n$ id_schoo <int> 373, 140, 268, 192, 337, 136, 219, 374, 176, 482, 340, 373, 2…\n$ uk       <int> 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1…\n$ germany  <int> 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0…\n$ usa      <int> 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0…\n```\n\n\n:::\n:::\n\n\n### Code Explanation\n- Country indicators (`uk`, `germany`, `usa`) are pre-coded dummy variables\n- `wleread` is the continuous reading proficiency; `pass_rea` is a dichotomized version suitable for logistic regression\n\n### Output Interpretation\n- 4,528 rows across 3 countries; compare reading proficiency across nations with regression models\n- `isei` provides a continuous measure of socioeconomic status\n:::\n\n\n### reading {#sec-app-data-reading}\n\n**Reading comprehension instruction experiment.**\n\n- **Source**: Adapted from educational intervention studies\n- **Context**: Experimental study comparing reading instruction methods (Basal, DRTA, Strat) with pre- and post-test measures.\n- **n**: 66 students\n\n| Variable | Type | Description |\n|:---------|:-----|:------------|\n| `subject` | Numeric | Student identifier |\n| `group` | Character | Instructional method (Basal, DRTA, Strat) |\n| `pre1`, `pre2` | Numeric | Pre-test scores |\n| `post1`, `post2`, `post3` | Numeric | Post-test scores |\n| `method` | Numeric | Numeric method code |\n\n::: {.panel-tabset}\n### R Code\n\n::: {.cell}\n\n```{.r .cell-code}\ndata(reading)\nglimpse(reading)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nRows: 66\nColumns: 8\n$ subject <int> 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18,…\n$ group   <chr> \"Basal\", \"Basal\", \"Basal\", \"Basal\", \"Basal\", \"Basal\", \"Basal\",…\n$ pre1    <int> 4, 6, 9, 12, 16, 15, 14, 12, 12, 8, 13, 9, 12, 12, 12, 10, 8, …\n$ pre2    <int> 3, 5, 4, 6, 5, 13, 8, 7, 3, 8, 7, 2, 5, 2, 2, 10, 5, 5, 3, 4, …\n$ post1   <int> 5, 9, 5, 8, 10, 9, 12, 5, 8, 7, 12, 4, 4, 8, 6, 9, 3, 5, 4, 2,…\n$ post2   <int> 4, 5, 3, 5, 9, 8, 5, 5, 7, 7, 4, 4, 6, 8, 4, 10, 3, 5, 5, 3, 4…\n$ post3   <int> 41, 41, 43, 46, 46, 45, 45, 32, 33, 39, 42, 45, 39, 44, 36, 49…\n$ method  <int> 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,…\n```\n\n\n:::\n:::\n\n\n### Code Explanation\n- `group` is a character variable with three levels; convert to factor for ANOVA or regression\n- Multiple pre- and post-test scores allow for examining treatment effects from different angles\n\n### Output Interpretation\n- 66 rows across 3 groups --- a small experimental dataset ideal for ANOVA demonstrations\n- `group` identifies the treatment condition; compare post-test scores controlling for pre-test performance\n:::\n\n\n### womenlf {#sec-app-data-womenlf}\n\n**Canadian women's labor force participation.**\n\n- **Source**: Canadian Survey of Consumer Finances; Fox (2008)\n- **Context**: Women's labor force participation decisions (not working, part-time, full-time) as a function of husband's income, region, and presence of children. Classic dataset for multinomial logit.\n- **n**: 263 women\n\n| Variable | Type | Description |\n|:---------|:-----|:------------|\n| `obs` | Numeric | Observation number |\n| `husbinc` | Numeric | Husband's income (thousands of dollars) |\n| `region` | Character | Canadian region (e.g., Ontario, Quebec) |\n| `workstat` | Numeric | Work status (0 = not working, 1 = part-time, 2 = full-time) |\n| `chilpres` | Numeric | Children present (0 = no, 1 = yes) |\n\n::: {.panel-tabset}\n### R Code\n\n::: {.cell}\n\n```{.r .cell-code}\ndata(womenlf)\nglimpse(womenlf)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nRows: 263\nColumns: 5\n$ obs      <int> 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18…\n$ husbinc  <int> 15, 13, 45, 23, 19, 7, 15, 7, 15, 23, 23, 13, 9, 9, 45, 15, 5…\n$ region   <chr> \"Ontario\", \"Ontario\", \"Ontario\", \"Ontario\", \"Ontario\", \"Ontar…\n$ workstat <int> 0, 0, 0, 0, 0, 0, 0, 2, 0, 0, 0, 2, 0, 0, 0, 0, 0, 0, 0, 0, 1…\n$ chilpres <int> 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 0…\n```\n\n\n:::\n:::\n\n\n### Code Explanation\n- `workstat` has 3 categories, making this suitable for multinomial logistic regression (`nnet::multinom()`)\n- `region` is a character variable; convert to factor for use as a predictor\n\n### Output Interpretation\n- 263 rows and 5 variables --- a compact dataset with a 3-category outcome\n- For multinomial logit, convert `workstat` to a factor with meaningful labels: `factor(workstat, labels = c(\"not working\", \"part-time\", \"full-time\"))`\n:::\n\n\n## Loading Any Dataset {#sec-app-data-loading}\n\nTo use any dataset from this book in your own analysis:\n\n::: {.panel-tabset}\n### R Code\n```r\n# Load the regdatasets package\nlibrary(regdatasets)\n\n# Load a specific dataset\ndata(gcse)\n\n# Or load and assign to a custom name\nmy_data <- regdatasets::gcse\n```\n\n### Code Explanation\n- `data(gcse)` loads the dataset into an object named `gcse` in your environment\n- You can also use `regdatasets::gcse` to access it directly with the package prefix, which is useful when you want to assign it to a different name\n\n### Output Interpretation\n- After `data(gcse)`, you will see `gcse` appear in your Environment pane (top-right in RStudio)\n- Using `regdatasets::gcse` does not add the object to your environment until you assign it with `<-`\n:::\n\n::: {.callout-tip}\n## Exploring a Dataset\nFor any dataset, use this quick exploration workflow:\n\n```r\ndata(gcse)          # Load\nglimpse(gcse)       # Structure\nsummary(gcse)       # Descriptive statistics\nhead(gcse, 10)      # First 10 rows\n```\n:::\n",
    "supporting": [],
    "filters": [
      "rmarkdown/pagebreak.lua"
    ],
    "includes": {},
    "engineDependencies": {},
    "preserve": {},
    "postProcess": true
  }
}