{
  "hash": "c3ab28f4dabfd5dcb823bdaf7643f81e",
  "result": {
    "engine": "knitr",
    "markdown": "# Linear Regression Example: Results & Discussion {#sec-linear-results}\n\n\n\n\n::: {.callout-note}\n## About This Chapter\nThis chapter demonstrates **Parts 4--6** of the linear regression project\n(Descriptive Statistics, Results, and Discussion). This is the main analysis\nchapter --- the heart of the project. Every code block runs on the PIAAC Korea\ndataset and produces real output, so you can follow along step by step.\n:::\n\n\n## Part 4: Descriptive Analysis {#sec-linear-ex-part4}\n\n::: {.callout-important}\n## Guideline Reminder --- Part 4\nBefore running any regressions, describe your data. Report the sample size,\npresent summary statistics for all continuous variables (mean, SD, min, max)\nand frequency tables for categorical variables, and include exploratory\nvisualizations that preview the relationships you will model.\n:::\n\n### Sample Overview {#sec-linear-ex-sample-overview}\n\nWe begin by loading the analysis dataset and confirming the sample size.\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Load the PIAAC Korea analysis dataset\npiaac <- readRDS(here::here(\"data\", \"piaac_kor.rds\"))\n\n# Confirm sample size and check for missing data\ncat(\"Sample size:\", nrow(piaac), \"\\n\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nSample size: 1357 \n```\n\n\n:::\n\n```{.r .cell-code}\ncat(\"Variables:  \", ncol(piaac), \"\\n\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nVariables:   21 \n```\n\n\n:::\n\n```{.r .cell-code}\ncat(\"Missing values:\", sum(is.na(piaac)), \"\\n\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nMissing values: 0 \n```\n\n\n:::\n:::\n\n\nThe analytic sample contains **N = 1,357** Korean full-time workers aged\n35--54 with complete data on all analysis variables. Because we constructed a\ncomplete-case dataset during data preparation, there are no missing values.\n\n### Continuous Variables {#sec-linear-ex-continuous}\n\n@tbl-desc-continuous presents summary statistics for the four key continuous\nvariables: log-income, years of education, work experience, and numeracy.\n\n\n::: {#tbl-desc-continuous .cell tbl-cap='Descriptive Statistics for Continuous Variables'}\n\n```{.r .cell-code}\npiaac |>\n  select(ln_inc, schyrs, exper, numeracy) |>\n  tbl_summary(\n    type = everything() ~ \"continuous\",\n    statistic = all_continuous() ~ \"{mean} ({sd})\",\n    label = list(\n      ln_inc   ~ \"Log monthly income\",\n      schyrs   ~ \"Years of education\",\n      exper    ~ \"Work experience (years)\",\n      numeracy ~ \"Numeracy (z-score)\"\n    ),\n    digits = everything() ~ 2\n  ) |>\n  bold_labels()\n```\n\n::: {.cell-output-display}\n\n```{=html}\n<div id=\"acawcqxvtj\" style=\"padding-left:0px;padding-right:0px;padding-top:10px;padding-bottom:10px;overflow-x:auto;overflow-y:auto;width:auto;height:auto;\">\n<style>#acawcqxvtj table {\n  font-family: system-ui, 'Segoe UI', Roboto, Helvetica, Arial, sans-serif, 'Apple Color Emoji', 'Segoe UI Emoji', 'Segoe UI Symbol', 'Noto Color Emoji';\n  -webkit-font-smoothing: antialiased;\n  -moz-osx-font-smoothing: grayscale;\n}\n\n#acawcqxvtj thead, #acawcqxvtj tbody, #acawcqxvtj tfoot, #acawcqxvtj tr, #acawcqxvtj td, #acawcqxvtj th {\n  border-style: none;\n}\n\n#acawcqxvtj p {\n  margin: 0;\n  padding: 0;\n}\n\n#acawcqxvtj .gt_table {\n  display: table;\n  border-collapse: collapse;\n  line-height: normal;\n  margin-left: auto;\n  margin-right: auto;\n  color: #333333;\n  font-size: 16px;\n  font-weight: normal;\n  font-style: normal;\n  background-color: #FFFFFF;\n  width: auto;\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #A8A8A8;\n  border-right-style: none;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #A8A8A8;\n  border-left-style: none;\n  border-left-width: 2px;\n  border-left-color: #D3D3D3;\n}\n\n#acawcqxvtj .gt_caption {\n  padding-top: 4px;\n  padding-bottom: 4px;\n}\n\n#acawcqxvtj .gt_title {\n  color: #333333;\n  font-size: 125%;\n  font-weight: initial;\n  padding-top: 4px;\n  padding-bottom: 4px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-bottom-color: #FFFFFF;\n  border-bottom-width: 0;\n}\n\n#acawcqxvtj .gt_subtitle {\n  color: #333333;\n  font-size: 85%;\n  font-weight: initial;\n  padding-top: 3px;\n  padding-bottom: 5px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-top-color: #FFFFFF;\n  border-top-width: 0;\n}\n\n#acawcqxvtj .gt_heading {\n  background-color: #FFFFFF;\n  text-align: center;\n  border-bottom-color: #FFFFFF;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n}\n\n#acawcqxvtj .gt_bottom_border {\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n}\n\n#acawcqxvtj .gt_col_headings {\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n}\n\n#acawcqxvtj .gt_col_heading {\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: normal;\n  text-transform: inherit;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n  vertical-align: bottom;\n  padding-top: 5px;\n  padding-bottom: 6px;\n  padding-left: 5px;\n  padding-right: 5px;\n  overflow-x: hidden;\n}\n\n#acawcqxvtj .gt_column_spanner_outer {\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: normal;\n  text-transform: inherit;\n  padding-top: 0;\n  padding-bottom: 0;\n  padding-left: 4px;\n  padding-right: 4px;\n}\n\n#acawcqxvtj .gt_column_spanner_outer:first-child {\n  padding-left: 0;\n}\n\n#acawcqxvtj .gt_column_spanner_outer:last-child {\n  padding-right: 0;\n}\n\n#acawcqxvtj .gt_column_spanner {\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  vertical-align: bottom;\n  padding-top: 5px;\n  padding-bottom: 5px;\n  overflow-x: hidden;\n  display: inline-block;\n  width: 100%;\n}\n\n#acawcqxvtj .gt_spanner_row {\n  border-bottom-style: hidden;\n}\n\n#acawcqxvtj .gt_group_heading {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: initial;\n  text-transform: inherit;\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n  vertical-align: middle;\n  text-align: left;\n}\n\n#acawcqxvtj .gt_empty_group_heading {\n  padding: 0.5px;\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: initial;\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  vertical-align: middle;\n}\n\n#acawcqxvtj .gt_from_md > :first-child {\n  margin-top: 0;\n}\n\n#acawcqxvtj .gt_from_md > :last-child {\n  margin-bottom: 0;\n}\n\n#acawcqxvtj .gt_row {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  margin: 10px;\n  border-top-style: solid;\n  border-top-width: 1px;\n  border-top-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n  vertical-align: middle;\n  overflow-x: hidden;\n}\n\n#acawcqxvtj .gt_stub {\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: initial;\n  text-transform: inherit;\n  border-right-style: solid;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#acawcqxvtj .gt_stub_row_group {\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: initial;\n  text-transform: inherit;\n  border-right-style: solid;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n  padding-left: 5px;\n  padding-right: 5px;\n  vertical-align: top;\n}\n\n#acawcqxvtj .gt_row_group_first td {\n  border-top-width: 2px;\n}\n\n#acawcqxvtj .gt_row_group_first th {\n  border-top-width: 2px;\n}\n\n#acawcqxvtj .gt_summary_row {\n  color: #333333;\n  background-color: #FFFFFF;\n  text-transform: inherit;\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#acawcqxvtj .gt_first_summary_row {\n  border-top-style: solid;\n  border-top-color: #D3D3D3;\n}\n\n#acawcqxvtj .gt_first_summary_row.thick {\n  border-top-width: 2px;\n}\n\n#acawcqxvtj .gt_last_summary_row {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n}\n\n#acawcqxvtj .gt_grand_summary_row {\n  color: #333333;\n  background-color: #FFFFFF;\n  text-transform: inherit;\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#acawcqxvtj .gt_first_grand_summary_row {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-top-style: double;\n  border-top-width: 6px;\n  border-top-color: #D3D3D3;\n}\n\n#acawcqxvtj .gt_last_grand_summary_row_top {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-bottom-style: double;\n  border-bottom-width: 6px;\n  border-bottom-color: #D3D3D3;\n}\n\n#acawcqxvtj .gt_striped {\n  background-color: rgba(128, 128, 128, 0.05);\n}\n\n#acawcqxvtj .gt_table_body {\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n}\n\n#acawcqxvtj .gt_footnotes {\n  color: #333333;\n  background-color: #FFFFFF;\n  border-bottom-style: none;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 2px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n}\n\n#acawcqxvtj .gt_footnote {\n  margin: 0px;\n  font-size: 90%;\n  padding-top: 4px;\n  padding-bottom: 4px;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#acawcqxvtj .gt_sourcenotes {\n  color: #333333;\n  background-color: #FFFFFF;\n  border-bottom-style: none;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 2px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n}\n\n#acawcqxvtj .gt_sourcenote {\n  font-size: 90%;\n  padding-top: 4px;\n  padding-bottom: 4px;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#acawcqxvtj .gt_left {\n  text-align: left;\n}\n\n#acawcqxvtj .gt_center {\n  text-align: center;\n}\n\n#acawcqxvtj .gt_right {\n  text-align: right;\n  font-variant-numeric: tabular-nums;\n}\n\n#acawcqxvtj .gt_font_normal {\n  font-weight: normal;\n}\n\n#acawcqxvtj .gt_font_bold {\n  font-weight: bold;\n}\n\n#acawcqxvtj .gt_font_italic {\n  font-style: italic;\n}\n\n#acawcqxvtj .gt_super {\n  font-size: 65%;\n}\n\n#acawcqxvtj .gt_footnote_marks {\n  font-size: 75%;\n  vertical-align: 0.4em;\n  position: initial;\n}\n\n#acawcqxvtj .gt_asterisk {\n  font-size: 100%;\n  vertical-align: 0;\n}\n\n#acawcqxvtj .gt_indent_1 {\n  text-indent: 5px;\n}\n\n#acawcqxvtj .gt_indent_2 {\n  text-indent: 10px;\n}\n\n#acawcqxvtj .gt_indent_3 {\n  text-indent: 15px;\n}\n\n#acawcqxvtj .gt_indent_4 {\n  text-indent: 20px;\n}\n\n#acawcqxvtj .gt_indent_5 {\n  text-indent: 25px;\n}\n\n#acawcqxvtj .katex-display {\n  display: inline-flex !important;\n  margin-bottom: 0.75em !important;\n}\n\n#acawcqxvtj div.Reactable > div.rt-table > div.rt-thead > div.rt-tr.rt-tr-group-header > div.rt-th-group:after {\n  height: 0px !important;\n}\n</style>\n<table class=\"gt_table\" data-quarto-disable-processing=\"false\" data-quarto-bootstrap=\"false\">\n  <thead>\n    <tr class=\"gt_col_headings\">\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_left\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"label\"><span data-qmd-base64=\"KipDaGFyYWN0ZXJpc3RpYyoq\"><span class='gt_from_md'><strong>Characteristic</strong></span></span></th>\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_center\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"stat_0\"><span data-qmd-base64=\"KipOID0gMSwzNTcqKg==\"><span class='gt_from_md'><strong>N = 1,357</strong></span></span><span class=\"gt_footnote_marks\" style=\"white-space:nowrap;font-style:italic;font-weight:normal;line-height:0;\"><sup>1</sup></span></th>\n    </tr>\n  </thead>\n  <tbody class=\"gt_table_body\">\n    <tr><td headers=\"label\" class=\"gt_row gt_left\" style=\"font-weight: bold;\">Log monthly income</td>\n<td headers=\"stat_0\" class=\"gt_row gt_center\">8.00 (0.62)</td></tr>\n    <tr><td headers=\"label\" class=\"gt_row gt_left\" style=\"font-weight: bold;\">Years of education</td>\n<td headers=\"stat_0\" class=\"gt_row gt_center\">13.65 (2.94)</td></tr>\n    <tr><td headers=\"label\" class=\"gt_row gt_left\" style=\"font-weight: bold;\">Work experience (years)</td>\n<td headers=\"stat_0\" class=\"gt_row gt_center\">16.46 (7.73)</td></tr>\n    <tr><td headers=\"label\" class=\"gt_row gt_left\" style=\"font-weight: bold;\">Numeracy (z-score)</td>\n<td headers=\"stat_0\" class=\"gt_row gt_center\">0.00 (1.00)</td></tr>\n  </tbody>\n  \n  <tfoot class=\"gt_footnotes\">\n    <tr>\n      <td class=\"gt_footnote\" colspan=\"2\"><span class=\"gt_footnote_marks\" style=\"white-space:nowrap;font-style:italic;font-weight:normal;line-height:0;\"><sup>1</sup></span> <span data-qmd-base64=\"TWVhbiAoU0Qp\"><span class='gt_from_md'>Mean (SD)</span></span></td>\n    </tr>\n  </tfoot>\n</table>\n</div>\n```\n\n:::\n:::\n\n\nSeveral features of the continuous variable distributions are worth noting:\n\n- **Log-income** has a mean of about 8.00 and ranges from 5.63 to 10.44. The\n  distribution is approximately symmetric after the log transformation, which\n  is desirable for linear regression.\n- **Years of education** averages approximately 13.7 years, reflecting Korea's\n  high educational attainment. The range (6--22 years) shows meaningful\n  variation.\n- **Work experience** averages about 16.5 years, as expected for a sample of\n  prime working-age adults (35--54). The range (0--40 years) is wide.\n- **Numeracy** is z-scored (mean $\\approx$ 0, SD $\\approx$ 1), ranging from\n  about $-3.8$ to $+3.0$ standard deviations.\n\n### Categorical Variables {#sec-linear-ex-categorical}\n\n@tbl-desc-categorical presents the frequency distributions of gender and\noccupational classification.\n\n\n::: {#tbl-desc-categorical .cell tbl-cap='Frequency Distributions of Categorical Variables'}\n\n```{.r .cell-code}\npiaac |>\n  select(female, occupation) |>\n  mutate(\n    female = factor(female, levels = c(0, 1),\n                    labels = c(\"Male\", \"Female\"))\n  ) |>\n  tbl_summary(\n    label = list(\n      female     ~ \"Gender\",\n      occupation ~ \"Occupation\"\n    )\n  ) |>\n  bold_labels()\n```\n\n::: {.cell-output-display}\n\n```{=html}\n<div id=\"xaigvvxkmy\" style=\"padding-left:0px;padding-right:0px;padding-top:10px;padding-bottom:10px;overflow-x:auto;overflow-y:auto;width:auto;height:auto;\">\n<style>#xaigvvxkmy table {\n  font-family: system-ui, 'Segoe UI', Roboto, Helvetica, Arial, sans-serif, 'Apple Color Emoji', 'Segoe UI Emoji', 'Segoe UI Symbol', 'Noto Color Emoji';\n  -webkit-font-smoothing: antialiased;\n  -moz-osx-font-smoothing: grayscale;\n}\n\n#xaigvvxkmy thead, #xaigvvxkmy tbody, #xaigvvxkmy tfoot, #xaigvvxkmy tr, #xaigvvxkmy td, #xaigvvxkmy th {\n  border-style: none;\n}\n\n#xaigvvxkmy p {\n  margin: 0;\n  padding: 0;\n}\n\n#xaigvvxkmy .gt_table {\n  display: table;\n  border-collapse: collapse;\n  line-height: normal;\n  margin-left: auto;\n  margin-right: auto;\n  color: #333333;\n  font-size: 16px;\n  font-weight: normal;\n  font-style: normal;\n  background-color: #FFFFFF;\n  width: auto;\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #A8A8A8;\n  border-right-style: none;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #A8A8A8;\n  border-left-style: none;\n  border-left-width: 2px;\n  border-left-color: #D3D3D3;\n}\n\n#xaigvvxkmy .gt_caption {\n  padding-top: 4px;\n  padding-bottom: 4px;\n}\n\n#xaigvvxkmy .gt_title {\n  color: #333333;\n  font-size: 125%;\n  font-weight: initial;\n  padding-top: 4px;\n  padding-bottom: 4px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-bottom-color: #FFFFFF;\n  border-bottom-width: 0;\n}\n\n#xaigvvxkmy .gt_subtitle {\n  color: #333333;\n  font-size: 85%;\n  font-weight: initial;\n  padding-top: 3px;\n  padding-bottom: 5px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-top-color: #FFFFFF;\n  border-top-width: 0;\n}\n\n#xaigvvxkmy .gt_heading {\n  background-color: #FFFFFF;\n  text-align: center;\n  border-bottom-color: #FFFFFF;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n}\n\n#xaigvvxkmy .gt_bottom_border {\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n}\n\n#xaigvvxkmy .gt_col_headings {\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n}\n\n#xaigvvxkmy .gt_col_heading {\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: normal;\n  text-transform: inherit;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n  vertical-align: bottom;\n  padding-top: 5px;\n  padding-bottom: 6px;\n  padding-left: 5px;\n  padding-right: 5px;\n  overflow-x: hidden;\n}\n\n#xaigvvxkmy .gt_column_spanner_outer {\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: normal;\n  text-transform: inherit;\n  padding-top: 0;\n  padding-bottom: 0;\n  padding-left: 4px;\n  padding-right: 4px;\n}\n\n#xaigvvxkmy .gt_column_spanner_outer:first-child {\n  padding-left: 0;\n}\n\n#xaigvvxkmy .gt_column_spanner_outer:last-child {\n  padding-right: 0;\n}\n\n#xaigvvxkmy .gt_column_spanner {\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  vertical-align: bottom;\n  padding-top: 5px;\n  padding-bottom: 5px;\n  overflow-x: hidden;\n  display: inline-block;\n  width: 100%;\n}\n\n#xaigvvxkmy .gt_spanner_row {\n  border-bottom-style: hidden;\n}\n\n#xaigvvxkmy .gt_group_heading {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: initial;\n  text-transform: inherit;\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n  vertical-align: middle;\n  text-align: left;\n}\n\n#xaigvvxkmy .gt_empty_group_heading {\n  padding: 0.5px;\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: initial;\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  vertical-align: middle;\n}\n\n#xaigvvxkmy .gt_from_md > :first-child {\n  margin-top: 0;\n}\n\n#xaigvvxkmy .gt_from_md > :last-child {\n  margin-bottom: 0;\n}\n\n#xaigvvxkmy .gt_row {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  margin: 10px;\n  border-top-style: solid;\n  border-top-width: 1px;\n  border-top-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n  vertical-align: middle;\n  overflow-x: hidden;\n}\n\n#xaigvvxkmy .gt_stub {\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: initial;\n  text-transform: inherit;\n  border-right-style: solid;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#xaigvvxkmy .gt_stub_row_group {\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: initial;\n  text-transform: inherit;\n  border-right-style: solid;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n  padding-left: 5px;\n  padding-right: 5px;\n  vertical-align: top;\n}\n\n#xaigvvxkmy .gt_row_group_first td {\n  border-top-width: 2px;\n}\n\n#xaigvvxkmy .gt_row_group_first th {\n  border-top-width: 2px;\n}\n\n#xaigvvxkmy .gt_summary_row {\n  color: #333333;\n  background-color: #FFFFFF;\n  text-transform: inherit;\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#xaigvvxkmy .gt_first_summary_row {\n  border-top-style: solid;\n  border-top-color: #D3D3D3;\n}\n\n#xaigvvxkmy .gt_first_summary_row.thick {\n  border-top-width: 2px;\n}\n\n#xaigvvxkmy .gt_last_summary_row {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n}\n\n#xaigvvxkmy .gt_grand_summary_row {\n  color: #333333;\n  background-color: #FFFFFF;\n  text-transform: inherit;\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#xaigvvxkmy .gt_first_grand_summary_row {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-top-style: double;\n  border-top-width: 6px;\n  border-top-color: #D3D3D3;\n}\n\n#xaigvvxkmy .gt_last_grand_summary_row_top {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-bottom-style: double;\n  border-bottom-width: 6px;\n  border-bottom-color: #D3D3D3;\n}\n\n#xaigvvxkmy .gt_striped {\n  background-color: rgba(128, 128, 128, 0.05);\n}\n\n#xaigvvxkmy .gt_table_body {\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n}\n\n#xaigvvxkmy .gt_footnotes {\n  color: #333333;\n  background-color: #FFFFFF;\n  border-bottom-style: none;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 2px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n}\n\n#xaigvvxkmy .gt_footnote {\n  margin: 0px;\n  font-size: 90%;\n  padding-top: 4px;\n  padding-bottom: 4px;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#xaigvvxkmy .gt_sourcenotes {\n  color: #333333;\n  background-color: #FFFFFF;\n  border-bottom-style: none;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 2px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n}\n\n#xaigvvxkmy .gt_sourcenote {\n  font-size: 90%;\n  padding-top: 4px;\n  padding-bottom: 4px;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#xaigvvxkmy .gt_left {\n  text-align: left;\n}\n\n#xaigvvxkmy .gt_center {\n  text-align: center;\n}\n\n#xaigvvxkmy .gt_right {\n  text-align: right;\n  font-variant-numeric: tabular-nums;\n}\n\n#xaigvvxkmy .gt_font_normal {\n  font-weight: normal;\n}\n\n#xaigvvxkmy .gt_font_bold {\n  font-weight: bold;\n}\n\n#xaigvvxkmy .gt_font_italic {\n  font-style: italic;\n}\n\n#xaigvvxkmy .gt_super {\n  font-size: 65%;\n}\n\n#xaigvvxkmy .gt_footnote_marks {\n  font-size: 75%;\n  vertical-align: 0.4em;\n  position: initial;\n}\n\n#xaigvvxkmy .gt_asterisk {\n  font-size: 100%;\n  vertical-align: 0;\n}\n\n#xaigvvxkmy .gt_indent_1 {\n  text-indent: 5px;\n}\n\n#xaigvvxkmy .gt_indent_2 {\n  text-indent: 10px;\n}\n\n#xaigvvxkmy .gt_indent_3 {\n  text-indent: 15px;\n}\n\n#xaigvvxkmy .gt_indent_4 {\n  text-indent: 20px;\n}\n\n#xaigvvxkmy .gt_indent_5 {\n  text-indent: 25px;\n}\n\n#xaigvvxkmy .katex-display {\n  display: inline-flex !important;\n  margin-bottom: 0.75em !important;\n}\n\n#xaigvvxkmy div.Reactable > div.rt-table > div.rt-thead > div.rt-tr.rt-tr-group-header > div.rt-th-group:after {\n  height: 0px !important;\n}\n</style>\n<table class=\"gt_table\" data-quarto-disable-processing=\"false\" data-quarto-bootstrap=\"false\">\n  <thead>\n    <tr class=\"gt_col_headings\">\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_left\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"label\"><span data-qmd-base64=\"KipDaGFyYWN0ZXJpc3RpYyoq\"><span class='gt_from_md'><strong>Characteristic</strong></span></span></th>\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_center\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"stat_0\"><span data-qmd-base64=\"KipOID0gMSwzNTcqKg==\"><span class='gt_from_md'><strong>N = 1,357</strong></span></span><span class=\"gt_footnote_marks\" style=\"white-space:nowrap;font-style:italic;font-weight:normal;line-height:0;\"><sup>1</sup></span></th>\n    </tr>\n  </thead>\n  <tbody class=\"gt_table_body\">\n    <tr><td headers=\"label\" class=\"gt_row gt_left\" style=\"font-weight: bold;\">Gender</td>\n<td headers=\"stat_0\" class=\"gt_row gt_center\"><br /></td></tr>\n    <tr><td headers=\"label\" class=\"gt_row gt_left\">    Male</td>\n<td headers=\"stat_0\" class=\"gt_row gt_center\">814 (60%)</td></tr>\n    <tr><td headers=\"label\" class=\"gt_row gt_left\">    Female</td>\n<td headers=\"stat_0\" class=\"gt_row gt_center\">543 (40%)</td></tr>\n    <tr><td headers=\"label\" class=\"gt_row gt_left\" style=\"font-weight: bold;\">Occupation</td>\n<td headers=\"stat_0\" class=\"gt_row gt_center\"><br /></td></tr>\n    <tr><td headers=\"label\" class=\"gt_row gt_left\">    Skilled</td>\n<td headers=\"stat_0\" class=\"gt_row gt_center\">438 (32%)</td></tr>\n    <tr><td headers=\"label\" class=\"gt_row gt_left\">    Semi-white</td>\n<td headers=\"stat_0\" class=\"gt_row gt_center\">487 (36%)</td></tr>\n    <tr><td headers=\"label\" class=\"gt_row gt_left\">    Semi-blue</td>\n<td headers=\"stat_0\" class=\"gt_row gt_center\">290 (21%)</td></tr>\n    <tr><td headers=\"label\" class=\"gt_row gt_left\">    Elementary</td>\n<td headers=\"stat_0\" class=\"gt_row gt_center\">142 (10%)</td></tr>\n  </tbody>\n  \n  <tfoot class=\"gt_footnotes\">\n    <tr>\n      <td class=\"gt_footnote\" colspan=\"2\"><span class=\"gt_footnote_marks\" style=\"white-space:nowrap;font-style:italic;font-weight:normal;line-height:0;\"><sup>1</sup></span> <span data-qmd-base64=\"biAoJSk=\"><span class='gt_from_md'>n (%)</span></span></td>\n    </tr>\n  </tfoot>\n</table>\n</div>\n```\n\n:::\n:::\n\n\nThe sample is about 60% male and 40% female. The occupational distribution\nshows that skilled occupations (managers, professionals, technicians) and\nsemi-white-collar workers (clerical, service/sales) are the most common\ncategories, together accounting for about 68% of the sample. Semi-blue-collar\nworkers make up about 21%, and elementary occupations represent about 10% of\nthe sample.\n\n\n### Visualizations {#sec-linear-ex-visualizations}\n\n#### Distribution of the Outcome Variable\n\n@fig-hist-lninc shows the distribution of log monthly income, our outcome\nvariable. The log transformation produces a distribution that is approximately\nnormal, which supports the normality assumption for the regression residuals.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nggplot(piaac, aes(x = ln_inc)) +\n  geom_histogram(\n    bins = 30, fill = ber640_colors[\"accent\"], color = \"white\", alpha = 0.8\n  ) +\n  geom_vline(\n    xintercept = mean(piaac$ln_inc),\n    linetype = \"dashed\", color = ber640_colors[\"secondary\"], linewidth = 0.8\n  ) +\n  labs(\n    x = \"Log monthly income\",\n    y = \"Count\",\n    title = \"Distribution of Log Monthly Income\",\n    subtitle = \"Dashed line = sample mean\"\n  )\n```\n\n::: {.cell-output-display}\n![Distribution of Log Monthly Income](ch05-linear-results_files/figure-html/fig-hist-lninc-1.png){#fig-hist-lninc fig-alt='Histogram of log monthly income showing an approximately normal, symmetric distribution centered around 8.0 with a dashed vertical line at the sample mean' width=2100}\n:::\n:::\n\n\n#### Scatterplots of Continuous Predictors\n\n@fig-scatter-predictors displays the bivariate relationships between\nlog-income and each continuous predictor. Each panel includes both a linear\nfit (red) and a LOESS smooth (blue) to help detect nonlinearity.\n\n\n::: {.cell}\n\n```{.r .cell-code}\np_schyrs <- ggplot(piaac, aes(x = as.numeric(schyrs), y = ln_inc)) +\n  geom_point(alpha = 0.15, color = ber640_colors[\"primary\"]) +\n  geom_smooth(method = \"lm\", se = FALSE,\n              color = ber640_colors[\"secondary\"], linewidth = 1) +\n  geom_smooth(method = \"loess\", se = FALSE,\n              color = ber640_colors[\"accent\"], linewidth = 1,\n              linetype = \"dashed\") +\n  labs(x = \"Years of education\", y = \"Log income\",\n       title = \"Education\")\n\np_exper <- ggplot(piaac, aes(x = as.numeric(exper), y = ln_inc)) +\n  geom_point(alpha = 0.15, color = ber640_colors[\"primary\"]) +\n  geom_smooth(method = \"lm\", se = FALSE,\n              color = ber640_colors[\"secondary\"], linewidth = 1) +\n  geom_smooth(method = \"loess\", se = FALSE,\n              color = ber640_colors[\"accent\"], linewidth = 1,\n              linetype = \"dashed\") +\n  labs(x = \"Work experience (years)\", y = \"Log income\",\n       title = \"Experience\")\n\np_numeracy <- ggplot(piaac, aes(x = numeracy, y = ln_inc)) +\n  geom_point(alpha = 0.15, color = ber640_colors[\"primary\"]) +\n  geom_smooth(method = \"lm\", se = FALSE,\n              color = ber640_colors[\"secondary\"], linewidth = 1) +\n  geom_smooth(method = \"loess\", se = FALSE,\n              color = ber640_colors[\"accent\"], linewidth = 1,\n              linetype = \"dashed\") +\n  labs(x = \"Numeracy (z-score)\", y = \"Log income\",\n       title = \"Numeracy\")\n\np_schyrs + p_exper + p_numeracy +\n  plot_annotation(\n    subtitle = \"Red = linear fit; Blue dashed = LOESS smooth\"\n  )\n```\n\n::: {.cell-output-display}\n![Scatterplots of Log Income vs. Continuous Predictors](ch05-linear-results_files/figure-html/fig-scatter-predictors-1.png){#fig-scatter-predictors fig-alt='Three-panel scatterplot showing log income versus education, experience, and numeracy. Education and numeracy show positive linear trends with LOESS curves confirming linearity. Experience shows a positive but slightly concave relationship where the LOESS curve bends downward at higher values, indicating diminishing returns.' width=2100}\n:::\n:::\n\n\nKey observations from the scatterplots:\n\n- **Education** shows a clear positive linear relationship with log-income.\n  The LOESS curve closely tracks the linear fit, suggesting linearity is\n  reasonable.\n- **Experience** shows a positive but slightly curved relationship. The LOESS\n  smooth bends downward at higher experience levels, consistent with the\n  diminishing-returns pattern that justifies including the squared term\n  (`exper2_c`) in our models.\n- **Numeracy** shows a moderate positive association with log-income. The\n  relationship appears approximately linear.\n\n#### Boxplots by Categorical Predictors\n\n@fig-boxplot-categorical displays the distribution of log-income across gender\nand occupational categories.\n\n\n::: {.cell}\n\n```{.r .cell-code}\np_gender <- piaac |>\n  mutate(Gender = factor(female, levels = c(0, 1),\n                         labels = c(\"Male\", \"Female\"))) |>\n  ggplot(aes(x = Gender, y = ln_inc, fill = Gender)) +\n  geom_boxplot(alpha = 0.7, show.legend = FALSE) +\n  scale_fill_manual(values = c(ber640_colors[\"primary\"],\n                               ber640_colors[\"accent\"])) +\n  labs(x = NULL, y = \"Log income\", title = \"Gender\")\n\np_occupation <- ggplot(piaac, aes(x = occupation, y = ln_inc,\n                                   fill = occupation)) +\n  geom_boxplot(alpha = 0.7, show.legend = FALSE) +\n  scale_fill_manual(values = unname(ber640_colors[1:4])) +\n  labs(x = NULL, y = \"Log income\", title = \"Occupation\") +\n  theme(axis.text.x = element_text(size = 10))\n\np_gender + p_occupation\n```\n\n::: {.cell-output-display}\n![Log Income by Gender and Occupation](ch05-linear-results_files/figure-html/fig-boxplot-categorical-1.png){#fig-boxplot-categorical fig-alt='Side-by-side boxplots in two panels. The gender panel shows males have a noticeably higher median log income than females, with the male median above the female 75th percentile. The occupation panel shows a clear earnings gradient: skilled workers earn the most, followed by semi-white-collar, semi-blue-collar, and elementary workers.' width=2100}\n:::\n:::\n\n\nTwo patterns stand out:\n\n- **Gender gap:** Male workers have noticeably higher log-income than female\n  workers. The median for males is above the 75th percentile for females.\n- **Occupational hierarchy:** There is a clear earnings gradient across\n  occupational categories. Skilled workers earn the most, followed by\n  semi-white-collar, semi-blue-collar, and elementary workers.\n\n::: {.callout-tip}\n## Writing Tip\nExploratory visualizations serve two purposes: (1) they preview the\nrelationships you will model, and (2) they help you check whether the\nlinearity assumption is reasonable *before* fitting the regression. Always\ndescribe what you see in each plot --- do not just drop in a figure without\ninterpretation.\n:::\n\n\n## Part 5: Regression Analysis {#sec-linear-ex-part5}\n\n::: {.callout-important}\n## Guideline Reminder --- Part 5\nFit your planned models, present the results in a publication-style table,\ninterpret every coefficient substantively, and check regression assumptions.\nLink each model back to the research question it addresses.\n:::\n\n### Model 1: Traditional Mincer Model (RQ1) {#sec-linear-ex-results-m1}\n\nWe begin by fitting Model 1, which regresses log-income on gender, years of\neducation (mean-centered), work experience (mean-centered, in decades), and\nthe squared experience term.\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# --- Model 1: Traditional Mincer model ---\nmodel1 <- lm(ln_inc ~ female + schyrs_c + exper_c + exper2_c,\n             data = piaac)\n\nsummary(model1)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\nCall:\nlm(formula = ln_inc ~ female + schyrs_c + exper_c + exper2_c, \n    data = piaac)\n\nResiduals:\n    Min      1Q  Median      3Q     Max \n-2.3039 -0.2843  0.0109  0.2984  3.3933 \n\nCoefficients:\n             Estimate Std. Error t value Pr(>|t|)    \n(Intercept)  8.203744   0.020047 409.220  < 2e-16 ***\nfemale      -0.399620   0.028436 -14.053  < 2e-16 ***\nschyrs_c     0.083800   0.004642  18.053  < 2e-16 ***\nexper_c      0.168767   0.017978   9.387  < 2e-16 ***\nexper2_c    -0.072866   0.017809  -4.092 4.54e-05 ***\n---\nSignif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1\n\nResidual standard error: 0.4796 on 1352 degrees of freedom\nMultiple R-squared:  0.3945,\tAdjusted R-squared:  0.3927 \nF-statistic: 220.2 on 4 and 1352 DF,  p-value: < 2.2e-16\n```\n\n\n:::\n:::\n\n\n**Interpretation of Model 1:**\n\n- **Intercept (8.20):** The predicted log-income for a *male* worker with\n  *average* education and *average* experience. In original units, this\n  corresponds to approximately $e^{8.20} \\approx 3{,}641$ (PPP-adjusted\n  monthly income units).\n- **Female ($b = -0.40$, $p < .001$):** Women earn approximately\n  $100 \\times (e^{-0.40} - 1) \\approx -33\\%$ less than men with the same\n  education and experience. This is a substantial gender gap.\n- **Years of education ($b = 0.084$, $p < .001$):** Each additional year of\n  education is associated with approximately an 8.4% increase in monthly\n  income, holding other variables constant. This is consistent with typical\n  Mincer estimates.\n- **Experience ($b = 0.169$, $p < .001$):** An additional decade of work\n  experience is associated with approximately a 16.9% increase in income.\n- **Experience squared ($b = -0.073$, $p < .001$):** The negative coefficient\n  confirms diminishing returns to experience --- the income gains from\n  additional experience decrease at higher experience levels.\n- **$R^2 = .395$:** The traditional Mincer variables explain about 39.5% of\n  the variance in log-income.\n\n\n### Model 2: Adding Occupation and Numeracy (RQ2) {#sec-linear-ex-results-m2}\n\nModel 2 extends Model 1 by adding three occupation dummy variables (with\nskilled occupations as the reference category) and numeracy proficiency.\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# --- Model 2: + Occupation and numeracy ---\nmodel2 <- lm(ln_inc ~ female + schyrs_c + exper_c + exper2_c +\n               semiwhite + semiblue + elementary + numeracy,\n             data = piaac)\n\nsummary(model2)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\nCall:\nlm(formula = ln_inc ~ female + schyrs_c + exper_c + exper2_c + \n    semiwhite + semiblue + elementary + numeracy, data = piaac)\n\nResiduals:\n    Min      1Q  Median      3Q     Max \n-2.3721 -0.2788  0.0034  0.2852  3.3199 \n\nCoefficients:\n             Estimate Std. Error t value Pr(>|t|)    \n(Intercept)  8.360984   0.030135 277.450  < 2e-16 ***\nfemale      -0.427377   0.029061 -14.706  < 2e-16 ***\nschyrs_c     0.048266   0.005846   8.256 3.55e-16 ***\nexper_c      0.150389   0.017666   8.513  < 2e-16 ***\nexper2_c    -0.067091   0.017260  -3.887 0.000106 ***\nsemiwhite   -0.142749   0.032712  -4.364 1.38e-05 ***\nsemiblue    -0.275441   0.041299  -6.670 3.74e-11 ***\nelementary  -0.377383   0.051782  -7.288 5.34e-13 ***\nnumeracy     0.060957   0.015082   4.042 5.61e-05 ***\n---\nSignif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1\n\nResidual standard error: 0.4641 on 1348 degrees of freedom\nMultiple R-squared:  0.4348,\tAdjusted R-squared:  0.4314 \nF-statistic: 129.6 on 8 and 1348 DF,  p-value: < 2.2e-16\n```\n\n\n:::\n:::\n\n\n**Interpretation of Model 2:**\n\n- **Occupation effects** (all relative to skilled workers):\n  - *Semi-white* ($b = -0.14$, $p < .001$): Semi-white-collar workers earn\n    about 13% less than skilled workers.\n  - *Semi-blue* ($b = -0.28$, $p < .001$): Semi-blue-collar workers earn\n    about 24% less than skilled workers.\n  - *Elementary* ($b = -0.38$, $p < .001$): Elementary workers earn about 31%\n    less than skilled workers.\n  - The clear gradient across occupation categories confirms that occupational\n    classification captures meaningful earnings differences.\n- **Numeracy ($b = 0.061$, $p < .001$):** A one-standard-deviation increase\n  in numeracy proficiency is associated with approximately a 6.1% increase in\n  income, even after controlling for education, experience, and occupation.\n  This means that *what workers know* (cognitive skills) matters for earnings\n  above and beyond *how long they went to school*.\n- **Education ($b = 0.048$):** Note that the education coefficient decreased\n  from 0.084 in Model 1 to 0.048 in Model 2. This reduction occurs because\n  some of the education effect in Model 1 was actually operating through\n  occupational sorting and cognitive skills. With those pathways controlled,\n  the direct return to an additional year of education is about 4.8%.\n- **$R^2 = .435$:** Model 2 explains about 43.5% of the variance in\n  log-income, a meaningful increase of 4 percentage points over Model 1.\n\n#### Incremental F-Test: Model 1 vs. Model 2\n\nWe formally test whether the four additional predictors (three occupation\ndummies + numeracy) significantly improve model fit using an incremental\n$F$-test.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nanova(model1, model2)\n```\n\n::: {.cell-output-display}\n<div class=\"kable-table\">\n\n| Res.Df|      RSS| Df| Sum of Sq|        F| Pr(>F)|\n|------:|--------:|--:|---------:|--------:|------:|\n|   1352| 310.9462| NA|        NA|       NA|     NA|\n|   1348| 290.2858|  4|  20.66039| 23.98515|      0|\n\n</div>\n:::\n:::\n\n\nThe $F$-test is highly significant ($F(4, 1348) = 23.99$, $p < .001$),\nconfirming that occupation and numeracy jointly add significant explanatory\npower beyond the traditional Mincer variables. This answers **RQ2** in the\naffirmative.\n\n\n### Model 3: Gender Interactions (RQ3) {#sec-linear-ex-results-m3}\n\nModel 3 extends Model 2 by adding interaction terms between gender and two key\npredictors: education and numeracy. These interaction terms test whether the\n*returns* to education and cognitive skills differ between men and women.\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# --- Model 3: + Gender interactions ---\nmodel3 <- lm(ln_inc ~ female + schyrs_c + exper_c + exper2_c +\n               semiwhite + semiblue + elementary + numeracy +\n               fem_schyrs_c + fem_numeracy,\n             data = piaac)\n\nsummary(model3)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\nCall:\nlm(formula = ln_inc ~ female + schyrs_c + exper_c + exper2_c + \n    semiwhite + semiblue + elementary + numeracy + fem_schyrs_c + \n    fem_numeracy, data = piaac)\n\nResiduals:\n    Min      1Q  Median      3Q     Max \n-2.3788 -0.2916 -0.0032  0.2898  3.2259 \n\nCoefficients:\n              Estimate Std. Error t value Pr(>|t|)    \n(Intercept)   8.351725   0.030184 276.694  < 2e-16 ***\nfemale       -0.425609   0.028989 -14.682  < 2e-16 ***\nschyrs_c      0.055464   0.007565   7.332 3.90e-13 ***\nexper_c       0.159066   0.017819   8.927  < 2e-16 ***\nexper2_c     -0.067731   0.017213  -3.935 8.75e-05 ***\nsemiwhite    -0.145028   0.032635  -4.444 9.56e-06 ***\nsemiblue     -0.263224   0.041364  -6.364 2.70e-10 ***\nelementary   -0.385662   0.051770  -7.449 1.67e-13 ***\nnumeracy      0.080469   0.019481   4.131 3.84e-05 ***\nfem_schyrs_c -0.014556   0.010348  -1.407   0.1597    \nfem_numeracy -0.055472   0.030391  -1.825   0.0682 .  \n---\nSignif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1\n\nResidual standard error: 0.4626 on 1346 degrees of freedom\nMultiple R-squared:  0.4391,\tAdjusted R-squared:  0.4349 \nF-statistic: 105.4 on 10 and 1346 DF,  p-value: < 2.2e-16\n```\n\n\n:::\n:::\n\n\n**Interpretation of the interaction terms:**\n\n- **Female $\\times$ Education ($b = -0.015$, $p = .160$):** The interaction\n  is not statistically significant at $\\alpha = .05$. There is no evidence\n  that the returns to education differ by gender.\n- **Female $\\times$ Numeracy ($b = -0.055$, $p = .068$):** This interaction\n  is marginally nonsignificant. There is a suggestive pattern that the\n  returns to numeracy may be somewhat smaller for women, but the evidence is\n  not strong enough to conclude that the difference is statistically reliable.\n- **$R^2 = .439$:** The addition of two interaction terms produces only a\n  small increase in $R^2$ (from .435 to .439).\n\n#### Incremental F-Test: Model 2 vs. Model 3\n\n\n::: {.cell}\n\n```{.r .cell-code}\nanova(model2, model3)\n```\n\n::: {.cell-output-display}\n<div class=\"kable-table\">\n\n| Res.Df|      RSS| Df| Sum of Sq|        F|    Pr(>F)|\n|------:|--------:|--:|---------:|--------:|---------:|\n|   1348| 290.2858| NA|        NA|       NA|        NA|\n|   1346| 288.0723|  2|  2.213532| 5.171295| 0.0057906|\n\n</div>\n:::\n:::\n\n\nThe incremental $F$-test for the two interaction terms yields\n$F(2, 1346) = 5.17$, $p = .006$. Although the block is statistically\nsignificant at $\\alpha = .05$, neither individual interaction term reaches\nsignificance on its own. This is a case where the *joint* test detects a\nsmall combined effect that the individual $t$-tests lack power to isolate.\nGiven the marginal nature of these results, the most conservative\ninterpretation --- and the one we adopt for **RQ3** --- is that the returns to\neducation and numeracy are broadly **similar for men and women**. The gender\ngap in earnings appears to operate primarily as a level difference (the main\neffect of `female`) rather than through differential returns to human capital.\n\n\n### Publication-Style Regression Table {#sec-linear-ex-reg-table}\n\n@tbl-regression-models presents all three models side by side in a\npublication-ready format.\n\n\n::: {#tbl-regression-models .cell tbl-cap='Nested Linear Regression Models Predicting Log Monthly Income'}\n\n```{.r .cell-code}\n# Create individual tbl_regression objects\nt1 <- tbl_regression(\n  model1,\n  intercept = TRUE,\n  label = list(\n    female   ~ \"Female\",\n    schyrs_c ~ \"Education (years, centered)\",\n    exper_c  ~ \"Experience (decades, centered)\",\n    exper2_c ~ \"Experience squared\"\n  )\n) |> bold_p(t = 0.05)\n\nt2 <- tbl_regression(\n  model2,\n  intercept = TRUE,\n  label = list(\n    female    ~ \"Female\",\n    schyrs_c  ~ \"Education (years, centered)\",\n    exper_c   ~ \"Experience (decades, centered)\",\n    exper2_c  ~ \"Experience squared\",\n    semiwhite ~ \"Semi-white-collar\",\n    semiblue  ~ \"Semi-blue-collar\",\n    elementary ~ \"Elementary\",\n    numeracy  ~ \"Numeracy (z-score)\"\n  )\n) |> bold_p(t = 0.05)\n\nt3 <- tbl_regression(\n  model3,\n  intercept = TRUE,\n  label = list(\n    female       ~ \"Female\",\n    schyrs_c     ~ \"Education (years, centered)\",\n    exper_c      ~ \"Experience (decades, centered)\",\n    exper2_c     ~ \"Experience squared\",\n    semiwhite    ~ \"Semi-white-collar\",\n    semiblue     ~ \"Semi-blue-collar\",\n    elementary   ~ \"Elementary\",\n    numeracy     ~ \"Numeracy (z-score)\",\n    fem_schyrs_c ~ \"Female x Education\",\n    fem_numeracy ~ \"Female x Numeracy\"\n  )\n) |> bold_p(t = 0.05)\n\n# Merge into one table\ntbl_merge(\n  tbls = list(t1, t2, t3),\n  tab_spanner = c(\"**Model 1**\", \"**Model 2**\", \"**Model 3**\")\n)\n```\n\n::: {.cell-output-display}\n\n```{=html}\n<div id=\"avjikcygjq\" style=\"padding-left:0px;padding-right:0px;padding-top:10px;padding-bottom:10px;overflow-x:auto;overflow-y:auto;width:auto;height:auto;\">\n<style>#avjikcygjq table {\n  font-family: system-ui, 'Segoe UI', Roboto, Helvetica, Arial, sans-serif, 'Apple Color Emoji', 'Segoe UI Emoji', 'Segoe UI Symbol', 'Noto Color Emoji';\n  -webkit-font-smoothing: antialiased;\n  -moz-osx-font-smoothing: grayscale;\n}\n\n#avjikcygjq thead, #avjikcygjq tbody, #avjikcygjq tfoot, #avjikcygjq tr, #avjikcygjq td, #avjikcygjq th {\n  border-style: none;\n}\n\n#avjikcygjq p {\n  margin: 0;\n  padding: 0;\n}\n\n#avjikcygjq .gt_table {\n  display: table;\n  border-collapse: collapse;\n  line-height: normal;\n  margin-left: auto;\n  margin-right: auto;\n  color: #333333;\n  font-size: 16px;\n  font-weight: normal;\n  font-style: normal;\n  background-color: #FFFFFF;\n  width: auto;\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #A8A8A8;\n  border-right-style: none;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #A8A8A8;\n  border-left-style: none;\n  border-left-width: 2px;\n  border-left-color: #D3D3D3;\n}\n\n#avjikcygjq .gt_caption {\n  padding-top: 4px;\n  padding-bottom: 4px;\n}\n\n#avjikcygjq .gt_title {\n  color: #333333;\n  font-size: 125%;\n  font-weight: initial;\n  padding-top: 4px;\n  padding-bottom: 4px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-bottom-color: #FFFFFF;\n  border-bottom-width: 0;\n}\n\n#avjikcygjq .gt_subtitle {\n  color: #333333;\n  font-size: 85%;\n  font-weight: initial;\n  padding-top: 3px;\n  padding-bottom: 5px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-top-color: #FFFFFF;\n  border-top-width: 0;\n}\n\n#avjikcygjq .gt_heading {\n  background-color: #FFFFFF;\n  text-align: center;\n  border-bottom-color: #FFFFFF;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n}\n\n#avjikcygjq .gt_bottom_border {\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n}\n\n#avjikcygjq .gt_col_headings {\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n}\n\n#avjikcygjq .gt_col_heading {\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: normal;\n  text-transform: inherit;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n  vertical-align: bottom;\n  padding-top: 5px;\n  padding-bottom: 6px;\n  padding-left: 5px;\n  padding-right: 5px;\n  overflow-x: hidden;\n}\n\n#avjikcygjq .gt_column_spanner_outer {\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: normal;\n  text-transform: inherit;\n  padding-top: 0;\n  padding-bottom: 0;\n  padding-left: 4px;\n  padding-right: 4px;\n}\n\n#avjikcygjq .gt_column_spanner_outer:first-child {\n  padding-left: 0;\n}\n\n#avjikcygjq .gt_column_spanner_outer:last-child {\n  padding-right: 0;\n}\n\n#avjikcygjq .gt_column_spanner {\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  vertical-align: bottom;\n  padding-top: 5px;\n  padding-bottom: 5px;\n  overflow-x: hidden;\n  display: inline-block;\n  width: 100%;\n}\n\n#avjikcygjq .gt_spanner_row {\n  border-bottom-style: hidden;\n}\n\n#avjikcygjq .gt_group_heading {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: initial;\n  text-transform: inherit;\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n  vertical-align: middle;\n  text-align: left;\n}\n\n#avjikcygjq .gt_empty_group_heading {\n  padding: 0.5px;\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: initial;\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  vertical-align: middle;\n}\n\n#avjikcygjq .gt_from_md > :first-child {\n  margin-top: 0;\n}\n\n#avjikcygjq .gt_from_md > :last-child {\n  margin-bottom: 0;\n}\n\n#avjikcygjq .gt_row {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  margin: 10px;\n  border-top-style: solid;\n  border-top-width: 1px;\n  border-top-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n  vertical-align: middle;\n  overflow-x: hidden;\n}\n\n#avjikcygjq .gt_stub {\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: initial;\n  text-transform: inherit;\n  border-right-style: solid;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#avjikcygjq .gt_stub_row_group {\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: initial;\n  text-transform: inherit;\n  border-right-style: solid;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n  padding-left: 5px;\n  padding-right: 5px;\n  vertical-align: top;\n}\n\n#avjikcygjq .gt_row_group_first td {\n  border-top-width: 2px;\n}\n\n#avjikcygjq .gt_row_group_first th {\n  border-top-width: 2px;\n}\n\n#avjikcygjq .gt_summary_row {\n  color: #333333;\n  background-color: #FFFFFF;\n  text-transform: inherit;\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#avjikcygjq .gt_first_summary_row {\n  border-top-style: solid;\n  border-top-color: #D3D3D3;\n}\n\n#avjikcygjq .gt_first_summary_row.thick {\n  border-top-width: 2px;\n}\n\n#avjikcygjq .gt_last_summary_row {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n}\n\n#avjikcygjq .gt_grand_summary_row {\n  color: #333333;\n  background-color: #FFFFFF;\n  text-transform: inherit;\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#avjikcygjq .gt_first_grand_summary_row {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-top-style: double;\n  border-top-width: 6px;\n  border-top-color: #D3D3D3;\n}\n\n#avjikcygjq .gt_last_grand_summary_row_top {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-bottom-style: double;\n  border-bottom-width: 6px;\n  border-bottom-color: #D3D3D3;\n}\n\n#avjikcygjq .gt_striped {\n  background-color: rgba(128, 128, 128, 0.05);\n}\n\n#avjikcygjq .gt_table_body {\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n}\n\n#avjikcygjq .gt_footnotes {\n  color: #333333;\n  background-color: #FFFFFF;\n  border-bottom-style: none;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 2px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n}\n\n#avjikcygjq .gt_footnote {\n  margin: 0px;\n  font-size: 90%;\n  padding-top: 4px;\n  padding-bottom: 4px;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#avjikcygjq .gt_sourcenotes {\n  color: #333333;\n  background-color: #FFFFFF;\n  border-bottom-style: none;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 2px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n}\n\n#avjikcygjq .gt_sourcenote {\n  font-size: 90%;\n  padding-top: 4px;\n  padding-bottom: 4px;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#avjikcygjq .gt_left {\n  text-align: left;\n}\n\n#avjikcygjq .gt_center {\n  text-align: center;\n}\n\n#avjikcygjq .gt_right {\n  text-align: right;\n  font-variant-numeric: tabular-nums;\n}\n\n#avjikcygjq .gt_font_normal {\n  font-weight: normal;\n}\n\n#avjikcygjq .gt_font_bold {\n  font-weight: bold;\n}\n\n#avjikcygjq .gt_font_italic {\n  font-style: italic;\n}\n\n#avjikcygjq .gt_super {\n  font-size: 65%;\n}\n\n#avjikcygjq .gt_footnote_marks {\n  font-size: 75%;\n  vertical-align: 0.4em;\n  position: initial;\n}\n\n#avjikcygjq .gt_asterisk {\n  font-size: 100%;\n  vertical-align: 0;\n}\n\n#avjikcygjq .gt_indent_1 {\n  text-indent: 5px;\n}\n\n#avjikcygjq .gt_indent_2 {\n  text-indent: 10px;\n}\n\n#avjikcygjq .gt_indent_3 {\n  text-indent: 15px;\n}\n\n#avjikcygjq .gt_indent_4 {\n  text-indent: 20px;\n}\n\n#avjikcygjq .gt_indent_5 {\n  text-indent: 25px;\n}\n\n#avjikcygjq .katex-display {\n  display: inline-flex !important;\n  margin-bottom: 0.75em !important;\n}\n\n#avjikcygjq div.Reactable > div.rt-table > div.rt-thead > div.rt-tr.rt-tr-group-header > div.rt-th-group:after {\n  height: 0px !important;\n}\n</style>\n<table class=\"gt_table\" data-quarto-disable-processing=\"false\" data-quarto-bootstrap=\"false\">\n  <thead>\n    <tr class=\"gt_col_headings gt_spanner_row\">\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_left\" rowspan=\"2\" colspan=\"1\" scope=\"col\" id=\"label\"><span data-qmd-base64=\"KipDaGFyYWN0ZXJpc3RpYyoq\"><span class='gt_from_md'><strong>Characteristic</strong></span></span></th>\n      <th class=\"gt_center gt_columns_top_border gt_column_spanner_outer\" rowspan=\"1\" colspan=\"3\" scope=\"colgroup\" id=\"level 1; estimate_1\">\n        <div class=\"gt_column_spanner\"><span data-qmd-base64=\"KipNb2RlbCAxKio=\"><span class='gt_from_md'><strong>Model 1</strong></span></span></div>\n      </th>\n      <th class=\"gt_center gt_columns_top_border gt_column_spanner_outer\" rowspan=\"1\" colspan=\"3\" scope=\"colgroup\" id=\"level 1; estimate_2\">\n        <div class=\"gt_column_spanner\"><span data-qmd-base64=\"KipNb2RlbCAyKio=\"><span class='gt_from_md'><strong>Model 2</strong></span></span></div>\n      </th>\n      <th class=\"gt_center gt_columns_top_border gt_column_spanner_outer\" rowspan=\"1\" colspan=\"3\" scope=\"colgroup\" id=\"level 1; estimate_3\">\n        <div class=\"gt_column_spanner\"><span data-qmd-base64=\"KipNb2RlbCAzKio=\"><span class='gt_from_md'><strong>Model 3</strong></span></span></div>\n      </th>\n    </tr>\n    <tr class=\"gt_col_headings\">\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_center\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"estimate_1\"><span data-qmd-base64=\"KipCZXRhKio=\"><span class='gt_from_md'><strong>Beta</strong></span></span></th>\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_center\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"conf.low_1\"><span data-qmd-base64=\"Kio5NSUgQ0kqKg==\"><span class='gt_from_md'><strong>95% CI</strong></span></span></th>\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_center\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"p.value_1\"><span data-qmd-base64=\"KipwLXZhbHVlKio=\"><span class='gt_from_md'><strong>p-value</strong></span></span></th>\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_center\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"estimate_2\"><span data-qmd-base64=\"KipCZXRhKio=\"><span class='gt_from_md'><strong>Beta</strong></span></span></th>\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_center\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"conf.low_2\"><span data-qmd-base64=\"Kio5NSUgQ0kqKg==\"><span class='gt_from_md'><strong>95% CI</strong></span></span></th>\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_center\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"p.value_2\"><span data-qmd-base64=\"KipwLXZhbHVlKio=\"><span class='gt_from_md'><strong>p-value</strong></span></span></th>\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_center\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"estimate_3\"><span data-qmd-base64=\"KipCZXRhKio=\"><span class='gt_from_md'><strong>Beta</strong></span></span></th>\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_center\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"conf.low_3\"><span data-qmd-base64=\"Kio5NSUgQ0kqKg==\"><span class='gt_from_md'><strong>95% CI</strong></span></span></th>\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_center\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"p.value_3\"><span data-qmd-base64=\"KipwLXZhbHVlKio=\"><span class='gt_from_md'><strong>p-value</strong></span></span></th>\n    </tr>\n  </thead>\n  <tbody class=\"gt_table_body\">\n    <tr><td headers=\"label\" class=\"gt_row gt_left\">(Intercept)</td>\n<td headers=\"estimate_1\" class=\"gt_row gt_center\">8.2</td>\n<td headers=\"conf.low_1\" class=\"gt_row gt_center\">8.2, 8.2</td>\n<td headers=\"p.value_1\" class=\"gt_row gt_center\" style=\"font-weight: bold;\"><0.001</td>\n<td headers=\"estimate_2\" class=\"gt_row gt_center\">8.4</td>\n<td headers=\"conf.low_2\" class=\"gt_row gt_center\">8.3, 8.4</td>\n<td headers=\"p.value_2\" class=\"gt_row gt_center\" style=\"font-weight: bold;\"><0.001</td>\n<td headers=\"estimate_3\" class=\"gt_row gt_center\">8.4</td>\n<td headers=\"conf.low_3\" class=\"gt_row gt_center\">8.3, 8.4</td>\n<td headers=\"p.value_3\" class=\"gt_row gt_center\" style=\"font-weight: bold;\"><0.001</td></tr>\n    <tr><td headers=\"label\" class=\"gt_row gt_left\">Female</td>\n<td headers=\"estimate_1\" class=\"gt_row gt_center\">-0.40</td>\n<td headers=\"conf.low_1\" class=\"gt_row gt_center\">-0.46, -0.34</td>\n<td headers=\"p.value_1\" class=\"gt_row gt_center\" style=\"font-weight: bold;\"><0.001</td>\n<td headers=\"estimate_2\" class=\"gt_row gt_center\">-0.43</td>\n<td headers=\"conf.low_2\" class=\"gt_row gt_center\">-0.48, -0.37</td>\n<td headers=\"p.value_2\" class=\"gt_row gt_center\" style=\"font-weight: bold;\"><0.001</td>\n<td headers=\"estimate_3\" class=\"gt_row gt_center\">-0.43</td>\n<td headers=\"conf.low_3\" class=\"gt_row gt_center\">-0.48, -0.37</td>\n<td headers=\"p.value_3\" class=\"gt_row gt_center\" style=\"font-weight: bold;\"><0.001</td></tr>\n    <tr><td headers=\"label\" class=\"gt_row gt_left\">Education (years, centered)</td>\n<td headers=\"estimate_1\" class=\"gt_row gt_center\">0.08</td>\n<td headers=\"conf.low_1\" class=\"gt_row gt_center\">0.07, 0.09</td>\n<td headers=\"p.value_1\" class=\"gt_row gt_center\" style=\"font-weight: bold;\"><0.001</td>\n<td headers=\"estimate_2\" class=\"gt_row gt_center\">0.05</td>\n<td headers=\"conf.low_2\" class=\"gt_row gt_center\">0.04, 0.06</td>\n<td headers=\"p.value_2\" class=\"gt_row gt_center\" style=\"font-weight: bold;\"><0.001</td>\n<td headers=\"estimate_3\" class=\"gt_row gt_center\">0.06</td>\n<td headers=\"conf.low_3\" class=\"gt_row gt_center\">0.04, 0.07</td>\n<td headers=\"p.value_3\" class=\"gt_row gt_center\" style=\"font-weight: bold;\"><0.001</td></tr>\n    <tr><td headers=\"label\" class=\"gt_row gt_left\">Experience (decades, centered)</td>\n<td headers=\"estimate_1\" class=\"gt_row gt_center\">0.17</td>\n<td headers=\"conf.low_1\" class=\"gt_row gt_center\">0.13, 0.20</td>\n<td headers=\"p.value_1\" class=\"gt_row gt_center\" style=\"font-weight: bold;\"><0.001</td>\n<td headers=\"estimate_2\" class=\"gt_row gt_center\">0.15</td>\n<td headers=\"conf.low_2\" class=\"gt_row gt_center\">0.12, 0.19</td>\n<td headers=\"p.value_2\" class=\"gt_row gt_center\" style=\"font-weight: bold;\"><0.001</td>\n<td headers=\"estimate_3\" class=\"gt_row gt_center\">0.16</td>\n<td headers=\"conf.low_3\" class=\"gt_row gt_center\">0.12, 0.19</td>\n<td headers=\"p.value_3\" class=\"gt_row gt_center\" style=\"font-weight: bold;\"><0.001</td></tr>\n    <tr><td headers=\"label\" class=\"gt_row gt_left\">Experience squared</td>\n<td headers=\"estimate_1\" class=\"gt_row gt_center\">-0.07</td>\n<td headers=\"conf.low_1\" class=\"gt_row gt_center\">-0.11, -0.04</td>\n<td headers=\"p.value_1\" class=\"gt_row gt_center\" style=\"font-weight: bold;\"><0.001</td>\n<td headers=\"estimate_2\" class=\"gt_row gt_center\">-0.07</td>\n<td headers=\"conf.low_2\" class=\"gt_row gt_center\">-0.10, -0.03</td>\n<td headers=\"p.value_2\" class=\"gt_row gt_center\" style=\"font-weight: bold;\"><0.001</td>\n<td headers=\"estimate_3\" class=\"gt_row gt_center\">-0.07</td>\n<td headers=\"conf.low_3\" class=\"gt_row gt_center\">-0.10, -0.03</td>\n<td headers=\"p.value_3\" class=\"gt_row gt_center\" style=\"font-weight: bold;\"><0.001</td></tr>\n    <tr><td headers=\"label\" class=\"gt_row gt_left\">Semi-white-collar</td>\n<td headers=\"estimate_1\" class=\"gt_row gt_center\"><br /></td>\n<td headers=\"conf.low_1\" class=\"gt_row gt_center\"><br /></td>\n<td headers=\"p.value_1\" class=\"gt_row gt_center\"><br /></td>\n<td headers=\"estimate_2\" class=\"gt_row gt_center\">-0.14</td>\n<td headers=\"conf.low_2\" class=\"gt_row gt_center\">-0.21, -0.08</td>\n<td headers=\"p.value_2\" class=\"gt_row gt_center\" style=\"font-weight: bold;\"><0.001</td>\n<td headers=\"estimate_3\" class=\"gt_row gt_center\">-0.15</td>\n<td headers=\"conf.low_3\" class=\"gt_row gt_center\">-0.21, -0.08</td>\n<td headers=\"p.value_3\" class=\"gt_row gt_center\" style=\"font-weight: bold;\"><0.001</td></tr>\n    <tr><td headers=\"label\" class=\"gt_row gt_left\">Semi-blue-collar</td>\n<td headers=\"estimate_1\" class=\"gt_row gt_center\"><br /></td>\n<td headers=\"conf.low_1\" class=\"gt_row gt_center\"><br /></td>\n<td headers=\"p.value_1\" class=\"gt_row gt_center\"><br /></td>\n<td headers=\"estimate_2\" class=\"gt_row gt_center\">-0.28</td>\n<td headers=\"conf.low_2\" class=\"gt_row gt_center\">-0.36, -0.19</td>\n<td headers=\"p.value_2\" class=\"gt_row gt_center\" style=\"font-weight: bold;\"><0.001</td>\n<td headers=\"estimate_3\" class=\"gt_row gt_center\">-0.26</td>\n<td headers=\"conf.low_3\" class=\"gt_row gt_center\">-0.34, -0.18</td>\n<td headers=\"p.value_3\" class=\"gt_row gt_center\" style=\"font-weight: bold;\"><0.001</td></tr>\n    <tr><td headers=\"label\" class=\"gt_row gt_left\">Elementary</td>\n<td headers=\"estimate_1\" class=\"gt_row gt_center\"><br /></td>\n<td headers=\"conf.low_1\" class=\"gt_row gt_center\"><br /></td>\n<td headers=\"p.value_1\" class=\"gt_row gt_center\"><br /></td>\n<td headers=\"estimate_2\" class=\"gt_row gt_center\">-0.38</td>\n<td headers=\"conf.low_2\" class=\"gt_row gt_center\">-0.48, -0.28</td>\n<td headers=\"p.value_2\" class=\"gt_row gt_center\" style=\"font-weight: bold;\"><0.001</td>\n<td headers=\"estimate_3\" class=\"gt_row gt_center\">-0.39</td>\n<td headers=\"conf.low_3\" class=\"gt_row gt_center\">-0.49, -0.28</td>\n<td headers=\"p.value_3\" class=\"gt_row gt_center\" style=\"font-weight: bold;\"><0.001</td></tr>\n    <tr><td headers=\"label\" class=\"gt_row gt_left\">Numeracy (z-score)</td>\n<td headers=\"estimate_1\" class=\"gt_row gt_center\"><br /></td>\n<td headers=\"conf.low_1\" class=\"gt_row gt_center\"><br /></td>\n<td headers=\"p.value_1\" class=\"gt_row gt_center\"><br /></td>\n<td headers=\"estimate_2\" class=\"gt_row gt_center\">0.06</td>\n<td headers=\"conf.low_2\" class=\"gt_row gt_center\">0.03, 0.09</td>\n<td headers=\"p.value_2\" class=\"gt_row gt_center\" style=\"font-weight: bold;\"><0.001</td>\n<td headers=\"estimate_3\" class=\"gt_row gt_center\">0.08</td>\n<td headers=\"conf.low_3\" class=\"gt_row gt_center\">0.04, 0.12</td>\n<td headers=\"p.value_3\" class=\"gt_row gt_center\" style=\"font-weight: bold;\"><0.001</td></tr>\n    <tr><td headers=\"label\" class=\"gt_row gt_left\">Female x Education</td>\n<td headers=\"estimate_1\" class=\"gt_row gt_center\"><br /></td>\n<td headers=\"conf.low_1\" class=\"gt_row gt_center\"><br /></td>\n<td headers=\"p.value_1\" class=\"gt_row gt_center\"><br /></td>\n<td headers=\"estimate_2\" class=\"gt_row gt_center\"><br /></td>\n<td headers=\"conf.low_2\" class=\"gt_row gt_center\"><br /></td>\n<td headers=\"p.value_2\" class=\"gt_row gt_center\"><br /></td>\n<td headers=\"estimate_3\" class=\"gt_row gt_center\">-0.01</td>\n<td headers=\"conf.low_3\" class=\"gt_row gt_center\">-0.03, 0.01</td>\n<td headers=\"p.value_3\" class=\"gt_row gt_center\">0.2</td></tr>\n    <tr><td headers=\"label\" class=\"gt_row gt_left\">Female x Numeracy</td>\n<td headers=\"estimate_1\" class=\"gt_row gt_center\"><br /></td>\n<td headers=\"conf.low_1\" class=\"gt_row gt_center\"><br /></td>\n<td headers=\"p.value_1\" class=\"gt_row gt_center\"><br /></td>\n<td headers=\"estimate_2\" class=\"gt_row gt_center\"><br /></td>\n<td headers=\"conf.low_2\" class=\"gt_row gt_center\"><br /></td>\n<td headers=\"p.value_2\" class=\"gt_row gt_center\"><br /></td>\n<td headers=\"estimate_3\" class=\"gt_row gt_center\">-0.06</td>\n<td headers=\"conf.low_3\" class=\"gt_row gt_center\">-0.12, 0.00</td>\n<td headers=\"p.value_3\" class=\"gt_row gt_center\">0.068</td></tr>\n  </tbody>\n  <tfoot class=\"gt_sourcenotes\">\n    <tr>\n      <td class=\"gt_sourcenote\" colspan=\"10\"><span data-qmd-base64=\"QWJicmV2aWF0aW9uOiBDSSA9IENvbmZpZGVuY2UgSW50ZXJ2YWw=\"><span class='gt_from_md'>Abbreviation: CI = Confidence Interval</span></span></td>\n    </tr>\n  </tfoot>\n  \n</table>\n</div>\n```\n\n:::\n:::\n\n\n::: {.callout-tip}\n## Writing Tip\nA combined regression table is the standard way to present nested models. It\nallows the reader to see at a glance how coefficients change as new predictors\nare added. Always include confidence intervals (or standard errors) and\nsignificance indicators.\n:::\n\n\n### Collinearity Diagnostics {#sec-linear-ex-vif}\n\nWe check for multicollinearity by computing variance inflation factors (VIFs)\nfor the full model (Model 3).\n\n\n::: {#tbl-vif .cell tbl-cap='Variance Inflation Factors for Model 3'}\n\n```{.r .cell-code}\ncar::vif(model3) |>\n  as.data.frame() |>\n  setNames(\"VIF\") |>\n  knitr::kable(digits = 2)\n```\n\n::: {.cell-output-display}\n\n\n|             |  VIF|\n|:------------|----:|\n|female       | 1.28|\n|schyrs_c     | 3.13|\n|exper_c      | 1.20|\n|exper2_c     | 1.07|\n|semiwhite    | 1.55|\n|semiblue     | 1.82|\n|elementary   | 1.59|\n|numeracy     | 2.42|\n|fem_schyrs_c | 2.52|\n|fem_numeracy | 2.26|\n\n\n:::\n:::\n\n\nAll VIF values are well below 5 (the highest is about 3.1 for `schyrs_c`),\nindicating that multicollinearity is not a concern in this analysis. Even the\ninteraction terms (`fem_schyrs_c`, `fem_numeracy`) have modest VIFs, which is\nexpected because we used mean-centered predictors to construct the\ninteractions.\n\n::: {.callout-note}\n## VIF Guidelines\n- VIF < 5: No concern\n- VIF 5--10: Moderate concern; consider whether centering or combining\n  predictors might help\n- VIF > 10: Serious multicollinearity problem; the affected coefficients may\n  be unstable\n:::\n\n\n### Residual Diagnostics {#sec-linear-ex-residuals}\n\nWe assess the regression assumptions by examining residual plots for Model 3\n(the most complex model).\n\n#### Histogram and Q--Q Plot of Residuals\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Extract residuals\nresid_df <- data.frame(\n  residuals = residuals(model3),\n  fitted    = fitted(model3),\n  std_resid = rstandard(model3)\n)\n\np_hist <- ggplot(resid_df, aes(x = residuals)) +\n  geom_histogram(bins = 30, fill = ber640_colors[\"accent\"],\n                 color = \"white\", alpha = 0.8) +\n  labs(x = \"Residuals\", y = \"Count\",\n       title = \"Histogram of Residuals\")\n\np_qq <- ggplot(resid_df, aes(sample = std_resid)) +\n  stat_qq(alpha = 0.3, color = ber640_colors[\"primary\"]) +\n  stat_qq_line(color = ber640_colors[\"secondary\"], linewidth = 0.8) +\n  labs(x = \"Theoretical quantiles\", y = \"Standardized residuals\",\n       title = \"Q-Q Plot\")\n\np_hist + p_qq\n```\n\n::: {.cell-output-display}\n![Normality Assessment of Residuals (Model 3)](ch05-linear-results_files/figure-html/fig-residual-hist-qq-1.png){#fig-residual-hist-qq fig-alt='Two-panel diagnostic display. The histogram of residuals shows an approximately symmetric, bell-shaped distribution with slight heavy tails. The Q-Q plot shows points closely following the diagonal reference line with minor deviations in the tails, indicating approximate normality.' width=2100}\n:::\n:::\n\n\nThe residual histogram is approximately symmetric and bell-shaped, with\nslight heavy tails. The Q--Q plot shows that most points follow the diagonal\nline closely, with some deviation in the tails. This is typical for earnings\ndata and does not pose a serious threat to inference given the large sample\nsize ($N = 1{,}357$).\n\n#### Residuals vs. Fitted Values\n\n\n::: {.cell}\n\n```{.r .cell-code}\nggplot(resid_df, aes(x = fitted, y = residuals)) +\n  geom_point(alpha = 0.15, color = ber640_colors[\"primary\"]) +\n  geom_hline(yintercept = 0, linetype = \"dashed\",\n             color = ber640_colors[\"secondary\"]) +\n  geom_smooth(method = \"loess\", se = FALSE,\n              color = ber640_colors[\"accent\"], linewidth = 0.8) +\n  labs(\n    x = \"Fitted values\",\n    y = \"Residuals\",\n    title = \"Residuals vs. Fitted Values\",\n    subtitle = \"Checking linearity and homoscedasticity\"\n  )\n```\n\n::: {.cell-output-display}\n![Residuals vs. Fitted Values (Model 3)](ch05-linear-results_files/figure-html/fig-residual-fitted-1.png){#fig-residual-fitted fig-alt='Scatterplot of residuals versus fitted values showing a random scatter of points around the horizontal zero line with no systematic pattern. The LOESS smooth is approximately flat near zero, supporting the linearity and homoscedasticity assumptions.' width=2100}\n:::\n:::\n\n\nThe residuals-vs-fitted plot shows no obvious systematic pattern. The LOESS\nsmooth is approximately flat around zero, suggesting that the linearity\nassumption is reasonable. The spread of residuals is roughly constant across\nfitted values, supporting the homoscedasticity assumption.\n\n#### Comprehensive Diagnostics with `performance::check_model()`\n\nFor a comprehensive view, we can also use the `performance` package's\ndiagnostic suite.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nperformance::check_model(\n  model3,\n  check = c(\"linearity\", \"homogeneity\", \"qq\", \"outliers\")\n)\n```\n\n::: {.cell-output-display}\n![Comprehensive Residual Diagnostics (Model 3)](ch05-linear-results_files/figure-html/fig-check-model-1.png){#fig-check-model fig-alt='Four-panel diagnostic suite from the performance package showing linearity check, homogeneity of variance, Q-Q plot of residuals, and outlier detection. All panels indicate that regression assumptions are reasonably well met with no evidence of serious violations.' width=2700}\n:::\n:::\n\n\n**Overall assessment:** The regression assumptions are reasonably well met.\nThere is no evidence of serious nonlinearity, heteroscedasticity, or\nproblematic outliers. The slight heavy-tailedness in the residual distribution\nis minor and unlikely to affect our conclusions given the sample size.\n\n\n## Part 6: Discussion {#sec-linear-ex-part6}\n\n::: {.callout-important}\n## Guideline Reminder --- Part 6\nSummarize your key findings, answer each research question directly, discuss\nat least 2--3 limitations, and note implications. This is where you show\nthat you understand what the numbers mean.\n:::\n\n### Summary of Key Findings {#sec-linear-ex-findings}\n\nThis study examined the determinants of monthly earnings among Korean\nfull-time workers using a series of nested linear regression models applied\nto PIAAC Korea data ($N = 1{,}357$). The results yield three main findings.\n\n**RQ1: Returns to education and experience.** Consistent with the Mincer\nearnings function, both years of education and work experience are\nsignificant predictors of log-income. Each additional year of education is\nassociated with approximately an 8.4% increase in monthly income in the\nbaseline model (Model 1), which decreases to about 4.8% after controlling\nfor occupation and numeracy (Model 2). Work experience shows the expected\nconcave (diminishing-returns) pattern: income rises with experience but at a\ndecreasing rate. Together, the traditional Mincer variables explain about\n39.5% of the variance in log-income.\n\n**RQ2: Added value of cognitive skills and occupation.** Occupational\nclassification and numeracy proficiency add significant explanatory power\nbeyond the traditional Mincer variables ($\\Delta R^2 = .040$,\n$F(4, 1348) = 23.99$, $p < .001$). The occupational dummies reveal a clear\nearnings hierarchy: relative to skilled workers, semi-white-collar workers\nearn about 13% less, semi-blue-collar workers earn about 24% less, and\nelementary workers earn about 31% less. Importantly, numeracy proficiency is\na significant predictor even after controlling for years of education and\noccupation: a one-SD increase in numeracy is associated with approximately a\n6.1% increase in income. This suggests that what workers *know* matters for\nearnings above and beyond how long they attended school.\n\n**RQ3: Gender differences in returns.** The interaction terms between gender\nand education ($p = .160$) and gender and numeracy ($p = .068$) are not\nindividually significant at $\\alpha = .05$. The returns to education and\ncognitive skills appear to be broadly similar for men and women. The gender\ngap in earnings operates primarily as a *level* difference: women earn\napproximately 33--35% less than men across all three models, and this gap\npersists regardless of education, experience, occupation, or cognitive\nskills.\n\n### The Persistent Gender Gap {#sec-linear-ex-gender-gap}\n\nOne of the most striking findings is the large and persistent gender gap.\nThe `female` coefficient is around $-0.40$ to $-0.43$ across all three\nmodels, corresponding to roughly a 33--35% earnings disadvantage for women\ncompared with men who have the same education, experience, occupation, and\ncognitive skills. This finding is consistent with the well-documented gender\nwage gap in South Korea, which is among the largest in the OECD. The fact\nthat the gap barely changes as we add controls suggests that it is not\nexplained by differences in human capital or occupational sorting --- it\nlikely reflects structural factors such as discrimination, career\ninterruptions, or within-occupation segregation that our model cannot capture.\n\n### Limitations {#sec-linear-ex-limitations}\n\nSeveral limitations should be noted when interpreting these results.\n\n1. **Cross-sectional design.** Because PIAAC is a cross-sectional survey, we\n   cannot establish causal relationships. The associations between education\n   and earnings, for example, may partly reflect selection effects (e.g.,\n   more able individuals obtain more education *and* earn more) rather than a\n   true causal return to schooling.\n\n2. **Single-country sample.** Our analysis focuses on South Korea, which has\n   distinctive features (very high educational attainment, large gender wage\n   gap, specific labor market institutions). The findings may not generalize\n   to other countries or cultural contexts.\n\n3. **Selection bias.** By restricting the sample to full-time workers aged\n   35--54, we exclude part-time workers, the unemployed, and those outside the\n   labor force. This sample selection may bias our estimates, particularly for\n   the gender gap, because women are disproportionately represented among\n   nonworkers and part-time workers.\n\n4. **Self-reported earnings.** Monthly income in PIAAC is self-reported and\n   may contain measurement error. However, the log transformation helps\n   reduce the influence of extreme values.\n\n### Implications {#sec-linear-ex-implications}\n\nDespite these limitations, the findings have practical implications for\neducation policy and workforce development:\n\n- The significant association between numeracy and earnings, above and beyond years of education,\n  suggests that policies focused solely on increasing educational attainment\n  (e.g., expanding college access) may be insufficient. Programs that develop\n  *actual cognitive skills* could have meaningful returns in the labor market.\n- The persistent gender earnings gap, even after extensive controls, points\n  to the need for structural interventions such as anti-discrimination\n  policies, family leave reforms, and workplace culture changes.\n- The clear occupational earnings hierarchy highlights the importance of\n  occupational counseling and training programs for workers in lower-tier\n  occupations.\n\n\n## Submission Checklist {#sec-linear-ex-checklist}\n\n::: {.callout-important}\n## Part 5 Submission Checklist\nBefore submitting your Results & Discussion write-up, confirm that you have\ncompleted all of the following:\n\n- [ ] **Descriptive statistics** for all continuous variables (mean, SD, min,\n  max) and frequency tables for categorical variables\n- [ ] **Exploratory visualizations** (histograms, scatterplots, boxplots)\n  with written interpretations\n- [ ] **Regression models** fitted and summarized (show `summary()` output\n  or a publication-style table)\n- [ ] **Coefficient interpretation** for every predictor --- direction,\n  magnitude, significance, and substantive meaning\n- [ ] **Model comparison** using $F$-tests or $R^2$ changes to evaluate\n  incremental contributions\n- [ ] **Assumption diagnostics** (residual plots, VIF) with a brief\n  assessment of whether assumptions are met\n- [ ] **Discussion** that answers each research question, notes limitations,\n  and discusses implications\n- [ ] All code runs without errors (`eval: true` for all code chunks)\n- [ ] All figures and tables are labeled, captioned, and cross-referenced\n:::\n",
    "supporting": [
      "ch05-linear-results_files"
    ],
    "filters": [
      "rmarkdown/pagebreak.lua"
    ],
    "includes": {},
    "engineDependencies": {},
    "preserve": {},
    "postProcess": true
  }
}