{
  "hash": "5eb02e2ac3bf5441fca7981a0325b6e6",
  "result": {
    "engine": "knitr",
    "markdown": "---\ntitle: \"Lab 11: Review --- Logistic Regression & Linear Diagnostics\"\n---\n\n\n\n\n## Goals\n\n::: {.callout-note}\n## What You'll Learn in This Lab\n- Review logistic regression with categorical predictors (3+ levels)\n- Fit and interpret a multiple logistic regression model\n- Create predicted probability curves for male vs. female passengers\n- Review the complete linear regression diagnostic checklist from Lab 8\n- Use `performance::check_model()` as a one-stop diagnostic dashboard\n- **Lecture Notes Reference:** Chapters 8–11 (Review)\n:::\n\n**Datasets:** `titanic` and `hsbs1` from the `regdatasets` package\n\nThis is a **review lab**. We revisit two major topics from the course --- logistic regression (Labs 9--10) and linear regression diagnostics (Lab 8) --- and tie them together. Think of it as a dress rehearsal for your final analysis.\n\n\n## Setup\n\n\n::: {.cell}\n\n```{.r .cell-code}\nlibrary(regdatasets)\ndata(titanic)\ndata(hsbs1)\n\n# Rename sex to female (already coded 0 = male, 1 = female)\ntitanic <- titanic |>\n  rename(female = sex)\n\n# Prepare hsbs1 variables (same as Lab 8)\nhsbs1 <- hsbs1 |>\n  mutate(\n    male   = if_else(gender == 1, 1L, 0L),\n    prog_f = factor(prog,\n                    levels = 1:3,\n                    labels = c(\"General\", \"Academic\", \"Vocational\"))\n  )\n\nglimpse(titanic)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nRows: 1,309\nColumns: 6\n$ pclass   <int> 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1…\n$ survived <int> 1, 1, 0, 0, 0, 1, 1, 0, 1, 0, 0, 1, 1, 1, 1, 0, 0, 1, 1, 0, 1…\n$ age      <dbl> 29.0000, 0.9167, 2.0000, 30.0000, 25.0000, 48.0000, 63.0000, …\n$ fare     <dbl> 211.3375, 151.5500, 151.5500, 151.5500, 151.5500, 26.5500, 77…\n$ embarked <chr> \"S\", \"S\", \"S\", \"S\", \"S\", \"S\", \"S\", \"S\", \"C\", \"C\", \"C\", \"C\", \"…\n$ female   <int> 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 0, 1, 1, 1, 0, 0, 0, 1, 1, 0, 0…\n```\n\n\n:::\n\n```{.r .cell-code}\nglimpse(hsbs1)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nRows: 350\nColumns: 18\n$ id      <int> 303, 404, 225, 553, 433, 189, 336, 321, 358, 422, 461, 593, 34…\n$ gender  <int> 2, 2, 1, 1, 2, 2, 1, 1, 2, 2, 1, 1, 2, 2, 2, 1, 2, 2, 2, 2, 2,…\n$ race    <int> 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 1, 4, 4, 4, 4,…\n$ ses     <int> 1, 2, 2, 2, 2, 3, 3, 1, 3, 2, 1, 2, 2, 3, 1, 3, 3, 2, 1, 3, 1,…\n$ sch     <int> 1, 1, 1, 2, 1, 1, 1, 1, 1, 1, 1, 2, 1, 2, 1, 2, 2, 1, 1, 1, 1,…\n$ prog    <int> 1, 1, 2, 2, 3, 2, 1, 3, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 1, 2, 2,…\n$ locus   <dbl> -0.84, -0.38, 0.89, 0.71, -0.64, 1.11, 0.06, -0.91, 0.45, 0.00…\n$ concept <dbl> -0.24, -0.47, 0.59, 0.28, 0.03, 0.90, 0.03, -0.59, 0.03, 0.03,…\n$ mot     <dbl> 1.00, 0.67, 0.67, 0.67, 1.00, 0.33, 0.67, 0.67, 1.00, 0.67, 0.…\n$ career  <int> 4, 4, 6, 16, 4, 6, 11, 8, 4, 9, 16, 11, 9, 1, 9, 9, 9, 15, 5, …\n$ read    <dbl> 54.8, 62.7, 60.6, 62.7, 41.6, 62.7, 41.6, 44.2, 62.7, 62.7, 70…\n$ write   <dbl> 64.5, 43.7, 56.7, 56.7, 46.3, 64.5, 39.1, 39.1, 51.5, 64.5, 43…\n$ math    <dbl> 44.5, 44.7, 70.5, 54.7, 38.4, 61.4, 56.3, 46.3, 54.4, 38.3, 58…\n$ sci     <dbl> 52.6, 52.6, 58.0, 58.0, 36.3, 58.0, 45.0, 36.3, 49.8, 55.8, 66…\n$ ss      <dbl> 50.6, 41.9, 65.5, 40.6, 45.6, 60.5, 50.6, 40.6, 50.6, 55.6, 60…\n$ sample  <int> 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,…\n$ male    <int> 0, 0, 1, 1, 0, 0, 1, 1, 0, 0, 1, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0,…\n$ prog_f  <fct> General, General, Academic, Academic, Vocational, Academic, Ge…\n```\n\n\n:::\n:::\n\n\n\n## Part 1: Logistic Regression Review (Titanic)\n\nLet's warm up by revisiting a few models from Labs 9 and 10. We will move quickly here since you have seen all of this before.\n\n### Step 1: Gender and Survival\n\n\n::: {.cell}\n\n```{.r .cell-code}\nmodel_female <- glm(survived ~ female, data = titanic, family = binomial)\nexp(coef(model_female))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n(Intercept)      female \n  0.2360704  11.3071844 \n```\n\n\n:::\n\n```{.r .cell-code}\nexp(confint(model_female))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n                2.5 %     97.5 %\n(Intercept) 0.1981912  0.2794823\nfemale      8.6871038 14.8093675\n```\n\n\n:::\n:::\n\n\n> Females had roughly 11.3 times the odds of surviving compared to males, and the 95% CI is comfortably above 1. No surprise --- we have seen this result several times now.\n\n### Step 2: Fare (Standardized)\n\nRemember the interpretation problem with fare? A one-pound change is tiny. Standardizing makes the OR meaningful:\n\n\n::: {.cell}\n\n```{.r .cell-code}\ntitanic <- titanic |>\n  mutate(z_fare = (fare - mean(fare, na.rm = TRUE)) / sd(fare, na.rm = TRUE))\n\nmodel_z_fare <- glm(survived ~ z_fare, data = titanic, family = binomial)\nexp(coef(model_z_fare))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n(Intercept)      z_fare \n  0.6263744   1.9051038 \n```\n\n\n:::\n\n```{.r .cell-code}\nexp(confint(model_z_fare))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n               2.5 %   97.5 %\n(Intercept) 0.557585 0.703113\nz_fare      1.629489 2.257161\n```\n\n\n:::\n:::\n\n\n> A one SD increase in fare (about 52 pounds) is associated with an OR of roughly 1.91. Higher fare, higher odds of survival.\n\n### Step 3: Passenger Class (3 Levels)\n\n\n::: {.cell}\n\n```{.r .cell-code}\ntitanic <- titanic |>\n  mutate(pclass_f = factor(pclass, labels = c(\"1st\", \"2nd\", \"3rd\")))\n\nmodel_pclass <- glm(survived ~ pclass_f, data = titanic, family = binomial)\n```\n:::\n\n\n:::: {.panel-tabset}\n\n#### Simple\n\n\n::: {.cell}\n\n```{.r .cell-code}\nsummary(model_pclass)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\nCall:\nglm(formula = survived ~ pclass_f, family = binomial, data = titanic)\n\nCoefficients:\n            Estimate Std. Error z value Pr(>|z|)    \n(Intercept)   0.4861     0.1146   4.242 2.21e-05 ***\npclass_f2nd  -0.7696     0.1669  -4.611 4.02e-06 ***\npclass_f3rd  -1.5567     0.1433 -10.860  < 2e-16 ***\n---\nSignif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1\n\n(Dispersion parameter for binomial family taken to be 1)\n\n    Null deviance: 1741.0  on 1308  degrees of freedom\nResidual deviance: 1613.3  on 1306  degrees of freedom\nAIC: 1619.3\n\nNumber of Fisher Scoring iterations: 4\n```\n\n\n:::\n\n```{.r .cell-code}\nexp(coef(model_pclass))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n(Intercept) pclass_f2nd pclass_f3rd \n  1.6260163   0.4631962   0.2108239 \n```\n\n\n:::\n:::\n\n\n#### Advanced\n\n\n::: {.cell}\n\n```{.r .cell-code}\nmodel_pclass |>\n  tbl_regression(exponentiate = TRUE) |>\n  bold_labels() |>\n  bold_p(t = 0.05)\n```\n\n::: {.cell-output-display}\n\n```{=html}\n<div id=\"wvuffnbtjm\" style=\"padding-left:0px;padding-right:0px;padding-top:10px;padding-bottom:10px;overflow-x:auto;overflow-y:auto;width:auto;height:auto;\">\n<style>#wvuffnbtjm table {\n  font-family: system-ui, 'Segoe UI', Roboto, Helvetica, Arial, sans-serif, 'Apple Color Emoji', 'Segoe UI Emoji', 'Segoe UI Symbol', 'Noto Color Emoji';\n  -webkit-font-smoothing: antialiased;\n  -moz-osx-font-smoothing: grayscale;\n}\n\n#wvuffnbtjm thead, #wvuffnbtjm tbody, #wvuffnbtjm tfoot, #wvuffnbtjm tr, #wvuffnbtjm td, #wvuffnbtjm th {\n  border-style: none;\n}\n\n#wvuffnbtjm p {\n  margin: 0;\n  padding: 0;\n}\n\n#wvuffnbtjm .gt_table {\n  display: table;\n  border-collapse: collapse;\n  line-height: normal;\n  margin-left: auto;\n  margin-right: auto;\n  color: #333333;\n  font-size: 16px;\n  font-weight: normal;\n  font-style: normal;\n  background-color: #FFFFFF;\n  width: auto;\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #A8A8A8;\n  border-right-style: none;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #A8A8A8;\n  border-left-style: none;\n  border-left-width: 2px;\n  border-left-color: #D3D3D3;\n}\n\n#wvuffnbtjm .gt_caption {\n  padding-top: 4px;\n  padding-bottom: 4px;\n}\n\n#wvuffnbtjm .gt_title {\n  color: #333333;\n  font-size: 125%;\n  font-weight: initial;\n  padding-top: 4px;\n  padding-bottom: 4px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-bottom-color: #FFFFFF;\n  border-bottom-width: 0;\n}\n\n#wvuffnbtjm .gt_subtitle {\n  color: #333333;\n  font-size: 85%;\n  font-weight: initial;\n  padding-top: 3px;\n  padding-bottom: 5px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-top-color: #FFFFFF;\n  border-top-width: 0;\n}\n\n#wvuffnbtjm .gt_heading {\n  background-color: #FFFFFF;\n  text-align: center;\n  border-bottom-color: #FFFFFF;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n}\n\n#wvuffnbtjm .gt_bottom_border {\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n}\n\n#wvuffnbtjm .gt_col_headings {\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n}\n\n#wvuffnbtjm .gt_col_heading {\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: normal;\n  text-transform: inherit;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n  vertical-align: bottom;\n  padding-top: 5px;\n  padding-bottom: 6px;\n  padding-left: 5px;\n  padding-right: 5px;\n  overflow-x: hidden;\n}\n\n#wvuffnbtjm .gt_column_spanner_outer {\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: normal;\n  text-transform: inherit;\n  padding-top: 0;\n  padding-bottom: 0;\n  padding-left: 4px;\n  padding-right: 4px;\n}\n\n#wvuffnbtjm .gt_column_spanner_outer:first-child {\n  padding-left: 0;\n}\n\n#wvuffnbtjm .gt_column_spanner_outer:last-child {\n  padding-right: 0;\n}\n\n#wvuffnbtjm .gt_column_spanner {\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  vertical-align: bottom;\n  padding-top: 5px;\n  padding-bottom: 5px;\n  overflow-x: hidden;\n  display: inline-block;\n  width: 100%;\n}\n\n#wvuffnbtjm .gt_spanner_row {\n  border-bottom-style: hidden;\n}\n\n#wvuffnbtjm .gt_group_heading {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: initial;\n  text-transform: inherit;\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n  vertical-align: middle;\n  text-align: left;\n}\n\n#wvuffnbtjm .gt_empty_group_heading {\n  padding: 0.5px;\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: initial;\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  vertical-align: middle;\n}\n\n#wvuffnbtjm .gt_from_md > :first-child {\n  margin-top: 0;\n}\n\n#wvuffnbtjm .gt_from_md > :last-child {\n  margin-bottom: 0;\n}\n\n#wvuffnbtjm .gt_row {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  margin: 10px;\n  border-top-style: solid;\n  border-top-width: 1px;\n  border-top-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n  vertical-align: middle;\n  overflow-x: hidden;\n}\n\n#wvuffnbtjm .gt_stub {\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: initial;\n  text-transform: inherit;\n  border-right-style: solid;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#wvuffnbtjm .gt_stub_row_group {\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: initial;\n  text-transform: inherit;\n  border-right-style: solid;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n  padding-left: 5px;\n  padding-right: 5px;\n  vertical-align: top;\n}\n\n#wvuffnbtjm .gt_row_group_first td {\n  border-top-width: 2px;\n}\n\n#wvuffnbtjm .gt_row_group_first th {\n  border-top-width: 2px;\n}\n\n#wvuffnbtjm .gt_summary_row {\n  color: #333333;\n  background-color: #FFFFFF;\n  text-transform: inherit;\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#wvuffnbtjm .gt_first_summary_row {\n  border-top-style: solid;\n  border-top-color: #D3D3D3;\n}\n\n#wvuffnbtjm .gt_first_summary_row.thick {\n  border-top-width: 2px;\n}\n\n#wvuffnbtjm .gt_last_summary_row {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n}\n\n#wvuffnbtjm .gt_grand_summary_row {\n  color: #333333;\n  background-color: #FFFFFF;\n  text-transform: inherit;\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#wvuffnbtjm .gt_first_grand_summary_row {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-top-style: double;\n  border-top-width: 6px;\n  border-top-color: #D3D3D3;\n}\n\n#wvuffnbtjm .gt_last_grand_summary_row_top {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-bottom-style: double;\n  border-bottom-width: 6px;\n  border-bottom-color: #D3D3D3;\n}\n\n#wvuffnbtjm .gt_striped {\n  background-color: rgba(128, 128, 128, 0.05);\n}\n\n#wvuffnbtjm .gt_table_body {\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n}\n\n#wvuffnbtjm .gt_footnotes {\n  color: #333333;\n  background-color: #FFFFFF;\n  border-bottom-style: none;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 2px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n}\n\n#wvuffnbtjm .gt_footnote {\n  margin: 0px;\n  font-size: 90%;\n  padding-top: 4px;\n  padding-bottom: 4px;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#wvuffnbtjm .gt_sourcenotes {\n  color: #333333;\n  background-color: #FFFFFF;\n  border-bottom-style: none;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 2px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n}\n\n#wvuffnbtjm .gt_sourcenote {\n  font-size: 90%;\n  padding-top: 4px;\n  padding-bottom: 4px;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#wvuffnbtjm .gt_left {\n  text-align: left;\n}\n\n#wvuffnbtjm .gt_center {\n  text-align: center;\n}\n\n#wvuffnbtjm .gt_right {\n  text-align: right;\n  font-variant-numeric: tabular-nums;\n}\n\n#wvuffnbtjm .gt_font_normal {\n  font-weight: normal;\n}\n\n#wvuffnbtjm .gt_font_bold {\n  font-weight: bold;\n}\n\n#wvuffnbtjm .gt_font_italic {\n  font-style: italic;\n}\n\n#wvuffnbtjm .gt_super {\n  font-size: 65%;\n}\n\n#wvuffnbtjm .gt_footnote_marks {\n  font-size: 75%;\n  vertical-align: 0.4em;\n  position: initial;\n}\n\n#wvuffnbtjm .gt_asterisk {\n  font-size: 100%;\n  vertical-align: 0;\n}\n\n#wvuffnbtjm .gt_indent_1 {\n  text-indent: 5px;\n}\n\n#wvuffnbtjm .gt_indent_2 {\n  text-indent: 10px;\n}\n\n#wvuffnbtjm .gt_indent_3 {\n  text-indent: 15px;\n}\n\n#wvuffnbtjm .gt_indent_4 {\n  text-indent: 20px;\n}\n\n#wvuffnbtjm .gt_indent_5 {\n  text-indent: 25px;\n}\n\n#wvuffnbtjm .katex-display {\n  display: inline-flex !important;\n  margin-bottom: 0.75em !important;\n}\n\n#wvuffnbtjm div.Reactable > div.rt-table > div.rt-thead > div.rt-tr.rt-tr-group-header > div.rt-th-group:after {\n  height: 0px !important;\n}\n</style>\n<table class=\"gt_table\" data-quarto-disable-processing=\"false\" data-quarto-bootstrap=\"false\">\n  <thead>\n    <tr class=\"gt_col_headings\">\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_left\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"label\"><span data-qmd-base64=\"KipDaGFyYWN0ZXJpc3RpYyoq\"><span class='gt_from_md'><strong>Characteristic</strong></span></span></th>\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_center\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"estimate\"><span data-qmd-base64=\"KipPUioq\"><span class='gt_from_md'><strong>OR</strong></span></span></th>\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_center\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"conf.low\"><span data-qmd-base64=\"Kio5NSUgQ0kqKg==\"><span class='gt_from_md'><strong>95% CI</strong></span></span></th>\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_center\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"p.value\"><span data-qmd-base64=\"KipwLXZhbHVlKio=\"><span class='gt_from_md'><strong>p-value</strong></span></span></th>\n    </tr>\n  </thead>\n  <tbody class=\"gt_table_body\">\n    <tr><td headers=\"label\" class=\"gt_row gt_left\" style=\"font-weight: bold;\">pclass_f</td>\n<td headers=\"estimate\" class=\"gt_row gt_center\"><br /></td>\n<td headers=\"conf.low\" class=\"gt_row gt_center\"><br /></td>\n<td headers=\"p.value\" class=\"gt_row gt_center\"><br /></td></tr>\n    <tr><td headers=\"label\" class=\"gt_row gt_left\">    1st</td>\n<td headers=\"estimate\" class=\"gt_row gt_center\">—</td>\n<td headers=\"conf.low\" class=\"gt_row gt_center\">—</td>\n<td headers=\"p.value\" class=\"gt_row gt_center\"><br /></td></tr>\n    <tr><td headers=\"label\" class=\"gt_row gt_left\">    2nd</td>\n<td headers=\"estimate\" class=\"gt_row gt_center\">0.46</td>\n<td headers=\"conf.low\" class=\"gt_row gt_center\">0.33, 0.64</td>\n<td headers=\"p.value\" class=\"gt_row gt_center\" style=\"font-weight: bold;\"><0.001</td></tr>\n    <tr><td headers=\"label\" class=\"gt_row gt_left\">    3rd</td>\n<td headers=\"estimate\" class=\"gt_row gt_center\">0.21</td>\n<td headers=\"conf.low\" class=\"gt_row gt_center\">0.16, 0.28</td>\n<td headers=\"p.value\" class=\"gt_row gt_center\" style=\"font-weight: bold;\"><0.001</td></tr>\n  </tbody>\n  <tfoot>\n    <tr class=\"gt_sourcenotes\">\n      <td class=\"gt_sourcenote\" colspan=\"4\"><span data-qmd-base64=\"QWJicmV2aWF0aW9uczogQ0kgPSBDb25maWRlbmNlIEludGVydmFsLCBPUiA9IE9kZHMgUmF0aW8=\"><span class='gt_from_md'>Abbreviations: CI = Confidence Interval, OR = Odds Ratio</span></span></td>\n    </tr>\n  </tfoot>\n</table>\n</div>\n```\n\n:::\n:::\n\n\n::::\n\n> With 1st class as the reference, both 2nd and 3rd class passengers had significantly lower odds of survival. Third class passengers fared the worst.\n\n### Step 4: Predicted Probabilities by Class\n\n\n::: {.cell}\n\n```{.r .cell-code}\nem_pclass <- emmeans(model_pclass, ~ pclass_f, type = \"response\")\nem_df <- as.data.frame(em_pclass)\n\nggplot(em_df, aes(x = pclass_f, y = prob)) +\n  geom_point(size = 4, color = ber640_colors[\"secondary\"]) +\n  geom_errorbar(aes(ymin = asymp.LCL, ymax = asymp.UCL),\n                width = 0.15, linewidth = 1, color = ber640_colors[\"secondary\"]) +\n  labs(x = \"Passenger Class\",\n       y = \"Predicted P(Survived)\",\n       title = \"Survival Probability by Passenger Class\",\n       subtitle = \"Error bars show 95% confidence intervals\") +\n  scale_y_continuous(limits = c(0, 1), labels = scales::percent)\n```\n\n::: {.cell-output-display}\n![Predicted survival probability by passenger class](lab11-logistic-diagnostics_files/figure-html/pclass-pred-plot-1.png){fig-alt='Point-and-error-bar plot showing predicted survival probabilities decreasing steeply from 1st to 2nd to 3rd class with non-overlapping confidence intervals' width=2100}\n:::\n:::\n\n\n> The gradient is steep: roughly 63% for 1st class, 47% for 2nd, and 24% for 3rd. These non-overlapping CIs confirm the differences are statistically significant.\n\n\n## Part 2: Multiple Logistic Regression\n\nNow let's combine everything into a single model. This is where logistic regression gets interesting --- we can ask: **controlling for age and class, did gender still matter?**\n\n### Step 1: Fit the Full Model\n\n\n::: {.cell}\n\n```{.r .cell-code}\nmodel_full <- glm(survived ~ female + age + pclass_f,\n                  data = titanic, family = binomial)\n```\n:::\n\n\n:::: {.panel-tabset}\n\n#### Simple\n\n\n::: {.cell}\n\n```{.r .cell-code}\nsummary(model_full)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\nCall:\nglm(formula = survived ~ female + age + pclass_f, family = binomial, \n    data = titanic)\n\nCoefficients:\n             Estimate Std. Error z value Pr(>|z|)    \n(Intercept)  1.024229   0.296280   3.457 0.000546 ***\nfemale       2.497845   0.166037  15.044  < 2e-16 ***\nage         -0.034393   0.006331  -5.433 5.56e-08 ***\npclass_f2nd -1.280570   0.225538  -5.678 1.36e-08 ***\npclass_f3rd -2.289661   0.225802 -10.140  < 2e-16 ***\n---\nSignif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1\n\n(Dispersion parameter for binomial family taken to be 1)\n\n    Null deviance: 1414.62  on 1045  degrees of freedom\nResidual deviance:  982.45  on 1041  degrees of freedom\n  (263 observations deleted due to missingness)\nAIC: 992.45\n\nNumber of Fisher Scoring iterations: 4\n```\n\n\n:::\n:::\n\n\n#### Advanced\n\n\n::: {.cell}\n\n```{.r .cell-code}\nmodel_full |>\n  tbl_regression(exponentiate = TRUE) |>\n  bold_labels() |>\n  bold_p(t = 0.05)\n```\n\n::: {.cell-output-display}\n\n```{=html}\n<div id=\"eaipzxyzks\" style=\"padding-left:0px;padding-right:0px;padding-top:10px;padding-bottom:10px;overflow-x:auto;overflow-y:auto;width:auto;height:auto;\">\n<style>#eaipzxyzks table {\n  font-family: system-ui, 'Segoe UI', Roboto, Helvetica, Arial, sans-serif, 'Apple Color Emoji', 'Segoe UI Emoji', 'Segoe UI Symbol', 'Noto Color Emoji';\n  -webkit-font-smoothing: antialiased;\n  -moz-osx-font-smoothing: grayscale;\n}\n\n#eaipzxyzks thead, #eaipzxyzks tbody, #eaipzxyzks tfoot, #eaipzxyzks tr, #eaipzxyzks td, #eaipzxyzks th {\n  border-style: none;\n}\n\n#eaipzxyzks p {\n  margin: 0;\n  padding: 0;\n}\n\n#eaipzxyzks .gt_table {\n  display: table;\n  border-collapse: collapse;\n  line-height: normal;\n  margin-left: auto;\n  margin-right: auto;\n  color: #333333;\n  font-size: 16px;\n  font-weight: normal;\n  font-style: normal;\n  background-color: #FFFFFF;\n  width: auto;\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #A8A8A8;\n  border-right-style: none;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #A8A8A8;\n  border-left-style: none;\n  border-left-width: 2px;\n  border-left-color: #D3D3D3;\n}\n\n#eaipzxyzks .gt_caption {\n  padding-top: 4px;\n  padding-bottom: 4px;\n}\n\n#eaipzxyzks .gt_title {\n  color: #333333;\n  font-size: 125%;\n  font-weight: initial;\n  padding-top: 4px;\n  padding-bottom: 4px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-bottom-color: #FFFFFF;\n  border-bottom-width: 0;\n}\n\n#eaipzxyzks .gt_subtitle {\n  color: #333333;\n  font-size: 85%;\n  font-weight: initial;\n  padding-top: 3px;\n  padding-bottom: 5px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-top-color: #FFFFFF;\n  border-top-width: 0;\n}\n\n#eaipzxyzks .gt_heading {\n  background-color: #FFFFFF;\n  text-align: center;\n  border-bottom-color: #FFFFFF;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n}\n\n#eaipzxyzks .gt_bottom_border {\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n}\n\n#eaipzxyzks .gt_col_headings {\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n}\n\n#eaipzxyzks .gt_col_heading {\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: normal;\n  text-transform: inherit;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n  vertical-align: bottom;\n  padding-top: 5px;\n  padding-bottom: 6px;\n  padding-left: 5px;\n  padding-right: 5px;\n  overflow-x: hidden;\n}\n\n#eaipzxyzks .gt_column_spanner_outer {\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: normal;\n  text-transform: inherit;\n  padding-top: 0;\n  padding-bottom: 0;\n  padding-left: 4px;\n  padding-right: 4px;\n}\n\n#eaipzxyzks .gt_column_spanner_outer:first-child {\n  padding-left: 0;\n}\n\n#eaipzxyzks .gt_column_spanner_outer:last-child {\n  padding-right: 0;\n}\n\n#eaipzxyzks .gt_column_spanner {\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  vertical-align: bottom;\n  padding-top: 5px;\n  padding-bottom: 5px;\n  overflow-x: hidden;\n  display: inline-block;\n  width: 100%;\n}\n\n#eaipzxyzks .gt_spanner_row {\n  border-bottom-style: hidden;\n}\n\n#eaipzxyzks .gt_group_heading {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: initial;\n  text-transform: inherit;\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n  vertical-align: middle;\n  text-align: left;\n}\n\n#eaipzxyzks .gt_empty_group_heading {\n  padding: 0.5px;\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: initial;\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  vertical-align: middle;\n}\n\n#eaipzxyzks .gt_from_md > :first-child {\n  margin-top: 0;\n}\n\n#eaipzxyzks .gt_from_md > :last-child {\n  margin-bottom: 0;\n}\n\n#eaipzxyzks .gt_row {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  margin: 10px;\n  border-top-style: solid;\n  border-top-width: 1px;\n  border-top-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n  vertical-align: middle;\n  overflow-x: hidden;\n}\n\n#eaipzxyzks .gt_stub {\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: initial;\n  text-transform: inherit;\n  border-right-style: solid;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#eaipzxyzks .gt_stub_row_group {\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: initial;\n  text-transform: inherit;\n  border-right-style: solid;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n  padding-left: 5px;\n  padding-right: 5px;\n  vertical-align: top;\n}\n\n#eaipzxyzks .gt_row_group_first td {\n  border-top-width: 2px;\n}\n\n#eaipzxyzks .gt_row_group_first th {\n  border-top-width: 2px;\n}\n\n#eaipzxyzks .gt_summary_row {\n  color: #333333;\n  background-color: #FFFFFF;\n  text-transform: inherit;\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#eaipzxyzks .gt_first_summary_row {\n  border-top-style: solid;\n  border-top-color: #D3D3D3;\n}\n\n#eaipzxyzks .gt_first_summary_row.thick {\n  border-top-width: 2px;\n}\n\n#eaipzxyzks .gt_last_summary_row {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n}\n\n#eaipzxyzks .gt_grand_summary_row {\n  color: #333333;\n  background-color: #FFFFFF;\n  text-transform: inherit;\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#eaipzxyzks .gt_first_grand_summary_row {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-top-style: double;\n  border-top-width: 6px;\n  border-top-color: #D3D3D3;\n}\n\n#eaipzxyzks .gt_last_grand_summary_row_top {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-bottom-style: double;\n  border-bottom-width: 6px;\n  border-bottom-color: #D3D3D3;\n}\n\n#eaipzxyzks .gt_striped {\n  background-color: rgba(128, 128, 128, 0.05);\n}\n\n#eaipzxyzks .gt_table_body {\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n}\n\n#eaipzxyzks .gt_footnotes {\n  color: #333333;\n  background-color: #FFFFFF;\n  border-bottom-style: none;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 2px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n}\n\n#eaipzxyzks .gt_footnote {\n  margin: 0px;\n  font-size: 90%;\n  padding-top: 4px;\n  padding-bottom: 4px;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#eaipzxyzks .gt_sourcenotes {\n  color: #333333;\n  background-color: #FFFFFF;\n  border-bottom-style: none;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 2px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n}\n\n#eaipzxyzks .gt_sourcenote {\n  font-size: 90%;\n  padding-top: 4px;\n  padding-bottom: 4px;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#eaipzxyzks .gt_left {\n  text-align: left;\n}\n\n#eaipzxyzks .gt_center {\n  text-align: center;\n}\n\n#eaipzxyzks .gt_right {\n  text-align: right;\n  font-variant-numeric: tabular-nums;\n}\n\n#eaipzxyzks .gt_font_normal {\n  font-weight: normal;\n}\n\n#eaipzxyzks .gt_font_bold {\n  font-weight: bold;\n}\n\n#eaipzxyzks .gt_font_italic {\n  font-style: italic;\n}\n\n#eaipzxyzks .gt_super {\n  font-size: 65%;\n}\n\n#eaipzxyzks .gt_footnote_marks {\n  font-size: 75%;\n  vertical-align: 0.4em;\n  position: initial;\n}\n\n#eaipzxyzks .gt_asterisk {\n  font-size: 100%;\n  vertical-align: 0;\n}\n\n#eaipzxyzks .gt_indent_1 {\n  text-indent: 5px;\n}\n\n#eaipzxyzks .gt_indent_2 {\n  text-indent: 10px;\n}\n\n#eaipzxyzks .gt_indent_3 {\n  text-indent: 15px;\n}\n\n#eaipzxyzks .gt_indent_4 {\n  text-indent: 20px;\n}\n\n#eaipzxyzks .gt_indent_5 {\n  text-indent: 25px;\n}\n\n#eaipzxyzks .katex-display {\n  display: inline-flex !important;\n  margin-bottom: 0.75em !important;\n}\n\n#eaipzxyzks div.Reactable > div.rt-table > div.rt-thead > div.rt-tr.rt-tr-group-header > div.rt-th-group:after {\n  height: 0px !important;\n}\n</style>\n<table class=\"gt_table\" data-quarto-disable-processing=\"false\" data-quarto-bootstrap=\"false\">\n  <thead>\n    <tr class=\"gt_col_headings\">\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_left\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"label\"><span data-qmd-base64=\"KipDaGFyYWN0ZXJpc3RpYyoq\"><span class='gt_from_md'><strong>Characteristic</strong></span></span></th>\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_center\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"estimate\"><span data-qmd-base64=\"KipPUioq\"><span class='gt_from_md'><strong>OR</strong></span></span></th>\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_center\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"conf.low\"><span data-qmd-base64=\"Kio5NSUgQ0kqKg==\"><span class='gt_from_md'><strong>95% CI</strong></span></span></th>\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_center\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"p.value\"><span data-qmd-base64=\"KipwLXZhbHVlKio=\"><span class='gt_from_md'><strong>p-value</strong></span></span></th>\n    </tr>\n  </thead>\n  <tbody class=\"gt_table_body\">\n    <tr><td headers=\"label\" class=\"gt_row gt_left\" style=\"font-weight: bold;\">female</td>\n<td headers=\"estimate\" class=\"gt_row gt_center\">12.2</td>\n<td headers=\"conf.low\" class=\"gt_row gt_center\">8.83, 16.9</td>\n<td headers=\"p.value\" class=\"gt_row gt_center\" style=\"font-weight: bold;\"><0.001</td></tr>\n    <tr><td headers=\"label\" class=\"gt_row gt_left\" style=\"font-weight: bold;\">age in years</td>\n<td headers=\"estimate\" class=\"gt_row gt_center\">0.97</td>\n<td headers=\"conf.low\" class=\"gt_row gt_center\">0.95, 0.98</td>\n<td headers=\"p.value\" class=\"gt_row gt_center\" style=\"font-weight: bold;\"><0.001</td></tr>\n    <tr><td headers=\"label\" class=\"gt_row gt_left\" style=\"font-weight: bold;\">pclass_f</td>\n<td headers=\"estimate\" class=\"gt_row gt_center\"><br /></td>\n<td headers=\"conf.low\" class=\"gt_row gt_center\"><br /></td>\n<td headers=\"p.value\" class=\"gt_row gt_center\"><br /></td></tr>\n    <tr><td headers=\"label\" class=\"gt_row gt_left\">    1st</td>\n<td headers=\"estimate\" class=\"gt_row gt_center\">—</td>\n<td headers=\"conf.low\" class=\"gt_row gt_center\">—</td>\n<td headers=\"p.value\" class=\"gt_row gt_center\"><br /></td></tr>\n    <tr><td headers=\"label\" class=\"gt_row gt_left\">    2nd</td>\n<td headers=\"estimate\" class=\"gt_row gt_center\">0.28</td>\n<td headers=\"conf.low\" class=\"gt_row gt_center\">0.18, 0.43</td>\n<td headers=\"p.value\" class=\"gt_row gt_center\" style=\"font-weight: bold;\"><0.001</td></tr>\n    <tr><td headers=\"label\" class=\"gt_row gt_left\">    3rd</td>\n<td headers=\"estimate\" class=\"gt_row gt_center\">0.10</td>\n<td headers=\"conf.low\" class=\"gt_row gt_center\">0.06, 0.16</td>\n<td headers=\"p.value\" class=\"gt_row gt_center\" style=\"font-weight: bold;\"><0.001</td></tr>\n  </tbody>\n  <tfoot>\n    <tr class=\"gt_sourcenotes\">\n      <td class=\"gt_sourcenote\" colspan=\"4\"><span data-qmd-base64=\"QWJicmV2aWF0aW9uczogQ0kgPSBDb25maWRlbmNlIEludGVydmFsLCBPUiA9IE9kZHMgUmF0aW8=\"><span class='gt_from_md'>Abbreviations: CI = Confidence Interval, OR = Odds Ratio</span></span></td>\n    </tr>\n  </tfoot>\n</table>\n</div>\n```\n\n:::\n:::\n\n\n::::\n\n### Step 2: Interpret the Odds Ratios\n\n\n::: {.cell}\n\n```{.r .cell-code}\nexp(coef(model_full))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n(Intercept)      female         age pclass_f2nd pclass_f3rd \n  2.7849484  12.1562649   0.9661915   0.2778789   0.1013008 \n```\n\n\n:::\n\n```{.r .cell-code}\nexp(confint(model_full))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n                2.5 %     97.5 %\n(Intercept) 1.5661786  5.0108579\nfemale      8.8252557 16.9295216\nage         0.9541052  0.9781055\npclass_f2nd 0.1776342  0.4303922\npclass_f3rd 0.0645310  0.1565287\n```\n\n\n:::\n:::\n\n\n> Let's walk through each predictor:\n>\n> - **female:** Controlling for age and class, females had about 12.2 times the odds of survival compared to males. Gender mattered enormously even after accounting for other factors.\n> - **age:** Each additional year of age is associated with an OR of about 0.966. Older passengers had slightly lower odds of survival, all else equal.\n> - **2nd class vs. 1st class:** The OR of 0.28 tells us 2nd class passengers had lower odds than 1st class, controlling for gender and age.\n> - **3rd class vs. 1st class:** An OR of 0.1 --- third class passengers had dramatically lower odds of survival than first class, even after adjusting for gender and age.\n\n::: {.callout-tip}\n## The \"Controlling For\" Interpretation\nIn multiple logistic regression, each OR represents the effect of that predictor **holding all other predictors constant**. So when we say females had higher odds of survival, we mean comparing a female and male passenger of the same age and same class.\n:::\n\n### Step 3: Predicted Probability Curves --- Male vs. Female\n\nThis is the payoff plot. We show how the predicted probability of survival changes with age, separately for males and females, within each passenger class.\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Create prediction grid\nnew_data <- expand.grid(\n  age      = seq(1, 70, length.out = 100),\n  female   = c(0, 1),\n  pclass_f = factor(c(\"1st\", \"2nd\", \"3rd\"))\n)\n\n# Get predictions on the link scale for proper CIs\npreds <- predict(model_full, newdata = new_data, type = \"link\", se.fit = TRUE)\n\nnew_data <- new_data |>\n  mutate(\n    prob    = plogis(preds$fit),\n    ci_low  = plogis(preds$fit - 1.96 * preds$se.fit),\n    ci_high = plogis(preds$fit + 1.96 * preds$se.fit),\n    gender_label = if_else(female == 1, \"Female\", \"Male\")\n  )\n\nggplot(new_data, aes(x = age, y = prob, color = gender_label, fill = gender_label)) +\n  geom_ribbon(aes(ymin = ci_low, ymax = ci_high), alpha = 0.15, color = NA) +\n  geom_line(linewidth = 1.2) +\n  facet_wrap(~ pclass_f) +\n  scale_color_manual(values = c(\"Female\" = ber640_colors[\"secondary\"],\n                                \"Male\"   = ber640_colors[\"accent\"])) +\n  scale_fill_manual(values = c(\"Female\" = ber640_colors[\"secondary\"],\n                               \"Male\"   = ber640_colors[\"accent\"])) +\n  labs(x = \"Age\", y = \"Predicted P(Survived)\",\n       color = \"Gender\", fill = \"Gender\",\n       title = \"Survival Probability by Age, Gender, and Class\",\n       subtitle = \"Shaded bands show 95% confidence intervals\") +\n  scale_y_continuous(limits = c(0, 1), labels = scales::percent)\n```\n\n::: {.cell-output-display}\n![Predicted probability of survival by age, gender, and passenger class](lab11-logistic-diagnostics_files/figure-html/pred-curves-gender-1.png){fig-alt='Three-panel faceted plot by passenger class showing S-shaped survival probability curves for females and males, with females consistently higher and the class gradient showing dramatic decline from 1st to 3rd class' width=3000}\n:::\n:::\n\n\n> Three things jump out. First, females had much higher survival probabilities than males at every age and in every class. Second, older passengers had lower probabilities than younger ones. Third, the class gradient is massive --- a young female in 1st class had near-certain survival odds, while an older male in 3rd class had very low odds.\n\n\n## Part 3: Linear Regression Diagnostics Review (hsbs1)\n\nNow we switch gears entirely. We return to the `hsbs1` dataset from Lab 8 and run through the **complete diagnostic checklist** one more time. Think of this as a compact reference you can come back to for any regression analysis.\n\n**Research Question:** *Is there a difference in science achievement between males and females, controlling for math, reading, and course track?*\n\n### Step 1: Fit the Model\n\n\n::: {.cell}\n\n```{.r .cell-code}\nmodel_lm <- lm(sci ~ math + read + male + prog_f, data = hsbs1)\ntidy_model(model_lm)\n```\n\n::: {.cell-output-display}\n<div class=\"kable-table\">\n\n|term             | estimate| std.error| statistic| p.value| conf.low| conf.high|\n|:----------------|--------:|---------:|---------:|-------:|--------:|---------:|\n|(Intercept)      |  10.2329|    2.4225|    4.2241|  0.0000|   5.4681|   14.9976|\n|math             |   0.3565|    0.0566|    6.3007|  0.0000|   0.2452|    0.4677|\n|read             |   0.4492|    0.0503|    8.9277|  0.0000|   0.3502|    0.5481|\n|male             |   2.3663|    0.7230|    3.2729|  0.0012|   0.9442|    3.7883|\n|prog_fAcademic   |  -1.3406|    0.9465|   -1.4163|  0.1576|  -3.2022|    0.5211|\n|prog_fVocational |  -1.5292|    1.0255|   -1.4911|  0.1368|  -3.5462|    0.4879|\n\n</div>\n:::\n:::\n\n\n> Same model as Lab 8. Now let's blitz through the diagnostics.\n\n### Step 2: Compute Residuals\n\n\n::: {.cell}\n\n```{.r .cell-code}\nhsbs1 <- hsbs1 |>\n  mutate(\n    resid_rstud = rstudent(model_lm),\n    fitted_vals = fitted(model_lm)\n  )\n```\n:::\n\n\nWe use **studentized deleted residuals** (`rstudent`) because they are the best at catching outliers --- each residual is computed from a model that excludes that observation.\n\n### Diagnostic 1: Normality\n\n::: {.panel-tabset}\n\n#### Histogram\n\n\n::: {.cell}\n\n```{.r .cell-code}\nggplot(hsbs1, aes(x = resid_rstud)) +\n  geom_histogram(aes(y = after_stat(density)),\n                 bins = 25, fill = ber640_colors[\"primary\"], color = \"white\") +\n  stat_function(fun = dnorm, color = ber640_colors[\"secondary\"],\n                linewidth = 1.2) +\n  labs(x = \"Studentized Deleted Residual\", y = \"Density\",\n       title = \"Normality Check: Histogram\")\n```\n\n::: {.cell-output-display}\n![Histogram of studentized deleted residuals](lab11-logistic-diagnostics_files/figure-html/diag-normality-hist-1.png){fig-alt='Histogram of studentized deleted residuals with normal density overlay, showing approximately bell-shaped distribution consistent with normality' width=2100}\n:::\n:::\n\n\n#### QQ Plot\n\n\n::: {.cell}\n\n```{.r .cell-code}\nggplot(hsbs1, aes(sample = resid_rstud)) +\n  stat_qq(alpha = 0.4, color = ber640_colors[\"primary\"]) +\n  stat_qq_line(color = ber640_colors[\"secondary\"], linewidth = 1.2) +\n  labs(x = \"Theoretical Quantiles\", y = \"Sample Quantiles\",\n       title = \"Normality Check: QQ Plot\")\n```\n\n::: {.cell-output-display}\n![QQ plot of studentized deleted residuals](lab11-logistic-diagnostics_files/figure-html/diag-normality-qq-1.png){fig-alt='QQ plot of studentized deleted residuals with points falling close to the diagonal reference line, indicating approximate normality' width=1800}\n:::\n:::\n\n\n:::\n\n> Points fall close to the diagonal line in the QQ plot, and the histogram looks roughly bell-shaped. Normality looks fine.\n\n### Diagnostic 2: Constant Variance\n\n\n::: {.cell}\n\n```{.r .cell-code}\nggplot(hsbs1, aes(x = fitted_vals, y = resid_rstud)) +\n  geom_point(alpha = 0.3, size = 2, color = ber640_colors[\"primary\"]) +\n  geom_hline(yintercept = 0, color = ber640_colors[\"secondary\"], linewidth = 1) +\n  geom_smooth(method = \"loess\", se = FALSE, color = ber640_colors[\"accent\"],\n              linewidth = 1.2, linetype = \"dashed\") +\n  labs(x = \"Fitted Values\", y = \"Studentized Deleted Residual\",\n       title = \"Constant Variance Check\",\n       subtitle = \"Look for a fan or funnel shape\")\n```\n\n::: {.cell-output-display}\n![Residuals vs. fitted values](lab11-logistic-diagnostics_files/figure-html/diag-variance-1.png){fig-alt='Residuals versus fitted values plot with LOWESS curve near zero and roughly constant spread, indicating no severe heteroscedasticity' width=2400}\n:::\n:::\n\n\n> No obvious megaphone pattern. The LOWESS line hovers near zero. Constant variance looks reasonable.\n\n### Diagnostic 3: Linearity (Added-Variable Plots)\n\n\n::: {.cell}\n\n```{.r .cell-code}\ncar::avPlots(model_lm)\n```\n\n::: {.cell-output-display}\n![Added-variable plots for continuous predictors](lab11-logistic-diagnostics_files/figure-html/diag-linearity-1.png){fig-alt='Multi-panel added-variable plots for math, read, male, and program type showing roughly linear partial relationships with science scores' width=3000}\n:::\n:::\n\n\n> Each panel should show a roughly linear cloud. If you see bending or curvature, the linearity assumption for that predictor may be violated. Here, the relationships look linear.\n\n### Diagnostic 4: Collinearity (VIF)\n\n\n::: {.cell}\n\n```{.r .cell-code}\ncar::vif(model_lm)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n           GVIF Df GVIF^(1/(2*Df))\nmath   2.079042  1        1.441888\nread   1.987151  1        1.409664\nmale   1.017984  1        1.008952\nprog_f 1.361543  2        1.080209\n```\n\n\n:::\n:::\n\n\n> All VIF values are well below 5. Math and reading are correlated, but not enough to cause any problems. No collinearity concerns.\n\n### Diagnostic 5: Outliers\n\n\n::: {.cell}\n\n```{.r .cell-code}\nhsbs1 |>\n  filter(abs(resid_rstud) > 3) |>\n  select(id, sci, math, read, male, prog_f, resid_rstud, fitted_vals)\n```\n\n::: {.cell-output-display}\n<div class=\"kable-table\">\n\n|  id|  sci| math| read| male|prog_f     | resid_rstud| fitted_vals|\n|---:|----:|----:|----:|----:|:----------|-----------:|-----------:|\n| 448| 71.5| 57.2| 41.6|    1|Vocational |    3.280997|    50.14372|\n\n</div>\n:::\n:::\n\n\n> Observations with $|\\text{rstudent}| > 3$ are potential outliers. Investigate them --- do not automatically delete. Check whether they are data entry errors or genuinely unusual cases.\n\n::: {.callout-important}\n## The Five-Point Checklist\nEvery linear regression analysis should check:\n\n1. **Normality** --- histogram + QQ plot of studentized deleted residuals\n2. **Constant variance** --- residuals vs. fitted values plot\n3. **Linearity** --- added-variable plots (or residual vs. each predictor)\n4. **Collinearity** --- VIF (worry if > 10, monitor if > 5)\n5. **Outliers** --- $|\\text{rstudent}| > 3$\n:::\n\n### Remedy: Robust Standard Errors\n\nIf constant variance looks questionable (even mildly), robust SE is a good safety net. It does not change the coefficients --- only the standard errors and p-values:\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Original OLS\ntidy_model(model_lm)\n```\n\n::: {.cell-output-display}\n<div class=\"kable-table\">\n\n|term             | estimate| std.error| statistic| p.value| conf.low| conf.high|\n|:----------------|--------:|---------:|---------:|-------:|--------:|---------:|\n|(Intercept)      |  10.2329|    2.4225|    4.2241|  0.0000|   5.4681|   14.9976|\n|math             |   0.3565|    0.0566|    6.3007|  0.0000|   0.2452|    0.4677|\n|read             |   0.4492|    0.0503|    8.9277|  0.0000|   0.3502|    0.5481|\n|male             |   2.3663|    0.7230|    3.2729|  0.0012|   0.9442|    3.7883|\n|prog_fAcademic   |  -1.3406|    0.9465|   -1.4163|  0.1576|  -3.2022|    0.5211|\n|prog_fVocational |  -1.5292|    1.0255|   -1.4911|  0.1368|  -3.5462|    0.4879|\n\n</div>\n:::\n\n```{.r .cell-code}\n# Robust (HC1)\nlmtest::coeftest(model_lm, vcov = sandwich::vcovHC(model_lm, type = \"HC1\"))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\nt test of coefficients:\n\n                  Estimate Std. Error t value  Pr(>|t|)    \n(Intercept)      10.232891   2.297032  4.4548 1.137e-05 ***\nmath              0.356452   0.060374  5.9040 8.511e-09 ***\nread              0.449152   0.053540  8.3891 1.283e-15 ***\nmale              2.366251   0.723273  3.2716  0.001178 ** \nprog_fAcademic   -1.340554   0.944991 -1.4186  0.156924    \nprog_fVocational -1.529178   1.034634 -1.4780  0.140326    \n---\nSignif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1\n```\n\n\n:::\n:::\n\n\n> Compare the standard errors side by side. If they are similar, heteroscedasticity is not a big concern. If they differ substantially, report the robust version.\n\n### Advanced: One-Stop Dashboard\n\nThe `performance` package can produce all diagnostic plots at once:\n\n\n::: {.cell}\n\n```{.r .cell-code}\nperformance::check_model(model_lm)\n```\n\n::: {.cell-output-display}\n![Complete diagnostic dashboard](lab11-logistic-diagnostics_files/figure-html/check-model-dashboard-1.png){fig-alt='Six-panel diagnostic dashboard from performance package showing normality, homoscedasticity, linearity, influential observations, and collinearity checks for the linear regression model' width=3000}\n:::\n:::\n\n\n> This is handy for a quick visual scan, but we recommend understanding each individual plot (which we just did) before relying on the dashboard.\n\n\n## Key Takeaways\n\n::: {.callout-note}\n## What We Reviewed\n\n1. **Logistic regression handles binary outcomes.** Use `glm(family = binomial)` and interpret coefficients as odds ratios via `exp(coef())`. Always report CIs alongside point estimates.\n\n2. **Categorical predictors with 3+ levels** create multiple dummy variables automatically when you use `factor()`. Choose a meaningful reference group with `relevel()`.\n\n3. **Multiple logistic regression** lets you ask \"controlling for\" questions. Each OR represents the effect of one predictor holding all others constant.\n\n4. **Predicted probability plots** are the best way to communicate logistic regression results to a non-technical audience. Use `predict(type = \"link\")` with `plogis()` for proper confidence intervals.\n\n5. **The diagnostic checklist** for linear regression is always the same: normality, constant variance, linearity, collinearity, outliers. Run through all five every time.\n\n6. **Robust standard errors** are your safety net when constant variance is questionable. They adjust SE without changing the point estimates.\n:::\n\n::: {.callout-tip}\n## Connecting Logistic and Linear Regression\nBoth logistic and linear regression follow the same workflow: specify a model, fit it, interpret coefficients, check assumptions. The key difference is the outcome type (binary vs. continuous) and the scale of interpretation (odds ratios vs. raw units). The diagnostic spirit is the same --- before you trust any results, verify that the model's assumptions are reasonable.\n:::\n",
    "supporting": [
      "lab11-logistic-diagnostics_files"
    ],
    "filters": [
      "rmarkdown/pagebreak.lua"
    ],
    "includes": {},
    "engineDependencies": {},
    "preserve": {},
    "postProcess": true
  }
}